### PR TITLE
fix: Do not cache flash messages

### LINKED ISSUE #11799: Flash messages are cached
### Shopware Version

6.7.0.1

### Affected area / extension

Platform(Default)

### Actual behaviour

Flash messages (e.g. success or error notifications) are being stored in the page cache, especially on CMS pages, and are therefore displayed repeatedly to all users who access the cached version of that page.

This leads to unexpected and incorrect behavior, as flash messages are meant to be shown only once and only to the intended user/session.

### Expected behaviour

Flash messages should never be part of the page cache. They should be handled in a session-safe and user-specific way. Caching them causes incorrect and potentially confusing UI behavior.

### How to reproduce

1. Create a CMS page (or use a page that is fully cacheable).
2. Trigger a flash message (e.g. via a controller or form submission that redirects to the CMS page).
3. Open the CMS page – the flash message is shown as expected.
4. Open the same page in a private/incognito browser or with another user – the flash message is still shown.
5. Clear the cache – the flash message disappears.

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by keulinho**
fixes #11799

follow up to https://github.com/shopware/shopware/pull/13973

Addresses the issues mentioned in the other PR

### CODE REVIEW

File: src/Core/Framework/Adapter/Cache/Event/HttpCacheCookieEvent.php [hunk 1]
```diff
@@ -19,7 +19,12 @@ class HttpCacheCookieEvent
 
     public const NOT_CACHEABLE = 'not-cacheable';
 
-    public bool $isCacheable = true;
```
Comment (keulinho) [inline src/Core/Framework/Adapter/Cache/Event/HttpCacheCookieEvent.php:22]: we can keep the old name and rather add `doNotStore()` behaviour? What do you think? so far this is not released so we **could** still change it, but **should** we?

**Comment by keulinho** [comment]
Sorry for rewriting history, but before this was based on the feature branch with a ton of commits on it, with the merge to trunk those commits got squashed and the history here was messed up, therefore i recreated the branch from trunk and applied the single commit i had in here before

File: src/Core/Framework/Adapter/Cache/Event/HttpCacheCookieEvent.php (hunk 1 above)
Comment (keulinho) [reply src/Core/Framework/Adapter/Cache/Event/HttpCacheCookieEvent.php:22]: we kept it with `isCacheable` for now, to not "break" the current behaviour and keep that as is

File: src/Storefront/Framework/Cache/CacheCookieEventSubscriber.php [hunk 2]
```diff
@@ -0,0 +1,76 @@
...
+        // therefore we cannot store the response in the cache
+        // however in general the cache should be used for the next requests
+        if (self::$flashbagWasFilled) {
+            $cookieEvent->doNotStore = true;
+        }
+    }
+
+    public function onKernelRequest(): void
+    {
+        self::$flashbagWasFilled = $this->flashBagFilledForCurrentSession();
```
Comment (keulinho) [inline src/Storefront/Framework/Cache/CacheCookieEventSubscriber.php]: looks like fiddling with the session this early in the stack might be pretty dangerous

i got some esi circular reference errors, some admin requests are taking super long (see integration test fails)

problem is i need to start the session to see if the flashbag is filled, however starting the session has definetly some weird side effects 

maybe it is easier to listen to the flashbag being cleared instead

**Comment by keulinho** [comment]
Somehow this leads to a funny side effect in commercial, where it "magically" re-initializes a session that we already set up in a test case, see: https://github.com/shopware/SwagCommercial/pull/1937

File: src/Core/Framework/Adapter/Session/StatefulFlashBag.php [hunk 3]
```diff
@@ -0,0 +1,112 @@
...
+    public function peekAll(): array
+    {
+        return $this->inner->peekAll();
+    }
+
+    public function get(string $type, array $default = []): array
+    {
+        $result = $this->inner->get($type, $default);
+
+        if ($result === []) {
```
Comment (h1k3r) [inline src/Core/Framework/Adapter/Session/StatefulFlashBag.php]: Is this comparison correct? 🤔

File: src/Core/Framework/Adapter/Session/StatefulFlashBag.php [hunk 4]
```diff
@@ -0,0 +1,112 @@
...
+    }
+
+    public function set(string $type, array|string $messages): void
+    {
+        $this->inner->set($type, $messages);
+    }
+
+    public function peek(string $type, array $default = []): array
+    {
+        return $this->inner->peek($type, $default);
```
Comment (h1k3r) [inline src/Core/Framework/Adapter/Session/StatefulFlashBag.php:38]: Do we need to set `displayedAnyFlashes` flag to true also here?
https://symfony.com/doc/current/session.html#flash-messages
>{% for message in app.session.flashbag.peek('notice') %}

There may be implementations that display messages using peek method (without deleting them).

File: src/Core/Framework/Adapter/Cache/Event/HttpCacheCookieEvent.php [hunk 5]
```diff
@@ -19,8 +19,16 @@ class HttpCacheCookieEvent
...
 
+    /**
+     * @var bool set to false to bypass the cache for further requests, the cache will be passed until this is set to true again for the cache state
+     */
     public bool $isCacheable = true;
 
+    /**
+     * @var bool set to true to not store the current response in the cache, however the cache will be used for further requests
+     */
+    public bool $doNotStore = false;
```
Comment (h1k3r) [inline src/Core/Framework/Adapter/Cache/Event/HttpCacheCookieEvent.php:30]: Not sure that it's clear from comments how the whole logic works (one will lead to setting cookie to non-cacheable state and all further requests will not be cached until cookie value is changed; another marks current response to be not stored in cache, but does not change cookie and allows subsequent requests from the same client to hit the cache). Maybe a bit of rewording or example would be great 🤔

File: src/Core/Framework/Adapter/Session/StatefulFlashBag.php (hunk 3 above)
Comment (keulinho) [reply src/Core/Framework/Adapter/Session/StatefulFlashBag.php]: good catch 👍 

adjusted the tests as well to catch this, i only asserted at the end of the testcase, but in all those testcases they also tested that they get an empty value after the first get, therefore the tests were green 🤦

File: src/Core/Framework/Adapter/Session/StatefulFlashBag.php (hunk 4 above)
Comment (keulinho) [reply src/Core/Framework/Adapter/Session/StatefulFlashBag.php:38]: For our use case that does not matter, because `hasAnyFlashes()` will be true when the flashes are not deleted, and that will not just lead to not storing that response to the cache, but also pass the next request (so the flashes will be shown)

File: src/Core/Framework/Adapter/Cache/Event/HttpCacheCookieEvent.php (hunk 5 above)
Comment (keulinho) [reply src/Core/Framework/Adapter/Cache/Event/HttpCacheCookieEvent.php:30]: add edsome info on what the settings do to the cache cookie, does that make it clearer?

**Review by h1k3r — APPROVED** [review]

**Review by shyim — APPROVED** [review]
