### PR TITLE
fix: Deleting properties fails without error popup when property values are still in use

### LINKED ISSUE #11721: Deleting properties fails without error popup when property values are still in use
### Shopware Version

6.7.1.2

### Affected area / extension

Platform(Default)

### Actual behaviour

When you have properties, of which some property values are still being used, and you try to delete those properties, the deletion will fail silently. The following error happens in the background:

```json
{
    "errors": [
        {
            "code": "1451",
            "status": "500",
            "title": "Internal Server Error",
            "detail": "An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`mkuhlmann_sw67`.`product_configurator_setting`, CONSTRAINT `fk.product_configurator_setting.property_group_option_id` FOREIGN KEY (`property_group_option_id`) REFERENCES `property_group_optio)"
        }
    ]
}
```

### Expected behaviour

An error message would pop up, informing that some property values are still in use

### How to reproduce

- Create properties with some values
- Create a product with variants generated from those values
- Try to delete the properties

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by nguyenquocdaile**
### Solution 

Screenshot 2025-08-08 at 14 03 43

### CODE REVIEW

File: src/Administration/Resources/app/administration/src/module/sw-property/page/sw-property-list/index.js [hunk 1]
```diff
@@ -73,6 +74,10 @@ export default {
 
             return this.propertyRepository.delete(id).then(() => {
                 this.getList();
+            }).catch(() => {
+                this.createNotificationError({
```
Comment (sydinh) [inline src/Administration/Resources/app/administration/src/module/sw-property/page/sw-property-list/index.js]: This addition is good. However, I would rely on an error signal to show this notification. If the property group is in use, an error code/status must be returned along with it.

Comment (sydinh) [reply src/Administration/Resources/app/administration/src/module/sw-property/page/sw-property-list/index.js]: Please add a changelog for the update, too.

**Review by sydinh — CHANGES_REQUESTED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-property/page/sw-property-list/index.js (hunk 1 above)
Comment (sydinh) [reply src/Administration/Resources/app/administration/src/module/sw-property/page/sw-property-list/index.js]: > This addition is good. However, I would rely on an error signal to show this notification. If the property group is in use, an error code/status must be returned along with it.

By doing this, others can show any other error notification in the future if needed.

**Review by nguyenytran — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-property/page/sw-property-list/index.js [hunk 2]
```diff
@@ -71,9 +72,16 @@ export default {
...
-            return this.propertyRepository.delete(id).then(() => {
-                this.getList();
-            });
+            return this.propertyRepository
+                .delete(id)
+                .then(() => {
+                    this.getList();
+                })
+                .catch(() => {
+                    this.createNotificationError({
```
Comment (vienthuong) [inline src/Administration/Resources/app/administration/src/module/sw-property/page/sw-property-list/index.js:97]: There are two approach:

1. please catch if the exception match the pattern "Cannot delete or update a parent row: a foreign key constraint fails" and show this error message
2. Check if the property is used in at least one of product `options` or `properties` and show the notification before calling the delete request

```
criteria.addFilter(Shopware.Data.Criteria.equals('options.groupId', '<deleting_id>'));

// also check for this case
criteria.addFilter(Shopware.Data.Criteria.equals('properties.groupId', '<deleting_id>'));

criteria.setTotalCountMode(0);
criteria.setLimit(1);

productRepository.searchIds(criteria);
```

File: src/Administration/Resources/app/administration/src/module/sw-property/snippet/de.json [hunk 3]
```diff
@@ -17,7 +17,8 @@
       "messageEmpty": "Noch keine Eigenschaften",
       "columnDescription": "Beschreibung",
       "buttonDelete": "Löschen",
-      "textDeleteConfirm": "Möchtest Du die Eigenschaft \"{name}\" wirklich löschen?"
+      "textDeleteConfirm": "Möchtest Du die Eigenschaft \"{name}\" wirklich löschen?",
+      "errorDelete": "The property could not be deleted. It is probably still in use by products."
```
Comment (vienthuong) [inline src/Administration/Resources/app/administration/src/module/sw-property/snippet/de.json]: you can multiple delete right? so it should be in plural form, and it's used by products either, not "probably"

File: changelog/_unreleased/2025-08-08-deleting-properties-fails-without-error-popup-when-property-values-are-still-in-use.md [hunk 4]
```diff
@@ -0,0 +1,9 @@
+---
+title: Deleting properties fails without error popup when property values are still in use
+issue: #11721
+author: Le Nguyen
+author_email: nguyenquocdaile@gmail.com
+author_github: @nguyenquocdaile
+---
+# Administration
+* Changed `onConfirmDelete` method to show error popup when deleting property fails in `src/module/sw-property/page/sw-property-list/index.js`.
```
Comment (marcelbrode) [inline changelog/_unreleased/2025-08-08-deleting-properties-fails-without-error-popup-when-property-values-are-still-in-use.md]:
```suggestion
* Changed `onConfirmDelete` method to show error popup when deleting a property fails in `src/module/sw-property/page/sw-property-list/index.js`.
```

File: src/Administration/Resources/app/administration/src/module/sw-property/page/sw-property-list/index.js [hunk 5]
```diff
@@ -68,11 +73,43 @@ export default {
...
+
         onConfirmDelete(id) {
             this.showDeleteModal = false;
 
-            return this.propertyRepository.delete(id).then(() => {
-                this.getList();
+            return this.productRepository.searchIds(this.usePropertyCriteria(id)).then((result) => {
+                if (result.data.length > 0) {
+                    this.createNotificationError({
+                        message: this.$tc('sw-property.list.errorDelete'),
```
Comment (marcelbrode) [inline src/Administration/Resources/app/administration/src/module/sw-property/page/sw-property-list/index.js]: Please do not re-introduce $tc, use $t instead.

File: src/Administration/Resources/app/administration/src/module/sw-property/page/sw-property-list/index.js [hunk 6]
```diff
@@ -68,11 +73,43 @@ export default {
...
+                    });
+                    return Promise.resolve();
+                }
+
+                return this.propertyRepository
+                    .delete(id)
+                    .then(() => {
```
Comment (marcelbrode) [inline src/Administration/Resources/app/administration/src/module/sw-property/page/sw-property-list/index.js:105]: Wouldn't "finally" make more sense here?

File: src/Administration/Resources/app/administration/src/module/sw-property/snippet/en.json [hunk 7]
```diff
@@ -17,7 +17,8 @@
       "messageEmpty": "No properties yet",
       "columnDescription": "Description",
       "buttonDelete": "Delete",
-      "textDeleteConfirm": "Are you sure you really want to delete the property \"{name}\"?"
+      "textDeleteConfirm": "Are you sure you really want to delete the property \"{name}\"?",
+      "errorDelete": "The property could not be deleted. It is probably still in use by products."
```
Comment (marcelbrode) [inline src/Administration/Resources/app/administration/src/module/sw-property/snippet/en.json]:
```suggestion
      "errorDelete": "Property could not be deleted because it is still in use by products."
```

File: src/Administration/Resources/app/administration/src/module/sw-property/snippet/de.json (hunk 3 above)
Comment (marcelbrode) [inline src/Administration/Resources/app/administration/src/module/sw-property/snippet/de.json]:
```suggestion
      "errorDelete": "Die Eigenschaft konnte nicht gelöscht werden, da sie noch von Produkten verwendet wird."
```

**Review by marcelbrode — CHANGES_REQUESTED** [review]

**Review by vienthuong — APPROVED** [review]

**Review by sydinh — APPROVED** [review]
This is the correct approach with the current data flow 👍🏻

File: src/Administration/Resources/app/administration/src/module/sw-property/page/sw-property-list/index.js (hunk 6 above)
Comment (marcelbrode) [reply src/Administration/Resources/app/administration/src/module/sw-property/page/sw-property-list/index.js:105]: Don't just resolve. If you don't agree, give a proper reasoning. It's not very nice to close it without doing anything.

File: src/Administration/Resources/app/administration/src/module/sw-property/page/sw-property-list/sw-property-list.spec.js [hunk 8]
```diff
@@ -261,4 +261,32 @@ describe('module/sw-property/page/sw-property-list', () => {
...
+    it('should not delete property group if it is in use', async () => {
+        global.activeAclRoles = ['property.deleter'];
+
+        const wrapper = await createWrapper();
+        await flushPromises();
+
+        // Mock productRepository to return results indicating usage
+        wrapper.vm.productRepository.searchIds = jest.fn(() => Promise.resolve({ data: ['some-product-id'], total: 1 }));
+
+        // Mock createNotificationError
```
Comment (marcelbrode) [inline src/Administration/Resources/app/administration/src/module/sw-property/page/sw-property-list/sw-property-list.spec.js]:
```suggestion
```
Everyone can see that without a comment.

File: src/Administration/Resources/app/administration/src/module/sw-property/page/sw-property-list/sw-property-list.spec.js [hunk 9]
```diff
@@ -261,4 +261,32 @@ describe('module/sw-property/page/sw-property-list', () => {
...
         wrapper.vm.searchRankingService.getSearchFieldsByEntity.mockRestore();
     });
+
+    it('should not delete property group if it is in use', async () => {
+        global.activeAclRoles = ['property.deleter'];
+
+        const wrapper = await createWrapper();
+        await flushPromises();
+
+        // Mock productRepository to return results indicating usage
```
Comment (marcelbrode) [inline src/Administration/Resources/app/administration/src/module/sw-property/page/sw-property-list/sw-property-list.spec.js]:
```suggestion
```

File: src/Administration/Resources/app/administration/src/module/sw-property/page/sw-property-list/sw-property-list.spec.js [hunk 10]
```diff
@@ -261,4 +261,32 @@ describe('module/sw-property/page/sw-property-list', () => {
...
+        // Mock createNotificationError
+        wrapper.vm.createNotificationError = jest.fn();
+
+        // Mock propertyRepository.delete to ensure it's not called
+        wrapper.vm.propertyRepository.delete = jest.fn(() => Promise.resolve());
+
+        await wrapper.vm.onConfirmDelete('test-group-id');
+
+        expect(wrapper.vm.createNotificationError).toHaveBeenCalledWith({
+            message: expect.any(String), // Matches the translated error message
```
Comment (marcelbrode) [inline src/Administration/Resources/app/administration/src/module/sw-property/page/sw-property-list/sw-property-list.spec.js]:
```suggestion
            message: expect.any(String),
```
What's with all these superfluous comments?

File: src/Administration/Resources/app/administration/src/module/sw-property/page/sw-property-list/sw-property-list.spec.js [hunk 11]
```diff
@@ -261,4 +261,32 @@ describe('module/sw-property/page/sw-property-list', () => {
...
+        await flushPromises();
+
+        // Mock productRepository to return results indicating usage
+        wrapper.vm.productRepository.searchIds = jest.fn(() => Promise.resolve({ data: ['some-product-id'], total: 1 }));
+
+        // Mock createNotificationError
+        wrapper.vm.createNotificationError = jest.fn();
+
+        // Mock propertyRepository.delete to ensure it's not called
+        wrapper.vm.propertyRepository.delete = jest.fn(() => Promise.resolve());
```
Comment (marcelbrode) [inline src/Administration/Resources/app/administration/src/module/sw-property/page/sw-property-list/sw-property-list.spec.js]: Why not add it to "wrapTestComponent"?

**Review by marcelbrode — DISMISSED** [review]
