### PR TITLE
fix: Elasticsearch list/price percentage ratio dynamic product groups…

### LINKED ISSUE #5899: Elasticsearch list/price percentage ratio dynamic product groups not working
*PHP Version:* 8.3   | *Shopware Version:* 6.5.8.15  | *Affected area / extension:* Platform(Default) 

 ----

*_Actual behaviour:_*

We use Elasticsearch and have created a dynamic product group with the rule "Percentage ratio price/strike price" equal to 0.

In the preview, it shows all products correctly, but in the frontend, products with a strike price are also displayed.

The cache was cleared and the index was completely rebuilt. 
We also deleted the current Elasticsearch index and created a new one -> products still not showing correctly

In the opposite case, with the rule "Percentage ratio price/strike price" "greater than 0", products that do not have a strike price also appear. (occurs less frequently, like the error with equal to 0)

If we deactivate Elasticsearch, everything works as expected.

The issue is probably related to 0/null values ​​that are stored directly with the product in the strike price or in the extended prices and the values ​​are interpreted differently by Elasticsearch here?

The rule (equal to 0) is needed for marketing campaigns in order to be able to exclude strike price items so that they do not receive any further discount and can be displayed in a category.
The rule (greater than 0) is used to display all reduced items in the "Sale" category.
Both are currently unusable because ES does not interpret the rules correctly

*_Expected behaviour:_*

The dynamic product group rule "Percentage ratio price/strike price" works in Elasticsearch as with DAL and fetches the same products.

*_How to reproduce:_*

1. Add products with and without strike prices
2. Add products with advanced prices with and without strike prices
3. Create a dynamic product group and apply the rule "Percentage ratio price/strike price" equal to 0
4. Optional: Add rule "active" = "yes"
5. Optional: Add a rule for a specific category
6. Assign the created dynamic product group to a category
7. See products in the frontend -> everything is fine
8. Activate Elasticsearch and reindex data (es:index, dal:refresh:index)
9. Products with strike prices appear -> wrong

### PR DESCRIPTION
**Pull request by tamvt**

### CODE REVIEW

**Comment by l-stauberg** [comment]
Hey, I tested these changes in a 6.5 environment. It does work with slight adjustments however I noticed an issue. Products with variants do not seem to be affected by these changes. Any Ideas on a fix? I did try to change all strike prices of all variants and see if the filter works but it didn't :/

**Comment by l-stauberg** [comment]
Update to my previous comment: These changes do work normally for regular products. You can simply change the Strikeprice and the filters will work. However if a product with variants gets a new strikeprice thus having a percentage of greater than 0, you need to index the product again in order to see the changes.

**Comment by vienthuong** [comment]
Hi @l-stauberg thanks for spotting the issue, also what is your slight adjustments that you mentioned? would be helpful if we can also apply it in the fix.

**Comment by tamvt** [comment]
Hi @l-stauberg,
That reindex is intended and has nothing to do with this bug. If you have any additional concerns or issues that need evaluation, please feel free to open a new issue for us to evaluate further.
Thank you.

File: tests/unit/Elasticsearch/Framework/DataAbstractionLayer/CriteriaParserTest.php [hunk 1]
```diff
@@ -695,6 +695,71 @@ public static function parseFilterDataProvider(): iterable
                 ],
             ],
         ];
+
+        yield 'EqualsFilter cheapestPrice field' => [
```
Comment (vienthuong) [inline tests/unit/Elasticsearch/Framework/DataAbstractionLayer/CriteriaParserTest.php]:
```suggestion
        yield 'EqualsFilter cheapestPrice field' => [],
        yield 'EqualsFilter cheapestPrice.percentage field' => [],
```

**Comment by l-stauberg** [comment]
> Hi @l-stauberg thanks for spotting the issue, also what is your slight adjustments that you mentioned? would be helpful if we can also apply it in the fix.

The adjustments mentioned were just the renaming of the `constructScriptQuery` function in the CriteriaParser as this function has a different name in the SW 6.5 Build (`constructScriptQueryOrFallback`). I am guessing the issues I'm facing actually don't have anything to do with the changes in this PR, it is likely that the environments used had issues with indexing. I don't know if this helps but here is "my version" of the `parseEqualsFilter` function for SW 6.5:

```php
    private function parseEqualsFilter(EqualsFilter $filter, EntityDefinition $definition, Context $context): BuilderInterface
    {
        if ($this->isCheapestPriceField($filter->getField())) {
            $scriptContent = $this->getScript('cheapest_price_filter');
            $parameters = [
                'params' => array_merge(
                    ['eq' => $filter->getValue() === null ? null : (float) $filter->getValue()],
                    $this->getCheapestPriceParameters($context)
                ),
            ];

            return $this->constructScriptQueryOrFallback($scriptContent, $parameters);
        }

        if ($this->isCheapestPriceField($filter->getField(), true)) {
            $scriptContent = $this->getScript('cheapest_price_percentage_filter');
            $parameters = [
                'params' => array_merge(
                    ['eq' => $filter->getValue() === null ? null : (float) $filter->getValue()],
                    ['accessors' => $this->getCheapestPriceAccessors($context, true)]
                ),
            ];

            return $this->constructScriptQueryOrFallback($scriptContent, $parameters);
        }

        if ($this->keyValueStorage->get(ElasticsearchIndexer::ENABLE_MULTILINGUAL_INDEX_KEY, false)) {
            $fieldName = $this->buildAccessor($definition, $filter->getField(), $context);

            $field = $this->getField($definition, $fieldName);

            if ($filter->getValue() === null) {
                $query = new BoolQuery();

                if ($field instanceof TranslatedField) {
                    foreach ($context->getLanguageIdChain() as $languageId) {
                        $query->add(new ExistsQuery(sprintf('%s.%s', $fieldName, $languageId)), BoolQuery::MUST_NOT);
                    }
                } else {
                    $query->add(new ExistsQuery($fieldName), BoolQuery::MUST_NOT);
                }

                return $this->createNestedQuery($query, $definition, $filter->getField());
            }

            $value = $this->parseValue($definition, $filter, $filter->getValue());
            $query = new TermQuery($fieldName, $value);

            if ($field instanceof TranslatedField) {
                $multiMatchFields = [];

                foreach ($context->getLanguageIdChain() as $languageId) {
                    $multiMatchFields[] = $this->getTranslatedFieldName($fieldName, $languageId);
                }

                $query = new MultiMatchQuery($multiMatchFields, $value, [
                    'type' => 'best_fields',
                ]);
            }

            return $this->createNestedQuery($query, $definition, $filter->getField());
        }

        $fieldName = $this->buildAccessor($definition, $filter->getField(), $context);

        if ($filter->getValue() === null) {
            $query = new BoolQuery();
            $query->add(new ExistsQuery($fieldName), BoolQuery::MUST_NOT);

            return $this->createNestedQuery($query, $definition, $filter->getField());
        }

        $value = $this->parseValue($definition, $filter, $filter->getValue());

        $query = new TermQuery($fieldName, $value);

        return $this->createNestedQuery($query, $definition, $filter->getField());
    }
```

**Comment by l-stauberg** [comment]
I am not sure if this problem is still in the scope. If you say that its not then I'll just create a new issue. 
```php
    public function handle(EntityIndexingMessage $message): void
    {
        $ids = array_values(array_unique(array_filter($message->getData())));

        if (empty($ids)) {
            return;
        }

        $parentIds = $this->filterVariants($ids);
       //...

        if ($message->allow(self::CHEAPEST_PRICE_UPDATER)) {
            Profiler::trace('product:indexer:cheapest-price', function () use ($parentIds, $context): void {
                $this->cheapestPriceUpdater->update($parentIds, $context);
            });
        }
```

Thats the handle function in the `Shopware\Core\Content\Product\DataAbstractionLayer\ProductIndexer`.
The parentIds are passed into the cheapest price updater. The issue with that is that the variants are not being updated when the cheapest price updater is triggered due to the `filterVariants` filtering out the variants if they are updated. Thus resulting in an empty array and not updating the elastic search indexes, therefore the rules will also not apply as the percentages are recalculated and pushed to the DAL but not elasticsearch.

**Review by nguyenytran — APPROVED** [review]

**Comment by tamvt** [comment]
Hi @l-stauberg, 
Thank you for thoroughly investigating the issue. I have updated the merge request to include a dispatch message within the CheapestPriceUpdater. This change will ensure that variants are reindexed whenever there is a change in the variant's cheapest price.

Please feel free to review the updates, and let me know if there are any further questions or feedback.

File: src/Core/Content/Product/DataAbstractionLayer/CheapestPriceUpdater.php [hunk 2]
```diff
@@ -75,13 +81,23 @@ public function update(array $parentIds, Context $context): void
...
                     'accessor' => $accessor,
                     'id' => Uuid::fromHexToBytes($variantId),
                     'version' => $versionId,
                 ]);
             }
         }
+
+        if (!empty($variantIdsUpdated)) {
+            $this->dispatcher->dispatch(new ProductIndexerEvent($variantIdsUpdated, $context, [
+                SeoUrlUpdateListener::PRODUCT_SEO_URL_UPDATER,
```
Comment (mitelg) [inline src/Core/Content/Product/DataAbstractionLayer/CheapestPriceUpdater.php:98]: couldn't we skip more? :thinking:

Comment (vienthuong) [reply src/Core/Content/Product/DataAbstractionLayer/CheapestPriceUpdater.php:98]: certainly, but currently I only see there is one skip event in `\Shopware\Storefront\Framework\Seo\SeoUrlRoute\SeoUrlUpdateListener::updateProductUrls`  so I don't know if we have any other events

**Comment by mromeike** [comment]
Hey @tamvt,

thanks for the quick update on this MR. Just one additional note, since you replied to my colleague, @l-stauberg:

> [...] I have updated the merge request to include a dispatch message within the CheapestPriceUpdater. This change will ensure that variants are reindexed whenever there is a change in the variant's cheapest price. [...]

This should definitely fix the issue with variants not being pushed to ES when their parent changes and updates the cheapest price.

In our specific case, i.e. cheapest price for variants, we would likely still encounter the general limitation from `ProductIndexer::handle()`, where (as mentioned) the `$parentIds` are extracted from the write event, then passed to the `CheapestPriceUpdater::update()`.

Updating a variant product will not update its `cheapest_price` and `cheapest_price_accessor` fields in the database and ES. This change will only be put in place, once the parent product is indexed. But as far as I could see, and our debugging results support this claim, the parent product indexing is not triggered in that case.

So when our customer updates the "strike price" on a variant, it will always only be visible the day after, when the nightly full-index rebuild has happened, unless he also triggers an update for the parent product of said variant.

I'm not sure if this is an intentional limitation here, but for us, it's a showstopper right now, as we have product streams (on product listing pages) with configurations that consider the relative reduction of the price in percent, i.e. if the product 90 EUR and 100 EUR is set as "strike price", the percentage is calculated to `10%`. If that value (coming from `cheapest_price_accessor` in the database) is not updated in ES immediately, the results are not up to date with actual product price data.

Maybe you, @mitelg, have some info on that side, if this limitation is/was intended?

**Comment by vienthuong** [comment]
@mromeike from our debugging:

1. when you update a variant, it will be handled synchronously in \Shopware\Core\Content\Product\DataAbstractionLayer\ProductIndexer::update

2. Its parent indexing message will be dispatched via message queue: https://github.com/shopware/shopware/blob/b3eb537dd8f8ed2c16e4144b71441d21d7ac67bf/src/Core/Content/Product/DataAbstractionLayer/ProductIndexer.php#L117

(in this step, the ProductIndexerEvent of the variantId is also dispatched and data is pushed to ES but cheapest_price_accessor of the variant is not updated yet at this point: https://github.com/shopware/shopware/blob/b3eb537dd8f8ed2c16e4144b71441d21d7ac67bf/src/Core/Content/Product/DataAbstractionLayer/ProductIndexer.php#L242)


3. When the queue handle the above parent's indexing message (\Shopware\Core\Content\Product\DataAbstractionLayer\ProductIndexer::handle), it will then pass to CheapestPriceUpdater with the parentId

4. In this class we update the cheapest_price and cheapest_price_accessor for parent and its variant ids. But it's only save the value into mysql at this point. That why in this PR, we dispatched another ProductIndexerEvent to push the data to ES (via the subscriber \Shopware\Elasticsearch\Product\ProductUpdater::update) so now the ES data of variant is up-to-date

So in conclusion, this claim is not true, the parent product indexing is actually dispatched when you update a variant, you need to setup your worker to handle the message on the queue.

> Updating a variant product will not update its cheapest_price and cheapest_price_accessor fields in the database and ES. This change will only be put in place, once the parent product is indexed. But as far as I could see, and our debugging results support this claim, the parent product indexing is not triggered in that case.


Correct me if i'm wrong, we don't want to update the cheapest_price & cheapest_price_access along other stuff synchronously because it's will be a performance bottleneck when a product with many variants, so we will fetch their parent & variant ids to dispatch ProductIndexingMessage to handle them asynchronously. 

https://github.com/shopware/shopware/blob/b3eb537dd8f8ed2c16e4144b71441d21d7ac67bf/src/Core/Content/Product/DataAbstractionLayer/ProductIndexer.php#L107

**Comment by mromeike** [comment]
Hello @vienthuong, thanks for the detailed explanation.

That's what should be happening, yes. For some reason, this did not happen in our testing yesterday (before the new changes). But I see you reference a newer commit in the comment, while our project runs on 6.5 still. So there might be subtle differences that were not spotted and that could also play into this.

I will suggest internally to apply the newly added changes as patches for our version and to be sure, test in an environment using real data. If that indeed fixes it entirely, all is fine.

And yes, we don't want to write those information synchronously, except for when the parent product is the one being updated. :)

**Comment by mitelg** [comment]
the improvement was introduced with 6.6.8.0
https://github.com/shopware/shopware/commit/4a46c90ca67c75d6c1f3cd6b375a53a96b10dee2

**Review by vienthuong — APPROVED** [review]

**Review by mitelg — APPROVED** [review]
