### PR TITLE
fix: Allow more options for RGB and HSL color functions.

### LINKED ISSUE #12947: Theme compile fails - hsl(), rgba() errors after SCSS Validator update
### Shopware Version

6.7.3.0

### Affected area / extension

Platform(Default)

### Actual behaviour

Since the latest SCSS Validator update, some SCSS functions throw errors.
Affected functions include `hsl()` when using variables and `rgba()` when using variables or hex values.

Example broken values:
```
hsl(hue($sw-border-color), saturation($sw-border-color), 94%)
rgba($sw-border-color, 20%)
rgba(#f1f1f1, 20%)
```

### Expected behaviour

The function have to work because you might want to shade colors and reuse color variables.

### How to reproduce

Paste a broken value in a config field.

### PR DESCRIPTION
**Pull request by Phil23**
Fixes: #12947 

### 1. Why is this change necessary?

The new SCSS validation does not support some combinations for RGB and HSL color functions.

### 2. What does this change do, exactly?

Add support for the following formats:

**RGB and RGBA with hex colors and SCSS variables:**
* `rgb($primary / 0.5)`
* `rgb(#fff / 0.5)`
* `rgba($primary, 0.5)`
* `rgba(#fff, 0.5)`

**RGB and RGBA in combination with SCSS functions:**
* `rgb(red($primary), green($primary), blue($primary))`
* `rgba(red($primary), green($primary), blue($primary), 0.5)`
* `rgba(red($primary), green($primary), blue($primary), alpha($primary))`

**HSL and HSLA in combination with SCSS functions:**
* `hsl(hue($primary), saturation($primary), 94%)`
* `hsl(180deg saturation($primary) lightness($primary)`
* `hsla(hue($primary), saturation($primary), lightness($primary), alpha($primary))`

### 3. Describe each step to reproduce the issue or behaviour.

* Open the theme manager and edit the default theme.
* Add some of the color values mentioned above.
* Validate that the configuration can be saved and the theme can be compiled correctly.

### CODE REVIEW

File: src/Storefront/Theme/Validator/SCSSValidator.php [hunk 1]
```diff
@@ -231,26 +236,47 @@ private static function isHSL(string $hslCode): bool
...
+     * Patterns like `hsla(from <color> H S L A)` are not valid.
      */
     private static function isHSLA(string $hslaCode): bool
     {
         $hue = '(?:360(?:\.0+)?|3[0-5]\d(?:\.\d+)?|[12]\d{2}(?:\.\d+)?|[1-9]?\d(?:\.\d+)?)';
         $percent = '(?:100|[1-9]?\d)%';
         $alpha = '(?:0?\.\d+|1(?:\.0+)?|0|(?:100|[1-9]?\d)%)';
 
+        // SCSS function call pattern (e.g., hue($var), saturation($var))
+        $scssFunction = '[a-z-]+\([^)]+\)';
```
Comment (mitelg) [inline src/Storefront/Theme/Validator/SCSSValidator.php:271]: are those functions like `hue`, `green`, etc predefined by some standard or so? 
I wonder, if we should allow any text here or just those specific names

Comment (Phil23) [reply src/Storefront/Theme/Validator/SCSSValidator.php:271]: I don't want to restrict it too much now, because every time the community comes up with some new syntax or color function that doesn't work. The variables are parsed through the compiler anyway. If it does not crash the compiler, it doesn't matter. It is easier than managing big allow lists.

**Review by BrocksiNet — APPROVED** [review]

**Review by mitelg — APPROVED** [review]
