### PR TITLE
fix: TypeError when _httpCache route attribute contains string

### LINKED ISSUE #14381: TypeError in CacheAttribute after upgrading to 6.7.6.0
### Shopware Version

6.7.6.0

### Affected area / extension

Platform(Default)

### Actual behaviour

After upgrading Shopware to 6.7.6.0, the application throws a TypeError in the HTTP cache system. The error occurs when CacheAttribute::fromAttributeValue() receives a string value (`'true'`) instead of the expected types (CacheAttribute|array|bool|null).
If you open any CMS page, you get a 500 error. It does not happen in homepage.

The application log shows the following error:

`request.CRITICAL: Uncaught PHP Exception TypeError: "Shopware\Core\Framework\Adapter\Cache\Http\CacheAttribute::fromAttributeValue(): Argument #1 ($attributeValue) must be of type Shopware\Core\Framework\Adapter\Cache\Http\CacheAttribute|array|bool|null, string given, called in /project-dir/vendor/shopware/core/Framework/Adapter/Cache/Http/CacheResponseSubscriber.php on line 111" at CacheAttribute.php line 46 {"exception":"[object] (TypeError(code: 0): Shopware\\Core\\Framework\\Adapter\\Cache\\Http\\CacheAttribute::fromAttributeValue(): Argument #1 ($attributeValue) must be of type Shopware\\Core\\Framework\\Adapter\\Cache\\Http\\CacheAttribute|array|bool|null, string given, called in /project-dir/vendor/shopware/core/Framework/Adapter/Cache/Http/CacheResponseSubscriber.php on line 111 at /project-dir/vendor/shopware/core/Framework/Adapter/Cache/Http/CacheAttribute.php:46)"} []`

This issue appears to be related to the HTTP caching rework introduced in version 6.7.6.0, specifically affecting production mode where HTTP cache is active by default.
The problem is environment-specific:

❌ APP_ENV=prod: TypeError occurs
✅ APP_ENV=dev: No error (HTTP cache disabled by default)

I've temporarily patched vendor/shopware/core/Framework/Adapter/Cache/Http/CacheResponseSubscriber.php  to converts string values "true" and "false" to their boolean equivalents before passing them to `fromAttributeValue()`

### Expected behaviour

CMS pages open without errors.

### How to reproduce

- Upgrade Shopware to 6.7.6.0
- Set production mode
- Access any CMS page on the storefront
- Check the application logs and search for a TypeError

### PR DESCRIPTION
**Pull request by h1k3r**
### 1. Why is this change necessary?

When route is defined in xml, `_httpCache` attribute may be string.

### 2. What does this change do, exactly?

Adds support for string and int types (for bc reasons).

### 3. Describe each step to reproduce the issue or behaviour.

Create a route definition like below and try to open page with enabled cache:
```xml
<route id="frontend.demo.page"
       path="/demo/{demoId}"
       methods="GET"
       controller="Shopware\Storefront\Controller\DemoController::index">
    <default key="_httpCache">true</default>
    <default key="_routeScope"><list><string>storefront</string></list></default>
    <default key="_controllerName">demo</default>
    <default key="_controllerAction">index</default>
</route>
```

### 4. Please link to the relevant issues (if any).
- closes https://github.com/shopware/shopware/issues/14381

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have updated developer-facing release notes if this change is **relevant** for external developers:
  - Add a short entry to `RELEASE_INFO-6.<major>.md` under “Upcoming” for informational changes, including the consequences of the change and how it affects external developers.
  - Add an `UPGRADE` section in `UPGRADE-6.<next-major>.md` for breaking changes (what/why/impact/how to adapt).
  - See the [Documenting a Release Process](https://github.com/shopware/shopware/blob/trunk/delivery-process/documenting-a-release.md) for details.
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Core/Framework/Adapter/Cache/Http/CacheAttribute.php [hunk 1]
```diff
@@ -43,8 +43,14 @@ public static function fromArray(array $attributeValue): self
     /**
      * @param CacheAttributeType $attributeValue
      */
-    public static function fromAttributeValue(array|bool|CacheAttribute|null $attributeValue): ?self
+    public static function fromAttributeValue(array|bool|string|int|CacheAttribute|null $attributeValue): ?self
     {
+        if (\is_string($attributeValue)) { // string values can come from XML route definitions
```
Comment (mitelg) [inline src/Core/Framework/Adapter/Cache/Http/CacheAttribute.php]: maybe use `\Symfony\Component\Config\Util\XmlUtils::phpize` or `filter_var($value, \FILTER_VALIDATE_BOOLEAN)` instead?

**Review by mitelg — CHANGES_REQUESTED** [review]

File: src/Core/Framework/Adapter/Cache/Http/CacheAttribute.php (hunk 1 above)
Comment (h1k3r) [reply src/Core/Framework/Adapter/Cache/Http/CacheAttribute.php]: Previous check was like: `if (!$attribute) {}`, where $attribute is mixed. So any validation is effectively bc break. But can add it behind feature flag 🤔

Comment (mitelg) [reply src/Core/Framework/Adapter/Cache/Http/CacheAttribute.php]: I am not sure, if I understand, where you see a BC :thinking: 

before only `array|bool|CacheAttribute|null` were allowed types, not mixed. 

I only thought about making your if/ifelse structure easier to read, because you obviously try to cast something that is string or int to bool

Comment (h1k3r) [reply src/Core/Framework/Adapter/Cache/Http/CacheAttribute.php]: Added filter_val.

**Review by mitelg — APPROVED** [review]

File: src/Core/Framework/Adapter/Cache/Http/CacheAttribute.php (hunk 1 above)
Comment (mitelg) [reply src/Core/Framework/Adapter/Cache/Http/CacheAttribute.php]: nice, much cleaner now :ok_hand:

**Review by keulinho — APPROVED** [review]
