### PR TITLE
fix: product category filter now reflects products from DPG

### LINKED ISSUE #13295: Category filter in admin product overview only considers manually assigned products
### Shopware Version

6.7.3.1

### Affected area / extension

Platform(Default)

### Actual behaviour

The category filter in admin product overview only considers manually assigned products. All products that have been assigned through a category using a dynamic product group are NOT shown. 

### Expected behaviour

Also, products that have been assigned to that category through a dynamic product group should show in the results after filtering 

### How to reproduce

1. Set up dynamic product group
2. Open any kind of category and open "products" tab
3. Set type to "Dynamic product group" and select your dynamic product group.
4. Open product overview and set category filter to that specific category you just assigned the dynamic product group to

Result: No products are shown after filtering (or at least just those that have potentially manually being assigned beforehand)

### PR DESCRIPTION
**Pull request by sydinh**
### 1. Why is this change necessary?

See https://github.com/shopware/shopware/issues/13295

### 2. What does this change do, exactly?

Adjusted the product list category filter so it also matches products that belong to the selected category through product streams, not only through direct category assignment. This change is scoped to the product listing only, so other filter sidebars keep their existing behaviour.

### 3. Describe each step to reproduce the issue or behaviour.

See https://github.com/shopware/shopware/issues/13295

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have updated developer-facing release notes if this change is **relevant** for external developers:
  - Add a short entry to `RELEASE_INFO-6.<major>.md` under “Upcoming” for informational changes, including the consequences of the change and how it affects external developers.
  - Add an `UPGRADE` section in `UPGRADE-6.<next-major>.md` for breaking changes (what/why/impact/how to adapt).
  - See the [Documenting a Release Process](https://github.com/shopware/shopware/blob/trunk/delivery-process/documenting-a-release.md) for details.
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

**Comment by sydinh** [comment]
Fixes https://github.com/shopware/shopware/issues/13295

File: src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-list/index.js [hunk 1]
```diff
@@ -425,12 +425,19 @@ export default {
...
         },
 
-        /**
-         * @deprecated tag:v6.8.0 - Use listing mixin implementation directly
-         */
         updateCriteria(criteria) {
-            // Delegate to listing mixin implementation
-            return Mixin.getByName('listing').methods.updateCriteria.call(this, criteria);
+            const mappedCriteria = criteria.map((filter) => {
+                if (filter.type !== 'equalsAny' || filter.field !== 'categories.id') {
```
Comment (vienthuong) [inline src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-list/index.js]:
```suggestion
                if (filter.field !== 'categories.id' || filter.type !== 'equalsAny') {
```

File: src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-list/index.js [hunk 2]
```diff
@@ -425,12 +425,19 @@ export default {
             this.getList();
         },
 
-        /**
-         * @deprecated tag:v6.8.0 - Use listing mixin implementation directly
-         */
         updateCriteria(criteria) {
```
Comment (rittou) [inline src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-list/index.js:429]: Does it still need the deprecation rule, doesn't it?

Comment (sydinh) [reply src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-list/index.js:429]: No, it's being used again now.

**Review by vienthuong — APPROVED** [review]

**Review by rittou — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-list/index.js [hunk 3]
```diff
@@ -425,12 +425,19 @@ export default {
...
-            // Delegate to listing mixin implementation
-            return Mixin.getByName('listing').methods.updateCriteria.call(this, criteria);
+            const mappedCriteria = criteria.map((filter) => {
```
Comment (nguyenquocdaile) [inline src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-list/index.js]: A meaningful ( purpose ) naming for which criteria is also good

**Review by nguyenquocdaile — APPROVED** [review]

**Review by davidtraum — APPROVED** [review]
Looks good to me. It would be good if you could add a test to to cover the new behavior.

File: src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-list/index.js (hunk 3 above)
Comment (sydinh) [reply src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-list/index.js]: I don't get it 🤔

Comment (nguyenquocdaile) [reply src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-list/index.js]: I mean the name of `mappedCriteria`.

Comment (sydinh) [reply src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-list/index.js]: Yes, it is actually a mapped criteria 😄

**Comment by sydinh** [comment]
I have updated the entire fix due to a bug when product filters got merged from the stored filters. Could you please take a look at it again?

File: src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-list/index.js [hunk 4]
```diff
@@ -425,12 +426,31 @@ export default {
             this.getList();
         },
 
-        /**
-         * @deprecated tag:v6.8.0 - Use listing mixin implementation directly
-         */
         updateCriteria(criteria) {
-            // Delegate to listing mixin implementation
-            return Mixin.getByName('listing').methods.updateCriteria.call(this, criteria);
+            return Mixin.getByName('listing').methods.updateCriteria.call(this, this.normalizeCategoryFilters(criteria));
```
Comment (vienthuong) [inline src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-list/index.js:430]: Maybe another approach is watch the `filterCriteria`

File: src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-list/index.js [hunk 5]
```diff
@@ -425,12 +426,31 @@ export default {
...
+        },
+
+        normalizeCategoryFilters(filters) {
+            const normalizedFilters = filters.map((filter) => this.normalizeCategoryFilter(filter));
+
+            return normalizedFilters.filter((filter, index, currentFilters) => {
```
Comment (vienthuong) [inline src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-list/index.js]: probably something like this could also work

```js
normalizeCategoryFilter(filters) {
  const categoryFilterIndex = filters.findIndex(filter => filter.field === 'categories.id' || filter.type === 'equals');

  if (categoryFilterIndex) {
    const filter = filters[categoryFilterIndex];
    const categoryIds = Array.isArray(filter.value) ? filter.value : filter.value.split('|');

    filters[categoryFilterIndex] = Criteria.multi('OR', [
      filter,
      Criteria.equalsAny('product.streams.categories.id',     categoryIds),
    ]);
  }
}

File: src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-list/index.js (hunk 4 above)
Comment (sydinh) [reply src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-list/index.js:430]: Hi, I basically leverage the updateCriteria() function from the listing mixin. This way allows us to mutate the criteria before passing them down, which is pretty convenient and transparent.

File: src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-list/index.js (hunk 5 above)
Comment (sydinh) [reply src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-list/index.js]: Don't you think the existing approach is more straightforward :)

Comment (vienthuong) [reply src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-list/index.js]: tbh after read it carefully, I don't fully get the existing approach, why we need to .filter, why we need to use JSON.stringify to compare when we can just set the filter by its index (`filters[index] = <new_filter>`).

Comment (sydinh) [reply src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-list/index.js]: updated, thank you 💙

**Review by vienthuong — APPROVED** [review]

**Review by nguyenquocdaile — APPROVED** [review]
