### PR TITLE
fix: Fix customer registration address validation handling

### LINKED ISSUE #11842: [StoreAPI][register] incorrect validation handling
### Shopware Version

6.7

### Affected area / extension

Platform(Default)

### Actual behaviour

Passing incorrect data results in:
- status: 200
- content-type: text/html
- body: nothing

Additionally browser sees at as CORS error, which made me look first in the wrong direction

### Expected behaviour

- status: 400
- content-type: application/json
- validation information what's wrong

### How to reproduce

invoke register endpoint with data
```json
{
  "email": "Estefania_Medhurst95@example.shopware.com",
  "password": "_dySmZ9b_3NllRZ",
  "firstName": "Camryn",
  "lastName": "Nitzsche",
  "storefrontUrl": "http://localhost:5173",
  "billingAddress": "South",
  "acceptedDataProtection": true
}
```

data is generated, address is in incorrect format

### Definition of Done

- [x] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [x] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by SpiGAndromeda**
### 1. Why is this change necessary?

The customer registration endpoint (`/store-api/account/register`) does not properly validate the data types of billing and shipping addresses. When invalid data is provided (e.g., a string instead of an object for addresses), the API returns a 500 Internal Server Error instead of a proper 400 Bad Request with validation errors.

This issue was reported in #11842 and partially addressed in PR #11712, which fixed the false success response but still resulted in 500 errors. This PR completes the fix by adding proper validation constraints.

### 2. What does this change do, exactly?

- Adds explicit type validation for `billingAddress` field requiring `associative_array` type
- Adds validation for `shippingAddress` field allowing either `associative_array` type or `null` value using `AtLeastOneOf` constraint  
- Fixes condition logic to prevent validation builder failures when billing address is not a DataBag but shipping address is null
- Returns proper 400 status code with detailed JSON validation errors instead of 500

### 3. Describe each step to reproduce the issue or behaviour.

1. Send a POST request to `/store-api/account/register` with invalid address data:
```json
{
  "email": "test@example.com",
  "billingAddress": "Just a string instead of an object",
  // ... other required fields
}
```

**Before this fix:** Returns 500 Internal Server Error
**After this fix:** Returns 400 Bad Request with validation error: `VIOLATION::INVALID_TYPE_ERROR`

### 4. Please link to the relevant issues (if any).

- Fixes #11842 
- Completes the fix started in #11712

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: tests/unit/Core/Checkout/Customer/SalesChannel/RegisterRouteTest.php [hunk 1]
```diff
@@ -850,4 +850,106 @@ public function testRegisterWithoutBillingAddressCountryViolation(): void
...
+                $subs = $definition->getSubDefinitions();
+
+                static::assertArrayNotHasKey('billingAddress', $subs);
+
+                $billingAddressConstraints = $definition->getProperty('billingAddress');
+                static::assertCount(1, $billingAddressConstraints);
+
+                $billingAddressConstraint = $billingAddressConstraints[0];
+                static::assertInstanceOf(Type::class, $billingAddressConstraint);
+                static::assertEquals('associative_array', $billingAddressConstraint->type);
```
Comment (mitelg) [inline tests/unit/Core/Checkout/Customer/SalesChannel/RegisterRouteTest.php]:
```suggestion
                static::assertSame('associative_array', $billingAddressConstraint->type);
```

File: tests/unit/Core/Checkout/Customer/SalesChannel/RegisterRouteTest.php [hunk 2]
```diff
@@ -850,4 +850,106 @@ public function testRegisterWithoutBillingAddressCountryViolation(): void
...
+            new CustomerDefinition(),
+        );
+
+        $countryId = Uuid::randomHex();
+
+        $country = new CountryEntity();
+        $country->setId($countryId);
+        $country->setVatIdRequired(true);
+
+        $countryRepository = $this->createMock(SalesChannelRepository::class);
```
Comment (mitelg) [inline tests/unit/Core/Checkout/Customer/SalesChannel/RegisterRouteTest.php]: why not using `StaticEntityRepository` here?

File: tests/unit/Core/Checkout/Customer/SalesChannel/RegisterRouteTest.php [hunk 3]
```diff
@@ -850,4 +850,106 @@ public function testRegisterWithoutBillingAddressCountryViolation(): void
...
+            $countryRepository,
+            $this->createMock(Connection::class),
+            $this->createMock(SalesChannelContextService::class),
+            $this->createMock(StoreApiCustomFieldMapper::class),
+            $this->createMock(EntityRepository::class),
+            $definitionFactory,
+        );
+
+        $salesChannelContext = $this->createMock(SalesChannelContext::class);
+        $salesChannelContext->method('getSalesChannelId')->willReturn(TestDefaults::SALES_CHANNEL);
```
Comment (mitelg) [inline tests/unit/Core/Checkout/Customer/SalesChannel/RegisterRouteTest.php]:
```suggestion
        $salesChannelContext = \Shopware\Core\Test\Generator::generateSalesChannelContext();
```

File: changelog/_unreleased/2025-08-22-fix-customer-registration-address-validation.md [hunk 4]
```diff
@@ -0,0 +1,38 @@
...
+---
+# Core
+* Changed validation in `RegisterRoute::validateRegistrationData()` to properly validate billing and shipping address data types
+* Added explicit type validation for `billingAddress` field requiring `associative_array` type
+* Added validation for `shippingAddress` field allowing either `associative_array` type or `null` value using `AtLeastOneOf` constraint
+* Changed condition logic to prevent validation builder failures when billing address is not a DataBag but shipping address is null
+___
+# API
+* Changed Store API `/store-api/account/register` endpoint to return proper 400 status code with JSON validation errors when invalid address data is provided
+* Changed error handling to complete the fix for issue #11842 which was partially addressed in PR #11712
```
Comment (mitelg) [inline changelog/_unreleased/2025-08-22-fix-customer-registration-address-validation.md]: imo this information is not necessary

File: changelog/_unreleased/2025-08-22-fix-customer-registration-address-validation.md [hunk 5]
```diff
@@ -0,0 +1,38 @@
...
+___
+# Upgrade Information
+
+## Customer Registration Validation
+The customer registration endpoint now properly validates the data types of billing and shipping addresses. This completes the fix for issue #11842, building upon PR #11712 which addressed the initial error handling.
```
Comment (mitelg) [inline changelog/_unreleased/2025-08-22-fix-customer-registration-address-validation.md]:
```suggestion
The customer registration endpoint now properly validates the data types of billing and shipping addresses.
```

File: changelog/_unreleased/2025-08-22-fix-customer-registration-address-validation.md [hunk 6]
```diff
@@ -0,0 +1,38 @@
...
+
+### Evolution of the fix:
```
Comment (mitelg) [inline changelog/_unreleased/2025-08-22-fix-customer-registration-address-validation.md]: please avoid AI story writing bla blub... Just one or two sentences what changed and that's it

**Review by mitelg — CHANGES_REQUESTED** [review]

File: src/Core/Checkout/Customer/SalesChannel/RegisterRoute.php [hunk 7]
```diff
@@ -339,7 +341,15 @@ private function validateRegistrationData(
...
-        if ($billingAddress instanceof DataBag || !($shippingAddress instanceof DataBag)) {
+
+        // The billing address is mandatory.
+        // The shipping address is optional but if there is one, a non-array value results in an exception in the validation process.
+        $definition->add('billingAddress', new Type('associative_array'));
+        $definition->add('shippingAddress', new AtLeastOneOf([new Type('associative_array'), new IsNull()]));
+
+        // The billing address validation must not be added if the data is neither a data bag nor valid because the validation building will fail.
+        // Using a null value must be possible to allow the event based modification (see BuildValidationEvent).
+        if ($billingAddress instanceof DataBag || (!$shippingAddress instanceof DataBag && $billingAddress === null)) {
```
Comment (BrocksiNet) [inline src/Core/Checkout/Customer/SalesChannel/RegisterRoute.php:361]: If shippingAddress is NOT an instance of DataBag it is NULL?

So would that condition be more readable?
```suggestion
        if ($billingAddress instanceof DataBag || ($shippingAddress === null && $billingAddress === null)) {
```

Comment (SpiGAndromeda) [reply src/Core/Checkout/Customer/SalesChannel/RegisterRoute.php:361]: The shipping address can be a string as well. I **think** the billing address should be "used" (validation enforced) if the shipping address is invalid (I am not sure about the intention here). And its also aligned with the next check for `$shippingAddress instanceof DataBag`.

**Comment by mkucmus** [comment]
the API responds with 400 instead of 500 when passing a string instead of actual object ✅ 
works as expected for `billingAddress` and `shippingAddress` reference ✅ 

image

@SpiGAndromeda is `associative_array` something shopwareish or also known in php world? maybe we could make it more human/dev friendly and say that the address should be in type of `Address` (if exists of course) or sth like that? just to consider to make it clear what API expects for people from JS world or other API consumers.

**Comment by SpiGAndromeda** [comment]
"associative_array" is from the Symfony constraint. It was the closest to the actual demand I could found that works with the Type constraint. Anything else would have required replicating the request structure. And "array" could also mean a list. So ... more ambiguous.

**Comment by mitelg** [comment]
maybe we can link this? https://github.com/shopware/shopware/blob/trunk/src/Core/Framework/Api/ApiDefinition/Generator/Schema/StoreApi/components/schemas/CustomerAddressBody.json

**Review by Phil23 — APPROVED** [review]

**Review by tobiasberge — APPROVED** [review]

**Review by cyl3x — APPROVED** [review]

**Comment by SpiGAndromeda** [comment]
> maybe we can link this? https://github.com/shopware/shopware/blob/trunk/src/Core/Framework/Api/ApiDefinition/Generator/Schema/StoreApi/components/schemas/CustomerAddressBody.json

In order to keep it compliant, I added `VIOLATION::BILLING_ADDRESS_INVALID_TYPE_ERROR` and `VIOLATION::SHIPPING_ADDRESS_INVALID_TYPE_ERROR` as violation messages. More detailed explanations were added to the storefront snippets.

> The billing address must be a valid object. Please refer to /store-api/_info/openapi3.json#/components/schemas/CustomerAddressBody for the correct structure.

**Comment by mkucmus** [comment]
> > maybe we can link this? https://github.com/shopware/shopware/blob/trunk/src/Core/Framework/Api/ApiDefinition/Generator/Schema/StoreApi/components/schemas/CustomerAddressBody.json
> 
> In order to keep it compliant, I added `VIOLATION::BILLING_ADDRESS_INVALID_TYPE_ERROR` and `VIOLATION::SHIPPING_ADDRESS_INVALID_TYPE_ERROR` as violation messages. More detailed explanations were added to the storefront snippets.
> 
> > The billing address must be a valid object. Please refer to /store-api/_info/openapi3.json#/components/schemas/CustomerAddressBody for the correct structure.

This looks good. The more details, the better from UX angle 🙌🏼 

I think we could improve the error reporting entirely for store-api context to make it more human/developer friendly. This was just an example 💪🏼

**Review by mitelg — APPROVED** [review]

**Review by patzick — APPROVED** [review]

File: changelog/_unreleased/2025-08-22-fix-customer-registration-address-validation.md [hunk 8]
```diff
@@ -0,0 +1,22 @@
+---
+title: Fix incorrect validation handling in customer registration endpoint
+issue: NEXT-11842
```
Comment (mstegmeyer) [inline changelog/_unreleased/2025-08-22-fix-customer-registration-address-validation.md]: you're not actually referencing a Jira issue here (which would be the `NEXT-` syntax). Just the number for the GitHub issue or with a `#` as a prefix would be more fitting.

Comment (SpiGAndromeda) [reply changelog/_unreleased/2025-08-22-fix-customer-registration-address-validation.md]: Fixed that.
