### PR TITLE
fix: skip VAT ID validation for non-EU company shipping countries

### LINKED ISSUE #14567: TaxDetector::isCompanyTaxFree() incorrectly requires VAT ID for non-EU (third-party) countries
Component: Checkout / Tax                                                                                                                                                                             
                                                                                                                                                                                                        
  Shopware Version: 6.7.0.0+                                                                                                                                                                            
                                                                                                                                                                                                        
  Description:                                                                                                                                                                                          
                                                                                                                                                                                                        
  Since Shopware 6.7, CartRuleLoader::detectTaxType() separates the tax-free detection into B2B and B2C paths based on customer.accountType. For B2B customers, only TaxDetector::isCompanyTaxFree() is 
  evaluated.                                                                                                                                                                                            
                                                                                                                                                                                                        
  However, isCompanyTaxFree() requires the customer to have a non-empty vatIds array:                                                                                                                   
                                                                                                                                                                                                        
```
  // TaxDetector.php:60-63                                                                                                                                                                              
  $vatIds = array_filter($customer->getVatIds() ?? []);                                                                                                                                                 
  if (empty($vatIds)) {                                                                                                                                                                                 
      return false;                                                                                                                                                                                     
  }                                                                                                                                                                                                     
              
```                                                                                                                                                                                          
  This makes sense for EU countries where a VAT ID is needed for reverse charge. But for third-party countries (e.g. United Kingdom, Switzerland, Norway), there is no EU VAT system – these countries  
  are configured as tax-free regardless of VAT ID. A B2B customer from the UK or Switzerland typically has no EU VAT ID.                                                                                
                                                                                                                                                                                                        
  In Shopware 6.5 and 6.6, this was not a problem because detectTaxType() checked both customerTax (B2C) and companyTax (B2B) with an OR condition:                                                     
                                                                                                                                                                                                        
```
  // 6.6 - CartRuleLoader::detectTaxType()                                                                                                                                                              
  $isReachedCustomerTaxFreeAmount = $country->getCustomerTax()->getEnabled() && ...;                                                                                                                    
  $isReachedCompanyTaxFreeAmount = $this->taxDetector->isCompanyTaxFree($context, $country) && ...;                                                                                                     
                                                                                                                                                                                                        
  if ($isReachedCustomerTaxFreeAmount || $isReachedCompanyTaxFreeAmount) {                                                                                                                              
      return CartPrice::TAX_STATE_FREE;                                                                                                                                                                 
  }        
```                                                                                                                                                                                             
                                                                                                                                                                                                        
  Even if isCompanyTaxFree() returned false due to missing VAT IDs, customerTax.enabled would still trigger tax-free for the country.                                                                   
                                                                                                                                                                                                        
  In Shopware 6.7, the logic was changed to an if/else based on accountType:                                                                                                                            
                                                                                                                                                                                                        
```
  // 6.7 - CartRuleLoader::detectTaxType()                                                                                                                                                              
  if ($context->getCustomer()?->getAccountType() === CustomerEntity::ACCOUNT_TYPE_BUSINESS) {                                                                                                           
      // ONLY companyTax path – customerTax is IGNORED for business customers                                                                                                                           
      $isReachedCompanyTaxFreeAmount = $this->taxDetector->isCompanyTaxFree($context, $country) && ...;                                                                                                 
  } else {                                                                                                                                                                                              
      // ONLY customerTax path                                                                                                                                                                          
      $isReachedCustomerTaxFreeAmount = $country->getCustomerTax()->getEnabled() && ...;                                                                                                                
  }             
```                                                                                                                                                                                        
                                                                                                                                                                                                        
  This means a B2B customer from a third-party country (e.g. UK) without a VAT ID is no longer tax-free, even though the country is correctly configured with both customerTax.enabled = true and       
  companyTax.enabled = true.                                                                                                                                                                            
                                                                                                                                                                                                        
  Steps to reproduce:                                                                                                                                                                                   
                                                                                                                                                                                                        
  1. Configure a non-EU country (e.g. United Kingdom) with both "Tax-free (B2C)" and "Tax-free (B2B)" enabled                                                                                           
  2. Create a B2B customer (accountType = business) with a company name but no VAT ID (or empty vatIds)                                                                                                 
  3. Set the customer's shipping address to the UK                                                                                                                                                      
  4. Add products to cart and go to checkout                                                                                                                                                            
  5. Expected: No tax is calculated (country is tax-free)                                                                                                                                               
  6. Actual: 19% VAT is calculated                                                                                                                                                                      
                                                                                                                                                                                                        
  Expected behavior:                                                                                                                                                                                    
                                                                                                                                                                                                        
  For third-party (non-EU) countries where companyTax.enabled = true, the tax-free status should not depend on the customer having a VAT ID. The VAT ID requirement is only relevant for EU reverse     
  charge scenarios.                                                                                                                                                                                     
                                                                                                                                                                                                        
  Suggested fix:                                                                                                                                                                                        
                                                                                                                                                                                                        
  In TaxDetector::isCompanyTaxFree(), skip the VAT ID check when the country is not an EU member state:                                                                                                 
                                                                                                                                                                                                        
```
  $vatIds = array_filter($customer->getVatIds() ?? []);                                                                                                                                                 
  if (empty($vatIds) && $shippingLocationCountry->getMemberOfEuropeanUnion()) {                                                                                                                         
      return false;                                                                                                                                                                                     
  }                                                                                                                                                                                                     
  if (empty($vatIds) && !$shippingLocationCountry->getMemberOfEuropeanUnion()) {                                                                                                                        
      // Non-EU country: VAT ID is not required for tax-free status                                                                                                                                     
      return true; // or skip this check entirely                                                                                                                                                       
  }                                                                                                                                                                                                     
                  
```                                                                                                                                                                                      
  Alternatively, detectTaxType() could fall back to the customerTax path when isCompanyTaxFree() returns false for a B2B customer, restoring the 6.6 OR behavior.                                       
                                                                                                                                                                                                        
  Regression introduced in: 6.7.0.0 (change to detectTaxType() separating B2B/B2C paths)

### PR DESCRIPTION
**Pull request by Aliaaaam**
### 1. Why is this change necessary?
Because VAT ID validation should only apply to EU countries. Requiring it for non-EU countries incorrectly prevents tax-free handling for business customers there.

### 2. What does this change do, exactly?
It enforces VAT ID checks only for EU countries and skips them for non-EU countries, allowing eligible non-EU business customers to remain tax-free.

### 3. Describe each step to reproduce the issue or behaviour.
1. Configure a non-EU country (e.g. United Kingdom) with both "Tax-free (B2C)" and "Tax-free (B2B)" enabled
2. Create a B2B customer (accountType = business) with a company name but no VAT ID (or empty vatIds)
3. Set the customer's shipping address to the UK
4. Add products to cart and go to checkout
5. Expected: No tax is calculated (country is tax-free)
6. Actual: 19% VAT is calculated

### 4. Please link to the relevant issues
- Fixes https://github.com/shopware/shopware/issues/14567

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [ ] I have updated developer-facing release notes if this change is **relevant** for external developers:
  - Add a short entry to `RELEASE_INFO-6.<major>.md` under “Upcoming” for informational changes, including the consequences of the change and how it affects external developers.
  - Add an `UPGRADE` section in `UPGRADE-6.<next-major>.md` for breaking changes (what/why/impact/how to adapt).
  - See the [Documenting a Release Process](https://github.com/shopware/shopware/blob/trunk/delivery-process/documenting-a-release.md) for details.
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Core/Checkout/Cart/Tax/TaxDetector.php [hunk 1]
```diff
@@ -56,19 +56,21 @@ public function isCompanyTaxFree(SalesChannelContext $context, CountryEntity $sh
             return false;
         }
 
-        $vatPattern = $shippingLocationCountry->getVatIdPattern();
-        $vatIds = array_filter($customer->getVatIds() ?? []);
+        if ($shippingLocationCountry->getIsEu()) {
```
Comment (cyl3x) [inline src/Core/Checkout/Cart/Tax/TaxDetector.php]: how about using an early return instead?

Comment (Aliaaaam) [reply src/Core/Checkout/Cart/Tax/TaxDetector.php]: I moved it to an early return.

**Review by En0Ma1259 — APPROVED** [review]

**Review by cyl3x — APPROVED** [review]
