### PR TITLE
fix: update MatchAllLineItemsRule to support multiple item types

### LINKED ISSUE #10720: Rule Builder - Position with additional field leads to errors with dispatch types
### Shopware Version

6.7.0.0

### Affected area / extension

Platform(Default)

### Actual behaviour

Rule Builder - If you use ‘Position with additional field’, this leads to an error with shipping methods and these can no longer be used to create an order via the admin if you do not add a standard position but an empty position and insert a ‘new’ product there as an offer.  
You can then not use the shipping method because it does not work according to the admin, but it can be used in the frontend or with standard products that have been created.

### Expected behaviour

You can still use the shipping method for non-existent items (add an empty position and enter your own text)

### How to reproduce

- Creates an additional field with a checkbox which is for products
- Creates a rule: Position with additional field > All > test_checkbox > Is equal > ‘Do not tick checkbox’
- Adds this rule to a shipping method as a condition
- now tries to create an order with the shipping method in the admin with an empty position and e.g. the text ‘Testbox’ 0% tax and 500€

This does not work because the shipping method ‘would’ not be permitted.

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by larskemper**
### 1. Why is this change necessary? 
closes #10720

Refactor the handling of line item types in the rule system and improve order validation and error messaging in the admin. The main focus is on replacing single-type handling with support for multiple line item types so line items of type `custom` are not instantly filtered out by the `MatchAllLineItemsRule` and can be evaluated by deeper rules. 

### 2. What does this change do, exactly?
- refactor & improve error handling in order details
- make it possible to filter out multiple line item types in the `MatchAllLineItemsRule`

### CODE REVIEW

File: src/Administration/Resources/app/administration/src/module/sw-order/page/sw-order-create/index.ts [hunk 1]
```diff
@@ -106,47 +119,66 @@ export default Shopware.Component.wrapComponentConfig({
...
-                    })
-                    // eslint-disable-next-line @typescript-eslint/no-unsafe-argument
-                    .catch((error) => this.showError(error))
-                    .finally(() => {
-                        this.isLoading = false;
-                    });
-            } else if (this.invalidPromotionCodes.length > 0) {
-                this.openInvalidCodeModal();
-            } else {
+            if (this.orderValidateMessage) {
```
[the remark this answers is not in the document]
Comment (larskemper) [reply src/Administration/Resources/app/administration/src/module/sw-order/page/sw-order-create/index.ts]: incorrect

**Comment by aragon999** [comment]
Not sure, if this was already planned and just not implemented, but please do not forget to add a migration, to update the existing rule values:
image

File: src/Core/Migration/V6_7/Migration1754398573ChangeAllLineItemsRuleValueType.php [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+    {
+        return 1754398573;
+    }
+
+    public function update(Connection $connection): void
+    {
+        $connection->executeStatement(
+            <<<'SQL'
+                UPDATE `rule_condition`
+                SET `value` = JSON_OBJECT('types', JSON_ARRAY(JSON_UNQUOTE(JSON_EXTRACT(`value`, '$.type'))))
```
Comment (mitelg) [inline src/Core/Migration/V6_7/Migration1754398573ChangeAllLineItemsRuleValueType.php:25]: have you tested this on mariaDB and MySQL? I know that they have different support of those JSON functions

File: src/Core/Migration/V6_7/Migration1754398573ChangeAllLineItemsRuleValueType.php [hunk 3]
```diff
@@ -0,0 +1,36 @@
...
+    public function getCreationTimestamp(): int
+    {
+        return 1754398573;
+    }
+
+    public function update(Connection $connection): void
+    {
+        $connection->executeStatement(
+            <<<'SQL'
+                UPDATE `rule_condition`
```
Comment (mitelg) [inline src/Core/Migration/V6_7/Migration1754398573ChangeAllLineItemsRuleValueType.php:24]: do we need to make this updates in chunks? is it likely that there are 100s of 1000s of rules?

**Review by ennasus4sun — APPROVED** [review]

File: src/Core/Migration/V6_7/Migration1754398573ChangeAllLineItemsRuleValueType.php (hunk 3 above)
Comment (larskemper) [reply src/Core/Migration/V6_7/Migration1754398573ChangeAllLineItemsRuleValueType.php:24]: I don’t think so. There will be maybe 100s, but certainly not 1000s. All previous updates to this table were also not done in chunks ([ref1](https://github.com/shopware/shopware/blob/trunk/src/Core/Migration/V6_4/Migration1653376989ResetDefaultAlwaysValidConditionValue.php), [ref2](https://github.com/shopware/shopware/blob/trunk/src/Core/Migration/V6_7/Migration1720603803RemoveDefaultPaymentMethodRule.php))

File: src/Core/Migration/V6_7/Migration1754398573ChangeAllLineItemsRuleValueType.php (hunk 2 above)
Comment (larskemper) [reply src/Core/Migration/V6_7/Migration1754398573ChangeAllLineItemsRuleValueType.php:25]: Seams like the json functions are supported since 10.2 (mariadb). I tested it locally and also all tests are working in the ci

**Review by mitelg — APPROVED** [review]

File: changelog/_unreleased/2025-08-05-update-matchalllineitemsrule-to-support-multiple-item-types.md [hunk 4]
```diff
@@ -0,0 +1,9 @@
+---
+title: Update MatchAllLineItemsRule to support multiple item types
+issue: 10720
+author: Lars Kemper
+author_email: l.kemper@shopware.com
+author_github: @larskemper
+---
+# Core
+* Changed `Shopware\Core\Framework\Rule\Container\MatchAllLineItemsRule` to support multiple line item types by changing the `$type` property and its corresponding constraint to an `array` and renaming the property to `$types`.
```
Comment (MalteJanz) [inline changelog/_unreleased/2025-08-05-update-matchalllineitemsrule-to-support-multiple-item-types.md:9]: Nice that it paid of to change these to final at the start of the year so we can do changes like this without breaks / major updates 🎉 . Also I don't think this changelog is strictly necessary, at least from a dev perspective you only changed an implementation detail.

But for the user / merchant it could be interesting that their rules changed slightly and allow more customization now 🤔

File: src/Administration/Resources/app/administration/src/module/sw-order/snippet/de-DE.json [hunk 5]
```diff
@@ -54,13 +54,20 @@
     "create": {
       "textNewOrder": "Neue Bestellung",
       "buttonSaveOrder": "Bestellung speichern",
-      "messageSaveError": "Bestellung konnte nicht gespeichert werden",
```
Comment (MalteJanz) [inline src/Administration/Resources/app/administration/src/module/sw-order/snippet/de-DE.json]: Technically this is a break and the snippet can only be removed with the next major update 🙈 .

We already have a collection of snippet we want to remove, maybe add it and make it a more general ticket:
https://github.com/shopware/shopware/issues/9063

But you also have to add a deprecation notice to the changelog / UPGRADE file

File: src/Core/Framework/Rule/Container/MatchAllLineItemsRule.php [hunk 6]
```diff
@@ -81,8 +86,22 @@ public function getConstraints(): array
...
+     */
+    private function filterAndFlatten(LineItemCollection $collection): array
+    {
+        if (empty($this->types)) {
+            return $collection->getFlat();
+        }
+
+        return $collection->filter(
+            fn (LineItem $lineItem) => \in_array($lineItem->getType(), $this->types, true),
+        )->getFlat();
```
Comment (MalteJanz) [inline src/Core/Framework/Rule/Container/MatchAllLineItemsRule.php]: Just curios: does this only filter on top level? Why should the filtering not applied after the flattening? 🤔

File: changelog/_unreleased/2025-08-05-update-matchalllineitemsrule-to-support-multiple-item-types.md (hunk 4 above)
Comment (larskemper) [reply changelog/_unreleased/2025-08-05-update-matchalllineitemsrule-to-support-multiple-item-types.md:9]: yeah, I tought the same, but as I also change the rule constraint that is public api and saved to the db, I thought it would not hurt to have this in a changelog

File: src/Administration/Resources/app/administration/src/module/sw-order/snippet/de-DE.json (hunk 5 above)
Comment (larskemper) [reply src/Administration/Resources/app/administration/src/module/sw-order/snippet/de-DE.json]: I can't remeber that we ever have deprecated a snippet actually 😅, it that a new decision?

File: src/Administration/Resources/app/administration/src/module/sw-order/page/sw-order-create/index.ts [hunk 7]
```diff
@@ -59,11 +59,24 @@ export default Shopware.Component.wrapComponentConfig({
             return Store.get('swOrder').invalidPromotionCodes;
         },
 
-        isSaveOrderValid(): boolean {
```
Comment (CR0YD) [inline src/Administration/Resources/app/administration/src/module/sw-order/page/sw-order-create/index.ts:62]: Maybe deprecate the function instead of removing it as this component is not marked as internal?

File: src/Core/Framework/Rule/Container/MatchAllLineItemsRule.php (hunk 6 above)
Comment (larskemper) [reply src/Core/Framework/Rule/Container/MatchAllLineItemsRule.php:105]: I use the [filter()](https://github.com/shopware/shopware/blob/trunk/src/Core/Framework/Struct/Collection.php#L140) method in the Collection which iterates the elements directly and gives be back a Collection instance.

File: src/Administration/Resources/app/administration/src/module/sw-order/snippet/de-DE.json (hunk 5 above)
Comment (CR0YD) [reply src/Administration/Resources/app/administration/src/module/sw-order/snippet/de-DE.json]: I also remember a talk with @marcelbrode about that and he said that it is okay to remove them not only in a major update.
As he is currently on vacation maybe @bschulzebaek knows something about that?

File: src/Administration/Resources/app/administration/src/module/sw-order/snippet/de-DE.json [hunk 8]
```diff
@@ -54,13 +54,20 @@
...
         "title": "Zahlungsaufforderung",
         "text": "Möchtest du den Kunden auffordern die Bestellung per \"{paymentMethodName}\" zu bezahlen?",
         "primaryAction": "Auffordern"
+      },
+      "saveError": {
+        "noCustomer": "Bestellung konnte nicht gespeichert werden. Kein Kunde ausgewählt.",
+        "noCart": "Bestellung konnte nicht gespeichert werden. Kein Warenkorb gefunden.",
+        "noLineItems": "Bestellung konnte nicht gespeichert werden. Keine Bestellposition gefunden.",
+        "invalidPromotionCodes": "Bestellung konnte nicht gespeichert werden. Ungültige Aktionscodes.",
+        "noTransactionReturned": "Für die Bestellung wurde keine Transaktion zurückgegeben.",
```
Comment (CR0YD) [inline src/Administration/Resources/app/administration/src/module/sw-order/snippet/de-DE.json]: The wording seems a little bit of.
Maybe have a look with @GitEvil again about these snippets.

File: src/Core/Framework/Rule/Container/MatchAllLineItemsRule.php (hunk 6 above)
Comment (larskemper) [reply src/Core/Framework/Rule/Container/MatchAllLineItemsRule.php]: good one, thought `filter()` would do the job for me and then return the collection, but apparently no 😅

File: src/Core/Migration/V6_7/Migration1754398573ChangeAllLineItemsRuleValueType.php [hunk 9]
```diff
@@ -0,0 +1,36 @@
...
+class Migration1754398573ChangeAllLineItemsRuleValueType extends MigrationStep
+{
+    public function getCreationTimestamp(): int
+    {
+        return 1754398573;
+    }
+
+    public function update(Connection $connection): void
+    {
+        $connection->executeStatement(
```
Comment (CR0YD) [inline src/Core/Migration/V6_7/Migration1754398573ChangeAllLineItemsRuleValueType.php:22]: Was there a specific reason you used the `executeStatement` instead of the `update` function?

Comment (larskemper) [reply src/Core/Migration/V6_7/Migration1754398573ChangeAllLineItemsRuleValueType.php:22]: just, personal preference 😉

File: src/Administration/Resources/app/administration/src/module/sw-order/snippet/de-DE.json (hunk 5 above)
Comment (bschulzebaek) [reply src/Administration/Resources/app/administration/src/module/sw-order/snippet/de-DE.json]: Right now we don't really have a process for that, but there is a risk that this new "version" of snippets makes it into CrowdIn and is then later used in a previous platform version. Deprecating them is a good start, but we also want to provide some guidelines (and ideally, a technical solution) for this in the future.

**Review by CR0YD — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-order/snippet/de-DE.json (hunk 5 above)
Comment (larskemper) [reply src/Administration/Resources/app/administration/src/module/sw-order/snippet/de-DE.json]: Will revert the change then. I just wanted to move the snippet and not remove it completely. Not really worth the effort

File: src/Administration/Resources/app/administration/src/module/sw-order/snippet/de-DE.json [hunk 10]
```diff
@@ -61,6 +61,13 @@
         "title": "Zahlungsaufforderung",
         "text": "Möchtest du den Kunden auffordern die Bestellung per \"{paymentMethodName}\" zu bezahlen?",
         "primaryAction": "Auffordern"
+      },
+      "saveError": {
+        "noCustomer": "Bestellung konnte nicht gespeichert werden, da kein Kunde ausgewählt wurde.",
+        "noCart": "Bestellung konnte nicht gespeichert werden, da kein Warenkorb vorhanden ist.",
+        "noLineItems": "Bestellung konnte nicht gespeichert werden, da keine Positionen hinzugefügt wurden.",
```
Comment (GitEvil) [inline src/Administration/Resources/app/administration/src/module/sw-order/snippet/de-DE.json]:
```suggestion
        "noLineItems": "Die Bestellung hat keine Positionen.",
```

File: src/Administration/Resources/app/administration/src/module/sw-order/snippet/de-DE.json [hunk 11]
```diff
@@ -61,6 +61,13 @@
         "title": "Zahlungsaufforderung",
         "text": "Möchtest du den Kunden auffordern die Bestellung per \"{paymentMethodName}\" zu bezahlen?",
         "primaryAction": "Auffordern"
+      },
+      "saveError": {
+        "noCustomer": "Bestellung konnte nicht gespeichert werden, da kein Kunde ausgewählt wurde.",
+        "noCart": "Bestellung konnte nicht gespeichert werden, da kein Warenkorb vorhanden ist.",
```
Comment (GitEvil) [inline src/Administration/Resources/app/administration/src/module/sw-order/snippet/de-DE.json]:
```suggestion
        "noCart": "Kein Warenkorb vorhanden.",
```

Comment (GitEvil) [reply src/Administration/Resources/app/administration/src/module/sw-order/snippet/de-DE.json]: Was ist der Unterschied zwischen "kein Warenkorb" und "keine Positionen"?

File: src/Administration/Resources/app/administration/src/module/sw-order/snippet/de-DE.json [hunk 12]
```diff
@@ -61,6 +61,13 @@
         "title": "Zahlungsaufforderung",
         "text": "Möchtest du den Kunden auffordern die Bestellung per \"{paymentMethodName}\" zu bezahlen?",
         "primaryAction": "Auffordern"
+      },
+      "saveError": {
+        "noCustomer": "Bestellung konnte nicht gespeichert werden, da kein Kunde ausgewählt wurde.",
```
Comment (GitEvil) [inline src/Administration/Resources/app/administration/src/module/sw-order/snippet/de-DE.json]:
```suggestion
        "noCustomer": "Kein Kunde ausgewählt.",
```

File: src/Administration/Resources/app/administration/src/module/sw-order/snippet/de-DE.json [hunk 13]
```diff
@@ -61,6 +61,13 @@
...
+        "noCart": "Bestellung konnte nicht gespeichert werden, da kein Warenkorb vorhanden ist.",
+        "noLineItems": "Bestellung konnte nicht gespeichert werden, da keine Positionen hinzugefügt wurden.",
+        "invalidPromotionCodes": "Bestellung konnte nicht gespeichert werden, da ungültige Aktionscodes vorhanden sind.",
```
Comment (GitEvil) [inline src/Administration/Resources/app/administration/src/module/sw-order/snippet/de-DE.json]:
```suggestion
        "invalidPromotionCodes": "Kein gültiger Aktionscode vorhanden.",
```

File: src/Administration/Resources/app/administration/src/module/sw-order/snippet/de-DE.json [hunk 14]
```diff
@@ -61,6 +61,13 @@
...
+        "noTransactionReturned": "Bestellung konnte nicht gespeichert werden, da keine Zahlung erstellt wurde."
```
Comment (GitEvil) [inline src/Administration/Resources/app/administration/src/module/sw-order/snippet/de-DE.json]:
```suggestion
        "noTransactionReturned": "Keine Zahlungsart vorhanden."
```

File: src/Administration/Resources/app/administration/src/module/sw-order/snippet/en-GB.json [hunk 15]
```diff
@@ -61,6 +61,13 @@
         "title": "Remind payment",
         "text": "Do you want to remind the customer to pay this order with \"{paymentMethodName}\"?",
         "primaryAction": "Remind"
+      },
+      "saveError": {
+        "noCustomer": "Order could not be saved because no customer was selected.",
```
Comment (GitEvil) [inline src/Administration/Resources/app/administration/src/module/sw-order/snippet/en-GB.json]:
```suggestion
        "noCustomer": "No customer selected.",
```

File: src/Administration/Resources/app/administration/src/module/sw-order/snippet/en-GB.json [hunk 16]
```diff
@@ -61,6 +61,13 @@
...
+        "noCart": "Order could not be saved because there is no cart.",
```
Comment (GitEvil) [inline src/Administration/Resources/app/administration/src/module/sw-order/snippet/en-GB.json]:
```suggestion
        "noCart": "No shopping cart available.",
```

File: src/Administration/Resources/app/administration/src/module/sw-order/snippet/en-GB.json [hunk 17]
```diff
@@ -61,6 +61,13 @@
...
+        "noLineItems": "Order could not be saved because no items were added.",
```
Comment (GitEvil) [inline src/Administration/Resources/app/administration/src/module/sw-order/snippet/en-GB.json]:
```suggestion
        "noLineItems": "No items added.",
```

File: src/Administration/Resources/app/administration/src/module/sw-order/snippet/en-GB.json [hunk 18]
```diff
@@ -61,6 +61,13 @@
...
+        "invalidPromotionCodes": "Order could not be saved because there are invalid promotion codes.",
```
Comment (GitEvil) [inline src/Administration/Resources/app/administration/src/module/sw-order/snippet/en-GB.json]:
```suggestion
        "invalidPromotionCodes": "Invalid promotion code found.",
```

File: src/Administration/Resources/app/administration/src/module/sw-order/snippet/en-GB.json [hunk 19]
```diff
@@ -61,6 +61,13 @@
...
+        "noTransactionReturned": "Order could not be saved because no payment was created."
```
Comment (GitEvil) [inline src/Administration/Resources/app/administration/src/module/sw-order/snippet/en-GB.json]:
```suggestion
        "noTransactionReturned": "No payment method created."
```
