### PR TITLE
fix(image-slider): Fix broken snippet key

### LINKED ISSUE #12829: A typo caused the translation to be missing
### Shopware Version

6.7.*

### Affected area / extension

Platform(Default)

### Actual behaviour

Typo mistake in this file : 
https://github.com/shopware/shopware/blob/a54b556a1bed823057c6d43f53f3f410b379e56c/src/Administration/Resources/app/administration/src/module/sw-cms/elements/image-slider/config/index.js#L123

Image

Image

### Expected behaviour

https://github.com/shopware/shopware/blob/a54b556a1bed823057c6d43f53f3f410b379e56c/src/Administration/Resources/app/administration/src/module/sw-cms/elements/image-slider/config/index.js#L123

Should be 

`this.$tc('sw-cms.elements.imageSlider.config.label.navigationPositionInside')`

### How to reproduce

1. Assign a block Image Slider in to a layout 

Image

2. Open element config Setting

3. Dots navigation setting, open this drop down list

 
Image

### PR DESCRIPTION
**Pull request by marcelbrode**
fixes #12829

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Administration/Resources/app/administration/src/module/sw-cms/elements/image-slider/config/index.js [hunk 1]
```diff
@@ -116,15 +116,15 @@ export default {
             return [
                 {
                     value: 'none',
-                    label: this.$tc('sw-cms.elements.imageSlider.config.label.navigationPositionNone'),
+                    label: this.$t('sw-cms.elements.imageSlider.config.label.navigationPositionNone'),
                 },
                 {
                     value: 'inside',
-                    label: this.$tc('-cms.elements.imageSlider.config.label.navigationPositionInside'),
+                    label: this.$t('sw-cms.elements.imageSlider.config.label.navigationPositionInside'),
```
Comment (marcelbrode) [inline src/Administration/Resources/app/administration/src/module/sw-cms/elements/image-slider/config/index.js:123]: This is the fix the ticket is about, but I took the opportunity to rename the $t, when I'm already here

**Review by lukasrump — APPROVED** [review]

**Review by dgrothaus-sw — APPROVED** [review]
