### PR TITLE
fix: error on user password change

### LINKED ISSUE #7606: Administration: "Profile information could not be saved." error after changing user password
*PHP Version:* 8.3.17   | *Shopware Version:* 6.6.9.0  | *Affected area / extension:* Platform(Default) 

 ----

*_Actual behaviour:_*

When an admin user changes their password via /admin#/sw/profile/index/general, they get a "Profile information could not be saved." (from snippet "sw-profile.index.notificationSaveErrorMessage") flash as they are redirected back to the login page. The password change was, however, successful.

*_Expected behaviour:_*

Since the profile information could in fact be saved, this error should not appear.

*_How to reproduce:_*

In the administration, head to "Your profile", enter a new password and hit Save. The flash appears briefly as you are redirected to the login page.

### PR DESCRIPTION
**Pull request by tajespasarela**
### 1. Why is this change necessary?
When the user changes the password in user settings, an error notification is shown, and the user is logged out. The password is changed, though.

### 2. What does this change do, exactly?
Fix the error by requesting a new auth token and saving it, only when the password is changed.

### 3. Describe each step to reproduce the issue or behaviour.
1. Go to Settings > User & permissions
2. type a new password in the field
3. Save using the previous password
4. Before the fix the user is logged out

### 4. Please link to the relevant issues (if any).
- closes #7606

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfill them.

### CODE REVIEW

**Review by jleifeld — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-users-permissions/page/sw-users-permissions-user-detail/index.js [hunk 1]
```diff
@@ -418,6 +418,20 @@ export default {
                         return this.userRepository
```
Comment (bschulzebaek) [inline src/Administration/Resources/app/administration/src/module/sw-users-permissions/page/sw-users-permissions-user-detail/index.js]: Would be a nice opportunity to break up these promises into some smaller easier-to-read functions 💡

**Review by bschulzebaek — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-users-permissions/page/sw-users-permissions-user-detail/index.js (hunk 1 above)
Comment (tajespasarela) [reply src/Administration/Resources/app/administration/src/module/sw-users-permissions/page/sw-users-permissions-user-detail/index.js]: Added the refactor in a new commit.
 Basically I extracted the new logic into a new method, and refactor the `.then` callback hell using `asyc` `await`, and I think it is clearer now

Comment (bschulzebaek) [reply src/Administration/Resources/app/administration/src/module/sw-users-permissions/page/sw-users-permissions-user-detail/index.js]: Thank you, looks way cleaner now 👍🏻

**Review by jleifeld — APPROVED** [review]

**Review by bschulzebaek — APPROVED** [review]
