### PR TITLE
fix: prevent duplicate cross-selling assignments

### LINKED ISSUE #14632: Crossselling über API mehrfach zuweisbar
### Shopware Version

6.7.4.2

### Affected area / extension

Platform(Default)

### Actual behaviour

Aktuell kann über die API (Endpoint product_cross_selling) das gleiche Produkt mehrfach einem Crossselling zugewiesen werden. Das Produkt wird dann auch im Admin mehrfach angezeigt, im Storefront nur 1x. Das erzeugt Datenmüll, der nicht notwendig ist.

### Expected behaviour

Das sollte beim Import verhindert werden, z.B.  durch einen UNIQUE INDEX an der Tabelle product_cross_selling_assigned_products .
Wichtig ist auch, dass die Daten automatisiert bereinigt werden, da sonst der INDEX nicht erstellt werden kann.

### How to reproduce

Image

### PR DESCRIPTION
**Pull request by vienthuong**
## Summary
- Closes #14632
- Prevents duplicate cross-selling assignments for the same cross-selling and product combination.
- Adds migration coverage for existing duplicate rows and documents the migration-test pattern used here.

## Root Cause
The `product_cross_selling_assigned_products` table lacked a composite uniqueness constraint for `cross_selling_id`, `product_id`, and `product_version_id`, so duplicate assignments could be stored.

## What Changed
- Add a migration that removes duplicate rows and creates a unique index for the cross-selling assignment tuple.
- Add a migration test that uses `MultiInsertQueryQueue`, verifies duplicate cleanup, and runs `update()` twice to prove idempotence.
- Add an integration test for duplicate assigned-product writes.
- Update the database migration guideline to document the idempotence check and the optional `MultiInsertQueryQueue` recommendation.

## Impact
- Stops duplicate cross-selling assignment rows from being persisted.
- Cleans up existing duplicate data during migration.
- Documents the migration-test expectations used by this fix.

### CODE REVIEW

**Review by tamvt — APPROVED** [review]

**Review by ngocblue — APPROVED** [review]
Looks good to me

- Duplicated records are removed from cross-selling after running the migration
- Call API will duplicate records will fail when creating or updating cross-selling

Note: The position of the remaining products will be kept in this case

File: src/Core/Migration/V6_7/Migration1775208486AddUniqueIndexToProductCrossSellingAssignedProducts.php [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+
+        $connection->executeStatement($removeDuplicatesSql);
+
+        $connection->executeStatement('
+            ALTER TABLE `product_cross_selling_assigned_products`
+                ADD UNIQUE KEY `uniq.cross_selling_id__product_id__product_version_id` (`cross_selling_id`, `product_id`, `product_version_id`)
+        ');
+    }
+
+    public function updateDestructive(Connection $connection): void
```
Comment (mitelg) [inline src/Core/Migration/V6_7/Migration1775208486AddUniqueIndexToProductCrossSellingAssignedProducts.php]: can be removed

File: tests/integration/Core/Content/Product/Repository/ProductCrossSellingAssignedProductsRepositoryTest.php [hunk 2]
```diff
@@ -0,0 +1,60 @@
...
+    {
+        $context = Context::createDefaultContext();
+        $ids = new IdsCollection();
+
+        $assignedProduct = (new ProductBuilder($ids, 'assigned-product'))
+            ->manufacturer('assigned-manufacturer')
+            ->price(15.0, 10.0)
+            ->build();
+
+        /** @var EntityRepository $productRepository */
```
Comment (mitelg) [inline tests/integration/Core/Content/Product/Repository/ProductCrossSellingAssignedProductsRepositoryTest.php]:
```suggestion
```

**Review by mitelg — APPROVED** [review]
