### PR TITLE
fix: Add mt-modal

### LINKED ISSUE #9693: X-Button on upload file from URL modal doesn't work
### Shopware Version

cloud

### Affected area / extension

Platform(Default)

### Actual behaviour

The x button does not close the modal and is not centered correctly.

Image

### Expected behaviour

X-button closes modal and is in the middle of the grey circle.

### How to reproduce

Go to media module.
Select from the primary button dropdown the option to Upload a file from URL
Press the x-button.

### PR DESCRIPTION
**Pull request by alexdumea**
### 1. Why is this change necessary?
The component `sw-media-url-form` previously used legacy `<sw-modal>` . Switched to `<mt-modal>`

### 2. What does this change do, exactly?
Replaces `<sw-modal>` with `<mt-modal>`

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfill them.

### CODE REVIEW

File: src/Administration/Resources/app/administration/src/app/component/media/sw-media-url-form/index.js [hunk 1]
```diff
@@ -41,9 +41,16 @@ export default {
...
             extensionFromUrl: '',
             extensionFromInput: '',
+            showModal: false,
         };
     },
 
+    mounted() {
+        if (this.variant === 'modal') {
+            this.showModal = true;
+        }
```
Comment (marcelbrode) [inline src/Administration/Resources/app/administration/src/app/component/media/sw-media-url-form/index.js]: Please wrap this in a function like "mountedComponent", so it's extensible

**Review by marcelbrode — CHANGES_REQUESTED** [review]

**Review by bschulzebaek — APPROVED** [review]

**Review by marcelbrode — APPROVED** [review]
