### PR TITLE
fix: properly parsing mysql replica parameters provided as dsn

### LINKED ISSUE #11085: MySQL Cluster could not be connected
### Shopware Version

6.7.0.0

### Affected area / extension

Platform(Default)

### Actual behaviour

Every where you can found an `PDOException {#66 #message: "SQLSTATE[HY000] [2002] No such file or directory"`.

### Expected behaviour

I can open the storefront and admin backend and i can run console commands.

### How to reproduce

1. Install Shopware 6.7 using pdo_mysql
2. ENV with
  ```env
  DATABASE_URL=mysql://shopware:shopware@mysql:3306/shopware
  DATABASE_REPLICA_0_URL=mysql://shopware:shopware@mysql:3306/shopware
  ```
3. Open any page or run an command.

*Analyses*
The Method `\Shopware\Core\Framework\Adapter\Database\MySQLFactory::create` receives all necessary informations. The parser works well.

The `$parameters` contains an array with host, port, user, password, primary[0], replica[0].
BUT the both variables primary[0], replica[0] doesn't contains the user or password, they have only the `url` value with a DSN.

The method `\Doctrine\DBAL\DriverManager::getConnection` received the `PrimaryReadReplicaConnection` and in the deepest level in `PrimaryReadReplicaConnection`:231i could not found any username or password. Here i can see the primary[0] with charset, and driver class.

I think the primary[0] must me parsed before we are reaching this point.

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by h1k3r**
### 1. Why is this change necessary?

`doctrine/dbal` removed [url connection parameter](https://github.com/doctrine/dbal/blob/4.2.x/UPGRADE.md#bc-break-removed-the-url-connection-parameter) in version 4.0.

### 2. What does this change do, exactly?

This change adapts parameters preparation in MySQLFactory to the mentioned change.

### 3. Describe each step to reproduce the issue or behaviour.

See original issue.

### 4. Please link to the relevant issues (if any).
- closes https://github.com/shopware/shopware/issues/11085

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: tests/unit/Core/Framework/Adapter/Database/MySQLFactoryTest.php [hunk 1]
```diff
@@ -8,19 +8,81 @@
...
+        static::assertSame(3307, $replica0['port']);
+        static::assertArrayHasKey('user', $replica0);
+        static::assertSame('replica_user', $replica0['user']);
+        static::assertArrayHasKey('password', $replica0);
+        static::assertSame('replica_pass', $replica0['password']);
+        static::assertArrayHasKey('dbname', $replica0);
+        static::assertSame('replica_db', $replica0['dbname']);
+        static::assertArrayHasKey('charset', $replica0);
+        static::assertSame('utf8mb4', $replica0['charset']);
+        static::assertArrayHasKey('driverOptions', $replica0);
```
Comment (nfortier-shopware) [inline tests/unit/Core/Framework/Adapter/Database/MySQLFactoryTest.php]: every other assertion, the key is checked and then its associated value compared, while for driverOptions only the key presence is checked, is it intended?

**Review by mitelg — APPROVED** [review]

**Review by nfortier-shopware — APPROVED** [review]

File: tests/unit/Core/Framework/Adapter/Database/MySQLFactoryTest.php (hunk 1 above)
Comment (h1k3r) [reply tests/unit/Core/Framework/Adapter/Database/MySQLFactoryTest.php]: Did small update. Not doing extensive testing for driverOptions in this test, as it's intended to cover replica params parsing.
