### PR TITLE
fix: remove Elasticsearch dependencies in Core namespace

### LINKED ISSUE #12528: Class "Shopware\Elasticsearch\Framework\DataAbstractionLayer\ElasticsearchEntitySearcher" not found
### Shopware Version

6.7.2.0

### Affected area / extension

Platform(Default)

### Actual behaviour

In Shopware version 6.7.2.0, an error occurs if the Elasticsearch package is not installed.
The system tries to access the class
Shopware\Elasticsearch\Framework\DataAbstractionLayer\ElasticsearchEntitySearcher,
which is not available unless the shopware/elasticsearch package is installed.

See: https://github.com/shopware/shopware/blame/trunk/src/Core/System/SalesChannel/Context/SalesChannelContextService.php#L111

### Expected behaviour

Shopware should handle the absence of the Elasticsearch package gracefully and not reference the ElasticsearchEntitySearcher class if the package is missing.

### How to reproduce

-

### PR DESCRIPTION
**Pull request by vienthuong**
allow Core to operate without Elasticsearch package while preserving explain-mode behavior

### CODE REVIEW

File: src/Elasticsearch/Framework/DataAbstractionLayer/ElasticsearchEntitySearcher.php [hunk 1]
```diff
@@ -24,6 +24,9 @@
 #[Package('framework')]
 class ElasticsearchEntitySearcher implements EntitySearcherInterface
 {
+    /**
+     * @deprecated tag:v6.8.0 - Will be removed, use \Shopware\Core\Framework\Context::ELASTICSEARCH_EXPLAIN_MODE instead.
+     */
     final public const EXPLAIN_MODE = 'explain-mode';
```
Comment (mitelg) [inline src/Elasticsearch/Framework/DataAbstractionLayer/ElasticsearchEntitySearcher.php]:
```suggestion
    final public const EXPLAIN_MODE = Context::ELASTICSEARCH_EXPLAIN_MODE;
```

**Review by mitelg — APPROVED** [review]

**Review by shyim — APPROVED** [review]

**Review by shyim — APPROVED** [review]

**Review by nguyenytran — APPROVED** [review]
