### PR TITLE
fix: sorting of properties

### LINKED ISSUE #13261: Property Options not sorted alphanumerically in Product Variant Generator Modal
### Shopware Version

6.7.3.1

### Affected area / extension

Platform(Default)

### Actual behaviour

The Property Group Options API ignores the sort parameter in Admin API requests, resulting in the options not being ordered alphanumerically. For Properties with 100+ options, it is now nearly impossible to find the relevant options when working on Products. We are experiencing this issue since SW 6.7.

Image

The Request is sent to Backend with order=ASC naturalSorting=true. So, the **Backend** does not correctly apply the sorting:

http://localhost:5173/api/search/property-group-option

```json
{
   "page":1,
   "limit":10,
   "filter":[
      {
         "type":"equals",
         "field":"groupId",
         "value":"019a3006a36f71e7ba129c1c9abaa9b0"
      }
   ],
   "sort":[
      {
         "field":"name",
         "order":"ASC",
         "naturalSorting":true
      }
   ],
   "total-count-mode":1
}
```

### Expected behaviour

Property Group Options should be returned to frontend alphanumerically, and displayed as such.

### How to reproduce

- Create a new property with 10+ property options, different names, configure it to be alphanumerically sorted.
- Go to a Product -> Variant Tab -> Generate variants -> Select Property -> See the options listed in seemingly random order, I believe creation date DESC.

Image

### PR DESCRIPTION
**Pull request by sydinh**
### 1. Why is this change necessary?

See https://github.com/shopware/shopware/issues/11702

### 2. What does this change do, exactly?

Do not allow natural sorting for the property group

### 3. Describe each step to reproduce the issue or behaviour.

See https://github.com/shopware/shopware/issues/11702

### 4. Please link to the relevant issues (if any).

_

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

**Comment by sydinh** [comment]
Fixes https://github.com/shopware/shopware/issues/11702

**Review by nguyenquocdaile — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/app/component/base/sw-property-search/index.js [hunk 1]
```diff
@@ -73,7 +73,7 @@ export default {
 
         propertyGroupCriteria() {
             const criteria = new Criteria(this.groupPage, 10);
-            criteria.addSorting(Criteria.sort('name', 'ASC', true));
+            criteria.addSorting(Criteria.sort('name', 'ASC', false));
```
Comment (nguyenytran) [inline src/Administration/Resources/app/administration/src/app/component/base/sw-property-search/index.js:76]:
```suggestion
            criteria.addSorting(Criteria.sort('name'));
```

Comment (sydinh) [reply src/Administration/Resources/app/administration/src/app/component/base/sw-property-search/index.js:76]: I would keep things explicitly 😉

**Review by vienthuong — APPROVED** [review]
