### PR TITLE
fix: Allow to set the file extension for media entities via admin api

### LINKED ISSUE #7993: Media file extension is null when creating using remote file path
### PHP Version

8.2

### Shopware Version

> 6.6.4.0

### Affected area / extension

Platform(Default)

### Actual behaviour

- In previous Shopware versions, when uploading media files, the file_extension is automatically realized and saved behind the scene

- Since the introduce of remote thumbnail:
https://developer.shopware.com/docs/guides/plugins/plugins/content/media/remote-thumbnail-generation.html , the file_extension is null as we don't realize it behind the scene, the MediaDefinition also have `file_extension` field as write protected so they cannot define it in the request.

### Expected behaviour

media file extension could be realized automatically or allow API consumer to define it 

### How to reproduce

1. Create a media using admin API with `path` defined as, for e.g, "https://example.com/foo.png" and other required fields
2. Notice the media is created successfuly but file_extension is null

### PR DESCRIPTION
**Pull request by MartinKrzykawski**
Closes #7993

### 1. Why is this change necessary?
When media entities are created via the Admin API—for example, during [remote thumbnail generation](https://developer.shopware.com/docs/guides/plugins/plugins/content/media/remote-thumbnail-generation.html)—the fileExtension field is null.
This is because it’s only set when using specific API routes and not populated through the Admin API. Additionally, the fileExtension field is write-protected and therefore cannot be manually set via the Admin API.

### 2. What does this change do, exactly?
I have removed the write protection for the fileExtension field to allow setting this field via Admin API.

### 3. Describe each step to reproduce the issue or behaviour.
1. Set up admin API
2. Create a media entity and include the fileExtension field in your request payload.
3. Check if the media entity was created and check for the fileExtension.

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfill them.

### CODE REVIEW

File: src/Core/Content/Media/MediaDefinition.php [hunk 1]
```diff
@@ -92,7 +92,7 @@ protected function defineFields(): FieldCollection
             new FkField('user_id', 'userId', UserDefinition::class),
             new FkField('media_folder_id', 'mediaFolderId', MediaFolderDefinition::class),
             (new StringField('mime_type', 'mimeType'))->addFlags(new ApiAware(), new SearchRanking(SearchRanking::LOW_SEARCH_RANKING)),
-            (new StringField('file_extension', 'fileExtension'))->addFlags(new ApiAware(), new WriteProtected(Context::SYSTEM_SCOPE)),
+            (new StringField('file_extension', 'fileExtension'))->addFlags(new ApiAware()),
```
Comment (mitelg) [inline src/Core/Content/Media/MediaDefinition.php:95]: shouldn't we detect the file extension automatically? I guess that is, why it was protected :thinking:

Comment (MartinKrzykawski) [reply src/Core/Content/Media/MediaDefinition.php:95]: Yes, and with this approach, it still works when using the MediaUploadController API endpoint.

The reason we want to remove the write protection is that some merchants prefer not to download media files. Instead, the resources remain on a remote system, and the media entity should only reference them. Additionally, the file extension is not always included in the provided URL, so we want to offer the ability to set it manually via the API when needed.

**Review by marcelbrode — APPROVED** [review]

File: src/Core/Content/Media/MediaDefinition.php (hunk 1 above)
Comment (mitelg) [reply src/Core/Content/Media/MediaDefinition.php:95]: ah I see, Shopware would need to download every image for detection :bulb: 
yes, makes sense to send it directly :+1: 

so, if the file extension is sent, we do not guess it ourselves anymore on other routes?

**Review by dgrothaus-sw — APPROVED** [review]

File: src/Core/Content/Media/MediaDefinition.php (hunk 1 above)
Comment (MartinKrzykawski) [reply src/Core/Content/Media/MediaDefinition.php:95]: Yes, exactly! 😊

It’s not really guessing, since the Shopware core downloads the files and knows the exact file extension. This behavior will remain unchanged after the update. Our goal is to enable media entity creation via the generic Admin API, allowing merchants to create media references—even in bulk—without downloading the files. :) This is currently not possible because the fileExtension is always null.

**Review by mitelg — APPROVED** [review]
