### PR TITLE
fix: migrate line item stock rule to actual stock and deprecate product.availableStock

### LINKED ISSUE #7790: deprecate "Item available" condition in RuleBuilder for next major 6.8
### Technical TODO

Since 6.6 the database field "product.available_stock", on which this rule is based, is only a mirror of product.stock (see ADR: https://developer.shopware.com/docs/resources/references/adr/2023-05-15-stock-api.html).

We can prepare the removal by migrating existing "Item available" conditions to "Item in stock".

This is the corresponding task on the inventory side deprecate/prepare the removal of the "product.available_stock" field: https://github.com/shopware/shopware/issues/7787

background information to this topic: https://shopware-ag.slack.com/archives/C02HBLGK3K7/p1742479795004679

### PR DESCRIPTION
**Pull request by DennisGarding**
closes: https://github.com/shopware/shopware/issues/7790

Deprecate ProductEntity.availableStock
Remove the rule for this property (cartLineItemStock)
Migrate existing rules from (cartLineItemStock) to (cartLineItemActualStock) using ProductEntity.stock

### CODE REVIEW

File: src/Core/Content/Product/ProductDefinition.php [hunk 1]
```diff
@@ -166,7 +166,7 @@ protected function defineFields(): FieldCollection
             (new BoolField('active', 'active'))->addFlags(new ApiAware(), new Inherited())->setDescription('When boolean value is `true`, the products are available for selection in the storefront for purchase.'),
             (new BoolField('available', 'available'))->addFlags(new ApiAware(), new WriteProtected())->setDescription('Indicates weather the product is available or not.'),
             (new BoolField('is_closeout', 'isCloseout'))->addFlags(new ApiAware(), new Inherited())->setDescription('When the value is set to true, the product is hidden when sold out.'),
-            (new IntField('available_stock', 'availableStock'))->addFlags(new ApiAware(), new WriteProtected())->setDescription('Indicates the number of products still available. This value results from the stock minus the open orders.'),
+            (new IntField('available_stock', 'availableStock'))->addFlags(new ApiAware(), new WriteProtected(), new Deprecated('v6.7.8.2', 'v6.8.0.0', 'stock'))->setDescription('Indicates the number of products still available. This value results from the stock minus the open orders.'),
```
Comment (mitelg) [inline src/Core/Content/Product/ProductDefinition.php]: please put adding this field behind a feature flag check, so it is missing in 6.8 already

File: tests/migration/Core/V6_7/Migration1774366000MigrateLineItemStockRuleConditionTest.php [hunk 2]
```diff
@@ -0,0 +1,137 @@
...
+
+        $checkPayloadSql = 'SELECT `payload` FROM `rule` WHERE `id` = :id';
+        static::assertNull($this->connection->fetchOne($checkPayloadSql, ['id' => $this->oldRuleId]));
+        static::assertSame('{"keep":true}', $this->connection->fetchOne($checkPayloadSql, ['id' => $this->otherRuleId]));
+
+        $indexers = (new IndexerQueuer($this->connection))->getIndexers();
+        static::assertArrayHasKey('rule.indexer', $indexers);
+    }
+
+    public function createTestRulesAndConditions(): void
```
Comment (mitelg) [inline tests/migration/Core/V6_7/Migration1774366000MigrateLineItemStockRuleConditionTest.php]: why does this need to be a public method?

File: .codex
Comment (mitelg) [inline .codex:1]: please remove that file again

**Review by mitelg — CHANGES_REQUESTED** [review]

**Review by mitelg — APPROVED** [review]

File: src/Core/Migration/V6_7/Migration1774366000MigrateLineItemStockRuleCondition.php [hunk 3]
```diff
@@ -0,0 +1,50 @@
...
+
+use Doctrine\DBAL\ArrayParameterType;
+use Doctrine\DBAL\Connection;
+use Shopware\Core\Framework\Log\Package;
+use Shopware\Core\Framework\Migration\MigrationStep;
+
+/**
+ * @internal
+ */
+#[Package('inventory')]
```
Comment (larskemper) [inline src/Core/Migration/V6_7/Migration1774366000MigrateLineItemStockRuleCondition.php]:
```suggestion
#[Package('after-sales')]
```

File: src/Core/Migration/V6_7/Migration1774366000MigrateLineItemStockRuleCondition.php [hunk 4]
```diff
@@ -0,0 +1,50 @@
...
+            'UPDATE `rule_condition`
+             SET `type` = :newType
+             WHERE `type` = :oldType',
+            [
+                'newType' => 'cartLineItemActualStock',
+                'oldType' => 'cartLineItemStock',
+            ]
+        );
+
+        $connection->executeStatement(
```
Comment (larskemper) [inline src/Core/Migration/V6_7/Migration1774366000MigrateLineItemStockRuleCondition.php:42]: the `RuleIndexer` rebuilds the payload for every rule not just when `payload = null`, so we don't need this extra query.

Comment (DennisGarding) [reply src/Core/Migration/V6_7/Migration1774366000MigrateLineItemStockRuleCondition.php:42]: `rule.payload` is pre-calculated for the rule and becomes obsolete after renaming `rule_condition.type`

Comment (larskemper) [reply src/Core/Migration/V6_7/Migration1774366000MigrateLineItemStockRuleCondition.php:42]: it will be re-calculated anyway, cause you trigger the index `$this->registerIndexer($connection, 'rule.indexer');`, so it does not make a difference if you set it to `null` before.  Or am i missing something? 😅

Comment (DennisGarding) [reply src/Core/Migration/V6_7/Migration1774366000MigrateLineItemStockRuleCondition.php:42]: Yes your right, the indexer dont care about that, but until the indexer runs  and fix it the value is wrong. If the value is null, it will be new calculated.

File: src/Administration/Resources/app/administration/scripts/runNpmAudit.ts [hunk 5]
```diff
@@ -26,5 +26,7 @@ runNpmAudit({
         'https://github.com/advisories/GHSA-fp25-p6mj-qqg6', // locutus RCE via call_user_func_array, high severity, devDep only (twig), fix requires twig semver major
         'https://github.com/advisories/GHSA-vh9h-29pq-r5m8', // locutus RCE via create_function(), critical severity, devDep only (twig), fix requires twig semver major
         'https://github.com/advisories/GHSA-qpx9-hpmf-5gmw', // underscore unlimited recursion DoS, high severity, devDep only, no fix available in 1.x
+        'https://github.com/advisories/GHSA-chqc-8p9q-pq6q', // basic-ftp basic-ftp has FTP Command Injection via CRLF, high severity
+        'https://github.com/advisories/GHSA-qj83-cq47-w5f8', // axios update to 1.15.0
```
Comment (larskemper) [inline src/Administration/Resources/app/administration/scripts/runNpmAudit.ts]: wait till https://github.com/shopware/shopware/pull/16059 is merged

Comment (DennisGarding) [reply src/Administration/Resources/app/administration/scripts/runNpmAudit.ts]: just removed in this moment

**Review by larskemper — APPROVED** [review]
