### PR TITLE
fix: promotion admin issues

### LINKED ISSUE #8649: Issues in promotion discounts
### Shopware Version

trunk

### Affected area / extension

Platform(Default)

### Actual behaviour

There are a couple of things wrong with promotion discounts.

1. The promotion cannot be saved anymore after the advanced prices modal for the maximum discount value has been opened once.
2. The whole promotion is broken afterwards: General and Conditions tabs are empty.
4. The link to the advanced prices modal is initially present but leads to an empty modal or a modal with only 0s.
5. The link disappears if the maximum discount value is set to 0 and reappears if it is set to a negative or positive number.
6. The ?-symbol that holds the tooltip vanishes and reappears for no reason as well (seems connected to the link, but is actually not)
7. The advanced prices are not calculated every time the value is changed, but only sometimes.
8. The discount values hit weird numbers when the arrows are used.

See video:

https://github.com/user-attachments/assets/d392cc74-2982-46b7-b901-fc40abf541e5

### Expected behaviour

- discount values always have only 2 digits
- maximum discount value cannot be negative
- advanced prices are calculated on change
- tooltip and advanced prices link don't appear/disappear apart from one another
- discount can be saved even if advanced prices modal has been opened
- promotion is not broken after using adv prices

### How to reproduce

Create promotion
Add discount
Play around with "value", "maximum discount value", tooltip and "advanced prices"

### PR DESCRIPTION
**Pull request by En0Ma1259**
### 1. Why is this change necessary?
There are multiple issues for promotion discounts in the administration.
- https://github.com/shopware/shopware/issues/8649

### 2. What does this change do, exactly?
Makes Entity properties nullable
Recalculate advanced prices after change
Remove help text conditions

Open will be "The link disappears if the maximum discount value is set to 0 and reappears if it is set to a negative or positive number.".
If max value is 0 it will lead into `null` and then we will not have any advanced prices

### 3. Describe each step to reproduce the issue or behaviour.
Go into the administration promotion discount page (`/admin#/sw/promotion/v2/detail/UUID/discounts`) and try different configurations 

### 4. Please link to the relevant issues (if any).
- closes #8649

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfill them.

### CODE REVIEW

File: src/Administration/Resources/app/administration/src/module/sw-promotion-v2/component/sw-promotion-discount-component/index.js [hunk 1]
```diff
@@ -444,22 +445,26 @@ export default {
             this.discount.value = discountHandler.getFixedValue(this.discount.value, this.discount.type);
         },
 
-        onDiscountValueChanged(value) {
+        onDiscountValueChanged: Utils.debounce(function debounceBla(value) {
```
Comment (Bird87ZA) [inline src/Administration/Resources/app/administration/src/module/sw-promotion-v2/component/sw-promotion-discount-component/index.js]: best name, `debounceBla`

File: src/Administration/Resources/app/administration/src/module/sw-promotion-v2/component/sw-promotion-discount-component/index.js [hunk 2]
```diff
@@ -477,6 +482,25 @@ export default {
...
+            const currencyMapping = {};
+            this.currencies.forEach((currency) => {
+                currencyMapping[currency.id] = currency.factor;
+            });
+
+            [...this.discount.promotionDiscountPrices].forEach((price) => {
+                if (currencyMapping[price.currencyId] === undefined) {
+                    this.discount.promotionDiscountPrices.remove(price.id);
+                } else {
+                    const setPrice = (basePrice ?? discountHandler.getMinValue()) * (currencyMapping[price.currencyId] ?? 0);
```
Comment (Bird87ZA) [inline src/Administration/Resources/app/administration/src/module/sw-promotion-v2/component/sw-promotion-discount-component/index.js]: This will calculate to 0 if there's no currency found. Is this what you want? Should it not be 1?

File: src/Administration/Resources/app/administration/src/module/sw-promotion-v2/component/sw-promotion-discount-component/index.js (hunk 1 above)
Comment (En0Ma1259) [reply src/Administration/Resources/app/administration/src/module/sw-promotion-v2/component/sw-promotion-discount-component/index.js]: 🙈

File: src/Administration/Resources/app/administration/src/module/sw-promotion-v2/component/sw-promotion-discount-component/index.js (hunk 2 above)
Comment (En0Ma1259) [reply src/Administration/Resources/app/administration/src/module/sw-promotion-v2/component/sw-promotion-discount-component/index.js]: Is fetched by the if above. Second check is not needed

File: src/Administration/Resources/app/administration/src/module/sw-promotion-v2/component/sw-promotion-discount-component/index.js [hunk 3]
```diff
@@ -477,6 +482,25 @@ export default {
...
+
+            [...this.discount.promotionDiscountPrices].forEach((price) => {
+                if (currencyMapping[price.currencyId] === undefined) {
+                    this.discount.promotionDiscountPrices.remove(price.id);
+                } else {
+                    const setPrice = (basePrice ?? discountHandler.getMinValue()) * currencyMapping[price.currencyId];
+
+                    price.price = setPrice < discountHandler.getMinValue() ? discountHandler.getMinValue() : setPrice;
+                }
+            });
```
Comment (cyl3x) [inline src/Administration/Resources/app/administration/src/module/sw-promotion-v2/component/sw-promotion-discount-component/index.js]:
```suggestion
            this.discount.promotionDiscountPrices = this.discount.promotionDiscountPrices
                .filter((price) => currencyMapping[price.currencyId] !== undefined)
                .map((price) => {
                      const setPrice = (basePrice ?? discountHandler.getMinValue()) * (currencyMapping[price.currencyId] ?? 0);
                      price.price = Math.min(setPrice, discountHandler.getMinValue());

                      return price;
               });
```

**Review by cyl3x — APPROVED** [review]

**Review by Bird87ZA — APPROVED** [review]
