### PR TITLE
fix: Navigation routes properly invalidated

### LINKED ISSUE #11420: Problem with cache delay after Cache Rework
### Shopware Version

67.0.1

### Affected area / extension

Platform(Default)

### Actual behaviour

We are currently preparing the Shopware update to 6.7 in the test system. 

We noticed that the cache delay, which has become the new standard due to the cache rework, is not working correctly.

Steps to reproduce:

- Call up the frontend to load a page into the cache, e.g. the start page
- Then deactivate or activate a category in the backend
- Reload the same page in the frontend, e.g., home page -> no change visible -> everything as expected so far
- Then wait until shopware.invalidate_cache has run or click the “Update cache” button in the backend
- Reload the same page in the frontend, e.g. home page -> Expectation: changes are now visible, but they are not. These are only visible when the entire cache is cleared

I also noticed the same behavior in Dockware with a fresh Shopware 6.7.0.1 installation.

Adjustable with any 6.7.0.1 installation.

### Expected behaviour

.

### How to reproduce

Steps to reproduce:

- Call up the frontend to load a page into the cache, e.g. the start page
- Then deactivate or activate a category in the backend
- Reload the same page in the frontend, e.g., home page -> no change visible -> everything as expected so far
- Then wait until shopware.invalidate_cache has run or click the “Update cache” button in the backend
- Reload the same page in the frontend, e.g. home page -> Expectation: changes are now visible, but they are not. These are only visible when the entire cache is cleared

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by keulinho**
fixes https://github.com/shopware/shopware/issues/11420

Navigation route was only tagged by active id, so changing any other category would not lead to category invalidation

to prevent adding to many tags per entry (as depending per cache store there is a upper limit) we only tag navigations generally and as soon as navigation relevant data in the category entity changes we invalidate all navigations

the reason is that figuring out exactly which navigation needs to be invalidated when a given category changes is not that easy, and category is an entity that should not be updated constantly

### CODE REVIEW

**Review by shyim — APPROVED** [review]

**Review by mitelg — COMMENTED** [review]
can we put the issue into a test? :thinking:

**Comment by frobel** [comment]
Demo done. Works as expected.

**Review by frobel — APPROVED** [review]

File: tests/unit/Core/Content/Category/SalesChannel/NavigationRouteTest.php [hunk 1]
```diff
@@ -0,0 +1,220 @@
...
+        $this->categoryTreePathResolver = $this->createMock(CategoryTreePathResolver::class);
+
+        $this->navigationRoute = new NavigationRoute(
+            $this->connection,
+            $this->categoryRepository,
+            $this->cacheTagCollector,
+            $this->categoryTreePathResolver
+        );
+
+        $salesChannel = new SalesChannelEntity();
```
Comment (mitelg) [inline tests/unit/Core/Content/Category/SalesChannel/NavigationRouteTest.php]: why did you create the saleschannel manually?

**Review by mitelg — APPROVED** [review]
