### PR TITLE
fix: ui issues for product module

### LINKED ISSUE #7311: Bulk edit- variant properties cannot be changed
Shopware: 6.6.10.1

If you want to change the properties of variants via bulk edit, you cannot do so once you break the inheritance. The following notification appears: "No properties have been assigned to this product yet." However, no property can be selected or added here either.

### LINKED ISSUE #9993: Make the currency modal larger
### Shopware Version

6.7

### Affected area / extension

Platform(Default)

### Actual behaviour

The currency modal is small now. You need to scroll right to see all the information.

### Expected behaviour

Make the modal large so that all the information can be easily seen.

### How to reproduce

Go to product detail
In the price card 
Click to `Currency dependent pricing `

Image

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### LINKED ISSUE #10022: Removing properties value doesn't work in production detail
### Shopware Version

6.7

### Affected area / extension

Platform(Default)

### Actual behaviour

Removing the property values doesn't work in production detail

### Expected behaviour

Can remove property values

### How to reproduce

Go to product detail
Go to Specifications tabs
In the Properties cards
Click to "X" remove icon, then nothing happens

Image

### LINKED ISSUE #10070: change behavior of bulk edit variants product of properties
### Shopware Version

6.7

### Affected area / extension

Platform(Default)

### Actual behaviour

When inherited enabled, changing properties doesn't disable

### Expected behaviour

Disabled properties changed when inherited, enabled

### How to reproduce

Bulk edit variants
change the Properties card 

Image

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by nguyenquocdaile**
Fix some of these issues:

chore: #9993 
Fixes: #10070
Fixes: #10022

### CODE REVIEW

File: src/Administration/Resources/app/administration/src/module/sw-product/component/sw-product-properties/index.js [hunk 1]
```diff
@@ -182,6 +182,7 @@ export default {
 
         onDeletePropertyValue(propertyValue) {
             this.productProperties.remove(propertyValue.id);
+            this.getProperties();
```
Comment (sydinh) [inline src/Administration/Resources/app/administration/src/module/sw-product/component/sw-product-properties/index.js:185]: missing tests for this addition...

**Review by sydinh — CHANGES_REQUESTED** [review]

**Review by sydinh — APPROVED** [review]

**Review by vienthuong — APPROVED** [review]

**Review by nguyenytran — APPROVED** [review]
