### PR TITLE
fix: remove empty alllineitemscontainer

### LINKED ISSUE #10532: All line item container does not remove container on delete
### Shopware Version

6.7.0.0-RC.5

### Affected area / extension

Platform(Default)

### Actual behaviour

Page broken after removing an "Items In Shopping cart" condition -> "All" container

### Expected behaviour

Expect the page not to break from removing the condition

### How to reproduce

Inside Rule builder 

1. I add a rule condition of the `lineItem` scope ("Items In Shoping Cart" group). e.g. Item Available
2. Choose "All" sub-condition
3. Any other setting (doesn't matter)
4. Click "Add And condition" button
5. Add any rule, e.g. Always Valid - Yes
6. Delete the first rule condition we created. Click on the "..." -> Delete
7. Fill in the Name & property values
8. Save
9. UI broken

Location of error:
src/Administration/Resources/app/administration/src/app/component/rule/sw-condition-all-line-items-container/index.js:82
```
setConditionValue() {
            this.condition.value = [];
            if (this.children.first().type === 'promotionLineItem') { // line 82
```

Error: `TypeError: Cannot read properties of null (reading 'type')`

Here is the payload that gets saved, please note that the `allLineItemsContainer` is still there despite being deleted & expects to have children, but does not:

```
POST http://localhost:5173/api/rule
{
    "id": "0197706cc65b76068ea2dfc846074409",
    "name": "T1",
    "priority": 5,
    "conditions": [
        {
            "id": "0197706cc6647344a02ff9f51e2a84c6",
            "type": "orContainer",
            "ruleId": "0197706cc65b76068ea2dfc846074409",
            "value": {},
            "position": 0,
            "children": [
                {
                    "id": "0197706cc66576fca26d1d79f7e77b7a",
                    "type": "andContainer",
                    "ruleId": "0197706cc65b76068ea2dfc846074409",
                    "parentId": "0197706cc6647344a02ff9f51e2a84c6",
                    "value": {},
                    "position": 0,
                    "children": [
                        {
                            "id": "0197706cec9f7e28bb5db25fc4895209",
                            "type": "allLineItemsContainer",
                            "ruleId": "0197706cc65b76068ea2dfc846074409",
                            "parentId": "0197706cc66576fca26d1d79f7e77b7a",
                            "value": {
                                "type": "product"
                            },
                            "position": 0
                        },
                        {
                            "id": "0197706cf0657511b9b1f2e07f314664",
                            "type": "alwaysValid",
                            "ruleId": "0197706cc65b76068ea2dfc846074409",
                            "parentId": "0197706cc66576fca26d1d79f7e77b7a",
                            "position": 1
                        }
                    ]
                }
            ]
        }
    ]
}
```

Suggested fix:
src/Administration/Resources/app/administration/src/app/component/rule/sw-condition-all-line-items-container/index.js

```
        childType(type) {
            if (!type) {
                this.removeNodeFromTree(this.parentCondition, this.condition); // add this at line 57
                return;
            }
```

I tested this fix locally with many different variations of containers and sub-containers, but I am not sure to test this automatically / properly. Hence why I am not opening a PR myself.

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by ennasus4sun**
**issue:**

- empty allLineItemsContainer wrapper persisted after condition was deleted

**root cause:**

- `children` watcher wasnt executed because just the object references are compared

**solution:**

- watch length property of object

- closes [#10532](https://github.com/shopware/shopware/issues/10532)

### CODE REVIEW

File: src/Administration/Resources/app/administration/src/app/component/rule/sw-condition-all-line-items-container/index.js [hunk 1]
```diff
@@ -65,6 +63,12 @@ export default {
             }
             this.setConditionValue();
         },
+
+        childrenLength(length) {
```
Comment (larskemper) [inline src/Administration/Resources/app/administration/src/app/component/rule/sw-condition-all-line-items-container/index.js:67]: Using a watcher for this souds a little overkill. This if statement should be at the end of some method that causes the reduction of the length. Is it possible to get rid of this easily?😅 When not it's ok for me.

File: src/Administration/Resources/app/administration/src/app/component/rule/sw-condition-all-line-items-container/sw-condition-all-line-items-container.spec.js [hunk 2]
```diff
@@ -107,4 +107,24 @@ describe('src/app/component/rule/sw-condition-and-container', () => {
         expect(createCondition).toHaveBeenCalled();
         expect(insertNodeIntoTree).toHaveBeenCalled();
     });
+
+    it('should remove empty wrapper when children are deleted', async () => {
+        const wrapper = await createWrapper();
+        expect(wrapper.vm.childrenLength).toBe(1);
```
Comment (larskemper) [inline src/Administration/Resources/app/administration/src/app/component/rule/sw-condition-all-line-items-container/sw-condition-all-line-items-container.spec.js:206]: Try not to use any `wrapper.vm.[...]` in jest tests, cause we also want to test the "interaction-layer” and want to try to test the ui like the user would use it. So e.g. it would be better to count the rendered childs in the dom, so we make sure their actually rendered...

File: src/Administration/Resources/app/administration/src/app/component/rule/sw-condition-all-line-items-container/sw-condition-all-line-items-container.spec.js [hunk 3]
```diff
@@ -107,4 +107,24 @@ describe('src/app/component/rule/sw-condition-and-container', () => {
...
+
+        const updatedCondition = { ...wrapper.props().condition };
+        updatedCondition.children = new EntityCollection('', 'rule_condition', Shopware.Context.api, null, []);
+        await wrapper.setProps({ condition: updatedCondition });
+        await wrapper.vm.$nextTick();
```
Comment (larskemper) [inline src/Administration/Resources/app/administration/src/app/component/rule/sw-condition-all-line-items-container/sw-condition-all-line-items-container.spec.js]: You propably dont need this or try to use `await flushPromises();` instead

File: src/Administration/Resources/app/administration/src/app/component/rule/sw-condition-all-line-items-container/index.js (hunk 1 above)
Comment (ennasus4sun) [reply src/Administration/Resources/app/administration/src/app/component/rule/sw-condition-all-line-items-container/index.js:67]: result: in a call we decide to keep that solution as it is.

File: src/Administration/Resources/app/administration/src/app/component/rule/sw-condition-all-line-items-container/sw-condition-all-line-items-container.spec.js [hunk 4]
```diff
@@ -107,4 +107,24 @@ describe('src/app/component/rule/sw-condition-and-container', () => {
         expect(createCondition).toHaveBeenCalled();
         expect(insertNodeIntoTree).toHaveBeenCalled();
     });
+
+    it('should remove empty wrapper when children are deleted', async () => {
```
Comment (MalteJanz) [inline src/Administration/Resources/app/administration/src/app/component/rule/sw-condition-all-line-items-container/sw-condition-all-line-items-container.spec.js:112]: Btw there is already a very similar test:
https://github.com/shopware/shopware/blob/3a5e65dcdabb10ed980617f25f304c334b21f489/src/Administration/Resources/app/administration/src/app/component/rule/sw-condition-all-line-items-container/sw-condition-all-line-items-container.spec.js#L82-L89

And I guess that was green all the time, otherwise we wouldn't have the bug right 🙈? Have you checked if this new test actually fails if you revert your component implementation changes?

*It might already fail because you don't have the computed `childrenLength` anymore then. That's also part of the reason why Lars suggested to not test the component internals (implementation details) but rather the interactions with the DOM. Because like in this case changing an implementation detail will already cause tests to fail, even though the component might still work fine.

Testing this component in isolation while just using the DOM might not be easily possible. Alternatively you could test only the outer layers of the component (it's props and events)

**Review by DennisGarding — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/app/component/rule/sw-condition-all-line-items-container/sw-condition-all-line-items-container.spec.js (hunk 2 above)
Comment (ennasus4sun) [reply src/Administration/Resources/app/administration/src/app/component/rule/sw-condition-all-line-items-container/sw-condition-all-line-items-container.spec.js:206]: done ✅ 
I would have liked to check via the DOM to see if the current empty wrapper had been removed (all-line-items), but that doesn't seem to be possible because the parent div (and-container) is not rendered when mounting just `sw-condition-all-line-items-container`...
But here I check if `removeNodeFromTree` is called with the expected params: https://github.com/shopware/shopware/pull/11084/files#diff-183a9ecdb5a4246399e5671c64b228c91a6f27046b325f79f2c60c8c929ac33fR231-R236

what do you think about?

**Review by jozsefdamokos — APPROVED** [review]

**Review by CR0YD — APPROVED** [review]

**Review by GitEvil — APPROVED** [review]
