### PR TITLE
fix: render documents with uppercase file extension

### LINKED ISSUE #8257: Order documents can not be rendered if file extension of media entity is with big letters "PDF"
### Shopware Version

6.6.10.2

### Affected area / extension

Platform(Default)

### Actual behaviour

I have a order document media entity with file extension with big letters: "PDF".
But then the order document can not be rendered.
The document was imported via api. That is the reason of the big letters.

### Expected behaviour

The order document should also be rendered if the file extension of the media entity is with big letters "PDF".
This was before Shopware 6.6.10.0. Now it is not working anymore.

### How to reproduce

Set the file extension of the document media entity to big letters "PDF".
Then go to the order and try to preview the document via the admin.
Same issue happens also if the customer wants to open the document via the storefront order history.

The issue is in this line:
$media?->getFileExtension() === strtolower($fileType)

It casts the $fileType with strtolower, but the $media?->getFileExtension() is not changed to strtolower.
This should also be casted to strtolower.

File: core/Checkout/Document/Service/DocumentGenerator.php - Line 393.

### PR DESCRIPTION
**Pull request by larskemper**
fixes #8257

### CODE REVIEW

File: tests/integration/Core/Checkout/Document/Service/DocumentGeneratorTest.php [hunk 1]
```diff
@@ -973,6 +973,54 @@ public static function readDocumentDataProvider(): \Generator
...
+                'fileName' => 'textFileWithExtension',
+                'fileSize' => 1024,
+                'private' => true,
+                'mediaType' => new BinaryType(),
+                'uploadedAt' => new \DateTimeImmutable('2011-01-01T15:03:01.012345Z'),
+            ],
+        ]], $this->context);
+
+        $criteria = (new Criteria([$documentId]))->addAssociation('documentMediaFile');
+        /** @var DocumentEntity $document */
```
Comment (mitelg) [inline tests/integration/Core/Checkout/Document/Service/DocumentGeneratorTest.php]: please do not use var annotations. Especially in tests you can simply assert the type. also see https://github.com/shopware/shopware/blob/trunk/coding-guidelines/core/writing-code-for-static-analysis.md

**Review by jozsefdamokos — APPROVED** [review]

**Review by ennasus4sun — APPROVED** [review]
