### PR TITLE
fix: ZUGFeRD download label and filename

### LINKED ISSUE #14838: Administration: Button label says “Create and download PDF” but downloads ZUGFeRD XML (filename null.xml)
### Shopware Version

6.7.7.1

### Affected area / extension

Platform(Default)

### Actual behaviour

"Create and download PDF", but it is an xml file.

Image

The file is named null.xml, not, e.g.,  {{invoice-number}}.xml

### Expected behaviour

Add Administration snippet for e-invoice or rename the existing snippet.

Change file name to, e.g., {{invoice-number}}.xml, but not null.

### How to reproduce

Create an e-invoice in the Administration and download it.

The null.xml filename only occurs when clicking on "Create and download PDF".

### PR DESCRIPTION
**Pull request by vintagesucks**
resolves #14838

The "Create and download" button always showed "PDF" and the downloaded file was named `null.xml` for ZUGFeRD e-invoices.

### CODE REVIEW

File: src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-document-card/index.js [hunk 1]
```diff
@@ -409,7 +413,8 @@ export default {
                 }
 
                 if (additionalAction === 'download') {
-                    this.downloadDocument(documentId, documentDeepLink);
+                    const fileType = this.isXmlDocument ? 'xml' : 'pdf';
```
Comment (jozsefdamokos) [inline src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-document-card/index.js:416]: I know currently we only have these 2 types, but maybe worth considering for extendability or possible future additions a mapping of technical names to their file types instead. wdyt?

File: src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-document-settings-modal/sw-order-document-settings-modal.html.twig [hunk 2]
```diff
@@ -206,7 +206,7 @@
                         data-analytics-id="sw-order-document-settings-modal.create-document-and-download-pdf"
                         @click="onCreateDocument('download')"
                     >
-                        {{ $tc('sw-order.documentModal.labelCreateDownloadPdf') }}
+                        {{ isXmlDocument ? $t('sw-order.documentModal.labelCreateDownloadXml') : $t('sw-order.documentModal.labelCreateDownloadPdf') }}
```
Comment (jozsefdamokos) [inline src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-document-settings-modal/sw-order-document-settings-modal.html.twig]: `Create and download` or `Create and download file` would also be enough I guess

**Review by jozsefdamokos — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-document-card/index.js (hunk 1 above)
Comment (MalteJanz) [reply src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-document-card/index.js:416]: I also don't really like this hard coding of types here, but I also wouldn't spend too much effort on changing it right now and I'm fine with merging it like this.

We will kick off our [new epic about documents](https://github.com/shopware/shopware/issues/14823) on Monday in the weekly planning, and part of that epic will also be [refactoring all of this mess](https://github.com/shopware/shopware/issues/14833) 🤞

**Review by MalteJanz — APPROVED** [review]

**Review by jozsefdamokos — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-order/snippet/de.json [hunk 3]
```diff
@@ -436,6 +436,7 @@
       "selectInvoiceNumber": "Rechnung wählen",
       "labelDeliveryNoteNumber": "Lieferscheinnummer",
       "labelDocumentComment": "Kommentar",
+      "labelCreateDownload": "Erstellen und herunterladen",
       "labelCreateDownloadPdf": "Erstellen und PDF herunterladen",
```
Comment (vintagesucks) [inline src/Administration/Resources/app/administration/src/module/sw-order/snippet/de.json:440]: kept the old snippet for now, added to #9063 for 6.8 cleanup
