### PR TITLE
fix: respect main variant that chose in the storefront presentation

### LINKED ISSUE #13901: Request for Reopen: Filtered listing does not respect mainVariant setting
### Shopware Version

6.6.10.1

### Affected area / extension

Platform(Default)

### Actual behaviour

Issue https://github.com/shopware/shopware/issues/4586 is causing real usability problems. 
All information, also a reference to the code which is causing the bug is provided in that issue. So please reopen that to keep the discussion there.

Can't see why this is considered low priority.

Also, see another request here:
https://github.com/shopware/shopware/issues/8302

### Expected behaviour

see https://github.com/shopware/shopware/issues/4586

### How to reproduce

see https://github.com/shopware/shopware/issues/4586

### PR DESCRIPTION
**Pull request by rittou**
### Respect storefront preview configuration unless “find best variant” is enabled

**Problem**

When a product listing was filtered by variant options, the configured storefront preview product, meaning main variant or parent, was no longer used consistently. This made the behavior hard to predict and not aligned with the product setting that controls whether the best matching variant should be shown.

**Solution**

We aligned preview resolution with the findBestVariant setting. 
- If it is disabled, listings and search results continue to use the configured storefront preview product, even with option filters. 
- If it is enabled, preview remapping is skipped and the best matching filtered variant is shown instead. 

The setting label and help text were also clarified to describe this behavior more clearly.

### CODE REVIEW

**Comment by rittou** [comment]
## Triage result

Core regression in storefront listing preview resolution: option/property filters bypass `variantListingConfig.mainVariantId`, so the configured storefront main variant is ignored after filtering.

## Issue summary

- shopware version: `6.6.5.1` reported, still confirmed in `6.6.9.0`
- affected area: `Storefront product listing / ProductListingLoader preview mapping`
- symptom: Applying a property/option filter can replace the configured main variant with another matched child variant.
- impact: Storefront presentation becomes inconsistent after filtering and can show a different variant than the configured storefront main variant.

## Problem statement

Issue [#4586](https://github.com/shopware/shopware/issues/4586) reports that a product with a configured storefront main variant shows the correct variant until a property filter is applied, then switches to another variant even when the main variant also satisfies the filter. A later confirmation in the issue says the bug still exists in `6.6.9.0` and points directly to the option-filter guard in `ProductListingLoader`. Local code history supports that diagnosis: preview loading is skipped for option-filter cases, so `variantListingConfig.mainVariantId` never participates in the filtered listing mapping.

## Reproduction

1. Configure a main variant in the storefront presentation.
2. Open the storefront listing/category page and confirm the configured main variant is shown.
3. Apply a property filter that the main variant also has.
4. Observe that the listing switches to another variant instead of keeping the configured main variant.

## Root cause

- `hasOptionFilter()` inspects post-filters for `product.options.id` / `optionIds`; once true, the older logic returned `false` from `shouldLoadPreviews()`, which skipped `loadPreviews()`.
- Skipping `loadPreviews()` means `variantListingConfig.mainVariantId` is not applied to the listing result, so the matched child variant is rendered instead of the configured storefront main variant.
- The regression was introduced by [`6a1d69c62649804b0e5d5e967f3c4c8dfe89d122`](https://github.com/shopware/shopware/commit/6a1d69c62649804b0e5d5e967f3c4c8dfe89d122) (`feat: changed ProductListingLoader to show found product variant instead of the preview variant (#11107)`), which added `shouldLoadPreviews()` and the option-filter short-circuit.
- The branch fix in [`2dfa94a9b23f6268297e4502188c6a15644510f1`](https://github.com/shopware/shopware/commit/2dfa94a9b23f6268297e4502188c6a15644510f1) restores preview loading for the option-filter case.
- confidence: `high`

## Regression history

- introducing change: [`6a1d69c62649804b0e5d5e967f3c4c8dfe89d122`](https://github.com/shopware/shopware/commit/6a1d69c62649804b0e5d5e967f3c4c8dfe89d122)
- related change: [`2dfa94a9b23f6268297e4502188c6a15644510f1`](https://github.com/shopware/shopware/commit/2dfa94a9b23f6268297e4502188c6a15644510f1), [PR #15844](https://github.com/shopware/shopware/pull/15844), [issue #4586](https://github.com/shopware/shopware/issues/4586)

## Recommended fix direction

- Keep preview loading enabled for option-filter cases so `variantListingConfig.mainVariantId` is still respected when a filtered variant belongs to a product with configured storefront presentation.
- Important tradeoff: this aligns `postFilter` behavior with the already-existing `filter` behavior, but it also preserves the broader product-family rule that the displayed card may still be the configured main variant rather than the exact matching child variant. If product expectations are “green filter must render green variant”, that requires a broader semantic change than this patch.

## Validation

- tests to add/update: keep `testMainVariantAndVariantGroupsWithPostFilterOnOptions()` and `testPostFilterOnOptionsWithoutMainVariantShowsFilteredVariant()`; consider adding a search-route case with `core.listing.findBestVariant=true` so the intended precedence is explicit.
- manual verification: verify category and search listings with no filter, with a property the main variant also has, and with a property only another child has; confirm the chosen semantics are intentional.
- rollback plan: revert [`2dfa94a9b23f6268297e4502188c6a15644510f1`](https://github.com/shopware/shopware/commit/2dfa94a9b23f6268297e4502188c6a15644510f1) if reviewers decide filtered listings must prefer the exact matching child variant and redesign preview mapping accordingly.

## Routing

- label: `priority/low`
- domain: `domain/inventory`
- team: `unknown`
- effort: `easy`
- evidence: `ProductListingLoader` is in `#[Package('inventory')]`; the issue is a storefront listing regression caused by preview-loading control flow introduced in [`6a1d69c62649804b0e5d5e967f3c4c8dfe89d122`](https://github.com/shopware/shopware/commit/6a1d69c62649804b0e5d5e967f3c4c8dfe89d122).

**Review by ngocblue — APPROVED** [review]
Test Date: 6 Apr 2026
Test Status: **PASSED**
Browser: Chrome, Safari, Firefox

- When setting 'Preview best matching variant in search results and filtered listings' is Disabled
+ Always display setup Main Variant before and after filter
+ Also display Main Variant when filter and only child product matches property
https://github.com/user-attachments/assets/1ad6119d-c7a5-427c-b56d-c7cfd531fcb2

- When setting 'Preview best matching variant in search results and filtered listings' is Disabled
+ Display Main Variant in Listing page but will display matched variant after filter
https://github.com/user-attachments/assets/a14dd545-889f-4f9b-b0c0-cfa49e761e2b

File: src/Core/Content/Product/SalesChannel/Listing/ProductListingLoader.php
Comment (tamvt) [inline src/Core/Content/Product/SalesChannel/Listing/ProductListingLoader.php:110]: hasOptionFilter() is now a misleading name, because it also checks property filters. Maybe renaming it would make the intent clearer.

**Review by tamvt — APPROVED** [review]

File: RELEASE_INFO-6.7.md [hunk 1]
```diff
@@ -6,6 +6,10 @@
 
 ## Core
 
+### Respect storefront preview configuration unless “find best variant” is enabled
```
Comment (vienthuong) [inline RELEASE_INFO-6.7.md]: I'd rephrase it as "Find best variant setting is now applied for storefront filtering"

**Review by vienthuong — APPROVED** [review]

File: src/Core/Content/Product/SalesChannel/Listing/ProductListingLoader.php
Comment (rittou) [reply src/Core/Content/Product/SalesChannel/Listing/ProductListingLoader.php:110]: I'd love to keep it still for now, since it's not a big deal compared to the BC check with the event `ProductListingResolvePreviewEvent` if we change it.
