### PR TITLE
fix: Fix styling of sw-app-app-url-changed-modal; Update app url change description

### LINKED ISSUE #8312: Domain change modal visually broken
### Shopware Version

6.7 RC

### Affected area / extension

Platform(Default)

### Actual behaviour

The text in the options for choosing the resolution strategy is not properly formatted.

Image

### Expected behaviour

The text in the options for choosing the resolution strategy is properly formatted.

Image

### How to reproduce

1. Check out current `trunk`
2. Modify `AppUrlChangeDetectedController::getUrlDifference` to `throw new AppUrlChangeDetectedException('http://localhost:8000', 'http://localhost:8001', 'shop-id');`
3. Log in to the Administration
4. The modal pops up

### PR DESCRIPTION
**Pull request by SebastianFranze**
!fixes #8312

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [X] I have read the contribution requirements and fulfill them.

### CODE REVIEW

File: src/Administration/Resources/app/administration/src/app/component/app/sw-app-app-url-changed-modal/index.js [hunk 1]
```diff
@@ -72,24 +72,25 @@ Component.register('sw-app-app-url-changed-modal', {
...
+        async confirm() {
+            try {
+                await this.appUrlChangeService.resolveUrlChange(this.selectedStrategy);
+
+                this.createNotificationSuccess({
+                    message: this.$tc('sw-app.component.sw-app-app-url-changed-modal.success'),
+                });
+
+                // shop url could have changed
+                window.location.reload();
```
Comment (fschmtt) [inline src/Administration/Resources/app/administration/src/app/component/app/sw-app-app-url-changed-modal/index.js:88]: The reload is necessary because the admin needs to initialize again e.g. so that app modules are rendered etc., right?

**Review by fschmtt — APPROVED** [review]

**Review by MoritzKrafeld — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/app/component/app/sw-app-app-url-changed-modal/index.js (hunk 1 above)
Comment (SebastianFranze) [reply src/Administration/Resources/app/administration/src/app/component/app/sw-app-app-url-changed-modal/index.js:88]: No, but I'm too lazy to add a new controller to update the shopId in the store :kekw:

It would also be okay to just update this one field in #8606

Comment (SebastianFranze) [reply src/Administration/Resources/app/administration/src/app/component/app/sw-app-app-url-changed-modal/index.js:88]: We could also think of returning the new shopId and app url from `api/app-system/app-url-change/resolve` :thinking:
