### PR TITLE
fix: replace theme media sidebar with media modal

### LINKED ISSUE #9055: Theme settings should use media modal
### Shopware Version

6.79

### Affected area / extension

Platform(Default)

### Actual behaviour

Theme editor uses old media sidebar and is therefore inconsistent with other components

### Expected behaviour

Open the normal media modal to choose media

### How to reproduce

Open the settings of the theme and pick a logo

### PR DESCRIPTION
**Pull request by bschulzebaek**
### 1. Why is this change necessary?
The theme module is still using the sidebar for handling media references, which makes is inconsistent with the rest of the admin. 

### 2. What does this change do, exactly?
* Replace the sidebar with the `sw-media-modal-v2`. 
* Deprecate the sidebar related blocks in `sw-theme-manager-detail`

### 3. Describe each step to reproduce the issue or behaviour.
Editing any media fields on a theme detail pages opens the Sidebar.

### 4. Please link to the relevant issues (if any).
- closes https://github.com/shopware/shopware/issues/9055

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfill them.

### CODE REVIEW

**Review by marcelbrode — APPROVED** [review]

File: src/Storefront/Resources/app/administration/src/modules/sw-theme-manager/page/sw-theme-manager-detail/index.js [hunk 1]
```diff
@@ -243,6 +245,9 @@ Component.register('sw-theme-manager-detail', {
             });
         },
 
+        /**
+         * @deprecated tag:v6.8.0 - This method will be removed.
```
Comment (MartinKrzykawski) [inline src/Storefront/Resources/app/administration/src/modules/sw-theme-manager/page/sw-theme-manager-detail/index.js:249]: Deprecations should also be included into a changelog

**Review by MartinKrzykawski — APPROVED** [review]
