### PR TITLE
fix: restore Symfony's Kernel::handle behavior to support ResetInterf…

### LINKED ISSUE #11215: Missing ResetInterface handling in Shopware Kernel (affects FrankenPHP and long-running processes)
### Shopware Version

6.7.0.1

### Affected area / extension

Platform(Default)

### Actual behaviour

Shopware’s Kernel::handle() implementation does not reset services implementing Symfony\Contracts\Service\ResetInterface, nor does it invoke the services_resetter as Symfony does by default.
This may lead to unexpected behavior in long-running environments (like FrankenPHP), where the same Kernel instance handles multiple requests without resetting stateful services.

### Expected behaviour

Expected behaviour:
On subsequent requests (after the kernel has already been booted), Shopware should trigger services_resetter to reset services tagged with ResetInterface, as Symfony does inside [Kernel::boot()](https://github.com/symfony/http-kernel/blob/7.3/Kernel.php#L169-L177).

### How to reproduce

How to reproduce:

1. Set up a Symfony/Shopware project with a service that implements ResetInterface.
2. Run the application via [FrankenPHP](https://github.com/dunglas/frankenphp) or any long-running runtime using Runtime\FrankenPhpSymfony\Runner.
3. Make multiple requests to the same application process.
4. Observe that the service is not reset between requests.

Related discussion on Slack:
[https://shopwarecommunity.slack.com/archives/C011VFQT7GB/p1752490431943509](https://shopwarecommunity.slack.com/archives/C011VFQT7GB/p1752490431943509)

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by mateuszfl**
### 1. Why is this change necessary?

Shopware overrides `Kernel::handle()` and bypasses Symfony’s built-in reset mechanism for services implementing `Symfony\Contracts\Service\ResetInterface`.

This causes unexpected behavior in long-running runtimes (e.g. FrankenPHP, RoadRunner), where the same kernel instance handles multiple requests without resetting internal state.

### 2. What does this change do, exactly?

Instead of removing Kernel::handle(), we now keep a custom implementation that directly calls $this->boot() (instead of Symfony’s internal handle() logic that checks for http_cache). This ensures that Symfony’s boot() lifecycle (including services_resetter) is invoked, while avoiding any side effects caused by Symfony’s internal HTTP cache handler.

### 3. Describe each step to reproduce the issue or behaviour.

1. Create a service that implements `ResetInterface`.
2. Boot Shopware inside a long-lived runtime (e.g. FrankenPHP).
3. Send two HTTP requests in a row — observe that `reset()` is **not called** between requests.
4. Apply this patch.
5. Observe that `reset()` is now properly called before each new request.

### 4. Please link to the relevant issues (if any).

- closes [#11215](https://github.com/shopware/shopware/issues/11215)
- Related Slack thread: https://shopwarecommunity.slack.com/archives/C011VFQT7GB/p1752490431943509

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Core/Kernel.php [hunk 1]
```diff
@@ -120,41 +120,22 @@ public function getProjectDir(): string
         return $this->projectDir;
     }
 
-    public function handle(Request $request, int $type = HttpKernelInterface::MAIN_REQUEST, bool $catch = true): Response
```
Comment (shyim) [inline src/Core/Kernel.php:123]: thats not going to work. we don't want to have this call

https://github.com/symfony/symfony/blob/7.4/src/Symfony/Component/HttpKernel/Kernel.php#L172-L174

Comment (mateuszfl) [reply src/Core/Kernel.php:123]: @shyim Thanks for the clarification! I've adjusted the PR to retain our custom `handle()` method while still calling `boot()` directly. This ensures that Symfony's `ResetInterface` support works as expected, without triggering the internal `http_cache` mechanism.

Let me know if you'd prefer a different strategy!

File: changelog/_unreleased/2025-07-14-restore-kernel-handle-resetinterface.md [hunk 2]
```diff
@@ -0,0 +1,8 @@
+### Changed
```
Comment (shyim) [inline changelog/_unreleased/2025-07-14-restore-kernel-handle-resetinterface.md]: this changelog does not match the schema
https://github.com/shopware/shopware/blob/trunk/changelog/_example.md

you can run also `bin/console changelog:check` locally to check it

Comment (mateuszfl) [reply changelog/_unreleased/2025-07-14-restore-kernel-handle-resetinterface.md]: @shyim 
Thanks for the heads-up!
I’ve updated the changelog to follow the correct schema as outlined in the example and validated it locally using bin/console changelog:check.
Let me know if anything else needs to be adjusted.

**Review by shyim — APPROVED** [review]

**Review by mitelg — APPROVED** [review]

**Comment by mitelg** [comment]
thanks for your contribution @mateuszfl 👍🎉💙

the backport is already created and will also be merged soon :+1: https://github.com/shopware/shopware/pull/11546
