### PR TITLE
fix: import with configurated CDN and non-seekable streams

### LINKED ISSUE #15853: Import csv does not work when using external storage
### Shopware Version

6.7.7.1

### Affected area / extension

Platform(Default)

### Actual behaviour

We are using Azure storage for filesystem. When I try to import a file from the import/export settings, I get the following error
```
php.ERROR: Warning: fseek(): Stream does not support seeking {"exception":"[object] (ErrorException(code: 0): Warning: fseek(): Stream does not support seeking at /shopware/vendor/shopware/core/Content/ImportExport/Processing/Reader/CsvReader.php:156)"} []
```

I also found an old PR with similar issue but the PR only fixed issues with export, import still does not work. https://github.com/shopware/shopware/pull/3288/files

### Expected behaviour

Importing a csv file works even while using external storage systems

### How to reproduce

1. Create an import profile on a system using external storage.
2. Export the profile (works).
3. Change some data and iImport the profile - on import/export status it shows succeeded but actually the import fails with the above mentioned error.

### PR DESCRIPTION
**Pull request by DennisGarding**
closes: #15853

Fixes CSV imports when the input stream is not seekable, for example, when the file comes from remote storage / CDN setups instead of a local filesystem.

for Testing: 
### Install the plugin with a fake adapter (fakes reading from CDN with a non-seekable stream)

[FakeHttpS3FilesystemAdapter.zip](https://github.com/user-attachments/files/26972930/FakeHttpS3FilesystemAdapter.zip)

### Create a Docker CDN:
```
    minio:
        image: minio/minio
        ports:
            - "9080:9000" # API Port
            - "9081:9001" # Web-Konsole
        environment:
            MINIO_ROOT_USER: <yourUSER>
            MINIO_ROOT_PASSWORD: <yourPW>
        command: server /data --console-address ":9001"
        volumes:
            - ./minio_data:/data
```

### Configure  shopware:

```
shopware:
  filesystem:
    private:
      type: "fake-http-s3"
      visibility: "private"
      config:
        bucket: "shopware-bucket"
        region: "us-east-1"
        endpoint: "http://127.0.0.1:9080"
        use_path_style_endpoint: true
        credentials:
          key: "<yourUSER>"
          secret: "<yourPW>"

    public:
      type: "amazon-s3"
      visibility: "public"
      config:
        bucket: "shopware-bucket"
        region: "us-east-1"
        endpoint: "http://127.0.0.1:9080"
        use_path_style_endpoint: true
        credentials:
          key: "<yourUSER>"
          secret: "<yourPW>"
```

### CODE REVIEW

File: src/Core/Content/ImportExport/Processing/Reader/CsvReader.php [hunk 1]
```diff
@@ -10,6 +11,9 @@ class CsvReader extends AbstractReader
 {
     private const BOM_UTF8 = "\xEF\xBB\xBF";
 
+    // Use 1 KB chunk when skipping forward on non-seekable streams.
+    private const SEEK_CHUNK_SIZE = 1024;
```
Comment (larskemper) [inline src/Core/Content/ImportExport/Processing/Reader/CsvReader.php]: 1kb feels a little small. Standard io block size is 4kb or 8kb

File: src/Core/Content/ImportExport/Processing/Reader/CsvReader.php [hunk 2]
```diff
@@ -149,12 +154,74 @@ private function mapRecord(array $record): ?array
...
+    }
+
+    /**
+     * @param resource $resource
+     */
+    private function getCurrentOffset($resource): int
+    {
+        $offset = ftell($resource);
+
+        if ($offset === false) {
```
Comment (larskemper) [inline src/Core/Content/ImportExport/Processing/Reader/CsvReader.php:220]: returning `0` when `ftell() === false` silently makes the reader treat a mid stream position as offset `0`. Is that intentional?

also is this case covered by a test?

Comment (DennisGarding) [reply src/Core/Content/ImportExport/Processing/Reader/CsvReader.php:220]: Yes, it is intended. This is easier to handle if you call the function. You don't have to check for null each time. 

And yes, there are multiple tests that cover this indirectly. 
CsvReaderTest::testReadsNonSeekableStream
CsvReaderTest::testIncrementalReadOnNonSeekableStream
CsvReaderTest::testIncrementalReadOnNonSeekableStreamWithOffsetLargerThanSeekChunkSize

**Review by jozsefdamokos — APPROVED** [review]

**Review by MalteJanz — APPROVED** [review]

**Review by larskemper — APPROVED** [review]
