### PR TITLE
fix: tax calculation for bulk edit price when not set

### LINKED ISSUE #14308: Bulk edit with locked price (auto tax calculation) does not account for selected tax rates
### Shopware Version

6.6.10.10 & 6.7.5.1

### Affected area / extension

Platform(Default)

### Actual behaviour

When you bulk edit a product or multiple products that do not use the default tax rate, then the calculated net or gross price will be set to the equivalent according to the default tax rate. Meaning it will set a wrong price when the product has a different tax rate assigned.

Example, before bulk edit, setting gross to 11€:

Image

After bulk edit, setting gross to 11€:

Image

### Expected behaviour

The bulk edit would account for the individual tax rate for each product

### How to reproduce

- Create a product with a different tax rate than default (i.e. super reduced) and set a price
- Set the same or a different gross price via bulk edit without touching the net price or the tax rate
- Observe the wrong net price being set

### PR DESCRIPTION
**Pull request by nguyenquocdaile**
This pull request enhances the bulk edit functionality for products by ensuring that when a price-related field is changed, the corresponding `taxId` is automatically included in the update if it hasn't been explicitly changed by the user. This helps prevent inconsistencies and ensures tax information stays in sync with price changes. Additionally, a new test has been added to verify this behavior.

**Bulk edit logic improvements:**

* Added a check in `onProcessData` to detect changes to any price-related fields (`price`, `purchasePrices`, `listPrice`, `regulationPrice`). If such a change is detected and the `taxId` hasn't been explicitly modified, the default `taxId` is automatically added to the bulk edit selection. [[1]](diffhunk://#diff-6f5d780ac16aff8423ac70fc38f2be2bb6a8c8f8da155948ca78a2c2e77cb783R1141) [[2]](diffhunk://#diff-6f5d780ac16aff8423ac70fc38f2be2bb6a8c8f8da155948ca78a2c2e77cb783R1151-R1169) [[3]](diffhunk://#diff-6f5d780ac16aff8423ac70fc38f2be2bb6a8c8f8da155948ca78a2c2e77cb783R1214-R1221)

### CODE REVIEW

File: src/Administration/Resources/app/administration/src/module/sw-bulk-edit/page/sw-bulk-edit-product/index.js [hunk 1]
```diff
@@ -1249,6 +1249,7 @@ export default {
             const context = {
                 'sw-measurement-length-unit': this.lengthUnit,
                 'sw-measurement-weight-unit': this.weightUnit,
+                'bulk-edit-default-tax-with-price': !this.isChild,
```
Comment (sydinh) [inline src/Administration/Resources/app/administration/src/module/sw-bulk-edit/page/sw-bulk-edit-product/index.js]: Does the target API accept this new header option?

@vienthuong @rittou @nguyenquocdaile

File: src/Administration/Resources/app/administration/src/module/sw-bulk-edit/service/handler/bulk-edit-product.handler.js [hunk 2]
```diff
@@ -21,8 +21,9 @@ class BulkEditProductHandler extends BulkEditBaseHandler {
         this.products = {};
     }
 
-    async bulkEdit(entityIds, payload, context) {
+    async bulkEdit(entityIds, payload, context = {}) {
         this.entityIds = entityIds;
+        const hadTaxIdChange = payload.some((change) => change.field === 'taxId');
```
Comment (sydinh) [inline src/Administration/Resources/app/administration/src/module/sw-bulk-edit/service/handler/bulk-edit-product.handler.js]:
```suggestion
        const hasTaxIdChange = payload.some((change) => change.field === 'taxId');
```

File: src/Administration/Resources/app/administration/src/module/sw-bulk-edit/service/handler/bulk-edit-product.handler.js [hunk 3]
```diff
@@ -44,6 +45,22 @@ class BulkEditProductHandler extends BulkEditBaseHandler {
             payload = payload.filter((change) => change.field !== 'price' && change.field !== 'purchasePrices');
         }
 
+        if (
+            (price || purchasePrices) &&
+            !hadTaxIdChange &&
+            context['bulk-edit-default-tax-with-price'] &&
+            updatedPricePayload.length > 0
+        ) {
+            const defaultTaxId = await this.getDefaultTaxId();
```
Comment (sydinh) [inline src/Administration/Resources/app/administration/src/module/sw-bulk-edit/service/handler/bulk-edit-product.handler.js]: Shall we getDefaultTaxId when the component is loaded instead? @vienthuong

File: src/Administration/Resources/app/administration/src/module/sw-bulk-edit/service/handler/bulk-edit-product.handler.js [hunk 4]
```diff
@@ -113,6 +130,16 @@ class BulkEditProductHandler extends BulkEditBaseHandler {
         });
     }
 
+    async getDefaultTaxId() {
+        const taxRepository = this.repositoryFactory.create('tax');
```
Comment (sydinh) [inline src/Administration/Resources/app/administration/src/module/sw-bulk-edit/service/handler/bulk-edit-product.handler.js]: Please split this into a computed prop, and the criteria as well.

File: src/Administration/Resources/app/administration/src/module/sw-bulk-edit/service/handler/bulk-edit-product.handler.js [hunk 5]
```diff
@@ -113,6 +130,16 @@ class BulkEditProductHandler extends BulkEditBaseHandler {
...
+        const criteria = new Criteria(1, 1);
+        criteria.addSorting(Criteria.sort('position'));
+
+        const taxes = await taxRepository.search(criteria, Shopware.Context.api);
+
+        return taxes.length > 0 ? taxes[0].id : null;
```
Comment (sydinh) [inline src/Administration/Resources/app/administration/src/module/sw-bulk-edit/service/handler/bulk-edit-product.handler.js]: taxes.first()?.id ?? null

**Review by sydinh — CHANGES_REQUESTED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-bulk-edit/service/handler/bulk-edit-product.handler.js (hunk 4 above)
Comment (nguyenquocdaile) [reply src/Administration/Resources/app/administration/src/module/sw-bulk-edit/service/handler/bulk-edit-product.handler.js]: It's a plain JS class, not a Vue component instance. It seems we can't use computed here.

File: src/Administration/Resources/app/administration/src/module/sw-bulk-edit/service/handler/bulk-edit-product.handler.js (hunk 3 above)
Comment (vienthuong) [reply src/Administration/Resources/app/administration/src/module/sw-bulk-edit/service/handler/bulk-edit-product.handler.js]: would be good 👍🏽

**Review by vienthuong — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-bulk-edit/service/handler/bulk-edit-product.handler.js (hunk 4 above)
Comment (sydinh) [reply src/Administration/Resources/app/administration/src/module/sw-bulk-edit/service/handler/bulk-edit-product.handler.js]: I still don't think this is worth it, we should avoid waterfalling API requests like this. It would be better to load all bulk editing dependencies when the page loads instead. See the `src/Administration/Resources/app/administration/src/module/sw-bulk-edit/page/sw-bulk-edit-product/index.js` line 905

File: src/Administration/Resources/app/administration/src/module/sw-bulk-edit/service/handler/bulk-edit-product.handler.js [hunk 6]
```diff
@@ -113,6 +130,17 @@ class BulkEditProductHandler extends BulkEditBaseHandler {
         });
     }
 
+    async getDefaultTaxId() {
+        const taxRepository = this.repositoryFactory.create('tax');
+        const criteria = new Criteria(1, 1);
+        criteria.addSorting(Criteria.sort('position'));
+
+        const taxes = await taxRepository.search(criteria, Shopware.Context.api);
```
Comment (vienthuong) [inline src/Administration/Resources/app/administration/src/module/sw-bulk-edit/service/handler/bulk-edit-product.handler.js]: please use searchIds

File: src/Administration/Resources/app/administration/src/module/sw-bulk-edit/service/handler/bulk-edit-product.handler.js (hunk 4 above)
Comment (nguyenquocdaile) [reply src/Administration/Resources/app/administration/src/module/sw-bulk-edit/service/handler/bulk-edit-product.handler.js]: I updated a new approach for it.

**Review by nguyenytran — APPROVED** [review]

**Review by sydinh — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-bulk-edit/service/handler/bulk-edit-product.handler.js (hunk 4 above)
Comment (sydinh) [reply src/Administration/Resources/app/administration/src/module/sw-bulk-edit/service/handler/bulk-edit-product.handler.js]: looks much simpler now
