### PR TITLE
fix: update product and property option names to use translated values

### LINKED ISSUE #6477: Translation – The values are not applied in the properties.
If values are stored in the properties, they are also applied to the available languages. However, when filtering by these values in the variant overview, the translations are not displayed.

If you go into the properties, switch the language to a "non-system language," and then click on a value, the name appears empty. While it is shown as existing, it is not permanently assigned.

### PR DESCRIPTION
**Pull request by nguyenquocdaile**
### Solution

| Before   | After |
|---------------------------|-------------------------|
| _2025-01-29 um 12 22 22 | image |
| _2025-01-29 um 12 22 46 | Screenshot 2025-06-19 at 16 31 44
 |

### CODE REVIEW

File: src/Administration/Resources/app/administration/src/module/sw-product/component/sw-product-variants/sw-product-variants-overview/index.js [hunk 1]
```diff
@@ -389,7 +389,7 @@ export default {
 
                     return {
                         id: group.id,
-                        name: group.name,
+                        name: group.name || group.translated.name,
```
Comment (vienthuong) [inline src/Administration/Resources/app/administration/src/module/sw-product/component/sw-product-variants/sw-product-variants-overview/index.js]: it should other way around

**Review by vienthuong — CHANGES_REQUESTED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-property/component/sw-property-option-detail/index.js [hunk 2]
```diff
@@ -51,6 +51,10 @@ export default {
             },
         },
 
+        optionName() {
+            return this.currentOption.name || this.currentOption?.translated?.name;
```
Comment (vienthuong) [inline src/Administration/Resources/app/administration/src/module/sw-property/component/sw-property-option-detail/index.js]: getter should be this.currentOption?.translated?.name || this.currentOption.name but setter should always be this.currentOption.name

Comment (sydinh) [reply src/Administration/Resources/app/administration/src/module/sw-property/component/sw-property-option-detail/index.js]: This is not a getter and setter property, I guess it will cause some error if users update the value on the template.

Comment (vienthuong) [reply src/Administration/Resources/app/administration/src/module/sw-property/component/sw-property-option-detail/index.js]: that's why I suggest it should be getter/setter, you're not supposed to save the value into `translated.name`. But looking at the other component, seems they don't use `translated` in v-model :think: so they just leave it empty with the fallback value at the placeholder. Please check how other component works

File: src/Administration/Resources/app/administration/src/module/sw-property/component/sw-property-option-detail/sw-property-option-detail.html.twig [hunk 3]
```diff
@@ -1,12 +1,12 @@
 {% block sw_property_option_detail %}
 <sw-modal
-    :title="currentOption.name ? currentOption.name : $tc('sw-property.detail.textOptionHeadline')"
+    :title="optionName ? optionName : $tc('sw-property.detail.textOptionHeadline')"
```
Comment (vienthuong) [inline src/Administration/Resources/app/administration/src/module/sw-property/component/sw-property-option-detail/sw-property-option-detail.html.twig]: `modalTitle` computed

**Review by vienthuong — APPROVED** [review]

**Review by sydinh — APPROVED** [review]
