### PR TITLE
fix: keep promotion codes after login

### LINKED ISSUE #10809: Presaved vouchers get lost at login
### Shopware Version

6.6.10.3

### Affected area / extension

Platform(Default)

### Actual behaviour

Vouchers whose terms have not yet been met are saved in the storefront after the customer enters them. These vouchers are then lost upon login.

### Expected behaviour

Vouchers remain remembered even when logging in and are activated as soon as the conditions are met

### How to reproduce

Create a coupon that is only valid for purchases above a certain shopping cart value. Go to the storefront and put an item in your cart that is cheaper, so that you don't reach the minimum shopping cart value for redeeming the coupon. You'll see a message telling you that the conditions for the coupon have not yet been met and that the coupon is being saved. Then log in with a storefront user. Add more products to your cart so that you exceed the minimum value. The coupon should now appear automatically in your shopping cart, but it doesn't. Without logging in in between, remembering the coupon works perfectly, but it gets lost when you log in.

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by lernhart**
fixes [#10809](https://github.com/shopware/shopware/issues/10809)

### CODE REVIEW

**Review by cyl3x — APPROVED** [review]

File: src/Core/Checkout/Promotion/Cart/CartPromotionsSubscriber.php [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+    public function onBeforeCartMerge(BeforeCartMergeEvent $event): void
+    {
+        $guestCart = $event->getGuestCart();
+        $customerCart = $event->getCustomerCart();
+
+        if (!$guestCart->hasExtension(CartExtension::KEY)) {
+            return;
+        }
+
+        /** @var CartExtension $guestPromotions */
```
Comment (mitelg) [inline src/Core/Checkout/Promotion/Cart/CartPromotionsSubscriber.php]: please do not use var annotations. you can use an if condition and return here.
also see https://github.com/shopware/shopware/blob/trunk/coding-guidelines/core/writing-code-for-static-analysis.md

Comment (mstegmeyer) [reply src/Core/Checkout/Promotion/Cart/CartPromotionsSubscriber.php]: no, use `getExtensionOfType`, then PHPstan knows the type.

File: src/Core/Checkout/Promotion/Cart/Extension/CartExtension.php [hunk 2]
```diff
@@ -80,4 +80,27 @@ public function isPromotionBlocked(string $id): bool
...
+
+    /**
+     * @return array<string>
+     */
+    public function getBlockedPromotions(): array
+    {
+        return $this->blockedPromotionIds;
+    }
+
+    public function merge(self $extension): self
```
Comment (mstegmeyer) [inline src/Core/Checkout/Promotion/Cart/Extension/CartExtension.php]: couldn't this be `static`? isn't that more precise?

File: src/Core/Checkout/Promotion/Cart/CartPromotionsSubscriber.php (hunk 1 above)
Comment (mitelg) [reply src/Core/Checkout/Promotion/Cart/CartPromotionsSubscriber.php]: or this :sweat_smile:

File: src/Core/Checkout/Promotion/Cart/Extension/CartExtension.php (hunk 2 above)
Comment (lernhart) [reply src/Core/Checkout/Promotion/Cart/Extension/CartExtension.php]: I've changed the return type to be static. This is what you meant with your comment, right?

**Review by mitelg — APPROVED** [review]

**Review by FlorianKe — APPROVED** [review]

File: src/Core/Checkout/Promotion/Cart/CartPromotionsSubscriber.php (hunk 1 above)
Comment (En0Ma1259) [reply src/Core/Checkout/Promotion/Cart/CartPromotionsSubscriber.php]: Would say even in the tests

**Review by mstegmeyer — APPROVED** [review]
