### PR TITLE
fix: error when changing to isempty in rule condition

### LINKED ISSUE #8357: Cannot set existing condition to "Is empty" if it had been saved with a value previously
### Shopware Version

6.6.10.3 & 6.7.0.0-rc2

### Affected area / extension

Platform(Default)

### Actual behaviour

When trying to change a condition in a rule to “Is empty” when it previously compared a value, the error “The property "amount" is not allowed.” appears.

Image

Workaround: delete the affected condition and re-create it.

### Expected behaviour

The updated condition would save.

### How to reproduce

- Create a new rule and insert “Item with list price > At least one > Is equal to > 0” as a condition
- Save the rule and then try to change the condition to “Item with list price > At least one > Is empty”
- Observe the error

### PR DESCRIPTION
**Pull request by philippdinkhoff**
### 1. Why is this change necessary?

Fixes the issue when trying to change the condition in "Item with list price"-rule  to “Is empty” when it previously compared a value, the error “The property "amount" is not allowed.” appears.

### 2. What does this change do, exactly?
Moves over the amount constraint so it is still known in the return.

### 3. Describe each step to reproduce the issue or behaviour.
    Create a new rule and insert “Item with list price > At least one > Is equal to > 0” as a condition
    Save the rule and then try to change the condition to “Item with list price > At least one > Is empty”
    Observe the error

### 4. Please link to the relevant issues (if any).

- closes #8357

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfill them.

### CODE REVIEW

**Comment by philippdinkhoff** [comment]
So far the amount-value will still be stored in the database. Does not effect the rule.

File: src/Administration/Resources/app/administration/src/module/sw-settings-rule/page/sw-settings-rule-detail/index.js [hunk 1]
```diff
@@ -448,6 +448,20 @@ export default {
         },
 
         onSave() {
+            const cleanConditions = (conditions) => {
```
Comment (ennasus4sun) [inline src/Administration/Resources/app/administration/src/module/sw-settings-rule/page/sw-settings-rule-detail/index.js]: I had a look into the other components of the rules. They handle their "data cleanup" on their own like 
- in `sw-condition-type-select`: https://github.com/shopware/shopware/blob/9a0becdbf862275a5c5dabbbfe099d6cbc34d9b6/src/Administration/Resources/app/administration/src/app/component/rule/sw-condition-type-select/index.js#L124-L146
- or in `sw-condition-unit-menu`: https://github.com/shopware/shopware/blob/9a0becdbf862275a5c5dabbbfe099d6cbc34d9b6/src/Administration/Resources/app/administration/src/app/component/rule/sw-condition-unit-menu/index.js#L198-L208
- there is also a changeOperator-method inside `sw-condition-operator-select` component:
https://github.com/shopware/shopware/blob/9a0becdbf862275a5c5dabbbfe099d6cbc34d9b6/src/Administration/Resources/app/administration/src/app/component/rule/sw-condition-operator-select/index.js#L70

maybe this is a "design decission".
Perhaps this approach should be used or considered. However, I can not contribute anything to this. But maybe someone else...

One difference in behaviour would be that the value is removed directly onchange.

**Review by ennasus4sun — COMMENTED** [review]
yes, looks good to me
can we provide a test?

File: src/Administration/Resources/app/administration/src/app/component/rule/sw-condition-operator-select/sw-condition-operator-select.spec.js [hunk 2]
```diff
@@ -38,4 +38,22 @@ describe('src/app/component/rule/sw-condition-operator-select', () => {
 
         expect(singleSelect.attributes().disabled).toBe('true');
     });
+
+    it('emits only operator when changed to empty operator', async () => {
```
Comment (ennasus4sun) [inline src/Administration/Resources/app/administration/src/app/component/rule/sw-condition-operator-select/sw-condition-operator-select.spec.js:42]: I think, I would also test the opposite case ("_preserves all condition properties when changed to non-empty operator"_)

**Review by ennasus4sun — APPROVED** [review]

**Review by MalteJanz — APPROVED** [review]
