### PR TITLE
fix: fix email recovery in admin login

### LINKED ISSUE #12041: User recovery not woking
### Shopware Version

trunk

### Affected area / extension

Platform(Default)

### Actual behaviour

An error was thrown in the console when clicking to [Send Recovery link]

```
chunk-33L774OX.js?v=f1e639c8:2594 Uncaught TypeError: Cannot read properties of undefined (reading 'createRecovery')
    at Proxy.sendRecoveryMail (index.ts:47:18)
    at cache.<computed>.cache.<computed> (chunk-33L774OX.js?v=f1e639c8:12420:12)
    at callWithErrorHandling (chunk-33L774OX.js?v=f1e639c8:2525:19)
    at callWithAsyncErrorHandling (chunk-33L774OX.js?v=f1e639c8:2532:17)
    at HTMLFormElement.invoker (chunk-33L774OX.js?v=f1e639c8:11462:5)
```

### Expected behaviour

An email should be sent

### How to reproduce

1. Access to the admin login page
2. Click the button [Did you forget your password?]
3. Enter the user's email
4. Click to [Send recovery link]

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by jleifeld**
### 1. Why is this change necessary?

Fixes https://github.com/shopware/shopware/issues/12041

### 2. What does this change do, exactly?

Replace the injection with direct access to the service to make it work again:

Bildschirmfoto 2025-09-09 um 10 44 06

### CODE REVIEW

**Review by cyl3x — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-login/view/sw-login-recovery/index.ts [hunk 1]
```diff
@@ -43,7 +41,7 @@ export default Component.wrapComponentConfig({
         sendRecoveryMail() {
             this.$emit('is-loading');
 
-            this.userRecoveryService
+            Shopware.Service('userRecoveryService')
```
Comment (bschulzebaek) [inline src/Administration/Resources/app/administration/src/module/sw-login/view/sw-login-recovery/index.ts:44]: Do you mind explaining in short what this change does? Are injected services only loaded when the client is authenticated?

Comment (jleifeld) [reply src/Administration/Resources/app/administration/src/module/sw-login/view/sw-login-recovery/index.ts:44]: We have a timing issue in the login which is not easy solvable because of the different boot process for it. Access to this service is therefore only available after the initial rendering

**Review by bschulzebaek — APPROVED** [review]
