### PR TITLE
fix: blocked shipping method not switched

### LINKED ISSUE #13434: Block shipping method
### Shopware Version

6.7.x

### Affected area / extension

Platform(Default)

### Actual behaviour

When a shipping method is blocked, it remains selected. The customer has to change the method manually.

### Expected behaviour

The selection should be updated automatically, as it was in version 6.6.

### How to reproduce

Rules to block shipping methods, for example when shipping costs are based on tags.

### PR DESCRIPTION
**Pull request by FlorianKe**
### 1. Why is this change necessary?
When a shipping method is blocked, it remains selected. The customer has to change the method manually.

### 2. What does this change do, exactly?
Adjusted the Criteria

### 4. Please link to the relevant issues (if any).
fixes #13434

### CODE REVIEW

**Review by cyl3x — APPROVED** [review]

**Review by socrec — APPROVED** [review]
Small UX fix 👍

**Review by En0Ma1259 — COMMENTED** [review]
We should add an integration test, which covers
1. Calling `BlockedShippingMethodSwitcher`
2. Create Criteria with ids/names
3. Multiple shipping methods are found with `$this->shippingMethodRoute->load(...)`
4. But the ruleIdMatcher within the `shippingMethodRoute` has filtered the first shipping method

File: src/Storefront/Checkout/Shipping/BlockedShippingMethodSwitcher.php
Comment (mstegmeyer) [inline src/Storefront/Checkout/Shipping/BlockedShippingMethodSwitcher.php:22]: please do the same for payment

File: tests/integration/Storefront/Checkout/Shipping/BlockedShippingMethodSwitcherTest.php [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+/**
+ * @internal
+ */
+#[Package('checkout')]
+class BlockedShippingMethodSwitcherTest extends TestCase
+{
+    use IntegrationTestBehaviour;
+    use SalesChannelApiTestBehaviour;
+
+    public function testBlockedShippingMethodSwitcherMessage(): void
```
Comment (mstegmeyer) [inline tests/integration/Storefront/Checkout/Shipping/BlockedShippingMethodSwitcherTest.php]: you can keep this test, but I would add a test for the `CartFacade`, that tests the actual switching

**Review by mstegmeyer — CHANGES_REQUESTED** [review]

**Review by mstegmeyer — APPROVED** [review]

**Comment by gecolay** [comment]
Why should we fetch all, if we just use `->first()` a few lines later? It looks like to me we now just fetch them for no reason

**Comment by FlorianKe** [comment]
> Why should we fetch all, if we just use `->first()` a few lines later? It looks like to me we now just fetch them for no reason

If we only fetch one, the ShippingMethodRoute::load() method will return null instead of a ShippingMethodEntity.

**Comment by En0Ma1259** [comment]
> Why should we fetch all, if we just use `->first()` a few lines later? It looks like to me we now just fetch them for no reason

There is a possibility that the [ShippingMethodRoute](https://github.com/shopware/shopware/blob/trunk/src/Core/Checkout/Shipping/SalesChannel/ShippingMethodRoute.php#L75) will remove shipping options. If the first one is removed and we have a limit of 1, we will remove the only shipping method we have loaded.

**Comment by philipreinken** [comment]
If this should be released in the `6.7.4.x` line as well, please backport it 🙂
