### PR TITLE
fix: Theme settings getting lost when navigating quickly

### LINKED ISSUE #9572: Navigating away from the theme settings can cause all theme config to get lost
### Shopware Version

6.6.10.3

### Affected area / extension

Platform(Default)

### Actual behaviour

We are using a child theme of a popular 3rd party general purpose (store) theme and made lots of customizations. Sometimes those customizations get lost.

### Expected behaviour

Theme config does not get reset

### How to reproduce

In administration:

1. Edit the theme config
2. Click save
3. Confirm the dialog "Save Theme" - "Do you really want to save the changes? This will change the appearance of your shops."
4. Now quickly navigate away, for example to the sales channel configuration
5. Error pops up

Error

Now all the customizations are gone.

We saw the following in the network tab.

I first does a /reset of the theme.
Then it does a patch of a completely different theme ID which does not even exist in the database:

Network tab

Returned JSON of the failing patch is

```json
{
	"errors": [
		{
			"status": "400",
			"code": "THEME__INVALID_THEME_BY_ID",
			"title": "Bad Request",
			"detail": "Could not find theme with id \"018e6183b67372d483078aada1f032fa\"",
			"meta": {
				"parameters": {
					"entity": "theme",
					"field": "id",
					"value": "018e6183b67372d483078aada1f032fa"
				}
			}
		}
	]
}
```

Database looks like this:

```sql
select id, technical_name from theme\G;
*************************** 1. row ***************************
            id: 0x018E618446AF7266880B46B2371A651B
technical_name: Storefront
*************************** 2. row ***************************
            id: 0x0196C3F82ED873DC9B7539718985B649
technical_name: zenitPlatformHorizon
*************************** 3. row ***************************
            id: 0x0196C3F8314E71F991F308BEFA36AE38
technical_name: zenitCustomTheme
```

### PR DESCRIPTION
**Pull request by amenk**
### 1. Why is this change necessary?

Theme settings can get lost when navigating away from the theme settings route to quickly 

### 2. What does this change do, exactly?

Before updating a theme, resetTheme was called. This now happens server side to make this more robust

### 3. Describe each step to reproduce the issue or behaviour.

1. throttle connection to 2G
2. save theme config
3. quickly navigate to sales channel config
4. updateTheme request fails, theme stays reset

### 4. Please link to the relevant issues (if any).
closes: #9572

### 5. Checklist

- [no, race condition too hard to reproduce] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [no, where?] I have written or adjusted the documentation according to my changes
- [it's obvious] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfill them.

### CODE REVIEW

File: src/Storefront/Resources/app/administration/src/modules/sw-theme-manager/page/sw-theme-manager-detail/index.js [hunk 1]
```diff
@@ -542,9 +542,7 @@ Component.register('sw-theme-manager-detail', {
             this.removeInheritedFromChangeset(allValues);
 
             // Theme has to be reset, because inherited fields needs to be removed from the set
-            return this.themeService.resetTheme(this.themeId).then(() => {
-                return this.themeService.updateTheme(this.themeId, { config: allValues });
-            });
+            return this.themeService.updateTheme(this.themeId, { config: allValues }, { reset: 1 });
```
Comment (mitelg) [inline src/Storefront/Resources/app/administration/src/modules/sw-theme-manager/page/sw-theme-manager-detail/index.js]:
```suggestion
            return this.themeService.updateTheme(this.themeId, { config: allValues }, { reset: true });
```

we should use real boolean values and then use `getBoolean` on the query in the PHP part

Comment (amenk) [reply src/Storefront/Resources/app/administration/src/modules/sw-theme-manager/page/sw-theme-manager-detail/index.js]: did not know about that -- very good advice, thanks. I changed it

File: changelog/_unreleased/2025-05-20-added-reset-parameter-to-update-theme.md [hunk 2]
```diff
@@ -0,0 +1,11 @@
+---
+title: Fix theme settings getting lost when navigating quickly
+issue: #9572
+author: Alexander Menk
+author_email: a.menk@imi.de
+author_github: @amenk
+---
+
+# Administration
+* Added new parameter `reset` to `src/Storefront/Theme/Controller/ThemeController.php`:`updateTheme` which resets the theme.
```
Comment (mitelg) [inline changelog/_unreleased/2025-05-20-added-reset-parameter-to-update-theme.md]:
```suggestion
* Added new parameter `reset` to `\Shopware\Storefront\Theme\Controller\ThemeController::updateTheme()` which resets the theme.
```

File: changelog/_unreleased/2025-05-20-added-reset-parameter-to-update-theme.md [hunk 3]
```diff
@@ -0,0 +1,11 @@
+---
+title: Fix theme settings getting lost when navigating quickly
+issue: #9572
+author: Alexander Menk
+author_email: a.menk@imi.de
+author_github: @amenk
+---
+
+# Administration
+* Added new parameter `reset` to `\Shopware\Storefront\Theme\Controller\ThemeController::updateTheme()` which resets the theme.
```
Comment (mitelg) [inline changelog/_unreleased/2025-05-20-added-reset-parameter-to-update-theme.md:10]: I think this would need to go into the storefront section :thinking:

File: changelog/_unreleased/2025-05-20-added-reset-parameter-to-update-theme.md [hunk 4]
```diff
@@ -0,0 +1,11 @@
...
+* Changed call in Theme Manager use the `reset=1` parameter to do reset and update in one step.
```
Comment (mitelg) [inline changelog/_unreleased/2025-05-20-added-reset-parameter-to-update-theme.md]: would you mind adding the file or class name of the JS part here as well to make it more clearer?

**Review by mitelg — COMMENTED** [review]
some tests would be nice

**Comment by amenk** [comment]
> some tests would be nice

yeah was thinking about that. But seems pretty complex - as least for the race condition. I thought about testing the controller, but it currently has no tests at all. It happens all at themeService level.

File: changelog/_unreleased/2025-05-20-added-reset-parameter-to-update-theme.md (hunk 3 above)
Comment (amenk) [reply changelog/_unreleased/2025-05-20-added-reset-parameter-to-update-theme.md:10]: I did not notice that this is a storefront controller ... because it's all happening in the Admin. Very intersting.

Shall I change it to storefront?

File: changelog/_unreleased/2025-05-20-added-reset-parameter-to-update-theme.md (hunk 4 above)
Comment (amenk) [reply changelog/_unreleased/2025-05-20-added-reset-parameter-to-update-theme.md]: sure

File: changelog/_unreleased/2025-05-20-added-reset-parameter-to-update-theme.md (hunk 3 above)
Comment (mitelg) [reply changelog/_unreleased/2025-05-20-added-reset-parameter-to-update-theme.md:10]: yeah, it is more about the namespace, I guess :thinking: but maybe the @shopware/product-cc-discovery team has an opinion on that

Comment (marcelbrode) [reply changelog/_unreleased/2025-05-20-added-reset-parameter-to-update-theme.md:10]: Storefront is correct. The complete Theme system is in an in-core-bundle for the Storefront, since Shopware can be used headless, as you know 😄 One of the rare places in Shopware were you have Admin stuff in the Storefront Domain :)

**Review by mitelg — APPROVED** [review]

**Review by marcelbrode — APPROVED** [review]

**Review by ravenokko — APPROVED** [review]
Looks good! Thank you for your contribution 💙

**Comment by mitelg** [comment]
thanks for your contribution @amenk 👍🎉💙

**Comment by amenk** [comment]
Thanks everybody for the swift processing.

I am always confused so I ask here again: I assume this will go into 6.7 ? Or will there be any backport to 6.6 ? 
Otherwise we will composer-patch this into our 6.6 stores.

What's the best way to find out in which version a patch get's released?

**Comment by mitelg** [comment]
@amenk right now, it would be part of the 6.7.1.0 release :wink: 

but we can backport it to 6.6
