### PR TITLE
fix: required field validation

### LINKED ISSUE #14792: Administration: Company in address modal is marked as required but can be blank
### Shopware Version

6.7.7.1

### Affected area / extension

Platform(Default)

### Actual behaviour

Image

### Expected behaviour

Add "Not Blank" check like in the other required fields.

### How to reproduce

Add or edit a address in the order detail page and save the address.

### PR DESCRIPTION
**Pull request by En0Ma1259**
### 1. Why is this change necessary?
1. Required order address fields were not marked "red", when try to save empty
2. For business customer, the *required* company field was not validated correctly 

### 2. What does this change do, exactly?
1. Added company required flag, if the customer is a business customer
2. Enhanced validation output for order address modal
3. Prevent order address to be updated, when closing the modal without "apply" (close button or click next to the modal), and save the order afterward

### 3. Describe each step to reproduce the issue or behaviour.
1. Navigate to a business customer order
2. Edit the order address and empty "company"

1. Click "apply" → address should not be updated
2. Click "close" (or next to the modal) and save the order → address should not be updated

### 4. Please link to the relevant issues (if any).
- fixes https://github.com/shopware/shopware/issues/14792

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have updated developer-facing release notes if this change is **relevant** for external developers:
  - Add a short entry to `RELEASE_INFO-6.<major>.md` under “Upcoming” for informational changes, including the consequences of the change and how it affects external developers.
  - Add an `UPGRADE` section in `UPGRADE-6.<next-major>.md` for breaking changes (what/why/impact/how to adapt).
  - See the [Documenting a Release Process](https://github.com/shopware/shopware/blob/trunk/delivery-process/documenting-a-release.md) for details.
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

**Review by Aliaaaam — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-address-selection/index.js [hunk 1]
```diff
@@ -151,7 +156,11 @@ export default {
 
         onEditAddress(id) {
             if (id === this.address.id) {
-                this.currentAddress = this.address;
+                // create to prevent side effects when closing the modal
+                this.currentAddress = this.orderAddressRepository.create(Shopware.Context.api, id);
+                delete this.currentAddress._isNew;
+                Object.assign(this.currentAddress, this.address);
```
Comment (cyl3x) [inline src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-address-selection/index.js]: what's the kind of side effect you want to avoid? Assign only copies on the top level + only basic types, e.g. objects are still assigned as reference. I suggest using `Shopware.Utils.object.cloneDeep` or so

Comment (En0Ma1259) [reply src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-address-selection/index.js]: If you change the address - e.g. clear company or postal code - and close the modal (close button or click next to the modal), and hit the order "save" button, the address will be saved with an empty company and/or postal code.
That should not have happened, because in my case both fields are marked as required.

`cloneDeep` will make it easier for plugins to add/save custom associations/data 👍🏽 
```js
// clone, to prevent side effects when closing the modal
this.currentAddress = Shopware.Utils.object.cloneDeep(this.addres);
```

**Review by cyl3x — APPROVED** [review]
