### PR TITLE
fix: Improve tag selection in customer and orders module

### LINKED ISSUE #7544: Tags cannot be added to Orders and Customers via the select field
No new tags can be created nor can available tags be assigned on customer and order detail pages.

!Screen Recording 2025-03-11 at 16.58.51.mov|width=1526,height=1014,alt="Screen Recording 2025-03-11 at 16.58.51.mov"!

### PR DESCRIPTION
**Pull request by Phil23**
### 1. Why is this change necessary?
- The tag selection in the customer module gives the impression that it is not functional. In fact, it is disabled if you are not in edit mode, but the disabled state is not properly implemented.
- The tag selection in the order module does not work properly.

### 2. What does this change do, exactly?
- The entity tag selection field now properly passes down the disabled state to the `sw-select-base` component, so that the tag field is properly visualized as disabled, when not in edit mode.
- The entity tag selection field in the order module now makes use of `v-model` for passing the entity collection, so that tags can be added and removed properly.

**Disabled customer tag selection:**  

image

### CODE REVIEW

**Comment by BrocksiNet** [comment]
This will closes: #7544

File: src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-general-info/index.js [hunk 1]
```diff
@@ -189,17 +188,7 @@ export default {
...
-            this.tagCollection = new EntityCollection(
-                this.order.tags.source,
-                this.order.tags.entity,
-                Shopware.Context.api,
-                null,
-                tags,
-                tags.length,
-            );
-
+            this.tagCollection = this.order.tags;
```
Comment (jleifeld) [inline src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-general-info/index.js]: This changes the behavior how the data get handled.

Previously:
- cloned the value deeply
- created a new EntityCollection based on the cloned values

Now: 
- References the tags directly in the order

I can imagine that the previous developer did this on purpose. Changing this could lead to several unknown side effects

**Review by jleifeld — CHANGES_REQUESTED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-general-info/index.js (hunk 1 above)
Comment (Phil23) [reply src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-general-info/index.js]: I reverted this, as the developer who changed this, was trying to fix the exact same issue, but apparently it did not work, so I thought it could be reverted. In the customers module, the same component also just gets passed `customer.tags` in the same way. But I can change it again. 🤷‍♂️

Comment (Phil23) [reply src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-general-info/index.js]: Ok, there is a test case for this 😅

Comment (Phil23) [reply src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-general-info/index.js]: Reverted the changes to the previous state.

**Review by keulinho — APPROVED** [review]

**Review by seggewiss — APPROVED** [review]

**Review by jleifeld — APPROVED** [review]
