### PR TITLE
fix: cart not recalculated without ESI on sub requests

### LINKED ISSUE #14861: Improve performance of loading rules on subrequests
### Technical TODO

While doing a request, we are loading rules 3 times. Once for the main request and another 2 for header and footer.

**Expected behavior**
Within the main request, the rules should be loaded / cart should be calculated only once.

Image

- related https://github.com/shopware/shopware/issues/8558

### PR DESCRIPTION
**Pull request by keulinho**
fixes: https://github.com/shopware/shopware/issues/14861

### 1. Why is this change necessary?
Currently when reverse proxy is enabled and the default symfony internal ESI handling in combination with symfonies cache handling is not used we calculate the cart 3 times per request

### 2. What does this change do, exactly?
Do not check for ESI flag, as it is not always present when we render a ESI subrequest, but only if the used http cache supports it, otherwise it will be handled as plain sub request

### 3. Describe each step to reproduce the issue or behaviour.
Have a long running cart calculation with a reverse proxy (e.g. varnish or fastly) and don't activate ESI support in the reverse proxies (e.g. as in our SaaS)
When you trace the request you see the cart calcualtion is done 3 times on every page.

### 4. Please link to the relevant issues (if any).
fixes: https://github.com/shopware/shopware/issues/14861

### CODE REVIEW

File: src/Core/System/SalesChannel/Context/SalesChannelContextService.php [hunk 1]
```diff
@@ -134,9 +134,8 @@ public function get(SalesChannelContextServiceParameters $parameters): SalesChan
                 $context->setImitatingUserId(null);
             }
 
-            // skip cart calculation on ESI sub-requests if it has already been done.
-            $esiRequest = $currentRequest?->attributes->has('_sw_esi') ?? false;
-            if (!$this->cartService->hasCart($token) || !$esiRequest) {
+            // Only calculate the cart once per request
+            if (!$this->cartService->hasCart($token)) {
```
Comment (keulinho) [inline src/Core/System/SalesChannel/Context/SalesChannelContextService.php]: wondering why the ESI check was even added 🤔 

Are there any sub requests where we know we need to recalculate the cart? Especially when the token does not change

Comment (cyl3x) [reply src/Core/System/SalesChannel/Context/SalesChannelContextService.php]: Please have a look at https://github.com/shopware/shopware/pull/10968

Comment (En0Ma1259) [reply src/Core/System/SalesChannel/Context/SalesChannelContextService.php]: With this, we will revert the improvement, right
- https://github.com/shopware/shopware/issues/8558

**Review by cyl3x — APPROVED** [review]

File: src/Core/System/SalesChannel/Context/SalesChannelContextService.php (hunk 1 above)
Comment (mitelg) [reply src/Core/System/SalesChannel/Context/SalesChannelContextService.php]: is this now fine? 🤔

Comment (cyl3x) [reply src/Core/System/SalesChannel/Context/SalesChannelContextService.php]: yes, our nmistake :+1:

**Review by En0Ma1259 — APPROVED** [review]

**Comment by keulinho** [comment]
Well looks like commercial is doing some recalculations in the same request and assumes that it works 🤦 

Maybe that was the reason we added the ESI check, let me check if there is a more stable way to figure out whether we are in a sub request for ESI, that does not depend on symfonies fragement rendering strategies etc

File: src/Core/Framework/Adapter/Kernel/HttpCacheKernel.php [hunk 2]
```diff
@@ -59,7 +59,7 @@ public function handle(Request $request, int $type = HttpKernelInterface::MAIN_R
         // https://github.com/symfony/symfony/issues/51648#issuecomment-1717846894
         if ($type === HttpKernelInterface::MAIN_REQUEST) {
             $response = parent::handle($request, $type, $catch);
-        } elseif ($request->attributes->has('_sw_esi')) {
```
Comment (keulinho) [inline src/Core/Framework/Adapter/Kernel/HttpCacheKernel.php:62]: @mitelg do you remember why exactly we needed to have that here? Was it important that it is only used when symfonies real esi strategy is used? 🤔 or is it enough to know that the request is for an _esi route?

File: src/Core/System/SalesChannel/Context/SalesChannelContextService.php [hunk 3]
```diff
@@ -135,7 +135,7 @@ public function get(SalesChannelContextServiceParameters $parameters): SalesChan
             }
 
             // skip cart calculation on ESI sub-requests if it has already been done.
-            $esiRequest = $currentRequest?->attributes->has('_sw_esi') ?? false;
+            $esiRequest = $currentRequest?->attributes->has('_esi') ?? false;
```
Comment (keulinho) [inline src/Core/System/SalesChannel/Context/SalesChannelContextService.php:138]: that's the attribute we add to all our _esi routes,so it works for every sub request to those routes, and not only when it goes through symfonies ESI handler

i assume that was exactly what was expected with the `_sw_esi` attribute before, but that has a different use case and semantic

File: src/Core/Framework/Adapter/Kernel/HttpCacheKernel.php (hunk 2 above)
Comment (keulinho) [reply src/Core/Framework/Adapter/Kernel/HttpCacheKernel.php:62]: i removed the whole decorator for now to see if it breaks in the pipeline

Comment (keulinho) [reply src/Core/Framework/Adapter/Kernel/HttpCacheKernel.php:62]: some acceptance test fail, let's see if they succeed again when i bring back this behaviour

Comment (mitelg) [reply src/Core/Framework/Adapter/Kernel/HttpCacheKernel.php:62]: I think the comment above give the right hint :thinking: If I remember correctly, if you use a proxy that natively supports ESI, the requests for the ESI snippets are normal requests in Symfony handling. 

But if only the Symfony ESI handling is active, the requests for ESI snippets are sub-requests of the main request. which needs different handling

File: src/Core/System/SalesChannel/Context/SalesChannelContextService.php (hunk 3 above)
Comment (mitelg) [reply src/Core/System/SalesChannel/Context/SalesChannelContextService.php:138]: are sub-requests of the Symfony ESI handling also marked with the `_esi` attribute?

File: src/Core/Framework/Adapter/Kernel/HttpCacheKernel.php (hunk 2 above)
Comment (keulinho) [reply src/Core/Framework/Adapter/Kernel/HttpCacheKernel.php:62]: But for that case the `_esi` attribute should also work 🤔 

I'll test the change in a saas instance if it behaves as expected

File: src/Core/System/SalesChannel/Context/SalesChannelContextService.php (hunk 3 above)
Comment (keulinho) [reply src/Core/System/SalesChannel/Context/SalesChannelContextService.php:138]: i assume not, we set that attribute manually on the route level: 

Image

so a sub request is on another route and that attribute won't be there

but the same is true for the other `_sw_esi` either right?

File: src/Core/Framework/Adapter/Kernel/HttpCacheKernel.php (hunk 2 above)
Comment (keulinho) [reply src/Core/Framework/Adapter/Kernel/HttpCacheKernel.php:62]: now it works locally with dev and prod mode (with symfony http caching) and on SaaS as expected
