### PR TITLE
fix: Allow partial loading in CustomerRoute via PHP

### LINKED ISSUE #9774: Allow partial loading for `CustomerRoute`
### Technical TODO

See parent ticket. Make sure that partial loading is working with `\Shopware\Core\Checkout\Customer\SalesChannel\CustomerRoute::load`. Exchange `NoneFieldsCriteria` with the normal `Criteria` in `src/Core/Framework/Api/ApiDefinition/Generator/Schema/StoreApi/paths/account.json`

### PR DESCRIPTION
**Pull request by cyl3x**
### 1. Why is this change necessary?
When providing criteria including the `fields` property to the `CustomerRoute` via PHP, you cannot access the loaded customer via `CustomerResponse::getCustomer`, as its strictly typed as `CustomerEntity` and does not allow for a `PartialEntity`.

### 2. What does this change do, exactly?
Change `CustomerResponse::getCustomer` to also allow `PartialEntity`

### 3. Describe each step to reproduce the issue or behaviour.
- See test case

### 4. Please link to the relevant issues (if any).

fixes #9774

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfilled them

### CODE REVIEW

**Review by En0Ma1259 — APPROVED** [review]

File: tests/integration/Core/Checkout/Customer/SalesChannel/CustomerRouteTest.php [hunk 1]
```diff
@@ -37,6 +45,35 @@ protected function setUp(): void
...
+        $criteria->addFields(['email']);
+
+        $response = $this->getContainer()
+            ->get(CustomerRoute::class)
+            ->load(new Request(), $salesChannelContext, $criteria, $customer);
+
+        static::assertInstanceOf(PartialEntity::class, $response->getPartialCustomer());
+        static::assertEquals(
+            ['id' => $id, '_uniqueIdentifier' => $id, 'email' => $email],
+            \array_filter($response->getCustomer()->jsonSerialize()),
```
Comment (mitelg) [inline tests/integration/Core/Checkout/Customer/SalesChannel/CustomerRouteTest.php:73]: why array filter? :thinking: shouldn't the partialEntity only contain the identifiers and the mail?

Comment (cyl3x) [reply tests/integration/Core/Checkout/Customer/SalesChannel/CustomerRouteTest.php:73]: A lot of properties - especially the collections - have a default value of `null`, which I wanted to filter out

Comment (mitelg) [reply tests/integration/Core/Checkout/Customer/SalesChannel/CustomerRouteTest.php:73]: okay, if this does not blur the test result :grimacing:

**Review by mitelg — APPROVED** [review]

**Review by mstegmeyer — APPROVED** [review]
