### PR TITLE
fix(services): use date filter to localize last update date

### LINKED ISSUE #11234: Date in Service Admin UI is not displayed orrectly
**Description**
In the Service Admin UI, the date is displayed in the format `7/14/2025` (month/day/year), as in the screenshot.

**Expected format**
The date should be displayed in this format: `2025/07/14` (year/month/day).

Image

### PR DESCRIPTION
**Pull request by fschmtt**
fixes #11234

### CODE REVIEW

**Review by nsaliu — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-settings-services/component/sw-settings-services-service-card/index.ts [hunk 1]
```diff
@@ -69,12 +69,23 @@ export default Shopware.Component.wrapComponentConfig({
         },
 
         updatedAt() {
-            return new Date(this.service.updated_at).toLocaleDateString();
+            return this.dateFilter(this.service.updated_at, {
+                month: '2-digit',
+                day: '2-digit',
+                year: '2-digit',
```
Comment (SebastianFranze) [inline src/Administration/Resources/app/administration/src/module/sw-settings-services/component/sw-settings-services-service-card/index.ts]: year should not be displayed in 2 digits

**Review by SebastianFranze — APPROVED** [review]

**Review by adrianles — APPROVED** [review]
