### PR TITLE
fix: Admin assets symfony bundles

### LINKED ISSUE #8271: Admin module of symfony bundle extension not loading
### Shopware Version

6.7-RC1

### Affected area / extension

Platform(Default)

### Actual behaviour

I have an extension build as symfony bundle, let us call it "MyBundle". On SW-6.6 the admin module of this bundle is placed in "public/bundles/my/" by "bin/build-administration.sh" and everything is fine (the Bundle-Extension is stripped off in AssetService->getTargetDirectory)

On SW-6.7-RC1 the admin module is also placed in "public/bundles/my/" but the .vite/entrypoints.json is pointing to  "/bundles/mybundle/administration/", so the Bundle-Extension is not stripped off from the path, and the module is not loaded

In SW6.7 the "getBundles" method in vendor/shopware/core/Framework/Api/Controller/InfoController.php is using vendor/shopware/administration/Framework/Twig/ViteFileAccessorDecorator.php which parse the entrypoints.json to determin the bundled js and css files to load and uses the path as given in the json-file.

In SW6.6 the "getBundles" method is replacing the Bundle-Suffix as in the AssetService

### Expected behaviour

The path should match so the module is loaded

### How to reproduce

Create or use a Shopware-Extension as Symfony-Bundle with an admin module and call bin/build-administration. 
The admin module will not show up

### PR DESCRIPTION
**Pull request by seggewiss**
### 1. Why is this change necessary?
Fixes https://github.com/shopware/shopware/issues/8271

### 2. What does this change do, exactly?
It removes the bundles suffix from bundle names in the ViteFileAccessorDecorator similar to the AssetService.

### 3. Describe each step to reproduce the issue or behaviour.
Create a plugin or bundle with a name like "MyTestBundle" that contains Admin code.

### CODE REVIEW

**Review by shyim — APPROVED** [review]

File: src/Administration/Framework/Twig/ViteFileAccessorDecorator.php [hunk 1]
```diff
@@ -121,6 +121,10 @@ private function getContent(string $fileType, ShopwareBundle $bundle): array
 
                 // Prepend the asset path to the every entry point
                 foreach ($entrypoint as $index => $entry) {
+                    // There is an edge case where symfony removes the "bunble" suffix from the bundle name
```
Comment (keulinho) [inline src/Administration/Framework/Twig/ViteFileAccessorDecorator.php]:
```suggestion
                    // There is an edge case where symfony removes the "bundle" suffix from the bundle name
```

**Review by tajespasarela — APPROVED** [review]

**Review by keulinho — APPROVED** [review]

File: src/Administration/Framework/Twig/ViteFileAccessorDecorator.php (hunk 1 above)
Comment (seggewiss) [reply src/Administration/Framework/Twig/ViteFileAccessorDecorator.php]: image

**Review by keulinho — APPROVED** [review]
