### PR TITLE
fix: order document link availability after customer deletion

### LINKED ISSUE #15960: No email login required for HTML invoice
### Shopware Version

6.7.8.2

### Affected area / extension

Platform(Default)

### Actual behaviour

Shopware adds the following sentence to the email:

```
Aus Datenschutzgründen ist für die HTML-Version ein Login erforderlich.

Im Falle einer Gastbestellung können Sie Ihre E-Mail-Adresse und die Postleitzahl der Rechnungsanschrift verwenden.
```

### Expected behaviour

Remove sentence or add a password form.

### How to reproduce

Click on email link in the email without being logged in.

### PR DESCRIPTION
**Pull request by CR0YD**
### 1. Why is this change necessary?
Documents were accessible via the sent links when the customer of the order was deleted and oneself isn't logged in.

### 2. What does this change do, exactly?
Now not logged in users will always get redirected to the login page.

### 3. Describe each step to reproduce the issue or behaviour.
1. Create a product, a user and with both an order
2. Create a document (e.g. invoide) on that order and send it to the customer
3. Check if the document is accessible via the sent link (should be)
4. Delete the customer
5. Click the link again
6.a (without fix) The document is now visible
6.b (with fix) The login page is now visible

### 4. Please link to the relevant issues (if any).

closes #15960 

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have updated developer-facing release notes if this change is **relevant** for external developers:
  - Add a short entry to `RELEASE_INFO-6.<major>.md` under “Upcoming” for informational changes, including the consequences of the change and how it affects external developers.
  - Add an `UPGRADE` section in `UPGRADE-6.<next-major>.md` for breaking changes (what/why/impact/how to adapt).
  - See the [Documenting a Release Process](https://github.com/shopware/shopware/blob/trunk/delivery-process/documenting-a-release.md) for details.
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Core/Checkout/Document/SalesChannel/DocumentRoute.php [hunk 1]
```diff
@@ -185,7 +185,7 @@ private function checkAuth(string $documentId, Request $request, SalesChannelCon
         }
 
         $orderCustomer = $order->getOrderCustomer();
-        if (!$orderCustomer) {
+        if (!$orderCustomer || $context->getCustomer() === null) {
```
Comment (larskemper) [inline src/Core/Checkout/Document/SalesChannel/DocumentRoute.php]: nit: would maybe make it more obvious that we check the same values for null before comparing them, so that case does not recur:

```suggestion
        $orderCustomer = $order->getOrderCustomer();
        $contextCustomerId = $orderCustomer->getCustomer()->getId();

        if ($orderCustomer->getCustomerId() === null || $contextCustomerId === null) {
            throw DocumentException::customerNotLoggedIn();
        }

        if ($orderCustomer->getCustomerId() === $contextCustomerId) {
            return;
        }
```

Comment (CR0YD) [reply src/Core/Checkout/Document/SalesChannel/DocumentRoute.php]: Changed it.

**Review by larskemper — APPROVED** [review]

**Review by larskemper — APPROVED** [review]

**Review by DennisGarding — APPROVED** [review]
