### PR TITLE
fix: Fixed snippet path loading in the storefront

### LINKED ISSUE #11927: Fix the usage of the new translation system in the storefront
### Shopware Version

6.7.2.0

### Affected area / extension

Platform(Default)

### Actual behaviour

Since we switched to the flysystem, we have a bug that the storefront snippets are broken.

### Expected behaviour

Fix the storefront part of the translation system. Translations installed via the cli command should work in the storefront.

### How to reproduce

1. Install new translations with the cli command
2. Select the new installed translation in the sales channel config.
3. Open the storefront

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by MartinKrzykawski**
### 1. Why is this change necessary?
Since we moved to the Flysystem, the snippets installed via the translation install cli command were broken in the storefront.

### 2. What does this change do, exactly?
I updated the SnippetService to use the private file system for remote and the local file system for local files.

### 3. Describe each step to reproduce the issue or behaviour.
Activate a language for a sales channel that was installed via the translation command and check if the storefront is still working.

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Core/System/Snippet/Files/SnippetFileLoader.php [hunk 1]
```diff
@@ -94,9 +94,11 @@ private function loadCoreSnippets(SnippetFileCollection $snippetFileCollection):
                 $fileName = 'messages.' . $pathComponents['locale'];
             }
 
+            $absolutePath = Path::join($this->kernel->getProjectDir(), 'files', $fileInfo->getPathname());
```
Comment (dgrothaus-sw) [inline src/Core/System/Snippet/Files/SnippetFileLoader.php]: This only works for the default configuration. The path can freely be configured. This path is just the default and will fail for all SaaS instances and probably for most PaaS instances. With the private filesystem, the snippet can be located on a remote filesystem. This assumes, that an absolute path is available, that it is local and that it is reachable from the project directory.

File: tests/unit/Core/System/Snippet/Files/SnippetFileLoaderTest.php [hunk 2]
```diff
@@ -418,10 +419,8 @@ public function testLoadInstalledCoreAndPluginSnippets(): void
         $files = $collection->getElements();
         static::assertContainsOnlyInstancesOf(GenericSnippetFile::class, $files);
 
-        $platformPath = Path::join($loader->getLocalePath('es-ES'), 'Platform');
-        $platformPath = mb_ltrim($platformPath, '/\\');
-        $activePluginPath = Path::join($loader->getLocalePath('es-ES'), 'Plugins', 'activePlugin');
-        $activePluginPath = mb_ltrim($activePluginPath, '/\\');
+        $platformPath = Path::join($projectPath, $loader->getLocalePath('es-ES'), 'Platform');
```
Comment (dgrothaus-sw) [inline tests/unit/Core/System/Snippet/Files/SnippetFileLoaderTest.php]: This will break loading the snippets. In the test environment, the snippets are loaded in an non-local "virtual" in-memory filesystem. With this change, they can't be found, because the files are never written to disk. Flysystem handles the creation and the deletion of the virtual filesystem.

**Review by dgrothaus-sw — CHANGES_REQUESTED** [review]

File: src/Core/System/Snippet/Files/AbstractSnippetFile.php [hunk 3]
```diff
@@ -50,4 +50,6 @@ abstract public function isBase(): bool;
      * Returns a technical name of the bundle or app that the file is belonged to
      */
     abstract public function getTechnicalName(): string;
+
+    abstract public function isLocal(): bool;
```
Comment (marcelbrode) [inline src/Core/System/Snippet/Files/AbstractSnippetFile.php]: Everything here is well documented. Would be great to add this here was well 😄

**Review by marcelbrode — CHANGES_REQUESTED** [review]

**Review by marcelbrode — APPROVED** [review]

File: src/Core/System/Snippet/SnippetService.php [hunk 4]
```diff
@@ -573,12 +576,16 @@ private function flatten(array $array, string $prefix = '', ?array $additionalPa
      */
     private function decodeSnippetFileJson(AbstractSnippetFile $snippetFile): array
     {
+        if ($snippetFile instanceof RemoteSnippetFile) {
+            $content = $this->filesystem->read($snippetFile->getPath());
+        } else {
+            $content = (string) file_get_contents($snippetFile->getPath());
```
Comment (dgrothaus-sw) [inline src/Core/System/Snippet/SnippetService.php]: Please use Symfony's Filesystem here to read the file instead of `file_get_contents()`.

File: tests/unit/Core/System/Snippet/SnippetServiceTest.php [hunk 5]
```diff
@@ -32,9 +34,12 @@ class SnippetServiceTest extends TestCase
 
     private Connection&MockObject $connection;
 
+    private Filesystem&MockObject $filesystem;
+
     protected function setUp(): void
     {
         $this->connection = $this->createMock(Connection::class);
+        $this->filesystem = $this->createMock(Filesystem::class);
```
Comment (dgrothaus-sw) [inline tests/unit/Core/System/Snippet/SnippetServiceTest.php]: You don't need to mock a Flysystem. You can create a Flysystem object with the `InMemory` adapter and test with real files in a temporary filesystem that is discarded as soon as the test terminates. This has the advantage, that you don't need to `expect` things but can just write/read proper files from the filesystem.

**Review by dgrothaus-sw — CHANGES_REQUESTED** [review]
Just minor changes. Overall it's a great change to fix the issue.

**Review by mitelg — CHANGES_REQUESTED** [review]
what Dominik said :grin:

File: src/Core/System/Snippet/SnippetService.php [hunk 6]
```diff
@@ -45,6 +48,8 @@ public function __construct(
         private readonly SnippetFilterFactory $snippetFilterFactory,
         private readonly ExtensionDispatcher $extensionDispatcher,
         private readonly EventDispatcherInterface $eventDispatcher,
+        private readonly FilesystemOperator $flysystem,
```
Comment (mitelg) [inline src/Core/System/Snippet/SnippetService.php]:
```suggestion
        private readonly FilesystemOperator $privateFileSystem,
```

File: src/Core/System/Snippet/SnippetService.php [hunk 7]
```diff
@@ -45,6 +48,8 @@ public function __construct(
...
+        private readonly Filesystem $fileSystem,
```
Comment (mitelg) [inline src/Core/System/Snippet/SnippetService.php]:
```suggestion
        private readonly Filesystem $localFileSystem,
```

**Review by dgrothaus-sw — APPROVED** [review]

**Review by mitelg — APPROVED** [review]
