### PR TITLE
fix: Allow integer backed EnumFields from db

### LINKED ISSUE #7348: EnumField of typ int does not work
*PHP Version:* 8.2   | *Shopware Version:* trunk  | *Affected area / extension:* Platform(Default) 

 ----

*_Actual behaviour:_*

If a EnumField of type integer is used in an EntityDefinition, the `\Shopware\Core\Framework\DataAbstractionLayer\FieldSerializer\EnumFieldSerializer::decode` throws an error. 

As the values from the DB are always string, it throws a type error while trying to create an enum from that value. 

*_Expected behaviour:_*

int EnumFields work without error

*_How to reproduce:_*

Change the level property of the LogEntry definition to an EnumField and execute the `\Shopware\Tests\Integration\Core\Framework\Log\LogEntryTest` test.

### PR DESCRIPTION
**Pull request by dgrothaus-sw**
Mysql stores all ENUM fields as string, so casting from db values to the proper type is needed.
Fixes #7348

### CODE REVIEW

File: src/Core/Framework/DataAbstractionLayer/FieldSerializer/EnumFieldSerializer.php [hunk 1]
```diff
@@ -48,8 +49,9 @@ public function encode(
     public function decode(Field $field, mixed $value): ?\BackedEnum
     {
         $field = $this->checkFieldTypeOrThrowInvalidFieldException($field);
+        $fieldValue = $this->castValueToFieldTypeValue($field, $value);
```
Comment (mitelg) [inline src/Core/Framework/DataAbstractionLayer/FieldSerializer/EnumFieldSerializer.php:52]: I guess we can early return after that if `fieldValue` is null, right? would make it more readable imo, instead of the ternary operator

File: changelog/_unreleased/2025-03-07-change-enumfieldserializer-to-decode-from-database.md [hunk 2]
```diff
@@ -0,0 +1,6 @@
+---
+title: Change EnumFieldSerializer to decode from database
+issue: 7378
+---
+# Core
+* Changed: EnumFieldSerializer now properly casts integer values to allow storage in Mysql
```
Comment (mitelg) [inline changelog/_unreleased/2025-03-07-change-enumfieldserializer-to-decode-from-database.md]: imo it is not necessary to add a changelog file just for a bugfix

File: src/Core/Framework/DataAbstractionLayer/FieldSerializer/EnumFieldSerializer.php [hunk 3]
```diff
@@ -82,4 +84,25 @@ private function checkFieldTypeOrThrowInvalidFieldException(Field $field): EnumF
 
         return $field;
     }
+
+    private function castValueToFieldTypeValue(EnumField $field, mixed $value): string|int|null
```
Comment (mitelg) [inline src/Core/Framework/DataAbstractionLayer/FieldSerializer/EnumFieldSerializer.php]: maybe we could make it more easier, and just type hint `string|null` for `$value`

because other values should never come to this point and we can already make that sure on language level.

**Review by mitelg — CHANGES_REQUESTED** [review]

File: src/Core/Framework/DataAbstractionLayer/FieldSerializer/EnumFieldSerializer.php (hunk 3 above)
Comment (dgrothaus-sw) [reply src/Core/Framework/DataAbstractionLayer/FieldSerializer/EnumFieldSerializer.php]: Is it a fact, that the serializer is only used to decode data from the database and cannot be used to decode JSON data or other data that actually **can** contain integer values. I'd feel better to change it to `string|int|null` instead of omitting the `int`. But I agree that `mixed` was a bad choice.

**Review by mitelg — APPROVED** [review]

File: src/Core/Framework/DataAbstractionLayer/DataAbstractionLayerException.php [hunk 4]
```diff
@@ -418,6 +419,19 @@ public static function expectedArrayWithType(string $path, string $type): self
...
+    public static function expectedFieldValueOfTypeWithValue(
+        Field $field,
+        string $expectedType,
+        string $actualValue
+    ): self {
+        return new self(
+            Response::HTTP_BAD_REQUEST,
+            self::EXPECTED_FIELD_VALUE_TYPE_WITH_VALUE,
+            'Expected value of {{ fieldClass }} to be of type "{{ expectedType }}", got "{{ actualType }}".',
+            ['fieldClass' => $field::class, 'expectedType' => $expectedType, 'actualType' => $actualValue]
```
Comment (AydinHassan) [inline src/Core/Framework/DataAbstractionLayer/DataAbstractionLayerException.php]: This looks a little wrong to me: it should be the type of the value but you pass in the actual value, is that intended?

File: src/Core/Framework/DataAbstractionLayer/FieldSerializer/EnumFieldSerializer.php [hunk 5]
```diff
@@ -82,4 +88,25 @@ private function checkFieldTypeOrThrowInvalidFieldException(Field $field): EnumF
...
+        return match ($field->getType()) {
+            Types::STRING => (string) $value,
+            Types::INTEGER => $this->castToIntOrThrow($field, $value),
+            default => throw DataAbstractionLayerException::fieldHasNoType(static::class),
+        };
+    }
+
+    private function castToIntOrThrow(EnumField $field, mixed $value): int
+    {
+        if (is_numeric($value)) {
```
Comment (AydinHassan) [inline src/Core/Framework/DataAbstractionLayer/FieldSerializer/EnumFieldSerializer.php:107]: This will also return true for floats right? And then there could be some data loss, although I'm not sure how you could get in that weird state without directly modifying the db.

Comment (dgrothaus-sw) [reply src/Core/Framework/DataAbstractionLayer/FieldSerializer/EnumFieldSerializer.php:107]: Yes, this would return true for floats. And this can only be achieved by creating an `ENUM()` field with floats in it. So the database designer would have to mess up the db structure from start to even get there.
You think this should be handled by an exception itself for this case?

File: src/Core/Framework/DataAbstractionLayer/DataAbstractionLayerException.php (hunk 4 above)
Comment (dgrothaus-sw) [reply src/Core/Framework/DataAbstractionLayer/DataAbstractionLayerException.php]: I first intended to pass the type but then realized that sometimes the type cannot be known, so I decided to use the actual value instead of the type. Refactoring did not rename the array key, so good catch from your side.

Comment (AydinHassan) [reply src/Core/Framework/DataAbstractionLayer/DataAbstractionLayerException.php]: You could also just use `get_debug_type` if you wanted to use the type

File: src/Core/Framework/DataAbstractionLayer/FieldSerializer/EnumFieldSerializer.php (hunk 5 above)
Comment (AydinHassan) [reply src/Core/Framework/DataAbstractionLayer/FieldSerializer/EnumFieldSerializer.php:107]: nah I think it's fine 😄

**Review by AydinHassan — APPROVED** [review]

File: src/Core/Framework/DataAbstractionLayer/DataAbstractionLayerException.php (hunk 4 above)
Comment (dgrothaus-sw) [reply src/Core/Framework/DataAbstractionLayer/DataAbstractionLayerException.php]: But it will always be string. The value is always stored as string in the database.
