### PR TITLE
fix: deletion of active customer address

### LINKED ISSUE #12434: Customer address gets stuck on non-default address when changed during checkout
### Shopware Version

6.7.2.1

### Affected area / extension

Platform(Default)

### Actual behaviour

When a customer changes the delivery or billing address during checkout, it will be used in future checkouts as well, despite having a different address set as default. The default value is not changed in the customer profile area and the customer cannot delete that stuck address either, a generic error appears with no error or event logged on the backend.

Image

Changing the default address has no effect. Only when an administrator deletes the “stuck” address in the admin, the default address will be used again on subsequent checkouts.

### Expected behaviour

The address in the checkout would update to the default once the checkout is completed or the default address is changed

### How to reproduce

- Create a customer with two addresses
- Go to checkout and switch to the other address that is not default
- Observe how the address won't change back, nor can the address be deleted

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by cyl3x**
### 1. Why is this change necessary?
Since #6580 it's possible to have diverged default and active customer addresses. This was not handled before in the account and not thought of during the implementation of the address manager.

### 2. What does this change do, exactly?
As active addresses are runtime fields that are resolved correctly if saved IDs are unavailable, the `Active addresses can't be deleted` exception was artificial after all.
We can therefore safely remove this guard and allow active addresses to be deleted.

### 3. Describe each step to reproduce the issue or behaviour.
See #12434

### 4. Please link to the relevant issues (if any).

- fixes #12434

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [x] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Core/Checkout/Customer/SalesChannel/DeleteAddressRoute.php [hunk 1]
```diff
@@ -51,17 +51,15 @@ public function delete(string $addressId, SalesChannelContext $context, Customer
...
-        $activeShippingAddress = $customer->getActiveShippingAddress();
+        $this->addressRepository->delete([['id' => $addressId]], $context->getContext());
 
-        if (
-            ($activeBillingAddress && $addressId === $activeBillingAddress->getId())
-            || ($activeShippingAddress && $addressId === $activeShippingAddress->getId())
-        ) {
-            throw CustomerException::cannotDeleteActiveAddress($addressId);
+        if ($addressId === $customer->getActiveBillingAddress()?->getId()) {
+            $customer->setActiveBillingAddress($customer->getDefaultBillingAddress());
```
Comment (En0Ma1259) [inline src/Core/Checkout/Customer/SalesChannel/DeleteAddressRoute.php]: Should we do `setActiveBillingAddressId()` as well?

Comment (cyl3x) [reply src/Core/Checkout/Customer/SalesChannel/DeleteAddressRoute.php]: The customer has no active address IDs, as the active addresses are runtime fields and the IDs are saved in the sales channel context. See [here](https://github.com/shopware/shopware/blob/773b41ca5f9d36231b9effa78175dba545ed155d/src/Core/System/SalesChannel/Context/SalesChannelContextFactory.php#L269) how the active addresses are resolved.

We could argue about whether to save the new IDs to the sales channel context, but since fallbacks are already defined, I don't think it would be necessary

**Review by En0Ma1259 — APPROVED** [review]

File: src/Core/Checkout/Customer/SalesChannel/DeleteAddressRoute.php [hunk 2]
```diff
@@ -51,17 +51,19 @@ public function delete(string $addressId, SalesChannelContext $context, Customer
...
 
-        if (
-            ($activeBillingAddress && $addressId === $activeBillingAddress->getId())
-            || ($activeShippingAddress && $addressId === $activeShippingAddress->getId())
-        ) {
-            throw CustomerException::cannotDeleteActiveAddress($addressId);
+        if ($addressId === $customer->getActiveBillingAddress()?->getId()) {
+            /** @deprecated tag:v6.8.0 - Use setter instead */
+            $customer->assign(['activeBillingAddress' => $customer->getDefaultBillingAddress()]);
+            // $customer->setActiveBillingAddress($customer->getDefaultBillingAddress());
```
Comment (untilu29) [inline src/Core/Checkout/Customer/SalesChannel/DeleteAddressRoute.php:59]: Remove commented code

File: src/Core/Checkout/Customer/SalesChannel/DeleteAddressRoute.php [hunk 3]
```diff
@@ -51,17 +51,19 @@ public function delete(string $addressId, SalesChannelContext $context, Customer
...
         }
 
-        $this->addressRepository->delete([['id' => $addressId]], $context->getContext());
+        if ($addressId === $customer->getActiveShippingAddress()?->getId()) {
+            /** @deprecated tag:v6.8.0 - Use setter instead */
+            $customer->assign(['activeShippingAddress' => $customer->getDefaultShippingAddress()]);
+            // $customer->setActiveBillingAddress($customer->getDefaultBillingAddress());
```
Comment (untilu29) [inline src/Core/Checkout/Customer/SalesChannel/DeleteAddressRoute.php]: same

File: src/Core/Checkout/Customer/SalesChannel/DeleteAddressRoute.php (hunk 2 above)
Comment (cyl3x) [reply src/Core/Checkout/Customer/SalesChannel/DeleteAddressRoute.php:59]: I left it on purpose. If I cannot create a feature flag condition out of this due to being unable to change the parameter type behind a feature flag, I can at least leave the commented code here :thinking:

File: src/Core/Checkout/Customer/SalesChannel/DeleteAddressRoute.php (hunk 3 above)
Comment (cyl3x) [reply src/Core/Checkout/Customer/SalesChannel/DeleteAddressRoute.php]: s.a.

**Review by FlorianKe — APPROVED** [review]

**Review by untilu29 — APPROVED** [review]
