### PR TITLE
fix: change native type of userId in StateMachineHistoryEntity

### LINKED ISSUE #8990: UserId in StateMachineHistoryEntity should be nullable
### Shopware Version

trunk

### Affected area / extension

Platform(Default)

### Actual behaviour

Currently the `userId` property of the `StateMachineHistoryEntity` class is not nullable. This is problematic because the database field is nullable. 

See here: https://github.com/shopware/shopware/blob/8eb70bfdbb769860660c7d8878e05c0d9fefd5e2/src/Core/System/StateMachine/Aggregation/StateMachineHistory/StateMachineHistoryEntity.php#L35

### Expected behaviour

Field should be nullable.

### How to reproduce

-

### PR DESCRIPTION
**Pull request by schneider-felix**
### 1. Why is this change necessary?

See https://github.com/shopware/shopware/pull/8989#issuecomment-2850258906

### 4. Please link to the relevant issues (if any).

Fixes #8990

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfill them.

### CODE REVIEW

**Review by h1k3r — APPROVED** [review]

**Review by cyl3x — APPROVED** [review]

File: src/Core/System/StateMachine/Aggregation/StateMachineHistory/StateMachineHistoryEntity.php [hunk 1]
```diff
@@ -32,7 +32,7 @@ class StateMachineHistoryEntity extends Entity
 
     protected ?StateMachineStateEntity $toStateMachineState = null;
 
-    protected string $userId;
+    protected ?string $userId;
```
Comment (En0Ma1259) [inline src/Core/System/StateMachine/Aggregation/StateMachineHistory/StateMachineHistoryEntity.php]: Would do something like this. It's more error prove, I guess
```suggestion
    protected ?string $userId = null;
```

Otherwise, this kind of code will fail.
```php
(new StateMachineHistoryEntity())->getUserId();
```

Comment (schneider-felix) [reply src/Core/System/StateMachine/Aggregation/StateMachineHistory/StateMachineHistoryEntity.php]: Yep, sounds good.

**Review by En0Ma1259 — APPROVED** [review]

**Comment by schneider-felix** [comment]
Did you discuss implementing a check for issues like these into dal:validate? I found a few of these issues in the last weeks. And I'm not sure if every single one of these has been found, yet. Releasing 6.7 without fully verifying that the native types work as expected sounds dangerous.

**Review by mstegmeyer — APPROVED** [review]

**Review by Bird87ZA — APPROVED** [review]

**Review by aragon999 — APPROVED** [review]

**Review by M-arcus — APPROVED** [review]

**Review by tinect — APPROVED** [review]
