### PR TITLE
fix: Show update button for composer plugins in custom/plugins

### LINKED ISSUE #6964: Commercial - After the update, the extension can no longer be activated.
After updating to 6.6.10.1, the Commercial extension can no longer be activated. Error messages appear, indicating that tables are missing. When I install a new test environment directly with 6.6.10.1, everything works fine. It seems to be an issue with the update.

### PR DESCRIPTION
**Pull request by keulinho**
fixes: https://github.com/shopware/shopware/issues/6964

### CODE REVIEW

**Review by shyim — APPROVED** [review]

File: src/Core/Framework/Store/Services/ExtensionLoader.php [hunk 1]
```diff
@@ -246,6 +247,8 @@ private function loadLocalAppsCollection(Context $context): ExtensionCollection
                 'installedAt' => null,
                 'active' => false,
                 'type' => ExtensionStruct::EXTENSION_TYPE_APP,
+                'allowUpdate' => $app->isManagedByComposer(),
```
Comment (mstegmeyer) [inline src/Core/Framework/Store/Services/ExtensionLoader.php]: shouldn't this be `!$app->isManagedByComposer()`? (negation)

**Review by mstegmeyer — CHANGES_REQUESTED** [review]

File: src/Core/Framework/Store/Services/ExtensionLoader.php (hunk 1 above)
Comment (keulinho) [reply src/Core/Framework/Store/Services/ExtensionLoader.php]: yes already fixed and added tests ;)

Comment (mstegmeyer) [reply src/Core/Framework/Store/Services/ExtensionLoader.php]: never mind, it was updated ...

**Review by mstegmeyer — APPROVED** [review]

**Review by mstegmeyer — APPROVED** [review]

File: tests/integration/Core/Framework/Store/Services/ExtensionLoaderTest.php [hunk 2]
```diff
@@ -128,6 +129,51 @@ public function testItLoadsExtensionsFromPlugins(): void
...
+        static::assertNotNull($pluginId);
+
+        $pluginRepo->upsert([
+            [
+                'id' => $pluginId,
+                'managedByComposer' => true,
+            ],
+        ], Context::createDefaultContext());
+
+        /** @var PluginCollection $plugins */
```
Comment (mitelg) [inline tests/integration/Core/Framework/Store/Services/ExtensionLoaderTest.php]: please do not use var annotation in tests. could all be replaced by proper assertions

File: src/Core/Framework/Store/Services/ExtensionLoader.php [hunk 3]
```diff
@@ -246,6 +247,8 @@ private function loadLocalAppsCollection(Context $context): ExtensionCollection
                 'installedAt' => null,
                 'active' => false,
                 'type' => ExtensionStruct::EXTENSION_TYPE_APP,
+                'allowUpdate' => !$app->isManagedByComposer(),
```
Comment (mitelg) [inline src/Core/Framework/Store/Services/ExtensionLoader.php:250]: afaik apps can now also be required by composer :thinking: do we need to consider that here?

Comment (keulinho) [reply src/Core/Framework/Store/Services/ExtensionLoader.php:250]: yes that is what we do here ;) 

Apps can not use the `executeComposerCommands` so there managedByComposer is based on whether they are actually installed over composer

For plugins that flag got messed up as there could be plugins that are managed by composer, because `executeComposerCommands` is set to true, and therefore they are required, but they are still installed over custom/plugins

**Review by mitelg — APPROVED** [review]
