### PR TITLE
fix: app flow actions custom headers are not sent

### LINKED ISSUE #3478: `WebhookEventMessageHandler` is ignoring custom headers defined in an App `flow-action.xml` manifest when admin worker is disabled
### PHP Version

8.1

### Shopware Version

6.4.20.2

### Expected behaviour

The request sent by `WebhookEventMessageHandler` should consider the headers defined in the app's `flow-action.xml` file:
```xml
<flow-actions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/shopware/platform/trunk/src/Core/Framework/App/FlowAction/Schema/flow-action-1.0.xsd">
  <flow-action>
    <meta>
      <name>REDACTED_VALID_NAME</name>
      <label>READCTED</label>
      <label lang="de-DE">READCTED</label>
      <url>REDACTED_VALID_URL</url>
      <sw-icon>regular-envelope</sw-icon>
      <requirements>orderAware</requirements>
    </meta>
    <headers>
      <parameter type="string" name="content-type" value="application/json" />
      <parameter type="string" name="authorization" value="{{ authType }} {{ authToken }}" />
    </headers>
    <!-- Further stuff like config, etc... -->
  </flow-action>
</flow-actions>
```

### Actual behaviour

The request sent by `WebhookEventMessageHandler` only contains headers set in `WebhookEventMessageHandler::__invoke`. see:
- [WebhookEventMessageHandler.php line 48](https://github.com/shopware/shopware/blob/070a9ada341acbfa61023398af9457f2afca2ea2/src/Core/Framework/Webhook/Handler/WebhookEventMessageHandler.php#L48C14-L48C14)
- [WebhookEventMessageHandler.php line 53](https://github.com/shopware/shopware/blob/070a9ada341acbfa61023398af9457f2afca2ea2/src/Core/Framework/Webhook/Handler/WebhookEventMessageHandler.php#L53)

Headers set on those lines are:
- `Content-Type`
- `sw-version`
- `sw-user-language`
- `sw-context-language`

But custom headers like `authorization` as described in the `flow-action.xml` file are ignored.

However, if the admin worker is enabled (`enable_admin_worker: true`), the webhook will be sent by the `WebhookDispatcher` itself synchronously, which considers all headers of the `AppFlowActionEvent` (see [WebhookDispatcher.php line 303](https://github.com/shopware/shopware/blob/c59aacc6a7c91aeeb7f89c122ea401442ca63fbc/src/Core/Framework/Webhook/WebhookDispatcher.php#L303)).

### How to reproduce

Disable the admin worker:
```yaml
shopware:
  admin_worker:
    enable_admin_worker: false
```

Create a custom App with flow action definition as described in [this guide](https://developer.shopware.com/docs/v6.4/guides/plugins/apps/flow-builder/add-custom-flow-actions-from-app-system.html).

Customize a flow (like "Order placed") to trigger the custom flow action.

Observe the resulting records in the `webhook_event_log` table in column `request_content`, which will not contain custom headers in the `headers` property.

### PR DESCRIPTION
**Pull request by h1k3r**
### 1. Why is this change necessary?

When custom app workflow action webhooks are processed asynchronously via the message queue (when `admin_worker` is disabled), custom headers defined in the app's `flow.xml` are not sent with the webhook HTTP request. The headers work correctly when `admin_worker` is enabled (synchronous processing).

### 2. What does this change do, exactly?

The fix adds support for transferring custom webhook headers through the message queue by adding `webhookHeaders` to the `WebhookEventMessage`

### Steps to reproduce

1. Create an app with a custom flow action that defines headers

   Follow the [App Flow Actions documentation](https://developer.shopware.com/docs/guides/plugins/apps/flow-builder/add-custom-flow-actions-from-app.html) to create an app.

   Example `Resources/flow.xml`:

   ```xml
    <flow-extensions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/shopware/shopware/trunk/src/Core/Framework/App/Flow/Schema/flow-1.0.xsd">
        <flow-actions>
            <flow-action>
                <meta>
                    <name>my-app.testing-action</name>
                    <label>My custom app action</label>
                    <url>https://...</url>
                    <requirements>orderAware</requirements>
                    <requirements>customerAware</requirements>
                    <requirements>customerGroupAware</requirements>
                    <requirements>delayAware</requirements>
                    <requirements>mailAware</requirements>
                    <requirements>salesChannelAware</requirements>
                    <requirements>userAware</requirements>
                </meta>
                <headers>
                    <parameter type="string" name="sw-test-header" value="category-update"/>
                </headers>
            </flow-action>
        </flow-actions>
    </flow-extensions>
   ```

2. Install the app and create a flow using this action

3.  Go to Settings > Automation > Flow Builder and create a flow that triggers your custom action (e.g., on "Review placed")

4. Trigger the flow and inspect the webhook request 

### 4. Please link to the relevant issues (if any).
- closes https://github.com/shopware/shopware/issues/3478

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have updated developer-facing release notes if this change is **relevant** for external developers:
  - Add a short entry to `RELEASE_INFO-6.<major>.md` under “Upcoming” for informational changes, including the consequences of the change and how it affects external developers.
  - Add an `UPGRADE` section in `UPGRADE-6.<next-major>.md` for breaking changes (what/why/impact/how to adapt).
  - See the [Documenting a Release Process](https://github.com/shopware/shopware/blob/trunk/delivery-process/documenting-a-release.md) for details.
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Core/Framework/Webhook/Handler/WebhookEventMessageHandler.php
Comment (h1k3r) [inline src/Core/Framework/Webhook/Handler/WebhookEventMessageHandler.php:88]: Here newly added headers will also land into webhook_event_log. Not sure what is our policy regarding that 🤔

File: RELEASE_INFO-6.7.md [hunk 1]
```diff
@@ -23,6 +23,10 @@ Also, the generator now sets `CASCADE DELETE` on foreign keys for the translatio
 
 ## App System
 
+### Fixed custom headers for app flow action webhooks in async mode
```
Comment (mitelg) [inline RELEASE_INFO-6.7.md:61]: not sure if we need that entry :man_shrugging:

**Review by mitelg — APPROVED** [review]

File: RELEASE_INFO-6.7.md (hunk 1 above)
Comment (h1k3r) [reply RELEASE_INFO-6.7.md:61]: I believe this may be important. Formally not a bc break, but as most setups are working in async mode, they will start sending headers to the webhooks. It potentially can break something.

**Review by umutdogan4291 — APPROVED** [review]
