### PR TITLE
fix: empty test mail headers

### LINKED ISSUE #10325: Mail sending test function does not work in 6.7 SaaS
### Shopware Version

6.7

### Affected area / extension

Platform(Default)

### Actual behaviour

Mail is not sent, following exception is thrown: `Handling "Symfony\Component\Mailer\Messenger\SendEmailMessage" failed: Unab  
  le to send an email: 1 validation error detected: Value at 'content.simple.  
  headers.2.member.value' failed to satisfy constraint: Member must have leng  
  th greater than or equal to 1 (code BadRequestException).           `

### Expected behaviour

Mail is sent without error

### How to reproduce

Login to a 6.7 SaaS shop, use send test mail function under Settings -> Mail templates

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by MalteJanz**
### 1. Why is this change necessary?
e.g. Amazon SES mail service doesn't like mail headers without a value and rejects requests like that.

### 2. What does this change do, exactly?
Fixes test mode mails to not set headers without a value.

### 3. Describe each step to reproduce the issue or behaviour.
in Shopware SaaS go to settings -> mail templates -> order confirmation -> on the sidebar send a test mail. That mail never gets delivered.

### 4. Please link to the relevant issues (if any).
closes #10325 

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfilled them

### CODE REVIEW

**Review by jozsefdamokos — APPROVED** [review]

**Review by ennasus4sun — APPROVED** [review]

**Review by keulinho — APPROVED** [review]

File: tests/unit/Core/Content/Mail/Service/MailServiceTest.php [hunk 1]
```diff
@@ -331,4 +339,63 @@ public function testMailSenderExceptionIsHandled(): void
...
+            static::isInstanceOf(MailBeforeSentEvent::class),
+            static::isInstanceOf(MailSentEvent::class)
+        );
+        $this->languageLocaleCodeProvider->expects($this->once())->method('getLocaleForLanguageId')->willReturn('en-GB');
+
+        $email = $this->mailService->send($data, Context::createDefaultContext());
+
+        static::assertInstanceOf(Email::class, $email);
+        $headers = $email->getHeaders();
+        static::assertSame($headers->get('X-Shopware-Language-Id')?->getBody(), Defaults::LANGUAGE_SYSTEM);
```
Comment (mitelg) [inline tests/unit/Core/Content/Mail/Service/MailServiceTest.php:392]: @MalteJanz the expected value is the first one :grimacing:

Comment (MalteJanz) [reply tests/unit/Core/Content/Mail/Service/MailServiceTest.php:392]: You're right and I'm sorry 🙈 . Fixed it here: https://github.com/shopware/shopware/pull/10806
