### PR TITLE
fix: Do not dump opcache preload file if warmup directory is used

### LINKED ISSUE #7811: OPCache preload path is invalid
### PHP Version

8.2.26

### Shopware Version

6.6.10.2

### Affected area / extension

Platform(Default)

### Actual behaviour

The file  `opcache-preload.php` contains a wrong path on line 3 for the `require once` statement. The cache folder inside `opcache-preload.php` ends with an underscore (_), but the actual name of the folder ends with an number. Therefore the `opcache-preload.php` script fails and this results into an failing PHP-FPM in our case.

Content of `opcache-preload.php`
Image

Actual directory name:

Image

### Expected behaviour

The `opcache-preload.php` contains a valid path and can be loaded.

### How to reproduce

Enable OPCache and use the shopware version 6.6.10.2.

### PR DESCRIPTION
**Pull request by mitelg**
### 1. Why is this change necessary?

While using `bin/console cache:clear` the cache is also warmed up. This mechanic in Symfony creates an additional container cache directory: https://github.com/symfony/symfony/blob/v7.2.6/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php#L115-L117

Therefore it could happen, that then the opcache preloading file is dumped with the wrong container hash. 

### 2. What does this change do, exactly?

Check for the underscore at the end of the cache directory. If there is one, do nothing. 

### 3. Describe each step to reproduce the issue or behaviour.

See https://github.com/shopware/shopware/issues/7811#issuecomment-2847922185

### 4. Please link to the relevant issues (if any).
- closes https://github.com/shopware/shopware/issues/7811

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfill them.

### CODE REVIEW

**Review by shyim — APPROVED** [review]

File: tests/unit/Core/KernelTest.php [hunk 1]
```diff
@@ -18,16 +25,72 @@ class KernelTest extends TestCase
...
+        return new Kernel(
             'fooBar',
             true,
             $this->createMock(StaticKernelPluginLoader::class),
             'cacheId',
             '6.6.6',
             $this->createMock(Connection::class),
-            'www/shopware'
+            'www/shopware',
+            $filesystem,
```
Comment (h1k3r) [inline tests/unit/Core/KernelTest.php:116]: nit: this is a new optional parameter, we do not check if code still works with default value (when no parameter is provided)

**Review by h1k3r — APPROVED** [review]

**Review by BrocksiNet — APPROVED** [review]

File: tests/unit/Core/KernelTest.php (hunk 1 above)
Comment (mitelg) [reply tests/unit/Core/KernelTest.php:116]: I added a test without providing a fileSystem

File: src/Core/Kernel.php [hunk 2]
```diff
@@ -61,26 +64,27 @@ public function __construct(
         private string $cacheId,
         string $version,
         Connection $connection,
-        protected string $projectDir
+        protected string $projectDir,
+        ?FilesystemOperator $filesystem = null,
```
Comment (shyim) [inline src/Core/Kernel.php:68]: why using league flysystem? We don't need any filesystem abstraction. any reason against symfony filesystem class for this purpose?

Comment (mitelg) [reply src/Core/Kernel.php:68]: as discussed in Slack, I will change to Symfony Filesystem :+1: 

there is not need for the League Flyssystem, and we should keep the kernel as simple as possible
