### PR TITLE
fix: extract url encoder utility

### LINKED ISSUE #12573: Container compilation fails as MediaSerializer has dependency on Storefront service UrlEncodingTwigFilter
### Shopware Version

v6.7.2.2

### Affected area / extension

Platform(Default)

### Actual behaviour

The [`Shopware\Core\Content\ImportExport\DataAbstractionLayer\Serializer\Entity\MediaSerializer`](https://github.com/shopware/shopware/blob/811961647e7eaf15e7e9740c00daeb4ba0566471/src/Core/Content/ImportExport/DataAbstractionLayer/Serializer/Entity/MediaSerializer.php#L49) has a [dependency on a Storefront service](https://github.com/shopware/shopware/blob/811961647e7eaf15e7e9740c00daeb4ba0566471/src/Core/Content/ImportExport/DataAbstractionLayer/Serializer/Entity/MediaSerializer.php#L49) `Shopware\Storefront\Framework\Twig\Extension\UrlEncodingTwigFilter`. This causes the Symfony container compilation to fail in a headless setup:

```
The service "Shopware\Core\Content\ImportExport\DataAbstractionLayer\Serializer\Entity\MediaSerializer" has a dependency on a non-existent service "Shopware\Storefront\Framework\Twig\Extension\UrlEncodingTwigFilter".
```

### Expected behaviour

The Symfony container compilation should succeed regardless if the storefront is installed or not.

### How to reproduce

In a blank shopware project, uninstall the `shopware/storefront` dependency: `composer remove shopware/storefront`. One should observe the container compilation failing after that.

P.S. the functionality in the [UrlEncodingTwigFilter](https://github.com/shopware/storefront/blob/5492d91dfabe958c1aa0203528343c76770788c4/Framework/Twig/Extension/UrlEncodingTwigFilter.php#L25) should most likely be extrated into a service present in `shopware/core` that is shared by the `UrlEncodingTwigFilter` as well as the `MediaSerializer`.

### PR DESCRIPTION
**Pull request by larskemper**
fixes #12573

### CODE REVIEW

**Review by mitelg — APPROVED** [review]

**Review by DennisGarding — APPROVED** [review]

File: src/Core/Framework/Util/UrlEncoder.php [hunk 1]
```diff
@@ -0,0 +1,50 @@
+<?php declare(strict_types=1);
+
+namespace Shopware\Core\Framework\Util;
+
+use Shopware\Core\Framework\Log\Package;
+
+#[Package('framework')]
+class UrlEncoder
+{
+    public static function encodeUrl(?string $mediaUrl): ?string
```
Comment (jozsefdamokos) [inline src/Core/Framework/Util/UrlEncoder.php:10]: Can it only be a "media" URL or can it be more generic?
