### PR TITLE
fix: Change path of header and footer routes to avoid collisions

### LINKED ISSUE #10906: SEO Conflict: Reserved /header and /footer Paths clash with category URLs
### Shopware Version

6.7.0.0

### Affected area / extension

Platform(Default)

### Actual behaviour

$ Problem
If a category is created with the name "header" or "footer", a conflicting SEO URL will be generated (e.g. /header), which causes unexpected and hard-to-diagnose side effects:

- The category page may not render properly, as the request is intercepted and handled as a layout component.
- It becomes impossible to have SEO-friendly URLs for such categories.
- The behavior is not intuitive or documented, leading to developer confusion.

### Expected behaviour

# Shopware should either:

- Avoid using /header and /footer as public-facing routes, or
- Namespace these internal routes (e.g. /__internal/header) to prevent overlap with SEO paths, or
- Warn/block category creation with reserved names, and document the reserved paths accordingly.

### How to reproduce

- Create a category with the name Header or Footer.
- Generate SEO URLs.
- Open any page in the storefront
- Observe that the page no longer renders

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [x] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [x] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by mitelg**
### 1. Why is this change necessary?

the path of the header and footer routes was too generic. It could cause collisions for example if a category named "Header" is created. 

### 2. What does this change do, exactly?

Change the path of header and footer routes to something that is more likely not causing name collision issues

### 3. Describe each step to reproduce the issue or behaviour.

- Create a category named "Header"
- Generate SEO URLs
- call any page of the shop

### 4. Please link to the relevant issues (if any).
- closes https://github.com/shopware/shopware/issues/10906

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Storefront/Controller/NavigationController.php [hunk 1]
```diff
@@ -94,7 +111,12 @@ public function offcanvas(Request $request, SalesChannelContext $context): Respo
         return $response;
     }
 
-    #[Route(path: '/header', name: 'frontend.header', defaults: ['XmlHttpRequest' => true, '_httpCache' => true, '_esi' => true], methods: ['GET'])]
+    #[Route(
+        path: '/_esi/global/header',
+        name: 'frontend.header',
```
Comment (mitelg) [inline src/Storefront/Controller/NavigationController.php:116]: I am not sure, if I need to rename the name :thinking: a route name must be unique, afaik, so this is already reserved by us :grin:

Comment (keulinho) [reply src/Storefront/Controller/NavigationController.php:116]: fine for me, also seo routes don't specify route names, we should be fine

Comment (keulinho) [reply src/Storefront/Controller/NavigationController.php:116]: ah i needed to double check, in the template we reference the route name, therefore we don't even need to adjust that 

anyway we should add a changelog what we changed and why, as the route name stays the same from the point of view how it is intended to be used it even keeps backward compatible and the exact URL for that part should be considered internal

**Review by shyim — APPROVED** [review]

**Review by tobiasberge — APPROVED** [review]

**Review by keulinho — APPROVED** [review]
