### PR TITLE
fix(snippets): Snippet validate command now checks pluralization

### LINKED ISSUE #11299: Change snippets to have pluralization fallbacks
### Shopware Version

6.7.x

### Affected area / extension

Platform(Default)

### Actual behaviour

When using a language with multiple pluralization cases (like Czech or Polish), shopware crashes when pluralization enters a 0 case.

### Expected behaviour

Pluralization should never break the software, even when unhandled cases are entered

### How to reproduce

- Create pluralization snippets like `{1} Singluar | ]1,Inf[ Plural` and use `'%count%', 0`
- Load the page

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by marcelbrode**
fixes: #11299

### 1. Why is this change necessary?
We noticed, some languages have multiple pluralization cases, confusing symfony, when providing exact 2 pluralization options.

### 2. What does this change do, exactly?
This fixes the pluralization ranges and adds tests to prevent further issues
image

### 3. Describe each step to reproduce the issue or behaviour.
- Have a snippet with ]1, Inf[ but no 0 case in Polish or Czech
- Render this snippet in Storefront
- Error

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

**Review by mstegmeyer — APPROVED** [review]

File: src/Core/System/Snippet/Command/ValidateSnippetsCommand.php [hunk 1]
```diff
@@ -16,6 +16,9 @@
 use Symfony\Component\Console\Output\OutputInterface;
 use Symfony\Component\Console\Question\Question;
 
+/**
+ * @phpstan-type Snippets array<string, string|mixed>
```
Comment (mitelg) [inline src/Core/System/Snippet/Command/ValidateSnippetsCommand.php]:
```suggestion
 * @phpstan-type Snippets array<string, string|mixed>
```

saying the value is `string` or `mixed` is quite useless :slightly_smiling_face: if it could be `mixed`, then there is no need to explicitly state `string`.

but better would be to specify exactly what the value could be instead of just saying `mixed` (meaning everything :grin:)

File: src/Core/System/Snippet/SnippetFileHandler.php [hunk 2]
```diff
@@ -7,28 +7,49 @@
 use Shopware\Storefront\Storefront;
 use Symfony\Component\Finder\Finder;
 
+/**
+ * @phpstan-type Snippets array<string, string|mixed>
```
Comment (mitelg) [inline src/Core/System/Snippet/SnippetFileHandler.php]: defining the same PHPStan type twice is not necessary, you import it into another class https://phpstan.org/writing-php-code/phpdoc-types#local-type-aliases

File: src/Core/System/Snippet/SnippetFileHandler.php [hunk 3]
```diff
@@ -7,28 +7,49 @@
...
 #[Package('discovery')]
 class SnippetFileHandler
 {
+    /**
+     * @return Snippets
+     */
     public function openJsonFile(string $path): array
     {
-        $json = json_decode(file_get_contents($path), true);
+        $fileContents = file_get_contents($path);
```
Comment (mitelg) [inline src/Core/System/Snippet/SnippetFileHandler.php]: would be nice, if you could refactor `file_get_contents` and similar native functions with the Symfony Filesystem component

File: src/Core/System/Snippet/SnippetFileHandler.php [hunk 4]
```diff
@@ -7,28 +7,49 @@
...
+
+        if ($fileContents === false) {
+            throw SnippetException::jsonNotFound();
+        }
+
+        $json = json_decode($fileContents, true, 512, \JSON_THROW_ON_ERROR);
 
         $jsonError = json_last_error();
```
Comment (mitelg) [inline src/Core/System/Snippet/SnippetFileHandler.php]: as you added the `JSON_THROW_ON_ERROR` flag to `json_decode` this would never be called :slightly_smiling_face: instead you should catch the \JsonException

File: src/Core/System/Snippet/SnippetFileHandler.php [hunk 5]
```diff
@@ -7,28 +7,49 @@
...
+     * @param Snippets $content
+     */
     public function writeJsonFile(string $path, array $content): void
     {
-        $json = json_encode($content, \JSON_PRETTY_PRINT | \JSON_UNESCAPED_UNICODE | \JSON_UNESCAPED_SLASHES);
-
+        $json = \json_encode(
+            $content,
+            \JSON_THROW_ON_ERROR | \JSON_PRETTY_PRINT | \JSON_UNESCAPED_UNICODE | \JSON_UNESCAPED_SLASHES
+        ) ?: '';
```
Comment (mitelg) [inline src/Core/System/Snippet/SnippetFileHandler.php]: what should the elvis operator catch? :thinking:

File: src/Core/System/Snippet/SnippetFileHandler.php [hunk 6]
```diff
@@ -7,28 +7,49 @@
...
+        $json = str_replace('    ', '  ', $json); // Workaround because of wrong indentation
         file_put_contents($path, $json);
```
Comment (mitelg) [inline src/Core/System/Snippet/SnippetFileHandler.php]: also nice to have refactoring with Symfony Filesystem

File: src/Core/System/Snippet/SnippetFileHandler.php [hunk 7]
```diff
@@ -7,28 +7,49 @@
...
     }
 
+    /**
+     * @return string[]
```
Comment (mitelg) [inline src/Core/System/Snippet/SnippetFileHandler.php]:
```suggestion
     * @return list<string>
```

list is more precise. `string[]` can also be `array<string, string>` or `array<int, string>`

File: src/Core/System/Snippet/SnippetFileHandler.php [hunk 8]
```diff
@@ -38,6 +59,9 @@ public function findAdministrationSnippetFiles(): array
         return $this->findSnippetFilesByPath($bundleDir . '/Resources/app/*/src/');
     }
 
+    /**
+     * @return string[]
```
Comment (mitelg) [inline src/Core/System/Snippet/SnippetFileHandler.php]:
```suggestion
     * @return list<string>
```

File: src/Core/System/Snippet/SnippetFileHandler.php [hunk 9]
```diff
@@ -56,6 +80,9 @@ private function getBundleDir(string $bundleClass): ?string
         return \dirname((string) (new \ReflectionClass($bundleClass))->getFileName());
     }
 
+    /**
+     * @return string[]
```
Comment (mitelg) [inline src/Core/System/Snippet/SnippetFileHandler.php]:
```suggestion
     * @return list<string>
```

File: src/Core/System/Snippet/SnippetFixer.php [hunk 10]
```diff
@@ -5,6 +5,9 @@
 use Shopware\Core\Framework\Log\Package;
 use Shopware\Core\System\Snippet\Struct\MissingSnippetCollection;
 
+/**
+ * @phpstan-type Snippets array<string, string|mixed>
```
Comment (mitelg) [inline src/Core/System/Snippet/SnippetFixer.php]: third time defining this :grin:

File: src/Core/System/Snippet/SnippetFixer.php [hunk 11]
```diff
@@ -15,7 +18,19 @@ public function __construct(private readonly SnippetFileHandler $snippetFileHand
     {
     }
 
+    /**
+     * @deprecated tag:v6.8.0 reason:new-optional-parameter - Will get a second parameter `$invalidPluralization`
+     */
     public function fix(MissingSnippetCollection $missingSnippetCollection): void
```
Comment (mitelg) [inline src/Core/System/Snippet/SnippetFixer.php]: please already add the new parameter with a comment 

```suggestion
    public function fix(MissingSnippetCollection $missingSnippetCollection /*, array $invalidPluralization*/): void
```

File: src/Core/System/Snippet/SnippetFixer.php [hunk 12]
```diff
@@ -15,7 +18,19 @@ public function __construct(private readonly SnippetFileHandler $snippetFileHand
...
+    {
+        /** @var Snippets $invalidPluralization */
+        $invalidPluralization = \func_num_args() === 2 ? func_get_arg(1) : [];
```
Comment (mitelg) [inline src/Core/System/Snippet/SnippetFixer.php]: please surround that with a feature isActive condition so that this not used anymore, if 6.8.0.0 flag is active

File: src/Core/System/Snippet/SnippetValidator.php [hunk 13]
```diff
@@ -38,14 +39,32 @@ public function validate(): array
...
+                        'snippetValue' => $value,
+                        'isFixable' => $validationData['isFixable'],
+                        'path' => $path,
+                    ];
+                }
             }
         }
 
-        return $this->findMissingSnippets($snippetFileMappings, $availableISOs);
+        return [
```
Comment (mitelg) [inline src/Core/System/Snippet/SnippetValidator.php]: nowadays im totally against those associative arrays :grimacing: better would be having structs for this structure. 

this is also a breaking change of the API, which is not directly obvious because of the array return type. before the change the array structure of the `findMissingSnippets` was expected by the callers, now it is something different. 

so it seems, that we now need a new method anyway, we can directly go the nice way with struct classes :slightly_smiling_face:

**Review by mitelg — CHANGES_REQUESTED** [review]

File: src/Core/System/Snippet/SnippetFixer.php (hunk 12 above)
Comment (mitelg) [reply src/Core/System/Snippet/SnippetFixer.php]: additionally we should trigger a deprecation message, if the second parameter is not provided

File: src/Core/System/Snippet/SnippetFileHandler.php (hunk 5 above)
Comment (marcelbrode) [reply src/Core/System/Snippet/SnippetFileHandler.php]: Phpstan being annoying with "could return false"

Comment (mitelg) [reply src/Core/System/Snippet/SnippetFileHandler.php]: even with the throw on error flag? 🤔

File: src/Core/System/Snippet/Command/ValidateSnippetsCommand.php (hunk 1 above)
Comment (marcelbrode) [reply src/Core/System/Snippet/Command/ValidateSnippetsCommand.php]: At first I tried a recursive type, but it seems PHPstant didn't like that :/ Hope `array<string, mixed>` is better for the inner ´mixed`

File: src/Core/System/Snippet/SnippetFileHandler.php (hunk 2 above)
Comment (marcelbrode) [reply src/Core/System/Snippet/SnippetFileHandler.php]: Didn't know that. Thanks 👍

File: src/Core/System/Snippet/SnippetFixer.php (hunk 12 above)
Comment (marcelbrode) [reply src/Core/System/Snippet/SnippetFixer.php]: That feels quite unhandy, but I hope I get your concern.

File: src/Core/System/Snippet/SnippetValidator.php (hunk 13 above)
Comment (marcelbrode) [reply src/Core/System/Snippet/SnippetValidator.php]: A Struct to fill in data for a return to immediately be unpacked after getting that struct feels overengineered, to be honest. But sure it helps new features a lot.

Comment (mitelg) [reply src/Core/System/Snippet/SnippetValidator.php]: but you see the point, that you broke the API of this class here?

File: src/Core/System/Snippet/SnippetFixer.php (hunk 12 above)
Comment (mitelg) [reply src/Core/System/Snippet/SnippetFixer.php]: with that we would make sure, it is correctly adjusted with 6.8.0.0

File: src/Core/System/Snippet/SnippetFileHandler.php (hunk 5 above)
Comment (mitelg) [reply src/Core/System/Snippet/SnippetFileHandler.php]: the flag is okay, but PHPStan should recognise it

File: src/Core/System/Snippet/SnippetValidator.php (hunk 13 above)
Comment (marcelbrode) [reply src/Core/System/Snippet/SnippetValidator.php]: Of course, this has to get fixed, no doubt 😄 I'll push without the file_get_contents exchange, now so you can see already

File: src/Core/System/Snippet/SnippetFixer.php (hunk 12 above)
Comment (marcelbrode) [reply src/Core/System/Snippet/SnippetFixer.php]: Hope its fine the way it is now 🙂

File: src/Core/System/Snippet/Command/ValidateSnippetsCommand.php (hunk 1 above)
Comment (mitelg) [reply src/Core/System/Snippet/Command/ValidateSnippetsCommand.php]: structs would solve that problems :grin:

File: src/Core/System/Snippet/SnippetFixer.php [hunk 14]
```diff
@@ -15,7 +20,23 @@ public function __construct(private readonly SnippetFileHandler $snippetFileHand
...
+     * @deprecated tag:v6.8.0 reason:new-optional-parameter - Will get a second parameter `$invalidPluralization`
+     */
+    public function fix(MissingSnippetCollection $missingSnippetCollection /*, array $invalidPluralization*/): void
+    {
+        /** @var Snippets $invalidPluralization */
+        $invalidPluralization = \func_num_args() === 2 ? func_get_arg(1) : [];
+
+        if (!Feature::isActive('v6.8.0.0') && \func_num_args() < 2) {
+            Feature::triggerDeprecationOrThrow('v6.8.0.0', 'New required parameter `$invalidPluralization` missing');
+        }
```
Comment (mitelg) [inline src/Core/System/Snippet/SnippetFixer.php]:
```suggestion
        if (!Feature::isActive('v6.8.0.0')) {
            /** @var Snippets $invalidPluralization */
            $invalidPluralization = \func_num_args() === 2 ? func_get_arg(1) : [];

            if (\func_num_args() < 2) {
                Feature::triggerDeprecationOrThrow('v6.8.0.0', 'New required parameter `$invalidPluralization` missing');
            }
        }
```

this makes it clear, that the whole code can be removed with next major

File: src/Core/System/Snippet/SnippetFixer.php [hunk 15]
```diff
@@ -15,7 +20,23 @@ public function __construct(private readonly SnippetFileHandler $snippetFileHand
     {
     }
 
-    public function fix(MissingSnippetCollection $missingSnippetCollection): void
+    /**
+     * @deprecated tag:v6.8.0 reason:new-optional-parameter - Will get a second parameter `$invalidPluralization`
+     */
```
Comment (mitelg) [inline src/Core/System/Snippet/SnippetFixer.php:26]: sorry I missed that last time. Symfony uses the same mechanism, but already add the new parameter with a `@param` annotation. 
```suggestion
     * @param Snippets $invalidPluralization
     */
```

this shows users already, that there is a new parameter

File: src/Core/System/Snippet/Struct/SnippetValidationStruct.php [hunk 16]
```diff
@@ -0,0 +1,32 @@
+<?php declare(strict_types=1);
+
+namespace Shopware\Core\System\Snippet\Struct;
+
+use Shopware\Core\Framework\Log\Package;
+use Shopware\Core\Framework\Struct\Struct;
+
+/**
+ * @phpstan-type MissingSnippets array<string, array<string, array{
+ *      path: string,
```
Comment (mitelg) [inline src/Core/System/Snippet/Struct/SnippetValidationStruct.php]: why stopping at the first level? :grin: 

object shape array annotations are the first sign of "hey, this should be a class instead" :wink:

File: src/Core/System/Snippet/SnippetValidator.php [hunk 17]
```diff
@@ -20,12 +25,23 @@ public function __construct(
     }
 
     /**
-     * @return array<string, mixed>
+     * @deprecated tag:v6.8.0 - reason:return-type-change - Will return SnippetValidationStruct
```
Comment (mitelg) [inline src/Core/System/Snippet/SnippetValidator.php]: I know, that you probably want to stick with the well-named method, but this not good to handle for people to make the usage of this class forward compatible. 

we should have an old method, that is deprecated and thrown away and a new method which should be used from now on. 

keeping a method and changing the return type between major versions is not good

Comment (mitelg) [reply src/Core/System/Snippet/SnippetValidator.php]: we might want to get rid of the interface, too :grimacing: as you would need a new interface with the new method, to make it correct

**Review by mitelg — CHANGES_REQUESTED** [review]

File: src/Core/System/Snippet/SnippetFixer.php (hunk 14 above)
Comment (marcelbrode) [reply src/Core/System/Snippet/SnippetFixer.php]: Do I get this wrong? In your case, activating the 6.8 feature flag in 6.7 will lead to an error, since the parameter is commented out, right? That's why I solved it the other way.

File: src/Core/System/Snippet/SnippetFixer.php (hunk 15 above)
Comment (marcelbrode) [reply src/Core/System/Snippet/SnippetFixer.php:26]: So you'd remove the deprecation?

File: src/Core/System/Snippet/Struct/SnippetValidationStruct.php (hunk 16 above)
Comment (marcelbrode) [reply src/Core/System/Snippet/Struct/SnippetValidationStruct.php]: You really do not think it is overengineering that data went from Array to Struct in a Struct? I think that would be too much to add 2 Structs to be contained in one struct, just to not build an array :/

File: src/Core/System/Snippet/SnippetValidator.php (hunk 17 above)
Comment (marcelbrode) [reply src/Core/System/Snippet/SnippetValidator.php]: kay, deprecated it

File: src/Core/System/Snippet/SnippetValidatorInterface.php [hunk 18]
```diff
@@ -3,9 +3,18 @@
...
 {
+    /**
+     * @return array<string, array<string, mixed>>
+     */
     public function validate(): array;
+
+    /**
+     * @deprecated tag:v6.8.0 - Will be removed, use validate() instead
+     */
+    public function getValidation(): SnippetValidationStruct;
```
Comment (mitelg) [inline src/Core/System/Snippet/SnippetValidatorInterface.php]: you cannot simply add methods to an interface :see_no_evil: this will break every implementation of this interface outside of the core

Comment (marcelbrode) [reply src/Core/System/Snippet/SnippetValidatorInterface.php]: Thought it'd be okay because it's in a DI context, but kay.

File: src/Core/System/Snippet/SnippetFixer.php (hunk 15 above)
Comment (mitelg) [reply src/Core/System/Snippet/SnippetFixer.php:26]: no no, as addition

Comment (marcelbrode) [reply src/Core/System/Snippet/SnippetFixer.php:26]: PHPstan doesn't like this. What would you prefer? Entry in phpstan-baseline.neon, removing this or do something like `@todo @param ...`?

File: src/Core/System/Snippet/Struct/SnippetValidationStruct.php (hunk 16 above)
Comment (mitelg) [reply src/Core/System/Snippet/Struct/SnippetValidationStruct.php]: well on another place you said, you had difficulties to describe what the arrays contain. with classes this is well described and also typed. for sure, it might sound easier to just throw everything in arrays, but they are worse in every regards in comparison to objects. maybe worth a read :slightly_smiling_face: -> 
https://peakd.com/php/@crell/php-use-associative-arrays-basically-never
https://presentations.garfieldtech.com/slides-never-use-arrays/phpday2021/

File: src/Core/System/Snippet/SnippetFixer.php (hunk 15 above)
Comment (mitelg) [reply src/Core/System/Snippet/SnippetFixer.php:26]: PHPStan does not recognize the parameter as it is commented, so we should ignore it in place

File: src/Core/System/Snippet/Struct/SnippetValidationStruct.php (hunk 16 above)
Comment (marcelbrode) [reply src/Core/System/Snippet/Struct/SnippetValidationStruct.php]: Kay.

File: src/Core/System/Snippet/SnippetFixer.php (hunk 15 above)
Comment (marcelbrode) [reply src/Core/System/Snippet/SnippetFixer.php:29]: Doesn't work. Even if I ignore without a rule, it still says "nothing to ignore". Since we don't do this anyway ins shopware at all, I'll go with `NOTE`. Searching the web a bit for it, I find that I can't ignore errors caused by phpstan comments itself. Since this PR takes unnecessarily long anyway, I'll stop the experiments here.

Comment (marcelbrode) [reply src/Core/System/Snippet/SnippetFixer.php:26]: Made obsolete, since I put this into a collection

File: src/Core/System/Snippet/SnippetFixer.php [hunk 19]
```diff
@@ -15,7 +21,31 @@ public function __construct(private readonly SnippetFileHandler $snippetFileHand
...
+    public function fix(MissingSnippetCollection $missingSnippetCollection /* , InvalidPluralizationCollection $invalidPluralization */): void
+    {
+        /** @var InvalidPluralizationCollection $invalidPluralization */
+        $invalidPluralization = \func_num_args() === 2 ? func_get_arg(1) : [];
```
Comment (mitelg) [inline src/Core/System/Snippet/SnippetFixer.php]: if the parameter is missing, this should probably be an empty collection 

```suggestion
        $invalidPluralization = \func_num_args() === 2 ? func_get_arg(1) : new InvalidPluralizationCollection();
```

File: src/Core/System/Snippet/SnippetFixer.php [hunk 20]
```diff
@@ -42,8 +72,31 @@ public function fix(MissingSnippetCollection $missingSnippetCollection): void
         }
     }
 
-    private function addTranslationUsingSnippetKey(array $json, string $translation, string $key): array
+    private function fixInvalidPluralization(InvalidPluralizationCollection $invalidPluralization): void
+    {
+        foreach ($invalidPluralization->getIterator() as $invalidSnippet) {
```
Comment (mitelg) [inline src/Core/System/Snippet/SnippetFixer.php:77]:
```suggestion
        foreach ($invalidPluralization as $invalidSnippet) {
```

should be obsolete

File: src/Core/System/Snippet/SnippetValidator.php [hunk 21]
```diff
@@ -20,12 +34,36 @@ public function __construct(
...
      */
     public function validate(): array
+    {
+        Feature::triggerDeprecationOrThrow(
+            'v6.8.0.0',
+            'The method  Will be removed, use `getValidation()` instead.'
+        );
+
+        $missingSnippetsArray = [];
+        foreach ($this->getValidation()->missingSnippets->getIterator() as $entry) {
```
Comment (mitelg) [inline src/Core/System/Snippet/SnippetValidator.php]:
```suggestion
        foreach ($this->getValidation()->missingSnippets as $entry) {
```

File: src/Core/System/Snippet/Struct/InvalidPluralizationCollection.php [hunk 22]
```diff
@@ -0,0 +1,14 @@
...
+namespace Shopware\Core\System\Snippet\Struct;
+
+use Shopware\Core\Framework\Log\Package;
+use Shopware\Core\Framework\Struct\Collection;
+
+/**
+ * @extends Collection<InvalidPluralizationStruct>
+ */
+#[Package('discovery')]
+class InvalidPluralizationCollection extends Collection
```
Comment (mitelg) [inline src/Core/System/Snippet/Struct/InvalidPluralizationCollection.php:12]: to have some additional type safety, you can implement the `getExpectedClass` with returning `InvalidPluralizationStruct` class name

**Review by mitelg — COMMENTED** [review]
looks much better now :+1: 

nice work. only just some smaller remarks

File: src/Core/System/Snippet/SnippetFixer.php (hunk 19 above)
Comment (marcelbrode) [reply src/Core/System/Snippet/SnippetFixer.php]: good catch!

**Review by mitelg — APPROVED** [review]

File: src/Core/System/Snippet/SnippetFileHandler.php [hunk 23]
```diff
@@ -4,31 +4,65 @@
...
 class SnippetFileHandler
 {
+    private readonly Filesystem $filesystem;
+
+    /**
+     * @internal
+     */
+    public function __construct()
+    {
+        $this->filesystem = new Filesystem();
```
Comment (dgrothaus-sw) [inline src/Core/System/Snippet/SnippetFileHandler.php]: Would be good if you move this to the constructor, so the Filesystem can be passed as a mock during testing or with another, compatible object.

File: src/Core/System/Snippet/SnippetFileHandler.php [hunk 24]
```diff
@@ -4,31 +4,65 @@
...
     {
-        $json = json_encode($content, \JSON_PRETTY_PRINT | \JSON_UNESCAPED_UNICODE | \JSON_UNESCAPED_SLASHES);
+        try {
+            $json = \json_encode($content, \JSON_THROW_ON_ERROR | \JSON_PRETTY_PRINT | \JSON_UNESCAPED_UNICODE | \JSON_UNESCAPED_SLASHES);
+        } catch (\Throwable $e) {
+            throw SnippetException::invalidSnippetFile($path, $e);
+        }
 
-        file_put_contents($path, $json);
+        $json = str_replace('    ', '  ', $json); // Workaround because of wrong indentation
```
Comment (dgrothaus-sw) [inline src/Core/System/Snippet/SnippetFileHandler.php:56]: Does this happen a lot? That the json is indented in a way that causes problems?

File: src/Core/System/Snippet/SnippetValidator.php [hunk 25]
```diff
@@ -2,10 +2,24 @@
...
 use Shopware\Core\System\Snippet\Files\GenericSnippetFile;
 use Shopware\Core\System\Snippet\Files\SnippetFileCollection;
+use Shopware\Core\System\Snippet\Struct\InvalidPluralizationCollection;
+use Shopware\Core\System\Snippet\Struct\InvalidPluralizationStruct;
+use Shopware\Core\System\Snippet\Struct\MissingSnippetCollection;
+use Shopware\Core\System\Snippet\Struct\MissingSnippetStruct;
+use Shopware\Core\System\Snippet\Struct\SnippetValidationStruct;
 
+/**
+ * @phpstan-type MissingSnippets array<string, array<string, array{
```
Comment (dgrothaus-sw) [inline src/Core/System/Snippet/SnippetValidator.php]: Is this needed? I see there's a `MissingSnippetCollection`. Can't that be used instead of using an array that has to be defined with a phpstan-type?

**Review by dgrothaus-sw — APPROVED** [review]
Just a few questions.

File: src/Core/System/Snippet/SnippetFileHandler.php (hunk 24 above)
Comment (marcelbrode) [reply src/Core/System/Snippet/SnippetFileHandler.php:56]: Well, sometimes. In general, it's somewhat inconsistent, and I just don't want the json files to be re-indented if I trigger the command.

File: src/Core/System/Snippet/SnippetValidator.php (hunk 25 above)
Comment (marcelbrode) [reply src/Core/System/Snippet/SnippetValidator.php]: Then PHPstan would complain since that "MissingSnippets" type does want more stuff than I, that's why I want to stick to this to not artifacally fill data for no purpose, you know?

Comment (marcelbrode) [reply src/Core/System/Snippet/SnippetValidator.php]: In Line 123 you can see, that that array will be transformed into a collection at that point.

Renamed it to `MissingSnippetsArray` to make this a bit more clear

**Review by dgrothaus-sw — APPROVED** [review]

File: src/Core/System/Snippet/SnippetFileHandler.php (hunk 23 above)
Comment (mitelg) [reply src/Core/System/Snippet/SnippetFileHandler.php]: the Symfony FileSystem has no "mock" or interface, which would make it possible to overwrite it in tests. for that, I would use the FlySystem
