### PR TITLE
fix: Set state machine history FK constraint to integration to SET NULL

### LINKED ISSUE #11583: Cloud: Errors when deleting integrations
### Shopware Version

cloud

### Affected area / extension

Platform(Default)

### Actual behaviour

When attempting to delete an integration, the following error may occur:

```
{code: "1451", status: "500", title: "Internal Server Error",…}
detail: 
"An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`ojlcjh6rkxgeaqj0g4hrmr`.`state_machine_history`, CONSTRAINT `fk.state_machine_history.integration_id` FOREIGN KEY (`integration_id`) REFERENCES `integration` (`id`) ON UPDATE CASCADE)"
status
: 
"500"
title
: 
"Internal Server Error"
```

### Expected behaviour

.

### How to reproduce

.

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by keulinho**
fixes https://github.com/shopware/shopware/issues/11583

### 1. Why is this change necessary?
The FK was added here: https://github.com/shopware/shopware/pull/8989/files#diff-7e93e76d1e17baa1da96b2b99becf9bcbf0d03c7c740c0a85bcf381ca898c918R26
With on delete action `NO ACTION` which equals `RESTRICT` for InnoDB: https://dev.mysql.com/doc/refman/8.4/en/create-table-foreign-keys.html#foreign-key-referential-actions

Thus integrations that added state machine state changes could not be uninstalled anymore.

### 2. What does this change do, exactly?
Set the on delete action for the FK to `SET NULL`, to allow integrations to be uninstalled again. 
This is similar to the behaviour for the `user_id` column for that table. 

And funny enough we had the same issue with that column as well, see: https://github.com/shopware/shopware/blob/trunk/src/Core/Migration/V6_3/Migration1609857999FixStateMachineHistoryUserConstraint.php#L15

### 3. Describe each step to reproduce the issue or behaviour.
Install a integration that mutates order states and try to delete it again after it changed the state of an order.

### 4. Please link to the relevant issues (if any).
https://github.com/shopware/shopware/issues/11583

### CODE REVIEW

File: src/Core/Migration/V6_7/Migration1753799632FixStateMachineHistoryIntegrationConstraint.php [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+        $this->dropForeignKeyIfExists($connection, 'state_machine_history', 'fk.state_machine_history.integration_id');
+
+        $connection->executeStatement('
+            ALTER TABLE `state_machine_history`
+            ADD CONSTRAINT `fk.state_machine_history.integration_id` FOREIGN KEY (`integration_id`)
+                REFERENCES `integration` (`id`) ON DELETE SET NULL ON UPDATE CASCADE;
+        ');
+    }
+
+    public function updateDestructive(Connection $connection): void
```
Comment (mitelg) [inline src/Core/Migration/V6_7/Migration1753799632FixStateMachineHistoryIntegrationConstraint.php]: can be removed completely

File: src/Core/Migration/V6_7/Migration1753799632FixStateMachineHistoryIntegrationConstraint.php [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+class Migration1753799632FixStateMachineHistoryIntegrationConstraint extends MigrationStep
+{
+    public function getCreationTimestamp(): int
+    {
+        return 1753799632;
+    }
+
+    public function update(Connection $connection): void
+    {
+        $this->dropForeignKeyIfExists($connection, 'state_machine_history', 'fk.state_machine_history.integration_id');
```
Comment (mitelg) [inline src/Core/Migration/V6_7/Migration1753799632FixStateMachineHistoryIntegrationConstraint.php:25]: yeah, my PHPStan rule works :tada: :sweat_smile: 

I think, we can add an ignore here, as the FK is added directly again.

**Review by mitelg — CHANGES_REQUESTED** [review]

File: src/Core/Migration/V6_7/Migration1753799632FixStateMachineHistoryIntegrationConstraint.php (hunk 2 above)
Comment (keulinho) [reply src/Core/Migration/V6_7/Migration1753799632FixStateMachineHistoryIntegrationConstraint.php:25]: Looking at this i'm not sure if dropping a FK is actually a dangerous operation, because in general the DB now accepts more and everything you could put into the column before you can put in afterwards as well

When it comes to FKs I guess adding one where there was none before is more dangerous in terms of blue green, because suddenly it is validated that the id exists in the other table 🤔

Comment (mitelg) [reply src/Core/Migration/V6_7/Migration1753799632FixStateMachineHistoryIntegrationConstraint.php:25]: :thinking: you are not wrong here :thinking:

**Review by mitelg — APPROVED** [review]

**Review by mstegmeyer — APPROVED** [review]

**Comment by mitelg** [comment]
do we also need to backport this?

**Comment by keulinho** [comment]
@mitelg i also thought about this, but actually I think this is not that critical, only deleting an integration does not work for the moment, but that should not be critical do your shop, all other flows continue to work

For the one cloud customer that reported this we already fixed this manually

additionally when we backport this we would include a migration into the patch release, which would mean for the cloud deployment that it would need a downtime
