### PR TITLE
fix: temporary technical name migration

### LINKED ISSUE #8238: Migration for enforcing technical names fails until all fields are filled
### Shopware Version

6.7.0.0

### Affected area / extension

Platform(Default)

### Actual behaviour

When running the 6.7 migrations, if payment or shipping methods exist without technical names, the migration will fail. This is partly expected as we want to enforce the technical name. However, the solution is not easy as you need to understand the SQL error message and set the technical names for your and foreign shipping and payment methods, the latter is not intended.

### Expected behaviour

The migrations should not fail. As most plugins will take care of this with the upcoming 6.7 compatibility, they may overlook that the requirement of the technical name was announced two majors ago and add one with their 6.7 compatible version. This will be too late, as Shopware migrations will have been done by then.  
We should add a temporary name like `temporary_<id-of-method>` to have an easily identifiable name so that our migrations can succeed and plugins can add/replace the technical name.

### How to reproduce

Run 6.7 migrations with shipping or payment methods without technical names

### PR DESCRIPTION
**Pull request by cyl3x**
We should add a temporary name like temporary_<id-of-method> to have an easily identifiable name so that our migrations can succeed and plugins can add/replace the technical name.

### 4. Please link to the relevant issues (if any).

fixes #8238

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [x] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfill them.

### CODE REVIEW

File: tests/migration/Core/V6_7/Migration1697112043TemporaryPaymentAndShippingTechnicalNamesTest.php [hunk 1]
```diff
@@ -0,0 +1,152 @@
...
+                ['ids' => $byteList],
+                ['ids' => ArrayParameterType::BINARY],
+            );
+        }
+    }
+
+    public function testMigrate(): void
+    {
+        $this->rollback();
+        $this->prepare();
```
Comment (mstegmeyer) [inline tests/migration/Core/V6_7/Migration1697112043TemporaryPaymentAndShippingTechnicalNamesTest.php:56]: please use database transaction instead. We're not altering tables here.

File: tests/migration/Core/V6_7/Migration1697112043TemporaryPaymentAndShippingTechnicalNamesTest.php [hunk 2]
```diff
@@ -0,0 +1,152 @@
...
+        $byteList = Uuid::fromHexToBytesList(\array_values($this->ids->all()));
+
+        foreach (['payment_method', 'shipping_method', 'app_shipping_method', 'app_payment_method'] as $table) {
+            $this->connection->executeStatement(
+                'DELETE FROM `' . $table . '` WHERE `id` in (:ids)',
+                ['ids' => $byteList],
+                ['ids' => ArrayParameterType::BINARY],
+            );
+        }
+    }
```
Comment (mstegmeyer) [inline tests/migration/Core/V6_7/Migration1697112043TemporaryPaymentAndShippingTechnicalNamesTest.php:51]: this becomes unnecessary then.

**Review by mstegmeyer — CHANGES_REQUESTED** [review]

File: tests/migration/Core/V6_7/Migration1697112043TemporaryPaymentAndShippingTechnicalNamesTest.php (hunk 1 above)
Comment (cyl3x) [reply tests/migration/Core/V6_7/Migration1697112043TemporaryPaymentAndShippingTechnicalNamesTest.php:56]: It would be lovely it that's true, but I need to roll back to nullable `technical_name` fields

**Review by mstegmeyer — APPROVED** [review]

File: tests/migration/Core/V6_7/Migration1697112043TemporaryPaymentAndShippingTechnicalNamesTest.php (hunk 1 above)
Comment (mstegmeyer) [reply tests/migration/Core/V6_7/Migration1697112043TemporaryPaymentAndShippingTechnicalNamesTest.php:56]: image

**Review by lernhart — APPROVED** [review]
