### PR TITLE
fix: Fix webhook dispatching for not versioned events

### LINKED ISSUE #7858: customer_address.written Event in App not triggered correctly
### PHP Version

8.3

### Shopware Version

6.6.9.0

### Affected area / extension

Platform(Default)

### Actual behaviour

We are developing an app to connect our ERP to Shopware. Among other things, we use the `customer_address.written` event. As soon as we add the option `onlyLiveVersion=‘true’`, not a single request is received.

As soon as we remove the option, the requests arrive. However, these do not contain a version ID, so it is impossible to distinguish drafts from live versions.

Here is an example request body:

```
Array
(
    [data] => Array
        (
            [payload] => Array
                (
                    [0] => Array
                        (
                            [entity] => customer_address
                            [operation] => insert
                            [primaryKey] => 0195c77b1319703fa7d5596c217bf26a
                            [updatedFields] => Array
                                (
                                    [0] => id
                                    [1] => customerId
                                    [2] => countryId
                                    [3] => countryStateId
                                    [4] => salutationId
                                    [5] => firstName
                                    [6] => lastName
                                    [7] => zipcode
                                    [8] => city
                                    [9] => company
                                    [10] => street
                                    [11] => department
                                    [12] => title
                                    [13] => phoneNumber
                                    [14] => additionalAddressLine1
                                    [15] => additionalAddressLine2
                                    [16] => createdAt
                                )

                        )

                )

            [event] => customer_address.written
        )

    [source] => Array
        (
            [url] => https://localhost
            [eventId] => 0195c77b13447341b182b7fdc0352b15
            [shopId] => aHsdxAmPz87Asgxv
            [appVersion] => 1.0.0
            [inAppPurchases] => 
        )

    [timestamp] => 1742808486
)
```

### Expected behaviour

The option onlyLiveVersion=‘true’ should not prevent any further requests from being received.

The request body should also contain the version ID.

### How to reproduce

Add the following line to the manifext.xml:

`<webhook name=‘customer-address-written’ url=‘[target-url]’ event=‘customer_address.written’/>`

Add or remove the `onlyLiveVersion="true"` option.

### PR DESCRIPTION
**Pull request by keulinho**
Fixes https://github.com/shopware/shopware/issues/7858

### CODE REVIEW

File: tests/unit/Core/Framework/Webhook/Service/WebhookManagerTest.php [hunk 1]
```diff
@@ -176,10 +193,39 @@ public function testWebhooksForLiveVersionOnlyAreIgnoredIfPayloadDoesNotHaveLive
...
+    {
+        $entityRepository = new StaticEntityRepository([], new CustomerDefinition());
+
+        $event = $entityRepository->create([
+            [
+                'id' => Uuid::randomHex(),
+            ],
+        ], Context::createDefaultContext());
+
+        /** @var EntityWrittenEvent $eventByEntityName */
```
Comment (mitelg) [inline tests/unit/Core/Framework/Webhook/Service/WebhookManagerTest.php]: please do not use var annotations. Especially in tests you can simply assert the type. also see https://github.com/shopware/shopware/blob/trunk/coding-guidelines/core/writing-code-for-static-analysis.md

Comment (keulinho) [reply tests/unit/Core/Framework/Webhook/Service/WebhookManagerTest.php]: copy & pasted -> fixed that plus the source as well 👍

**Review by mitelg — APPROVED** [review]

**Review by nfortier-shopware — APPROVED** [review]

**Review by BrocksiNet — APPROVED** [review]

**Comment by JoshuaBehrens** [comment]
I am glad you already fixed this. It is flagged as RC3 and the commit 3fdb485564fe9bf94ff82b0f0041107ed9e64d0a is not released with RC3 :( what is happening here @keulinho

**Comment by mitelg** [comment]
@JoshuaBehrens it was part of RC3 :thinking: https://github.com/shopware/shopware/commit/7a852b18f2a8bf292e4001a6b03d256be1a12300

**Comment by JoshuaBehrens** [comment]
@mitelg ok this was some cherry-pick thing and therefore the pull request reference does not match the actual code. But why isn't it in my vendor folder like this . Weird

**Comment by mitelg** [comment]
@JoshuaBehrens
