### PR TITLE
fix: case (in)sensitiv guest order validation

### LINKED ISSUE #8686: Order deeplink email check is case-sensitive
### Shopware Version

6.6.10.3

### Affected area / extension

Platform(Default)

### Actual behaviour

When a guest customer makes an order and visits the order from the link in the order confirmation, he has to enter his email address and postcode. The email check is case-sensitive. When the customer enters the email as "Test@Example.com" in the order and tries to access it afterwards with "test@example.com", the order will not be shown.

### Expected behaviour

The order should always show, even when the email address is entered with a mixed case. In the orderRoute (Core/Checkout/Order/SalesChannel/OrderRoute.php) the email in function "checkGuestAuth" should be checked case-insensitiv.

### How to reproduce

1. Make an order as a guest
2. open the order link in the order-confirmation
3. enter the email with a different case from the entered order email

### PR DESCRIPTION
**Pull request by En0Ma1259**
closes https://github.com/shopware/shopware/issues/8686

### Actual behaviour

When a guest customer makes an order and visits the order from the link in the order confirmation, he has to enter his email address and postcode. The email check is case-sensitive. When the customer enters the email as "Test@Example.com" in the order and tries to access it afterwards with "test@example.com", the order will not be shown.

### Expected behaviour

The order should always show, even when the email address is entered with a mixed case. In the orderRoute (`Core/Checkout/Order/SalesChannel/OrderRoute.php`) the email in function "checkGuestAuth" should be checked case-insensitiv.

### How to reproduce

1. Make an order as a guest
2. open the order link in the order-confirmation
3. enter the email with a different case from the entered order email

### Changes
`\Shopware\Core\Checkout\Order\SalesChannel\OrderRoute::checkGuestAuth`
E-Mail will be compared with `strtolower` and postal code will compare with `strtoupper`

### CODE REVIEW

**Review by FlorianKe — APPROVED** [review]

File: tests/unit/Core/Checkout/Order/SalesChannel/OrderRouteTest.php [hunk 1]
```diff
@@ -93,4 +97,103 @@ public function testLoadCustomerOrder(): void
...
+        );
+
+        $criteria = new Criteria();
+        $criteria->addFilter(new EqualsFilter('deepLinkCode', 'deepLinkCode'));
+
+        $request = new Request();
+        $request->attributes->set('email', $mail);
+        $request->attributes->set('zipcode', $postalCode);
+
+        /** @var OrderEntity $responseOrder */
```
Comment (mitelg) [inline tests/unit/Core/Checkout/Order/SalesChannel/OrderRouteTest.php]: please do not use var annotations. Especially in tests you can simply assert the type. also see https://github.com/shopware/shopware/blob/trunk/coding-guidelines/core/writing-code-for-static-analysis.md

Comment (En0Ma1259) [reply tests/unit/Core/Checkout/Order/SalesChannel/OrderRouteTest.php]: Also removed the annotation from the other test

**Review by mitelg — APPROVED** [review]

File: changelog/_unreleased/2025-04-28-case-insensitive-guest-order-check.md [hunk 2]
```diff
@@ -0,0 +1,6 @@
+---
+title: Case insensitive guest order e-mail and postal code check
+issue: #8686
+---
+# Core
+* Changed `\Shopware\Core\Checkout\Order\SalesChannel\OrderRoute::checkGuestAuth`. Compare the guest's e-mail address with `strtolower` and the postal code with `strtoupper` to avoid small typing differences.
```
Comment (cyl3x) [inline changelog/_unreleased/2025-04-28-case-insensitive-guest-order-check.md]:
```suggestion
* Changed `\Shopware\Core\Checkout\Order\SalesChannel\OrderRoute::checkGuestAuth` to compare guest email address and postalcode case insensitive.
```

**Review by cyl3x — APPROVED** [review]

**Review by mstegmeyer — APPROVED** [review]

**Review by Bird87ZA — APPROVED** [review]
