### PR TITLE
fix: theme config inheritance for database child themes

### LINKED ISSUE #8591: Error when assigning duplicated child theme to sales channel
### Shopware Version

6.6.9, trunk

### Affected area / extension

Platform(Default)

### Actual behaviour

After duplicating a child theme using the "Create duplicate" button in the administration, assigning the duplicated child theme to a sales channel results in a theme compilation error.

### Expected behaviour

The duplicated child theme should behave the same as the original child theme and be assignable to a sales channel without compilation errors.

### How to reproduce

1. Install the themes provided in the attached archive: [themes.zip](https://github.com/user-attachments/files/19757804/themes.zip)
 - MyAppTheme – a custom theme
 - MyAppThemeChild – a child theme that inherits from MyAppTheme.

2. In the Shopware administration:
- Navigate to Content -> Themes
- Use the "Create duplicate" button on MyAppThemeChild to create a duplicate.
- Try to assign the duplicated child theme to any sales channel. On save compilation error happens:

Image

#### Additional context

- The parent theme (MyAppTheme) can be duplicated and assigned without any issues.
- The original child theme (MyAppThemeChild) can also be assigned without error.
- Duplicated version of the child theme causes a compilation failure.

### PR DESCRIPTION
**Pull request by Phil23**
Fixes: #8591

### 1. Why is this change necessary?
The theme config inheritance setting is not resolved correctly for database child themes, resulting in a broken theme config.

### 2. What does this change do, exactly?
Fix the corresponding config inheritance resolution to iterate recursively through parent themes to apply the correct theme config settings. 

### 3. Describe each step to reproduce the issue or behaviour.

Test app themes and the description to reproduce this behaviour can be found in the issue: [#8591](https://github.com/shopware/shopware/issues/8591)

### CODE REVIEW

**Review by mitelg — APPROVED** [review]

File: src/Storefront/Theme/ConfigLoader/DatabaseConfigLoader.php [hunk 1]
```diff
@@ -300,22 +300,38 @@ private function resolveMediaIds(StorefrontPluginConfiguration $pluginConfig, Co
      */
     private function getConfigInheritance(ThemeEntity $mainTheme): array
     {
-        if (!\is_array($mainTheme->getBaseConfig())) {
-            return [];
+        if (\is_array($mainTheme->getBaseConfig())
```
Comment (h1k3r) [inline src/Storefront/Theme/ConfigLoader/DatabaseConfigLoader.php]: nit: I would probably introduce local variable for `mainTheme->getBaseConfig() ` - could simplify reading next lines

File: tests/unit/Storefront/Theme/ThemeMergedConfigBuilderTest.php [hunk 2]
```diff
@@ -171,15 +196,40 @@ public function testGetThemeConfigurationFieldStructure(
...
-            new EntitySearchResult(
-                'theme',
-                1,
-                $themeCollection,
-                null,
-                new Criteria(),
-                $this->context
-            )
+        // Set up the mock to handle both the main search and the parent theme search
+        $this->themeRepositoryMock->method('search')->willReturnCallback(
```
Comment (h1k3r) [inline tests/unit/Storefront/Theme/ThemeMergedConfigBuilderTest.php:189]: Maybe move it into private method? 🤔  Quite a logic to duplicate

**Review by h1k3r — APPROVED** [review]

File: src/Storefront/Theme/ConfigLoader/DatabaseConfigLoader.php (hunk 1 above)
Comment (Phil23) [reply src/Storefront/Theme/ConfigLoader/DatabaseConfigLoader.php]: Thx, I implemented it.

File: tests/unit/Storefront/Theme/ThemeMergedConfigBuilderTest.php (hunk 2 above)
Comment (Phil23) [reply tests/unit/Storefront/Theme/ThemeMergedConfigBuilderTest.php:189]: Thx, I implemented it.

File: src/Storefront/Theme/ThemeMergedConfigBuilder.php [hunk 3]
```diff
@@ -108,7 +110,18 @@ public function getPlainThemeConfiguration(string $themeId, Context $context): a
...
+        if ($theme->getTechnicalName() === null && $theme->getParentThemeId() !== null) {
+            $parentTheme = $themes->filter(fn (ThemeEntity $themeEntry) => $themeEntry->getId() === $theme->getParentThemeId())->first();
+
+            if ($parentTheme instanceof ThemeEntity) {
+                $themeConfig['themeTechnicalName'] = $parentTheme->getTechnicalName();
+            }
+        } else {
+            $themeConfig['themeTechnicalName'] = $theme->getTechnicalName();
+        }
+
```
Comment (Phil23) [inline src/Storefront/Theme/ThemeMergedConfigBuilder.php:123]: @mitelg, @h1k3r I implemented this additional change, because database themes don't have a technical name, so if falls back to the parent theme to resolve things like snippet keys etc.

File: src/Storefront/Theme/ThemeMergedConfigBuilder.php [hunk 4]
```diff
@@ -110,7 +110,18 @@ public function getPlainThemeConfiguration(string $themeId, Context $context): a
             }
         }
 
-        $themeConfig['themeTechnicalName'] = $theme->getTechnicalName();
+        // Check if the theme is a database copy of a physical theme.
+        // If so, use the technical name of the parent theme.
+        if ($theme->getTechnicalName() === null && $theme->getParentThemeId() !== null) {
+            $parentTheme = $themes->filter(fn (ThemeEntity $themeEntry) => $themeEntry->getId() === $theme->getParentThemeId())->first();
```
Comment (mitelg) [inline src/Storefront/Theme/ThemeMergedConfigBuilder.php:115]: `\Shopware\Core\Framework\DataAbstractionLayer\EntityCollection::filterByProperty` could also be used

**Review by mitelg — APPROVED** [review]

File: src/Storefront/Theme/ThemeMergedConfigBuilder.php (hunk 4 above)
Comment (Phil23) [reply src/Storefront/Theme/ThemeMergedConfigBuilder.php:115]: Does it have any advantages? I just did it like it was done before in that file. 😅

Comment (mitelg) [reply src/Storefront/Theme/ThemeMergedConfigBuilder.php:115]: no, doesn't matter :sweat_smile:

Comment (mitelg) [reply src/Storefront/Theme/ThemeMergedConfigBuilder.php:115]: maybe a bit easier to read :man_shrugging:

Comment (mitelg) [reply src/Storefront/Theme/ThemeMergedConfigBuilder.php:115]: but as I already approved, you can of course ignore this :blush:
