### PR TITLE
fix: auto select correct mail template for ZUGFeRD document types

### LINKED ISSUE #16019: No email template preselected for ZUGFeRD invoice document types when using “Create and send”
### Shopware Version

6.7.8.2

### Affected area / extension

Platform(Default)

### Actual behaviour

When creating an invoice and selecting “Create and send” in the modal, no email template is preselected for the following document types:

- Invoice: PDF with embedded ZUGFeRD E-invoice
- Invoice: ZUGFeRD E-invoice

### Expected behaviour

Preselected email template.

### How to reproduce

Create an order.
Create an invoice.
Select a ZUGFeRD document type and select “Create and send”

### PR DESCRIPTION
**Pull request by larskemper**
resolves https://github.com/shopware/shopware/issues/16019

The send document modal only auto selected mail templates for the invoice, credit_note, delivery_note, canncellation_invoice. ZUGFeRD variants were silently ignored, leaving the template field blank.

### CODE REVIEW

**Review by ennasus4sun — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-send-document-modal/index.js [hunk 1]
```diff
@@ -113,35 +133,33 @@ export default {
...
 
-                    this.mailTemplateId = mailTemplate.id;
-                    this.onMailTemplateChange(mailTemplate.id, mailTemplate);
-                });
+            const context = {
+                ...Shopware.Context.api,
+                languageId: this.order.languageId,
+            };
+
+            this.mailTemplateRepository.search(criteria, context).then((result) => {
```
Comment (MalteJanz) [inline src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-send-document-modal/index.js]: returning this promise would be nice, so the callsite can wait for the process to finish if they want to

File: src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-send-document-modal/index.js [hunk 2]
```diff
@@ -113,35 +133,33 @@ export default {
...
-                invoice: 'invoice_mail',
-                credit_note: 'credit_note_mail',
-                delivery_note: 'delivery_mail',
-                storno: 'cancellation_mail',
-            };
+            const type = this.document.documentType.technicalName;
 
-            if (!documentMailTemplateMapping.hasOwnProperty(this.document.documentType.technicalName)) {
+            if (!(type in DOCUMENT_MAIL_TEMPLATE_MAPPING)) {
                 return;
```
Comment (MalteJanz) [inline src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-send-document-modal/index.js:139]: if the promise below is returned, we should keep consistent returns and change this as well

```suggestion
                return Promise.resolve();
```

**Review by MalteJanz — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-send-document-modal/index.js (hunk 1 above)
Comment (larskemper) [reply src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-send-document-modal/index.js]: refactored the component to use async / await throughout

File: src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-send-document-modal/index.js [hunk 3]
```diff
@@ -119,20 +119,20 @@ export default {
         },
     },
 
-    created() {
-        this.createdComponent();
+    async created() {
```
Comment (MalteJanz) [inline src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-send-document-modal/index.js:122]: Nit: I think the vue lifecycle hook itself can't be async or wont do anything different when async, so it could stay a normal function. But I might be wrong with this

**Review by MalteJanz — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-send-document-modal/index.js (hunk 3 above)
Comment (larskemper) [reply src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-send-document-modal/index.js:122]: yes vue itself wont await in the lifecycle. I kept it this way because `createdComponent()` is async so eslint "advises" (no error) to flag it. The await is mainly for explicit promise handling consistency.
