### PR TITLE
fix: deny bulk delete of promotions if orderCount

### LINKED ISSUE #11946: Editing an order's promotion fails if its line item references a deleted promotion
### Shopware Version

6.7.1.2

### Affected area / extension

Platform(Default)

### Actual behaviour

If a promotion used in an order is later deleted, editing that order fails because the promotion_id in order_line_item still references a missing promotion.
When I tried to either remove the deleted promotion from the order or add a new promotion, I faced with:

Image

And normally you cannot delete a promotion if it has already been used in an order:

Image

but with bulk deletion ("select all" in admin) it seems the safeguard is skipped, so promotions that are linked to orders can be removed!

Image

### Expected behaviour

Bulk deletion should follow the same business rule as single deletion.

### How to reproduce

1. Create a promotion.
2. Place an order that applies this promotion.
3. Delete the promotion in the administration.
4. Open the order in the administration and try to edit its promotion.

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by mstegmeyer**
### 1. Why is this change necessary?
Promotions should not be deleteable, if they have already been used. But Bulk Delete is still possible, even if the singular delete is disabled.

### 2. What does this change do, exactly?
Toggles bulk delete when a promotion is used.

### 3. Describe each step to reproduce the issue or behaviour.
Create a promotion, use it in an order, try to delete via bulk edit.

### 4. Please link to the relevant issues (if any).
fixes #11946

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

**Review by En0Ma1259 — APPROVED** [review]

**Review by cyl3x — COMMENTED** [review]
Can't we also add a PHP fix? It's still possible via API and any future bug will still lead to deleted promotions

File: src/Core/Checkout/Promotion/DataAbstractionLayer/PromotionValidator.php [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+    {
+        $ids = $event->getDeletedPrimaryKeys(PromotionDefinition::ENTITY_NAME);
+
+        $ids = \array_column($ids, 'id');
+
+        if (empty($ids)) {
+            return;
+        }
+
+        $pluginIds = $this->connection->fetchOne(
```
Comment (cyl3x) [inline src/Core/Checkout/Promotion/DataAbstractionLayer/PromotionValidator.php]:
```suggestion
        $promotionIds = $this->connection->fetchOne(
```

**Review by cyl3x — APPROVED** [review]
