### PR TITLE
chore: Fix login

### LINKED ISSUE #12691: issue while login
### Shopware Version

trunk

### Affected area / extension

Platform(Default)

### Actual behaviour

issue while login with "executeQuery" in update context. Use "executeStatement" instead

See thread: https://shopware-ag.slack.com/archives/C05B6NYKKC2/p1758533067434309

### Expected behaviour

Login works

### How to reproduce

-

### PR DESCRIPTION
**Pull request by DennisGarding**
Closes: #12691

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

**Review by mitelg — APPROVED** [review]

File: src/Core/Framework/Sso/UserService/UserService.php [hunk 1]
```diff
@@ -110,7 +110,7 @@ public function removeExternalToken(string $userId): void
             ->where('user_id = :userId')
             ->setParameter('userId', Uuid::fromHexToBytes($userId))
             ->setParameter('token', null)
-            ->executeQuery();
+            ->executeStatement();
```
Comment (pweyck) [inline src/Core/Framework/Sso/UserService/UserService.php:113]: Using connection->update would also automatically work, because it always uses executeStatement. I don't see the benefit of using the query builder for updates tbh, if it's not a very dynamic select with optional joins etc. 

But I do wonder if we have more issues like this in shopware and how we can prevent this from happening in the future. It leads to random failures in saas (and everyone else that uses read replica)

**Review by pweyck — APPROVED** [review]

File: src/Core/Framework/Sso/UserService/UserService.php (hunk 1 above)
Comment (DennisGarding) [reply src/Core/Framework/Sso/UserService/UserService.php:113]: I have checked the login directory. There are no other issues like that
