### PR TITLE
fix: overwrite slot config

### LINKED ISSUE #11800: Can not override the products assigned into a cms slider
### Shopware Version

6.7

### Affected area / extension

Platform(Default)

### Actual behaviour

 the overrided result of assigned products in product slider is not correct

### Expected behaviour

the override result should reflect correctly

### How to reproduce

- Create a layout with product sliders and assign 5 products.

- Assign the layout for a category

Image

- Go to layout tab.

- Try to override the products of product slider to 3 products or empty (whatever)

- Press Save and verify the result

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by rittou**
### 1. Why is this change necessary?
This pull request refines how configuration arrays are merged for CMS page slots, ensuring that overrides behave correctly for both associative and indexed arrays. It introduces a custom `overrideArray` method to replace the previous merging logic and updates related unit tests to reflect the new behavior.

**Config merging improvements:**

* Replaced usage of `array_replace_recursive` with a custom `overrideArray` method in `SalesChannelCmsPageLoader.php`, ensuring that associative arrays are merged recursively and indexed arrays are fully replaced, giving more predictable override behavior.
* Added the `overrideArray` to `SalesChannelCmsPageLoader.php` to support the new merging logic.

### 2. What does this change do, exactly?

This pull request refines how CMS slot configurations are overridden in the `SalesChannelCmsPageLoader`. The main improvement is the introduction of a custom recursive array merging function that better handles the merging of associative and indexed arrays, ensuring that overrides behave as expected. The test suite has also been updated to reflect and verify the new merging behavior.

**Config merging improvements:**

* Replaced `array_replace_recursive` with a new `overrideArray` method in `SalesChannelCmsPageLoader.php`, which recursively merges associative arrays and fully replaces indexed arrays, ensuring more predictable configuration overrides.
* Added the private helper method`overrideArray` to handle the custom merging logic and distinguish between associative and indexed arrays.

### 3. Describe each step to reproduce the issue or behaviour.
[recording.webm](https://github.com/user-attachments/assets/dc6048d8-4f3c-4a44-96f1-0d39011637d9)

### 4. Please link to the relevant issues (if any).
- closes #11800 - closes the issue #11800 when the PR is merged

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [x] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Core/Content/Cms/SalesChannel/SalesChannelCmsPageLoader.php [hunk 1]
```diff
@@ -204,4 +201,41 @@ private function extractProductIds(EntityCollection $pages): array
...
+        }
+
+        return $original;
+    }
+
+    /**
+     * Determines if an array is associative (has string keys)
+     * or indexed (sequential numeric keys).
+     */
+    private function isAssoc(array $arr): bool
```
Comment (bschulzebaek) [inline src/Core/Content/Cms/SalesChannel/SalesChannelCmsPageLoader.php]: You can use `array_is_list` https://www.php.net/manual/en/function.array-is-list.php

File: src/Core/Content/Cms/SalesChannel/SalesChannelCmsPageLoader.php [hunk 2]
```diff
@@ -204,4 +201,41 @@ private function extractProductIds(EntityCollection $pages): array
...
     }
+
+    /**
+     * Recursively merges two arrays, with values from the override array taking precedence.
+     * For associative arrays, merges recursively. For indexed arrays, replaces completely.
+     */
+    private function overrideArray(array $original, array $override): array
+    {
+        foreach ($override as $key => $value) {
+            if (\array_key_exists($key, $original) && \is_array($original[$key]) && \is_array($value)) {
```
Comment (bschulzebaek) [inline src/Core/Content/Cms/SalesChannel/SalesChannelCmsPageLoader.php]:
```suggestion
                if (
                    $originalValue !== null && 
                    is_array($originalValue) && 
                    is_array($value) && 
                    !array_is_list($originalValue) && 
                    !array_is_list($value)
                ) {
                    $original[$key] = $this->overrideArray($originalValue, $value);
                } else {
                    $original[$key] = $value;
                }
            
```

The `else` statements do the same, so need need for nested ifs

**Review by ravenokko — APPROVED** [review]

File: changelog/_unreleased/2025-08-18-fix-overwrite-slot-config.md [hunk 3]
```diff
@@ -0,0 +1,7 @@
+---
+title: fix overwrite slot config
+issue: 11800
+---
+# Core
+* Replaced usage of `array_replace_recursive` with a custom `overrideArray` method in `SalesChannelCmsPageLoader.php`, ensuring that associative arrays are merged recursively and indexed arrays are fully replaced, giving more predictable override behavior.
```
Comment (marcelbrode) [inline changelog/_unreleased/2025-08-18-fix-overwrite-slot-config.md]: `Replaced` is not a valid keyword for a changelog. Please use either `Added`, `Changed`, `Removed` or `Deprecated` only in changelogs.

Also: Please do not describe the changes in the code but what the result is. A customer doesn't care if you use implementation A or B, only what it effectively means for them.

File: src/Core/Content/Cms/SalesChannel/SalesChannelCmsPageLoader.php [hunk 4]
```diff
@@ -204,4 +201,34 @@ private function extractProductIds(EntityCollection $pages): array
...
     }
+
+    /**
+     * Recursively merges two arrays, with values from the override array taking precedence.
+     * For associative arrays, merges recursively. For indexed arrays, replaces completely.
+     *
+     * @param array<string, mixed> $original
+     * @param array<string, mixed> $override
+     *
+     * @return array<string, mixed>
```
Comment (marcelbrode) [inline src/Core/Content/Cms/SalesChannel/SalesChannelCmsPageLoader.php:212]: Can you get more precise than "mixed"?

File: src/Core/Content/Cms/SalesChannel/SalesChannelCmsPageLoader.php [hunk 5]
```diff
@@ -204,4 +201,34 @@ private function extractProductIds(EntityCollection $pages): array
             ...array_map(EntityCacheKeyGenerator::buildCmsTag(...), $pages->getIds()),
         ];
     }
+
+    /**
+     * Recursively merges two arrays, with values from the override array taking precedence.
+     * For associative arrays, merges recursively. For indexed arrays, replaces completely.
```
Comment (marcelbrode) [inline src/Core/Content/Cms/SalesChannel/SalesChannelCmsPageLoader.php]:
```suggestion
     * Recursively overrides an array with values from the override array.
     * Merges recursively for associative arrays and replaces completely for index arrays.
```

**Review by marcelbrode — CHANGES_REQUESTED** [review]

File: src/Core/Content/Cms/SalesChannel/SalesChannelCmsPageLoader.php (hunk 5 above)
Comment (rittou) [reply src/Core/Content/Cms/SalesChannel/SalesChannelCmsPageLoader.php]: I have adjusted your suggestions a bit. Please take a peek at it.

File: changelog/_unreleased/2025-08-18-fix-overwrite-slot-config.md (hunk 3 above)
Comment (rittou) [reply changelog/_unreleased/2025-08-18-fix-overwrite-slot-config.md]: It's updated, please review it.

File: src/Core/Content/Cms/SalesChannel/SalesChannelCmsPageLoader.php (hunk 4 above)
Comment (rittou) [reply src/Core/Content/Cms/SalesChannel/SalesChannelCmsPageLoader.php:212]: Because the config contains various data types, I don't think we could or should specify the precise ones.

**Review by marcelbrode — APPROVED** [review]

**Comment by marcelbrode** [comment]
Guess you need to sign the CLA
