### PR TITLE
fix: theme config boolean values

### LINKED ISSUE #11766: Theme config fields of type 'bool' or 'switch' fall back to their default base_config values when disabled
### Shopware Version

6.7.1.2

### Affected area / extension

Platform(Default)

### Actual behaviour

Currently, disabled 'bool' or 'switch' fields in the theme configuration fall back to their base_config default values in SCSS when toggled off.
This leads to an issue where fields with a default value of 'true' always evaluate to 'true' during SCSS compilation, because:
'true' → 'true' and 'false' → 'null'  -> fallback to default from base_config → 'true'.

Image

### Expected behaviour

The value 'false' should be stored as a config value instead of 'null'.

### How to reproduce

1. create a config field in your theme from type 'bool' or 'switch'
2. add true as default value in your theme config
3. enable SCSS usage for the field
4. dump the value in a SCSS file (`@debug $myvalue;`)
5. Toggle the value off in your config
6. Compile the theme -> you will always get 1 (true) in your console

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by Phil23**
fixes #11766

### 1. Why is this change necessary?

Config fields with value `false` fallback to `null`. This should not be the case for boolean fields.

### 2. What does this change do, exactly?

Exclude boolean fields from falling back to `null` on falsy value in the SCSS Validator.

### 3. Describe each step to reproduce the issue or behaviour.

Create a theme config field of type `switch` or `checkbox` and try to save the theme config. The value should always be saved as a boolean value.

### CODE REVIEW

**Review by keulinho — APPROVED** [review]

**Review by tobiasberge — APPROVED** [review]

File: tests/unit/Storefront/Theme/Validator/SCSSValidatorTest.php [hunk 1]
```diff
@@ -208,6 +208,35 @@ public static function sanitizeDataProvider(): \Generator
             ],
             null,
         ];
+        // Boolean values
+        yield 'checkbox true' => [
```
Comment (mitelg) [inline tests/unit/Storefront/Theme/Validator/SCSSValidatorTest.php:212]:
```suggestion
        yield 'boolean true' => [
```

File: tests/unit/Storefront/Theme/Validator/SCSSValidatorTest.php [hunk 2]
```diff
@@ -208,6 +208,35 @@ public static function sanitizeDataProvider(): \Generator
...
+        yield 'switch true' => [
+            [
+                'type' => 'switch',
+                'value' => true,
+            ],
+            true,
+        ];
+        yield 'checkbox false' => [
+            [
+                'type' => 'boolean',
```
Comment (mitelg) [inline tests/unit/Storefront/Theme/Validator/SCSSValidatorTest.php]:
```suggestion
                'type' => 'checkbox',
```

File: tests/unit/Storefront/Theme/Validator/SCSSValidatorTest.php [hunk 3]
```diff
@@ -601,6 +630,35 @@ public static function validateDataProvider(): \Generator
             ],
             '#040404',
         ];
+        // Boolean values
+        yield 'checkbox true' => [
```
Comment (mitelg) [inline tests/unit/Storefront/Theme/Validator/SCSSValidatorTest.php:634]:
```suggestion
        yield 'boolean true' => [
```

File: tests/unit/Storefront/Theme/Validator/SCSSValidatorTest.php [hunk 4]
```diff
@@ -601,6 +630,35 @@ public static function validateDataProvider(): \Generator
...
+        yield 'switch true' => [
+            [
+                'type' => 'switch',
+                'value' => false,
+            ],
+            false,
+        ];
+        yield 'checkbox false' => [
+            [
+                'type' => 'boolean',
```
Comment (mitelg) [inline tests/unit/Storefront/Theme/Validator/SCSSValidatorTest.php]:
```suggestion
                'type' => 'checkbox',
```

**Review by SpiGAndromeda — APPROVED** [review]

File: src/Storefront/Theme/Validator/SCSSValidator.php [hunk 5]
```diff
@@ -23,7 +23,7 @@ public static function validate(AbstractScssCompiler $compiler, array $data, arr
         if (!\array_key_exists('value', $data)
             || !isset($data['value'])
             || $data['value'] === ''
-            || $data['value'] === false) {
+            || ($data['value'] === false && !in_array($data['type'], ['checkbox', 'switch', 'boolean', 'bool']))) {
```
Comment (mitelg) [inline src/Storefront/Theme/Validator/SCSSValidator.php]: would be nice if we could introduce some constants similar to `\Shopware\Core\System\CustomField\CustomFieldTypes` and also an array constant that contains all boolean. so it can be re-used in different places, without being hardcoded

**Review by mitelg — CHANGES_REQUESTED** [review]

File: src/Storefront/Theme/Validator/SCSSValidator.php (hunk 5 above)
Comment (Phil23) [reply src/Storefront/Theme/Validator/SCSSValidator.php]: I would not make it part of this fix. This could be a general refactoring of the theme config fields.

**Review by mitelg — APPROVED** [review]
