### PR TITLE
fix: correct sorted listings with product variants and different prices

### LINKED ISSUE #4053: Sorting by price does not work for variants with multiple prices
Description: If you have within a category with different prices, the sorting by price within the category does not work and variant items are not sorted correctly

Environment: 6.4.x

Steps to reproduce: Create 2 variant articles within a category.
Make one of the variant items cheaper than the other and create multiple variants for both with higher prices than the base price of the variant. Remove the inheritance of the prices of the variants for both articles. Then assign them to a category and sort them by price in this category.

Expected result: The variant items are sorted according to the lowest/display price.

Actual result: The variant articles are not sorted according to the lowest price/display price.

### PR DESCRIPTION
**Pull request by ulloe**
Fixes an issue where product variants with different prices were not correctly included in the price sorting.

targets #4053

### 1. Why is this change necessary?
See #4053 

If we have Product P1 priced at 10 EUR, and Product P2, which has variants priced at 5 EUR and 15 EUR, and we sort the listings by price (asc), P2 (displayed as "From 5 EUR") appears after P1 (10 EUR). This is not the expected behavior.

### 2. What does this change do, exactly?
It adds a MIN() function to the accessor when sorting by cheapestPrice is selected.

### 3. Describe each step to reproduce the issue or behaviour.
1. Create a product with any price.
2. Create another product.
3. Add two variants to the second product: one variant priced lower than the first product, and the other priced higher.
4. Visit a page with a listing that includes both products. Sort the listing by price in ascending order. The second product appears after the first one, even though its displayed price is lower.

### 4. Please link to the relevant issues (if any).
- closes #4053 

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [X] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [X] I have written or adjusted the documentation according to my changes
- [X] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Core/Framework/DataAbstractionLayer/Dbal/CriteriaQueryBuilder.php [hunk 1]
```diff
@@ -146,6 +146,8 @@ public function addSortings(EntityDefinition $definition, Criteria $criteria, ar
                 } else {
                     $accessor = 'MAX(' . $accessor . ')';
                 }
+            } else {
+                $accessor = 'MIN(' . $accessor . ')';
```
Comment (mitelg) [inline src/Core/Framework/DataAbstractionLayer/Dbal/CriteriaQueryBuilder.php:150]: maybe we can add this before going into the if `if (!\in_array($sorting->getField(), ['product.cheapestPrice', 'cheapestPrice'], true)) {` and then simply check for `FieldSorting::DESCENDING` where we add the `MAX()` function. 


also a test would be nice.

File: changelog/_unreleased/2025-07-11-fix-correctly-sort-product-variants-with-different-prices.md [hunk 2]
```diff
@@ -0,0 +1,15 @@
+---
+title: Adds MIN() Function to cheapestPrice Accessor
+issue: #4053
+flag:
```
Comment (mitelg) [inline changelog/_unreleased/2025-07-11-fix-correctly-sort-product-variants-with-different-prices.md]:
```suggestion
```

**Review by mitelg — CHANGES_REQUESTED** [review]

File: src/Core/Framework/DataAbstractionLayer/Dbal/CriteriaQueryBuilder.php (hunk 1 above)
Comment (ulloe) [reply src/Core/Framework/DataAbstractionLayer/Dbal/CriteriaQueryBuilder.php:150]: Please disregard this if I have misunderstood, but keep in mind: the accessor should always be `MIN()` for the `cheapestPrice` option. Even if I sort by the cheapest price descending, the cheapest price still serves as the reference.

Comment (mitelg) [reply src/Core/Framework/DataAbstractionLayer/Dbal/CriteriaQueryBuilder.php:150]:
```
$accessor = 'MIN(' . $accessor . ')';
if (!\in_array($sorting->getField(), ['product.cheapestPrice', 'cheapestPrice'], true)) {
    if ($sorting->getDirection() === FieldSorting::DESCENDING) {
        $accessor = 'MAX(' . $accessor . ')';
    }
}
```

this is what I meant :blush: does it make sense for you?

Comment (ulloe) [reply src/Core/Framework/DataAbstractionLayer/Dbal/CriteriaQueryBuilder.php:150]: No it does not, I'm sorry. 🙃 
Keep in mind, that we concatenate the `$accessor` . Your suggestion can cause `SQLSTATE[HY000]: General error: 1111 Invalid use of group function` errors. There are cases in which we end up with an `MAX(MIN( $accessor ))` accessor.

I'd stick to the `if / else` solution or maybe use something like:

```php
if (\in_array($sorting->getField(), ['product.cheapestPrice', 'cheapestPrice'], true)) {
    $accessor = 'MIN(' . $accessor . ')';
} else if ($sorting->getDirection() === FieldSorting::DESCENDING) {
    $accessor = 'MAX(' . $accessor . ')';
} else {
    $accessor = 'MIN(' . $accessor . ')';
}
```

Comment (mitelg) [reply src/Core/Framework/DataAbstractionLayer/Dbal/CriteriaQueryBuilder.php:150]: oh right :man_facepalming: would work with renaming the variable :grin: but okay, your solution works

Comment (mitelg) [inline src/Core/Framework/DataAbstractionLayer/Dbal/CriteriaQueryBuilder.php:150]: but we still would need a test for this

Comment (ulloe) [reply src/Core/Framework/DataAbstractionLayer/Dbal/CriteriaQueryBuilder.php:150]: I have created and committed a test. However, please keep in mind that the test _may_ also pass without the fix. As described in Issue #4053 and the [MySQL documentation](https://dev.mysql.com/doc/refman/8.4/en/group-by-handling.html#:~:text=unless%20they%20are%20the%20same%2C%20the%20values%20chosen%20are%20nondeterministic%2C%20which%20is%20probably%20not%20what%20you%20want.). The result of the final SQL query is not deterministic in this case.

File: tests/integration/Core/Framework/DataAbstractionLayer/Dbal/CriteriaQueryBuilderTest.php [hunk 3]
```diff
@@ -0,0 +1,98 @@
...
+{
+    use IntegrationTestBehaviour;
+    private const VALID_TEST_SET = [
+        's1' => '0198bd43b1c37964a5c1ecbd2d89fd6e',
+        'p1' => '0198bd4417f471a69742ca2390243653',
+        'p1.1' => '0198bd446e0973448206e3197b2d24ea',
+        'p1.2' => '0198bd446e077084984f95175b2bea27',
+    ];
+
+    private const INVALID_TEST_SET = [
```
Comment (mitelg) [inline tests/integration/Core/Framework/DataAbstractionLayer/Dbal/CriteriaQueryBuilderTest.php]: this is unused.

File: tests/integration/Core/Framework/DataAbstractionLayer/Dbal/CriteriaQueryBuilderTest.php [hunk 4]
```diff
@@ -0,0 +1,98 @@
...
+use Shopware\Core\Test\TestDefaults;
+use Symfony\Component\HttpFoundation\Request;
+
+/**
+ * @internal
+ */
+class CriteriaQueryBuilderTest extends TestCase
+{
+    use IntegrationTestBehaviour;
+    private const VALID_TEST_SET = [
```
Comment (mitelg) [inline tests/integration/Core/Framework/DataAbstractionLayer/Dbal/CriteriaQueryBuilderTest.php]: why putting them into a private constant at all?

File: tests/integration/Core/Framework/DataAbstractionLayer/Dbal/CriteriaQueryBuilderTest.php [hunk 5]
```diff
@@ -0,0 +1,98 @@
...
+    private const INVALID_TEST_SET = [
+        's1' => '00000000000000000000000000000001',
+        'p1' => '00000000000000000000000000000002',
+        'p1.1' => '00000000000000000000000000000003',
+        'p1.2' => '00000000000000000000000000000004',
+    ];
+
+    public IdsCollection $ids;
+
+    public function testSortingByCheapestPrice(): void
```
Comment (mitelg) [inline tests/integration/Core/Framework/DataAbstractionLayer/Dbal/CriteriaQueryBuilderTest.php:47]: wouldn't it be possible to recreate the situation described in the issue?

File: tests/integration/Core/Framework/DataAbstractionLayer/Dbal/CriteriaQueryBuilderTest.php (hunk 3 above)
Comment (ulloe) [reply tests/integration/Core/Framework/DataAbstractionLayer/Dbal/CriteriaQueryBuilderTest.php]: I wanted to keep a set of IDs that does not produce the expected behavior due to MySQL's non-deterministic results when `ONLY_FULL_GROUP_BY` is disabled. I've now moved that ID set into the comment for clarity, since it's not used in the actual test. 
I'd like to add to this comment, if that's okay with you.

```php
/**
 * This test checks listing sorting behavior affected by MySQL's GROUP BY handling.
 *
 * Shopware disables ONLY_FULL_GROUP_BY, allowing queries that may return non-deterministic
 * results when selecting columns not functionally dependent on the GROUP BY clause.
 * See: https://dev.mysql.com/doc/refman/8.4/en/group-by-handling.html
 *
 * The CriteriaQueryBuilder generates such a query. Without the fix, results may vary between
 * runs; with the fix, the outcome is deterministic and the test should always pass.
 *
 * A specific ID set is used to reproduce the issue. For reference, the following ID set
 * does NOT trigger the problem and is noted here for completeness:
 * ['s1' => '00000000000000000000000000000001',
 *  'p1' => '00000000000000000000000000000002',
 *  'p1.1' => '00000000000000000000000000000003',
 *  'p1.2' => '00000000000000000000000000000004']
 *
 * Changing the data may prevent the issue from appearing, so edit with caution.
 */
```

File: tests/integration/Core/Framework/DataAbstractionLayer/Dbal/CriteriaQueryBuilderTest.php (hunk 4 above)
Comment (ulloe) [reply tests/integration/Core/Framework/DataAbstractionLayer/Dbal/CriteriaQueryBuilderTest.php]: From my perspective, there's no real need to keep these IDs in a private constant. I'm happy to remove it. I'll include everything in the next commit.

File: tests/integration/Core/Framework/DataAbstractionLayer/Dbal/CriteriaQueryBuilderTest.php (hunk 5 above)
Comment (ulloe) [reply tests/integration/Core/Framework/DataAbstractionLayer/Dbal/CriteriaQueryBuilderTest.php:47]: I'm not entirely sure what’s being asked here. I _did_ recreate the situation described in the original issue - that’s what this test is based on.
If the question is about reproducing the issue with two articles and their variants, then yes, I can easily add that setup.
However, if the concern is about making the test consistently fail without the fix, that’s unfortunately not possible. The non-deterministic nature of the results (due to MySQL’s internal behavior and the lack of `ONLY_FULL_GROUP_BY`) makes that inherently unreliable without the fix in place.

Comment (mitelg) [reply tests/integration/Core/Framework/DataAbstractionLayer/Dbal/CriteriaQueryBuilderTest.php:47]: okay, I understand :+1:

**Review by mitelg — APPROVED** [review]

**Review by nguyenytran — APPROVED** [review]

**Review by keulinho — APPROVED** [review]

**Comment by mitelg** [comment]
thanks for your contribution @ulloe 👍🎉💙
