### PR TITLE
fix: Fix SwTwigFunction memory leak in long-running environments

### LINKED ISSUE #14457: Fixing the SwTwigFunction memory leak
### Technical TODO

the methods in `SwTwigFunction` are vulnerable to memory leaks in long running envs. 
This needs to be fixed by removing the `static $strings` property with a proper class property. As the properties and methods are all static, we would need another service, that resets the properties.

### PR DESCRIPTION
**Pull request by mateuszfl**
## 1. Why is this change necessary?

`SwTwigFunction` stores static references to function instances in `self::$functions` array. In traditional PHP-FPM, this is cleared when the process ends. However, in long-running PHP environments (FrankenPHP worker mode, RoadRunner, Swoole), these static references accumulate across requests, causing a memory leak.

## 2. What does this change do, exactly?

**New files:**
- `SwTwigFunctionResetter` - A resetter service that clears `SwTwigFunction::$functions` on kernel reset

**Modified files:**
- `SwTwigFunction` - Add `resetInstances()` static method to clear the functions array
- `services.xml` - Register `SwTwigFunctionResetter` with `kernel.reset` tag

**How it works:**
1. Symfony's `kernel.reset` event is triggered between requests in long-running environments
2. `SwTwigFunctionResetter::reset()` is called
3. It calls `SwTwigFunction::resetInstances()` to clear static references
4. Memory is freed, preventing accumulation across requests

## 3. Describe each step to reproduce the issue or behaviour.

**Before fix:**
1. Start FrankenPHP in worker mode
2. Make 1000 requests to a page using Twig functions
3. Monitor memory usage with `memory_get_usage()`
4. Memory grows continuously

**After fix:**
1. Same setup
2. Same requests
3. Memory stays stable (reset between requests)

## 4. Please link to the relevant issues (if any).

closes #14457

## 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have squashed related commits into one, where suitable
- [ ] I have updated developer-facing release notes if this change is relevant
- [ ] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: tests/unit/Core/Framework/Adapter/Twig/SwTwigFunctionResetterTest.php [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+        $resetter = new SwTwigFunctionResetter();
+        $resetter->reset();
+
+        // After reset, cache should be cleared
+        SwTwigFunction::escapeFilter($env, 'resetter_test_string', 'html', 'UTF-8');
+        // @phpstan-ignore staticMethod.impossibleType (PHPStan doesn't track reference through callback)
+        static::assertSame(2, $runtimeCallCount, 'After resetter->reset(), cache should be cleared');
+    }
+
+    public function testResetterImplementsResetInterface(): void
```
Comment (mitelg) [inline tests/unit/Core/Framework/Adapter/Twig/SwTwigFunctionResetterTest.php]: I don't think this is necessary

**Review by mitelg — APPROVED** [review]

**Review by BrocksiNet — APPROVED** [review]

File: src/Core/Framework/DependencyInjection/services.xml [hunk 2]
```diff
@@ -360,6 +360,10 @@ frame-ancestors 'none';
             <tag name="kernel.reset" method="reset"/>
         </service>
 
+        <service id="Shopware\Core\Framework\Adapter\Twig\SwTwigFunctionResetter">
+            <tag name="kernel.reset" method="reset"/>
+        </service>
```
[the remark this answers is not in the document]
Comment (mitelg) [reply src/Core/Framework/DependencyInjection/services.xml]: it seems to be right. I checked with my recently introduced `\Shopware\Core\Framework\Util\Database\TableHelperResetter` and it got removed from the container. 
marking it as public should help

**Review by mitelg — CHANGES_REQUESTED** [review]

**Review by mitelg — APPROVED** [review]

File: tests/unit/Core/Framework/Adapter/Twig/SwTwigFunctionResetterTest.php [hunk 3]
```diff
@@ -0,0 +1,63 @@
...
+        // Call resetter
+        $resetter = new SwTwigFunctionResetter();
+        $resetter->reset();
+
+        // After reset, cache should be cleared
+        SwTwigFunction::escapeFilter($env, 'resetter_test_string', 'html', 'UTF-8');
+        // @phpstan-ignore staticMethod.impossibleType (PHPStan doesn't track reference through callback)
+        static::assertSame(2, $runtimeCallCount, 'After resetter->reset(), cache should be cleared');
+    }
+
```
Comment (mitelg) [inline tests/unit/Core/Framework/Adapter/Twig/SwTwigFunctionResetterTest.php]:
```suggestion
```

**Comment by mitelg** [comment]
thanks for your contribution @mateuszfl 👍🎉💙
