### PR TITLE
fix: matching of flow scope rules in promotions

### LINKED ISSUE #6587: Rule ‘Order created by administrator’ does not work
As soon as you add the rule ‘Order created by administrator’ to a discount, for example, in order to be able to redeem it only for orders that were created via the admin, the rule does not apply and the discount code cannot be added because the rule is supposedly not fulfilled.

### PR DESCRIPTION
**Pull request by larskemper**
### 1. Why is this change necessary?

When submitting a promotion code to an order in the past, all rules were executed using `CartScopeRule`. This led to incorrect evaluations for rules utilizing `FlowScopeRule`, as they check the scope immediately and always return false.

Additionally, I noticed missing error and info messages in the administration, which were caused by cart incomplete data translation within the Cart processor. I created a ticket for that bug: https://shopware.atlassian.net/browse/NEXT-40798

Lastly, I refactored the admin component responsible for adding promotions to an order.

### 2. What does this change do, exactly?

I added rule-awareness configurations for order- and cart promotions. So that the flow/order conditions are not assignable anymore for promotions.

### 4. Please link to the relevant issues (if any).

- closes #6587
- jira: https://shopware.atlassian.net/browse/NEXT-40565

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfill them.

### CODE REVIEW

File: src/Core/Checkout/Promotion/Cart/PromotionCalculator.php [hunk 1]
```diff
@@ -368,19 +380,105 @@ private function limitDiscountResult(float $maxDiscountValue, PriceCollection $p
...
+    private function fetchOrder(Context $context, Cart $cart): ?OrderEntity
+    {
+        $orderIdStruct = $cart->getExtensions()[OrderConverter::ORIGINAL_ID] ?? null;
+
+        if (!($orderIdStruct instanceof IdStruct)) {
+            return null;
+        }
+
+        $criteria = new Criteria();
+        $criteria->addFilter(new EqualsFilter('id', $orderIdStruct->getId()));
```
Comment (cyl3x) [inline src/Core/Checkout/Promotion/Cart/PromotionCalculator.php]:
```suggestion
        $criteria = new Criteria([$orderIdStruct->getId()]);
```

File: src/Core/Checkout/Promotion/Cart/PromotionCalculator.php [hunk 2]
```diff
@@ -368,19 +380,105 @@ private function limitDiscountResult(float $maxDiscountValue, PriceCollection $p
...
+
+        return false;
+    }
+
+    /**
+     * Flattens the nested rules in the given container.
+     *
+     * @return Rule[]
+     */
+    private function flattenRule(Container $container): array
```
Comment (cyl3x) [inline src/Core/Checkout/Promotion/Cart/PromotionCalculator.php]: if this function does not have any other use case besides `hasFlowRuleScope` I would prefer making `hasFlowRuleScope` recursive:
 ```php
private function hasFlowRuleScope(...$rules): bool
{
    foreach ($rules as $item) {
        if ($item instanceof FlowRule) {
            return true;
        } else if ($item instanceof Container) {
            return $this->hasFlowRuleScope(...$item->getRules());
        }
    }
    
    return false;
}
```

**Comment by jozsefdamokos** [comment]
This feels weird. Building a flow rule scope in the checkout scope. We want to keep these domains separate. Maybe the rule evaluation is correct as is. It's not weird that a rule that is intended to work in the flow scope does not evaluate the same way in the checkout scope. I would suggest changing the scope of the rule if that is possible.

**Comment by larskemper** [comment]
> This feels weird. Building a flow rule scope in the checkout scope. We want to keep these domains separate. Maybe the rule evaluation is correct as is. It's not weird that a rule that is intended to work in the flow scope does not evaluate the same way in the checkout scope. I would suggest changing the scope of the rule if that is possible.

It's not possible because the rule evaluation depends on order data, just like any other FlowRule.

This issue isn't limited to a single rule, any rule extending FlowRule and requiring FlowRuleScope will always evaluate as false when used in a promotion, cause there are checking the scope right away (see: [link](https://github.com/shopware/shopware/blob/trunk/src/Core/Content/Flow/Rule/OrderCreatedByAdminRule.php#L26)). So, it's not just behaving "differently" but incorrectly.

The only alternative would be to disable all FlowRules for promotions (and any other not "flow" purpose) in some way.

File: src/Core/Checkout/Promotion/Cart/PromotionCalculator.php [hunk 3]
```diff
@@ -368,19 +380,105 @@ private function limitDiscountResult(float $maxDiscountValue, PriceCollection $p
...
+        $orderIdStruct = $cart->getExtensions()[OrderConverter::ORIGINAL_ID] ?? null;
+
+        if (!($orderIdStruct instanceof IdStruct)) {
+            return null;
+        }
+
+        $criteria = new Criteria();
+        $criteria->addFilter(new EqualsFilter('id', $orderIdStruct->getId()));
+
+        /** @var OrderEntity|null $order */
```
Comment (mitelg) [inline src/Core/Checkout/Promotion/Cart/PromotionCalculator.php]: if you annotate the EntityRepository property correctly, you can omit this var annotation

**Comment by mstegmeyer** [comment]
Couldn't this also happen not only with adding promotions but also when adding a LineItem or any other recalculation? I don't understand why this behavior is placed specifically in the PromotionCalculator.

File: tests/unit/Core/Checkout/Cart/Promotion/Cart/PromotionCalculatorTest.php [hunk 4]
```diff
@@ -52,8 +77,208 @@ protected function setUp(): void
...
+            $this->createMock(SalesChannelContext::class),
+            new CartBehavior()
+        );
+
+        static::assertCount(0, $cart->getErrors());
+    }
+
+    public function testBuildScopeWithRootFlowRule(): void
+    {
+        /** @phpstan-ignore shopware.mockingSimpleObjects */
```
Comment (mitelg) [inline tests/unit/Core/Checkout/Cart/Promotion/Cart/PromotionCalculatorTest.php]: there is a reason why we have this PHPStan rule :slightly_smiling_face: why can't you create it directly?

Comment (larskemper) [reply tests/unit/Core/Checkout/Cart/Promotion/Cart/PromotionCalculatorTest.php]: I like the rule, but underneath it, I use the mock to verify whether the method is called, how often, and with which arguments. If there's another way to achieve this, I'd appreciate any tips!

Comment (mitelg) [reply tests/unit/Core/Checkout/Cart/Promotion/Cart/PromotionCalculatorTest.php]: I would assume, that at least the tests, where you only check for `once` could be refactored to directly use the rule class :thinking:

Comment (larskemper) [reply tests/unit/Core/Checkout/Cart/Promotion/Cart/PromotionCalculatorTest.php]: If it were only about checking the call count, I would agree. However, the most important aspect of this test is the rule scope with which the match method is called, and I verify that using the mock...

Comment (mitelg) [reply tests/unit/Core/Checkout/Cart/Promotion/Cart/PromotionCalculatorTest.php]: ah okay. if that is important, then it is okay :+1:

**Comment by larskemper** [comment]
> Couldn't this also happen not only with adding promotions but also when adding a LineItem or any other recalculation? I don't understand why this behavior is placed specifically in the PromotionCalculator.

What do you mean exactly? When a recalculation is triggered, the cart Processor also calls the PromotionCalculator through the PromotionProcessor. Promotions rely on rules, which is why this error occurs

File: src/Core/Checkout/Promotion/Cart/PromotionCalculator.php [hunk 5]
```diff
@@ -368,19 +382,81 @@ private function limitDiscountResult(float $maxDiscountValue, PriceCollection $p
...
+
+        return false;
+    }
+
+    /**
+     * fetches the order entity from the cart
+     */
+    private function fetchOrder(Context $context, Cart $cart): ?OrderEntity
+    {
+        $orderIdStruct = $cart->getExtensions()[OrderConverter::ORIGINAL_ID] ?? null;
```
Comment (mstegmeyer) [inline src/Core/Checkout/Promotion/Cart/PromotionCalculator.php]: there is an `getExtensionOfType` method, with which you can save the type check

File: src/Core/Checkout/Promotion/Cart/PromotionCalculator.php [hunk 6]
```diff
@@ -368,19 +382,81 @@ private function limitDiscountResult(float $maxDiscountValue, PriceCollection $p
...
+
+        if (!($orderIdStruct instanceof IdStruct)) {
+            return null;
+        }
+
+        $criteria = new Criteria([$orderIdStruct->getId()]);
+
+        return $this->orderRepository->search($criteria, $context)->first();
```
Comment (mstegmeyer) [inline src/Core/Checkout/Promotion/Cart/PromotionCalculator.php]: You're not loading any associations here, but normally, for executing flows, there are loads of associations being loaded (`Shopware\Core\Content\Flow\Dispatching\Storer\OrderStorer::loadOrder`).

I looked up the rules working with the `FlowRuleScope`, and they are depending on several associations, such as `transactions`, `deliveries` and `documents`.
So you probably need to add them here. But: This sounds completely horrible for performance. So another required step would be to cache the order somewhere.

At some point, I wonder, if it is just easier to drop a hint in the promotion configuration in the Admin, that those kind of rules aren't evaluated here. I mean, if someone creating an order in the administration wants to give someone a discount, just do it there instead of adding a promotion.

**Review by mstegmeyer — DISMISSED** [review]
For my previous comment:
I did not look close enough and assumed, that the PromotionCalculator would just look into the SalesChannelContext for which rules are active and not do its own matching. Because I would have expected this logic in the `CartRuleLoader`, which calls `Shopware\Core\Content\Rule\RuleCollection::filterMatchingRules`, so that when we're editing an order, the Flow-based rules would be in the SalesChannelContext together with the OrderRules.
That's why I thought, I would expect the rule "created by admin" to match everywhere in a cart, not just when evaluating promotions.
But since the PromotionCalculator does this "lazy-evaluating" of rules, we can also evaluate it here manually.

**Comment by larskemper** [comment]
FYI: After discussing within the team, we made the following decisions:
- <s>Explore a workaround that avoids fetching the order (e.g., passing it through the checkout process).</s>
- Deprecate `FlowScopeRule` / `FlowRule` and replace them with `OrderScopeRule` / `OrderRule` for better clarity in the future.
- Assess the possibility of restricting the use of flow condition rules within promotions using rule awareness.

**Review by cyl3x — APPROVED** [review]

**Review by ennasus4sun — APPROVED** [review]

**Review by mstegmeyer — APPROVED** [review]
