### PR TITLE
fix: fixed updating of order_count in promotions table

### LINKED ISSUE #7453: Promotion Discounts used in orders cannot be edited/deleted
-If you have an existing promotion, and you- [-migrate from 6.6 to 6.7-|https://shopware.atlassian.net/wiki/spaces/CORE/pages/19743014995/Web+Installer+for+Unreleased+Versions]-, all functionality under the Discount tab will be greyed out and cannot be edited.  New promotions added after the migration have no issues.-

Promotions cannot be edited or deleted once they are applied to a successfully submitted order (see linked PR in comments)

### PR DESCRIPTION
**Pull request by Bird87ZA**
### 1. Why is this change necessary?
There was no explanation why a promotion could not be deleted

### 2. What does this change do, exactly?
Fixes an issue where promotions can be deleted when they are used. Also adds a tooltip to the delete button if it's disabled.

### 3. Describe each step to reproduce the issue or behaviour.
create new promotion
redeem promotion in order
delete promotion

You should not be able to delete promotion

### 4. Please link to the relevant issues (if any).
Fixes #7453

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfill them.

### CODE REVIEW

File: src/Core/Checkout/Promotion/DataAbstractionLayer/PromotionRedemptionUpdater.php [hunk 1]
```diff
@@ -104,23 +119,31 @@ public function update(array $ids, Context $context): void
...
+            $criteria = new Criteria($event->getIds());
+            $criteria->addAssociations(['lineItems', 'orderCustomer']);
+
+            $order = $this->orderRepository->search($criteria, $event->getContext())->getEntities()->first();
+            $promotions = $order->getLineItems()->filterByType(PromotionProcessor::LINE_ITEM_TYPE);
+            $customer = $order->getOrderCustomer();
+        } else {
+            $promotions = $event->getOrder()->getLineItems()->filterByType(PromotionProcessor::LINE_ITEM_TYPE);
+            $customer = $event->getOrder()->getOrderCustomer();
+        }
```
Comment (mstegmeyer) [inline src/Core/Checkout/Promotion/DataAbstractionLayer/PromotionRedemptionUpdater.php]: can't you do two different methods calling one private one afterwards? Would look cleaner and make the method shorter

File: src/Administration/Resources/app/administration/src/module/sw-promotion-v2/page/sw-promotion-v2-list/sw-promotion-v2-list.html.twig [hunk 2]
```diff
@@ -129,8 +130,9 @@
                 <template #delete-action="{ item, showDelete }">
                     <sw-context-menu-item
                         variant="danger"
+                        v-tooltip="deleteDisabledTooltip(item)"
                         :disabled="(item && item.orderCount > 0) || !acl.can('promotion.deleter') || undefined"
-                        @click="showDelete(item.id)"
+                        @click="onDelete(item)"
```
Comment (cyl3x) [inline src/Administration/Resources/app/administration/src/module/sw-promotion-v2/page/sw-promotion-v2-list/sw-promotion-v2-list.html.twig]: this is an `sw-context-menu-item` problem, it shouldn't emit click if it's disabled. Please do a proper fix in that component

**Review by cyl3x — CHANGES_REQUESTED** [review]

File: src/Core/Checkout/Promotion/DataAbstractionLayer/PromotionRedemptionUpdater.php [hunk 3]
```diff
@@ -329,4 +354,26 @@ private function getAllCustomerCounts(array $promotionIds): array
...
+     * @return array<string, int>
+     */
+    private function fetchPromotionCounts(array $promotionIds): array
+    {
+        $criteria = new Criteria();
+        $criteria->addFilter(new EqualsFilter('versionId', Defaults::LIVE_VERSION));
+        $criteria->addFilter(new EqualsFilter('type', PromotionProcessor::LINE_ITEM_TYPE));
+        $criteria->addFilter(new EqualsAnyFilter('promotionId', $promotionIds));
+
+        $lineItems = $this->lineItemRepository->search($criteria, Context::createDefaultContext())->getEntities();
```
Comment (mstegmeyer) [inline src/Core/Checkout/Promotion/DataAbstractionLayer/PromotionRedemptionUpdater.php]: it seems highly inefficient to do this query via the DAL with hydrating objects here. I would vote for a simple SQL query with `COUNT()` and `GROUP BY promotion_id`.

File: src/Administration/Resources/app/administration/src/module/sw-promotion-v2/page/sw-promotion-v2-list/sw-promotion-v2-list.html.twig (hunk 2 above)
Comment (Bird87ZA) [reply src/Administration/Resources/app/administration/src/module/sw-promotion-v2/page/sw-promotion-v2-list/sw-promotion-v2-list.html.twig]: this is going to reverted because of this: https://github.com/shopware/shopware/pull/7490

**Review by mstegmeyer — CHANGES_REQUESTED** [review]

File: src/Core/Checkout/Promotion/DataAbstractionLayer/PromotionRedemptionUpdater.php [hunk 4]
```diff
@@ -104,54 +114,20 @@ public function update(array $ids, Context $context): void
...
-    public function orderPlaced(CheckoutOrderPlacedEvent $event): void
+    public function orderUpdated(EntityWrittenEvent $event): void
     {
-        $lineItems = $event->getOrder()->getLineItems();
-        $customer = $event->getOrder()->getOrderCustomer();
-
-        if (!$lineItems || !$customer) {
+        if ($event->getEntityName() !== OrderDefinition::ENTITY_NAME) {
             return;
         }
```
Comment (cyl3x) [inline src/Core/Checkout/Promotion/DataAbstractionLayer/PromotionRedemptionUpdater.php:122]: We shouldn't do this only on live versions, right?
```suggestion
if ($event->getContext()->getVersionId() !== Defaults::LIVE_VERSION) {
    continue;
}
```

**Review by cyl3x — APPROVED** [review]

File: src/Core/Checkout/Promotion/DataAbstractionLayer/PromotionRedemptionUpdater.php (hunk 4 above)
Comment (mstegmeyer) [reply src/Core/Checkout/Promotion/DataAbstractionLayer/PromotionRedemptionUpdater.php:122]: your English is really wrong here and contradictory to your code suggestion 😉

**Review by mstegmeyer — APPROVED** [review]
