### PR TITLE
fix: product cloning variant listing config is delete on original product

### LINKED ISSUE #10944: Product cloning: VariantListingConfig is changed/deleted on original product
### Shopware Version

6.6.10.1

### Affected area / extension

Platform(Default)

### Actual behaviour

`variantListingConfig` of the **original (source) product** is changed when cloning it, for example it loses its configured `mainVariantId`. 
This has been adressed in closed PR https://github.com/shopware/shopware/pull/3821, (maybe a little hidden among other changes, probably why it was not approved)

Critical Issue, since it would corrupt existing product data when using the ("Duplicate product") feature in the Administratioin

### Expected behaviour

Leave the original source products variantListingConfig intact when cloning products

### How to reproduce

Any product with a set `MainVariantId`.
Save and duplicate it.
Look again at the original product 
-> it's `MainVariantId` is deleted

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by nguyenquocdaile**

### CODE REVIEW

File: src/Administration/Resources/app/administration/src/module/sw-product/component/sw-product-clone-modal/index.js [hunk 1]
```diff
@@ -58,7 +58,8 @@ export default {
         },
 
         async cloneParent(number) {
-            const variantListingConfigOverwrite = this.product.variantListingConfig;
+            // Create shallow copy to prevent changing the original product
+            const variantListingConfigOverwrite = { ...this.product.variantListingConfig };
```
Comment (nguyenytran) [inline src/Administration/Resources/app/administration/src/module/sw-product/component/sw-product-clone-modal/index.js]:
```suggestion
            const variantListingConfigOverwrite = cloneDeep(this.product.variantListingConfig);
```

File: src/Administration/Resources/app/administration/src/module/sw-product/component/sw-product-clone-modal/sw-product-clone-modal.spec.js [hunk 2]
```diff
@@ -80,4 +80,27 @@ describe('src/module/sw-product/component/sw-product-clone-modal', () => {
...
+                mainVariantId: '1a2b3c',
+            },
+            childCount: 1,
+        };
+
+        await wrapper.setProps({
+            product: product,
+        });
+
+        await wrapper.vm.cloneParent({
```
Comment (nguyenytran) [inline src/Administration/Resources/app/administration/src/module/sw-product/component/sw-product-clone-modal/sw-product-clone-modal.spec.js]: no need for this, as it is already called when create the component

**Review by vienthuong — APPROVED** [review]

**Review by nguyenytran — APPROVED** [review]
