### PR TITLE
fix: get correct store select id for bulk edit modal

### LINKED ISSUE #9870: Bulk edit product variant doesn't work
### Shopware Version

6.7

### Affected area / extension

Platform(Default)

### Actual behaviour

https://github.com/user-attachments/assets/0d322462-df1b-4d3e-b2c5-a93137f9eac4

### Expected behaviour

Can bulk edit variant 

### How to reproduce

Select variants in the product, then use the bulk edit feature.

### PR DESCRIPTION
**Pull request by nguyenquocdaile**
Miss a fix for bulk edit modal from this [PR](https://github.com/shopware/shopware/pull/8030)

### CODE REVIEW

**Review by vienthuong — APPROVED** [review]

**Review by sydinh — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/app/component/entity/sw-bulk-edit-modal/index.js [hunk 1]
```diff
@@ -96,7 +96,7 @@ export default {
             this.$emit('modal-close');
 
             if (this.itemCount > 0) {
-                Shopware.Store.get('shopwareApps').selectedIds = Object.keys(this.bulkEditSelection);
+                Shopware.Store.get('swBulkEdit').selectedIds = Object.keys(this.bulkEditSelection);
```
Comment (nguyenytran) [inline src/Administration/Resources/app/administration/src/app/component/entity/sw-bulk-edit-modal/index.js:100]:
```suggestion
                Shopware.Store.get('shopwareApps').selectedIds = Object.keys(this.bulkEditSelection);
                Shopware.Store.get('swBulkEdit').selectedIds = Object.keys(this.bulkEditSelection);
```
