### PR TITLE
fix: Improve error handling and validation in plugin:create command

### LINKED ISSUE #13583: Infinite Loop in plugin:create Command with -n Option
### Shopware Version

6.7

### Affected area / extension

Platform(Default)

### Actual behaviour

The plugin:create command enters an infinite loop when executed with the -n (no-interaction) option and not all required arguments are provided.

### Expected behaviour

The command should terminate with a clear error message indicating that the plugin-namespace argument is required when using non-interactive mode.

### How to reproduce

Execute the command with -n option but without the plugin-namespace argument:

bash   bin/console plugin:create TestPlugin -n

The command repeatedly displays the error message "Answer cannot be empty"
The command does not terminate and must be manually aborted (Ctrl+C)

Problem:
```
private function askPascalCaseString(string $question, SymfonyStyle $io): string
{
    $answer = $io->ask($question);

    if (empty($answer)) {
        $io->error('Answer cannot be empty');
        return $this->askPascalCaseString($question, $io); // Infinite loop
    }
    // ...
}
```

Possible solution in askPascalCaseString():
```
if (!$namespace) {
    if (!$input->isInteractive()) {
        throw new \RuntimeException(
            'Plugin namespace is required. Please provide it as argument or run without -n option.'
        );
    }
    
    $namespace = $this->askPascalCaseString('Please enter a plugin namespace (PascalCase)', $io);
}
```

### PR DESCRIPTION
**Pull request by umutdogan4291**
### 1. Why is this change necessary?
Running the command in non-interactive mode without required arguments causes an infinite loop instead of failing with an error.

### 2. What does this change do, exactly?
It validates required arguments in non-interactive mode and exits with a clear error message if any are missing.

### 3. Describe each step to reproduce the issue or behaviour.
Run `bin/console plugin:create TestPlugin -n`
The command repeatedly shows “Answer cannot be empty”.

### 4. Please link to the relevant issues (if any).
https://github.com/shopware/shopware/issues/13583

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [ ] I have updated developer-facing release notes if this change is **relevant** for external developers:
  - Add a short entry to `RELEASE_INFO-6.<major>.md` under “Upcoming” for informational changes, including the consequences of the change and how it affects external developers.
  - Add an `UPGRADE` section in `UPGRADE-6.<next-major>.md` for breaking changes (what/why/impact/how to adapt).
  - See the [Documenting a Release Process](https://github.com/shopware/shopware/blob/trunk/delivery-process/documenting-a-release.md) for details.
- [ ] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Core/Framework/Plugin/Exception/InvalidPluginCreationInputException.php [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+declare(strict_types=1);
+
+namespace Shopware\Core\Framework\Plugin\Exception;
+
+use Shopware\Core\Framework\Log\Package;
+use Shopware\Core\Framework\Plugin\PluginException;
+use Symfony\Component\HttpFoundation\Response;
+
+#[Package('framework')]
+class InvalidPluginCreationInputException extends PluginException
```
Comment (mitelg) [inline src/Core/Framework/Plugin/Exception/InvalidPluginCreationInputException.php]: we only create new specific exception classes, if we need to catch them ourselves specifically in the code. so this can simply be moved into the static method of the PluginException

File: tests/unit/Core/Framework/Plugin/Command/PluginCreateCommandTest.php [hunk 2]
```diff
@@ -134,6 +134,12 @@ public static function invalidInputsProvider(): \Generator
             'inputs' => ['test'],
             'expectedErrorMessage' => 'The name must start with an uppercase character',
         ];
+
+        yield 'non-interactive without arguments' => [
```
Comment (mitelg) [inline tests/unit/Core/Framework/Plugin/Command/PluginCreateCommandTest.php:138]: we should also test the happy case, right?

**Review by mitelg — CHANGES_REQUESTED** [review]

File: tests/unit/Core/Framework/Plugin/Command/PluginCreateCommandTest.php (hunk 2 above)
Comment (umutdogan4291) [reply tests/unit/Core/Framework/Plugin/Command/PluginCreateCommandTest.php:138]: There was already a test so I didn't want to add a new one. It still covers the happy case. Maybe the name is misleading because one scenario has no arguments but inputs.

"testSuccessfulCreateCommandWithArguments"

yield 'with inputs' => [
    'arguments' => [],
    'inputs' => [
        'TestPlugin',
        'Test',
    ],
];

I can rename it to "testSuccessfulCreateCommandWithArgumentsOrInputs"

Comment (mitelg) [reply tests/unit/Core/Framework/Plugin/Command/PluginCreateCommandTest.php:138]: ah sorry, the issue was about missing input/arguments :facepalm:

**Review by mitelg — APPROVED** [review]

**Review by shyim — APPROVED** [review]
