### PR TITLE
fix: import export profile search by technical name

### LINKED ISSUE #13073: Search for import export profile - finds nothing on searching for technical name
### Shopware Version

6.7.3.0

### Affected area / extension

Platform(Default)

### Actual behaviour

# In admin at the import / export I search for "product"
# Nothing is found -> because it searches for the translated field "label", and not for the technical name.#
# In admin with 6.7 we only see the technical name, and not the label anymore. So the customer can not find what he see in admin.

### Expected behaviour

# When I search for "product", I want to see all import / export profiles with technical name includes "product"

### How to reproduce

# Make an admin user with langauge German
# Search for "product" inside the import / export profiles -> Nothing will be found

### PR DESCRIPTION
**Pull request by jozsefdamokos**
- added search-ability for technical name in entity definition

fixes: [#13073](https://github.com/shopware/shopware/issues/13073)

### CODE REVIEW

File: src/Administration/Resources/app/administration/src/module/sw-import-export/view/sw-import-export-view-profiles/index.js
Comment (vintagesucks) [inline src/Administration/Resources/app/administration/src/module/sw-import-export/view/sw-import-export-view-profiles/index.js:1]: We should also check the profile select fields in the import and export tabs, as it seems that filtering by technical name is missing there, too.

**Review by vintagesucks — APPROVED** [review]

**Review by larskemper — APPROVED** [review]

File: src/Core/Content/ImportExport/ImportExportProfileDefinition.php [hunk 1]
```diff
@@ -39,9 +40,9 @@ public function since(): ?string
 
     protected function defineFields(): FieldCollection
     {
-        $fields = new FieldCollection([
+        return new FieldCollection([
             (new IdField('id', 'id'))->addFlags(new PrimaryKey(), new Required()),
-            (new StringField('technical_name', 'technicalName'))->addFlags(new Required()),
+            (new StringField('technical_name', 'technicalName'))->addFlags(new Required(), new SearchRanking(SearchRanking::HIGH_SEARCH_RANKING)),
```
Comment (ennasus4sun) [inline src/Core/Content/ImportExport/ImportExportProfileDefinition.php:45]: should we add a test to ensure/remind ourselves that a search should always be possible?

**Review by ennasus4sun — APPROVED** [review]

**Review by vintagesucks — APPROVED** [review]
