### PR TITLE
fix: skip cart recalculation on esi sub-requests

### LINKED ISSUE #8558: Improve cart recalculation on subrequests
### Technical TODO

Blackfire Homepage profile
Image

While doing a request, we calculate the cart 3 times for navigation pages. Once for the main request and another 2 for header and footer.
With large carts, up to 90% of the time is only needed to calculate and load the shopping cart.

**Preconditions:**
- Cart with
    - Multiple Promotions (with and without specific range of products)
    - ~100 products with quantity around 1000

**Expected behaviour**

Within the main request the cart should be recalculated only once.
To solve this, we could try to share the `salesChannelContext` over each subrequest

----
Related:
Issue "Big carts are slow with promotion code": https://github.com/shopware/shopware/issues/8329
PR: https://github.com/shopware/shopware/pull/8425

### PR DESCRIPTION
**Pull request by cyl3x**
### 1. Why is this change necessary?
With the new ESI sub-requests for header and footer, the cart is recalculated three times as each request loads the `SalesChannelContext` via the `SalesChannelContextService`, which always triggers a cart calculated.

### 2. What does this change do, exactly?
We check for the existence of an already calculated and memoized cart and for the kind of request which is currently loading the `SalesChannelContext` to skip the recalculation for ESI sub-requests.

### 3. Describe each step to reproduce the issue or behaviour.
for more details, see #8558.

- Have a cart
- load any navigation page
- Have a look at the stack trace

### 4. Please link to the relevant issues (if any).

- fixes #8558 

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: tests/unit/Core/System/SalesChannel/Context/SalesChannelContextServiceTest.php [hunk 1]
```diff
@@ -94,40 +123,95 @@ public function testTokenNotExpired(): void
...
+
+        $this->service->get(new SalesChannelContextServiceParameters(TestDefaults::SALES_CHANNEL, $token, Defaults::LANGUAGE_SYSTEM));
+    }
+
+    public static function skipCartCalculationIfAlreadyDoneAndESISubrequestProvider(): \Generator
+    {
+        yield 'esi request with cart => false' => [new Request(attributes: ['_sw_esi' => true]), true, false];
+        yield 'esi request without cart => true' => [new Request(attributes: ['_sw_esi' => true]), false, true];
+        yield 'no esi request but cart => true' => [new Request(), true, true];
+        yield 'no esi request and cart => true' => [new Request(), false, true];
```
Comment (mitelg) [inline tests/unit/Core/System/SalesChannel/Context/SalesChannelContextServiceTest.php]:
```suggestion
        yield 'no esi request and no cart => true' => [new Request(), false, true];
```

**Review by mitelg — APPROVED** [review]

**Review by En0Ma1259 — APPROVED** [review]

**Review by mstegmeyer — APPROVED** [review]
