### PR TITLE
fix: Info controller does not hard depend on admin bundle

### LINKED ISSUE #8855: Symfony container does not build
### Shopware Version

6.7.0.0-rc2

### Affected area / extension

Platform(Default)

### Actual behaviour

The Symfony container can not be compiled due to a hard dependency to a class from `shopware/administration`:

> The service "Shopware\Core\Framework\Api\Controller\InfoController" has a dependency on a non-existent service "Shopware\Administration\Framework\Twig\ViteFileAccessorDecorator

### Expected behaviour

The Symfony container compiles without errors, when only `shopware/core` is required in the Composer Dependencies.

### How to reproduce

1. Create a Shopware project without `shopware/administration` as a dependency
2. Run `cache:clear`
3. See the described error

### PR DESCRIPTION
**Pull request by keulinho**
Fixes https://github.com/shopware/shopware/issues/8855

### CODE REVIEW

File: src/Core/Framework/Api/Controller/InfoController.php [hunk 1]
```diff
@@ -58,7 +58,7 @@ public function __construct(
         private readonly SystemConfigService $systemConfigService,
         private readonly ApiRouteInfoResolver $apiRouteInfoResolver,
         private readonly InAppPurchase $inAppPurchase,
-        private readonly ViteFileAccessorDecorator $viteFileAccessorDecorator,
+        private readonly ?ViteFileAccessorDecorator $viteFileAccessorDecorator,
```
Comment (h1k3r) [inline src/Core/Framework/Api/Controller/InfoController.php:61]: I think we need automated check to notify in PR comments about such dependencies (or better forbid them :) )

**Review by h1k3r — APPROVED** [review]

File: src/Core/Framework/Api/Controller/InfoController.php (hunk 1 above)
Comment (mitelg) [reply src/Core/Framework/Api/Controller/InfoController.php:61]: we had deptrac in the past and there were several attempts to bring it back or similar tools :see_no_evil: 

but yes, we need something like this.

Comment (mitelg) [inline src/Core/Framework/Api/Controller/InfoController.php:61]: I know, this is the simple solution. but how about decoupling it completely with an event or so?

**Review by mitelg — APPROVED** [review]

File: src/Core/Framework/Api/Controller/InfoController.php (hunk 1 above)
Comment (keulinho) [reply src/Core/Framework/Api/Controller/InfoController.php:61]: i won't go in that direction, actually the controller is only there fore the admin, or at least that route, so doing it "correctly" the route should be in admin namespace, but we don't want more PHP in admin I guess

Comment (mitelg) [reply src/Core/Framework/Api/Controller/InfoController.php:61]: yeah, we need to define, what is needed for "our" admin, and what is needed for "any" admin and then separate accordingly properly

**Comment by astehlik** [comment]
Thank you for taking care of this, @keulinho :heart: 

I already started on a fix for this with an alternative approach and now finally hat the time to publish it in #9058 

Just putting it out there as a suggestion, feel free to close it does not make sense for you. If you think it makes sense, I'll publish the PR (currently it's just a draft) :smiley:
