### PR TITLE
fix: do not show intra community note if VAT is invalid

### LINKED ISSUE #5715: Intra-community note shown on invoices for orders with invalid vat.ID
*Steps to reproduce:* 

* open country settings “settings” > “countries” and select “Belgium” for example
* make sure that the settings “Tax-free (B2B)“ and “Validate VAT.no format“ are enabled
* submit an order for a B2B customer (from Belgium) with an invalid(!) vat ID next

*Result:* 

Since the vat ID is invalid, the order now no longer will be tax free, which is correct. Nevertheless, the intra-community note gets shown on the invoice being generated afterwards.

*Expected result:* 

In this case, however, the intra-community note must NOT appear on the invoice document being generated afterwards.

### PR DESCRIPTION
**Pull request by jozsefdamokos**
fixes #5715 

Steps to reproduce: 

- open country settings “settings” > “countries” and select “Belgium” for example
- make sure that the settings “Tax-free (B2B)“ and “Validate VAT.no format“ are enabled
- submit an order for a B2B customer (from Belgium) with an invalid(!) vat ID next

Result: 

Since the vat ID is invalid, the order now no longer will be tax free, which is correct. Nevertheless, the intra-community note gets shown on the invoice being generated afterwards.

Expected result: 

In this case, however, the intra-community note must NOT appear on the invoice document being generated afterwards.

### CODE REVIEW

**Review by ennasus4sun — APPROVED** [review]

File: src/Core/Checkout/Document/Renderer/AbstractDocumentRenderer.php [hunk 1]
```diff
@@ -73,4 +76,40 @@ protected function isAllowIntraCommunityDelivery(array $config, OrderEntity $ord
...
+        if ($customerType !== CustomerEntity::ACCOUNT_TYPE_BUSINESS) {
+            return false;
+        }
+
+        $orderDelivery = $order->getDeliveries()?->first();
+        if (!$orderDelivery) {
+            return false;
+        }
+
+        $shippingAddress = $orderDelivery->getShippingOrderAddress();
```
Comment (MalteJanz) [inline src/Core/Checkout/Document/Renderer/AbstractDocumentRenderer.php:92]: Just curious: is the shipping address the right choice here? Alternative could be the billing address right? 🤔

Comment (MalteJanz) [reply src/Core/Checkout/Document/Renderer/AbstractDocumentRenderer.php:92]: Ah I see, it's similar to the method `isAllowIntraCommunityDelivery`

File: src/Core/Checkout/Document/Renderer/CreditNoteRenderer.php [hunk 2]
```diff
@@ -138,7 +140,7 @@ public function render(array $operations, Context $context, DocumentRendererConf
                     'intraCommunityDelivery' => $this->isAllowIntraCommunityDelivery(
                         $config->jsonSerialize(),
                         $order,
-                    ),
+                    ) && $this->isValidVat($order, $this->validator),
```
Comment (MalteJanz) [inline src/Core/Checkout/Document/Renderer/CreditNoteRenderer.php:143]: Can't this logic be included in `isAllowIntraCommunityDelivery`? That also contains some similiar checks to retrieve the country 🤔

File: tests/integration/Core/Checkout/Document/Renderer/InvoiceRendererTest.php [hunk 3]
```diff
@@ -419,11 +419,13 @@ function (DocumentGenerateOperation $operation, ContainerInterface $container):
...
-                static::assertNotNull($order->getAddresses()->get($order->getBillingAddressId()));
-                static::assertNotNull($order->getAddresses()->get($order->getBillingAddressId())->getCountry());
+                $orderAddress = $order->getDeliveries()?->first()?->getShippingOrderAddress();
+
+                static::assertNotNull($orderAddress);
+                static::assertNotNull($orderAddress->getCountry());
+
                 $container->get('country.repository')->upsert([[
-                    'id' => $order->getAddresses()->get($order->getBillingAddressId())->getCountry()->getId(),
+                    'id' => $orderAddress->getCountry()->getId(),
```
Comment (MalteJanz) [inline tests/integration/Core/Checkout/Document/Renderer/InvoiceRendererTest.php:428]: Seems like not only I'm confused about what to use here (country of delivery address vs billing address) 🤔 

cc: @shopware/product-cc-checkout do you have any insights into when to use which for the vatId and intra community note ?

**Comment by MalteJanz** [comment]
Btw: there is also this crazy logic in the twig templates:
- https://github.com/shopware/shopware/blob/4698d5970b0bdb36a11f18b147b42d32f141bda5/src/Core/Framework/Resources/views/documents/includes/letter_header.html.twig#L36-L38
- https://github.com/shopware/shopware/blob/39f86f4b064814f30b103484c447ce78157a68a6/src/Core/Framework/Resources/views/documents/includes/position_header.html.twig#L36-L42

Maybe there is a way to simplify that? Also looks like they are using the billingAddress 🙈

File: tests/integration/Core/Checkout/Document/Renderer/InvoiceRendererTest.php (hunk 3 above)
Comment (cyl3x) [reply tests/integration/Core/Checkout/Document/Renderer/InvoiceRendererTest.php:428]: Don't take me for granted, but since Intra-Community is about shipping within the EU, the shipping address should be correct :thinking:

Comment (Bird87ZA) [reply tests/integration/Core/Checkout/Document/Renderer/InvoiceRendererTest.php:428]: I agree, if it's about shipping, it should use the Shipping address (not billing).

File: src/Core/Checkout/Document/Renderer/CreditNoteRenderer.php (hunk 2 above)
Comment (jozsefdamokos) [reply src/Core/Checkout/Document/Renderer/CreditNoteRenderer.php:143]: The reason was that the method needs the `Validator` class and to have it I would need to introduce a constructor in `AbstractDocumentRenderer`, which is a public class and did not want to deprecate it. Also maybe the method is useful on its own in some scenarios.

File: tests/integration/Core/Checkout/Document/Renderer/InvoiceRendererTest.php (hunk 3 above)
Comment (jozsefdamokos) [reply tests/integration/Core/Checkout/Document/Renderer/InvoiceRendererTest.php:428]: I am also unsure which one it should be

**Comment by jozsefdamokos** [comment]
> Btw: there is also this crazy logic in the twig templates:
> 
> * https://github.com/shopware/shopware/blob/4698d5970b0bdb36a11f18b147b42d32f141bda5/src/Core/Framework/Resources/views/documents/includes/letter_header.html.twig#L36-L38
> * https://github.com/shopware/shopware/blob/39f86f4b064814f30b103484c447ce78157a68a6/src/Core/Framework/Resources/views/documents/includes/position_header.html.twig#L36-L42
> 
> Maybe there is a way to simplify that? Also looks like they are using the billingAddress 🙈

Created https://github.com/shopware/shopware/issues/8571 for this

**Review by DennisGarding — APPROVED** [review]
