### PR TITLE
fix: variant indicator missing in product listing

### LINKED ISSUE #7559: 6.7 - Variant button missing in product listing in certain cases
If you duplicate a product with variants, the icon/button, which would open a modal to show all the variants of this product, is missing in the product listing.

*Steps to reproduce:*

# Have a product with variants
# Duplicate this product
# Go to the product listing in the admin

*Expected behaviour:*
The button should always be visible for all products, that have variants

*Actual behaviour:*
The button to open a modal with a list of variants is missing, if this product is a duplicate

### PR DESCRIPTION
**Pull request by sydinh**
### 1. Why is this change necessary?

When cloning a product with variants. A `ProductIndexingMessage` message is dispatched to the queue. The AdminWorker continuously polls the specified message queue receiver for messages. If a message of type EntityIndexingMessage is retrieved, it is dispatched to the MessageBusInterface. The MessageBusInterface routes the message to the ProductIndexer handler class, which processes the message.
This causes us to have a delay for the message to be processed and the childCount to be updated, the variant icon to be displayed.

### 2. What does this change do, exactly?

The childCount is inserted directly when cloning a product because we clone both the parent and the variants when cloning a product. Therefore, childCount does not change. We skip calling childCountUpdater to eliminate unnecessary processing, solving the delay in calculating childCount.

### 3. Describe each step to reproduce the issue or behaviour.

https://shopware.atlassian.net/browse/NEXT-41038

### 4. Please link to the relevant issues (if any).

https://shopware.atlassian.net/browse/NEXT-41038

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfill them.

### CODE REVIEW

**Review by vienthuong — APPROVED** [review]

**Comment by mitelg** [comment]
hey @sydinh 
for externals it would be nice, if we can get some more context in the PR description, then just a link to our internal Jira. 

is this still WIP? otherwise I am missing some test :grin:

**Comment by sydinh** [comment]
> hey @sydinh for externals it would be nice, if we can get some more context in the PR description, then just a link to our internal Jira.
> 
> is this still WIP? otherwise I am missing some test 😁

Thank you @mitelg. I just updated the PR description. The test part is about to be added, too 😉

File: src/Core/Content/Product/ProductEntity.php [hunk 1]
```diff
@@ -45,7 +45,7 @@ class ProductEntity extends Entity implements \Stringable
 
     protected ?string $parentId = null;
 
-    protected int $childCount = 0;
+    protected int $childCount;
```
Comment (mitelg) [inline src/Core/Content/Product/ProductEntity.php]: as it is not required in the definition, should it be nullable? :thinking:

**Review by nguyenytran — APPROVED** [review]

File: src/Core/Content/Product/ProductEntity.php (hunk 1 above)
Comment (mitelg) [reply src/Core/Content/Product/ProductEntity.php]: on the other hand, I don't know it this would have some impact. as the field is a special field and might be handled specially :sweat_smile:

**Review by mitelg — APPROVED** [review]

**Comment by mitelg** [comment]
can we have a test for this?

**Review by vienthuong — APPROVED** [review]

File: changelog/_unreleased/2025-03-12-variant-indicator-missing-in-product-listing.md [hunk 2]
```diff
@@ -0,0 +1,10 @@
+---
+title: Variant indicator missing in product listing
+issue: 7447
+---
+# Core
+* Changed `update` method in `Shopware\Core\Content\Product\DataAbstractionLayer\ProductIndexer` to skip update childCount for cloned products.
+___
+# Administration
+* Changed `sw-product-clone-modal` component to insert childCount for parent product when cloning a product.
+* Changed `Shopware\Core\Framework\DataAbstractionLayer\Field\ChildCountField` to allow system_scope context to write childCount.
```
Comment (sydinh) [inline changelog/_unreleased/2025-03-12-variant-indicator-missing-in-product-listing.md:10]: One of the core changes.

**Review by mitelg — APPROVED** [review]

**Review by nguyenytran — APPROVED** [review]
