### PR TITLE
fix: allow select parent product for cross selling

### LINKED ISSUE #14954: Im Crossselling sind keine Hauptartikel wählbar
### Shopware Version

6.7.4.2

### Affected area / extension

Platform(Default)

### Actual behaviour

#14631 was closed ans i cant reopen it-

In cross-selling, only variants or "articles without variants" can be selected when assigning manually.
The problem is that you cant assign parent-articles if you choose "manual assignment". There are only variants or single-articles (without variant) available, thats the problem.

If you choose dynamic its possible, but thats not the problem, because we will use "manual assignment".

### Expected behaviour

Main articles should also be selectable when assigned manually. Currently, main articles can only be selected via a dynamic product group.

### How to reproduce

Choose "manual assignment" and try to configure a parent article.

### PR DESCRIPTION
**Pull request by nguyenquocdaile**
### Solution 

Screenshot 2026-02-24 at 2 55 28 PM

### CODE REVIEW

**Review by vienthuong — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-product/component/sw-product-cross-selling-assignment/index.js [hunk 1]
```diff
@@ -63,14 +63,6 @@ export default {
         searchCriteria() {
             const criteria = new Criteria(1, 25);
 
-            criteria.addFilter(Criteria.not('and', [Criteria.equals('id', this.product.id)]));
```
Comment (rittou) [inline src/Administration/Resources/app/administration/src/module/sw-product/component/sw-product-cross-selling-assignment/index.js:66]: Should exclude the current viewing product.

Comment (nguyenquocdaile) [reply src/Administration/Resources/app/administration/src/module/sw-product/component/sw-product-cross-selling-assignment/index.js:66]: Good point. Updated it.

**Review by sydinh — APPROVED** [review]
