### PR TITLE
fix: fix product entity stringify should use translated name

### LINKED ISSUE #5086: product variable "is empty" except for non-variant product in default language
Originally reported in issue #4070 for SW6.5.7.3, but that one timed out and this remains an issue in 6.6.5.1 as well as 6.6.6.1.

The product variable passes the 'is empty' test in Twig templates if it's a storefront domain with a non-default language or the current product is a variant product. I was able to test this in a new sales channel with the base theme.

For example, in templates like `storefront/component/buy-widget/buy-widget.html.twig` and `storefront/component/product/card/box-standard.html.twig`, `product is empty` (or, in the case of the product detail page, `page.product` is empty) evaluates to true in the mentioned conditions. This is the case despite the product data being still visibly loaded and `dump()`able. This ruins checks in included templates for valid passed product variables - even `product|default('something')` will evaluate to `'something'`.

### PR DESCRIPTION
**Pull request by vienthuong**
Please see the description of the linked issue #5086

According: https://twig.symfony.com/doc/3.x/tests/empty.html

> For objects that implement the __toString() magic method (and not Countable), it will check if an empty string is returned.

### CODE REVIEW

File: tests/integration/Core/Content/Product/ProductEntityTest.php [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+ */
+#[Package('inventory')]
+class ProductEntityTest extends TestCase
+{
+    use IntegrationTestBehaviour;
+
+    #[DataProvider('productProvider')]
+    public function testStringifyProduct(ProductEntity $entity, string $expected): void
+    {
+        static::assertEquals($expected, $this->renderTestTemplate($entity));
```
Comment (mitelg) [inline tests/integration/Core/Content/Product/ProductEntityTest.php]:
```suggestion
        static::assertSame($expected, $this->renderTestTemplate($entity));
```
please use `assertSame` where possible instead, as it is type safe

File: tests/unit/Core/Content/Product/ProductEntityTest.php [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+#[Package('inventory')]
+#[CoversClass(ProductEntity::class)]
+class ProductEntityTest extends TestCase
+{
+    public function testStringify(): void
+    {
+        $entity = new ProductEntity();
+        $entity->setId('fooId');
+
+        static::assertEquals('', (string) $entity);
```
Comment (mitelg) [inline tests/unit/Core/Content/Product/ProductEntityTest.php]:
```suggestion
        static::assertSame('', (string) $entity);
```

File: tests/unit/Core/Content/Product/ProductEntityTest.php [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+
+        $entity->setName('foo');
+
+        static::assertEquals('foo', (string) $entity);
```
Comment (mitelg) [inline tests/unit/Core/Content/Product/ProductEntityTest.php]:
```suggestion
        static::assertSame('foo', (string) $entity);
```

File: tests/unit/Core/Content/Product/ProductEntityTest.php [hunk 4]
```diff
@@ -0,0 +1,34 @@
...
+
+        $entity->setTranslated([
+            'name' => 'translated foo',
+        ]);
+
+        static::assertEquals('translated foo', (string) $entity);
```
Comment (mitelg) [inline tests/unit/Core/Content/Product/ProductEntityTest.php]:
```suggestion
        static::assertSame('translated foo', (string) $entity);
```

**Review by mitelg — CHANGES_REQUESTED** [review]

**Review by mitelg — APPROVED** [review]

**Review by nguyenytran — APPROVED** [review]
