### PR TITLE
fix: reduce too many cache cleaning operations

### LINKED ISSUE #10706: Commercial 7.0.0 prevents installation of other extensions
### Shopware Version

7.0.0

### Affected area / extension

Extension:Commercial

### Actual behaviour

With Commercial 7.0.0 (Shopware 6.7.0.0) installed and active, it is not possible to install other extensions. It will throw the following error message: 
`Failed opening required '/var/www/clients/client13354/web18686/web/var/cache/prod_h7e50101cc0fc5807342ae54e068de98f/Container3xPUF6Y/removed-ids.php' (include_path='.:/opt/php-8.4/lib/php')`

The weird thing is, that this error message is not necessarily thrown all the time and even if it is thrown, it is not always necessarily preventing the action of the user. 

### Expected behaviour

Extensions can still be installed, although commercial is active

### How to reproduce

1. Install Shopware 6.7.0.0
2. Install Commercial 7.0.0
3. Install any other extension (tested with Custom Products, CMS Extension and PayPal)

It's worth mentioning, that this error message does not seem to occur in all cases. However, this seems to be the most reliable way. It seems to be important, that the extension you want to install at step 3 has never been installed yet. 
For example, I did not get this error message, when I have installed Custom products first, installed Commercial afterwards, and then uninstalled and reinstalled Custom products

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by nfortier-shopware**
### 1. Why is this change necessary?

There are concurrent calls from SwagExtensionCore, shopaware main application, that are invoking 2 cache cleaning:
- cache container cleaning 
- general cache

This can result to fatal error, while one process is destroying those php files cached, that were loaded and required by the application on another process.

### 2. What does this change do, exactly?

This PR add a simple lock with a time to live of 30s to these 2 methods, from anywhere they are invoked. 
This will reduce the possibility of race condition.

### 3. Describe each step to reproduce the issue or behaviour.

See issue, this can be done on local also without using the store to install extensions (with zip install)

### 4. Please link to the relevant issues (if any).

- closes [#10706](https://github.com/shopware/shopware/issues/10706)

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Core/Framework/Adapter/Cache/CacheClearer.php [hunk 1]
```diff
@@ -142,7 +147,9 @@ public function cleanupOldContainerCacheDirectories(): void
         }
 
         if ($remove !== []) {
-            $this->filesystem->remove($remove);
+            $this->lock(function () use ($remove): void {
+                $this->filesystem->remove($remove);
+            }, __FUNCTION__, self::LOCK_TTL);
```
Comment (keulinho) [inline src/Core/Framework/Adapter/Cache/CacheClearer.php]: you use the method name as the key for the lock, however when `clearContainerCache`and `cleanupOldContainerCacheDirectories` run in parallel you still have a race condition right? so IMHO they should share the same lock because they likely operate at least on a subset of same files

File: changelog/_unreleased/2025-07-01-add-lock-for-cache-clearer.md [hunk 2]
```diff
@@ -0,0 +1,10 @@
+---
+title: Add lock for CacheClearer
+issue: 10706
+author: nfortier
+author_email: n.fortier@shopware.com
+author_github: nfortier-shopware
+---
+
+# Core
+* Added a lock of 30s to `CacheClearer` for `cleanupOldContainerCacheDirectories` and `clearContainerCache` methods to limit concurrent execution and fatal error due to PHP files destroyed by one process and required by the other.
```
Comment (mitelg) [inline changelog/_unreleased/2025-07-01-add-lock-for-cache-clearer.md]:
```suggestion
* Added a lock of 30s to `\Shopware\Core\Framework\Adapter\CacheCacheClearer` for `cleanupOldContainerCacheDirectories` and `clearContainerCache` methods to limit concurrent execution and fatal error due to PHP files destroyed by one process and required by the other.
```

imo, we should use the FQCN in the changelogs. we sometimes have classes with the same name, but different namespace :grin:

File: src/Core/Framework/Adapter/Cache/CacheClearer.php (hunk 1 above)
Comment (nfortier-shopware) [reply src/Core/Framework/Adapter/Cache/CacheClearer.php]: Makes sense they should indeed use the same lock 👍

File: src/Core/Framework/Adapter/Cache/CacheClearer.php [hunk 3]
```diff
@@ -156,6 +163,17 @@ public function clearHttpCache(): void
         }
     }
 
+    private function lock(\Closure $closure, string $key, int $timeToLive): void
+    {
+        $lock = $this->lockFactory->createLock('cache-clearer::' . $key, $timeToLive);
+
+        if ($lock->acquire(true)) {
```
Comment (mitelg) [inline src/Core/Framework/Adapter/Cache/CacheClearer.php:177]: should we add a comment here, that the request is blocked until the lock could be acquired? I needed to look up, what the parameter's effect is

Comment (nfortier-shopware) [reply src/Core/Framework/Adapter/Cache/CacheClearer.php:177]: https://symfony.com/doc/current/components/lock.html you mean we need to explain Symfony mechanism? 🤔

**Review by keulinho — APPROVED** [review]

**Review by mitelg — APPROVED** [review]
