### PR TITLE
fix: remove exception handler for FK errors and rely on restrict delete DAL handling

### LINKED ISSUE #4113: LanguageForeignKeyDeleteException is wrongly thrown
h2. Overview of the problem

The {{Core/System/Language/LanguageExceptionHandler}} has a very generic {{matchException}} implementation. It basically only checks for the MySQL error codes 1216 and 1217, which both relate to foreign key constraint failures. There is currently no check if this MySQL error relates to a language and a deletion in any way.

There was a check for that some time ago, when the handler also checked the command, that was executed, but that was removed for unknown reasons.

h2. Why this is bad

This false error is confusing when using the DAL / API, because it leads to wrong conclusions. It also impacted the {{MigrationAssistant}} and migration process, because it appeared multiple times in the migration log and doesn’t help to find the root cause of the issue (some source data was invalid and not written, which leads to later follow up errors because of foreign key constraints). It was discovered during the developer support of *#SWAG-250255*

h2. Further investigation

List of the MariaDB error codes: [https://mariadb.com/kb/en/mariadb-error-codes/|https://mariadb.com/kb/en/mariadb-error-codes/|smart-link] 
List of MySQL error codes: [https://dev.mysql.com/doc/mysql-errors/8.0/en/server-error-reference.html|https://dev.mysql.com/doc/mysql-errors/8.0/en/server-error-reference.html|smart-link] 

Take a closer look at the error codes: 1216, 1217 and 1451, 1452

It looks like the later 14** codes are replacements for the older 12** codes because they provide more context. See [https://bugs.mysql.com/bug.php?id=3443|https://bugs.mysql.com/bug.php?id=3443|smart-link] 

It also looks like these 12** errors are still thrown in MySQL, because the customer of the support case was using MySQL 8.0.25-15 .

Local reproduction of the issue with MariaDB 10.5.22 never showed the `LanguageForeignKeyDeleteException` which maybe means that mariaDB doesn’t throw these errors without context anymore.

h3. Open questions

Is this a regression bug in MySQL? Does it occur in the later MySQL versions?

Searches for similar MySQL issues may provide some insights: [https://bugs.mysql.com/search.php?search_for=&status[]=Active&severity=&limit=30&order_by=&cmd=display&phpver=&os=0&os_details=&bug_age=0&cpu_arch=0&cpu_arch_details=&last_updated=0&tags=&similar=3443|https://bugs.mysql.com/search.php?search_for=&status%5B%5D=Active&severity=&limit=30&order_by=&cmd=display&phpver=&os=0&os_details=&bug_age=0&cpu_arch=0&cpu_arch_details=&last_updated=0&tags=&similar=3443]

h2. Expected behaviour

don’t throw a `LanguageForeignKeyDeleteException` if the error has nothing to do with languages or deleting. At least throw a meaningful error, which describes what is going on. At beast also provide more context, like what command / table was affected, which would really help in debugging the issue.

### PR DESCRIPTION
**Pull request by keulinho**
Fixes https://github.com/shopware/shopware/issues/4113

Restrict deletes are handled generally in the DAL, see `EntityWriter`, there is no need (anymore) for the specific exception handlers to catch DB level errors (when restrict delete flag is properly set)

One exception was that Language was excluded from this, but it only affects 5 fks, IMHO it makes more sense to handle language like every other entity here

### CODE REVIEW

File: src/Core/Framework/DataAbstractionLayer/Dbal/EntityForeignKeyResolver.php [hunk 1]
```diff
@@ -167,11 +167,6 @@ private function fetch(EntityDefinition $definition, array $ids, string $class,
             return [];
         }
 
-        // prevent foreign key check for language definition, otherwise all ids of language translations has to be checked
-        if ($definition->getClass() === LanguageDefinition::class) {
```
Comment (keulinho) [inline src/Core/Framework/DataAbstractionLayer/Dbal/EntityForeignKeyResolver.php:171]: this is the main change, that makes all the language specific FK exception handlers unnecessary (and actually changing this would never trigger the old exception handlers anymore)

File: src/Core/System/SalesChannel/Aggregate/SalesChannelDomain/SalesChannelDomainDefinition.php [hunk 2]
```diff
@@ -70,7 +71,7 @@ protected function defineFields(): FieldCollection
             (new ManyToOneAssociationField('currency', 'currency_id', CurrencyDefinition::class, 'id', false))->addFlags(new ApiAware()),
             new ManyToOneAssociationField('snippetSet', 'snippet_set_id', SnippetSetDefinition::class, 'id', false),
             (new OneToOneAssociationField('salesChannelDefaultHreflang', 'id', 'hreflang_default_domain_id', SalesChannelDefinition::class, false))->addFlags(new ApiAware()),
-            new OneToManyAssociationField('productExports', ProductExportDefinition::class, 'sales_channel_domain_id', 'id'),
+            (new OneToManyAssociationField('productExports', ProductExportDefinition::class, 'sales_channel_domain_id', 'id'))->addFlags(new RestrictDelete()),
```
Comment (keulinho) [inline src/Core/System/SalesChannel/Aggregate/SalesChannelDomain/SalesChannelDomainDefinition.php:74]: Here the restrictDelete was missing, with the restrictDelete in place we can remove the whole `SalesChannelExceptionHandler`

File: src/Storefront/Theme/ThemeDefinition.php [hunk 3]
```diff
@@ -70,7 +71,7 @@ protected function defineFields(): FieldCollection
 
             (new TranslationsAssociationField(ThemeTranslationDefinition::class, 'theme_id'))->addFlags(new Required()),
             new ManyToManyAssociationField('salesChannels', SalesChannelDefinition::class, ThemeSalesChannelDefinition::class, 'theme_id', 'sales_channel_id'),
-            (new ManyToManyAssociationField('media', MediaDefinition::class, ThemeMediaDefinition::class, 'theme_id', 'media_id'))->addFlags(new ApiAware()),
+            (new ManyToManyAssociationField('media', MediaDefinition::class, ThemeMediaDefinition::class, 'theme_id', 'media_id'))->addFlags(new ApiAware(), new RestrictDelete()),
```
Comment (keulinho) [inline src/Storefront/Theme/ThemeDefinition.php]: same here

File: src/Core/Framework/DataAbstractionLayer/Dbal/EntityForeignKeyResolver.php (hunk 1 above)
Comment (h1k3r) [reply src/Core/Framework/DataAbstractionLayer/Dbal/EntityForeignKeyResolver.php:171]: Why was it even made like this? Looks like some optimization 🤔

Comment (mitelg) [reply src/Core/Framework/DataAbstractionLayer/Dbal/EntityForeignKeyResolver.php:171]: unfortunately the relevant commit linked to the overall language epic. according to the comment it sounds like a performance thing. Did you made some test runs with blackfire or so?

Comment (keulinho) [reply src/Core/Framework/DataAbstractionLayer/Dbal/EntityForeignKeyResolver.php:171]: looked at this again, 

this method is used to fetch all foreign keys, 
for cascade deletes and set null this is used to dispatch the correct entity written event for the cascade entities, this could have a bigger performance impact

however for restrict deletes there are only 5 fks on the language with that cascade behaviour and additionally for restrict deletes we only fetch the first level of entities, therefore in that case the performance impact is limited

so I adjusted the case that we still filter out language fks when we look for cascades and set nulls, but include language information for the restrict delete case

**Review by mitelg — APPROVED** [review]

File: changelog/_unreleased/2025-07-28-remove-fk-delete-exception-handler.md [hunk 4]
```diff
@@ -0,0 +1,49 @@
...
+
+Additionally, the following exception handlers don't throw any exceptions anymore and are deprecated and will be removed in v6.8.0.0:
+* `OrderExceptionHandler`
+* `NewsletterExceptionHandler`
+* `LanguageExceptionHandler`
+* `SalesChannelExceptionHandler`
+* `ThemeExceptionHandler`
+___
+# Next Major Version Changes
+## Deprecate FK delete exception handler
```
Comment (mitelg) [inline changelog/_unreleased/2025-07-28-remove-fk-delete-exception-handler.md]:
```suggestion
## Remove FK delete exception handler
```

**Review by mitelg — APPROVED** [review]

**Review by h1k3r — APPROVED** [review]
