### PR TITLE
fix: sales channel context language

### LINKED ISSUE #11389: An error occurred during the selection of the customer's Sales Channel when creating an order by the administration
### Shopware Version

trunk

### Affected area / extension

Platform(Default)

### Actual behaviour

an exception was throw: 

```
{
  "errors": [
    {
      "status": "412",
      "code": "SYSTEM__SALES_CHANNEL_LANGUAGE_NOT_AVAILABLE_EXCEPTION",
      "title": "Precondition Failed",
      "detail": "Provided language \"2fbb5fe2e29a4d70aa5854ce7ce3e20b\" is not in list of available languages: 019817498e34711ea6a06fe839f52f05",
      "meta": {
        "parameters": []
      },
      "trace": [
        {
          "file": "/Users/phuoccao/Project/shopware/platform/src/Core/System/SalesChannel/Context/ContextFactory.php",
          "line": 108,
          "function": "providedLanguageNotAvailable",
          "class": "Shopware\\Core\\System\\SalesChannel\\SalesChannelException",
          "type": "::"
        },
        {
          "file": "/Users/phuoccao/Project/shopware/platform/src/Core/System/SalesChannel/Context/ContextFactory.php",
          "line": 75,
          "function": "buildLanguageChain",
          "class": "Shopware\\Core\\System\\SalesChannel\\Context\\ContextFactory",
          "type": "->"
        },
        {
          "file": "/Users/phuoccao/Project/shopware/platform/src/Core/System/SalesChannel/Context/BaseSalesChannelContextFactory.php",
          "line": 77,
          "function": "getContext",
          "class": "Shopware\\Core\\System\\SalesChannel\\Context\\ContextFactory",
          "type": "->"
        },
        {
          "file": "/Users/phuoccao/Project/shopware/platform/src/Core/System/SalesChannel/Context/CachedBaseSalesChannelContextFactory.php",
          "line": 27,
          "function": "create",
          "class": "Shopware\\Core\\System\\SalesChannel\\Context\\BaseSalesChannelContextFactory",
          "type": "->"
        },
        {
          "file": "/Users/phuoccao/Project/shopware/platform/src/Core/System/SalesChannel/Context/SalesChannelContextFactory.php",
          "line": 67,
          "function": "create",
          "class": "Shopware\\Core\\System\\SalesChannel\\Context\\CachedBaseSalesChannelContextFactory",
          "type": "->"
        },
        {
          "file": "/Users/phuoccao/Project/shopware/platform/src/Core/System/SalesChannel/Context/CachedSalesChannelContextFactory.php",
          "line": 47,
          "function": "create",
          "class": "Shopware\\Core\\System\\SalesChannel\\Context\\SalesChannelContextFactory",
          "type": "->"
        },
        {
          "file": "/Users/phuoccao/Project/shopware/platform/vendor/symfony/cache/LockRegistry.php",
          "line": 111,
          "function": "Shopware\\Core\\System\\SalesChannel\\Context\\{closure}",
          "class": "Shopware\\Core\\System\\SalesChannel\\Context\\CachedSalesChannelContextFactory",
          "type": "->"
        },
        {
          "file": "/Users/phuoccao/Project/shopware/platform/vendor/symfony/cache/Traits/ContractsTrait.php",
          "line": 102,
          "function": "compute",
          "class": "Symfony\\Component\\Cache\\LockRegistry",
          "type": "::"
        },
        {
          "file": "/Users/phuoccao/Project/shopware/platform/vendor/symfony/cache-contracts/CacheTrait.php",
          "line": 64,
          "function": "Symfony\\Component\\Cache\\Traits\\{closure}",
          "class": "Symfony\\Component\\Cache\\Adapter\\TagAwareAdapter",
          "type": "->"
        },
        {
          "file": "/Users/phuoccao/Project/shopware/platform/vendor/symfony/cache/Traits/ContractsTrait.php",
          "line": 85,
          "function": "contractsGet",
          "class": "Symfony\\Component\\Cache\\Adapter\\TagAwareAdapter",
          "type": "->"
        },
        {
          "file": "/Users/phuoccao/Project/shopware/platform/vendor/symfony/cache-contracts/CacheTrait.php",
          "line": 30,
          "function": "doGet",
          "class": "Symfony\\Component\\Cache\\Adapter\\TagAwareAdapter",
          "type": "->"
        },
        {
          "file": "/Users/phuoccao/Project/shopware/platform/src/Core/System/SalesChannel/Context/CachedSalesChannelContextFactory.php",
          "line": 43,
          "function": "get",
          "class": "Symfony\\Component\\Cache\\Adapter\\TagAwareAdapter",
          "type": "->"
        },
        {
          "file": "/Users/phuoccao/Project/shopware/platform/src/Core/System/SalesChannel/Context/SalesChannelContextService.php",
          "line": 99,
          "function": "create",
          "class": "Shopware\\Core\\System\\SalesChannel\\Context\\CachedSalesChannelContextFactory",
          "type": "->"
        },
        {
          "file": "/Users/phuoccao/Project/shopware/platform/src/Core/Profiling/Profiler.php",
          "line": 67,
          "function": "Shopware\\Core\\System\\SalesChannel\\Context\\{closure}",
          "class": "Shopware\\Core\\System\\SalesChannel\\Context\\SalesChannelContextService",
          "type": "->"
        },
        {
          "file": "/Users/phuoccao/Project/shopware/platform/src/Core/System/SalesChannel/Context/SalesChannelContextService.php",
          "line": 66,
          "function": "trace",
          "class": "Shopware\\Core\\Profiling\\Profiler",
          "type": "::"
        },
        {
          "file": "/Users/phuoccao/Project/shopware/platform/src/Core/Framework/Api/Controller/SalesChannelProxyController.php",
          "line": 350,
          "function": "get",
          "class": "Shopware\\Core\\System\\SalesChannel\\Context\\SalesChannelContextService",
          "type": "->"
        },
        {
          "file": "/Users/phuoccao/Project/shopware/platform/src/Core/Framework/Api/Controller/SalesChannelProxyController.php",
          "line": 258,
          "function": "fetchSalesChannelContext",
          "class": "Shopware\\Core\\Framework\\Api\\Controller\\SalesChannelProxyController",
          "type": "->"
        },
        {
          "file": "/Users/phuoccao/Project/shopware/platform/src/Core/Framework/Api/Controller/SalesChannelProxyController.php",
          "line": 95,
          "function": "setUpSalesChannelApiRequest",
          "class": "Shopware\\Core\\Framework\\Api\\Controller\\SalesChannelProxyController",
          "type": "->"
        },
        {
          "file": "/Users/phuoccao/Project/shopware/platform/vendor/symfony/http-kernel/HttpKernel.php",
          "line": 183,
          "function": "proxy",
          "class": "Shopware\\Core\\Framework\\Api\\Controller\\SalesChannelProxyController",
          "type": "->"
        },
        {
          "file": "/Users/phuoccao/Project/shopware/platform/vendor/symfony/http-kernel/HttpKernel.php",
          "line": 76,
          "function": "handleRaw",
          "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
          "type": "->"
        },
        {
          "file": "/Users/phuoccao/Project/shopware/platform/src/Core/Framework/Adapter/Kernel/HttpKernel.php",
          "line": 72,
          "function": "handle",
          "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
          "type": "->"
        },
        {
          "file": "/Users/phuoccao/Project/shopware/platform/vendor/symfony/http-kernel/HttpCache/SubRequestHandler.php",
          "line": 86,
          "function": "handle",
          "class": "Shopware\\Core\\Framework\\Adapter\\Kernel\\HttpKernel",
          "type": "->"
        },
        {
          "file": "/Users/phuoccao/Project/shopware/platform/vendor/symfony/http-kernel/HttpCache/HttpCache.php",
          "line": 466,
          "function": "handle",
          "class": "Symfony\\Component\\HttpKernel\\HttpCache\\SubRequestHandler",
          "type": "::"
        },
        {
          "file": "/Users/phuoccao/Project/shopware/platform/vendor/symfony/http-kernel/HttpCache/HttpCache.php",
          "line": 443,
          "function": "forward",
          "class": "Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache",
          "type": "->"
        },
        {
          "file": "/Users/phuoccao/Project/shopware/platform/vendor/symfony/http-kernel/HttpCache/HttpCache.php",
          "line": 341,
          "function": "fetch",
          "class": "Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache",
          "type": "->"
        },
        {
          "file": "/Users/phuoccao/Project/shopware/platform/vendor/symfony/http-kernel/HttpCache/HttpCache.php",
          "line": 216,
          "function": "lookup",
          "class": "Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache",
          "type": "->"
        },
        {
          "file": "/Users/phuoccao/Project/shopware/platform/src/Core/Framework/Adapter/Kernel/HttpCacheKernel.php",
          "line": 65,
          "function": "handle",
          "class": "Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache",
          "type": "->"
        },
        {
          "file": "/Users/phuoccao/Project/shopware/platform/src/Core/Kernel.php",
          "line": 129,
          "function": "handle",
          "class": "Shopware\\Core\\Framework\\Adapter\\Kernel\\HttpCacheKernel",
          "type": "->"
        },
        {
          "file": "/Users/phuoccao/Project/shopware/platform/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php",
          "line": 35,
          "function": "handle",
          "class": "Shopware\\Core\\Kernel",
          "type": "->"
        },
        {
          "file": "/Users/phuoccao/Project/shopware/platform/vendor/autoload_runtime.php",
          "line": 29,
          "function": "run",
          "class": "Symfony\\Component\\Runtime\\Runner\\Symfony\\HttpKernelRunner",
          "type": "->"
        },
        {
          "file": "/Users/phuoccao/Project/shopware/platform/public/index.php",
          "line": 10,
          "args": [
            "/Users/phuoccao/Project/shopware/platform/vendor/autoload_runtime.php"
          ],
          "function": "require_once"
        }
      ]
    }
  ]
}
```

### Expected behaviour

Can create an order for the selected customer

### How to reproduce

- Create a Sales Channel and select the Languages as German.
- Use English for administration
- Add new order -> Select customer -> select Sales Channel above

https://github.com/user-attachments/assets/14855523-ba29-4f6e-813b-c40be0ab095d

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by En0Ma1259**
### 1. Why is this change necessary?
Wrongly context language can be provided, when creating a new order via admin

### 2. What does this change do, exactly?
Validate the right sales channel language, when selecting the sales channel

### 3. Describe each step to reproduce the issue or behaviour.
- Create a Sales Channel and select the Languages as German.
- Use English for administration
- Add new order → Select customer → select Sales Channel above

### 4. Please link to the relevant issues (if any).
- fixes https://github.com/shopware/shopware/issues/11389

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have updated developer-facing release notes if this change is **relevant** for external developers:
  - Add a short entry to `RELEASE_INFO-6.<major>.md` under “Upcoming” for informational changes, including the consequences of the change and how it affects external developers.
  - Add an `UPGRADE` section in `UPGRADE-6.<next-major>.md` for breaking changes (what/why/impact/how to adapt).
  - See the [Documenting a Release Process](https://github.com/shopware/shopware/blob/trunk/delivery-process/documenting-a-release.md) for details.
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

**Review by cyl3x — APPROVED** [review]

**Review by FlorianKe — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-customer-grid/index.ts [hunk 1]
```diff
@@ -382,5 +376,19 @@ export default Component.wrapComponentConfig({
...
+                (language) => language.id === Context.api.systemLanguageId,
+            );
+
+            if (!isExists && this.customer?.salesChannel?.languageId) {
+                Store.get('context').api.languageId = this.customer.salesChannel.languageId;
+            }
+
+            if (isExists && !Store.get('context').isSystemDefaultLanguage) {
+                Store.get('context').resetLanguageToDefault();
+            }
```
Comment (mstegmeyer) [inline src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-customer-grid/index.ts]:
```suggestion
            const exists = (this.customer?.salesChannel?.languages || []).some(
                (language) => language.id === Context.api.systemLanguageId,
            );

            if (!exists && this.customer?.salesChannel?.languageId) {
                Store.get('context').api.languageId = this.customer.salesChannel.languageId;
            }

            if (exists && !Store.get('context').isSystemDefaultLanguage) {
                Store.get('context').resetLanguageToDefault();
            }
```
