### PR TITLE
fix: Re-introduce Twig escaper cache

### LINKED ISSUE #15977: Twig escape caching does not work anymore since SW 6.6.4.0
### Technical TODO

Probably since this commit https://github.com/shopware/shopware/commit/66d19da4aefed957886bd7da18fbe267c4152bf8
while updating to Twig 3.10.x the caching of escaping does not work anymore. 
Change in Twig: https://github.com/twigphp/Twig/pull/4055

Overwrite for the cache:
https://github.com/shopware/shopware/blob/trunk/src/Core/Framework/Adapter/Twig/TwigEnvironment.php#L40
https://github.com/shopware/shopware/blob/trunk/src/Core/Framework/Adapter/Twig/SwTwigFunction.php#L94

the string `twig_escape_filter(` is no longer in the generated Twig files, so this has no effect. 

Re-introduce the caching of escaping, as it should give some performance boost. Evaluate if there is better possibility than the current string-replace method.

### PR DESCRIPTION
**Pull request by mitelg**
### 1. Why is this change necessary?

The cache around the Twig EscaperRuntime did not work anymore

### 2. What does this change do, exactly?

Re-introduce it again, by replacing the correct string in the compiled Twig template.

32k less calls of the Twig core escaper

download

### 3. Describe each step to reproduce the issue or behaviour.

- Create a lot of categories (tested with 50189)
- delete twig cache and load page again

### 4. Please link to the relevant issues (if any).
- closes #15977 

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [ ] I have updated developer-facing release notes if this change is **relevant** for external developers:
  - Add a short entry to `RELEASE_INFO-6.<major>.md` under “Upcoming” for informational changes, including the consequences of the change and how it affects external developers.
  - Add an `UPGRADE` section in `UPGRADE-6.<next-major>.md` for breaking changes (what/why/impact/how to adapt).
  - See the [Documenting a Release Process](https://github.com/shopware/shopware/blob/trunk/delivery-process/documenting-a-release.md) for details.
- [ ] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfilled them

### CODE REVIEW

**Review by nfortier-shopware — APPROVED** [review]

File: src/Core/Framework/Adapter/Twig/SwTwigFunction.php [hunk 1]
```diff
@@ -82,32 +88,43 @@ public static function getAttribute(Environment $env, Source $source, mixed $obj
...
 
-        $result = $env->getRuntime(EscaperRuntime::class)->escape($string, $strategy, $charset, $autoescape);
+        try {
+            $result = $escaperRuntime->escape($string, $strategy, $charset, $autoescape);
+        } catch (RuntimeError) {
+            return $string;
+        }
 
         if (!$isString) {
             return $result;
```
Comment (SpiGAndromeda) [inline src/Core/Framework/Adapter/Twig/SwTwigFunction.php:130]: If `$string = new \stdClass()` and `$strategy = 'html'`, this line would return a `stdClass` object violating the return type.

(`EscaperRuntime::escape` passes non-Stringable inputs through unchanged, for the common strategies)

File: src/Core/Framework/Adapter/Twig/TwigEnvironment.php [hunk 2]
```diff
@@ -37,7 +40,7 @@ public function compile(Node $node): string
 
         $replaces = [
             'CoreExtension::getAttribute(' => '\Shopware\Core\Framework\Adapter\Twig\SwTwigFunction::getAttribute(',
-            'twig_escape_filter(' => '\Shopware\Core\Framework\Adapter\Twig\SwTwigFunction::escapeFilter(',
+            '$this->env->getRuntime(\'Twig\\Runtime\\EscaperRuntime\')->escape(' => '\Shopware\Core\Framework\Adapter\Twig\SwTwigFunction::escapeFilter($this->env->getRuntime(\'Twig\\Runtime\\EscaperRuntime\'), ',
```
Comment (SpiGAndromeda) [inline src/Core/Framework/Adapter/Twig/TwigEnvironment.php:43]: That fixes the problem but this seems to be as brittle as before. An internal change in Twig would break the functionality again. As far as I can see, no test would catch this.

File: src/Core/Framework/Adapter/Twig/SwTwigFunction.php [hunk 3]
```diff
@@ -14,62 +15,67 @@
...
-                if (method_exists($object, $item)) { // @phpstan-ignore-next-line
-                    return $object->$item();    // property()
+                /** @see DefinitionValidator::validateStruct() */
+                $getterMethods = [
+                    'get' . $item,
+                    'is' . $item,
+                    'has' . $item,
+                    'was' . $item,
+                    (string) $item, // property()
+                    'has' . preg_replace('/^has/', '', $item),
```
Comment (SpiGAndromeda) [inline src/Core/Framework/Adapter/Twig/SwTwigFunction.php:71]: Could you give an example method name that would match here? Same for the next line.

File: src/Core/Framework/Adapter/Twig/SwTwigFunction.php [hunk 4]
```diff
@@ -82,32 +88,43 @@ public static function getAttribute(Environment $env, Source $source, mixed $obj
...
+        string $strategy = 'html',
+        ?string $charset = null,
+        bool $autoescape = false,
+    ): string|Markup {
         if ($string === null) {
             $string = '';
         }
 
-        if (\is_int($string)) {
+        if (\is_scalar($string)) {
```
Comment (SpiGAndromeda) [inline src/Core/Framework/Adapter/Twig/SwTwigFunction.php:105]: Passing a boolean previously returned the raw boolean from `escapeFilter` (the old `is_int` guard didn't cast it, and `EscaperRuntime::escape` returns non-Stringable scalars as-is for html). So thats better now, I think?

A unit test would pin the new behavior so a future revert doesn't silently regress it.

File: src/Core/Framework/Adapter/Twig/SwTwigFunction.php [hunk 5]
```diff
@@ -14,62 +15,67 @@
 use Twig\Source;
 use Twig\Template;
 
-#[Package('framework')]
 /**
  * @internal
+ * The here defined methods are set into the compiled Twig templates in the Twig Enviornment override in {@see TwigEnvironment::compile()}
```
Comment (SpiGAndromeda) [inline src/Core/Framework/Adapter/Twig/SwTwigFunction.php]:
```suggestion
 * The here defined methods are set into the compiled Twig templates in the Twig Environment override in {@see TwigEnvironment::compile()}
```

File: src/Core/Framework/Adapter/Twig/SwTwigFunction.php [hunk 6]
```diff
@@ -14,62 +15,67 @@
...
-     * @param mixed $item The item to get from the array or object
-     * @param array<int|mixed> $arguments An array of arguments to pass if the item is an object method
-     * @param string $type The type of attribute (@see \Twig\Template constants)
-     * @param bool $isDefinedTest Whether this is only a defined check
-     * @param bool $ignoreStrictCheck Whether to ignore the strict attribute check or not
-     * @param int $lineno The template line where the attribute was called
-     *
-     * @throws RuntimeError if the attribute does not exist and Twig is running in strict mode and $isDefinedTest is false
+     * Wrapper around {@see CoreExtension::getAttribute()}
+     * Implements a shortcut for recieving property values from the Shopware specific `Struct` class.
```
Comment (SpiGAndromeda) [inline src/Core/Framework/Adapter/Twig/SwTwigFunction.php]:
```suggestion
     * Implements a shortcut for receiving property values from the Shopware specific `Struct` class.
```

**Review by SpiGAndromeda — CHANGES_REQUESTED** [review]

File: src/Core/Framework/Adapter/Twig/TwigEnvironment.php (hunk 2 above)
Comment (BrocksiNet) [reply src/Core/Framework/Adapter/Twig/TwigEnvironment.php:43]: Just test if the EscaperRuntime exists in our Twig environment 🤔

File: src/Core/Framework/Adapter/Twig/SwTwigFunction.php (hunk 1 above)
Comment (mitelg) [reply src/Core/Framework/Adapter/Twig/SwTwigFunction.php:130]: done

File: src/Core/Framework/Adapter/Twig/TwigEnvironment.php (hunk 2 above)
Comment (mitelg) [reply src/Core/Framework/Adapter/Twig/TwigEnvironment.php:43]: I know, that this is not the best solution and I already search a bit the Twig code. but the entry points are very limited unfortunately. I had another idea and will check it.

File: src/Core/Framework/Adapter/Twig/SwTwigFunction.php (hunk 3 above)
Comment (mitelg) [reply src/Core/Framework/Adapter/Twig/SwTwigFunction.php:71]: I commented a link to the DefinitionValidator above that code part, so you can search in the entities for examples

File: .bc-exclude.php [hunk 7]
```diff
@@ -1,4 +1,5 @@
 <?php declare(strict_types=1);
+use Shopware\Core\Framework\Adapter\Twig\SwTwigFunction;
```
Comment (mitelg) [inline .bc-exclude.php:3]:
```suggestion

use Shopware\Core\Framework\Adapter\Twig\SwTwigFunction;
```

File: src/Core/Framework/Adapter/Twig/TwigEnvironment.php (hunk 2 above)
Comment (SpiGAndromeda) [reply src/Core/Framework/Adapter/Twig/TwigEnvironment.php:43]: Maybe a decorator for the `EscaperRuntime`?

Comment (mitelg) [reply src/Core/Framework/Adapter/Twig/TwigEnvironment.php:43]: if Twig would use the container, yes. but no :grimacing: https://github.com/twigphp/Twig/blob/3.x/src/Environment.php#L133-L135

Comment (SpiGAndromeda) [reply src/Core/Framework/Adapter/Twig/TwigEnvironment.php:43]: Mhhhhhh .... decorate `Environment` then? :D (even if possible, probably an overkill for this one here)

Comment (mitelg) [reply src/Core/Framework/Adapter/Twig/TwigEnvironment.php:43]: we are already doing this. so let me check

Comment (mitelg) [reply src/Core/Framework/Adapter/Twig/TwigEnvironment.php]: I refactored this. please have a look again

File: src/Core/Framework/Adapter/Twig/SwTwigFunction.php (hunk 4 above)
Comment (mitelg) [reply src/Core/Framework/Adapter/Twig/SwTwigFunction.php]: refactored also this part a bit to directly check boolean.

File: src/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntime.php [hunk 8]
```diff
@@ -0,0 +1,127 @@
...
+
+    public function __construct(
+        private readonly EscaperRuntime $originalEscaperRuntime,
+    ) {
+    }
+
+    /**
+     * Mimic the public API of {@see EscaperRuntime} as it is final and cannot be extended
+     */
+    public function setEscaper(string $strategy, callable $callable): void
```
Comment (mitelg) [inline src/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntime.php:37]: @nfortier-shopware would it be okay, to ignore coverage for those wrapper methods?

Comment (nfortier-shopware) [reply src/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntime.php:37]: yes, there is zero logic but calling the original escape timer wrapped here 👍 
same for getEscaper.

The only value could be the public escape() that has branching by if statements

File: src/Core/DevOps/StaticAnalyze/PHPStan/Rules/Tests/NoAssertsOnObjectsRule.php [hunk 9]
```diff
@@ -53,6 +53,9 @@ public function processNode(Node $node, Scope $scope): array
         }
 
         $type = $scope->getType($firstArg->value);
+        if ($type->isObject()->no()) {
```
Comment (mitelg) [inline src/Core/DevOps/StaticAnalyze/PHPStan/Rules/Tests/NoAssertsOnObjectsRule.php:56]: makes only sense, if the given type is an object. During development, this was a `NEVER` type for a time and this rule showed an error 😬

**Comment by BrocksiNet** [comment]
Did you try removing the `|raw` from the Twig templates Soner added before? 
Should the performance be the same without the `|raw` right?

**Comment by mitelg** [comment]
@BrocksiNet no, best would be to check for UUID much earlier in the Twig stack and not applying the escaper at all. see my thought on the separate issue: https://github.com/shopware/shopware/issues/15971

**Review by BrocksiNet — APPROVED** [review]

File: tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeResetterTest.php [hunk 10]
```diff
@@ -0,0 +1,56 @@
...
+    {
+        // Clean up static cache after each test
+        CachedEscaperRuntime::resetEscapeCache();
+    }
+
+    public function testEscapeFilterCallsGetRuntimeAfterReset(): void
+    {
+        $escaper = new CachedEscaperRuntime(new EscaperRuntime());
+
+        $escapeCacheProperty = new \ReflectionProperty($escaper, 'escapeCache');
```
Comment (SpiGAndromeda) [inline tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeResetterTest.php]: Testing a private property is problematic. The test is bound to internal behavior with that.

Did you consider using PSR cache in the CachedEscaperRuntime? This would allow testing with a mock or stub that exposes its internal state.

File: tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeResetterTest.php [hunk 11]
```diff
@@ -0,0 +1,56 @@
...
+        CachedEscaperRuntime::resetEscapeCache();
+    }
+
+    protected function tearDown(): void
+    {
+        // Clean up static cache after each test
+        CachedEscaperRuntime::resetEscapeCache();
+    }
+
+    public function testEscapeFilterCallsGetRuntimeAfterReset(): void
```
Comment (SpiGAndromeda) [inline tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeResetterTest.php]: The test validates three distinct behaviors: cache population, cache clearing via reset, and cache re-population after reset.

Cache population and re-population are not in scope of this test file and should be moved to the `CachedEscaperRuntimeTest`.

File: tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php [hunk 12]
```diff
@@ -271,22 +292,21 @@ public function testUnicodeCodepointConversionToUtf8(): void
 
     public function testJavascriptEscapingEscapesOwaspRecommendedRanges(): void
```
Comment (SpiGAndromeda) [inline tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php:290]: Condiationals in tests are a hint that this test should be split or at least paramertized. E.g. alphanumeric, immune chars and all others.

File: tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php [hunk 13]
```diff
@@ -296,22 +316,21 @@ public function testJavascriptEscapingEscapesOwaspRecommendedRanges(): void
 
     public function testHtmlAttributeEscapingEscapesOwaspRecommendedRanges(): void
```
Comment (SpiGAndromeda) [inline tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php:314]: See https://github.com/shopware/shopware/pull/16109/changes#r3116865305

File: tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php [hunk 14]
```diff
@@ -321,35 +340,32 @@ public function testHtmlAttributeEscapingEscapesOwaspRecommendedRanges(): void
 
     public function testCssEscapingEscapesOwaspRecommendedRanges(): void
```
Comment (SpiGAndromeda) [inline tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php:338]: See https://github.com/shopware/shopware/pull/16109/changes#r3116865305

File: tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php [hunk 15]
```diff
@@ -403,6 +417,131 @@ public static function provideObjectsForEscaping(): array
...
+    }
+
+    public function testEscapeWithCachedString(): void
+    {
+        // First call to cache the result
+        $string = 'cached_string';
+        $result1 = $this->escaper->escape($string, 'html', 'UTF-8');
+
+        // Make sure result is cached
+        $cache = (new \ReflectionProperty($this->escaper, 'escapeCache'))->getValue();
```
Comment (SpiGAndromeda) [inline tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php]: See https://github.com/shopware/shopware/pull/16109/changes#r3116830124

File: tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php [hunk 16]
```diff
@@ -403,6 +417,131 @@ public static function provideObjectsForEscaping(): array
...
+            public function __toString(): string
+            {
+                return 'cached_string';
+            }
+        };
+        $hash = spl_object_hash($stringable);
+        $result1 = $this->escaper->escape($stringable, 'html', 'UTF-8');
+
+        // Make sure result is cached
+        $cache = (new \ReflectionProperty($this->escaper, 'escapeCache'))->getValue();
```
Comment (SpiGAndromeda) [inline tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php]: See https://github.com/shopware/shopware/pull/16109/changes#r3116830124

File: tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php [hunk 17]
```diff
@@ -403,6 +417,131 @@ public static function provideObjectsForEscaping(): array
...
+    }
+
+    public function testEscapeUuidWithCache(): void
+    {
+        // First call to cache the result
+        $string = Uuid::randomHex();
+        $result1 = $this->escaper->escape($string, 'html', 'UTF-8');
+
+        // Make sure result is cached
+        $cache = (new \ReflectionProperty($this->escaper, 'escapeCache'))->getValue();
```
Comment (SpiGAndromeda) [inline tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php]: See https://github.com/shopware/shopware/pull/16109/changes#r3116830124

File: tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php [hunk 18]
```diff
@@ -403,6 +417,131 @@ public static function provideObjectsForEscaping(): array
...
+        // Second call to get the cached result
+        $result2 = $this->escaper->escape($string, 'html', 'UTF-8');
+
+        // Assert that the results are the same, indicating the cache was used
+        static::assertSame($result1, $result2);
+    }
+
+    public function testEscapeDoesNotCacheBooleanInput(): void
+    {
+        $cacheProperty = new \ReflectionProperty($this->escaper, 'escapeCache');
```
Comment (SpiGAndromeda) [inline tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php]: See https://github.com/shopware/shopware/pull/16109/changes#r3116830124

File: tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php [hunk 19]
```diff
@@ -403,6 +417,131 @@ public static function provideObjectsForEscaping(): array
...
+        static::assertArrayHasKey($hash, $cache);
+
+        // Second call to get the cached result
+        $result2 = $this->escaper->escape($stringable, 'html', 'UTF-8');
+
+        // Assert that the results are the same, indicating the cache was used
+        static::assertSame($result1, $result2);
+    }
+
+    public function testEscapeUuidWithCache(): void
```
Comment (SpiGAndromeda) [inline tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php]: Doesn't this test the exact same code path as the `testEscapeWithCachedString` test?

File: tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php [hunk 20]
```diff
@@ -403,6 +417,131 @@ public static function provideObjectsForEscaping(): array
...
+    {
+        // First call to cache the result
+        $string = Uuid::randomHex();
```
Comment (SpiGAndromeda) [inline tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php]: Not necessary problematic here but non-deterministic test values are discouraged in general.

File: tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php [hunk 21]
```diff
@@ -171,39 +172,65 @@ class SwEscapeFilterTest extends TestCase
...
+        CachedEscaperRuntime::resetEscapeCache();
+        $this->escaper = new CachedEscaperRuntime(new EscaperRuntime());
+    }
+
+    protected function tearDown(): void
+    {
+        CachedEscaperRuntime::resetEscapeCache();
+    }
+
+    #[TestDox('Ensures that the decoration stays in sync with upstream')]
```
Comment (SpiGAndromeda) [inline tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php]: Very cool that you added one! Better suggestion:

```suggestion
    #[TestDox('stays in sync with upstream EscaperRuntime public methods')]
```

"Ensures that" is a meta-preamble that adds noise to the validation list of the output.

File: tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php
Comment (SpiGAndromeda) [inline tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php]: Although you didnt touch this method: could you refactor this to `yield` usage?

Comment (SpiGAndromeda) [inline tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php]: Although you didnt touch this method: could you refactor this to yield usage?

File: tests/unit/Core/Framework/Adapter/Twig/SwTwigFunctionTest.php [hunk 22]
```diff
@@ -106,86 +96,12 @@ public function testGetAttributeWithVariousInputs(Struct $object, string $attrib
...
-        $result1 = SwTwigFunction::escapeFilter($env, true, 'html', 'UTF-8');
-        $result2 = SwTwigFunction::escapeFilter($env, true, 'html', 'UTF-8');
-
-        // Results are the same with same input, but cache was not involved - guaranteed by earlier expectations
-        static::assertSame($result1, $result2);
-    }
-
     public function testGetAttributePropagatesThrowable(): void
     {
         $env = $this->createMock(Environment::class);
```
Comment (SpiGAndromeda) [inline tests/unit/Core/Framework/Adapter/Twig/SwTwigFunctionTest.php]: Mock without expects. This should be a stub instead.

File: tests/unit/Core/Framework/Adapter/Twig/SwTwigFunctionTest.php [hunk 23]
```diff
@@ -106,86 +96,12 @@ public function testGetAttributeWithVariousInputs(Struct $object, string $attrib
...
-
-        // Use a boolean since $string is mixed, and a non-string input should not be cached
-        $result1 = SwTwigFunction::escapeFilter($env, true, 'html', 'UTF-8');
-        $result2 = SwTwigFunction::escapeFilter($env, true, 'html', 'UTF-8');
-
-        // Results are the same with same input, but cache was not involved - guaranteed by earlier expectations
-        static::assertSame($result1, $result2);
-    }
-
     public function testGetAttributePropagatesThrowable(): void
```
Comment (SpiGAndromeda) [inline tests/unit/Core/Framework/Adapter/Twig/SwTwigFunctionTest.php]:
```suggestion
    public function testGetAttributeFallsBackToCoreExtensionWhenMethodThrows(): void
```

The name `testGetAttributePropagatesThrowable` claims the method propagates `\Throwable`. The source (`SwTwigFunction::getAttribute`) explicitly catches `\Throwable` at line 66 and delegates to `CoreExtension::getAttribute()`. It does NOT propagate. The test passes because of specific mock behavior in the fallback, not because the original exception was propagated.

File: tests/unit/Core/Framework/Adapter/Twig/TwigEnvironmentTest.php [hunk 24]
```diff
@@ -22,4 +25,42 @@ public function testUsesShopwareFunctions(): void
 
         static::assertStringContainsString('\Shopware\Core\Framework\Adapter\Twig\SwTwigFunction::getAttribute', $code);
     }
+
+    public function testGetRuntimeToReturnCachedEscaper(): void
```
Comment (SpiGAndromeda) [inline tests/unit/Core/Framework/Adapter/Twig/TwigEnvironmentTest.php:29]: This test tests two logically independent behaviors:

1. type substitution (`getRuntime(EscaperRuntime::class)` returns `CachedEscaperRuntime`)
2. identity-caching across calls

Both could break independently.

File: tests/unit/Core/Framework/Adapter/Twig/TwigEnvironmentTest.php [hunk 25]
```diff
@@ -22,4 +25,42 @@ public function testUsesShopwareFunctions(): void
...
+        static::assertInstanceOf(CachedEscaperRuntime::class, $escaper);
+
+        $secondCallEscaper = $twig->getRuntime(EscaperRuntime::class);
+        static::assertInstanceOf(CachedEscaperRuntime::class, $secondCallEscaper);
+
+        // Assert internal caching of the class
+        static::assertSame($escaper, $secondCallEscaper);
+    }
+
+    public function testGetRuntimeDelegatesOtherClasses(): void
```
Comment (SpiGAndromeda) [inline tests/unit/Core/Framework/Adapter/Twig/TwigEnvironmentTest.php:46]: See https://github.com/shopware/shopware/pull/16109/changes#r3116942643

**Review by SpiGAndromeda — CHANGES_REQUESTED** [review]

File: src/Core/DevOps/StaticAnalyze/PHPStan/Rules/Tests/NoAssertsOnObjectsRule.php (hunk 9 above)
Comment (nfortier-shopware) [reply src/Core/DevOps/StaticAnalyze/PHPStan/Rules/Tests/NoAssertsOnObjectsRule.php:56]: Then can you add modify the test in consequence? tests/devops/Core/DevOps/StaticAnalyse/PHPStan/Rules/data/NoAssertOnResponseObject/shopware-unit-test.php

File: src/Core/Framework/Adapter/Twig/SwTwigFunction.php [hunk 26]
```diff
@@ -3,73 +3,62 @@
...
-                    return $object->$getter();
-                }
-
-                if (method_exists($object, $isGetter)) { // @phpstan-ignore-next-line
-                    return $object->$isGetter();
-                }
-
-                if (method_exists($object, $item)) { // @phpstan-ignore-next-line
-                    return $object->$item();    // property()
+                // Structs best only have getter with get/is prefixes, or public properties. Checking for other prefixes as well is to costly
```
Comment (nfortier-shopware) [inline src/Core/Framework/Adapter/Twig/SwTwigFunction.php]: tiny typo: `to costly` -> `too costly`

File: tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php [hunk 27]
```diff
@@ -171,39 +172,65 @@ class SwEscapeFilterTest extends TestCase
...
+
+        $cachedMethods = (new \ReflectionClass(CachedEscaperRuntime::class))->getMethods(\ReflectionMethod::IS_PUBLIC);
+        $cachedMethodNames = [];
+        foreach ($cachedMethods as $method) {
+            $cachedMethodNames[] = $method->getName();
+        }
+
+        // Will fail, if methods are added upstream
+        static::assertSame([], array_diff($originalMethodNames, $cachedMethodNames));
+    }
```
Comment (nfortier-shopware) [inline tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php:200]: There is no need for reflection here:

```
    $originalMethods = get_class_methods(EscaperRuntime::class);
    $cachedMethods = get_class_methods(CachedEscaperRuntime::class);

    $missingMethods = array_diff($originalMethods, $cachedMethods);

    StrictEmpty::assertEmpty(
        $missingMethods,
        'CachedEscaperRuntime is missing methods: ' . implode(', ', $missingMethods)
    );
```

File: tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeResetterTest.php (hunk 10 above)
Comment (SpiGAndromeda) [reply tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeResetterTest.php]: Could also look like this:

```php
public function testResetClearsCacheSoSubsequentEscapeRecomputesResult(): void
    {
        $callCount = 0;
        $runtime = new EscaperRuntime();
        $runtime->setEscaper('test', static function (mixed $string, string $charset) use (&$callCount): string {
            ++$callCount;

            return strtoupper($string);
        });

        $escaper = new CachedEscaperRuntime($runtime);

        $escaper->escape('foo', 'test');
        $escaper->escape('foo', 'test');

        (new CachedEscaperRuntimeResetter())->reset();

        $escaper->escape('foo', 'test');

        static::assertSame(2, $callCount, 'The inner runtime should be called once before and once after the reset');
    }
```

File: tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php (hunk 15 above)
Comment (SpiGAndromeda) [reply tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php]: Could also look like this:

```php
public function testCachesStringEscapeResult(): void
    {
        $callCount = 0;
        $runtime = new EscaperRuntime();
        $runtime->setEscaper('test', static function (mixed $string, string $charset) use (&$callCount): string {
            ++$callCount;

            return strtoupper($string);
        });

        $escaper = new CachedEscaperRuntime($runtime);

        static::assertSame('FOO', $escaper->escape('foo', 'test'));
        static::assertSame('FOO', $escaper->escape('foo', 'test'));
        static::assertSame('FOO', $escaper->escape('foo', 'test'));

        static::assertSame(1, $callCount);
    }
```

File: tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php (hunk 16 above)
Comment (SpiGAndromeda) [reply tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php]: Could also look like this:

```php
public function testCachesStringableEscapeResult(): void
    {
        $callCount = 0;
        $runtime = new EscaperRuntime();
        $runtime->setEscaper('test', static function (mixed $string, string $charset) use (&$callCount): string {
            ++$callCount;

            return strtoupper($string);
        });

        $escaper = new CachedEscaperRuntime($runtime);

        $stringable = new class implements \Stringable {
            public function __toString(): string
            {
                return 'foo';
            }
        };

        static::assertSame('FOO', $escaper->escape($stringable, 'test'));
        static::assertSame('FOO', $escaper->escape($stringable, 'test'));

        static::assertSame(1, $callCount);
    }
```

File: tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php (hunk 17 above)
Comment (SpiGAndromeda) [reply tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php]: Could also look like this:

```php
public function testDifferentStrategiesAreCachedSeparately(): void
    {
        $callCount = 0;
        $runtime = new EscaperRuntime();
        $runtime->setEscaper('upper', static function (mixed $string, string $charset) use (&$callCount): string {
            ++$callCount;

            return strtoupper($string);
        });
        $runtime->setEscaper('lower', static function (mixed $string, string $charset) use (&$callCount): string {
            ++$callCount;

            return strtolower($string);
        });

        $escaper = new CachedEscaperRuntime($runtime);

        static::assertSame('FOO', $escaper->escape('Foo', 'upper'));
        static::assertSame('foo', $escaper->escape('Foo', 'lower'));
        static::assertSame('FOO', $escaper->escape('Foo', 'upper'));
        static::assertSame('foo', $escaper->escape('Foo', 'lower'));

        static::assertSame(2, $callCount);
    }
```

File: tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php (hunk 18 above)
Comment (SpiGAndromeda) [reply tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php]: Could also look like this:

```php
public function testDoesNotCacheBooleanInput(): void
    {
        $callCount = 0;
        $runtime = new EscaperRuntime();
        $runtime->setEscaper('test', static function (mixed $string, string $charset) use (&$callCount): string {
            ++$callCount;

            return 'escaped';
        });

        $escaper = new CachedEscaperRuntime($runtime);

        static::assertSame('escaped', $escaper->escape(true, 'test'));
        static::assertSame('escaped', $escaper->escape(true, 'test'));

        static::assertSame(2, $callCount);
    }
```

File: tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php (hunk 27 above)
Comment (mitelg) [reply tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php:200]: ah nice! was not aware of those :grin:

File: tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeResetterTest.php (hunk 10 above)
Comment (mitelg) [reply tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeResetterTest.php]: the benefit of caching the escaped values is already only in a ms range. now adding a cache layer on it, with many more operations seems, just for better testing, would probably kill the performance gain again.

File: tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeResetterTest.php (hunk 11 above)
Comment (mitelg) [reply tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeResetterTest.php]: it would be enough to check how often the `EscaperRuntime` is actually called, but as this class is final we cannot mock it and I see no other way to make sure, that the resetter is doing its job :thinking: :man_shrugging:

File: tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php
Comment (mitelg) [reply tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php]: done

Comment (mitelg) [reply tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php]: done

File: tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php (hunk 15 above)
Comment (mitelg) [reply tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php]: done

File: tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php (hunk 16 above)
Comment (mitelg) [reply tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php]: done

File: tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php (hunk 19 above)
Comment (mitelg) [reply tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php]: this is a leftover from a former solution. where I checked strings for being valid UUIDs. but I removed that due to performance reasons, so this could also be removed 👍

File: tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php (hunk 20 above)
Comment (mitelg) [reply tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php]: test removed

File: tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php (hunk 18 above)
Comment (mitelg) [reply tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php]: done

File: tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php (hunk 17 above)
Comment (mitelg) [reply tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php]: test added

File: src/Core/DevOps/StaticAnalyze/PHPStan/Rules/Tests/NoAssertsOnObjectsRule.php (hunk 9 above)
Comment (mitelg) [reply src/Core/DevOps/StaticAnalyze/PHPStan/Rules/Tests/NoAssertsOnObjectsRule.php:56]: done

File: tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php (hunk 21 above)
Comment (mitelg) [reply tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php]: done

File: tests/unit/Core/Framework/Adapter/Twig/SwTwigFunctionTest.php (hunk 22 above)
Comment (mitelg) [reply tests/unit/Core/Framework/Adapter/Twig/SwTwigFunctionTest.php]: done

File: tests/unit/Core/Framework/Adapter/Twig/TwigEnvironmentTest.php (hunk 25 above)
Comment (mitelg) [reply tests/unit/Core/Framework/Adapter/Twig/TwigEnvironmentTest.php:46]: removed the assertion of the second call, as this is internal twig logic

File: tests/unit/Core/Framework/Adapter/Twig/TwigEnvironmentTest.php (hunk 24 above)
Comment (mitelg) [reply tests/unit/Core/Framework/Adapter/Twig/TwigEnvironmentTest.php:29]: done

File: tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeResetterTest.php (hunk 10 above)
Comment (mitelg) [reply tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeResetterTest.php]: changed the test

File: tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php (hunk 12 above)
Comment (mitelg) [reply tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php:290]: as I feel not safe here, I would like to close that as out of scope

File: tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php (hunk 13 above)
Comment (mitelg) [reply tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php:314]: as I feel not safe here, I would like to close that as out of scope

File: tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php (hunk 14 above)
Comment (mitelg) [reply tests/unit/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeTest.php:338]: as I feel not safe here, I would like to close that as out of scope

**Review by nfortier-shopware — APPROVED** [review]

File: src/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntime.php [hunk 28]
```diff
@@ -0,0 +1,132 @@
...
+        $isString = \is_string($string);
+        if ($isString && isset(self::$escapeCache[$string][$strategy])) {
+            return self::$escapeCache[$string][$strategy];
+        }
+
+        // Only cache Twigs internal Markup class, as other Stringable classes cannot be ensured to be immutable
+        $isMarkup = $string instanceof Markup;
+        if ($isMarkup) {
+            $markupHash = spl_object_hash($string);
+            if (isset(self::$escapeCache[$markupHash][$strategy])) {
```
Comment (SpiGAndromeda) [inline src/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntime.php:100]: `$autoescape` is missing here for the matching. 

https://github.com/twigphp/Twig/blob/a6769aefb305efef849dc25c9fd1653358c148f0/src/Runtime/EscaperRuntime.php#L102 `EscaperRuntime::escape` uses it. First call wins for both modes (`$autoescape = true|false`) after caching. The problem happens when `{{ someMarkup|e }}` is used in the same template (at rendering level) as implicit `{{ someMarkup }}`.

Either markup caching would have to be skipped when `$autoescape = false` or the `$autoescape` value has to be part of the "cache-path".

`$charset` leads to the same problem. However, much more unlikely to happen (but a comment would be nice).

File: src/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntime.php [hunk 29]
```diff
@@ -0,0 +1,132 @@
...
+    {
+        $isString = \is_string($string);
+        if ($isString && isset(self::$escapeCache[$string][$strategy])) {
+            return self::$escapeCache[$string][$strategy];
+        }
+
+        // Only cache Twigs internal Markup class, as other Stringable classes cannot be ensured to be immutable
+        $isMarkup = $string instanceof Markup;
+        if ($isMarkup) {
+            $markupHash = spl_object_hash($string);
```
Comment (SpiGAndromeda) [inline src/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntime.php:99]: `spl_object_hash` can be reused after GC. The cache stores the result but does not hold a reference to the input Markup object.

After GC, a new unrelated Markup can land on the same hash and receive the prior cached value. From PHP docs: 
> Once the object is destroyed, its hash may be reused for other objects.

`Markup::$content` is not readonly so two distinct Markup objects can legitimately carry different content.

This can be solved by using a `WeakMap` keyed on Markup instance.

File: src/Core/Framework/DependencyInjection/services.xml [hunk 30]
```diff
@@ -364,7 +364,7 @@ frame-ancestors 'none';
             <tag name="kernel.reset" method="reset"/>
         </service>
 
-        <service id="Shopware\Core\Framework\Adapter\Twig\SwTwigFunctionResetter" public="true">
+        <service id="Shopware\Core\Framework\Adapter\Twig\Runtime\CachedEscaperRuntimeResetter" public="true">
```
Comment (SpiGAndromeda) [inline src/Core/Framework/DependencyInjection/services.xml:367]: Isn't this a BC break? A previously existing service Id is no longer available. The old service was not marked internal. An alias would be good here.

However, the whole mechanism can be considered internal (I guess the annotation was just missing). So, your decision.

... and it seems the BC detection misses this.

File: src/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntime.php [hunk 31]
```diff
@@ -0,0 +1,132 @@
...
+use Twig\Error\RuntimeError;
+use Twig\Extension\RuntimeExtensionInterface;
+use Twig\Markup;
+use Twig\Runtime\EscaperRuntime;
+
+/**
+ * @internal
+ */
+#[Package('framework')]
+class CachedEscaperRuntime implements RuntimeExtensionInterface
```
Comment (SpiGAndromeda) [inline src/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntime.php:17]:
```suggestion
final class CachedEscaperRuntime implements RuntimeExtensionInterface
```

Not mocked (and wont be mocked) and internal, so its safe to make it final (with modifier).

File: src/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeResetter.php [hunk 32]
```diff
@@ -1,25 +1,25 @@
...
  * This is essential for long runner environments (RoadRunner, FrankenPHP, Swoole)
  * where the same PHP process handles multiple requests. Without reset,
  * the escape filter cache in SwTwigFunction would grow unbounded,
  * causing memory leaks.
- *
- * @internal
  */
 #[Package('framework')]
-class SwTwigFunctionResetter implements ResetInterface
+class CachedEscaperRuntimeResetter implements ResetInterface
```
Comment (SpiGAndromeda) [inline src/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntimeResetter.php:19]:
```suggestion
final class CachedEscaperRuntimeResetter implements ResetInterface
```

Not mocked (and wont be mocked) and internal, so its safe to make it final (with modifier).

**Review by SpiGAndromeda — CHANGES_REQUESTED** [review]
While its a fix for a regression, a changelog entry might be good. But it depends on if we consider this whole funcationality as internal. Without a changelog and release note, the service alias should be added.

File: src/Core/Framework/DependencyInjection/services.xml (hunk 30 above)
Comment (mitelg) [reply src/Core/Framework/DependencyInjection/services.xml:367]: as the resetter was internal from day one, I see no reason for adding an alias...

File: src/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntime.php (hunk 28 above)
Comment (mitelg) [reply src/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntime.php]: - I added charset to the cachekey
- `autoescape` is now considered, but has no influence on the result, added a comment

File: src/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntime.php (hunk 29 above)
Comment (mitelg) [reply src/Core/Framework/Adapter/Twig/Runtime/CachedEscaperRuntime.php]: removed the support for Markup class completely, as it is returned untouched anyway in all our cases

**Review by SpiGAndromeda — APPROVED** [review]

File: src/Core/Framework/Adapter/Twig/ConfigurableFilesystemCache.php [hunk 33]
```diff
@@ -6,6 +6,9 @@
 use Shopware\Core\Framework\Util\Hasher;
 use Twig\Cache\FilesystemCache;
 
+/**
+ * @deprecated tag:v6.8.0 - reason:becomes-internal - Will be internal in v6.8.0
```
Comment (shyim) [inline src/Core/Framework/Adapter/Twig/ConfigurableFilesystemCache.php:10]: Why internal? How should I create now as a Plugin a Twig class on myself? This should be final

File: src/Core/Framework/Adapter/Twig/TemplateScopeDetector.php [hunk 34]
```diff
@@ -6,6 +6,9 @@
 use Shopware\Core\Framework\Log\Package;
 use Symfony\Component\HttpFoundation\RequestStack;
 
+/**
+ * @deprecated tag:v6.8.0 - reason:becomes-internal - Will be internal in v6.8.0
```
Comment (shyim) [inline src/Core/Framework/Adapter/Twig/TemplateScopeDetector.php:10]: Why internal? How should I create now as a Plugin a Twig class on myself? This should be final
