### PR TITLE
fix: Media manager improvements based on feedback

### LINKED ISSUE #14257: Media Manager Evaluation Ticket
### Technical TODO

Miro link: https://miro.com/app/board/uXjVIUDxQZ8=/?moveToWidget=3458764652728886355&cot=14

## AI Summary:

This evaluation ticket addresses multiple issues in the media management system affecting user experience, file operations, and UI elements. The issues range from visual feedback problems to critical functional errors in file operations.
Issues to Evaluate
1. UI Feedback Improvements
Snackbar percentages need polishing to properly display file progress counts (e.g., "3/5 files")  ✅ 
Sidebar video preview consistently displays only the first selected video instead of the currently selected one  ✅ 
2. File Deletion Problems
Multiple media deletion in the media manager triggers errors
Some files fail to delete when attempting batch deletion
Note: Deletion of multiple videos in the same file format (MP4) works correctly, suggesting format-specific issues
**EDIT: Issue is not reproducible on latest trunk. Tested it with MP4 and MOV files.** ✅ 
3. Upload Reliability
Timeout errors occur during upload processes
Files of moderate size (30MB) fail to upload under constrained network conditions (4G throttling)
Need to implement more resilient upload handling for varying network conditions ✅ 
4. Replacement Modal Issues ✅
Reference ticket #13831 for replacement modal functionality problems
"Use existing file" option in the replace modal is broken
Modal requires thorough testing to ensure proper functionality
Expected Outcomes
Reliable batch deletion of media files regardless of file type
Accurate progress indicators in the snackbar
Resilient upload functionality that handles network constraints
Properly functioning replacement modal with working "use existing file" option
Correct sidebar preview that updates based on selection
Testing Notes
Some issues are not reproducible in all environments
Cloud environment specifically shows different behavior for multiple media deletion
Testing should cover various file formats, sizes, and network conditionshttps://miro.com/app/board/uXjVIUDxQZ8=/?moveToWidget=3458764652728886355&cot=14

### PR DESCRIPTION
**Pull request by MartinKrzykawski**
fixes [#14257](https://github.com/shopware/shopware/issues/14257)

### 1. Why is this change necessary?
The evaluation ticket highlights multiple UX and functional issues in media management: inaccurate snackbar progress display, unreliable upload behavior under slow networks, sidebar video preview not updating, and a broken “use existing file” flow in the duplicate/replace modal.

### 2. What does this change do, exactly?
- Snackbar progress now shows processed counts (e.g., “3/5 files”) and is driven by upload progress events.
- Uploads no longer time out client‑side (timeout disabled for media uploads), and transport failures are mapped to clear messages (payload too large vs. connection/server timeout).
- Upload completion logic is corrected so “complete” only means the server responded (no false success at 100%).
- On failed uploads, the list refreshes so placeholder entities disappear immediately.
- The “use existing file” option in the duplicate/replace flow now closes the snackbar correctly by resolving the original placeholder upload.
- Sidebar media preview (video/audio) reloads when the selected source URL changes, so the preview matches the current selection.

### 3. Describe each step to reproduce the issue or behaviour.
A) Snackbar progress counts

- Upload multiple files in the media manager.
- Expected (after fix): snackbar shows processed count like “Uploading files (3/5)”.

B) Upload reliability under slow networks

- Throttle network (e.g., 4G) and upload video file.
- Expected (after fix): no client timeout; if a proxy/server limit is hit, a clear transport error is shown.

C) Payload too large (413)

- Set a low request body limit (e.g., Caddy request_body { max_size 1MB }), restart.
- Upload a file >1MB.
- Expected (after fix): clear “file too large / server limit” message.

D) “Use existing file” in duplicate/replace modal

- Upload a file with an existing name to trigger the duplicate modal.
- Select “Use existing file”.
- Expected (after fix): snackbar closes correctly and no placeholder remains.

E) Sidebar video preview

- Open media sidebar for a video, then select another video.
- Expected (after fix): preview reloads to the newly selected video.

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have updated developer-facing release notes if this change is **relevant** for external developers:
  - Add a short entry to `RELEASE_INFO-6.<major>.md` under “Upcoming” for informational changes, including the consequences of the change and how it affects external developers.
  - Add an `UPGRADE` section in `UPGRADE-6.<next-major>.md` for breaking changes (what/why/impact/how to adapt).
  - See the [Documenting a Release Process](https://github.com/shopware/shopware/blob/trunk/delivery-process/documenting-a-release.md) for details.
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Administration/Resources/app/administration/src/app/component/media/sw-media-preview-v2/index.js [hunk 1]
```diff
@@ -363,6 +374,20 @@ export default {
...
 
+        reloadMediaElement() {
+            if (!this.isPlayable || (this.mimeTypeGroup !== 'video' && this.mimeTypeGroup !== 'audio')) {
+                return;
+            }
+
+            this.$nextTick(() => {
+                const element = this.$refs.mediaElement;
+
+                if (element && typeof element.load === 'function') {
```
Comment (marcelbrode) [inline src/Administration/Resources/app/administration/src/app/component/media/sw-media-preview-v2/index.js]:
```suggestion
                if (typeof element?.load === 'function') {
```
Optional: First check is not necessary, if you use `?` operator.

File: src/Administration/Resources/app/administration/src/app/component/utils/sw-upload-status/index.ts [hunk 2]
```diff
@@ -77,9 +84,25 @@ const ErrorMessages = {
...
+
+const TimeoutStatuses = [
+    408,
+    504,
+    524,
+];
+const GatewayErrorStatuses = [
+    502,
+    503,
+];
```
Comment (marcelbrode) [inline src/Administration/Resources/app/administration/src/app/component/utils/sw-upload-status/index.ts:104]: Small comments would be helpful. I personally do not know what e.g. Error 408 is without googling.

File: src/Administration/Resources/app/administration/src/app/component/utils/sw-upload-status/index.ts [hunk 3]
```diff
@@ -291,11 +355,40 @@ export default Shopware.Component.wrapComponentConfig({
...
+            }
+
             messageSnippets.forEach((snippet) => {
                 this.createNotificationError({
                     message: this.$t(snippet, { fileName: payload.fileName }),
                 });
             });
         },
+        getTransportErrorSnippet(error?: UploadError): string | null {
+            const status = error?.response?.status;
```
Comment (marcelbrode) [inline src/Administration/Resources/app/administration/src/app/component/utils/sw-upload-status/index.ts]:
```suggestion
            const status = error?.response?.status || -1;
```
I guess it makes more sense to do this here, than in every check

File: src/Administration/Resources/app/administration/src/app/component/utils/sw-upload-status/sw-upload-status.spec.js [hunk 4]
```diff
@@ -120,7 +144,11 @@ async function createWrapper() {
             mocks: {
                 $t: (key, params = {}) => {
                     if (key === 'global.sw-media-upload.snackbar.message') {
-                        return `Uploading ${params.count} file(s)`;
+                        if (params.count === 1) {
+                            return 'Uploading file';
+                        }
```
Comment (marcelbrode) [inline src/Administration/Resources/app/administration/src/app/component/utils/sw-upload-status/sw-upload-status.spec.js]: Is there a way to write this test in a way to not rely on the translation itself?

File: src/Administration/Resources/app/administration/src/app/component/utils/sw-upload-status/sw-upload-status.spec.js [hunk 5]
```diff
@@ -186,6 +221,21 @@ describe('src/app/component/utils/sw-upload-status', () => {
...
 
+    it('should mark upload as finished when original target id is provided', async () => {
+        wrapper.vm.updateSnackbar = jest.fn();
+        const file = createFile('test.jpg', 'content');
+        const task = [createUploadTask('original-target', file)];
+
+        wrapper.vm.onUploadEvent(createUploadAddedEvent(task));
+        wrapper.vm.onUploadEvent(createUploadFinishedEventWithOriginal('existing-target', 'original-target'));
+
+        await wrapper.vm.$nextTick();
```
Comment (marcelbrode) [inline src/Administration/Resources/app/administration/src/app/component/utils/sw-upload-status/sw-upload-status.spec.js]: Please try to avoid `$nextTick`. Try `flushPromises` instead if possible.

File: src/Administration/Resources/app/administration/src/app/snippet/de.json [hunk 6]
```diff
@@ -490,6 +490,12 @@
         },
         "requestCanceled": {
           "message": "Das Hochladen wurde abgebrochen."
+        },
+        "payloadTooLarge": {
+          "message": "Die Datei ist für den Server oder Proxy zu groß. Bitte reduziere die Größe oder passe Server-Limits an."
+        },
+        "transportError": {
+          "message": "Upload fehlgeschlagen wegen Verbindungs- oder Server-Timeout. Bitte Verbindung oder Server-Limits pruefen."
```
Comment (marcelbrode) [inline src/Administration/Resources/app/administration/src/app/snippet/de.json]:
```suggestion
          "message": "Upload fehlgeschlagen aufgrund eines Verbindungsproblems oder eines Server-Timeouts. Bitte Verbindung oder Server-Limits prüfen."
```

File: src/Administration/Resources/app/administration/src/app/snippet/en.json [hunk 7]
```diff
@@ -490,6 +490,12 @@
         },
         "requestCanceled": {
           "message": "The upload has been cancelled."
+        },
+        "payloadTooLarge": {
+          "message": "The file is too large for the server or proxy. Please reduce the size or adjust server limits."
```
Comment (marcelbrode) [inline src/Administration/Resources/app/administration/src/app/snippet/en.json]:
```suggestion
          "message": "File is too large. Please reduce the file size or adjust server limits."
```
I think the info about server/proxy is self-explainatory.

File: src/Administration/Resources/app/administration/src/app/snippet/en.json [hunk 8]
```diff
@@ -490,6 +490,12 @@
...
+        },
+        "transportError": {
+          "message": "The upload failed due to a connection or server timeout. Please check your connection or server limits."
```
Comment (marcelbrode) [inline src/Administration/Resources/app/administration/src/app/snippet/en.json]:
```suggestion
          "message": "Upload failed due to a connection or server timeout. Please check your connection or server limits."
```

File: src/Administration/Resources/app/administration/src/app/snippet/de.json [hunk 9]
```diff
@@ -490,6 +490,12 @@
         },
         "requestCanceled": {
           "message": "Das Hochladen wurde abgebrochen."
+        },
+        "payloadTooLarge": {
+          "message": "Die Datei ist für den Server oder Proxy zu groß. Bitte reduziere die Größe oder passe Server-Limits an."
```
Comment (marcelbrode) [inline src/Administration/Resources/app/administration/src/app/snippet/de.json]:
```suggestion
          "message": "Die Datei ist zu groß. Bitte reduziere die Dateigröße oder passe Server-Limits an."
```

**Review by marcelbrode — CHANGES_REQUESTED** [review]

**Review by marcelbrode — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/app/snippet/de.json [hunk 10]
```diff
@@ -490,6 +490,12 @@
         },
         "requestCanceled": {
           "message": "Das Hochladen wurde abgebrochen."
+        },
+        "payloadTooLarge": {
+          "message": "Die Datei ist zu groß. Bitte reduziere die Dateigröße oder passe Server-Limits an."
```
Comment (bschulzebaek) [inline src/Administration/Resources/app/administration/src/app/snippet/de.json]: I dont think this would work well - thats nothing the typical user would be able to do

File: src/Administration/Resources/app/administration/src/module/sw-media/page/sw-media-index/index.js [hunk 11]
```diff
@@ -113,12 +113,16 @@ export default {
             this.uploads = this.uploads.filter((upload) => {
                 return upload.id !== targetId;
             });
+
+            this.reloadList();
```
Comment (bschulzebaek) [inline src/Administration/Resources/app/administration/src/module/sw-media/page/sw-media-index/index.js]: I would rather delete the faulty items, if possible. That way, the client does not have to re-request the whole directory (resources should be cached in the browser, but still). The Id / Tag of the upload should be known

File: src/Administration/Resources/app/administration/src/core/service/api/media.api.service.js [hunk 12]
```diff
@@ -182,10 +185,10 @@ class MediaApiService extends ApiService {
         );
     }
 
-    _startUpload(task) {
+    _startUpload(task, uploadTag) {
```
Comment (bschulzebaek) [inline src/Administration/Resources/app/administration/src/core/service/api/media.api.service.js]:
```suggestion
    _startUpload(task, uploadTag = null) {
```

**Review by bschulzebaek — APPROVED** [review]
