### PR TITLE
fix: Check plugin requirements during activation

### LINKED ISSUE #12229: Shop version 6.7.2.0 + Commercial version 7.1.2 = 500 error
### Shopware Version

6.7.2.0

### Affected area / extension

Extension:Commercial

### Actual behaviour

After updating an environment from 6.7.1.2 to the new 6.7.2.0, you are able to activate the Commercial version 7.1.2, which is not supported by the new Shopversion. 

Image

After activating the unsupported Commercial version, the Admin and Storefront are not available anymore due to 500 error:

Image

### Expected behaviour

It should not be able to activate an unsupported commercial version. Also it would be great, if the new Shopware Version and the new compatible Commercial Version are released simultaneously.

### How to reproduce

- Create new fresh 6.7.1.2 environment
- Install Commercial Version 7.1.2
- Update to 6.7.2.0
- Activate Commercial without updating to new version 

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [x] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by mitelg**
### 1. Why is this change necessary?

If a plugin is managed by composer, and it is deactivated during a Shopware update, it could be possible, that the plugin is no longer compatible with SW after this update. 
If now the plugin is tried to be activated again, it could lead to errors as incompatible code is used. See linked issue. 
This happens, because the requirements are not checked for composer managed plugins. But composer is not executed during activation, so requirements are not checked again. 

### 2. What does this change do, exactly?

Introduce an exception for the case, when the requirement validator is called during activation of the plugin, so SW will re-check the requirements manually in this case.

### 3. Describe each step to reproduce the issue or behaviour.

see linked issue

### 4. Please link to the relevant issues (if any).

- closes https://github.com/shopware/shopware/issues/12229

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [ ] I have updated developer-facing release notes if this change is **relevant** for external developers:
  - Add a short entry to `RELEASE_INFO-6.<major>.md` under “Upcoming” for informational changes, including the consequences of the change and how it affects external developers.
  - Add an `UPGRADE` section in `UPGRADE-6.<next-major>.md` for breaking changes (what/why/impact/how to adapt).
  - See the [Documenting a Release Process](https://github.com/shopware/shopware/blob/trunk/delivery-process/documenting-a-release.md) for details.
- [ ] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: tests/unit/Core/Framework/Plugin/Requirement/RequirementsValidatorTest.php [hunk 1]
```diff
@@ -139,6 +140,30 @@ public function testDoesNotValidateIfPluginIsManagedByComposer(): void
...
+
+        $packages = [];
+        static::assertInstanceOf(RequirementStackException::class, $exception);
+        foreach ($exception->getRequirements() as $requirement) {
+            $packages[] = $requirement->getParameters()['requirement'];
+        }
+
+        static::assertContains('shopware/platform', $packages);
+        static::assertContains('test/not-installed', $packages);
+    }
```
Comment (nfortier-shopware) [inline tests/unit/Core/Framework/Plugin/Requirement/RequirementsValidatorTest.php:165]: We could do something like

```
        $path = str_replace($this->projectDir, '', $this->fixturePath . 'SwagRequirementInvalidTest');

        $plugin = $this->createPlugin($path);
        $plugin->setManagedByComposer(true);

        static::expectException(RequirementStackException::class);

        try {
            $this->createValidator()->validateRequirements($plugin, Context::createDefaultContext(), PluginLifecycleService::PLUGIN_LIFECYCLE_METHOD_ACTIVATE);
        } catch (RequirementStackException $exception) {
            $packages = [];
            foreach ($exception->getRequirements() as $requirement) {
                $packages[] = $requirement->getParameters()['requirement'];
            }

            static::assertContains('shopware/platform', $packages);
            static::assertContains('test/not-installed', $packages);

            throw $exception;
        }
```
(Not a big deal and other tests in this file were written closer to your commit)

**Review by nfortier-shopware — APPROVED** [review]

File: tests/unit/Core/Framework/Plugin/Requirement/RequirementsValidatorTest.php (hunk 1 above)
Comment (mitelg) [reply tests/unit/Core/Framework/Plugin/Requirement/RequirementsValidatorTest.php:165]: yeah, I saw that, too, but I didn't wanted to refactor the whole test file :grimacing:

**Review by keulinho — APPROVED** [review]
