### PR TITLE
fix: allow ZUGFeRD invoice number selection

### LINKED ISSUE #10875: ZUGFeRD invoices numbers not selectable for credit notes and storno invoices
### Shopware Version

6.7.0.0

### Affected area / extension

Platform(Default)

### Actual behaviour

Only regular PDF invoices (document type 'invoice') can be selected when creating a credit note or storno invoice.

### Expected behaviour

The numbers of every type of invoice (ZUGFeRD, embedded ZUGFeRD and regular PDF) should be selectable when creating a credit note or storno invoice.

### How to reproduce

1. Create an order.
3. Navigate to the 'Documents' tab of the order.
4. Create a ZUGFeRD invoice.
5. Add a credit position to the order.
6. Open the modal to create a credit note.
7. Try to select the invoice number of the recently created ZUGFeRD invoice.

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [x] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by jgeramb**
### 1. Why is this change necessary?
See the related issue.

### 2. What does this change do, exactly?
It extends the document filter function to include ZUGFeRD and embedded ZUGFeRD invoices when looking for existing invoices. Also, the custom document field “invoiceNumber”, which is also set by regular and ZUGFeRD-embedded invoices, is set to the document number to display it in the administration drop-down menu.

### 3. Describe each step to reproduce the issue or behaviour.
See the related issue.

### 4. Please link to the relevant issues (if any).
- closes #10875 

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfilled them

### CODE REVIEW

**Review by larskemper — APPROVED** [review]

File: src/Core/Checkout/Document/Service/ReferenceInvoiceLoader.php [hunk 1]
```diff
@@ -45,7 +46,7 @@ public function load(string $orderId, ?string $referenceDocumentId = null, ?stri
         $builder->where('`document_type`.`technical_name` IN (:technicalNames)')
             ->andWhere('`document`.`order_id` = :orderId');
 
-        $builder->setParameter('technicalNames', [InvoiceRenderer::TYPE, ZugferdEmbeddedRenderer::TYPE], ArrayParameterType::STRING);
+        $builder->setParameter('technicalNames', [InvoiceRenderer::TYPE, ZugferdRenderer::TYPE, ZugferdEmbeddedRenderer::TYPE], ArrayParameterType::STRING);
```
Comment (jozsefdamokos) [inline src/Core/Checkout/Document/Service/ReferenceInvoiceLoader.php:49]: Can you update the test for this too? `Shopware\Tests\Integration\Core\Checkout\Document\Service\ReferenceInvoiceLoaderTest`

**Review by MalteJanz — APPROVED** [review]
