### PR TITLE
fix(app-system): update snippets with proper locales on system language change

### LINKED ISSUE #11223: Changing the default language moves admin snippets from en-GB to new default language
### Shopware Version

6.7.0.0

### Affected area / extension

Platform(Default)

### Actual behaviour

Switching the shop's default language from `en-GB` to another language after apps with admin snippets exist will move the `en-GB` snippets to the new locale. This results in missing fall back snippets in the Admin

### Expected behaviour

Snippets use the fallback for en-gb

### How to reproduce

Install apps with snippets. Change default language

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by fschmtt**
closes #11223

### CODE REVIEW

File: src/Core/Framework/App/Subscriber/SystemLanguageChangedSubscriber.php [hunk 1]
```diff
@@ -0,0 +1,132 @@
...
+        $criteria->addAssociation('locale');
+
+        $language = $this->languageRepository->search($criteria, $context)->first();
+        \assert($language instanceof LanguageEntity);
+
+        $locale = $language->getLocale();
+        \assert($locale instanceof LocaleEntity);
+
+        return $locale;
+    }
```
Comment (SebastianFranze) [inline src/Core/Framework/App/Subscriber/SystemLanguageChangedSubscriber.php]: They are basically the same :sweat_smile: 

```suggestion
    private function getLocale(string $languageId, Context $context): LocaleEntity
    {
        $criteria = new Criteria([$languageId]);
        $criteria->addAssociation('locale');

        $language = $this->languageRepository->search($criteria, $context)->first();
        \assert($language instanceof LanguageEntity);

        $locale = $language->getLocale();
        \assert($locale instanceof LocaleEntity);

        return $locale;
    }

    /**
     * Returns the locale of the new default language.
     */
    private function getDefaultLocale(Context $context): LocaleEntity
    {
        return $this->getLocale(Defaults::LANGUAGE_SYSTEM);
    }
```

File: src/Core/Framework/DependencyInjection/app.xml [hunk 2]
```diff
@@ -674,5 +675,13 @@
             <argument type="service" id="Doctrine\DBAL\Connection"/>
             <argument type="service" id="Shopware\Core\Framework\App\Privileges\Privileges"/>
         </service>
+
+        <service id="Shopware\Core\Framework\App\Subscriber\SystemLanguageChangedSubscriber">
+            <argument type="service" id="language.repository"/>
+            <argument type="service" id="app.repository" on-invalid="null"/>
```
Comment (fschmtt) [inline src/Core/Framework/DependencyInjection/app.xml]:
```suggestion
            <argument type="service" id="app.repository"/>
```

File: src/Core/Framework/App/Subscriber/SystemLanguageChangedSubscriber.php [hunk 3]
```diff
@@ -0,0 +1,113 @@
...
+        return $this->appRepository->search(new Criteria(), $context)->getEntities();
+    }
+
+    /**
+     * @param EntityRepository<AppAdministrationSnippetCollection> $snippetRepository
+     */
+    private function getSnippets(EntityRepository $snippetRepository, Context $context): AppAdministrationSnippetCollection
+    {
+        return $snippetRepository->search(new Criteria(), $context)->getEntities();
+    }
```
Comment (SebastianFranze) [inline src/Core/Framework/App/Subscriber/SystemLanguageChangedSubscriber.php]: The repo is already available:

```suggestion
    private function getSnippets(Context $context): AppAdministrationSnippetCollection
    {
        return $this->snippetRepository->search(new Criteria(), $context)->getEntities();
    }
```

File: src/Core/Framework/App/Subscriber/SystemLanguageChangedSubscriber.php [hunk 4]
```diff
@@ -0,0 +1,113 @@
...
+        $snippets = $this->getSnippets($this->snippetRepository, $context);
+        if ($snippets->count() === 0) {
+            return;
+        }
+
+        $appIds = $this->getApps($context)->getIds();
+
+        $appsWithSnippets = [];
+        foreach ($snippets as $snippet) {
+            if (\in_array($snippet->getAppId(), $appIds, true) && !\in_array($snippet->getAppId(), $appsWithSnippets, true)) {
```
Comment (SebastianFranze) [inline src/Core/Framework/App/Subscriber/SystemLanguageChangedSubscriber.php]: The test for `\in_array($snippet->getAppId(), $appIds, true)` makes no sense to me. Are you checking if a snippet's `app_id` exists in the `app` table? This is secured by data base constraints. :D

```suggestion
        $appsWithSnippets = [];
        foreach ($snippets as $snippet) {
            $appsWithSnippets[] = $snippet->getAppId();
       }
       
       $appsWithSnippets = array_unique($appsWithSnippets);
```

File: src/Core/Framework/App/Subscriber/SystemLanguageChangedSubscriber.php [hunk 5]
```diff
@@ -0,0 +1,113 @@
...
+
+        $previousLocale = $this->getLocale($event->previousLanguageId, $context);
+        $newLocale = $this->getLocale(Defaults::LANGUAGE_SYSTEM, $context);
+
+        foreach ($appsWithSnippets as $appId) {
+            $snippetToClone = $snippets->filter(fn (AppAdministrationSnippetEntity $snippet) => $appId === $snippet->getAppId() && $snippet->getLocaleId() === $newLocale->getId())->first();
+            \assert($snippetToClone instanceof AppAdministrationSnippetEntity);
+
+            $snippetWithPreviousLocaleExists = $snippets->filter(fn (AppAdministrationSnippetEntity $snippet) => $appId === $snippet->getAppId() && $snippet->getLocaleId() === $previousLocale->getId())->first();
+            if ($snippetWithPreviousLocaleExists) {
```
Comment (SebastianFranze) [inline src/Core/Framework/App/Subscriber/SystemLanguageChangedSubscriber.php]: I think if it exists, you have to swap both back because they got swapped with the locale change

But not if previous is `en-GB` and new is `de-DE` because they don't get swapped :see_no_evil:

File: src/Core/Framework/App/Subscriber/SystemLanguageChangedSubscriber.php [hunk 6]
```diff
@@ -0,0 +1,113 @@
...
+                continue;
+            }
+
+            $this->snippetRepository->create([[
```
Comment (SebastianFranze) [inline src/Core/Framework/App/Subscriber/SystemLanguageChangedSubscriber.php]: Need to upsert here

File: src/Core/Framework/App/Subscriber/SystemLanguageChangedSubscriber.php (hunk 3 above)
Comment (fschmtt) [reply src/Core/Framework/App/Subscriber/SystemLanguageChangedSubscriber.php]: It's nullable in the constructor and this way I make PHPStan happy without having to do additional `null` checks 😂

File: src/Core/Framework/App/Subscriber/SystemLanguageChangedSubscriber.php (hunk 4 above)
Comment (fschmtt) [reply src/Core/Framework/App/Subscriber/SystemLanguageChangedSubscriber.php]: Yeah IDK where my brain went yesterday evening 🤣

File: src/Core/Framework/App/Subscriber/SystemLanguageChangedSubscriber.php (hunk 6 above)
Comment (fschmtt) [reply src/Core/Framework/App/Subscriber/SystemLanguageChangedSubscriber.php]: Hmm not sure, I think in no case we want to override existing snippets - only if they do not exist, we need to create them 🤔

File: src/Core/Framework/DependencyInjection/app.xml [hunk 7]
```diff
@@ -674,5 +675,12 @@
             <argument type="service" id="Doctrine\DBAL\Connection"/>
             <argument type="service" id="Shopware\Core\Framework\App\Privileges\Privileges"/>
         </service>
+
+        <service id="Shopware\Core\Framework\App\Subscriber\SystemLanguageChangedSubscriber">
```
Comment (shyim) [inline src/Core/Framework/DependencyInjection/app.xml]: can we not put the subscriber into Administration bundle? It would fix also the on-invalid hack here

Comment (fschmtt) [reply src/Core/Framework/DependencyInjection/app.xml]: you're totally right 👍

File: src/Administration/Framework/App/Subscriber/SystemLanguageChangedSubscriber.php [hunk 8]
```diff
@@ -0,0 +1,90 @@
...
+        }
+
+        $appsWithSnippets = array_values(array_unique($snippets->map(fn (AppAdministrationSnippetEntity $snippet) => $snippet->getAppId())));
+
+        $previousLocale = $this->getLocale($event->previousLanguageId, $context);
+        $newLocale = $this->getLocale(Defaults::LANGUAGE_SYSTEM, $context);
+
+        foreach ($appsWithSnippets as $appId) {
+            $snippetToClone = $snippets->filter(fn (AppAdministrationSnippetEntity $snippet) => $appId === $snippet->getAppId() && $snippet->getLocaleId() === $newLocale->getId())->first();
+            \assert($snippetToClone instanceof AppAdministrationSnippetEntity);
```
Comment (mitelg) [inline src/Administration/Framework/App/Subscriber/SystemLanguageChangedSubscriber.php]: maybe a continue instead?

File: src/Administration/Framework/App/Subscriber/SystemLanguageChangedSubscriber.php [hunk 9]
```diff
@@ -0,0 +1,90 @@
...
+        }
+    }
+
+    private function getLocale(string $languageId, Context $context): LocaleEntity
+    {
+        $criteria = new Criteria([$languageId]);
+        $criteria->addAssociation('locale');
+
+        $language = $this->languageRepository->search($criteria, $context)->first();
+        \assert($language instanceof LanguageEntity);
```
Comment (mitelg) [inline src/Administration/Framework/App/Subscriber/SystemLanguageChangedSubscriber.php]: maybe exceptions instead of asserts. 

I am not sure, if this assert is always true at this place, but better we explicit about it, wdyt?

File: src/Administration/Framework/App/Subscriber/SystemLanguageChangedSubscriber.php (hunk 8 above)
Comment (fschmtt) [reply src/Administration/Framework/App/Subscriber/SystemLanguageChangedSubscriber.php]: switched to `continue`

File: src/Administration/Framework/App/Subscriber/SystemLanguageChangedSubscriber.php (hunk 9 above)
Comment (fschmtt) [reply src/Administration/Framework/App/Subscriber/SystemLanguageChangedSubscriber.php]: Fetching the `LocaleEntity` directly now, not through the `LanguageEntity` any more.

Both fetched locales do exist because otherwise the `ShopConfigurator` would already throw.

For this reason I annotated `/** @var LocaleEntity $locale */`

File: src/Core/Framework/App/Subscriber/SystemLanguageChangedSubscriber.php (hunk 5 above)
Comment (fschmtt) [reply src/Core/Framework/App/Subscriber/SystemLanguageChangedSubscriber.php]: And in case of `<any locale>` to `en-GB` I need to create `en-GB` snippets for the fallback mechanism 🤔

File: src/Administration/Framework/App/Subscriber/SystemLanguageChangedSubscriber.php [hunk 10]
```diff
@@ -0,0 +1,88 @@
...
+            ]], $context);
+        }
+    }
+
+    private function getLocale(string $code, Context $context): LocaleEntity
+    {
+        $criteria = new Criteria();
+        $criteria->addFilter(new EqualsFilter('code', $code));
+
+        /** @var LocaleEntity $locale */
```
Comment (mitelg) [inline src/Administration/Framework/App/Subscriber/SystemLanguageChangedSubscriber.php]: then better use the assert after the locale :grimacing:

Comment (fschmtt) [reply src/Administration/Framework/App/Subscriber/SystemLanguageChangedSubscriber.php]: will use an exception 😂

File: src/Administration/Framework/App/Subscriber/SystemLanguageChangedSubscriber.php [hunk 11]
```diff
@@ -0,0 +1,131 @@
...
+    }
+
+    public static function getSubscribedEvents(): array
+    {
+        return [
+            SystemLanguageChangeEvent::class => 'onSystemLanguageChanged',
+        ];
+    }
+
+    public function onSystemLanguageChanged(SystemLanguageChangeEvent $event): void
```
Comment (SebastianFranze) [inline src/Administration/Framework/App/Subscriber/SystemLanguageChangedSubscriber.php:42]: I'd like to try what happens if you do an early return here if `previousLocale === 'en-GB` and `newLocale === `de-DE`. In this case we only switch the `languageId`s but the snippets should remain untouched.

If we switch from `en-GB` to something other we rename language and locale instead of switching the ids.

**Review by mitelg — APPROVED** [review]

**Review by adrianles — APPROVED** [review]

File: src/Administration/Framework/App/Subscriber/SystemLanguageChangedSubscriber.php [hunk 12]
```diff
@@ -0,0 +1,114 @@
...
+        }
+
+        $appsWithSnippets = array_values(array_unique($snippets->map(fn (AppAdministrationSnippetEntity $snippet) => $snippet->getAppId())));
+
+        $previousLocale = $this->getLocale($event->previousLocaleCode, $context);
+        $newLocale = $this->getLocale($event->newLocaleCode, $context);
+
+        if ($previousLocale->getCode() === 'en-GB' && $newLocale->getCode() === 'de-DE') {
+            return;
+        }
```
Comment (SebastianFranze) [inline src/Administration/Framework/App/Subscriber/SystemLanguageChangedSubscriber.php]: You can do this on the very beginning of the handler

**Review by shyim — APPROVED** [review]

**Review by frobel — APPROVED** [review]
