### PR TITLE
fix: getAllCodes returns only string array

### LINKED ISSUE #12506: CartPromotionsDataDefinition::removeCode() may fail when codes are returned as int from getAllCodes()
### Shopware Version

6.6.5.1

### Affected area / extension

Platform(Default)

### Actual behaviour

In CartPromotionsDataDefinition, the method
```
public function getAllCodes(): array
{
    return array_keys($this->codePromotions);
}
```
can return codes as int if the promotion code was numeric.
Later, when calling
```
public function removeCode(string $code): void
{
    if (!\array_key_exists($code, $this->codePromotions)) {
        return;
    }

    unset($this->codePromotions[$code]);
}
```
the method expects a string, but array_key_exists will not match because the array key is stored as int and the argument is string.
As a result, removeCode() will fail to remove numeric codes.

### Expected behaviour

getAllCodes() should consistently return codes as string (like in getPromotionCodeTuples() where codes are explicitly cast to (string)), or removeCode() should normalize the type of $code before checking/unsetting.

Proposed fix:
```
public function getAllCodes(): array
{
    return array_map('strval', array_keys($this->codePromotions));
}
```
This will make removeCode() work correctly for numeric codes.

### How to reproduce

1. Add a promotion with a numeric code (e.g. 12345).
2. Call getAllCodes() → returns [12345] as int.
3. Pass that code into removeCode((string) $code) → the method does not remove it, because the key types don’t match.

### PR DESCRIPTION
**Pull request by FlorianKe**
### 1. Why is this change necessary?
getAllCodes code could return int array

### 4. Please link to the relevant issues (if any).
fixes #12506

### CODE REVIEW

File: src/Core/Checkout/Promotion/Cart/CartPromotionsDataDefinition.php [hunk 1]
```diff
@@ -100,7 +100,7 @@ public function removeCode(string $code): void
      */
     public function getAllCodes(): array
     {
-        return array_keys($this->codePromotions);
+        return array_map('strval', array_keys($this->codePromotions));
```
Comment (cyl3x) [inline src/Core/Checkout/Promotion/Cart/CartPromotionsDataDefinition.php]:
```suggestion
        return array_map(\strval(...), array_keys($this->codePromotions));
```

**Review by En0Ma1259 — APPROVED** [review]

**Review by mitelg — APPROVED** [review]

**Review by cyl3x — APPROVED** [review]
