### PR TITLE
fix: respect errorRoute parameter in captcha failure handler

### LINKED ISSUE #12859: Captcha error ignores errorRoute
### Shopware Version

6.7.2.2

### Affected area / extension

Platform(Default)

### Actual behaviour

If a captcha fails during the checkout/register process, the errorRoute parameter is ignored and always redirected to account/register, which leads to the guest order input being lost, for example, and the user being forced to enter a password and register an account.

### Expected behaviour

Even after a captcha validation error, the correct page from which it was started should be displayed checkout/register || account/register

### How to reproduce

Activate at least one captcha in the master data, such as Basic Captcha.
Add an item to the shopping cart and click "Checkout."
Fill out all registration fields, but make a captcha error and submit the form.
Afterward, even if, for example, "Create customer account" was deselected, you still land on account/register, and the option to create a customer account is no longer available.
After a captcha validation error, you always land on account/register without a forwardToRoute to, for example, checkout/register, where the corresponding fields, such as "Create customer account," are displayed.

### PR DESCRIPTION
**Pull request by BrocksiNet**
### 1. Why is this change necessary?

The captcha validation error handling in `ErrorController::onCaptchaFailure` was ignoring the `errorRoute` parameter, causing users to always be redirected to the current route (typically `account/register`) even when attempting guest checkout. This resulted in guest checkout users losing their checkout context and being redirected to the wrong page when captcha validation failed.

### 2. What does this change do, exactly?

- Updates `ErrorController::onCaptchaFailure` to respect the `errorRoute` parameter when forwarding after captcha validation failure
- Instead of always using the current route, the controller now forwards to the route specified in the `errorRoute` parameter
- Adds unit test coverage in `ErrorControllerTest` to verify the `errorRoute` parameter is properly handled during captcha failures
- Preserves existing behavior when no `errorRoute` parameter is provided (defaults to current route)

### 3. Describe each step to reproduce the issue or behaviour.

1. Navigate to guest checkout (`/checkout/register`) 
2. Fill out the guest checkout form
3. Fail the captcha validation (e.g., by not completing it or entering incorrect data)
4. Observe that user is redirected to `/account/register` instead of staying on `/checkout/register`
5. Checkout context and form data preferences are lost

After the fix:
1. Follow steps 1-3 above
2. User is now correctly redirected back to `/checkout/register`
3. Checkout context and preferences are preserved

### 4. Please link to the relevant issues (if any).

- closes #12859

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: tests/unit/Storefront/Controller/ErrorControllerTest.php [hunk 1]
```diff
@@ -0,0 +1,196 @@
...
+        );
+        $violations = new ConstraintViolationList([$violation]);
+
+        $request = new Request();
+        $request->request->set('errorRoute', '');
+        $request->attributes->set('_route', 'frontend.account.login.page');
+
+        $this->controller->onCaptchaFailure($violations, $request);
+
+        // Empty string is cast to string and used as-is
```
Comment (mitelg) [inline tests/unit/Storefront/Controller/ErrorControllerTest.php]: is that intended behaviour? :thinking:

**Review by mitelg — CHANGES_REQUESTED** [review]

File: tests/unit/Storefront/Controller/ErrorControllerTest.php (hunk 1 above)
Comment (BrocksiNet) [reply tests/unit/Storefront/Controller/ErrorControllerTest.php]: I was also wondering. So now the empty string is handled like in other controllers.

File: src/Storefront/Controller/ErrorController.php [hunk 2]
```diff
@@ -89,7 +89,10 @@ public function onCaptchaFailure(
     ): Response {
         $formViolations = new ConstraintViolationException($violations, []);
         if (!$request->isXmlHttpRequest()) {
-            return $this->forwardToRoute($request->get('_route'), ['formViolations' => $formViolations]);
+            $errorRoute = $request->request->get('errorRoute');
+            $route = !empty($errorRoute) ? (string) $errorRoute : (string) $request->get('_route', 'frontend.home.page');
```
Comment (mitelg) [inline src/Storefront/Controller/ErrorController.php]: why using empty? now my route name `0` is not working anymore :cry: 

just cast it to string and check for `!== ''` :slightly_smiling_face:

Comment (mitelg) [reply src/Storefront/Controller/ErrorController.php]: also consider that `_route` can also contain an empty string

**Review by mitelg — APPROVED** [review]

**Review by keulinho — APPROVED** [review]
