### PR TITLE
fix(snippet-list): Fix issues regarding deletion of snippet in sets

### LINKED ISSUE #6786: Prevent creation of Snippets - with reference to the name - with a value of type ‘integer’.
It is currently possible to assign an integer value for the name of a snippet. Although the snippet is created, it cannot be edited or deleted later on.

The error message is displayed when submitting changes / when deleting:

```json
{
    "errors": [
        {
            "code": "ba785a8c-82cb-4283-967c-3cf342181b40",
            "status": "400",
            "detail": "Dieser Wert sollte vom Typ string sein.",
            "template": "This value should be of type {{ type }}.",
            "meta": {
                "parameters": {
                    "{{ value }}": "1",
                    "{{ type }}": "string"
                }
            },
            "source": {
                "pointer": "\/0\/translationKey"
            }
        }
    ]
}
```

### LINKED ISSUE #6787: Cannot delete Snippets
Steps to reproduce: 

Set up a new snippet and try to delete it afterwards. 

The first click on ‘Delete’ causes the translations / content of the snippet to be reset. 

If I click on Delete again, I expect the snippet to be removed completely, but nothing happens here.

### PR DESCRIPTION
**Pull request by marcelbrode**
fixes #6786
fixes #6787

### 1. Why is this change necessary?
Deletion of snippets was faulty

### 2. What does this change do, exactly?
Fix multiple issues to ensure correct delete processes

### 3. Describe each step to reproduce the issue or behaviour.
Either:
- Try to delete a snippet wit ha numeric key
- Try to delete multiple snippet changes with a partial snippet set overview

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Administration/Resources/app/administration/src/module/sw-settings-snippet/page/sw-settings-snippet-list/index.js [hunk 1]
```diff
@@ -499,82 +498,84 @@ export default {
...
+        },
+
+        onCloseDeleteModal() {
+            this.showDeleteModal = false;
+            this.modalDeleteAll = false;
+            this.hasResetableItems = false;
+            this.resetItems = [];
         },
 
         onConfirmReset(fullSelection) {
```
Comment (bschulzebaek) [inline src/Administration/Resources/app/administration/src/module/sw-settings-snippet/page/sw-settings-snippet-list/index.js:511]: Could you add some tests for this?

Comment (marcelbrode) [reply src/Administration/Resources/app/administration/src/module/sw-settings-snippet/page/sw-settings-snippet-list/index.js:511]: Probably not before my vacation. I'll try my best.

Comment (marcelbrode) [reply src/Administration/Resources/app/administration/src/module/sw-settings-snippet/page/sw-settings-snippet-list/index.js:511]: Unfortunately, there's not test at all (besides simple ACL tests), so I'd take your offer and skip this for now :/

**Review by CR0YD — APPROVED** [review]

**Review by ravenokko — APPROVED** [review]
