### PR TITLE
fix: error messages when removing cms sections

### LINKED ISSUE #12423: Shopping Experiences: Request failed with status code 400 e.forEach is not a function
### Shopware Version

6.7.2.1

### Affected area / extension

Platform(Default)

### Actual behaviour

See How to reproduce

### Expected behaviour

I expect that no error messages will appear and that content that has already been created will not be lost!

### How to reproduce

1. Create a new layout.
2. Select a landing page and assign a name.
3. Add another section.
4. Add a text block to each section.
5. Save the layout.
6. Select the navigator.
7. Move the text block from the second section to the first.
8. Delete the second section.
The first error message now appears  
Image  

9. Save.
The second error message now appears.  
Image  

10. Exit the layout.
11. Select “Discard.”
12. Reopen the layout world.

The deleted section AND the content that was just moved are no longer there.

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by taltholtmann**
### 1. Why is this change necessary?
When blocks are moved between sections they should be saved, so that all the associations are correct while further editing the cms page.

### 2. What does this change do, exactly?
Save the changes when blocks are moved to other sections

### 4. Please link to the relevant issues (if any).

- closes #12423 

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have updated developer-facing release notes if this change affects external developers:
  - Add a short entry to `RELEASE_INFO-6.<major>.md` under “Upcoming” for informational changes.
  - Add an `UPGRADE` section in `UPGRADE-6.<next-major>.md` for breaking changes (what/why/impact/how to adapt).
  - See the [Release Notes & Changelog Process](../adr/2025-10-28-changelog-release-info-process.md) for details.
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Administration/Resources/app/administration/src/module/sw-cms/component/sw-cms-sidebar/index.ts [hunk 1]
```diff
@@ -570,6 +570,8 @@ export default Shopware.Component.wrapComponentConfig({
             if (!dragSectionHasBlock && !dropSectionHasBlock) {
                 this.page.sections![dragSectionIndex].blocks!.add(dragData.block);
             }
+
+            this.$emit('page-save');
```
Comment (marcelbrode) [inline src/Administration/Resources/app/administration/src/module/sw-cms/component/sw-cms-sidebar/index.ts:574]: Does this mean that everytime you drag something, but abort the process the page will be saved? That doesn't sound that right to me 🤔 Do I misunderstand something?

Comment (taltholtmann) [reply src/Administration/Resources/app/administration/src/module/sw-cms/component/sw-cms-sidebar/index.ts:574]: This is the case when using the navigator in the sidebar and then dragging blocks to other sections. 

I have evaluated that on friday with benedikt. The saving inside the cms is currently inconsistent at all.
While doing a lot of other stuff, like deleting sections, the page is saved is also saved. The problem with switching blocks to other sections is, that the association in the database is not also changed and you ran easily into error when further editing the data.

Comment (marcelbrode) [reply src/Administration/Resources/app/administration/src/module/sw-cms/component/sw-cms-sidebar/index.ts:574]: Sounds good to me then 👍

**Review by marcelbrode — APPROVED** [review]

**Review by bschulzebaek — APPROVED** [review]
