### PR TITLE
fix: batch s3 visibility

### LINKED ISSUE #8770: Copy batch ignores visibility configuration for S3
### Shopware Version

6.6.10.3

### Affected area / extension

Platform(Default)

### Actual behaviour

With the following code in `src/Core/Framework/Adapter/Filesystem/Plugin/CopyBatch.php`:
```php
$adapter = self::getAdapter($filesystem);
if ($adapter instanceof WriteBatchInterface) {
    $adapter->writeBatch(...$files);
    return;
}
``` 

...and when the filesystem is configured to use S3 (tested with DigitalOcean Spaces) like this:

```yaml
# config/packages/shopware.yaml
shopware:
  filesystem:
    asset:
        type: "amazon-s3"
        visibility: "public"
        url: "%env(string:S3_URL)%/%env(string:S3_ROOT_DIR_PUBLIC)%"
        config:
            bucket: "%env(string:S3_BUCKET)%"
            region: "%env(string:S3_REGION)%"
            endpoint: "%env(string:S3_ENDPOINT)%"
            root: "%env(string:S3_ROOT_DIR_PUBLIC)%"
            credentials:
                key: "%env(string:S3_KEY)%"
                secret: "%env(string:S3_SECRET)%"
``` 

...then **visibility is ignored**, and all copied files are uploaded as `private`, even when they should be public.

Testable by republishing the assets `bin/console assets:install --force`.

**Removing the `writeBatch` code block above resolves the issue.**

### Expected behaviour

Copied assets should respect the configured visibility settings (e.g. "public").

### How to reproduce

1. Configure filesystem to use S3/Spaces with visibility: "public" in config/packages/shopware.yaml
2. Trigger an asset copy process `bin/console assets:install --force`
3. Check visibility of the files in the S3 bucket or try to load the admin dashboard
4. The dashboard will not load since asset files are private, network requests will get 403

### PR DESCRIPTION
**Pull request by shyim**
### 4. Please link to the relevant issues (if any).

Closes https://github.com/shopware/shopware/issues/8770

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfill them.

### CODE REVIEW

File: src/Core/Framework/Adapter/Filesystem/Adapter/AsyncAwsS3WriteBatchAdapter.php [hunk 1]
```diff
@@ -46,6 +51,7 @@ public function writeBatch(CopyBatchInput ...$files): void
                         'Bucket' => $bucketName,
                         'Key' => $prefixer->prefixPath($targetFile),
                         'Body' => $sourceFile,
+                        'ACL' => $visibilityConverter->visibilityToAcl(Visibility::PUBLIC),
```
Comment (nfortier-shopware) [inline src/Core/Framework/Adapter/Filesystem/Adapter/AsyncAwsS3WriteBatchAdapter.php]: Right now by default its private when not given, but what if the visibility is defined as private in the config we would always override it with public with this change, no?

**Comment by mitelg** [comment]
@shyim any progress here?

**Comment by shyim** [comment]
tested with real aws s3 bucket, works

**Review by mitelg — APPROVED** [review]

File: src/Core/Framework/Adapter/Filesystem/Plugin/CopyBatchInput.php [hunk 2]
```diff
@@ -19,7 +20,8 @@ class CopyBatchInput
      */
     public function __construct(
```
Comment (mitelg) [inline src/Core/Framework/Adapter/Filesystem/Plugin/CopyBatchInput.php:24]: don't we need to adjust all places where this is constructed? :thinking: 

before, the files were private according to the issue creator, now they are public by default. this would mean a break of the behaviour

**Review by mitelg — CHANGES_REQUESTED** [review]

File: src/Core/Framework/Plugin/Util/AssetService.php [hunk 3]
```diff
@@ -224,7 +224,8 @@ private function sync(string $originDir, string $targetDirectory, array $localMa
         foreach ($uploads as $file) {
             $batches[] = new CopyBatchInput(
                 $originDir . '/' . $file,
-                [$targetDirectory . '/' . $file]
+                [$targetDirectory . '/' . $file],
+                $this->parameterBag->get('shopware.filesystem.asset.config')['visibility'] ?? 'public',
```
Comment (mitelg) [inline src/Core/Framework/Plugin/Util/AssetService.php]: why not using the constant here?

File: src/Storefront/Theme/ThemeCompiler.php [hunk 4]
```diff
@@ -51,7 +52,8 @@ public function __construct(
         private readonly AbstractThemePathBuilder $themePathBuilder,
         private readonly AbstractScssCompiler $scssCompiler,
         private readonly array $customAllowedRegex = [],
-        private readonly bool $validate = false
+        private readonly bool $validate = false,
+        private readonly array $themeFilesystemConfig = [],
```
Comment (mitelg) [inline src/Storefront/Theme/ThemeCompiler.php:57]: would it not possible to only inject `visibility`? :thinking:

File: src/Storefront/Theme/ThemeCompiler.php [hunk 5]
```diff
@@ -191,7 +193,7 @@ private function copyScriptFilesToTheme(
             $targetPath = $themePath . '/js/' . $folderName;
             foreach ($files as $file) {
                 if (file_exists($file->getRealPath())) {
-                    $copyFiles[] = new CopyBatchInput($file->getRealPath(), [$targetPath . '/' . $file->getFilename()]);
+                    $copyFiles[] = new CopyBatchInput($file->getRealPath(), [$targetPath . '/' . $file->getFilename()], $this->themeFilesystemConfig['visibility'] ?? 'public');
```
Comment (mitelg) [inline src/Storefront/Theme/ThemeCompiler.php]: also here the constant

File: src/Storefront/Theme/ThemeCompiler.php [hunk 6]
```diff
@@ -265,7 +267,7 @@ private function getAssets(
                 $asset = $fs->path('Resources', $asset);
             }
 
-            $collected = [...$collected, ...$this->copyBatchInputFactory->fromDirectory($asset, $outputPath)];
+            $collected = [...$collected, ...$this->copyBatchInputFactory->fromDirectory($asset, $outputPath, $this->themeFilesystemConfig['visibility'] ?? 'public')];
```
Comment (mitelg) [inline src/Storefront/Theme/ThemeCompiler.php]: also here the constant

File: src/Storefront/Theme/ThemeCompiler.php [hunk 7]
```diff
@@ -486,7 +488,8 @@ private function collectCompiledFiles(
                 $tempStream,
                 [
                     $compileLocation . \DIRECTORY_SEPARATOR . 'css' . \DIRECTORY_SEPARATOR . 'all.css',
-                ]
+                ],
+                $this->themeFilesystemConfig['visibility'] ?? 'public'
```
Comment (mitelg) [inline src/Storefront/Theme/ThemeCompiler.php]: also here the constant

File: src/Core/Framework/Adapter/Filesystem/Plugin/CopyBatchInput.php [hunk 8]
```diff
@@ -2,9 +2,13 @@
 
 namespace Shopware\Core\Framework\Adapter\Filesystem\Plugin;
 
+use League\Flysystem\Visibility;
 use Shopware\Core\Framework\Adapter\AdapterException;
 use Shopware\Core\Framework\Log\Package;
 
+/**
+ * @final
```
Comment (mitelg) [inline src/Core/Framework/Adapter/Filesystem/Plugin/CopyBatchInput.php:10]: I am so sorry :see_no_evil: but wouldn't that be a break, if we just say, it is final? :see_no_evil:

**Review by mitelg — APPROVED** [review]

File: src/Core/Framework/Adapter/Filesystem/Plugin/CopyBatchInput.php (hunk 8 above)
Comment (shyim) [reply src/Core/Framework/Adapter/Filesystem/Plugin/CopyBatchInput.php:10]: any better idea? 😂

Comment (mitelg) [reply src/Core/Framework/Adapter/Filesystem/Plugin/CopyBatchInput.php:10]: announcing it with a deprecation? :thinking:

**Review by nfortier-shopware — APPROVED** [review]

File: src/Core/Framework/Adapter/Filesystem/Plugin/CopyBatchInput.php (hunk 8 above)
Comment (shyim) [reply src/Core/Framework/Adapter/Filesystem/Plugin/CopyBatchInput.php:10]: not needed symfony is doing it https://github.com/symfony/symfony/blob/7.4/src/Symfony/Component/ErrorHandler/DebugClassLoader.php#L661
