### PR TITLE
fix: Add check for supported types

### LINKED ISSUE #13044: Media items should support common video file types
### Shopware Version

6.7.3.0

### Affected area / extension

Platform(Default)

### Actual behaviour

Certain common file formats such as `.mov` video files are not well supported. While `.mov` can be uploaded and used in the administration, it won't be displayed in the Storefront, while `.mp4` works just fine.

### Expected behaviour

Common file types are supported in the administration AND storefront.

### How to reproduce

1. Go to the administration -> media module
2. Upload a new media item (`.mov` for example)
3. Add the media item to a product
4. Go to the products storefront page -> the video cannot be played

### PR DESCRIPTION
**Pull request by alexdumea**
### 1. Why is this change necessary?
shopware allows uploading various video and audio formats in the Administration , but many of this formats are not supported by web browsers

### 2. What does this change do, exactly?
add visual warning indicator in admin media preview to notify users when a video or audio format may not be supported by browser
Screenshot 2025-10-23 at 10 39 30

Screenshot 2025-10-23 at 10 39 42

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Administration/Resources/app/administration/src/app/component/media/sw-media-preview-v2/index.js [hunk 1]
```diff
@@ -194,6 +194,10 @@ export default {
             return this.$options.playableAudioFormats.includes(this.mimeType);
         },
 
+        showUnsupportedFormatWarning() {
+            return (this.mimeTypeGroup === 'video' || this.mimeTypeGroup === 'audio') && !this.isPlayable;
```
Comment (MartinKrzykawski) [inline src/Administration/Resources/app/administration/src/app/component/media/sw-media-preview-v2/index.js]: I would recommend to store the unsupported formats in a list in an own file / class. As a list it is easier to extend it with new items as adding new conditions here and you can re-use it in the other component as well.

File: src/Administration/Resources/app/administration/src/app/snippet/de.json [hunk 2]
```diff
@@ -438,7 +438,8 @@
     "sw-media-preview-v2": {
       "fallbackVideoTagSupport": "Dein Browser unterstützt diesen Video-Tag nicht",
       "fallbackAudioTagSupport": "Dein Browser unterstützt diesen Audio-Tag nicht",
-      "textNoMedia": "Kein Medium verfügbar"
+      "textNoMedia": "Kein Medium verfügbar",
+      "warningUnsupportedFormat": "Format {format} wird möglicherweise nicht in allen Browsern unterstützt."
```
Comment (MartinKrzykawski) [inline src/Administration/Resources/app/administration/src/app/snippet/de.json]:
```suggestion
      "warningUnsupportedFormat": "Format \"{format}\" wird möglicherweise nicht in allen Browsern unterstützt."
```

File: src/Administration/Resources/app/administration/src/app/snippet/en.json [hunk 3]
```diff
@@ -438,7 +438,8 @@
     "sw-media-preview-v2": {
       "fallbackVideoTagSupport": "Your browser does not support the video tag",
       "fallbackAudioTagSupport": "Your browser does not support the audio tag",
-      "textNoMedia": "No media available"
+      "textNoMedia": "No media available",
+      "warningUnsupportedFormat": "Format {format} may not be supported in all browsers."
```
Comment (MartinKrzykawski) [inline src/Administration/Resources/app/administration/src/app/snippet/en.json]:
```suggestion
      "warningUnsupportedFormat": "Format \"{format}\" may not be supported in all browsers."
```

File: src/Administration/Resources/app/administration/src/module/sw-media/component/sidebar/sw-media-quickinfo/index.js [hunk 4]
```diff
@@ -99,6 +99,32 @@ export default {
...
+                'audio/mpeg',
+                'audio/ogg',
+                'audio/wav',
+            ];
+
+            return playableFormats.includes(this.item.mimeType);
+        },
+
+        showUnsupportedFormatWarning() {
+            return (this.mimeTypeGroup === 'video' || this.mimeTypeGroup === 'audio') && !this.isPlayable;
```
Comment (MartinKrzykawski) [inline src/Administration/Resources/app/administration/src/module/sw-media/component/sidebar/sw-media-quickinfo/index.js]: See other comment

**Review by MartinKrzykawski — CHANGES_REQUESTED** [review]

**Comment by MartinKrzykawski** [comment]
A changelog would be great :) IMO it is always good to be transparent with our work to also show our community that we are active

File: src/Administration/Resources/app/administration/src/app/component/media/sw-media-preview-v2/index.js (hunk 1 above)
Comment (marcelbrode) [reply src/Administration/Resources/app/administration/src/app/component/media/sw-media-preview-v2/index.js]: In the same manner as `SwagCmsExtensions/src/Resources/app/administration/src/extension/module/sw-cms/constant/swag-cms-extensions.constant.js` would be good, imo!

File: src/Administration/Resources/app/administration/src/app/component/media/sw-media-preview-v2/sw-media-preview-v2.spec.js [hunk 5]
```diff
@@ -264,4 +264,28 @@ describe('src/app/asyncComponent/media/sw-media-preview-v2', () => {
...
+        const wrapper = await createWrapper();
+        await wrapper.setData({
+            imagePreviewFailed: true,
+            trueSource: { mimeType: 'video/mp4', thumbnails: [] },
+        });
+        await flushPromises();
+
+        const warningIcon = wrapper.find('.sw-media-preview-v2__warning-icon');
+        expect(warningIcon.exists()).toBe(false);
+    });
```
Comment (marcelbrode) [inline src/Administration/Resources/app/administration/src/app/component/media/sw-media-preview-v2/sw-media-preview-v2.spec.js]:
```suggestion
    it.each([
        { mimeType: 'video/quicktime', isSupported: true },
        { mimeType: 'video/mp4', isSupported: false },
    ])(`should show warning icon if video format is not supported (type: ${mimetype}, supported: ${isSupported.toString()})`, async (mimeType, isSupported) => {
        const wrapper = await createWrapper();
        await wrapper.setData({
            imagePreviewFailed: true,
            trueSource: { mimeType, thumbnails: [] },
        });
        await flushPromises();

        const warningIcon = wrapper.find('.sw-media-preview-v2__warning-icon');
        expect(warningIcon.exists()).toBe(isSupported);
    });
```

How about a dataprovider? You can easily add more types to the test and you have a better overview.

File: src/Administration/Resources/app/administration/src/app/snippet/en.json (hunk 3 above)
Comment (marcelbrode) [reply src/Administration/Resources/app/administration/src/app/snippet/en.json]: Maybe it makes sense to add a caniuse link here?

File: src/Administration/Resources/app/administration/src/module/sw-media/component/sidebar/sw-media-quickinfo/sw-media-quickinfo.spec.js [hunk 6]
```diff
@@ -491,4 +491,20 @@ describe('module/sw-media/components/sw-media-quickinfo', () => {
 
         expect(actionButtonMethod).toHaveBeenCalled();
     });
+
+    it('should show warning banner for unsupported video format (MOV)', async () => {
```
Comment (marcelbrode) [inline src/Administration/Resources/app/administration/src/module/sw-media/component/sidebar/sw-media-quickinfo/sw-media-quickinfo.spec.js]: Same as in the other test

**Review by marcelbrode — APPROVED** [review]
Since my comments are more on a suggestion level, I'm fine if you apply Martins ideas already. So have my approve.

File: src/Administration/Resources/app/administration/src/app/component/media/sw-media-preview-v2/sw-media-preview-v2.spec.js [hunk 7]
```diff
@@ -264,4 +264,22 @@ describe('src/app/asyncComponent/media/sw-media-preview-v2', () => {
 
         expect(wrapper.vm.sourceSet).toBe('');
     });
+
+    it.each([
+        { mimeType: 'video/quicktime', shouldShowWarning: true },
+        { mimeType: 'video/mp4', shouldShowWarning: false },
+    ])(
+        'should show warning icon if video format is not supported (type: $mimeType, shouldShowWarning: $shouldShowWarning)',
```
Comment (marcelbrode) [inline src/Administration/Resources/app/administration/src/app/component/media/sw-media-preview-v2/sw-media-preview-v2.spec.js:272]: Never saw that. Does this work without templateString without ${..}?

Comment (alexdumea) [reply src/Administration/Resources/app/administration/src/app/component/media/sw-media-preview-v2/sw-media-preview-v2.spec.js:272]: yes , it's automatically replaced

Comment (marcelbrode) [reply src/Administration/Resources/app/administration/src/app/component/media/sw-media-preview-v2/sw-media-preview-v2.spec.js:272]: very nice to know!

**Review by MartinKrzykawski — APPROVED** [review]
Good job! :)
