### PR TITLE
fix: added locking to cart mutating routes to avoid race conditions

### LINKED ISSUE #8724: possible race condition on adding to cart
### Shopware Version

cloud

### Affected area / extension

Platform(Default)

### Actual behaviour

Quickly adding multiple products to cart is making some of them disappear.

As example: There are three `addLineItem` operations
1. first got 200 and line item was in the cart
2. second was 200 and contained only lineItem from second request
3. third was also 200 and contained line items from second and third request

in result successful operation of adding first item was lost.

Session token was the same for all three requests

### Expected behaviour

All three items should be successfully added to the cart.

### How to reproduce

1. Go to listing page: https://frontends-demo.vercel.app/Cooking-pleasure-Provence/
2. open devtools to track requests
3. quickly add first three items in the row
4. See that responses from the API indicated all products were added but at some point cart is not containing all of them

It might not work always, it took me 2 tries to reproduce this.

### PR DESCRIPTION
**Pull request by h1k3r**
### 1. Why is this change necessary?

The current implementation of cart mutating routes is subject to race conditions.

### 2. What does this change do, exactly?

Introduces simple locking like it already was made for `CartOrderRoute`

### 3. Describe each step to reproduce the issue or behaviour.

See linked issue.

### 4. Please link to the relevant issues (if any).
- closes https://github.com/shopware/shopware/issues/8724 (at lease with simplistic implementation)

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Core/Checkout/Cart/CartLocker.php [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+            throw CartException::cartLocked($token);
+        }
+
+        try {
+            return $closure();
+        } finally {
+            $lock->release();
+        }
+    }
+}
```
Comment (nfortier-shopware) [inline src/Core/Checkout/Cart/CartLocker.php:47]: Not blocking, more an open question: as we are using more and more this lockFactory mechanism in different part of our system with very similar usage, shall we use at some point a generic object that would be more core/framework domain (and replace the difference usages)?

Screenshot 2025-07-14 at 23 41 58

Comment (h1k3r) [reply src/Core/Checkout/Cart/CartLocker.php:47]: Something like this?
```php

class Locked
{
    public function __construct(private readonly LockFactory $lockFactory) {}

    public function runOrThrow(string $key, \Closure $closure, int $ttl = 5)
    {
        $lock = $this->createLock($key, $ttl);

        if (!$lock->acquire()) {
            throw LockedException::lockAquireFailed($key);
        }

        try {
            return $closure();
        } finally {
            $lock->release();
        }
    }

    public function waitAndRun(string $key, \Closure $closure, int $ttl = 5): mixed
    {
        $lock = $this->createLock($key, $ttl);

        if ($lock->acquire(true)) {
            try {
                return $closure();
            } finally {
                $lock->release();
            }
        }
    }

    private function createLock(string $key, int $ttl = 5): LockInterface
    {
        return $this->lockFactory->createLock(
            sprintf('locked_%s', $key),
            $ttl,
        );
    }
}
```

Then usage will look like
```php
// non-blocking
try {
    $result = $locked->runOrThrow('cart-' . $token, function () {
        // logic
    });
} catch (LockedException $e) {
    throw CartException::cartLocked($token);
}

//blocking
$result = $locked->waiteAndRun('cart-' . $token, function () {
    // logic
});
```

In my opinion it does not decrease size/complexity of the client code too much.

@nfortier-shopware @mitelg wdyt?

Comment (mitelg) [reply src/Core/Checkout/Cart/CartLocker.php:47]: imo, it would be a nice addition, but out of scope of this task. 

it may not reduce the code or complexity where the LockFactory is used, but having it in a central place, would abstract it away and would give us the possibility to improve or change locking globally however we like. (e.g. exchanging the Symfony component with another library, etc).

no need to change it in this PR, but we should create an issue for that.

**Review by mitelg — APPROVED** [review]

**Review by keulinho — APPROVED** [review]

File: src/Core/Checkout/Cart/CartLocker.php (hunk 1 above)
Comment (nfortier-shopware) [reply src/Core/Checkout/Cart/CartLocker.php:47]: I believe it would be good to have it yes, as it would provide a proper class tooling while now we are looking for what was implemented (remember how we were looking for non existing doc not so long ago to bandaid cache clearer)

And yes, no need to ship this within this PR, like I wrote earlier, non blocking and just an open question for later 👍

**Review by nfortier-shopware — APPROVED** [review]

File: src/Core/Checkout/Cart/CartLocker.php (hunk 1 above)
Comment (h1k3r) [reply src/Core/Checkout/Cart/CartLocker.php:47]: Created an issue https://github.com/shopware/shopware/issues/11302
