### PR TITLE
fix: Ensure product is included in search keywords

### LINKED ISSUE #13913: SearchKeywordUpdater (indexer) excludes products without assigned manufacturer when manufacturer.name is searchable
### Shopware Version

6.6.10.9, trunk

### Affected area / extension

Platform(Default)

### Actual behaviour

When manufacturer.name is configured as searchable in the product search configuration, products without an assigned manufacturer are excluded from the search index if they don't have a direct translation in the sales channel language.

The product is completely excluded from the search index and cannot be found via search.

### Expected behaviour

The product should be indexed based on its other searchable fields (name, productNumber, description, etc.),  independent on whether it has a manufacturer assigned or not. Indexing for the manufacturer fields should take place for the fallback language if needed.

### How to reproduce

  1. **Create a new language variant** (e.g., "Deutsch/AT")
     - It doesn't matter whether it inherits from a parent language or not

  2. **Ensure no Sales Channel uses a main language** (Deutsch or English)
     - Either delete the default Headless Sales Channel, or remove Deutsch/English from it
     - The only active Sales Channel should use the new language variant as its **only** language

  3. **Create a product WITHOUT a manufacturer assigned** (`manufacturer_id = NULL`)
     - The product must be **active**
     - The product must be **assigned to the active Sales Channel**
     - The product should have a translation in a main language (e.g., "Deutsch"), but not necessarily in the Sales Channel's language

  4. **Rebuild the search index:**
     ```bash
     bin/console dal:refresh:index --only=product.indexer

  5. Check the search index:
     - Expected Result: The product should be indexed.
     - Actual Result: The product is not indexed.

### PR DESCRIPTION
**Pull request by vanWittlaer**
### 1. Why is this change necessary?

  Products without a manufacturer assigned were being excluded from the search keyword index when `manufacturer.name` was configured as a searchable field (which is the default configuration). This
   caused these products to not appear in search results, particularly affecting non-system languages where the language-specific indexing would skip these products entirely.

  ### 2. What does this change do, exactly?

  The `buildCriteria` method in `SearchKeywordUpdater` builds a filter to fetch products for keyword indexing. Previously, when processing the `manufacturer.name` accessor, it added a filter
  requiring `manufacturer.translations.languageId` to match the current language. For products without a manufacturer, this filter failed to match, causing them to be excluded.

  This fix adds an OR condition that explicitly includes products where the association's foreign key is NULL (e.g., `manufacturerId = null`), ensuring products without a manufacturer are still
  fetched and indexed for their other searchable fields like `name` and `productNumber`.

  ### 3. Describe each step to reproduce the issue or behaviour.

  1. Create a new language variant (e.g., "Deutsch/AT")
     - It doesn't matter whether it inherits from a parent language or not
  2. Ensure no Sales Channel uses a main language (Deutsch or English)
     - Either delete the default Headless Sales Channel, or remove Deutsch/English from it
     - The only active Sales Channel should use the new language variant as its only language
  3. Create a product WITHOUT a manufacturer assigned (`manufacturer_id = NULL`)
     - The product must be active
     - The product must be assigned to the active Sales Channel
     - The product should have a translation in a main language (e.g., "Deutsch"), but not necessarily in the Sales Channel's language
  4. Run the search keyword indexer or trigger a product update
  5. Search for the product by its name
  6. **Expected:** Product appears in search results
  7. **Actual (before fix):** Product does not appear because it was never indexed

### 4. Please link to the relevant issues (if any).

closes #13913

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have updated developer-facing release notes if this change is **relevant** for external developers:
  - Add a short entry to `RELEASE_INFO-6.<major>.md` under “Upcoming” for informational changes, including the consequences of the change and how it affects external developers.
  - Add an `UPGRADE` section in `UPGRADE-6.<next-major>.md` for breaking changes (what/why/impact/how to adapt).
  - See the [Documenting a Release Process](https://github.com/shopware/shopware/blob/trunk/delivery-process/documenting-a-release.md) for details.
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Core/Content/Product/DataAbstractionLayer/SearchKeywordUpdater.php [hunk 1]
```diff
@@ -255,14 +255,21 @@ private function buildCriteria(array $accessors, Criteria $criteria, Context $co
                 continue;
             }
 
+            // Get the foreign key field name for null check (e.g., 'manufacturerId' for 'manufacturer')
+            $foreignKeyField = $association . 'Id';
```
Comment (vienthuong) [inline src/Core/Content/Product/DataAbstractionLayer/SearchKeywordUpdater.php]: Please check if the field exists, you can refer to \Shopware\Core\Framework\DataAbstractionLayer\Search\Parser\QueryStringParser::normalizeAssociationId

Comment (vanWittlaer) [reply src/Core/Content/Product/DataAbstractionLayer/SearchKeywordUpdater.php]: Done, however using EntityDefinitionQueryHelper::getField. Also added a test.

**Review by vienthuong — APPROVED** [review]

File: RELEASE_INFO-6.7.md [hunk 2]
```diff
@@ -57,6 +57,10 @@ shopware:
 
 ## Critical fixes
 
+### Search keywords include products without manufacturer
+
+Products without a manufacturer assigned are now properly included in the search keyword index. Previously, when `manufacturer.name` was configured as a searchable field (which is the default), products without a manufacturer were excluded from keyword indexing because the filter on manufacturer translations failed to match. This primarily affected non-system languages where the language-specific indexing would skip these products entirely.
```
Comment (mitelg) [inline RELEASE_INFO-6.7.md]: please do not add bugfix information to the release information.

**Review by mitelg — CHANGES_REQUESTED** [review]

**Review by tamvt — APPROVED** [review]

File: RELEASE_INFO-6.7.md (hunk 2 above)
Comment (vanWittlaer) [reply RELEASE_INFO-6.7.md]: removed

**Review by mitelg — APPROVED** [review]

**Comment by mitelg** [comment]
thanks for your contribution @vanWittlaer 👍🎉💙
