### PR TITLE
fix: customer active check

### LINKED ISSUE #11953: Inactive customer can buy
### Shopware Version

6.6.10.6

### Affected area / extension

Platform(Default)

### Actual behaviour

- a customer is logged in in frontend
- the customer will be disabled in admin
- the customer can use his account furthermore

### Expected behaviour

the customer is being logged out, at least when accessing any commerce function.

### How to reproduce

see behaviour

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by mstegmeyer**
### 1. Why is this change necessary?
Once a context is logged in, there is no check anymore, if a customer is actually active. Depending on session length, this could be an actual issue.

### 2. What does this change do, exactly?
Add a check on SalesChannelContext creation. Not adding a filter due to a missing index and it's an edge case.

### 3. Describe each step to reproduce the issue or behaviour.
- Create a customer
- Log in in the Storefront
- Disable the customer in the Administration
- Check if the customer is still logged in in the Storefront

### 4. Please link to the relevant issues (if any).
fixes #11953 

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Core/System/SalesChannel/Context/SalesChannelContextFactory.php [hunk 1]
```diff
@@ -243,7 +243,7 @@ private function loadCustomer(array $options, Context $context): ?CustomerEntity
         ]));
 
         $customer = $this->customerRepository->search($criteria, $context)->getEntities()->get($customerId);
-        if (!$customer) {
+        if (!$customer || !$customer->getActive()) {
```
Comment (cyl3x) [inline src/Core/System/SalesChannel/Context/SalesChannelContextFactory.php]: We should comment why we did this in PHP, so nobody will "optimize" this away

**Review by En0Ma1259 — COMMENTED** [review]
Should we add a test case (if not already there), for access a document with `deepLinkCode` and inactive customer? So this case will not be forgotten in the future?

File: src/Core/System/SalesChannel/Context/SalesChannelContextFactory.php (hunk 1 above)
Comment (mstegmeyer) [reply src/Core/System/SalesChannel/Context/SalesChannelContextFactory.php]: what? I don't see why someone would optimize it. Or do you mean putting it into an EqualsFilter?

Comment (cyl3x) [reply src/Core/System/SalesChannel/Context/SalesChannelContextFactory.php]: yes, someone trying to add it to the criteria

Comment (En0Ma1259) [reply src/Core/System/SalesChannel/Context/SalesChannelContextFactory.php]:
```suggestion
        if (!$customer?->getActive() ?? false) {
```

**Comment by mstegmeyer** [comment]
> Should we add a test case (if not already there), for access a document with `deepLinkCode` and inactive customer? So this case will not be forgotten in the future?

I will create a new ticket for this, that deepLinkCode accessed routes like OrderRoute and DocumentRoute should also be reachable for inactive registered users.
This fix will only prevent the SalesChannelContext from being filled with the customer, therefore does not have any impact on login functionality. So the inactive user already cannot be logged in and download documents at the moment 😉

**Review by cyl3x — APPROVED** [review]

**Review by En0Ma1259 — APPROVED** [review]

**Review by FlorianKe — APPROVED** [review]
