### PR TITLE
fix: Fix health checks in combination with saas

### LINKED ISSUE #9335: Extend System check: Check product detail and product listing page
### Technical TODO

Currently only the entry page of a sales channel is checked during a system check. This covers a lot of the basic cases but certain cases (e.g. on product detail or listing) can be missed when the customer has a cms page without products as their default page.

For this it would be great if the system checks also checks a product detail and product listing page. To avoid flakiness, it should return the checked pages and at the same time allow to pass a list of pages that should be changed for any future checks 

Original Issue: [NEXT-40654](https://shopware.atlassian.net/browse/NEXT-40654)

[NEXT-40654]: https://shopware.atlassian.net/browse/NEXT-40654?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### PR DESCRIPTION
**Pull request by MartinKrzykawski**
### 1. Why is this change necessary?
Since saas has an own implementation of the fetchSalesChannelDomains method (https://github.com/shopware/saas/blob/trunk/src/Framework/SystemCheck/SaleChannelsReadinessCheck.php), the core implementation has to be at least protected. I implement here an own provider to have it easier to redefine in the saas project.

### 2. What does this change do, exactly?
I moved the fetchSalesChannelDomains logic into an own provider and implemented an Entity and a Collection for the data transfer.

### 3. Describe each step to reproduce the issue or behaviour.
/ 

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfill them.

### CODE REVIEW

File: src/Storefront/Framework/SystemCheck/SalesChannelsReadinessCheck.php [hunk 1]
```diff
@@ -86,20 +85,4 @@ private function doRun(): Result
             $extra
         );
     }
-
-    /**
-     * @return array<string>
-     */
-    private function fetchSalesChannelDomains(): array
```
Comment (mitelg) [inline src/Storefront/Framework/SystemCheck/SalesChannelsReadinessCheck.php:93]: good, that we talked about this :grin: 

https://github.com/shopware/shopware/pull/9530#discussion_r2112036825

Comment (MartinKrzykawski) [reply src/Storefront/Framework/SystemCheck/SalesChannelsReadinessCheck.php:93]: :D

Comment (MartinKrzykawski) [reply src/Storefront/Framework/SystemCheck/SalesChannelsReadinessCheck.php:93]: as a seperated service it can be better redefined in saas 👍

File: src/Storefront/Framework/SystemCheck/Util/AbstractSalesChannelDomainProvider.php [hunk 2]
```diff
@@ -0,0 +1,17 @@
...
+use Shopware\Core\Framework\Log\Package;
+
+/**
+ * @internal
+ */
+#[Package('framework')]
+abstract class AbstractSalesChannelDomainProvider
+{
+    /**
+     * @return array<string, string>
```
Comment (mitelg) [inline src/Storefront/Framework/SystemCheck/Util/AbstractSalesChannelDomainProvider.php]: do we need to document, what this array should contain? unfortunately this annotation is not really descriptive what should be returned :slightly_smiling_face:

Comment (MartinKrzykawski) [reply src/Storefront/Framework/SystemCheck/Util/AbstractSalesChannelDomainProvider.php]: yes! what do you think about an array shape annotation?

Comment (MartinKrzykawski) [reply src/Storefront/Framework/SystemCheck/Util/AbstractSalesChannelDomainProvider.php]: hmm we have only a salesChannelId => url structure, so a array shape annotation is not enough

Comment (MartinKrzykawski) [reply src/Storefront/Framework/SystemCheck/Util/AbstractSalesChannelDomainProvider.php]: We could also use a DTO since we want to extend this service

Comment (mitelg) [reply src/Storefront/Framework/SystemCheck/Util/AbstractSalesChannelDomainProvider.php]: a list of associative arrays? if so, it could be a DTO then :grin: 

but if you want to keep the key-value structure, we can just add a comment above, which says what the key is and what the value is

Comment (MartinKrzykawski) [reply src/Storefront/Framework/SystemCheck/Util/AbstractSalesChannelDomainProvider.php]: i saw a wonderful presentation and i choose the DTO

File: src/Storefront/Framework/SystemCheck/Util/SalesChannelDomainCollection.php [hunk 3]
```diff
@@ -0,0 +1,29 @@
...
+    public function __construct(
+        array $elements,
+    ) {
+        $indexed = [];
+        foreach ($elements as $element) {
+            $indexed[$element->salesChannelId] = $element;
+        }
+
+        parent::__construct($indexed);
+    }
```
Comment (mitelg) [inline src/Storefront/Framework/SystemCheck/Util/SalesChannelDomainCollection.php:28]: if you want to validate your input, you can implement `getExpectedClass`

**Review by mitelg — APPROVED** [review]

File: src/Storefront/Framework/SystemCheck/Util/SalesChannelDomainCollection.php (hunk 3 above)
Comment (MartinKrzykawski) [reply src/Storefront/Framework/SystemCheck/Util/SalesChannelDomainCollection.php:28]: ah nice, added it 👍

File: src/Storefront/Framework/SystemCheck/Util/AbstractSalesChannelDomainProvider.php [hunk 4]
```diff
@@ -0,0 +1,14 @@
...
+
+namespace Shopware\Storefront\Framework\SystemCheck\Util;
+
+use Shopware\Core\Framework\Log\Package;
+
+/**
+ * @internal
+ */
+#[Package('framework')]
+abstract class AbstractSalesChannelDomainProvider
```
Comment (h1k3r) [inline src/Storefront/Framework/SystemCheck/Util/AbstractSalesChannelDomainProvider.php:11]: Is there any need for abstract class (it's still internal)?

**Review by h1k3r — APPROVED** [review]

File: src/Storefront/Framework/SystemCheck/Util/AbstractSalesChannelDomainProvider.php (hunk 4 above)
Comment (MartinKrzykawski) [reply src/Storefront/Framework/SystemCheck/Util/AbstractSalesChannelDomainProvider.php:11]: I was planning to decorate this provider in saas, and in my opinion, using an abstract class is the cleaner approach.

Oh, and I forgot to add the getDecorated method – I’ll commit it unless you have any objections to the use of the abstract class.

File: src/Storefront/Framework/SystemCheck/Util/AbstractSalesChannelDomainProvider.php [hunk 5]
```diff
@@ -0,0 +1,14 @@
...
+{
+    abstract public function fetchSalesChannelDomains(): SalesChannelDomainCollection;
```
Comment (MartinKrzykawski) [inline src/Storefront/Framework/SystemCheck/Util/AbstractSalesChannelDomainProvider.php:13]: getDecorated method is missing

File: src/Storefront/Framework/SystemCheck/Util/AbstractSalesChannelDomainProvider.php (hunk 4 above)
Comment (MartinKrzykawski) [reply src/Storefront/Framework/SystemCheck/Util/AbstractSalesChannelDomainProvider.php:11]: okay, it is not allowed to have a getDecorated method inside an internal class 🙈

File: src/Storefront/Framework/SystemCheck/Util/AbstractSalesChannelDomainProvider.php (hunk 5 above)
Comment (MartinKrzykawski) [reply src/Storefront/Framework/SystemCheck/Util/AbstractSalesChannelDomainProvider.php:13]: I will not add a getDecorated method because it is not allowed inside internal classes.

File: src/Storefront/Framework/SystemCheck/Util/AbstractSalesChannelDomainProvider.php (hunk 4 above)
Comment (h1k3r) [reply src/Storefront/Framework/SystemCheck/Util/AbstractSalesChannelDomainProvider.php:11]: And I do not see enough value in adding abstract class - normally we add them to open something for extension :)

Comment (MartinKrzykawski) [reply src/Storefront/Framework/SystemCheck/Util/AbstractSalesChannelDomainProvider.php:11]: In my opinion, it already provides enough value when the decorator knows which methods to expect. Without a required method defined by an abstract class, changes to the original method would go unnoticed – and the decorated method would then be treated as a standalone method, without any reference to the original one 🤔
