### PR TITLE
fix: Fix product slider with variants in closeout 

### LINKED ISSUE #5354: Product slider does not display product with variants
Description: 
If a product has variants and is selected in the product slider element it is not displayed if its stock is 0 and clearance sale is enabled. On the product listing page this behaves differently and displays the product with the image of a variant.
IMO if a product has variants it does not even make sense to set the stock for the product manually. You should only have to set the stock for the variants. 

Also if a dynamic product group is used, the maximum number of products seems to count products that are not displayed because they are out of stock or something like that. This causes the number of products to be lower than the max. even if there would be enough products in the product group.

Environment: 
Shopware 6.6.4.1

Steps to reproduce: 
Create product slider, select product with 0 stock but with variant that has stock > 0 and clearance sale enabled.

Expected result: 
Product gets displayed with the product image of a variant. Just like on the category page.

Actual result: 
Product is not displayed

### PR DESCRIPTION
**Pull request by lukasrump**
Fixes #5354

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have updated developer-facing release notes if this change is **relevant** for external developers:
  - Add a short entry to `RELEASE_INFO-6.<major>.md` under “Upcoming” for informational changes, including the consequences of the change and how it affects external developers.
  - Add an `UPGRADE` section in `UPGRADE-6.<next-major>.md` for breaking changes (what/why/impact/how to adapt).
  - See the [Release Notes & Changelog Process](https://github.com/shopware/shopware/blob/trunk/adr/2025-10-28-changelog-release-info-process.md) for details.
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Core/Content/Product/Cms/ProductSlider/StaticProductProcessor.php [hunk 1]
```diff
@@ -45,6 +45,7 @@ public function collect(CmsSlotEntity $slot, FieldConfigCollection $config, Reso
         $products = $config->get('products');
         \assert($products instanceof FieldConfig);
         $criteria = new Criteria($products->getArrayValue());
+        $criteria->addAssociation('children');
```
Comment (aragon999) [inline src/Core/Content/Product/Cms/ProductSlider/StaticProductProcessor.php]: This will probably have significant performance impact on large variant products, i.e. loading all variants of a product is not a good idea ;-)

In the case of the product detail page variant products are excluded in general from this filter: https://github.com/shopware/shopware/blob/1d4d4aa2c26a8f747aac60f4bef94883bd2022ef/src/Core/Content/Product/SalesChannel/Detail/ProductDetailRoute.php#L148-L154

Which should probably be done here as well.

Comment (tinect) [reply src/Core/Content/Product/Cms/ProductSlider/StaticProductProcessor.php]: As a shop owner with `just` 12.960 variants on a single product, I would not be happy.

**Review by marcelbrode — APPROVED** [review]

**Review by dgrothaus-sw — APPROVED** [review]
