### PR TITLE
fix: ensure import export profile technical names are generated

### LINKED ISSUE #10773: empty import_export_profile.technical_name  prevents update to 6.7.0.0
### Shopware Version

6.7.0.0

### Affected area / extension

Platform(Default)

### Actual behaviour

The update to 6.7.0.0 fails because one or more import/export profiles do not have a `technical_name` stored.

Internal Slack Chat: https://shopware-ag.slack.com/archives/C05QHLTM1TN/p1750770164743819

### Expected behaviour

A migration should generate technical names again in case there is none in the migration, before we drop the name column in `Migration1717572627RemoveImportExportProfileName` so the update process is bullet proof.

### How to reproduce

- create a new import export profile without a technical name
- update to 6.7.0.0

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by ennasus4sun**
**context:**
we introduce the new column `import_export_profile.technical_name` in this PR: https://gitlab.shopware.com/shopware/6/product/platform/-/merge_requests/13881 for Version 6.6.3.0 and generate the `technical_name` in the Migration (https://gitlab.shopware.com/shopware/6/product/platform/-/merge_requests/13881/diffs#089111fafdeb960ad48cc9b1e3df51075e24d095).

We create these Migrations for the update to 6.7.0.0:

- in [Migration1717572627RemoveImportExportProfileName](https://github.com/shopware/shopware/blob/v6.7.0.0/src/Core/Migration/V6_7/Migration1717572627RemoveImportExportProfileName.php) we remove the import_export_profile.name column
- in [Migration1717573310ImportExportTechnicalNameRequired](https://github.com/shopware/shopware/blob/v6.7.0.0/src/Core/Migration/V6_7/Migration1717573310ImportExportTechnicalNameRequired.php) we make import_export_profile.technical_name non nullable

**Problem**
As the column `import_export_profile.technical_name` wasn't required (nullable) until 6.7.0.0, it was still possible to create new profiles without a `technical_name`. As we do not generate new `technical_names` in the 6.7 Migrations, customers who do not have `technical_names` cannot perform the Update.

**Solution**
Before making the field required and non nullable and removing the `import_export_profile.name` column, we need to generate all technical names again in case there is none. This needs to be done before dropping the `name` column.

- closes #10773

### CODE REVIEW

File: tests/migration/Core/V6_7/Migration1717572627RemoveImportExportProfileNameTest.php [hunk 1]
```diff
@@ -42,6 +75,123 @@ public function testUpdateDestructiveRemovesColumn(): void
...
+                    'expected_technical_name' => 'unnamed_profile_1',
+                ],
+                [
+                    'uuid' => $uuid3,
+                    'name' => null,
+                    'technical_name' => null,
+                    'expected_technical_name' => 'unnamed_profile_2',
+                ],
+            ],
+        ];
```
Comment (ennasus4sun) [inline tests/migration/Core/V6_7/Migration1717572627RemoveImportExportProfileNameTest.php]: Iam not sure if it makes sense to also add a test which provides a name which is not unique like that

```
yield 'single profile with already existing name' => [
    [
        [
            'uuid' => $uuid1,
            'name' => 'Default product',
            'technical_name' => null,
            'expected_technical_name' => 'default_producs',
        ],
    ],
];
```
The `name` column wasn`t unique before. this is the table structure of the current 6.6.x:
```
import_export_profile | CREATE TABLE `import_export_profile` (
  `id` binary(16) NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `system_default` tinyint unsigned NOT NULL DEFAULT '0',
  `source_entity` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `file_type` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `delimiter` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `enclosure` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `type` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'import-export',
  `mapping` longtext COLLATE utf8mb4_unicode_ci,
  `update_by` json DEFAULT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `config` json DEFAULT NULL,
  `technical_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq.import_export_profile.technical_name` (`technical_name`),
  CONSTRAINT `json.import_export_profile.config` CHECK (json_valid(`config`))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
```

This test would fail ...

File: src/Core/Migration/V6_7/Migration1717572627RemoveImportExportProfileName.php [hunk 2]
```diff
@@ -19,10 +20,77 @@ public function getCreationTimestamp(): int
...
+        if (!$this->indexExists($connection, ImportExportProfileDefinition::ENTITY_NAME, 'uniq.import_export_profile.technical_name')) {
+            $connection->executeStatement('ALTER TABLE `import_export_profile` ADD CONSTRAINT `uniq.import_export_profile.technical_name` UNIQUE (`technical_name`)');
+        }
+
+        $names = $connection->executeQuery('SELECT id, name, technical_name FROM import_export_profile')->fetchAllAssociative();
+
+        $technicalNames = [];
+        foreach ($names as $name) {
+            if ($name['technical_name'] !== null) {
+                continue;
```
Comment (keulinho) [inline src/Core/Migration/V6_7/Migration1717572627RemoveImportExportProfileName.php]: can't we fetch the id and name where technical_name is null? 

No need to iterate over all entries, we can the DB handle that here

Comment (ennasus4sun) [reply src/Core/Migration/V6_7/Migration1717572627RemoveImportExportProfileName.php]: ~~I thought that too but I was not sure if this way is slower~~ I will do it 👍🏻

File: tests/migration/Core/V6_7/Migration1717572627RemoveImportExportProfileNameTest.php (hunk 1 above)
Comment (jozsefdamokos) [reply tests/migration/Core/V6_7/Migration1717572627RemoveImportExportProfileNameTest.php]: If the name was not unique before, generating technical names from the name should also handle that case, so it wouldnt generate the same technical name twice and then throw an error because it's not unique. And yes, a test would be nice to cover it too

Comment (keulinho) [reply tests/migration/Core/V6_7/Migration1717572627RemoveImportExportProfileNameTest.php]: IMHO that should work, we would need to fetch the existing technical names to check if they already exist

File: src/Core/Migration/V6_7/Migration1717572627RemoveImportExportProfileName.php [hunk 3]
```diff
@@ -19,10 +20,77 @@ public function getCreationTimestamp(): int
 
     public function update(Connection $connection): void
     {
+        if (!$this->columnExists($connection, 'import_export_profile', 'technical_name')) {
```
Comment (mitelg) [inline src/Core/Migration/V6_7/Migration1717572627RemoveImportExportProfileName.php]: can we add something to this already existing migration, now 6.7 is released? :thinking:

Comment (ennasus4sun) [reply src/Core/Migration/V6_7/Migration1717572627RemoveImportExportProfileName.php]: I think it is not possible to do this in another way. We need the `name` column to generate the `technical_names` which is dropped in this migration.
In my opinion, this should have no effect on migrations that have already been executed. All those that have gone through had no problems and should be at the same state as with this adjusted migration.

Comment (mitelg) [reply src/Core/Migration/V6_7/Migration1717572627RemoveImportExportProfileName.php]: if I understand it correctly, this is only a problem, once the column is set to not nullable and there are still null values in that column. 

shouldn't then the new logic here be moved into the other migration to ensure, that the column could be made not nullable?

Comment (ennasus4sun) [reply src/Core/Migration/V6_7/Migration1717572627RemoveImportExportProfileName.php]: ah, sorry, I misunderstood your concerns.
If the https://github.com/shopware/shopware/blob/v6.7.0.0/src/Core/Migration/V6_6/Migration1716196653AddTechnicalNameToImportExportProfile.php Migration was already executed, we may be able to remove the `columnExists` and the following `indexExists`-check and start with the query for `$names`.
I am not sure... @keulinho What do you think?

Comment (ennasus4sun) [reply src/Core/Migration/V6_7/Migration1717572627RemoveImportExportProfileName.php]: you mean here:  [Migration1717573310ImportExportTechnicalNameRequired](https://github.com/shopware/shopware/blob/v6.7.0.0/src/Core/Migration/V6_7/Migration1717573310ImportExportTechnicalNameRequired.php) ?
There we do not have the `name` column anymore and all `technical_names` will be generated to "unnamed_profile", "unnamed_profile_1", "unnamed_profile_2" and so on. 🤔

Comment (ennasus4sun) [reply src/Core/Migration/V6_7/Migration1717572627RemoveImportExportProfileName.php]: maybe this comment (internal Slack) helps: https://shopware-ag.slack.com/archives/C05QHLTM1TN/p1750772518632349?thread_ts=1750770164.743819&cid=C05QHLTM1TN

Comment (keulinho) [reply src/Core/Migration/V6_7/Migration1717572627RemoveImportExportProfileName.php]: for me it's ok to touch the existing migration in this case, it fixes a bug that prevented you from updating

when you were not affected you had no profiles without a technical name you are fine and don't need this fix, if you are affected you couldn't update

Comment (mitelg) [reply src/Core/Migration/V6_7/Migration1717572627RemoveImportExportProfileName.php]: but the destructive method is executed ~before~ after the normal update methods? :thinking: how could the column be already removed?

File: src/Core/Migration/V6_7/Migration1717572627RemoveImportExportProfileName.php [hunk 4]
```diff
@@ -19,10 +20,84 @@ public function getCreationTimestamp(): int
...
+        }
+
+        $names = $connection->executeQuery('SELECT id, name FROM import_export_profile WHERE technical_name IS NULL')->fetchAllAssociative();
+        $existingTechnicalNames = $connection->executeQuery('SELECT technical_name FROM import_export_profile WHERE technical_name IS NOT NULL')->fetchFirstColumn();
+
+        $technicalNames = [];
+        foreach ($names as $name) {
+            $technicalNames[] = [
+                'id' => $name['id'],
+                'technical_name' => $this->generateTechnicalName(
```
Comment (keulinho) [inline src/Core/Migration/V6_7/Migration1717572627RemoveImportExportProfileName.php]: we can add the technical name it generated to the `existingTechnicalNames` array and feed only that to the `generateTechnicalName` that way we do not have to look into the deep array structure and merge the two arrays

```php
$newName = $this->generate($name, $existingNames);
$existingNames[] = $newName;
$technicalNames[] = [... the structure you have]
```

File: src/Core/Migration/V6_7/Migration1717572627RemoveImportExportProfileName.php (hunk 3 above)
Comment (keulinho) [reply src/Core/Migration/V6_7/Migration1717572627RemoveImportExportProfileName.php]: i guess what you meant is that the `destructive` is only called after the update, totally correct we could move all the logic to the migration where we make it required then 

sorry for the confusion I didn't saw that the column was removed in a destructive migration 

BTW we also don't need to copy the logic that creates the column again

Comment (ennasus4sun) [reply src/Core/Migration/V6_7/Migration1717572627RemoveImportExportProfileName.php]: tested that with `init:testdb`:
image
I think this is the same like other migrations are executed.

Comment (mitelg) [reply src/Core/Migration/V6_7/Migration1717572627RemoveImportExportProfileName.php]: that's what I meant :grin: :+1:

Comment (ennasus4sun) [reply src/Core/Migration/V6_7/Migration1717572627RemoveImportExportProfileName.php]: mh 🤔, yes understand: the `name` column is still there in the next Migration [Migration1717573310ImportExportTechnicalNameRequired](https://github.com/shopware/shopware/blob/v6.7.0.0/src/Core/Migration/V6_7/Migration1717573310ImportExportTechnicalNameRequired.php).
So you think it`s better to move the "fix" into the next Migration for logical reason, right?

File: src/Core/Migration/V6_7/Migration1717572627RemoveImportExportProfileName.php (hunk 4 above)
Comment (ennasus4sun) [reply src/Core/Migration/V6_7/Migration1717572627RemoveImportExportProfileName.php]: beautiful, yes. I will try that.

File: src/Core/Migration/V6_7/Migration1717572627RemoveImportExportProfileName.php (hunk 3 above)
Comment (mitelg) [reply src/Core/Migration/V6_7/Migration1717572627RemoveImportExportProfileName.php]: yes, I would put the fix right before we make the technical name required

File: src/Core/Migration/V6_7/Migration1717573310ImportExportTechnicalNameRequired.php [hunk 5]
```diff
@@ -20,11 +20,71 @@ public function getCreationTimestamp(): int
...
+                ->executeStatement('ALTER TABLE `import_export_profile` MODIFY COLUMN `technical_name` VARCHAR(255) NOT NULL');
+        }
+    }
+
+    /**
+     * @param array<int, string> $existingTechnicalNames
+     */
+    private function generateTechnicalName(?string $name, array $existingTechnicalNames): string
+    {
+        $name = $name ?? 'Unnamed profile';
```
Comment (MalteJanz) [inline src/Core/Migration/V6_7/Migration1717573310ImportExportTechnicalNameRequired.php:65]: The `$name` could still be an empty string `''`right? Just in case I would add an additional check for that with the same fallback to `Unamed profile`. Something like
```php
if (empty(trim($name))) {
    $name = 'Unnamed profile';
}
```

File: tests/migration/Core/V6_7/Migration1717573310ImportExportTechnicalNameRequiredTest.php [hunk 6]
```diff
@@ -40,4 +64,126 @@ public function testMigrate(): void
...
+        ];
+
+        yield 'multiple profiles with null name and null technical_name' => [
+            [
+                [
+                    'uuid' => $uuid1,
+                    'name' => null,
+                    'technical_name' => null,
+                    'expected_technical_name' => 'unnamed_profile',
+                ],
```
Comment (MalteJanz) [inline tests/migration/Core/V6_7/Migration1717573310ImportExportTechnicalNameRequiredTest.php]: As described above, I would also add a case for an empty string `name` here, just to be extra sure the migration doesn't mess up.

**Review by MalteJanz — APPROVED** [review]
LGTM 👍 , only found one smaller nitpick to be extra sure the conversion from name to technical name is considering all possible cases.

**Review by mitelg — APPROVED** [review]

**Review by jozsefdamokos — APPROVED** [review]

**Review by MalteJanz — APPROVED** [review]
