### PR TITLE
fix: UpdatedByField not cleared on API changes

### LINKED ISSUE #11188: Incorrect "Last changed by" Info on Order Entity After API Updates
### Shopware Version

6.6.10

### Affected area / extension

Platform(Default)

### Actual behaviour

When the order is changed via API, a new version of the Order entity is not created, so the user attribution is not updated. However, the correct user/system info is recorded in the Status History, accessible from the Details tab.

### Expected behaviour

When the order is changed via API, a new version of the Order entity is not created, so the user attribution is not updated. However, the correct user/system info is recorded in the Status History, accessible from the Details tab.

### How to reproduce

March 3, 2025: User John Doe manually updated the order.

March 4, 2025: Order was cancelled via an external system (SN) using the API.
→ Result: The order shows the last change as:
Last changed: 03/04/2025, 04:02 PM by John Doe
However, John did not perform this action. This is misleading for order tracking and accountability.

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by mstegmeyer**
### 1. Why is this change necessary?
When updating an order via API, there is obviously no user id present in the context. Currently, any `UpdatedByField` does not get changed, if no user id is present. But the state of the field is then untrue, because the latest change is actually done via the API.

### 2. What does this change do, exactly?
From 6.8 on, these fields get set to null, if an API does a change, reflecting the correct last update, just like the `UpdatedAtField` does.

### 3. Describe each step to reproduce the issue or behaviour.
- Change an existing order via the administration, so it shows `last edited by XYZ`
- Do a change via API, e.g. a state machine change
- It should show no user name from 6.8 on.

### 4. Please link to the relevant issues (if any).
fixes #11188 

### 5. Checklist

- [X] I have written tests and verified that they fail without my change
- [X] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [X] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: tests/unit/Core/Framework/DataAbstractionLayer/FieldSerializer/UpdatedByFieldSerializerTest.php [hunk 1]
```diff
@@ -0,0 +1,231 @@
...
+
+        static::assertEmpty($result);
+    }
+
+    /**
+     * @deprecated tag:v6.8.0 - remove this test, as the behavior will be removed
+     */
+    public function testEncodeWithNoUserIdDeprecated(): void
+    {
+        Feature::skipTestIfActive('v6.8.0.0', $this);
```
Comment (cyl3x) [inline tests/unit/Core/Framework/DataAbstractionLayer/FieldSerializer/UpdatedByFieldSerializerTest.php]: can you use `#[DisabledFeatures(['v6.8.0.0'])]` instead?

Comment (mstegmeyer) [reply tests/unit/Core/Framework/DataAbstractionLayer/FieldSerializer/UpdatedByFieldSerializerTest.php]: yes, whoops, mixed up unit and integration annotations.

**Review by cyl3x — APPROVED** [review]

**Review by mitelg — APPROVED** [review]
