### PR TITLE
fix: promotion deletion cart error

### LINKED ISSUE #8285: Weird notifications in order module
### Shopware Version

trunk

### Affected area / extension

Platform(Default)

### Actual behaviour

If you add a credit item to an order two notifications appear:

Image

The error states:
"status": "500",
"code": "FRAMEWORK__INVALID_PRICE_FIELD_TYPE",
Although the price calculation apparently went well.

The info message does not make any sense at all.

### Expected behaviour

No error messages and no info about promotions should appear.

### How to reproduce

Open existing order
Add credit item
Save order

### PR DESCRIPTION
**Pull request by cyl3x**
### 1. Why is this change necessary?
Adding a credit line item to an existing order results in a promotion deleted notification

### 2. What does this change do, exactly?
The line items used for finding removed promotions missed a line item type filter step.

### 3. Describe each step to reproduce the issue or behaviour.
- Open existing order
- Add/Edit credit item

### 4. Please link to the relevant issues (if any).

fixes #8285

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfill them.

### CODE REVIEW

**Review by En0Ma1259 — APPROVED** [review]

**Review by Bird87ZA — APPROVED** [review]

File: src/Core/Checkout/Promotion/Cart/PromotionCollector.php [hunk 1]
```diff
@@ -170,7 +170,10 @@ public function collect(CartDataCollection $data, Cart $original, SalesChannelCo
             // when being in a recalculation, having notifications about the removal of automatic promotion is desired
             // addition notifications are handled as usual in the PromotionCalculator
             if ($behavior->isRecalculation()) {
-                $oldPromotions = $original->getLineItems()->filter(static fn (LineItem $item) => !$item->getReferencedId())->getElements();
+                $oldPromotions = $original->getLineItems()
+                    ->filterType(PromotionProcessor::LINE_ITEM_TYPE)
+                    ->filter(static fn (LineItem $item) => !$item->getReferencedId())
```
Comment (mstegmeyer) [inline src/Core/Checkout/Promotion/Cart/PromotionCollector.php]: I would filter this in one function. Every filter creates a new collection, seems overly resource intensive.

**Review by mstegmeyer — CHANGES_REQUESTED** [review]

**Review by mstegmeyer — APPROVED** [review]

**Review by lernhart — APPROVED** [review]
