### PR TITLE
fix: product media import with whitespace in url

### LINKED ISSUE #5868: Import error on webp images
When using the Import/Export function to import a product with product images that have the webp-Format, the import will fail with the error “Invalid media url”

Steps to reproduce:

* Create product with at least 1 webp image
* Export that product using the default product profile
* Select the unmodified file for import and start a dry run
* The import will fail

Example error CSV attached

Both 6.6.9.0 and 6.5.8.15 are affected

[^Standardprofil Produkt_20241217-075116.csv] 

[^Standardprofil Produkt_20241217-075116_failed.csv]

### PR DESCRIPTION
**Pull request by philippdinkhoff**
### 1. Why is this change necessary?
When a product has a cover image that is named with an whitespace ("My Example.png") then the import will fail.

### 2. What does this change do, exactly?
It alters the URL in the MediaSerializer so it replaces the whitespace with the encoding "%20".

### 3. Describe each step to reproduce the issue or behaviour.
    - Create product with an cover that has a whitespace in its name
    - Export that product using the default product profile
    - Select the unmodified file for import and start a dry run
    - The import will fail

### 4. Please link to the relevant issues (if any).
- Jira issue: https://shopware.atlassian.net/browse/NEXT-40069

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfill them.

### CODE REVIEW

File: src/Core/Content/ImportExport/DataAbstractionLayer/Serializer/Entity/MediaSerializer.php [hunk 1]
```diff
@@ -63,6 +63,8 @@ public function deserialize(Config $config, EntityDefinition $definition, $entit
             return $deserialized;
         }
 
+        $url = str_replace(' ', '%20', $url);
```
Comment (ennasus4sun) [inline src/Core/Content/ImportExport/DataAbstractionLayer/Serializer/Entity/MediaSerializer.php]: the PHP's built-in urlencode() or rawurlencode() functions did not work? If they would work, I think I would use one of them....

Comment (philippdinkhoff) [reply src/Core/Content/ImportExport/DataAbstractionLayer/Serializer/Entity/MediaSerializer.php]: Yeah, the `filter_var($url, \FILTER_VALIDATE_URL)` function does not recognize the fully encoded URL as valid. So my approach would be to only encode the whitespaces "manually" with the str_replace.

Comment (ennasus4sun) [reply src/Core/Content/ImportExport/DataAbstractionLayer/Serializer/Entity/MediaSerializer.php]: OK ...

**Review by ennasus4sun — APPROVED** [review]

**Review by DennisGarding — APPROVED** [review]

File: src/Core/Content/ImportExport/DataAbstractionLayer/Serializer/Entity/MediaSerializer.php (hunk 1 above)
Comment (MalteJanz) [inline src/Core/Content/ImportExport/DataAbstractionLayer/Serializer/Entity/MediaSerializer.php]: As far as I can see this isn't an issue with the import. It expects valid urls, see line below
```php

filter_var($url, \FILTER_VALIDATE_URL)
```

It should correctly report errors if the CSV contains invalid URLs.


I think the error is either in the export code, that is doesn't export valid URLs for the media files, or in the media file URL generation in general.


And after quickly testing it, it looks like if you upload a media file with `My image.jpg` and click `copy link` you get:
```
http://platform.localhost/media/90/6a/15/1735806912/My Image.jpg?ts=1735806912
```
Which isn't a valid URL. Same if you hover over the `download` button. It only works because the browser (in my case Chrome) applies some magic and tries to fix the url by himself. After pasting that in the browser you will get a valid one:
```
http://platform.localhost/media/90/6a/15/1735806912/My%20Image.jpg?ts=1735806912
```

We should instead fix the URL generation to properly encode the filename in my POV.

Also this fix is very short sighted, as other special characters that aren't properly URL encoded would still fail

**Review by MalteJanz — CHANGES_REQUESTED** [review]

**Review by ennasus4sun — COMMENTED** [review]
could we add a test? maybe here: tests/unit/Core/Content/Media/Infrastructure/Path/MediaUrlGeneratorTest.php

File: tests/unit/Storefront/Framework/Twig/Extension/UrlEncodingTwigFilterTest.php [hunk 2]
```diff
@@ -112,6 +112,6 @@ public function testItEncodesTheUrl(): void
 
         $media->setUrl((string) $url);
 
-        static::assertStringEndsWith('%28image%20with%20spaces%20and%20brackets%29.png', (string) $filter->encodeMediaUrl($media));
+        static::assertStringEndsWith('%2528image%2520with%2520spaces%2520and%2520brackets%2529.png', (string) $filter->encodeMediaUrl($media));
```
Comment (mitelg) [inline tests/unit/Storefront/Framework/Twig/Extension/UrlEncodingTwigFilterTest.php]: that looks strange. why is the encoding doubled?

Comment (philippdinkhoff) [reply tests/unit/Storefront/Framework/Twig/Extension/UrlEncodingTwigFilterTest.php]: Yup, double encoded, forgot to remove. Was testing, since the MediaUrlGenerator would already encode the URL the test would fail. 
Can the generated URL in this test just be replaced with a string?

Comment (mitelg) [reply tests/unit/Storefront/Framework/Twig/Extension/UrlEncodingTwigFilterTest.php]: I don't know what should be tested here :see_no_evil:

Comment (MalteJanz) [reply tests/unit/Storefront/Framework/Twig/Extension/UrlEncodingTwigFilterTest.php]: Mh 🤔  if every media entity now has a correctly encoded URL already (because of the change in `MediaUrlGenerator`) you might also need to change the implementation of this `UrlEncodingTwigFilter::encodeMediaUrl` method to not double encode.

File: src/Core/Content/Media/Infrastructure/Path/MediaUrlGenerator.php [hunk 3]
```diff
@@ -26,7 +26,10 @@ public function generate(array $paths): array
             if (str_starts_with($value->path, 'http')) {
                 $url = $value->path;
             } else {
-                $url = $this->filesystem->publicUrl($value->path);
```
Comment (MalteJanz) [inline src/Core/Content/Media/Infrastructure/Path/MediaUrlGenerator.php:29]: When is this `MediaUrlGenerator` called? Are these generated URL stored somewhere or generated on demand?

If they are stored we might need to trigger a regeneration of all of them 🤔

File: tests/unit/Storefront/Framework/Twig/Extension/UrlEncodingTwigFilterTest.php (hunk 2 above)
Comment (MartinKrzykawski) [reply tests/unit/Storefront/Framework/Twig/Extension/UrlEncodingTwigFilterTest.php]: This test should behave as before. The fact that the values are encoded twice is not correct in my opinion.

File: src/Administration/Resources/app/administration/src/app/asyncComponent/media/sw-media-preview-v2/sw-media-preview-v2.spec.js [hunk 4]
```diff
@@ -229,4 +229,44 @@ describe('src/app/asyncComponent/media/sw-media-preview-v2', () => {
...
+            trueSource: {
+                thumbnails: [
+                    { url: 'https://example.com/image1.jpg', width: 200 },
+                    { url: 'https://example.com/image2.jpg', width: 400 },
+                ],
+            },
+        });
+        expect(wrapper.vm.sourceSet).toBe('https://example.com/image1.jpg 200w, https://example.com/image2.jpg 400w');
+    });
+    it('should return an empty string if trueSource is a file', async () => {
```
Comment (marcelbrode) [inline src/Administration/Resources/app/administration/src/app/asyncComponent/media/sw-media-preview-v2/sw-media-preview-v2.spec.js]:
```suggestion
    });

    it('should return an empty string if trueSource is a file', async () => {
```

File: src/Administration/Resources/app/administration/src/app/asyncComponent/media/sw-media-preview-v2/sw-media-preview-v2.spec.js [hunk 5]
```diff
@@ -229,4 +229,44 @@ describe('src/app/asyncComponent/media/sw-media-preview-v2', () => {
...
+        const wrapper = await createWrapper();
+        const trueSource = new File([''], 'example.jpg', { type: 'image/jpg' });
+        trueSource.thumbnails = [];
+        await wrapper.setData({
+            trueSource: trueSource,
```
Comment (marcelbrode) [inline src/Administration/Resources/app/administration/src/app/asyncComponent/media/sw-media-preview-v2/sw-media-preview-v2.spec.js]:
```suggestion
            trueSource,
```
Shorthand. Test case underneath as well

File: src/Administration/Resources/app/administration/src/app/asyncComponent/media/sw-media-preview-v2/sw-media-preview-v2.spec.js [hunk 6]
```diff
@@ -229,4 +229,44 @@ describe('src/app/asyncComponent/media/sw-media-preview-v2', () => {
...
+
+    it('should return an empty string if trueSource is a URL', async () => {
+        const wrapper = await createWrapper();
+        const trueSource = new URL('https://example.com/image.jpg');
+        trueSource.thumbnails = [];
+        await wrapper.setData({
+            trueSource: trueSource,
+        });
+        expect(wrapper.vm.sourceSet).toBe('');
+    });
```
Comment (marcelbrode) [inline src/Administration/Resources/app/administration/src/app/asyncComponent/media/sw-media-preview-v2/sw-media-preview-v2.spec.js]: This and above could enjoy some empty lines. Would Improves readablity.

File: src/Administration/Resources/app/administration/src/app/asyncComponent/media/sw-media-preview-v2/sw-media-preview-v2.spec.js [hunk 7]
```diff
@@ -229,4 +229,44 @@ describe('src/app/asyncComponent/media/sw-media-preview-v2', () => {
 
         expect(wrapper.vm.previewUrl).toEqual(wrapper.vm.source);
     });
+
```
Comment (marcelbrode) [inline src/Administration/Resources/app/administration/src/app/asyncComponent/media/sw-media-preview-v2/sw-media-preview-v2.spec.js]: Have you thought about a dataprovider, since all testcases are doing the same testing?

File: src/Core/Content/Media/Infrastructure/Path/MediaUrlGenerator.php [hunk 8]
```diff
@@ -26,7 +26,10 @@ public function generate(array $paths): array
...
+                $pathInfo = pathinfo($value->path);
+                $encodedFilename = rawurlencode($pathInfo['basename']);
+                $encodedPath = ($pathInfo['dirname'] ?? '') . '/' . $encodedFilename;
```
Comment (marcelbrode) [inline src/Core/Content/Media/Infrastructure/Path/MediaUrlGenerator.php]:
```suggestion
                $encodedPath = \sprintf('%s/%s', $pathInfo['dirname'] ?? '', $encodedFilename);
```
I personally think that sprintf is always a bit more clean than native concatination

File: src/Core/Migration/V6_6/Migration1739348080.php [hunk 9]
```diff
@@ -0,0 +1,49 @@
...
+use Shopware\Core\Content\Media\Core\Application\MediaUrlLoader;
+use Shopware\Core\Framework\Context;
+use Shopware\Core\Framework\DataAbstractionLayer\Search\Criteria;
+use Shopware\Core\Framework\Log\Package;
+use Shopware\Core\Framework\Migration\MigrationStep;
+
+/**
+ * @internal
+ */
+#[Package('core')]
```
Comment (marcelbrode) [inline src/Core/Migration/V6_6/Migration1739348080.php]: Adjust package

File: src/Core/Migration/V6_6/Migration1739348080.php [hunk 10]
```diff
@@ -0,0 +1,49 @@
...
+{
+    public function getCreationTimestamp(): int
+    {
+        return 1739348080;
+    }
+
+    public function update(Connection $connection): void
+    {
+        //Work in progress
+        //TODO Finish migration
```
Comment (marcelbrode) [inline src/Core/Migration/V6_6/Migration1739348080.php]: Oh, well. Didn't know you aren't finished.

**Review by marcelbrode — CHANGES_REQUESTED** [review]

File: src/Storefront/Framework/Twig/Extension/UrlEncodingTwigFilter.php [hunk 11]
```diff
@@ -65,7 +66,9 @@ public function encodeMediaUrl(?MediaEntity $media): ?string
         if ($media === null || !$media->hasFile()) {
             return null;
         }
-
+        if (!Feature::isActive('v6.7.0.0')) {
```
Comment (marcelbrode) [inline src/Storefront/Framework/Twig/Extension/UrlEncodingTwigFilter.php]: This is a 6.7 branch. You shouldn't add more flags

File: src/Core/Content/ImportExport/DataAbstractionLayer/Serializer/Entity/MediaSerializer.php [hunk 12]
```diff
@@ -112,6 +113,21 @@ public function deserialize(Config $config, EntityDefinition $definition, $entit
...
+        if ($entity instanceof \Traversable) {
+            $entity = iterator_to_array($entity);
+        }
+
+        if (isset($entity['url'])) {
+            $urlEncodingTwig = new UrlEncodingTwigFilter();
+            $entity['url'] = $urlEncodingTwig->encodeUrl($entity['url']);
+        }
+
+        yield from parent::serialize($config, $definition, $entity);
```
Comment (mitelg) [inline src/Core/Content/ImportExport/DataAbstractionLayer/Serializer/Entity/MediaSerializer.php]: why do you need to yield two times?

**Review by marcelbrode — APPROVED** [review]

File: src/Core/Content/ImportExport/DataAbstractionLayer/Serializer/Entity/MediaSerializer.php [hunk 13]
```diff
@@ -113,20 +113,6 @@ public function deserialize(Config $config, EntityDefinition $definition, $entit
         return $deserialized;
     }
 
-    public function serialize(Config $config, EntityDefinition $definition, $entity): iterable
```
Comment (marcelbrode) [inline src/Core/Content/ImportExport/DataAbstractionLayer/Serializer/Entity/MediaSerializer.php]: You can't just remove public functions. You have to deprecate it first

File: src/Core/Content/Media/Infrastructure/Path/MediaUrlGenerator.php [hunk 14]
```diff
@@ -33,9 +33,48 @@ public function generate(array $paths): array
...
-            $urls[$key] = $url;
+            $urls[$key] = $this->encodeUrl($url);
         }
 
         return $urls;
     }
+
+    private function encodeUrl(string $mediaUrl): ?string
+    {
+        if ($mediaUrl === null) {
```
Comment (marcelbrode) [inline src/Core/Content/Media/Infrastructure/Path/MediaUrlGenerator.php]: This will never ber true

File: src/Core/Content/Media/Infrastructure/Path/MediaUrlGenerator.php [hunk 15]
```diff
@@ -33,9 +33,48 @@ public function generate(array $paths): array
...
+            return null;
```
Comment (marcelbrode) [inline src/Core/Content/Media/Infrastructure/Path/MediaUrlGenerator.php]: Please think about cover those two cases please :)

**Review by marcelbrode — DISMISSED** [review]

File: src/Administration/Resources/app/administration/src/app/asyncComponent/media/sw-media-preview-v2/sw-media-preview-v2.spec.js [hunk 16]
```diff
@@ -226,4 +226,49 @@ describe('src/app/asyncComponent/media/sw-media-preview-v2', () => {
...
+        const wrapper = await createWrapper();
+        const trueSource = new File([''], 'example.jpg', { type: 'image/jpg' });
+        trueSource.thumbnails = [];
+
+        await wrapper.setData({ trueSource });
+
+        expect(wrapper.vm.sourceSet).toBe('');
+    });
+
+    it('should return an empty string if trueSource is a URL', async () => {
```
Comment (ennasus4sun) [inline src/Administration/Resources/app/administration/src/app/asyncComponent/media/sw-media-preview-v2/sw-media-preview-v2.spec.js]: just because you have to adjust some things again anyway:
```suggestion
    it('should return an empty string if trueSource is an URL', async () => {
```

Comment (marcelbrode) [reply src/Administration/Resources/app/administration/src/app/asyncComponent/media/sw-media-preview-v2/sw-media-preview-v2.spec.js]: Please don't. URL starts with a "Yu" sound, which is why "a URL" is correct.

Comment (ennasus4sun) [reply src/Administration/Resources/app/administration/src/app/asyncComponent/media/sw-media-preview-v2/sw-media-preview-v2.spec.js]: I checked this right at the moment. sorry 😅

Comment (marcelbrode) [reply src/Administration/Resources/app/administration/src/app/asyncComponent/media/sw-media-preview-v2/sw-media-preview-v2.spec.js]: no worries 😄

File: src/Core/Content/Media/Infrastructure/Path/MediaUrlGenerator.php [hunk 17]
```diff
@@ -33,9 +33,45 @@ public function generate(array $paths): array
...
+
+        if (isset($urlInfo['scheme'])) {
+            $encodedPath = "{$urlInfo['scheme']}://";
+        }
+
+        if (isset($urlInfo['host'])) {
+            $encodedPath .= "{$urlInfo['host']}";
+        }
+
+        if (isset($urlInfo['port'])) {
```
Comment (marcelbrode) [inline src/Core/Content/Media/Infrastructure/Path/MediaUrlGenerator.php]: Maybe I am missing something, but is it possible to have a port without a host? And will the result still be valid?

File: src/Core/Content/Media/Infrastructure/Path/MediaUrlGenerator.php [hunk 18]
```diff
@@ -33,9 +33,45 @@ public function generate(array $paths): array
                 $url .= '?ts=' . $value->updatedAt->getTimestamp();
             }
 
-            $urls[$key] = $url;
+            $urls[$key] = $this->encodeUrl($url);
```
Comment (MalteJanz) [inline src/Core/Content/Media/Infrastructure/Path/MediaUrlGenerator.php]: Just curious: why is the encoding handled here and not in the else branch above (line 29) where the url is constructed from a file path?

File: src/Storefront/Framework/Twig/Extension/UrlEncodingTwigFilter.php [hunk 19]
```diff
@@ -65,6 +66,9 @@ public function encodeMediaUrl(?MediaEntity $media): ?string
         if ($media === null || !$media->hasFile()) {
             return null;
         }
+        if (!Feature::isActive('v6.8.0')) {
+            return $media->getUrl();
+        }
 
         return $this->encodeUrl($media->getUrl());
```
Comment (MalteJanz) [inline src/Storefront/Framework/Twig/Extension/UrlEncodingTwigFilter.php]: What's the reason for the feature toggle just in this place? Also why should it be encoded again in `6.8`? 🤔

**Review by MalteJanz — CHANGES_REQUESTED** [review]

File: src/Core/Content/Media/Infrastructure/Path/MediaUrlGenerator.php (hunk 3 above)
Comment (MalteJanz) [reply src/Core/Content/Media/Infrastructure/Path/MediaUrlGenerator.php:29]: What was the answer to this question?

File: src/Core/Content/Media/Infrastructure/Path/MediaUrlGenerator.php [hunk 20]
```diff
@@ -38,4 +40,43 @@ public function generate(array $paths): array
 
         return $urls;
     }
+
+    private function encodeUrl(string $mediaUrl): string
+    {
+        if (!Feature::isActive('v6.8.0.0')) {
+            return $mediaUrl;
```
Comment (MalteJanz) [inline src/Core/Content/Media/Infrastructure/Path/MediaUrlGenerator.php]: You should add a changelog that explains this break for 6.8

File: src/Storefront/Framework/Twig/Extension/UrlEncodingTwigFilter.php [hunk 21]
```diff
@@ -65,6 +66,9 @@ public function encodeMediaUrl(?MediaEntity $media): ?string
         if ($media === null || !$media->hasFile()) {
             return null;
         }
+        if (Feature::isActive('v6.8.0.0')) {
+            return $media->getUrl();
+        }
 
         return $this->encodeUrl($media->getUrl());
```
Comment (MalteJanz) [inline src/Storefront/Framework/Twig/Extension/UrlEncodingTwigFilter.php]: Small nitpick: its better to invert this if so for the 6.8 major deprecation removal we can just remove the if

File: tests/unit/Core/Content/Media/Infrastructure/Path/MediaUrlGeneratorTest.php [hunk 22]
```diff
@@ -27,6 +28,25 @@ public function testGenerate(UrlParams $params, ?string $expected): void
             new Filesystem(new InMemoryFilesystemAdapter(), ['public_url' => 'http://localhost:8000']),
         );
 
+        if (Feature::isActive('v6.8.0.0') && $expected !== null) {
```
Comment (MalteJanz) [inline tests/unit/Core/Content/Media/Infrastructure/Path/MediaUrlGeneratorTest.php]: Also here: the feature check should be in it's own if to make it clear what needs to be removed here. Have you seen the best practices message in slack about deprecations? Might be a good read 🙂 
https://shopware-ag.slack.com/archives/CBD3SQCMC/p1739884109134679

File: tests/unit/Core/Content/Media/Infrastructure/Path/MediaUrlGeneratorTest.php [hunk 23]
```diff
@@ -27,6 +28,25 @@ public function testGenerate(UrlParams $params, ?string $expected): void
...
+            if (isset($urlParts['path'])) {
+                $pathSegments = explode('/', $urlParts['path']);
+                $lastSegment = array_pop($pathSegments);
+                $lastSegment = rawurlencode($lastSegment);
+                $pathSegments[] = $lastSegment;
+
+                $urlParts['path'] = implode('/', $pathSegments);
+            }
+
+            $expected = $this->buildUrl($urlParts);
```
Comment (MalteJanz) [inline tests/unit/Core/Content/Media/Infrastructure/Path/MediaUrlGeneratorTest.php]: What's the reason you change (encode) the `$expected` value like this for 6.8? It should be enough to change the expected values in the dataProvider `generateProvider` to be properly url encoded

File: tests/unit/Core/Content/Media/Infrastructure/Path/MediaUrlGeneratorTest.php [hunk 24]
```diff
@@ -62,5 +82,37 @@ public static function generateProvider(): \Generator
             new UrlParams('id', UrlParamsSource::MEDIA, 'https://test.com/photo/flower.jpg', null),
             'https://test.com/photo/flower.jpg',
         ];
+
+        yield 'Test with whitespaces in path' => [
+            new UrlParams('id', UrlParamsSource::MEDIA, 'media/foo/3a/test file.jpg', null),
+            Feature::isActive('v6.8.0.0')
+                ? 'http://localhost:8000/media/foo/3a/test%20file.jpg'
+                : 'http://localhost:8000/media/foo/3a/test file.jpg',
```
Comment (MalteJanz) [inline tests/unit/Core/Content/Media/Infrastructure/Path/MediaUrlGeneratorTest.php]: Like you already do here, so I don't think all the magic is needed or did I miss something? 🙈

File: src/Administration/Resources/app/administration/src/app/asyncComponent/media/sw-media-preview-v2/index.js [hunk 25]
```diff
@@ -287,8 +287,8 @@ export default {
             this.trueSource.thumbnails.forEach((thumbnail) => {
                 const url = thumbnail.url;
 
-                const encoded = encodeURI(url);
-                sources.push(`${encoded} ${thumbnail.width}w`);
+
+                sources.push(`${url} ${thumbnail.width}w`);
```
Comment (MalteJanz) [inline src/Administration/Resources/app/administration/src/app/asyncComponent/media/sw-media-preview-v2/index.js]: If the backend change is only behind a major flag, this should be as well

**Review by MalteJanz — DISMISSED** [review]

File: src/Administration/Resources/app/administration/src/app/asyncComponent/media/sw-media-preview-v2/index.js (hunk 25 above)
Comment (philippdinkhoff) [reply src/Administration/Resources/app/administration/src/app/asyncComponent/media/sw-media-preview-v2/index.js]: I think this one is a bug, the "added" part is what was normally there, see: 
https://github.com/shopware/shopware/blob/5bec5f6c418b8a4ed61f96681916be3820a24c37/src/Administration/Resources/app/administration/src/app/asyncComponent/media/sw-media-preview-v2/index.js#L291

Comment (MalteJanz) [reply src/Administration/Resources/app/administration/src/app/asyncComponent/media/sw-media-preview-v2/index.js]: Can you explain a bit further what you mean? In `trunk` it looks like this right now (includes the `encodeURI` call):
https://github.com/shopware/shopware/blob/trunk/src/Administration/Resources/app/administration/src/app/asyncComponent/media/sw-media-preview-v2/index.js#L290-L291

Comment (philippdinkhoff) [reply src/Administration/Resources/app/administration/src/app/asyncComponent/media/sw-media-preview-v2/index.js]: Ah, I got confused by a different change. Yeah, i will put a feature flag in.

File: src/Core/Content/Media/Infrastructure/Path/MediaUrlGenerator.php (hunk 3 above)
Comment (philippdinkhoff) [reply src/Core/Content/Media/Infrastructure/Path/MediaUrlGenerator.php:29]: As of my testing these are generated on demand. Used when loading media thumbnails etc. (taking the media-path and then generating an URL)

File: changelog/_unreleased/2025-04-04-fix-product-media-import-with-whitespace-in-url.md [hunk 26]
```diff
@@ -0,0 +1,16 @@
+---
+title: fix product media import with whitespace in url
+issue: 5868
+author: p.dinkhoff
+author_email: p.dinkhoff@shopware.com
+author_github: @p.dinkhoff
+---
+# Core
+* Changed: URLs generated by the `MediaUrlGenerator` now encode whitespaces as `%20` in version `v6.8.0.0`. This ensures valid URLs in media and Import/Export operations.
```
Comment (MalteJanz) [inline changelog/_unreleased/2025-04-04-fix-product-media-import-with-whitespace-in-url.md]:
```suggestion
* Changed: URLs generated by the `MediaUrlGenerator` will properly encode the file path to produce valid URLs in version `v6.8.0.0` (e.g. replace whitespaces as `%20`). The current implementation relies on the caller to do proper URL encoding with the returned string.
```

Comment (MalteJanz) [reply changelog/_unreleased/2025-04-04-fix-product-media-import-with-whitespace-in-url.md]: Regarding:
> This ensures valid URLs in media and Import/Export operations.

What about implementing a workaround for that, like all the other places in 6.7 we could manually encode the URLs for now by calling the proper method / service and stop doing that for 6.8

File: changelog/_unreleased/2025-04-04-fix-product-media-import-with-whitespace-in-url.md [hunk 27]
```diff
@@ -0,0 +1,16 @@
...
+___
+# Next Major Version Changes
+## Breaking Change 1:
+* Changed: Whitespace characters (`' '`) in Media URLs will now be URL-encoded as `%20`.
+
+## Breaking Change 2:
+* Changed: Method `encodeUrl` in `Core/Content/Media/Infrastructure/Path/MediaUrlGenerator.php` will now return the URL in its already encoded form.
```
Comment (MalteJanz) [inline changelog/_unreleased/2025-04-04-fix-product-media-import-with-whitespace-in-url.md]:
```suggestion
## Changed URL generation of `MediaUrlGenerator` to properly encode the file path to produce valid URLs
* For example media files with spaces in their name now should be properly URL-encoded with `%20` by default, without doing URL-encoding only with the return value of the `MediaUrlGenerator`. Make sure to remove extra URL-encoding (e.g. usage of twig filter `encodeUrl`) on media entities to not accidentally double encode the URLs.
* Changed twig filter `encodeMediaUrl` in `Storefront/Framework/Twig/Extension/UrlEncodingTwigFilter.php` will now return the URL in its already encoded form and is basically the same as `$media->getUrl()` with some extra checks.
```

**Review by MalteJanz — DISMISSED** [review]
@GitEvil Might be worth doing some more testing with the `6.8` feature active  on this (current `trunk` / `6.7` should stay the same). Idk if you did a demo here?, e.g. : 
- upload a media file with spaces in the name
- use that in all possible places and check that it correctly displays (including storefront)
  - Just to make sure we didn't miss some spot and accidentelly double encode, which might led to a broken URL of the media file.

File: changelog/_unreleased/2025-04-04-fix-product-media-import-with-whitespace-in-url.md (hunk 26 above)
Comment (marcelbrode) [reply changelog/_unreleased/2025-04-04-fix-product-media-import-with-whitespace-in-url.md]: I personally would not enter the way it was before that. That can be confusing, while reading the changelog.

File: changelog/_unreleased/2025-04-04-fix-product-media-import-with-whitespace-in-url.md (hunk 27 above)
Comment (marcelbrode) [reply changelog/_unreleased/2025-04-04-fix-product-media-import-with-whitespace-in-url.md]: I heard we want to get rid of those changelog files entirely and BCs and Major changes should be put into the `UPGRADE-6.7.md` or `UPGRADE-6.8.md` directly.

**Review by marcelbrode — DISMISSED** [review]
.

**Review by mitelg — APPROVED** [review]

File: src/Core/Content/Media/Infrastructure/Path/MediaUrlGenerator.php [hunk 28]
```diff
@@ -38,4 +40,43 @@ public function generate(array $paths): array
...
+
+        $segments = explode('/', $urlInfo['path'] ?? '');
+
+        foreach ($segments as $index => $segment) {
+            $segments[$index] = rawurlencode($segment);
+        }
+
+        $path = implode('/', $segments);
+        if (isset($urlInfo['query'])) {
+            $path .= "?{$urlInfo['query']}";
```
Comment (ennasus4sun) [inline src/Core/Content/Media/Infrastructure/Path/MediaUrlGenerator.php]: I think, these 2 cases can be easily included in your test with a DataProvider....

**Review by ennasus4sun — APPROVED** [review]

File: UPGRADE-6.8.md [hunk 29]
```diff
@@ -153,6 +153,11 @@ Get the first order delivery with `primaryOrderDelivery` so you should replace m
 ## Use `primaryOrderTransaction`
 Get the latest order transaction with `primaryOrderTransaction` so you should replace methods like `transaction.last()`
 
+## Changed URL generation in MediaUrlGenerator to properly encode file paths
+* Media URLs with whitespace or other special characters in the filename will now be correctly URL-encoded (e.g. spaces replaced by `%20`).
+* This change is behind the feature flag `v6.8.0.0`.
```
Comment (MalteJanz) [inline UPGRADE-6.8.md]: The feature flag will not be there / needed when we release the major, so you can remove this bullet point here in the `UPGRADE-6.8.md` 🙂

File: src/Core/Content/Media/Infrastructure/Path/MediaUrlGenerator.php [hunk 30]
```diff
@@ -38,4 +40,43 @@ public function generate(array $paths): array
...
+        if (isset($urlInfo['host'])) {
+            $encodedPath .= "{$urlInfo['host']}";
+
+            if (isset($urlInfo['port'])) {
+                $encodedPath .= ":{$urlInfo['port']}";
+            }
+        }
+
+        return $encodedPath . $path;
+    }
```
Comment (MalteJanz) [inline src/Core/Content/Media/Infrastructure/Path/MediaUrlGenerator.php]: Is this the same code as here?

https://github.com/shopware/shopware/blob/32c45e2b237cb5661a41e629984330ce047ac3a8/src/Storefront/Framework/Twig/Extension/UrlEncodingTwigFilter.php#L25-L62

Then I would suggest making one of them easily accessible (e.g. making this `public static`) and then calling this function in the twig filter.

File: src/Core/Content/Media/Infrastructure/Path/MediaUrlGenerator.php [hunk 31]
```diff
@@ -27,6 +28,7 @@ public function generate(array $paths): array
                 $url = $value->path;
             } else {
                 $url = $this->filesystem->publicUrl($value->path);
```
Comment (MalteJanz) [inline src/Core/Content/Media/Infrastructure/Path/MediaUrlGenerator.php]: Have you tried just encoding `$value->path` before passing it into this method? That would be much simpler than doing it after the fact with all the url parsing and then only encoding the "path"

**Review by MalteJanz — CHANGES_REQUESTED** [review]
Found a few more smaller things. Just to double check: Have you done a demo about this change recently? 

My previous comment on that: https://github.com/shopware/shopware/pull/5957#pullrequestreview-2759848074

I think we should be extra careful with this change and do a lot of tests, maybe even in a SaaS staging instace to really make sure it doesn't break anything with or without the 6.8 major flag

File: src/Core/Content/Media/Infrastructure/Path/MediaUrlGenerator.php (hunk 30 above)
Comment (MalteJanz) [reply src/Core/Content/Media/Infrastructure/Path/MediaUrlGenerator.php]: But you might not need all of that as I questioned here: https://github.com/shopware/shopware/pull/5957#discussion_r2144462245

File: changelog/_unreleased/2025-04-04-fix-product-media-import-with-whitespace-in-url.md [hunk 32]
```diff
@@ -0,0 +1,14 @@
...
+author_email: p.dinkhoff@shopware.com
+author_github: @p.dinkhoff
+---
+# Core
+* Changed: URLs generated by the `MediaUrlGenerator` will properly encode the file path to produce valid URLs in version `v6.8.0.0` (e.g. replace whitespaces as `%20`). The current implementation relies on the caller to do proper URL encoding with the returned string.
+___
+# Next Major Version Changes
+## Changed URL generation of `MediaUrlGenerator` to properly encode the file path to produce valid URLs
+* For example media files with spaces in their name now should be properly URL-encoded with `%20` by default, without doing URL-encoding only with the return value of the `MediaUrlGenerator`. Make sure to remove extra URL-encoding (e.g. usage of twig filter `encodeUrl`) on media entities to not accidentally double encode the URLs.
+* Changed twig filter `encodeMediaUrl` in `Storefront/Framework/Twig/Extension/UrlEncodingTwigFilter.php` will now return the URL in its already encoded form and is basically the same as `$media->getUrl()` with some extra checks.
```
Comment (marcelbrode) [inline changelog/_unreleased/2025-04-04-fix-product-media-import-with-whitespace-in-url.md]: I think (please correct me if I'm wrong, @mitelg) this is not necessary anymore, since you aleady updated `UPGRADE-6.8.md`

File: src/Core/Content/ImportExport/DataAbstractionLayer/Serializer/Entity/MediaSerializer.php [hunk 33]
```diff
@@ -63,6 +64,10 @@ public function deserialize(Config $config, EntityDefinition $definition, $entit
             return $deserialized;
         }
 
+        if (!Feature::isActive('v6.8.0.0')) {
+            $url = str_replace(' ', '%20', $url);
```
Comment (marcelbrode) [inline src/Core/Content/ImportExport/DataAbstractionLayer/Serializer/Entity/MediaSerializer.php]: Is that really everything? Don't we have sanitizers or encoders who do this without hardcoded replacements?

**Review by marcelbrode — CHANGES_REQUESTED** [review]

File: changelog/_unreleased/2025-04-04-fix-product-media-import-with-whitespace-in-url.md (hunk 32 above)
Comment (mitelg) [reply changelog/_unreleased/2025-04-04-fix-product-media-import-with-whitespace-in-url.md]: yes, please do not duplicate :grin: 

`# Next Major Version Changes` in changelog files is not necessary, if you already adjusted the 6.8 upgrade guide

File: src/Core/Content/ImportExport/DataAbstractionLayer/Serializer/Entity/MediaSerializer.php (hunk 33 above)
Comment (MalteJanz) [reply src/Core/Content/ImportExport/DataAbstractionLayer/Serializer/Entity/MediaSerializer.php]: Actually no, that just fixes the space issue. But we should do proper encoding of the path in the URL here, like we do in other places.

It's only a temporary workaround until the url's are properly encoded by default with 6.8

**Review by DennisGarding — APPROVED** [review]

**Review by marcelbrode — APPROVED** [review]

**Review by MalteJanz — APPROVED** [review]

**Review by ennasus4sun — APPROVED** [review]

File: src/Core/Content/ImportExport/Exception/MediaSerializerException.php [hunk 34]
```diff
@@ -0,0 +1,33 @@
+<?php declare(strict_types=1);
+
+namespace Shopware\Core\Content\ImportExport\Exception;
+
+use Shopware\Core\Content\ImportExport\ImportExportException;
+use Shopware\Core\Framework\Log\Package;
+use Symfony\Component\HttpFoundation\Response;
+
+#[Package('fundamentals@after-sales')]
+class MediaSerializerException extends ImportExportException
```
Comment (mitelg) [inline src/Core/Content/ImportExport/Exception/MediaSerializerException.php]: those should be directly part of the `\Shopware\Core\Content\ImportExport\ImportExportException` 

or is there a reason, why you added this?

Comment (philippdinkhoff) [reply src/Core/Content/ImportExport/Exception/MediaSerializerException.php]: Ah you're right, I changed it.

**Review by mitelg — APPROVED** [review]
