### PR TITLE
fix: Show new customer address after saving admin modal

### LINKED ISSUE #7350: Add Address not working in customer overview
*PHP Version:* 8.3.17   | *Shopware Version:* 6.6.10.0  | *Affected area / extension:* Platform(Default) 

 ----

*_Actual behaviour:_*

In the customer overview, when you create a new address using the 'Add Address' button, it is not being stored

https://github.com/user-attachments/assets/adb7876b-bc66-42f1-aa84-f49d09079c00

*_Expected behaviour:_*

A new address should be created.

*_How to reproduce:_*

- Create a new Customer from the backend
- Add new address using 'Add Address' button

### PR DESCRIPTION
**Pull request by En0Ma1259**
**Actual behaviour:**
In the customer overview, when you create a new address using the 'Add Address' button, it is not being ~~stored~~ / displayed before saving

**Expected behaviour:**
A new address should be created.

**How to reproduce:**
- Create a new Customer from the backend
- Add new address using 'Add Address' button

Issue:
https://github.com/shopware/shopware/issues/7350

### CODE REVIEW

File: src/Administration/Resources/app/administration/src/module/sw-customer/view/sw-customer-detail-addresses/index.js [hunk 1]
```diff
@@ -279,12 +277,7 @@ export default {
         },
 
         onEditAddress(id) {
-            const currentAddress = this.addressRepository.create(Shopware.Context.api, id);
-
-            // assign values and id to new address
-            Object.assign(currentAddress, this.activeCustomer.addresses.get(id));
-
-            this.currentAddress = currentAddress;
+            this.currentAddress = this.activeCustomer.addresses.get(id);
```
Comment (En0Ma1259) [inline src/Administration/Resources/app/administration/src/module/sw-customer/view/sw-customer-detail-addresses/index.js]: Can't see, why we had created a new entity here
https://github.com/shopware/shopware/commit/9777cdbf2b17138463ecd3e5e52e70e895c6d499#diff-11ee423b1a8bc02920ba8aa0a08425c30ec5c3e093cd171794915143becad710

Comment (En0Ma1259) [reply src/Administration/Resources/app/administration/src/module/sw-customer/view/sw-customer-detail-addresses/index.js]: Maybe it is also solved, cause we are saving now the entity and reload the grid

File: src/Administration/Resources/app/administration/src/module/sw-customer/view/sw-customer-detail-addresses/sw-customer-detail-addresses.html.twig
Comment (cyl3x) [inline src/Administration/Resources/app/administration/src/module/sw-customer/view/sw-customer-detail-addresses/sw-customer-detail-addresses.html.twig:1]: Please have a look here why all blocks are intended, this shouldn't happen. If I'm right, it's a format setting in phpstorm, triggered by "format on save" or something

File: src/Administration/Resources/app/administration/src/module/sw-customer/view/sw-customer-detail-addresses/index.js (hunk 1 above)
Comment (cyl3x) [reply src/Administration/Resources/app/administration/src/module/sw-customer/view/sw-customer-detail-addresses/index.js]: You should get back a reference to the address when you call `get`, therefore any changes to the address will be stored in the customer entity - meaning if you cancel editing the address will still be changed and updated with the customer :thinking:

File: src/Administration/Resources/app/administration/src/module/sw-customer/view/sw-customer-detail-addresses/sw-customer-detail-addresses.html.twig
Comment (En0Ma1259) [reply src/Administration/Resources/app/administration/src/module/sw-customer/view/sw-customer-detail-addresses/sw-customer-detail-addresses.html.twig:1]: It was done, after I executed `composer eslint:admin:fix`. So I thought this is right. If I revert the change and execute it again, it will be the same as it is now. But this should be then the right format, or not

Comment (En0Ma1259) [reply src/Administration/Resources/app/administration/src/module/sw-customer/view/sw-customer-detail-addresses/sw-customer-detail-addresses.html.twig:1]: But since I have not changed there anything, I will revert it

**Review by Bird87ZA — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-customer/view/sw-customer-detail-addresses/index.js [hunk 2]
```diff
@@ -230,13 +230,11 @@ export default {
 
             Object.assign(address, this.currentAddress);
 
-            if (this.customer.addresses.has(address.id)) {
-                this.customer.addresses.remove(address.id);
-            }
-
-            this.customer.addresses.push(address);
+            this.customerAddressRepository.save(address).then(() => {
```
Comment (cyl3x) [inline src/Administration/Resources/app/administration/src/module/sw-customer/view/sw-customer-detail-addresses/index.js:233]: I'm not sure about this. Updates are supposed to be pushed to the DB for the whole customer after clicking "Save", but this will create the address regardless.
As far as I can tell, it's a reactivity issue :thinking:

Comment (En0Ma1259) [reply src/Administration/Resources/app/administration/src/module/sw-customer/view/sw-customer-detail-addresses/index.js:233]: This not a unique behaviour. As an example, the property options will save the changes directly as well after clicking the "apply" modal button.

----
Has something to do with `:local-mode="false"`

Comment (cyl3x) [reply src/Administration/Resources/app/administration/src/module/sw-customer/view/sw-customer-detail-addresses/index.js:233]: Still a behaviour break. If it's not necessary, don't save the address and keep the old behaviour

Comment (En0Ma1259) [reply src/Administration/Resources/app/administration/src/module/sw-customer/view/sw-customer-detail-addresses/index.js:233]: So we have the following options:
1. This way and keep `:local-mode="false"`
2. `:local-mode="true"` ⇾ maybe also a behaviour break at other points and will lead into bigger changes
4. Some kind of hacky solution, where we trick and bypass local-mode and do not implement the `sw-one-to-many-grid` component as it was supposed to be

Started 2. but needed to change too much and then rolled back to the current implementation. Even in the `sw-one-to-many-grid` component

Comment (cyl3x) [reply src/Administration/Resources/app/administration/src/module/sw-customer/view/sw-customer-detail-addresses/index.js:233]: This module is confusing, it seems that creating, editing and changing defaults is not supposed to be saved, whereas the deletion is done instantly. Maybe saving instantly is the best solution, it's correctly not showing up before a save anyway :+1:

**Review by cyl3x — APPROVED** [review]

**Comment by cyl3x** [comment]
@En0Ma1259 we should backport this
