### PR TITLE
fix: plugins fallback to bare language

### LINKED ISSUE #15019: Changing locale of duplicated snippet set empties some snippets provided by extensions
### Shopware Version

6.7.7.1

### Affected area / extension

Platform(Default)

### Actual behaviour

When duplicating snippet sets, snippets provided by extensions may be removed once the locale is changed. This impacts 3rd-party extensions, but also for example our SwagPayPal or SwagAnalytics extensions.

As a result, some text in the storefront may not be in the language desired. In some cases (i.e. for the de-AT example described below), the [fallback language selection](https://developer.shopware.com/docs/concepts/translations/fallback-language-selection.html) introduced in 6.7 does not seem to work either, displaying English text instead of the de-DE or de fallback.

<details><summary>Screenshots</summary>
<p>

Image

Image

</p>
</details> 

This behaviour makes it very difficult to create storefronts for certain regions with slight language differences, such as in this example.

### Expected behaviour

All duplicated snippets would remain when the locale is changed, or would at least fall back to the language its based on

### How to reproduce

- Set up a new shop with the PayPal extension
- Duplicate the “BASE de-DE” snippet set and set its Locale to de-AT
- Search for “paypal” in both the de-DE and de-AT snippet sets, they will be gone in de-AT

If you want to test the effects in the storefront:
- Change the sales channel to use the new snippet set
- Configure the PayPal Sandbox and add the credit card method to the sales channel
- Create a product, then in the storefront put it in the cart and go to checkout, select credit card, observe the wrong language in the credit card fields

### PR DESCRIPTION
**Pull request by dgrothaus-sw**
### 1. Why is this change necessary?

Due to the changes in the language system, the fallback of regional translations like `de-AT` won't fallback to parent language  `de-DE`, when the plugin only  provides `de-DE` instead of the now required `de`.

### 2. What does this change do, exactly?

Add a fallback layer to also check for `de-DE` and `en-GB` in plugin snippet files.

### 3. Describe each step to reproduce the issue or behaviour.

See Fixes #15019

### 4. Please link to the relevant issues (if any).

Fixes #15019

### 5. Checklist

- [X] I have written tests and verified that they fail without my change
- [ ] I have updated developer-facing release notes if this change is **relevant** for external developers:
  - Add a short entry to `RELEASE_INFO-6.<major>.md` under “Upcoming” for informational changes, including the consequences of the change and how it affects external developers.
  - Add an `UPGRADE` section in `UPGRADE-6.<next-major>.md` for breaking changes (what/why/impact/how to adapt).
  - See the [Documenting a Release Process](https://github.com/shopware/shopware/blob/trunk/delivery-process/documenting-a-release.md) for details.
- [ ] I have written or adjusted the documentation according to my changes
- [X] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Core/System/Snippet/Files/SnippetFileCollection.php [hunk 1]
```diff
@@ -111,6 +117,43 @@ public function getSnippetFilesByIso(string $iso): array
...
+     * @return list<AbstractSnippetFile>
+     */
+    public function getSnippetFilesWithLocaleFallback(string $locale): array
+    {
+        if (!preg_match(SnippetPatterns::COMPLETE_LOCALE_PATTERN, $locale, $matches) || empty($matches['region'])) {
+            return $this->getSnippetFilesByIso($locale);
+        }
+
+        $agnosticLanguage = $matches['language'];
+        $canonicalIso = self::CANONICAL_LANGUAGE_MAP[$agnosticLanguage] ?? ($agnosticLanguage . '-' . strtoupper($agnosticLanguage));
```
Comment (MartinKrzykawski) [inline src/Core/System/Snippet/Files/SnippetFileCollection.php:137]: The fallback `$agnosticLanguage . '-' . strtoupper($agnosticLanguage)` is not a reliable way to derive the canonical locale. It only works for languages where the canonical region matches the uppercased language code, such as `de -> de-DE`, but it fails for cases like `da -> da-DK`, `sv -> sv-SE`, or `ja -> ja-JP`. From an extension perspective this means locales like `da-GL` may still miss plugin snippets if the extension only provides the canonical file `da-DK`.`

Comment (dgrothaus-sw) [reply src/Core/System/Snippet/Files/SnippetFileCollection.php:137]: Yes, that's totally true. But not the cause of the bug that is fixed with this.
The origin of the  bug is, that in the PayPal plugin there's currently an event that deliberately takes the already agnostic `de` and `en` translation and re-maps it to `de-DE` and `en-GB` to be backwards compatible.
This causes the already existing fallback of `de` in the PayPal plugin (and others) to not be seen in the collection, as it is registered as `de_DE`.

We only ship `de-DE` and `en-GB` translations by default (the rest is provided as a download), so the only irregular language code to be considered is `en-GB` which is done by the map. Considering the other languages is out of scope, as the bug that causes this only re-maps `de` ⇒ `de-DE` and `en` ⇒ `en-GB`.

I had the same train of thoughts as you and decided for this simple fix, as it will be obsolete with the next mayor and the cause is also just temporary.

Comment (MartinKrzykawski) [reply src/Core/System/Snippet/Files/SnippetFileCollection.php:137]: Okay, thanks for the explaination!

**Review by MartinKrzykawski — APPROVED** [review]

**Review by marcelbrode — APPROVED** [review]
