### PR TITLE
fix: Reset value if below or equals zero

### LINKED ISSUE #10165: Incorrect Behavior for Promotions with Max Total Uses and Max Uses Per Customer Set to Zero
### Shopware Version

6.7

### Affected area / extension

Platform(Default)

### Actual behaviour

Promotion is valid and can be applied to cart

### Expected behaviour

An error is thrown and the promotion is not applied to the cart

### How to reproduce

Steps to reproduce:
1. Create a new promotion with Max. total uses and Max. uses per customer set to 0
2. Apply the promotion to the cart
3. Check the behavior

https://github.com/user-attachments/assets/6d24142e-40af-415c-b70f-58ab3e1361f3

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by En0Ma1259**
### 1. Why is this change necessary?
Promotion with max value below or equal to zero doesn't make much sense

### 2. What does this change do, exactly?
Check on blur, if the value is below or equal to zero

### 3. Describe each step to reproduce the issue or behaviour.
Set the max value to zero

### 4. Please link to the relevant issues (if any).
- fixes https://github.com/shopware/shopware/issues/10165
### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfill them.

### CODE REVIEW

File: src/Administration/Resources/app/administration/src/module/sw-promotion-v2/view/sw-promotion-v2-detail-base/index.js [hunk 1]
```diff
@@ -179,5 +179,11 @@ export default {
         generateFinish() {
             this.isGenerateSuccessful = false;
         },
+
+        checkPromotionMaxValue(value, property) {
+            if (value <= 0) {
```
Comment (cyl3x) [inline src/Administration/Resources/app/administration/src/module/sw-promotion-v2/view/sw-promotion-v2-detail-base/index.js]: How about:
```suggestion
        checkPromotionMaxValue(property) {
            if (this.promotion[property] <= 0) {
```

**Review by cyl3x — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-promotion-v2/view/sw-promotion-v2-detail-base/sw-promotion-v2-detail-base.html.twig [hunk 2]
```diff
@@ -85,6 +85,7 @@
                 :placeholder="$tc('sw-promotion-v2.detail.base.general.maxUsesGlobalPlaceholder')"
                 :disabled="!acl.can('promotion.editor')"
                 allow-empty
+                @blur="checkPromotionMaxValue('maxRedemptionsGlobal')"
```
Comment (cyl3x) [inline src/Administration/Resources/app/administration/src/module/sw-promotion-v2/view/sw-promotion-v2-detail-base/sw-promotion-v2-detail-base.html.twig]: I looked into the docs:
```suggestion
                :min="0"
```
should be enough

Comment (En0Ma1259) [reply src/Administration/Resources/app/administration/src/module/sw-promotion-v2/view/sw-promotion-v2-detail-base/sw-promotion-v2-detail-base.html.twig]: You are almost right. Should be 1

File: src/Administration/Resources/app/administration/src/module/sw-promotion-v2/view/sw-promotion-v2-detail-base/sw-promotion-v2-detail-base.html.twig [hunk 3]
```diff
@@ -96,6 +97,7 @@
                 :label="$tc('sw-promotion-v2.detail.base.general.maxUsesPerCustomerLabel')"
                 :placeholder="$tc('sw-promotion-v2.detail.base.general.maxUsesPerCustomerPlaceholder')"
                 :disabled="!acl.can('promotion.editor')"
+                :min="1"
```
Comment (cyl3x) [inline src/Administration/Resources/app/administration/src/module/sw-promotion-v2/view/sw-promotion-v2-detail-base/sw-promotion-v2-detail-base.html.twig:100]: Can you still unset it / set the value to null? As a value of 0 was used to disable it

Comment (En0Ma1259) [reply src/Administration/Resources/app/administration/src/module/sw-promotion-v2/view/sw-promotion-v2-detail-base/sw-promotion-v2-detail-base.html.twig:100]: Yes. If you remove the value, it will be "unlimited"

**Review by cyl3x — APPROVED** [review]

**Review by FlorianKe — APPROVED** [review]

**Review by mstegmeyer — APPROVED** [review]
