### PR TITLE
fix: recursive usage of CartLocker

### LINKED ISSUE #11692: Handling of locking mechanism in shopware 6.7.1.0 breaking subscriber functionality with custom products
### Shopware Version

6.7.1.2

### Affected area / extension

Extension:Custom-Products

### Actual behaviour

Using custom products 7.1.1 and adding a custom extension subscribing to `onLineItemAdded` leaves the cart locked, so no operation can be performed.

### Expected behaviour

Lock mechanism should release the cart after add the custom product order line item.

### How to reproduce

s. behaviour

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by mstegmeyer**
### 1. Why is this change necessary?
It may happen, that extensions want to call CartRoutes in Events, that are triggered by Cart routes. This currently leads to a deadlock due to the new CartLocker, that is supposed to prevent editing by separate API requests.

### 2. What does this change do, exactly?
Save the lock in the SalesChannelContext (as the cart gets persisted and replaced by the calculation process, which seems unsafe) and only acquire a lock on the outermost CartLocker call.

### 3. Describe each step to reproduce the issue or behaviour.
- Listen to an event, e.g. `BeforeLineItemAddedEvent`
- In that subscriber, try to remove the added line item again via the `CartItemRemoveRoute`

### 4. Please link to the relevant issues (if any).
fixes #11692 

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Core/System/SalesChannel/SalesChannelContext.php [hunk 1]
```diff
@@ -449,4 +452,14 @@ public function setMeasurementSystem(MeasurementUnits $measurementSystem): void
     {
         $this->measurementSystem = $measurementSystem;
     }
+
+    public function getLock(): ?LockInterface
```
Comment (cyl3x) [inline src/Core/System/SalesChannel/SalesChannelContext.php]: Only calling it lock implies that also the sales channel is locked somehow - I propose `cartLock`

**Review by mitelg — APPROVED** [review]

File: src/Core/Checkout/Cart/CartLocker.php [hunk 2]
```diff
@@ -24,19 +25,27 @@ public function __construct(private readonly LockFactory $lockFactory)
      *
      * @template \T
      */
-    public function locked(string $token, \Closure $closure)
+    public function locked(SalesChannelContext $context, \Closure $closure)
     {
-        $lockKey = $this->getLockKey($token);
+        if ($context->getCartLock() !== null && $context->getCartLock()->isAcquired()) {
```
Comment (En0Ma1259) [inline src/Core/Checkout/Cart/CartLocker.php]:
```suggestion
        if ($context->getCartLock()?->isAcquired()) {
```

**Review by En0Ma1259 — APPROVED** [review]

File: src/Core/System/SalesChannel/SalesChannelContext.php [hunk 3]
```diff
@@ -449,4 +452,14 @@ public function setMeasurementSystem(MeasurementUnits $measurementSystem): void
     {
         $this->measurementSystem = $measurementSystem;
     }
+
+    public function getCartLock(): ?LockInterface
```
Comment (keulinho) [inline src/Core/System/SalesChannel/SalesChannelContext.php:462]: we should mark this and the setter as internal right? if needed externals should use the cart locker

**Review by keulinho — APPROVED** [review]

File: src/Core/System/SalesChannel/SalesChannelContext.php (hunk 3 above)
Comment (mstegmeyer) [reply src/Core/System/SalesChannel/SalesChannelContext.php:462]: CartLocker is internal, but yes, let's mark this as internal as well 👍
