### PR TITLE
fix: savepoint errors during queue processing

### LINKED ISSUE #14569: Processing message queue may occasionally log SQL SAVEPOINT error when CategoryIndexingMessage are processed in parallel to other transports
### Shopware Version

6.7.6.2

### Affected area / extension

Platform(Default)

### Actual behaviour

When you route CategoryIndexingMessage to its own transport, and then you process them simultaneously, occasionally the following error may be logged:

```
Error thrown while running command "messenger:consume low_priority --time-limit=280". Message: "An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT DOCTRINE_2 does not exist" {"exception":"[object] (Symfony\\Component\\Messenger\\Exception\\TransportException(code: 0): An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT DOCTRINE_2 does not exist at /home/mkuhlmann/files/sw67/vendor/symfony/doctrine-messenger/Transport/DoctrineSender.php:48)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\DriverException(code: 1305): An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT DOCTRINE_2 does not exist at /home/mkuhlmann/files/sw67/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:102)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1305): SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT DOCTRINE_2 does not exist at /home/mkuhlmann/files/sw67/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:24)\n[previous exception] [object] (PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT DOCTRINE_2 does not exist at /home/mkuhlmann/files/sw67/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:27)","command":"messenger:consume low_priority --time-limit=280","message":"An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT DOCTRINE_2 does not exist"} []
```

This error can also come up during various other actions, such as thumbnail generation or when the shop tries to store cache invalidation tags:

```
Failed to store cache invalidation tags, invalidating immediately. Error: An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT DOCTRINE_2 does not exist [] []
```

This is reported as part of a support case (#SWAG-322802).

Tested environment:

- PHP 8.2.30 & 8.3.24
- MySQL 8.0.44 & MariaDB 10.11.15

### Expected behaviour

Processing transports in parallel won't lead to errors

### How to reproduce

- Set up a new shop and configure elasticsearch
- Generate lots of products and categories (8.5k products and 2.2k categories in my test, more = probably better)
- Set the following configurations:
```yaml
#config/packages/framework.yaml
framework:
    messenger:
        transports:
            category_indexing:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: 'category_indexing'
```

```yaml
#config/packages/shopware.yaml
shopware:
    admin_worker:
        enable_admin_worker: false
    messenger:
        routing_overwrite:
            'Shopware\Core\Content\Category\DataAbstractionLayer\CategoryIndexingMessage': category_indexing
            'Shopware\Core\Content\Media\Message\GenerateThumbnailsMessage': low_priority
            'Shopware\Core\Content\Media\Message\DeleteFileMessage': low_priority
            'Shopware\Core\Content\Product\DataAbstractionLayer\ProductIndexingMessage': low_priority
            'Shopware\Core\Framework\DataAbstractionLayer\Indexing\MessageQueue\IterateEntityIndexerMessage': low_priority
```
- Clear the cache and set up the following cronjobs afterwards:
```cron
*/5 * * * * /usr/bin/php8.3 /var/www/path_to_shop/bin/console messenger:consume async failed --time-limit=280
*/5 * * * * /usr/bin/php8.3 /var/www/path_to_shop/bin/console messenger:consume low_priority --time-limit=280
*/5 * * * * /usr/bin/php8.3 /var/www/path_to_shop/bin/console messenger:consume category_indexing --time-limit=280
*/5 * * * * /usr/bin/php8.3 /var/www/path_to_shop/bin/console scheduled-task:run --time-limit=280
*/1 * * * * /usr/bin/php8.3 /var/www/path_to_shop/bin/console dal:refresh:index --use-queue
```

This will process all transports in parallel and generate new CategoryIndexingMessage messages continuously. Eventually you should see the error in the log files (it may take an hour or more).

### PR DESCRIPTION
**Pull request by h1k3r**
### 1. Why is this change necessary?

When deadlock happens, Connection internal track of transactionNestingLevel is not restored, that may lead to exceptions in subsequent transactions.

### 2. What does this change do, exactly?

Replaces `Connection::transactional` and `Connection::beginTransaction` usage with `RetryableTransaction::transactional`.

### 3. Describe each step to reproduce the issue or behaviour.

See linked issue description.

### 4. Please link to the relevant issues (if any).
- closes https://github.com/shopware/shopware/issues/14569
- relates https://github.com/shopware/shopware/pull/9202
- relates https://github.com/shopware/shopware/pull/15332

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have updated developer-facing release notes if this change is **relevant** for external developers:
  - Add a short entry to `RELEASE_INFO-6.<major>.md` under “Upcoming” for informational changes, including the consequences of the change and how it affects external developers.
  - Add an `UPGRADE` section in `UPGRADE-6.<next-major>.md` for breaking changes (what/why/impact/how to adapt).
  - See the [Documenting a Release Process](https://github.com/shopware/shopware/blob/trunk/delivery-process/documenting-a-release.md) for details.
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Core/Content/Flow/Dispatching/FlowExecutor.php [hunk 1]
```diff
@@ -214,21 +214,11 @@ private function callHandle(ActionSequence $sequence, StorableFlow $event): void
...
-
-            throw FlowException::transactionFailed($e);
-        }
-
-        try {
-            $this->connection->commit();
-        } catch (DBALException $e) {
-            $this->connection->rollBack();
-
             throw FlowException::transactionFailed($e);
```
Comment (h1k3r) [inline src/Core/Content/Flow/Dispatching/FlowExecutor.php:222]: With this logic should remain as before, as it seems `Connection::transactional` does not throw other `Throwable` than thrown by callback or ones extending `DBALException`

File: src/Core/Framework/App/Privileges/Privileges.php [hunk 2]
```diff
@@ -238,7 +239,8 @@ private function fetchPrivileges(array $appIds): array
      */
     private function writePrivileges(string $appId, array $privileges, array $requestedPrivileges, Context $context): void
     {
-        $this->connection->transactional(
+        RetryableTransaction::transactional(
```
Comment (nfortier-shopware) [inline src/Core/Framework/App/Privileges/Privileges.php:242]: Should we remove the @codeCoverageIgnore \Shopware\Tests\Integration\Core\Framework\App\Permission\PrivilegesTest on L 18 and make a unit test class for this?

Not about the SQL lines under but more about mocking Connection with transactional throwing an exception (the wrapping)

File: src/Core/Content/Media/Thumbnail/ThumbnailService.php [hunk 3]
```diff
@@ -183,7 +184,7 @@ public function updateThumbnails(MediaEntity $media, Context $context, bool $str
 
         $delete = \array_values(\array_map(static fn (string $id) => ['id' => $id], $toBeDeletedThumbnails->getIds()));
 
-        $update = $this->connection->transactional(function () use ($delete, $media, $config, $context, $toBeCreatedSizes): array {
```
Comment (mitelg) [inline src/Core/Content/Media/Thumbnail/ThumbnailService.php:186]: should we introduce a PHPStan rule to disallow usage of `transactional` method? 🤔

**Review by mitelg — APPROVED** [review]

**Review by umutdogan4291 — APPROVED** [review]

File: src/Core/Framework/App/Privileges/Privileges.php (hunk 2 above)
Comment (h1k3r) [reply src/Core/Framework/App/Privileges/Privileges.php:242]: All this looks like something that would be PrivilegeStorage class. I would stick to using integration test only. Unless we want to split this to Service + Storage class, but I am not sure that it makes a lot of sense here 🤔

File: src/Core/Content/Media/Thumbnail/ThumbnailService.php (hunk 3 above)
Comment (h1k3r) [reply src/Core/Content/Media/Thumbnail/ThumbnailService.php:186]: I am not sure that this would be useful, we have less than dozen of places in the system where we directly work with transaction. But it will definitely add even more computations to phpstan 🤔

File: src/Core/Framework/App/Privileges/Privileges.php (hunk 2 above)
Comment (nfortier-shopware) [reply src/Core/Framework/App/Privileges/Privileges.php:242]: Alright, can be something in another PR another time, since this private is used in the public updatePrivileges, which does some logic with many array_intersect it was an opportunity to cover it 😅 

Now for the Retryable logic part, the existing integration is not going that in depth: it checks the exception is thrown and that's it (meaning this PR changes makes no difference to it).

Why would we do that split in another PR: to keep the minimum on integration level and ditch the method `assertPrivileges(` which is asserting by checking the DB.  Really checking mainly it articulates well, while more in depth in unit, and to go cover this behavior related to transactional handling.
