### PR TITLE
fix(breadcrumb): handle null category in buy-widget-form

### LINKED ISSUE #14657: Breadcrumb Error after upgrade to 6.7.7.0
### Shopware Version

6.7.7.0

### Affected area / extension

Platform(Default)

### Actual behaviour

Upgrade from 6.7.6.1 to 6.7.7.0 and now can't display the product detail page.  Get this error:

Can not render @Storefront/storefront/component/buy-widget/buy-widget-form.html.twig view: An exception has been thrown during the rendering of a template ("Shopware\Core\Framework\Adapter\Twig\Extension\BuildBreadcrumbExtension::getFullBreadcrumb(): Argument #2 ($category) must be of type Shopware\Core\Content\Category\CategoryEntity, null given

### Expected behaviour

Should display the product detail.

### How to reproduce

Upgrade to 6.7.7.0

### PR DESCRIPTION
**Pull request by BrocksiNet**
### 1. Why is this change necessary?

When a product has no SEO category assigned, `page.product.seoCategory` is `null`. Twig's `is defined` check returns `true` (it checks property existence, not nullness), so `sw_breadcrumb_full(null, context)` is called, causing a `TypeError` because `BuildBreadcrumbExtension::getFullBreadcrumb()` expects a non-nullable `CategoryEntity`.

### 2. What does this change do, exactly?

- Fixes the condition in `buy-widget-form.html.twig` from `page.product.seoCategory is defined` to a truthy check (`page.product.seoCategory`), matching the pattern already used in `breadcrumb.html.twig`.

### 3. Describe each step to reproduce the issue or behaviour.

1. Have a product without an SEO category assigned
2. Open the product detail page in the storefront
3. A `TypeError` is thrown: `BuildBreadcrumbExtension::getFullBreadcrumb(): Argument #2 ($category) must be of type CategoryEntity, null given`

### 4. Please link to the relevant issues (if any).

closes #14657

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have updated developer-facing release notes if this change is **relevant** for external developers
- [ ] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Core/Framework/Adapter/Twig/Extension/BuildBreadcrumbExtension.php [hunk 1]
```diff
@@ -37,7 +37,14 @@ public function getFunctions(): array
     {
         /** @deprecated tag:v6.8.0 - Remove `needs_context` option, as the SalesChannelContext is required and the Twig Context is not needed anymore */
         return [
-            new TwigFunction('sw_breadcrumb_full', $this->getFullBreadcrumb(...), ['needs_context' => true]),
+            new TwigFunction('sw_breadcrumb_full', function (array $twigContext, ?CategoryEntity $category, Context|SalesChannelContext $context): array {
```
Comment (mitelg) [inline src/Core/Framework/Adapter/Twig/Extension/BuildBreadcrumbExtension.php]: why is this necessary? I don't think we should allow passing `null`. instead failing is correct, imo

**Review by mitelg — CHANGES_REQUESTED** [review]

File: src/Core/Framework/Adapter/Twig/Extension/BuildBreadcrumbExtension.php (hunk 1 above)
Comment (BrocksiNet) [reply src/Core/Framework/Adapter/Twig/Extension/BuildBreadcrumbExtension.php]: It is defensive programming ... we can protect developers from using it incorrectly in their extensions... this was the idea behind this. And currently, with Twig, you can pass anything there; there is no type safety in Twig either.

Comment (mitelg) [reply src/Core/Framework/Adapter/Twig/Extension/BuildBreadcrumbExtension.php]: the whole thing will be removed anyway with https://github.com/shopware/shopware/pull/14158 :man_shrugging:

Comment (BrocksiNet) [reply src/Core/Framework/Adapter/Twig/Extension/BuildBreadcrumbExtension.php]: nice 😂 so why are we talking?

Comment (BrocksiNet) [reply src/Core/Framework/Adapter/Twig/Extension/BuildBreadcrumbExtension.php]: okay let's revert that and just take the Twig fix with us ... will push update in some secs

**Review by SpiGAndromeda — APPROVED** [review]

**Review by tobiasberge — APPROVED** [review]

**Review by Phil23 — APPROVED** [review]

**Review by mitelg — APPROVED** [review]
