### PR TITLE
fix(sales-channel-create)!: Revoke createdComponent back to being sync

### LINKED ISSUE #11599: Cloud: Unable to create a Google Shopping saleschannel
### Shopware Version

cloud

### Affected area / extension

Platform(Default)

### Actual behaviour

No more Google Shopping sales channels can be created in the cloud. Other sales channels are available. The window remains empty.

Image

### Expected behaviour

.

### How to reproduce

Create a Google Shopping sales channel in the cloud shop :)

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by marcelbrode**
fixes: #11599

### 1. Why is this change necessary?
Meassurements introduced a breaking change in a minor version

### 2. What does this change do, exactly?
Encapsulate the async functions and handle them with a promise instead

### 3. Describe each step to reproduce the issue or behaviour.
- Install Social Shopping
- Try to create a SOC sales channel
- Create page shouldn't break

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Administration/Resources/app/administration/src/module/sw-sales-channel/page/sw-sales-channel-create/index.js [hunk 1]
```diff
@@ -31,29 +31,34 @@ export default {
...
-
             if (!Shopware.Store.get('context').isSystemDefaultLanguage) {
                 Shopware.Store.get('context').resetLanguageToDefault();
             }
 
             this.salesChannel = this.salesChannelRepository.create();
             this.salesChannel.typeId = this.$route.params.typeId;
             this.salesChannel.active = false;
+
+            this.setMeasurementUnits().then(() => {
```
Comment (bschulzebaek) [inline src/Administration/Resources/app/administration/src/module/sw-sales-channel/page/sw-sales-channel-create/index.js]:
```suggestion
            this.setMeasurementUnits().finally(() => {
```

Some error notification would be nice, but at least the page should remain functional if this req fails.

Comment (marcelbrode) [reply src/Administration/Resources/app/administration/src/module/sw-sales-channel/page/sw-sales-channel-create/index.js]: Derp, you're totally right.

**Comment by bschulzebaek** [comment]
Please add a changelog clarifying that this is not a breaking change, but actually reverting an unnanounced breaking change.

**Review by vienthuong — APPROVED** [review]

**Review by ravenokko — APPROVED** [review]

**Review by sydinh — APPROVED** [review]

**Review by nguyenquocdaile — APPROVED** [review]

**Review by bschulzebaek — APPROVED** [review]
