### PR TITLE
fix: load all existing property group in product variants

### LINKED ISSUE #14697: Admin may freeze when variants don't have configurator settings by loading all existing property groups
### Shopware Version

6.7.7.0

### Affected area / extension

Platform(Default)

### Actual behaviour

When a shop has a lot of property groups and has generated variants without configurator settings / properties assigned, the browser will freeze temporarily when opening the variants tab due to trying to load all existing property groups.

This is being reported as part of a support case (#SWAG-323434) where the customer has pinpointed the root cause to be within the [loadConfigSettingsGroup()](https://github.com/shopware/shopware/blob/279fbdc062e0824999b0981fccd216dcd1da8337/src/Administration/Resources/app/administration/src/module/sw-product/view/sw-product-detail-variants/index.js#L148) function. Checking for the length of groupIds and returning when it is 0 prior to calling cloneDeep(this.groupCriteria) prevents the loading of all property groups and the resulting freeze.

### Expected behaviour

The administration would not load any property groups

### How to reproduce

- Create lots of property groups, you can feel effects starting at 500, the more, the longer the administration freezes
- Create a product with a variant which does not have a configuration assigned (only possible by API or by deleting the relevant entry from product_configurator_setting)
- Open the variant overview, observe the browser freezing

### PR DESCRIPTION
**Pull request by rittou**
### 1. Why is this change necessary?
This pull request refactors how configuration setting groups are handled in the `sw-product-detail-variants` component, making `configSettingGroups` a computed property instead of a data property loaded by a method.

### 2. What does this change do, exactly?
**Product detail variants logic:**

* `configSettingGroups` is now a computed property derived from `productEntity.configuratorSettings` and `groups`, instead of being set via `data()` and loaded asynchronously. [[1]](diffhunk://#diff-68a2fc19800c9f1b97cf18b92e057a68185e40024cf6c2b46aa2bce3517a6ab5L34) [[2]](diffhunk://#diff-68a2fc19800c9f1b97cf18b92e057a68185e40024cf6c2b46aa2bce3517a6ab5R95-R112)
* The `loadConfigSettingGroups()` method is deprecated, now a no-op, and marked for removal in v6.8.0. Calls to this method should be removed. [[1]](diffhunk://#diff-68a2fc19800c9f1b97cf18b92e057a68185e40024cf6c2b46aa2bce3517a6ab5L138-R162) [[2]](diffhunk://#diff-5a6f4c7d1cc118800bd6f17fc8ba236b2629f6b166997a724d14de54d5dc1e20R464-R470)
* The `loadData()` method no longer calls `loadConfigSettingGroups()`, as the computation is now reactive.

### 4. Please link to the relevant issues (if any).
- closes #14697 

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have updated developer-facing release notes if this change is **relevant** for external developers:
  - Add a short entry to `RELEASE_INFO-6.<major>.md` under “Upcoming” for informational changes, including the consequences of the change and how it affects external developers.
  - Add an `UPGRADE` section in `UPGRADE-6.<next-major>.md` for breaking changes (what/why/impact/how to adapt).
  - See the [Documenting a Release Process](https://github.com/shopware/shopware/blob/trunk/delivery-process/documenting-a-release.md) for details.
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Administration/Resources/app/administration/src/module/sw-product/view/sw-product-detail-variants/index.js [hunk 1]
```diff
@@ -136,27 +135,28 @@ export default {
...
-            if (groupIds.length) {
-                criteria.addFilter(Criteria.equalsAny('id', groupIds));
+            if (groupIds.length === 0) {
+                this.configSettingGroups = [];
+                return;
             }
 
-            this.configSettingGroups = await this.loadAllPropertyGroups(criteria);
+            const groupMap = new Map(
+                this.groups.map((g) => [
```
Comment (vienthuong) [inline src/Administration/Resources/app/administration/src/module/sw-product/view/sw-product-detail-variants/index.js]: We would prefer to not use abbreviation
```suggestion
                this.groups.map((group) => [
```

Comment (vienthuong) [reply src/Administration/Resources/app/administration/src/module/sw-product/view/sw-product-detail-variants/index.js]: this groupMap can be also be put to a computed property `groupIds` or `allGroupIds`

File: src/Administration/Resources/app/administration/src/module/sw-product/view/sw-product-detail-variants/index.js [hunk 2]
```diff
@@ -136,27 +135,28 @@ export default {
...
+                    g.id,
+                    g,
+                ]),
+            );
+            this.configSettingGroups = groupIds.map((id) => groupMap.get(id)).filter(Boolean);
```
Comment (vienthuong) [inline src/Administration/Resources/app/administration/src/module/sw-product/view/sw-product-detail-variants/index.js]: then `configSettingGroups` can also be a computed property, we don't even need `loadConfigSettingGroups`

Comment (vienthuong) [reply src/Administration/Resources/app/administration/src/module/sw-product/view/sw-product-detail-variants/index.js]: if the component is expecting the configSettingGroups is an array of group Entity then this is a breaking change

**Review by sydinh — APPROVED** [review]
Looks good 👍🏻

File: src/Administration/Resources/app/administration/src/module/sw-product/view/sw-product-detail-variants/index.js (hunk 2 above)
Comment (rittou) [reply src/Administration/Resources/app/administration/src/module/sw-product/view/sw-product-detail-variants/index.js]: Turning the `configSettingGroups` into a computed property sounds good. Others are unnecessary since they're not used anywhere.

And the breaking changes: Is it kind of "Will be removed from `data()`, use it from computed"?

Comment (vienthuong) [reply src/Administration/Resources/app/administration/src/module/sw-product/view/sw-product-detail-variants/index.js]: yes it is 👍🏽 I guess we can introduce a new computed `configSettingGroupsIds` and deprecate the `configSettingGroups` instead?

Also on the same note, making `async loadConfigSettingGroups` became `loadConfigSettingGroups` (non async) is also a breaking change

**Review by nguyenquocdaile — APPROVED** [review]

**Review by vienthuong — APPROVED** [review]
