### PR TITLE
fix: date range rule json serialization format

### LINKED ISSUE #13642: DateRangeRule/Promotion: DateTime format mismatch causes (silent) validation errors at order conversion
### Shopware Version

6.7.4.2

### Affected area / extension

Platform(Default)

### Actual behaviour

A seemingly working promotion in the cart, but on the order conversion a silent validation error without error logs is thrown. Storefront only shows a general error and no order was created.

### Expected behaviour

A successful order conversion with a valid promotion without any errors.

### Rule
1. Create a rule.
2. Add a valid date range rule with timestamp.

### Promotion
1. Create a simple active promotion.
2. (Optionally, add a code)
3. No additional pre-conditions needed.
4. Add a percentage discount, activate "Apply to a specific range of products only." and select the newly created rule.

### Checkout
1. Add a product to the cart.
2. Activate the promotion by code, if defined.
3. See a valid promotion in cart with the valid discount.
4. Order
5. "error.message-default"-Snippet is shown, no order was created.

It seems to be caused by a mismatched DateTime-format.
The DateTime gets serialized with `RFC3339_EXTENDED`, the DateRangeRule expects `ATOM`.

https://github.com/shopware/shopware/blob/c7734d9faf52961fc8ce9b2c2d392d3fd8f61cfc/src/Core/Framework/Struct/JsonSerializableTrait.php#L28

https://github.com/shopware/shopware/blob/c7734d9faf52961fc8ce9b2c2d392d3fd8f61cfc/src/Core/Framework/Rule/DateRangeRule.php#L76

### PR DESCRIPTION
**Pull request by vintagesucks**
resolves #13642

Overrides `jsonSerialize` in `DateRangeRule` to format dates as `Y-m-d\TH:i:s` (`DateRangeRule::DATETIME_FORMAT`) instead of [`RFC3339_EXTENDED`](https://github.com/shopware/shopware/blob/8a5dcf63debb276e4fa1ca5a9392d4676b4c7d85/src/Core/Framework/Struct/JsonSerializableTrait.php#L28), matching the validation constraints.

### CODE REVIEW

File: src/Core/Framework/Rule/DateRangeRule.php [hunk 1]
```diff
@@ -96,4 +96,18 @@ public function getConstraints(): array
             'timezone' => [new Timezone()],
         ];
     }
+
+    public function jsonSerialize(): array
```
Comment (vintagesucks) [inline src/Core/Framework/Rule/DateRangeRule.php:114]: This broke stuff in the order admin, looking into it.

Comment (vintagesucks) [reply src/Core/Framework/Rule/DateRangeRule.php:114]: [`ae97c6b`](https://github.com/shopware/shopware/commit/ae97c6b022879d1ed7ab28c87dace117072fd263) 😬

File: tests/unit/Core/Framework/Rule/DateRangeRuleTest.php [hunk 2]
```diff
@@ -263,4 +264,45 @@ public static function matchDataProvider(): array
...
+    public function testSerializationAndValidation(): void
+    {
+        $rule = new DateRangeRule(
+            new \DateTime('2024-01-15 10:30:45'),
+            new \DateTime('2024-01-31 23:59:59'),
+            true,
+            new \DateTimeZone('UTC')
+        );
+
+        $serialized = (string) json_encode($rule);
```
Comment (MalteJanz) [inline tests/unit/Core/Framework/Rule/DateRangeRuleTest.php]: nitpick: instead of string casting, just add an `static::assertIsString` call, which I think should make PHPStan happy as well (and also properly fails the test if it isn't the case).

**Review by MalteJanz — APPROVED** [review]
Nice job 👍 , the code looks fine to me but have you tried if this rule actually works as expected when used as a "product" condition inside a discount promotion (like stated in the issue)?

Still find it a bit strange that a `DateRangeRule` is being used to filter down products that are applied to a promotion discount, but I guess in the end it doesn't matter because `$now` always uses the server time right now, and never the time of the customer, so this rule is basically context independent 🤷 

related user docs: https://docs.shopware.com/en/shopware-6-en/marketing/promotions#discounts

File: tests/unit/Core/Framework/Rule/DateRangeRuleTest.php (hunk 2 above)
Comment (vintagesucks) [reply tests/unit/Core/Framework/Rule/DateRangeRuleTest.php]: Regarding your main comment: Yes, I replicated the error from the issue (checkout explodes) and my initial fix resolved that. Haven't retested that manually after adding the second half (`assign()`), will check.

File: src/Core/Framework/Rule/DateRangeRule.php [hunk 3]
```diff
@@ -96,4 +96,32 @@ public function getConstraints(): array
             'timezone' => [new Timezone()],
         ];
     }
+
+    public function assign(array $options)
```
Comment (jozsefdamokos) [inline src/Core/Framework/Rule/DateRangeRule.php:100]: what does this do exactly and why is it needed?

**Review by DennisGarding — APPROVED** [review]

**Review by larskemper — APPROVED** [review]

File: src/Core/Framework/Rule/DateRangeRule.php (hunk 3 above)
Comment (vintagesucks) [reply src/Core/Framework/Rule/DateRangeRule.php:100]: after formatting the dates in `jsonSerialize()` to fix the initial issue, `match()` exploded in the admin because it still expects DateTime objects at that point:

https://github.com/shopware/shopware/blob/fca935ace10bd9ac3b1aa714d79dc861f05d8ca1/src/Core/Framework/Rule/DateRangeRule.php#L47-L51

to convert back to DateTime objects without repeating logic, I call `__wakeup()` here:

https://github.com/shopware/shopware/blob/fca935ace10bd9ac3b1aa714d79dc861f05d8ca1/src/Core/Framework/Rule/DateRangeRule.php#L34-L45

**Review by jozsefdamokos — APPROVED** [review]
