### PR TITLE
fix: no icons for media preview uploads

### LINKED ISSUE #8305: No icon for applicatio/pdf media uploads
### Shopware Version

6.7-RC1

### Affected area / extension

Platform(Default)

### Actual behaviour

Instead of an icon a broken image is shown in the backend for uploaded media files type PDF.

### Expected behaviour

Show a propper icon for pdf media files

### How to reproduce

Upload a pdf file via media manager

### PR DESCRIPTION
**Pull request by philippdinkhoff**
### 1. Why is this change necessary?
Every media preview items currently cant find the correct icon.

### 2. What does this change do, exactly?
Changed the basepath of the icons so they can find them.
From 
`/administration/static/img/media-preview/`
To
`/administration/administration/static/img/media-preview/`

Similar path like in this change:
fix: vite providing platform and extension administration assets (7349)

### 3. Describe each step to reproduce the issue or behaviour.
Upload a PDF or other filetype in the Media manager
It now has no icon and only has placeholder-text like "application/pdf" 

### 4. Please link to the relevant issues (if any).
- closes #8305 

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfill them.

### CODE REVIEW

**Review by ennasus4sun — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/app/asyncComponent/media/sw-media-preview-v2/index.js [hunk 1]
```diff
@@ -44,7 +44,7 @@ export default {
         'audio/wav',
     ],
 
-    placeholderThumbnailsBasePath: '/administration/static/img/media-preview/',
+    placeholderThumbnailsBasePath: '/administration/administration/static/img/media-preview/',
```
Comment (MalteJanz) [inline src/Administration/Resources/app/administration/src/app/asyncComponent/media/sw-media-preview-v2/index.js:47]: I guess this was missed during https://github.com/shopware/shopware/pull/7349 (that provides more context on why this change is needed)

**Review by MalteJanz — APPROVED** [review]
LGTM and great find 💪

File: src/Administration/Resources/app/administration/src/app/asyncComponent/media/sw-media-preview-v2/index.js (hunk 1 above)
Comment (MalteJanz) [reply src/Administration/Resources/app/administration/src/app/asyncComponent/media/sw-media-preview-v2/index.js:47]: Feel free to also backport to `6.7.0` because it was introduced with the change to vite in 6.7 and ideally is fixed with the final 6.7 release.

But this shouldn't be backportet to 6.6 as that version shouldn't be affected
