### PR TITLE
fix: allow reset inheritance in plugin configuration required fields

### LINKED ISSUE #5615: Plugin configuration constraint violation error when reverting to inherit values
*Description:* 

plugin configuration throws "constraint violation error" when restoring inheritance of a required config.xml field.

*Environment:* 

tested and broken with Shopware 6.5.0.0 and 6.5.3.3; we tested it locally with devenv and in an Shopware test environment for our plugin; works in 6.4.x.x

*Steps to reproduce:* 

1. Define plugin config.xml with a "required" field. 

2. Save plugin config in admin with a general value for that field 

3. Select a specific sales channel and change field value to a custom value for that sales channel (removing inheritance). Save plugin config. 

4. Restore the inheritance and save the plugin config.

*Expected result:* 

Plugin config saved.

*Actual result:*

 400 - Constraint violation error (This value should not be blank) for the field.

This error is seen with all kinds of fields (text, select..). The error is not thrown when editing optional (not-required) fields.

### PR DESCRIPTION
**Pull request by h1k3r**
### 1. Why is this change necessary?

Currently `SystemConfigService` uses null values to remove configurations, also for required fields. At the same time `SystemConfigValidator` does not allow null values for required fields.

### 2. What does this change do, exactly?

Allows null values for required fields for inherited (with channel id specified) configs.

### 3. Describe each step to reproduce the issue or behaviour.

1. Checkout affected branch
2. Reinstall system: drop all DB tables and execute bin/console system:install --basic-setup --create-database --force
3. Create new plugin bin/console plugin:create MyPlugin
4. Add new fields without default values in file `custom/plugins/MyPlugin/src/Resources/config/config.xml`

```xml
<?xml version="1.0" encoding="UTF-8"?>

<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/shopware/shopware/trunk/src/Core/System/SystemConfig/Schema/config.xsd">

    <card>
        <title>Minimal configuration</title>
        <input-field type="text">
            <name>myTextField</name>
            <label>Text field without default value</label>
            <required>true</required>
        </input-field>

        <input-field type="date">
            <name>myDateField</name>
            <label>Date field without default value</label>
        </input-field>
    </card>

</config>
```
5. Install plugin in the interface
6. Configure general value, and save
7. Configure and save values for some channel, for example Storefront
8. Restore inheritance and save 

### 4. Please link to the relevant issues (if any).

- closes https://github.com/shopware/shopware/issues/5615

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfill them.

### CODE REVIEW

File: tests/unit/Core/System/SystemConfig/Validation/SystemConfigValidatorTest.php
Comment (h1k3r) [inline tests/unit/Core/System/SystemConfig/Validation/SystemConfigValidatorTest.php:1]: `testValidateSuccess` and `testValidateFailure` do not make too much sense. They make sure that nothing breaks in the call stack when supported data structures passed, but no real validation is running, as DataValidator is mocked
```php
$dataValidatorMock = $this->createMock(DataValidator::class);
```
I am in favor or removing them (or replacing with a simple test that would make sure that validation exception is propagated). Wdyt?

File: src/Core/System/SystemConfig/Validation/SystemConfigValidator.php [hunk 1]
```diff
@@ -109,7 +112,7 @@ private function buildConstraintsWithConfigs(array $elementConfig): array
             'min' => fn (mixed $ruleValue) => new Assert\Range(['min' => $ruleValue]),
             'max' => fn (mixed $ruleValue) => new Assert\Range(['max' => $ruleValue]),
             'dataType' => fn (mixed $ruleValue) => new Assert\Type($ruleValue),
-            'required' => fn (mixed $ruleValue) => new Assert\NotBlank(),
+            'required' => fn (mixed $ruleValue) => new Assert\NotBlank(null, null, $allowNulls),
```
Comment (mitelg) [inline src/Core/System/SystemConfig/Validation/SystemConfigValidator.php:115]: you can use named parameter, so you do not need to provide the first two arguments

**Review by mitelg — APPROVED** [review]

File: src/Core/System/SystemConfig/Validation/SystemConfigValidator.php (hunk 1 above)
Comment (h1k3r) [reply src/Core/System/SystemConfig/Validation/SystemConfigValidator.php:115]: Yes, but parameter names are not covered by symfony bc promise:
> [10] Parameter names are only covered by the compatibility promise for constructors of Attribute classes. Using PHP named arguments might break your code when upgrading to newer Symfony versions.

https://symfony.com/doc/current/contributing/code/bc.html#notes

Comment (mitelg) [reply src/Core/System/SystemConfig/Validation/SystemConfigValidator.php:115]: ah, good to know :+1:

**Review by AydinHassan — APPROVED** [review]
