### PR TITLE
fix: extended associations prevent the deletion of unused media

### LINKED ISSUE #15851: Image keyword assistant prevents the deletion of unused media
### Shopware Version

6.7.8.0

### Affected area / extension

Extension:Commercial

### Actual behaviour

If the image keyword wizard is used, unused media can no longer be removed with “media:delete-unused”.  

Once media have alt text assigned to them, they are no longer recognized as unused, even if they are not used anywhere. 

### Expected behaviour

Media files that are not stored anywhere will be deleted, regardless of whether they have an alt tag.

### How to reproduce

Upload unused media and enable the image keyword assistant beforehand.  

Then wait until the alt tag has been assigned, and if necessary, change the image’s upload date in the database so that it has been in the store for more than 20 days.  

Next, run `media:delete-unused` via the console.

### PR DESCRIPTION
**Pull request by buzyka**
Closes #15851

### 1. Why is this change necessary?

`media:delete-unused` currently treats technical `media` extension associations as real usage references.

This becomes visible in `SwagCommercial`, where the image classification feature stores AI metadata through the `mediaAiTag` association. Once this association exists, the unused media search no longer considers the media item unused, even if the file is not actually assigned anywhere in products, CMS, categories, themes, or other entities.

The problem is not limited to `SwagCommercial`. Any plugin that adds technical associations to `media` can accidentally make unused files appear as used.

This prevents unused media with technical metadata, such as AI-generated alt text, from being deleted.

### 2. What does this change do, exactly?

This change introduces a dedicated DAL flag, `IgnoreInUnusedMediaSearch`, for media associations that should not be treated as actual usage references.

`UnusedMediaPurger` now skips associations marked with this flag when building the criteria for `media:delete-unused`.

This provides a generic core mechanism for plugins that add technical media associations.

`SwagCommercial` marks the `mediaAiTag` association with this flag, so the Commercial image classification feature keeps working as before, but AI metadata is no longer interpreted as business usage of the media file.

### 3. Describe each step to reproduce the issue or behaviour.

1. Enable the Commercial image keyword / image classification feature.
2. Upload a media file that is not assigned anywhere.
3. Wait until AI processing creates metadata for the file, for example alt text and `mediaAiTag` data.
4. Run `bin/console media:delete-unused --dry-run --grace-period-days=0`.
5. Before this change, the file is missing from the deletion candidates even though it is unused.
6. After this change, the file appears in the deletion candidates and can be removed.

### 4. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have updated developer-facing release notes if this change is **relevant** for external developers:
  - Add a short entry to `RELEASE_INFO-6.<major>.md` under “Upcoming” for informational changes, including the consequences of the change and how it affects external developers.
  - Add an `UPGRADE` section in `UPGRADE-6.<next-major>.md` for breaking changes (what/why/impact/how to adapt).
  - See the [Documenting a Release Process](https://github.com/shopware/shopware/blob/trunk/delivery-process/documenting-a-release.md) for details.
- [x] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Core/Framework/DataAbstractionLayer/Field/Flag/IgnoreInUnusedMediaSearch.php [hunk 1]
```diff
@@ -0,0 +1,14 @@
+<?php declare(strict_types=1);
+
+namespace Shopware\Core\Framework\DataAbstractionLayer\Field\Flag;
+
+use Shopware\Core\Framework\Log\Package;
+
+#[Package('framework')]
+class IgnoreInUnusedMediaSearch extends Flag
```
Comment (MartinKrzykawski) [inline src/Core/Framework/DataAbstractionLayer/Field/Flag/IgnoreInUnusedMediaSearch.php:11]: Nice idea, do you think a changelog entry would be good to make our merchants and third-party devs aware of this?

File: src/Core/Framework/DataAbstractionLayer/Field/Flag/IgnoreInUnusedMediaSearch.php [hunk 2]
```diff
@@ -0,0 +1,14 @@
+<?php declare(strict_types=1);
+
+namespace Shopware\Core\Framework\DataAbstractionLayer\Field\Flag;
+
+use Shopware\Core\Framework\Log\Package;
+
+#[Package('framework')]
```
Comment (MartinKrzykawski) [inline src/Core/Framework/DataAbstractionLayer/Field/Flag/IgnoreInUnusedMediaSearch.php:10]: optional: other flags have a docblock explaining the purpose. A short description could improve the dev experience

**Review by MartinKrzykawski — APPROVED** [review]

**Review by SimonVorgers — APPROVED** [review]

File: src/Core/Framework/DataAbstractionLayer/Field/Flag/IgnoreInUnusedMediaSearch.php (hunk 2 above)
Comment (buzyka) [reply src/Core/Framework/DataAbstractionLayer/Field/Flag/IgnoreInUnusedMediaSearch.php:10]: Thank you. Short dockblock added

File: src/Core/Framework/DataAbstractionLayer/Field/Flag/IgnoreInUnusedMediaSearch.php (hunk 1 above)
Comment (buzyka) [reply src/Core/Framework/DataAbstractionLayer/Field/Flag/IgnoreInUnusedMediaSearch.php:11]: Thank you for the comment,
I have added info to `RELEASE_INFO-6.7.md` in section `# 6.7.11.0 (upcoming)`. 
Do I need to add the info about changes to another file as well?

**Comment by AydinHassan** [comment]
Sorry I was on vacation and didn't get to review. I wonder if this could have been solved in a different manner like how `MediaThumbnailDefinition` is excluded via the parent/child relationship. If not, I would have probably named the flag different to not directly tie it to the media clean up process. Something like `MediaMetaData`  - which could be used by other code, as well as media cleaner.

**Comment by buzyka** [comment]
> Sorry I was on vacation and didn't get to review. I wonder if this could have been solved in a different manner like how `MediaThumbnailDefinition` is excluded via the parent/child relationship. If not, I would have probably named the flag different to not directly tie it to the media clean up process. Something like `MediaMetaData` - which could be used by other code, as well as media cleaner.


Thank you for your comment @AydinHassan 
Yes. You can reply like this:
Thanks for the suggestion. I agree that this would technically be possible by modeling the plugin entity as a child of media, similar to `MediaThumbnailDefinition`.
I did not go that way on purpose, because for a plugin this feels like a stronger semantic decision than what we actually need for this fix. Declaring a parent definition does not only affect the media cleanup logic, it also makes the entity part of the broader DAL parent/child model. For a plugin-owned table, that felt more invasive and harder to reason about than a small, explicit opt-in for the cleanup behavior.
I also think the flag approach is a better fit for third-party plugins, because it is more lightweight and does not require the plugin entity to be modeled as a true media child entity. A plugin may only want to say “this association should not count as media usage” without taking on the wider parent/child semantics.
Regarding the naming, I chose IgnoreInUnusedMediaSearch intentionally to keep the connection to the current functionality explicit. At the moment this behavior is only needed for the unused media cleanup, so I preferred the more concrete name and followed YAGNI here. If we later see a real second use case for a more general concept, we can still introduce a broader flag and deprecate this one in a controlled way.
