### PR TITLE
fix: Updated child order line item quantity on parent quantity change

### LINKED ISSUE #6211: Change Quantity on OrderLineItems does not update Child Items
Description: See attached unittest

Environment: any
Steps to reproduce: run unittest or do the steps in the Browser.
1. Create parent product
2. Create child product
3. Connect parent and child product
4. Order the parent product
5. As admin change the order, modify the quantity of the lineitem
6. The modify works, reaches the database and writes the new value. But forgets to update the quantity on the child product
7. The recalculate Order request which is triggered after the save finds the wrong quantity and bugs out.

Expected result: As in the test. Correctly updated quantities

Actual result: Childitems are neglected. :(

### PR DESCRIPTION
**Pull request by cyl3x**
fixes #6211

### 1. Why is this change necessary?
When changing the quantity of an order line that has children/nested items via the administration order page, an error complaining about a quantity mismatch will occur. This happens because the quantity of a child item needs to be a multiple of the parent, but the administration misses updating all the children accordingly.

### 2. What does this change do, exactly?
Update all children of a line item recursively, like [LineItem::refreshChildQuantity](https://github.com/shopware/shopware/blob/e62f7a52beb127cb38216aedf4e65e536042a2be/src/Core/Checkout/Cart/LineItem/LineItem.php#L609) does.

### 3. Describe each step to reproduce the issue or behaviour.
1. Place an order with an item that includes a child
2. (or - place an order with two line items and change one order line item in the DB to have a parentId of the other)
3. Attempt to update the quantity of the line item via the administration order detail page
 
### 4. Please link to the relevant issues (if any).

- fixes #6211 

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfill them.

### CODE REVIEW

**Review by Bird87ZA — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-line-items-grid/index.js [hunk 1]
```diff
@@ -408,12 +408,24 @@ export default {
             return get(item, 'price.calculatedTaxes') && item.price.calculatedTaxes.length > 1;
         },
 
-        updateItemQuantity(item) {
-            if (item.type !== this.lineItemTypes.CUSTOM) {
-                return;
-            }
+        updateItemQuantity(item, newQuantity = item.quantity) {
```
Comment (lernhart) [inline src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-line-items-grid/index.js]: BC?

**Review by lernhart — CHANGES_REQUESTED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-line-items-grid/index.js (hunk 1 above)
Comment (cyl3x) [reply src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-line-items-grid/index.js]: Maybe, but I don't think so - signature wise it's a new optional param, but the functions' behaviour changed. Also compared to before the quantity is changed here instead of via `v-model`. The worst case would be that someone has a copy of that number field block in his extension and .. okay, it's not exactly the old behaviour, as the child quantity update breaks - I'll update that

**Review by mstegmeyer — APPROVED** [review]

**Review by lernhart — APPROVED** [review]
