### PR TITLE
fix: properly restore content slot overrides and clear module states

### LINKED ISSUE #6948: Unable to remove images from CMS Element "Image Slider" in category tab layout
*PHP Version:* 8.3   | *Shopware Version:* 6.6.10.0  | *Affected area / extension:* Platform(Default) 

 ----

*_Actual behaviour:_*

When trying to remove images from the CMS element "Image Slider" in the category tab layout, the deletion does not work as expected. Even after removing an image and saving the changes, the image remains in the slider.

Image

*_Expected behaviour:_*

The expected behavior is that when a user removes an image from the CMS element "Image Slider" in the category tab layout and saves the changes, the image should be permanently removed from the slider for this category.

*_How to reproduce:_*

1. Go to the Shopware Admin panel.
2. Navigate to Shopping Experiences
3. Create layout and place Image Slider element
4. Assign layout to a category
5. Open the category that includes the Image Slider element and go to layout tab.
6. Click on the Image Slider element image to edit it.
7. Remove one or more images from the slider.
8. Click Save and refresh the category.
9. Check that the removed images are still present in the slider.

Issue: The removed images reappear in the slider, indicating that the deletion is not being saved properly.

### PR DESCRIPTION
**Pull request by bschulzebaek**
### 1. Why is this change necessary?
CMS slot configs are not initialized properly in the admin, meaning that in many cases a "config override" on product or category default pages would be overriden by the config created in the default language, or by the shared config created in the cms module. 

### 2. What does this change do, exactly?
Properly merge CMS slot configs from different sources, correctly load configs from translations.

### 4. Please link to the relevant issues (if any).
- #6948 
- #10898 
- #10537 
- #8696
- #7826
- #7023
- #6948
- #6248

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Administration/Resources/app/administration/src/module/sw-cms/page/sw-cms-detail/index.js [hunk 1]
```diff
@@ -351,12 +350,19 @@ export default {
...
+        },
+
         setPageContext() {
             this.getDefaultFolderId().then((folderId) => {
                 this.cmsPageState.setDefaultMediaFolderId(folderId);
             });
         },
 
+        /**
+         * @deprecated: v6.8.0 - Replaced by "resetRelatedStores" method
```
Comment (MartinKrzykawski) [inline src/Administration/Resources/app/administration/src/module/sw-cms/page/sw-cms-detail/index.js]: Please add your deprecations into a changelog :)

**Review by MartinKrzykawski — APPROVED** [review]
LGTM - Would be great if you could add your deprecation into a changelog, otherwise we can merge it :)

File: src/Administration/Resources/app/administration/src/module/sw-cms/mixin/sw-cms-element.mixin.ts [hunk 2]
```diff
@@ -94,8 +112,23 @@ export default Mixin.register(
                 return this.cmsService.getPropertyByMappingPath(this.cmsPageState.currentDemoEntity, mappingPath);
             },
 
+            getEntitySlotConfig() {
+                const entity = this.category ?? this.product;
```
Comment (MartinKrzykawski) [inline src/Administration/Resources/app/administration/src/module/sw-cms/mixin/sw-cms-element.mixin.ts]: just for understanding: why do you prioritize the category config over the product config?

**Review by MartinKrzykawski — APPROVED** [review]

**Review by dgrothaus-sw — APPROVED** [review]
I really like the comments in places where confusion could occur.
