### PR TITLE
fix: Seo url not generating anymore

### LINKED ISSUE #10513: SEO url not generating anymore, message: "There are no SEO URLs yet"
### Shopware Version

6.6.10.1

### Affected area / extension

Platform(Default)

### Actual behaviour

It's not generating a SEO url after pressing save, this problem happend after changing urls from the main and variant product.

### Expected behaviour

It should generate the URL based on the settings provided after pressing save.

### How to reproduce

The main product had the url set to "houten-jaloezieen/63mm/" and one of the variants had "houten-jaloezieen/63mm/zwart-6321/". After changing the variant to houten-jaloezieen/63mm/ and saving it, the main product url went to 63mm/6320.P/ (6320.P is the main product productnumber). Then I changed that one back to houten-jaloezieen/63mm/. After saving, I bricked the seo url generation, it keeps showing "There are no SEO URLs yet." after saving it multiple times:

Image

I also changed back to variant to it's previous URL, that didn't work. 

Here is a dump of my seo_url table:
[seo_url.txt](https://github.com/user-attachments/files/20723658/seo_url.txt)

There seems to be an underlying issue somewhere with SEO urls/variants (I read 2 other Github issues about it), I did all of the above because I wanted to reproduce another SEO url issue I had earlier (one product having 2 working urls, while "Instead of setting canonical URLs, redirect to the most recent URL via HTTP 301." is activated. Also someone else mentioned in the Slack channel he had issues with variants and SEO urls.

Edit:
Something to look into right away together with the issue is the url(s) containing "nova", there is a product that has 2 URLs "houten-jaloezieen/nova/" and "houten-jaloezieen/nova/zwart-5021/". Thats what I tried to reproduce but ran into the bricked seo url generation. Could be related to each other maybe. 

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by tamvt**
This pull request addresses a bug in the SEO URL generation process by updating the `updateSeoUrls` method in the `SeoUrlPersister` class and introducing new methods to handle canonical SEO URLs.

### Bug Fixes and Enhancements to SEO URL Handling:
* Modified `updateSeoUrls` in `SeoUrlPersister` to update the `is_canonical` and `is_modified` fields for default SEO URLs when a foreign key's SEO URL is replaced or deleted. This ensures that canonical URLs are preserved correctly.
* Added a new private method `findInuseSeoUrls` to fetch existing canonical SEO URLs based on `seoPathInfo`.
* Introduced another private method `updateDefaultSeoUrls` to identify and update the earliest valid SEO URL as the default, setting its `is_canonical` and `is_modified` fields to `true`.

### Before

https://github.com/user-attachments/assets/6639c262-28d2-49c5-b78e-2b681a6ff844

### After

https://github.com/user-attachments/assets/89add368-bc93-44d9-b01d-0e136d221fee

### CODE REVIEW

**Review by nguyenytran — APPROVED** [review]

File: src/Core/Content/Seo/SeoUrlPersister.php [hunk 1]
```diff
@@ -105,6 +108,8 @@ public function updateSeoUrls(Context $context, string $routeName, array $foreig
             $insertQuery->addInsert($this->seoUrlRepository->getDefinition()->getEntityName(), $insert);
         }
 
+        $inuseSeoUrls = $this->findInuseSeoUrls($seoPathInfos);
```
Comment (mitelg) [inline src/Core/Content/Seo/SeoUrlPersister.php]:
```suggestion
        $unusedSeoUrls = $this->findUnusedSeoUrls($seoPathInfos);
```

File: src/Core/Content/Seo/SeoUrlPersister.php [hunk 2]
```diff
@@ -179,6 +190,69 @@ private function findCanonicalPaths(string $routeName, string $languageId, array
...
+            ['seoPathInfos' => ArrayParameterType::BINARY]
+        );
+    }
+
+    /**
+     * Find the earliest valid SEO URL created. This means it is the default SEO URL and update the `is_canonical` and `is_modified` fields.
+     *
+     * @param array<array<string, mixed>> $seoUrls
+     */
+    private function updateDefaultSeoUrls(array $seoUrls): void
```
Comment (vienthuong) [inline src/Core/Content/Seo/SeoUrlPersister.php]:
```suggestion
    private function updateCanonicalSeoUrls(array $seoUrls): void
```

File: src/Core/Content/Seo/SeoUrlPersister.php (hunk 1 above)
Comment (vienthuong) [reply src/Core/Content/Seo/SeoUrlPersister.php]: I think she meant the opposite 😅 I'd name it `findInUseCanonicalSeoUrls`

Comment (mitelg) [reply src/Core/Content/Seo/SeoUrlPersister.php]: ah okay :bulb:

File: src/Core/Content/Seo/SeoUrlPersister.php [hunk 3]
```diff
@@ -179,6 +191,69 @@ private function findCanonicalPaths(string $routeName, string $languageId, array
...
+        $ids = [];
+        foreach ($seoUrls as $seoUrl) {
+            $id = $this->connection->fetchOne(
+                'SELECT HEX(id) AS id
+                 FROM seo_url
+                 WHERE language_id = :languageId
+                   AND foreign_key = :foreignKey
+                   AND sales_channel_id = :salesChannelId
+                   AND route_name = :routeName
+                   AND is_canonical IS NULL
```
Comment (vienthuong) [inline src/Core/Content/Seo/SeoUrlPersister.php]:
```suggestion
                   AND is_canonical IS NULL AND is_deleted = 0
```

**Review by vienthuong — APPROVED** [review]

**Review by jc-sw-git — APPROVED** [review]
