### PR TITLE
fix: Don't generate new ID for non PK id fields

### LINKED ISSUE #6242: IdField isn't nullable
*PHP Version:* 8.2   | *Shopware Version:* 6.6.9.0  | *Affected area / extension:* Platform(Default) 

 ----

*_Actual behaviour:_*

Have some kind of entity with an IdField that's neither flagged as primary nor as required, update the entity

```
$this->someRepo->update(['id' => '019464e1dddf74b5be7858e03d8bf2bc', 'idField' => null]);
```

if you then check that entity, the id field will have some random new UUID in it

*_Expected behaviour:_*

idField will be null

*_How to reproduce:_*

expand the tests added [here](https://github.com/shopware/shopware/commit/0b32b62491762b3e0e8977a9d2354703b06f4283) to actually make sure null is respected, right now the normalizer will overwrite null with some new random uuid

https://github.com/shopware/shopware/blob/051d3feee65661b7196c9a2daaeb548f606db34e/src/Core/Framework/DataAbstractionLayer/FieldSerializer/IdFieldSerializer.php#L27-L29

### PR DESCRIPTION
**Pull request by keulinho**
Jira ticket: https://shopware.atlassian.net/browse/NEXT-40277 
Fixes https://github.com/shopware/shopware/issues/6242

Add test case to try to reproduce #6242

@phit can you maybe add a reproducer test case here, as the simple example seems to be working

### CODE REVIEW

File: tests/unit/Core/Framework/DataAbstractionLayer/FieldSerializer/IdFieldSerializerTest.php [hunk 1]
```diff
@@ -54,48 +54,76 @@ public function testSerializer(Field $field, ?string $value, ?string $expected =
...
+
+        $encoded = iterator_to_array($serializer->encode($field, $existence, $kv, $params));
+
+        static::assertArrayHasKey('media_id', $encoded);
+
+        static::assertTrue(Uuid::isValid(Uuid::fromBytesToHex($encoded['media_id'])));
+    }
 
-        yield 'field is pk and specified (should not be generated)' => [
+    public static function idShouldBeGeneratedCasesProvider(): \Generator
```
Comment (mitelg) [inline tests/unit/Core/Framework/DataAbstractionLayer/FieldSerializer/IdFieldSerializerTest.php:95]: you are missing the case where it neither PK or required, like described in the ticket. that is also the question, if this is intended to be supported :thinking:

Comment (keulinho) [reply tests/unit/Core/Framework/DataAbstractionLayer/FieldSerializer/IdFieldSerializerTest.php:95]: that case is covered in the other testcase generator ;) 

I now added a integration test that uses the repo to write and read and it is working as expected, looking at the change needed I see no reason to not support it, as we already tried to support it

File: tests/integration/Core/Framework/DataAbstractionLayer/Reader/EntityReaderTest.php [hunk 2]
```diff
@@ -2214,8 +2216,14 @@ public function testSearchWithNonIdPK(): void
             ],
             [
                 'testField' => $id2,
+                'nonPk' => null,
                 'name' => 'test2',
             ],
+            [
+                'testField' => $id3,
```
Comment (keulinho) [inline tests/integration/Core/Framework/DataAbstractionLayer/Reader/EntityReaderTest.php:2223]: not the most obvious place to test this, but ok IMHO

The entityRepositoryTest currently uses only existing definitions to test things, I didn't want to make that test more complicated by doing schema changes and registering custom test definitions

File: tests/integration/Core/Framework/DataAbstractionLayer/Reader/EntityReaderTest.php [hunk 3]
```diff
@@ -2639,4 +2659,8 @@ public static function casesToManyReadPaginatedInherited(): iterable
             'variant-main',
         ];
     }
+
+    public function testNonPkIdFieldIsNotAutofilled(): void
```
Comment (mitelg) [inline tests/integration/Core/Framework/DataAbstractionLayer/Reader/EntityReaderTest.php]: can this be removed again?

**Review by mitelg — APPROVED** [review]

**Review by AydinHassan — APPROVED** [review]

**Review by shyim — APPROVED** [review]
