### PR TITLE
fix: Use agnostic language layer functionality when loading snippets

### LINKED ISSUE #12732: Country-Agnostic languages are not loaded in Snippet Module
### Shopware Version

Trunk

### Affected area / extension

Platform(Default)

### Actual behaviour

When selecting british english or german, snippets are not loaded. Renaming them back to "en-GB" fixes the issue. Probably the file selection is wrong.

Update: This has been "fixed" with [this PR](https://github.com/shopware/shopware/pull/12695/files), but this is only a duct tape solution. The agnostic language layer functionality should function there as well, checking at first the specific locale like `de-AT` and then falling back to `de`.

### Expected behaviour

Snippets should be loaded

### How to reproduce

- Go to Snippets Module
- Select en-GB

### PR DESCRIPTION
**Pull request by taltholtmann**
### 4. Please link to the relevant issues (if any).

closes #12732

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Core/System/Snippet/SnippetService.php [hunk 1]
```diff
@@ -306,6 +306,15 @@ private function getSnippetsByLocale(SnippetFileCollection $snippetFileCollectio
     }
 
     /**
+     *  Collects snippet files for each given locale (ISO code).
```
Comment (marcelbrode) [inline src/Core/System/Snippet/SnippetService.php]:
```suggestion
     *  Collects snippet files for each given locale
```
I'm not that much of a fan of "ISO code" and would like to avoid it as much es possible. ISO code is like "Yeah, there's a standard behind it, but I don't tell you which".

Very personal opinion, feel free to just resolve this.

File: src/Core/System/Snippet/SnippetService.php [hunk 2]
```diff
@@ -306,6 +306,15 @@ private function getSnippetsByLocale(SnippetFileCollection $snippetFileCollectio
...
+     *
+     *  For each locale (e.g., "en-GB"), the method first tries to load files
+     *  that match the exact locale. If that locale contains a region separator ("-"),
+     *  it will also load files for the base language (e.g., "en").
+     *
+     *  The base-language snippet files are prepended, ensuring region-specific
+     *  snippets (e.g., "en-GB") override more general ones ("en").
```
Comment (marcelbrode) [inline src/Core/System/Snippet/SnippetService.php]:
```suggestion
     *  The base language snippet files are prepended, ensuring country-specific
     *  snippets (e.g. "en-GB") override more general ones ("en").
```

File: src/Core/System/Snippet/SnippetService.php [hunk 3]
```diff
@@ -314,12 +323,24 @@ private function getSnippetFilesByIso(array $isoList): array
...
-                'en-GB' => 'en',
-                default => $iso,
-            };
-            $result[$iso] = $this->snippetFileCollection->getSnippetFilesByIso($mappedIso);
+            // Load all snippet files that match the exact locale (e.g., "en-GB")
+            $files = $this->snippetFileCollection->getSnippetFilesByIso($iso);
+
+            // If the locale has a region (e.g., "de-AT"), try to load its base language ("de")
+            if (\str_contains($iso, '-')) {
+                [$baseIso] = \explode('-', $iso, 2);
```
Comment (marcelbrode) [inline src/Core/System/Snippet/SnippetService.php]: Please use `\Shopware\Core\System\Snippet\SnippetPatterns` and preg_match instead.

File: src/Core/System/Snippet/SnippetService.php [hunk 4]
```diff
@@ -314,12 +323,23 @@ private function getSnippetFilesByIso(array $isoList): array
...
+            preg_match(
+                SnippetPatterns::COMPLETE_LOCALE_PATTERN,
+                $iso,
+                $matchedPattern,
+                \PREG_UNMATCHED_AS_NULL
+            );
+
+            // If the locale has a region (e.g., "es-AR"), try to load its base language ("es")
+            if (!empty($matchedPattern['region']) && strtolower($matchedPattern['region']) !== $iso) {
+                $fallbackFiles = $this->snippetFileCollection->getSnippetFilesByIso($matchedPattern['language']);
```
Comment (marcelbrode) [inline src/Core/System/Snippet/SnippetService.php:339]:
```suggestion
                \assert(!empty($matchedPattern['language']));
                \assert(!empty($matchedPattern['region']));
                $fallbackFiles = $this->snippetFileCollection->getSnippetFilesByIso($matchedPattern['language']);
```

Recommend fixing PhpStand like this :)

File: tests/unit/Core/System/Snippet/SnippetServiceTest.php [hunk 5]
```diff
@@ -307,6 +311,118 @@ public static function getStorefrontSnippetsDataProvider(): \Generator
...
+    #[DataProvider('getListDataProvider')]
+    public function testGetList(string $iso, array $expectedSnippets): void
+    {
+        $availableFixtures = [
+            'base.es',
+            'country.es-AR',
+            'country.fr-CA',
+            'base.zh',
+            'country.zh-Hans-CN',
+        ];
```
Comment (marcelbrode) [inline tests/unit/Core/System/Snippet/SnippetServiceTest.php:325]:
```suggestion
        $availableFixtures = [
            'agnostic.es',
            'country.es-AR',
            'country.fr-CA',
            'agnostic.zh',
            'country.zh-Hans-CN',
        ];
```

File: tests/unit/Core/System/Snippet/SnippetServiceTest.php [hunk 6]
```diff
@@ -307,6 +311,118 @@ public static function getStorefrontSnippetsDataProvider(): \Generator
...
+
+        $baseIso = \explode('-', $iso, 2)[0];
+
+        $baseFileName = 'base.' . $baseIso;
```
Comment (marcelbrode) [inline tests/unit/Core/System/Snippet/SnippetServiceTest.php]:
```suggestion
        $baseFileName = 'agnostic.' . $baseIso;
```

File: tests/unit/Core/System/Snippet/SnippetServiceTest.php [hunk 7]
```diff
@@ -307,6 +311,118 @@ public static function getStorefrontSnippetsDataProvider(): \Generator
...
+            ],
+        ];
+
+        yield 'country es-EM does not exist - only base es exists' => [
+            'iso' => 'es-EM',
+            'expectedSnippets' => [
+                'title' => 'Base ES',
+                'baseOnly' => 'Base ES',
+            ],
+        ];
```
Comment (marcelbrode) [inline tests/unit/Core/System/Snippet/SnippetServiceTest.php]:
```suggestion
        yield 'agnostic locale es without country' => [
            'iso' => 'es',
            'expectedSnippets' => [
                'title' => 'Agnostic ES',
                'baseOnly' => 'Agnostic ES',
            ],
        ];

        yield 'es-AR iso falls back to es' => [
            'iso' => 'es-AR',
            'expectedSnippets' => [
                'title' => 'Country es-AR',
                'baseOnly' => 'Agnostic ES',
            ],
        ];

        yield 'country exists without base' => [
            'iso' => 'fr-CA',
            'expectedSnippets' => [
                'title' => 'Country fr-CA',
            ],
        ];

        yield 'country es-EM does not exist - only base es exists' => [
            'iso' => 'es-EM',
            'expectedSnippets' => [
                'title' => 'Agnostic ES',
                'baseOnly' => 'Agnostic ES',
            ],
        ];
```

**Review by marcelbrode — CHANGES_REQUESTED** [review]

**Review by marcelbrode — APPROVED** [review]

File: src/Core/System/Snippet/SnippetService.php [hunk 8]
```diff
@@ -314,12 +323,25 @@ private function getSnippetFilesByIso(array $isoList): array
...
+            preg_match(
+                SnippetPatterns::COMPLETE_LOCALE_PATTERN,
+                $iso,
+                $matchedPattern,
+                \PREG_UNMATCHED_AS_NULL
+            );
+
+            // If the locale has a region (e.g., "es-AR"), try to load its base language ("es")
+            if (!empty($matchedPattern['region']) && strtolower($matchedPattern['region']) !== $iso) {
+                \assert(!empty($matchedPattern['language']));
```
Comment (MartinKrzykawski) [inline src/Core/System/Snippet/SnippetService.php:337]: `assert` is more of a dev tool and is not a real error handling in production. You should throw an exception if language is not set.

File: src/Core/System/Snippet/SnippetService.php [hunk 9]
```diff
@@ -314,12 +323,25 @@ private function getSnippetFilesByIso(array $isoList): array
...
+                \assert(!empty($matchedPattern['region']));
```
Comment (MartinKrzykawski) [inline src/Core/System/Snippet/SnippetService.php:338]: is this assert not obsolete since you already validated in your if condition that region is not empty?

File: tests/unit/Core/System/Snippet/SnippetServiceTest.php [hunk 10]
```diff
@@ -307,6 +311,118 @@ public static function getStorefrontSnippetsDataProvider(): \Generator
...
+            snippetSetRepository: $snippetSetRepository,
+            snippetFileCollection: $snippetCollection,
+            connection: $this->connection,
+        );
+
+        $context = Context::createDefaultContext();
+        $result = $service->getList(1, 10, $context, [], []);
+
+        // Assert the total count matches the number of expected translation keys
+        static::assertSame(\count($expectedSnippets), $result['total']);
```
Comment (MartinKrzykawski) [inline tests/unit/Core/System/Snippet/SnippetServiceTest.php:377]: please use `assertCount()` instead

File: tests/unit/Core/System/Snippet/SnippetServiceTest.php [hunk 11]
```diff
@@ -315,16 +431,38 @@ private function addThemes(): void
...
         ?EventDispatcherInterface $eventDispatcher = null,
+        ?EntityRepository $snippetRepository = null,
+        ?EntityRepository $snippetSetRepository = null,
+        ?SnippetFileCollection $snippetFileCollection = null,
+        ?Connection $connection = null,
+        ?SnippetFilterFactory $snippetFilterFactory = null,
+        ?ExtensionDispatcher $extensionDispatcher = null
     ): SnippetService {
+        // Use provided or fall back to sensible defaults and mocks.
+        $snippetRepository = $snippetRepository ?? $this->createMock(EntityRepository::class);
```
Comment (MartinKrzykawski) [inline tests/unit/Core/System/Snippet/SnippetServiceTest.php]: Please do not mock the EntityRepository and use the `StaticEntityRepository` instead

File: tests/unit/Core/System/Snippet/SnippetServiceTest.php [hunk 12]
```diff
@@ -315,16 +431,38 @@ private function addThemes(): void
         $this->snippetCollection->add(new MockSnippetFile('swagtheme.en', 'en', '{}', true, 'SwagTheme'));
     }
 
+    /**
+     * All parameters are optional. When provided they override defaults.
+     *
+     * @param StaticEntityRepository<SnippetCollection>|null $snippetRepository
+     * @param StaticEntityRepository<SnippetSetCollection>|null $snippetSetRepository
+     *
+     * @throws Exception
```
Comment (MartinKrzykawski) [inline tests/unit/Core/System/Snippet/SnippetServiceTest.php]: throws exception does not have a real added-value IMO - just delete it or specify the thrown exception

File: tests/unit/Core/System/Snippet/SnippetServiceTest.php [hunk 13]
```diff
@@ -307,6 +311,118 @@ public static function getStorefrontSnippetsDataProvider(): \Generator
         ];
     }
 
+    /**
+     * @param array<string,string> $expectedSnippets
+     *
+     * @throws Exception
```
Comment (MartinKrzykawski) [inline tests/unit/Core/System/Snippet/SnippetServiceTest.php]: throws exception does not have a real added-value IMO - just delete it or specify the thrown exception

**Review by MartinKrzykawski — CHANGES_REQUESTED** [review]

File: src/Core/System/Snippet/SnippetService.php (hunk 9 above)
Comment (taltholtmann) [reply src/Core/System/Snippet/SnippetService.php:338]: you are right

File: src/Core/System/Snippet/SnippetService.php (hunk 8 above)
Comment (taltholtmann) [reply src/Core/System/Snippet/SnippetService.php:337]: I removed the asserts and added a check in the if. I dont think we need an exception, we can just skip adding the base file if the language is not set.

File: tests/unit/Core/System/Snippet/SnippetServiceTest.php (hunk 10 above)
Comment (taltholtmann) [reply tests/unit/Core/System/Snippet/SnippetServiceTest.php:377]: but total is already an integer. it does not need to be counted. I will continue with assertSame

**Review by dgrothaus-sw — APPROVED** [review]

**Review by MartinKrzykawski — APPROVED** [review]
