### PR TITLE
fix: Add default entity to property collection in sales channel detail

### LINKED ISSUE #10115: Selecting a default sales channel detail entities, won't add it to the general list
### Shopware Version

6.7.0.0-RC5

### Affected area / extension

Platform(Default)

### Actual behaviour

Countries/languages/currencies/payment methods/shipping methods are not visually added, when selected with the defaults dropdown but are there when you save.

### Expected behaviour

Either, the default dropdown should not include those entities, which aren't in already select in the full list OR selected entities should be visually added to the list of entities.

### How to reproduce

Go to sales channel detail, select new languages or countries from defaults dropdown. (Also happens with payment methods, shipping methods and currencies)

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by MartinKrzykawski**
Closes #10115

### 1. Why is this change necessary?
Countries, languages, currencies, payment and shipping methods are not visually added, when selected with the defaults dropdown in the sales channel detail page.

### 2. What does this change do, exactly?
Previously, the default item was only added to the propertyCollection (the element list), but since propertyCollection is not reactive, the component wasn’t updated. I changed the logic to reassign propertyCollection to the main property to trigger a reload and ensure the component refreshes properly.

Bildschirmfoto 2025-06-12 um 10 34 17

### 3. Describe each step to reproduce the issue or behaviour.
1. Open sales channel detail page in admin
2. Select a new default value for countries, languages, currencies, payment or shipping methods that is not included in the general list.
3. The default has been added to the general list.

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Administration/Resources/app/administration/src/module/sw-sales-channel/component/sw-sales-channel-defaults-select/index.js [hunk 1]
```diff
@@ -210,7 +210,7 @@ export default {
             this.defaultId = defaultId;
 
             if (!!defaultId && !this.propertyCollection.has(defaultId)) {
-                this.propertyCollection.add(defaultEntity);
+                this.propertyCollection = this.propertyCollection.concat([defaultEntity]);
```
Comment (marcelbrode) [inline src/Administration/Resources/app/administration/src/module/sw-sales-channel/component/sw-sales-channel-defaults-select/index.js:213]: Does `push` work instead? This would not create a new array

Comment (MartinKrzykawski) [reply src/Administration/Resources/app/administration/src/module/sw-sales-channel/component/sw-sales-channel-defaults-select/index.js:213]: no, it does not - it has to be a new array because otherwise it does not trigger the refresh

Comment (marcelbrode) [reply src/Administration/Resources/app/administration/src/module/sw-sales-channel/component/sw-sales-channel-defaults-select/index.js:213]: Ah, okay. Makes sense! 👍

**Review by marcelbrode — APPROVED** [review]

**Review by bschulzebaek — APPROVED** [review]
