### PR TITLE
fix(link-category): Implement redirect behaviour on link categories

### LINKED ISSUE #10294: Link that points to a category with type = link --> external doesn't work
### Shopware Version

6.6.10.4

### Affected area / extension

Platform(Default)

### Actual behaviour

If you set up a link (in product description or somewhere in a cms layout) that points to a category which uses the configuration `link type = external`, you'd end up in the category (which leads to an error 404) but are not being forwarded to the defined link destination. 

To summarize, the procedure should be as follows:
Click link in product description --> forwards to a category --> should forward to link destination (last stept doesn't work) 

Configurations look as follows:

Image

Image

### Expected behaviour

Clicking the link would forward to external link which has been defined in the category.

### How to reproduce

1. Open random category and make sure to set the link type = external 
2. Define link destination (make sure to use https:// if not using relative path)
3. Open random product and add link which points to category used in step 1
4. Open storefront and click link

result: you are just being forwarded to the category and an error 404 will show. Forwarding to the link destination doesn't take place

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by marcelbrode**
fixes #10294

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfill them.

### CODE REVIEW

**Review by MartinKrzykawski — APPROVED** [review]

**Review by ravenokko — APPROVED** [review]

File: src/Core/Content/Category/CategoryException.php [hunk 1]
```diff
@@ -21,6 +21,9 @@ public static function pageNotFound(string $pageId): ShopwareHttpException
         return new PageNotFoundException($pageId);
     }
 
+    /**
+     * @deprecated tag:v6.8.0 - reason:return-type-change - Will return self instead
+     */
     public static function categoryNotFound(string $id): ShopwareHttpException
     {
         return new CategoryNotFoundException($id);
```
Comment (dgrothaus-sw) [inline src/Core/Content/Category/CategoryException.php]:
```suggestion
        if (!Feature::isActive('v6.8.0.0')) {
            return new CategoryNotFoundException($id);
        }

        return new self(
            Response::HTTP_BAD_REQUEST,
            self::CATEGORY_NOT_FOUND,
            'Category "{{ categoryId }}" not found.',
            ['categoryId' => $id]
        );
```

Comment (dgrothaus-sw) [reply src/Core/Content/Category/CategoryException.php]: Plus `public const CATEGORY_NOT_FOUND = 'CONTENT__CATEGORY_NOT_FOUND';`

**Review by dgrothaus-sw — CHANGES_REQUESTED** [review]
Good PR. Link now works as intended. Just one little suggestion from my side.

**Review by dgrothaus-sw — APPROVED** [review]

**Review by MartinKrzykawski — APPROVED** [review]
