### PR TITLE
fix: reset document selection state between bulk edits

### LINKED ISSUE #14360: Incorrect document generation via multiple changes (invoice + delivery note)
### Shopware Version

6.7.5.1

### Affected area / extension

Platform(Default)

### Actual behaviour

If an invoice is generated for orders using bulk edit, and then a delivery note is generated for another orders using bulk edit, an invoice will automatically be created for the delivery note in the second case.

This only occurs if invoices have been generated for other orders beforehand.

### Expected behaviour

.

### How to reproduce

.

### PR DESCRIPTION
**Pull request by vintagesucks**
resolves #14360

Resets document type `isChanged` when entering bulk edit to prevent previous selections from persisting across sessions.

### CODE REVIEW

File: src/Administration/Resources/app/administration/src/module/sw-bulk-edit/page/sw-bulk-edit-order/index.js [hunk 1]
```diff
@@ -251,6 +251,7 @@ export default {
     methods: {
         async createdComponent() {
             this.setRouteMetaModule();
+            this.resetOrderDocumentsIsChanged();
```
Comment (larskemper) [inline src/Administration/Resources/app/administration/src/module/sw-bulk-edit/page/sw-bulk-edit-order/index.js]: nit: you could also just call the Store here directly, no need for an extra method


```suggestion
            Shopware.Store.get('swBulkEdit').resetOrderDocumentsIsChanged();
```

**Review by larskemper — APPROVED** [review]

**Review by jozsefdamokos — APPROVED** [review]

**Review by cyl3x — APPROVED** [review]
