### PR TITLE
fix: promotion order count update

### LINKED ISSUE #10774: Promotion usage count increases incorrectly when applied to both products and shipping
### Shopware Version

6.6.10.4

### Affected area / extension

Platform(Default)

### Actual behaviour

When a promotion applies a discount to both product line items and shipping costs, the promotion’s usage count (order_count) increases by more than one per order. This leads to incorrect tracking of promotion usage.

PromotionRedemptionUpdater L72

### Expected behaviour

The promotion’s usage should only increase once per order, regardless of how many line items or discount targets are affected.

### How to reproduce

1.	Create a promotion with:
	Scope: Entire cart
	Discounts: One for product(s), one for shipping
	Global usage limit: e.g. 5
2.	Place one order where both discounts are applied.
3.	Observe that the usage counter increases by 2 instead of 1.

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by En0Ma1259**
### 1. Why is this change necessary?
When a promotion applies a discount to both product line items and shipping costs, the promotion’s usage count (order_count) increases by more than one per order. This leads to incorrect tracking of promotion usage.

### 2. What does this change do, exactly?
The “index” update method is used to create and delete promotion items.
Before a promotion item is deleted, we search for the promotion ID. After deletion, all these promotions are updated.

**Administration**: Promotions will be grouped now on order detail page.

### 3. Describe each step to reproduce the issue or behaviour.

Create a promotion with:
Scope: Entire cart
Discounts: One for product(s), one for shipping
Global usage limit: e.g. 5
Place one order where both discounts are applied.
Observe that the usage counter increases by 2 instead of 1.

### 4. Please link to the relevant issues (if any).
- fixes https://github.com/shopware/shopware/issues/10774

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Core/Checkout/Promotion/DataAbstractionLayer/PromotionRedemptionUpdater.php [hunk 1]
```diff
@@ -102,292 +146,31 @@ public function update(array $ids, Context $context): void
...
-                'customerCount' => json_encode($totals, \JSON_THROW_ON_ERROR),
+                'count' => (int) array_sum($totals),
+                'customerCount' => !empty($totals) ? json_encode($totals, \JSON_THROW_ON_ERROR) : null,
             ]);
-
-            $this->processedPromotions[$id] = true;
-        }
-    }
-
-    public function orderUpdated(EntityWrittenEvent $event): void
```
Comment (En0Ma1259) [inline src/Core/Checkout/Promotion/DataAbstractionLayer/PromotionRedemptionUpdater.php:117]: Will deprecate it

File: src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-promotion-field/index.js [hunk 2]
```diff
@@ -417,16 +428,9 @@ export default {
...
-            });
-
-            await this.saveAndReload();
+            this.order.lineItems = this.order.lineItems.filter(item => item.type !== 'promotion' && item.promotionId !== removedItem.promotionId);
 
-            return this.orderLineItemRepository
-                .delete(lineItem.id, this.versionContext)
-                .then(this.emitEntityData.bind(this))
-                .catch(this.handleError.bind(this));
+            await this.$emit('save-and-recalculate');
```
Comment (cyl3x) [inline src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-promotion-field/index.js]: please use provide/inject instead, it should be primary way to interact

File: src/Administration/Resources/app/administration/src/module/sw-order/view/sw-order-detail-general/sw-order-detail-general.html.twig [hunk 3]
```diff
@@ -166,6 +166,7 @@
             @loading-change="updateLoading"
             @reload-entity-data="reloadEntityData"
             @save-and-reload="saveAndReload"
+            @save-and-recalculate="saveAndRecalculate"
```
Comment (cyl3x) [inline src/Administration/Resources/app/administration/src/module/sw-order/view/sw-order-detail-general/sw-order-detail-general.html.twig]: s.a.

File: src/Core/Checkout/Promotion/DataAbstractionLayer/PromotionRedemptionUpdater.php [hunk 4]
```diff
@@ -4,60 +4,102 @@
...
+            }
+        }
+
+        if (empty($lineItemsIds)) {
+            return;
+        }
+
+        $sql = <<<SQL
+            SELECT LOWER(HEX(`promotion_id`)) FROM `order_line_item`
+            WHERE `promotion_id` IS NOT NULL AND `type` = :type AND `id` IN (:ids);
```
Comment (cyl3x) [inline src/Core/Checkout/Promotion/DataAbstractionLayer/PromotionRedemptionUpdater.php]: Shouldn't this also include a live version filter?

File: src/Core/Checkout/Promotion/DataAbstractionLayer/PromotionRedemptionUpdater.php [hunk 5]
```diff
@@ -70,19 +112,21 @@ public function update(array $ids, Context $context): void
...
-                    AND order_customer.version_id = order_line_item.version_id
-                WHERE order_line_item.type = :type
-                AND order_line_item.promotion_id IN (:ids)
-                AND order_line_item.version_id = :versionId
-                GROUP BY order_line_item.promotion_id, order_customer.customer_id
-SQL;
+            SELECT LOWER(HEX(promotion.id)) as promotion_id,
+                   COUNT(DISTINCT order_line_item.order_id) as total,
+                   LOWER(HEX(order_customer.customer_id)) as customer_id
+            FROM promotion
```
Comment (cyl3x) [inline src/Core/Checkout/Promotion/DataAbstractionLayer/PromotionRedemptionUpdater.php]: Is it really necessary to select from the promotion table? Joining the order line item column seems like an expensive operation, isn't it?

Comment (En0Ma1259) [reply src/Core/Checkout/Promotion/DataAbstractionLayer/PromotionRedemptionUpdater.php]: With this, we can be certain, that the promotion really exists. Even, if the last "usage" is removed. This will also filter invalid `promotionIds` automatically.

1. Id is valid and has usage -> update statement with current values
2. Id is valid, but no usage -> update statement with `0/null`
3. Invalid id -> no update statement

Comment (En0Ma1259) [reply src/Core/Checkout/Promotion/DataAbstractionLayer/PromotionRedemptionUpdater.php]: Did some changes here

**Review by mstegmeyer — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-promotion-field/index.js [hunk 6]
```diff
@@ -248,6 +252,18 @@ export default {
...
+         * To prevent losing unsaved changes on recalculate the order,
+         * we need to save the **versioned** order beforehand.
+         */
+        async saveAndRecalculate(afterRecalculateFn = null) {
+            if (this.swOrderDetailOnSaveAndRecalculate) {
+                await this.swOrderDetailOnSaveAndRecalculate(afterRecalculateFn);
+            } else {
+                this.$emit('save-and-recalculate', afterRecalculateFn);
+            }
+        },
```
Comment (cyl3x) [inline src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-promotion-field/index.js]: saveAndRecalculate doesn't have a afterFn:
```suggestion
        async saveAndRecalculate() {
            if (this.swOrderDetailOnSaveAndRecalculate) {
                await this.swOrderDetailOnSaveAndRecalculate();
            } else {
                this.$emit('save-and-recalculate');
            }
        },
```

**Review by cyl3x — APPROVED** [review]
