### PR TITLE
fix: race condition between cart persist and load

### LINKED ISSUE #11928: Race condition between “place order” and “get cart” can restore deleted cart and cause duplicate orders
### Shopware Version

6.6.10.6

### Affected area / extension

Platform(Default)

### Actual behaviour

When calling the place order endpoint (/store-api/checkout/order) and, in parallel, the get cart endpoint (/store-api/checkout/cart), it’s possible for a deleted cart (removed during the place order process) to be restored and saved again to the database.

This happens because:
- During get cart, the cart is saved unconditionally.
- The save process always inserts the cart rather than checking if it still exists (no insert-or-update logic).

### Expected behaviour

Once an order is placed, the cart should remain deleted and must not be restored by a concurrent get cart request — even under race conditions, system delays, or parallel calls.

### How to reproduce

- Place an order via `POST /store-api/checkout/order`
- While that request is running, quickly call `GET /store-api/checkout/cart`
- Deleted cart may be restored if the timing is "right".

To make the issue reproducible almost every time:
Add a `sleep(5)` right before `cartPersister->save()` in the CartRuleLoader.

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by mstegmeyer**
### 1. Why is this change necessary?
When calling the place order endpoint (/store-api/checkout/order) and, in parallel, the get cart endpoint (/store-api/checkout/cart), it’s possible for a deleted cart (removed during the place order process) to be restored and saved again to the database.

This happens because:
- During get cart, the cart is saved unconditionally.
- The save process always inserts the cart rather than checking if it still exists (no insert-or-update logic).

### 2. What does this change do, exactly?
Add separate update-or-insert and only update logic. For this: added a bool flag to cart, whether it was freshly created or previously loaded from DB / redis

### 3. Describe each step to reproduce the issue or behaviour.
see 1.

### 4. Please link to the relevant issues (if any).
fixes #11928 

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have updated developer-facing release notes if this change is **relevant** for external developers:
  - Add a short entry to `RELEASE_INFO-6.<major>.md` under “Upcoming” for informational changes, including the consequences of the change and how it affects external developers.
  - Add an `UPGRADE` section in `UPGRADE-6.<next-major>.md` for breaking changes (what/why/impact/how to adapt).
  - See the [Documenting a Release Process](https://github.com/shopware/shopware/blob/trunk/delivery-process/documenting-a-release.md) for details.
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Core/Checkout/Cart/CartPersister.php [hunk 1]
```diff
@@ -90,11 +91,19 @@ public function save(Cart $cart, SalesChannelContext $context): void
...
-        $sql = <<<'SQL'
-            INSERT INTO `cart` (`token`, `payload`, `rule_ids`, `compressed`, `created_at`)
-            VALUES (:token, :payload, :rule_ids, :compressed, :now)
-            ON DUPLICATE KEY UPDATE `payload` = :payload, `compressed` = :compressed, `rule_ids` = :rule_ids, `created_at` = :now;
-        SQL;
+        if ($cart->isNew()) {
+            $sql = <<<'SQL'
+                INSERT INTO `cart` (`token`, `payload`, `rule_ids`, `compressed`, `created_at`)
+                VALUES (:token, :payload, :rule_ids, :compressed, :now)
+                ON DUPLICATE KEY UPDATE `payload` = :payload, `compressed` = :compressed, `rule_ids` = :rule_ids, `created_at` = :now;
```
Comment (En0Ma1259) [inline src/Core/Checkout/Cart/CartPersister.php:98]: Is this still needed? If it's declared as new, there should not be duplicate key, right

File: src/Core/Checkout/Cart/CartPersister.php [hunk 2]
```diff
@@ -90,11 +91,19 @@ public function save(Cart $cart, SalesChannelContext $context): void
...
+            SQL;
+        } else {
+            $sql = <<<'SQL'
+                UPDATE `cart`
+                SET `payload` = :payload, `rule_ids` = :rule_ids, `compressed` = :compressed, `created_at` = :now
```
Comment (En0Ma1259) [inline src/Core/Checkout/Cart/CartPersister.php:103]: Why do we want to change the `created_at` at all? The proper column would be `updated_at`, but doesn't exist

**Review by En0Ma1259 — CHANGES_REQUESTED** [review]

File: src/Core/Checkout/Cart/RedisCartPersister.php [hunk 3]
```diff
@@ -101,9 +102,17 @@ public function save(Cart $cart, SalesChannelContext $context): void
         }
 
         $content = $this->serializeCart($cart, $context);
+        $options = ['EX' => $this->expireDays * 86400];
 
-        $this->redis->set(self::PREFIX . $cart->getToken(), $content, ['EX' => $this->expireDays * 86400]);
+        if (!$cart->isNew()) {
+            $options[] = 'xx';
```
Comment (mitelg) [inline src/Core/Checkout/Cart/RedisCartPersister.php]: what does that do?

Comment (mstegmeyer) [reply src/Core/Checkout/Cart/RedisCartPersister.php]: Only sets the entry if it already exists. So "update", no "insert"

Comment (mitelg) [reply src/Core/Checkout/Cart/RedisCartPersister.php]: so some special redis config? can we have a comment and/or constant for this string? :grin:

File: src/Core/Checkout/Cart/CartPersister.php (hunk 1 above)
Comment (mstegmeyer) [reply src/Core/Checkout/Cart/CartPersister.php:98]: I would rather keep it, just to be safe if concurrent requests write for the same token.

File: src/Core/Checkout/Cart/CartPersister.php (hunk 2 above)
Comment (mstegmeyer) [reply src/Core/Checkout/Cart/CartPersister.php:103]: Well, maybe @shyim can shine light on why we don't have an `updated_at` column anymore.

File: src/Core/Checkout/Cart/Cart.php [hunk 4]
```diff
@@ -234,6 +236,16 @@ public function markUnmodified(): void
...
 
+    public function isNew(): bool
+    {
+        return $this->isNew;
+    }
+
+    public function setIsNew(bool $isNew): void
+    {
+        $this->isNew = $isNew;
+    }
```
Comment (cyl3x) [inline src/Core/Checkout/Cart/Cart.php]: is this should be the approach, can we at least at comments when to set it? e.g. if I create a new cart for some calculation, do I have to set that flag or not?
Maybe this is also worth adding as a state and not as a separate property?

Comment (mstegmeyer) [reply src/Core/Checkout/Cart/Cart.php]: After local discussions: inverting the naming from `isNew` to `isPersisted` for understandability reasons.

We also had a discussions about using the CartLocker, and skipping the persistence if a write operation has the cart locked, but decided against it, because the following scenario can still happen:

1. Read request loads cart before the write starts.
2. Write request acquires lock, places order, deletes cart, releases lock.
3. Read request reaches CartPersister->save() after the lock is already gone.
4. A “skip if locked” check sees no active lock and still recreates the cart.

So the lock check only helps if the stale save happens during the write, not after it. That means it narrows the race window, but it doesn’t close it.

**Review by cyl3x — COMMENTED** [review]
I'm seeing changes in here that don't belong here

**Review by cyl3x — APPROVED** [review]

File: src/Core/Checkout/Cart/CartPersister.php (hunk 2 above)
Comment (shyim) [reply src/Core/Checkout/Cart/CartPersister.php:103]: why do we need it? you cannot access those fields anyway. see the cart table as an key value store, which is the bad implementation of the redis one. the sql impl, should not have anything what the redis one can't have.

real reason: performance, less fields you update less spinning disk have to write something and and

**Review by En0Ma1259 — APPROVED** [review]

File: src/Core/Checkout/Cart/RedisCartPersister.php (hunk 3 above)
Comment (mstegmeyer) [reply src/Core/Checkout/Cart/RedisCartPersister.php]: not very special, a regular option, but I replaced all strings in this class with private constants 😃
