### PR TITLE
fix: Wrong customer context on login if entry from `sales_channel_api_context` table is expired

### LINKED ISSUE #11097: Wrong customer context on login if entry from sales_channel_api_context is expired
### Shopware Version

6.7.0.1

### Affected area / extension

Platform(Default)

### Actual behaviour

**Behaviour:**
Currently if my payload inside the sales_channel_api_context table is expired, it creates on login the wrong customer context. That is the reason, why the cart is afterwards validated with the wrong context.
In combination with other extensions (e.g. Shopware Dynamic Access) it can be that products which are not valid for the wrong context are kicked out from the customer cart.

**Technical issue:**
1. core/System/SalesChannel/Context/CartRestorer.php:80 - loads customer context on login
2. This customer context is wrong if the sales_channel_api_context is expired

**Solution:**
In core/System/SalesChannel/Context/SalesChannelContextPersister.php:147
Wrong: $payload = ['expired' => true];
Correct: $payload['expired'] = true;

Why? The problem is, that the customerId is kicked out from the payload. With the fix the customerId stays inside the payload.

### Expected behaviour

The $customerContext in core/System/SalesChannel/Context/CartRestorer.php:80 on login should be correct, also if the entry from sales_channel_api_context is expired.

### How to reproduce

1. Add Shopware dynamic access plugin
2. Set a product A to be only accessible for customer group "Dealer"
3. Create a user
4. Switch the customer group of the user in admin to "Dealer"
5. Login in Storefront with the user, and put product A into the cart
6. Logout
7. Open database table sales_channel_api_context and set updated_at column to a date in the past (e.g. one year ago)
8. Login with the customer
9. -> Result is, that the product A is kicked out from the cart!

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by acris-cp**
### 1. Why is this change necessary?
**Behaviour:**
Currently if my payload inside the sales_channel_api_context table is expired, it creates on login the wrong customer context. That is the reason, why the cart is afterwards validated with the wrong context.
In combination with other extensions (e.g. Shopware Dynamic Access) it can be that products which are not valid for the wrong context are kicked out from the customer cart.

**Technical issue:**
1. core/System/SalesChannel/Context/CartRestorer.php:80 - loads customer context on login
2. This customer context is wrong if the sales_channel_api_context is expired

### 2. What does this change do, exactly?
**Solution:**
In core/System/SalesChannel/Context/SalesChannelContextPersister.php:147
Wrong: $payload = ['expired' => true];
Correct: $payload['expired'] = true;

Why? The problem is, that the customerId is kicked out from the payload. With the fix the customerId stays inside the payload.

The $customerContext in core/System/SalesChannel/Context/CartRestorer.php:80 on login should be correct, also if the entry from sales_channel_api_context is expired.

### 3. Describe each step to reproduce the issue or behaviour.
1. Add Shopware dynamic access plugin
2. Set a product A to be only accessible for customer group "Dealer"
3. Create a user
4. Switch the customer group of the user in admin to "Dealer"
5. Login in Storefront with the user, and put product A into the cart
6. Logout
7. Open database table sales_channel_api_context and set updated_at column to a date in the past (e.g. one year ago)
8. Login with the customer
9. -> Result is, that the product A is kicked out from the cart!

### 4. Please link to the relevant issues (if any).
- closes #11097

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Core/System/SalesChannel/Context/SalesChannelContextPersister.php [hunk 1]
```diff
@@ -144,7 +144,7 @@ public function load(string $token, string $salesChannelId, ?string $customerId
         $now = new \DateTimeImmutable();
         if ($expiredTime < $now) {
             // context is expired
-            $payload = ['expired' => true];
+            $payload['expired'] = true;
```
Comment (mitelg) [inline src/Core/System/SalesChannel/Context/SalesChannelContextPersister.php]: would you mind adding a test for that, so it is ensured, that the payload stays correct?

File: changelog/_unreleased/2025-07-09-fix-wrong-customer-context-on-login.md [hunk 2]
```diff
@@ -0,0 +1,8 @@
+---
+title: Fix wrong customer context on login if entry from sales_channel_api_context is expired
+issue: 11097
+author: Christoph Pötz
+author_github: @acris-cp
+---
+# Core
+* `Shopware\Core\System\SalesChannel\Context\SalesChannelContextPersister` don't remove customerId and other information from payload if sales_channel_api_context is expired
```
Comment (mitelg) [inline changelog/_unreleased/2025-07-09-fix-wrong-customer-context-on-login.md]:
```suggestion
* Changed `Shopware\Core\System\SalesChannel\Context\SalesChannelContextPersister` so it doesn't remove `customerId` and other information from payload if the context is expired
```

**Review by mitelg — CHANGES_REQUESTED** [review]

File: src/Core/System/SalesChannel/Context/SalesChannelContextPersister.php (hunk 1 above)
Comment (shyim) [inline src/Core/System/SalesChannel/Context/SalesChannelContextPersister.php]: but after login attemp you're still not logged in right?

Comment (acris-cp) [reply src/Core/System/SalesChannel/Context/SalesChannelContextPersister.php]: After logged in attempt I am logged in. Also if the found context from the sales_channel_api_context table was expired. Here everything works.

The problem is, when you dump the $customerContext->getCustomerId() at the core/System/SalesChannel/Context/CartRestorer.php, then it will return null if the sales_channel_api_context is expired (updated_at older then x hours -> depends on lifetimeInterval).

Cause of this it validates the wrong rules and the cart validation is done on the wrong rules.

The same issue causes also more problems I think (like payment method is blocked message after login with expired sales_channel_api_context). So with that fix more problems could be solved.

Comment (acris-cp) [reply src/Core/System/SalesChannel/Context/SalesChannelContextPersister.php]: No, sorry. Please add a test on your own.
I already used some hours to debug the whole process and to find a solution for the customer.

This is also an issue with Shopware Dynamic Access plugin and also other issues are based on that (like Payment Method Blocked after login with expired sales_channel_api_context).
So please add a test and accept the pull request, when everything is fine for you.
Thanks.

**Comment by acris-cp** [comment]
I needed to adjust the pull request. Reason: If the sales channel api context update at is too far in the past (marked as expired), the customer would be still logged in on the first request. With the fixed the customer is correctly logged out.

**Comment by mitelg** [comment]
hey @acris-cp 
I put the PR on draft mode, so we know you still need to work on it. let us know, once your are finished :blush:

**Comment by acris-cp** [comment]
Hej,
I am finished.
You can merge the pull request, thanks.

**Comment by nfortier-shopware** [comment]
@acris-cp this does not look like "finished" sorry, it breaks some tests so it cannot be merged as is.
The lint check is also broken (a simple `composer run ecs-fix` on your local env has fixed that).
The missing test that was asked is not optional either. 

```
There was 1 failure:

Shopware\Tests\Integration\Core\System\SalesChannel\Context\CartRestorerTest::testRestoreByTokenIsReplacedWhenExpired
Failed asserting that actual size 4 matches expected size 2.

/home/runner/work/shopware/shopware/tests/integration/Core/System/SalesChannel/Context/CartRestorerTest.php:286
```
and
```
Shopware\Tests\Integration\Core\Checkout\Cart\SalesChannel\CartOrderRouteTest::testContextTokenExpiring
Failed asserting that two strings are not identical.

/home/runner/work/shopware/shopware/tests/integration/Core/Checkout/Cart/SalesChannel/CartOrderRouteTest.php:296
```

We will take more time to fix those and check if anything else is more deeply broken (sometimes it's just the tests to be adjusted, sometimes it is more)

File: src/Core/System/SalesChannel/Context/SalesChannelContextPersister.php [hunk 3]
```diff
@@ -144,7 +144,11 @@ public function load(string $token, string $salesChannelId, ?string $customerId
         $now = new \DateTimeImmutable();
         if ($expiredTime < $now) {
             // context is expired
-            $payload = ['expired' => true];
+            if (!empty($customerId)) {
+                $payload['expired'] = true;
+            } else {
+                $payload = ['expired'];
```
Comment (nfortier-shopware) [inline src/Core/System/SalesChannel/Context/SalesChannelContextPersister.php]: Shouldn't we have here `$payload = ['expired' => true];`?
With this the tests are not broken any longer (and we keep $payload when customerId is available)

Comment (nfortier-shopware) [reply src/Core/System/SalesChannel/Context/SalesChannelContextPersister.php]: Self responding, I have applied it so now it is not broken any longer

**Comment by nfortier-shopware** [comment]
@mitelg I have finalised it and added the missing tests (unit & integration) for checking the payload consistency

**Comment by acris-cp** [comment]
Great, thank you!
Looking forward to see the fix in the next Shopware version!

**Review by keulinho — APPROVED** [review]

File: src/Core/System/SalesChannel/Context/SalesChannelContextPersister.php [hunk 4]
```diff
@@ -144,7 +144,11 @@ public function load(string $token, string $salesChannelId, ?string $customerId
         $now = new \DateTimeImmutable();
         if ($expiredTime < $now) {
             // context is expired
-            $payload = ['expired' => true];
+            if (!empty($customerId)) {
```
Comment (mitelg) [inline src/Core/System/SalesChannel/Context/SalesChannelContextPersister.php]:
```suggestion
            if ($customerId !== null) {
```

the same condition is used above. I do not like empty as check. we should be more explicit, what we want to check and need

**Review by mitelg — APPROVED** [review]

File: src/Core/System/SalesChannel/Context/SalesChannelContextPersister.php (hunk 4 above)
Comment (nfortier-shopware) [reply src/Core/System/SalesChannel/Context/SalesChannelContextPersister.php]: we are already protected by argument type
```
?string $customerId
```
But it doesn't hurt to be more specific, sure 👍

File: src/Core/System/SalesChannel/Context/SalesChannelContextPersister.php [hunk 5]
```diff
@@ -144,7 +144,11 @@ public function load(string $token, string $salesChannelId, ?string $customerId
         $now = new \DateTimeImmutable();
         if ($expiredTime < $now) {
             // context is expired
-            $payload = ['expired' => true];
+            if ($customerId !== null) {
+                $payload['expired'] = true;
+            } else {
+                $payload = ['expired' => true];
+            }
```
Comment (BrocksiNet) [inline src/Core/System/SalesChannel/Context/SalesChannelContextPersister.php:151]:
```suggestion
    $payload['expired'] = true;

    if ($customerId === null) {
        $payload = ['expired' => true];
    }
```
