### PR TITLE
fix: Execute composer remove on plugin update if necessary

### LINKED ISSUE #6442: Updating plugin when switching state of executeComposerCommands
*PHP Version:* 8.2   | *Shopware Version:* 6.6.9.0  | *Affected area / extension:* Platform(Default) 

 ----

*_Actual behaviour:_*

Update for the plugin is not shown and could not be made.

When using a plugin with composer dependencies (returning `true` from `executeComposerCommands()`), there is no way of returning to a state where `executeComposerCommands()` is `false`, because an update of a plugin is ignored (since it is now "managed" by composer).

*_Expected behaviour:_*

Plugin update should be shown. When updating the plugin, the composer dependencies should be uninstalled and the plugin should be removed from the root's composer.json.

*_How to reproduce:_*

1. Install a plugin with composer dependencies returning `true` from `executeComposerCommands()`
2. Change the plugin code by removing dependencies and returning `false` from `executeComposerCommands()`
3. Upload the new updated version in the administration.

### PR DESCRIPTION
**Pull request by mitelg**
### 1. Why is this change necessary?

If the plugin should not execute composer commands anymore due to an update, the plugin should be removed from the require section of the root `composer.json`

### 2. What does this change do, exactly?

Execute composer remove if the plugin was previously managed by composer, but should not any longer.

### 3. Describe each step to reproduce the issue or behaviour.

- Install plugin, that executes composer commands
- change it so it not executes the composer commands anymore
- increase plugin version
- do plugin update

### 4. Please link to the relevant issues (if any).
- closes #6442
- Jira issue: https://shopware.atlassian.net/browse/NEXT-40447

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfill them.

### CODE REVIEW

**Review by keulinho — APPROVED** [review]

File: src/Core/Framework/Plugin/PluginLifecycleService.php [hunk 1]
```diff
@@ -722,4 +708,25 @@ private function executeComposerRequireWhenNeeded(PluginEntity $plugin, Plugin $
...
         return true;
     }
+
+    private function executeComposerRemoveCommand(PluginEntity $plugin, Context $shopwareContext): void
+    {
+        if (\PHP_SAPI === 'cli') {
+            // only remove the plugin composer dependency directly when running in CLI
+            // otherwise do it async in kernel.response
+            $this->removePluginComposerDependency($plugin, $shopwareContext);
+        /* @codeCoverageIgnoreStart -> code path can not be executed in unit tests as SAPI will always be CLI */
```
Comment (nfortier-shopware) [inline src/Core/Framework/Plugin/PluginLifecycleService.php:718]: We could move that condition in a mockable method or little object, would the unit test be critical for the 2 strategies. 

Now this private method is purely ported from previous inline usage, so we can postpone for another time.

**Review by nfortier-shopware — APPROVED** [review]

**Review by h1k3r — APPROVED** [review]
