### PR TITLE
fix: change in new generated language get an error

### LINKED ISSUE #9426: Changes in new generated languages generate error
### Shopware Version

6.7-RC3

### Affected area / extension

Platform(Default)

### Actual behaviour

Languages can only be saved upon creation. If changes are made immediately afterwards, an error occurs.

### Expected behaviour

Saving without conflict

### How to reproduce

- Create a new language
- Make a change in the newly created language without closing language
- Save
- An error appears in the console:
` Expected command for "language" to be "Shopware\Core\Framework\DataAbstractionLayer\Write\Command\InsertCommand". (Got: Shopware\Core\Framework\DataAbstractionLayer\Write\Command\UpdateCommand)`

### PR DESCRIPTION
**Pull request by thuylt**
### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfill them.

### CODE REVIEW

File: src/Administration/Resources/app/administration/src/module/sw-settings-language/page/sw-settings-language-detail/index.js [hunk 1]
```diff
@@ -240,10 +240,13 @@ export default {
                 .then(() => {
                     this.isLoading = false;
                     this.isSaveSuccessful = true;
+
                     if (!this.languageId) {
                         this.$router.push({
                             name: 'sw.settings.language.detail',
                             params: { id: this.language.id },
+                        }).then(() => {
+                            this.loadEntityData();
```
Comment (tuanngo1993) [inline src/Administration/Resources/app/administration/src/module/sw-settings-language/page/sw-settings-language-detail/index.js]: @thuylt I am wondering how can it work like this, even using `then` handler right after none-promise object but I think the convention should be to look at the changes from the method `updated` lifecycle:

```
updated() {
        this.createdComponent();
    }
```

**Review by tuanngo1993 — APPROVED** [review]

**Review by marcelbrode — APPROVED** [review]
