### PR TITLE
fix: duplicate address display in sw-order-detail

### LINKED ISSUE #11623: Doppelte ANzeige der Liefer- und Rechnungsadresse innerhalb einer Bestellung
### Shopware Version

6.7.0.1

### Affected area / extension

Platform(Default)

### Actual behaviour

If you want to change the delivery or billing address of an order, the entry is displayed twice in the pull-down menu, even though only one delivery address, for example, has been created.

This is extremely confusing for the user, especially since you could edit both entries.

Image

### Expected behaviour

.

### How to reproduce

Create an order and try to change the delivery address.

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by mstegmeyer**
### 1. Why is this change necessary?
If the customer address exists still as the same as the order address, both are shown on the order detail page, which is confusing.

### 2. What does this change do, exactly?
Hide the customer address, as it is the same as the already selected order address.

### 3. Describe each step to reproduce the issue or behaviour.
Place an order, look at the address selection dropdown.

### 4. Please link to the relevant issues (if any).
fixes #11623 

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

**Review by cyl3x — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-address-selection/index.js [hunk 1]
```diff
@@ -103,14 +103,20 @@ export default {
...
+                .map((item) => {
+                    if (this.address && this.address.hash === item.hash) {
+                        return null;
+                    }
+
+                    const option = {
+                        label: this.addressLabel(item),
+                        ...item,
+                    };
+                    option.id = item.id;
```
Comment (En0Ma1259) [inline src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-address-selection/index.js]: Why do we need to do this? Is this a JS thing? Would expect `...item` doing this already 🤔

Comment (mstegmeyer) [reply src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-address-selection/index.js]: 🤔 no clue ... I just had to indent the existing code 🤣 I will check

**Review by En0Ma1259 — APPROVED** [review]
