### PR TITLE
fix: Storefront route usage in Core

### LINKED ISSUE #12969: Storefront routes are used in Core/Checkout
### Technical TODO

In some places in the Core/Checkout namespace, routes from the Storefront are referenced. Instead of using them directly, extension points should be introduced so frontends can provide the necessary values themselves. Or the logic needs to be moved to the Storefront package.

- \Shopware\Core\Checkout\Cart\Address\Error\BillingAddressCountryRegionMissingError::getRoute
- \Shopware\Core\Checkout\Cart\Address\Error\BillingAddressSalutationMissingError::getRoute
- \Shopware\Core\Checkout\Cart\Address\Error\ShippingAddressCountryRegionMissingError::getRoute
- \Shopware\Core\Checkout\Cart\Address\Error\ShippingAddressSalutationMissingError::getRoute
- \Shopware\Core\Checkout\Customer\Subscriber\CustomerGroupSubscriber

### PR DESCRIPTION
**Pull request by mstegmeyer**
### 1. Why is this change necessary?
Storefront and Core are separate packages. Therefore, if Storefront is not installed, Route generation for Storefront Routes will fail. We therefore want to remove all Storefront routes (`frontend.*`) from Core.

### 2. What does this change do, exactly?
- Moved the CustomerGroupSubscriber to the Storefront package. It's internal and its functionality is completely limited to Storefront Sales Channels.
- Deprecated the class `Shopware\Core\Checkout\Cart\Error\ErrorRoute`, as the Storefront does not properly use this class. Therefore, the class, and the `route` property of `Shopware\Core\Checkout\Cart\Error\CartError` will be removed.

### 4. Please link to the relevant issues (if any).
fixes #12969

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have updated developer-facing release notes if this change affects external developers:
  - Add a short entry to `RELEASE_INFO-6.<major>.md` under “Upcoming” for informational changes.
  - Add an `UPGRADE` section in `UPGRADE-6.<next-major>.md` for breaking changes (what/why/impact/how to adapt).
  - See the [Release Notes & Changelog Process](../adr/2025-10-28-changelog-release-info-process.md) for details.
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Storefront/Controller/StorefrontController.php [hunk 1]
```diff
@@ -231,12 +232,14 @@ protected function addCartErrors(Cart $cart, ?\Closure $filter = null): void
...
+                Feature::callSilentIfInactive('v6.8.0.0', function () use (&$parameters, $error): void {
+                    if ($error->getRoute() instanceof ErrorRoute) {
+                        $parameters['%url%'] = $this->generateUrl(
+                            $error->getRoute()->getKey(),
+                            $error->getRoute()->getParams()
+                        );
+                    }
+                });
 
                 $translatedMessage = $this->trans('checkout.' . $error->getMessageKey(), $parameters);
```
Comment (mitelg) [inline src/Storefront/Controller/StorefrontController.php:249]: we also need to adjust the snippets then, right?

**Review by cyl3x — APPROVED** [review]

File: src/Storefront/Controller/StorefrontController.php (hunk 1 above)
Comment (mstegmeyer) [reply src/Storefront/Controller/StorefrontController.php:249]: You mean snippets with `%url%` in them? They don't exist 😆 
That's why I removed that parameter so easily

Comment (mitelg) [reply src/Storefront/Controller/StorefrontController.php:249]: are you sure? https://github.com/shopware/shopware/blob/trunk/src/Core/Framework/Resources/snippet/messages.de.base.json#L28-L29

Comment (mitelg) [reply src/Storefront/Controller/StorefrontController.php:249]: the message key is the ID and `protected const KEY = parent::KEY . '-billing-address';` will result in `country-region-missing-billing-address` which exists

**Review by En0Ma1259 — APPROVED** [review]

File: src/Storefront/Controller/StorefrontController.php (hunk 1 above)
Comment (mstegmeyer) [reply src/Storefront/Controller/StorefrontController.php:249]: Ah f***, I only looked in the Storefront package 🙄

**Review by En0Ma1259 — APPROVED** [review]

File: src/Storefront/Controller/StorefrontController.php (hunk 1 above)
Comment (mstegmeyer) [reply src/Storefront/Controller/StorefrontController.php:249]: I created a new `AddressErrorInterface` that provides the Address ID. With that, the Storefront can then inject the URL to provide in snippets.

File: src/Core/Checkout/Cart/Address/Error/AddressValidationError.php [hunk 2]
```diff
@@ -3,18 +3,30 @@
...
 use Symfony\Component\Validator\ConstraintViolationList;
 
 #[Package('checkout')]
-class AddressValidationError extends Error
+class AddressValidationError extends Error implements AddressErrorInterface
 {
     private const KEY = 'address-invalid';
 
+    /**
+     * @deprecated tag:v6.8.0 - reason:parameter-type-change - $addressId will be required
```
Comment (mitelg) [inline src/Core/Checkout/Cart/Address/Error/AddressValidationError.php]: means, only the default `null` will be removed, right? should maybe stated explicitly. not that someone in the future removes the null part completely :grin:

Comment (mstegmeyer) [reply src/Core/Checkout/Cart/Address/Error/AddressValidationError.php]: Nope, I want the `?` to be removed. I try to make it more clear.

**Review by mitelg — APPROVED** [review]

File: src/Core/Checkout/Cart/Address/Error/AddressValidationError.php [hunk 3]
```diff
@@ -57,4 +69,9 @@ public function getViolations(): ConstraintViolationList
     {
         return $this->violations;
     }
+
+    public function getAddressId(): ?string
```
Comment (cyl3x) [inline src/Core/Checkout/Cart/Address/Error/AddressValidationError.php:73]: I suspect the function doesn't need to return an optional value too?

Comment (mstegmeyer) [reply src/Core/Checkout/Cart/Address/Error/AddressValidationError.php:73]: "doch", it needs to. I wanted this function to identify all Address-related errors, but there is one Error (`ShippingAddressBlockedError`) that get's thrown based on the `ShippingLocation` and the country in there and does not necessarily have an address created yet. That's unfortunately the only reason why this is optional.

Comment (mitelg) [reply src/Core/Checkout/Cart/Address/Error/AddressValidationError.php:73]: I also stumbled about that, it is bit unfortunate, but there is no other way, I guess?

**Review by untilu29 — APPROVED** [review]

File: UPGRADE-6.8.md [hunk 4]
```diff
@@ -485,6 +485,12 @@ which means the `salesChannel` property of the `BaseSalesChannelContext` no long
 The `Shopware\Core\Checkout\Customer\ImitateCustomerTokenGenerator` has been refactored to use JWT tokens for imitating customers instead of a custom solution.
 Previous additional request parameters are not required anymore and part of the token.
 
+## Removal of ErrorRoutes
```
Comment (mitelg) [inline UPGRADE-6.8.md]: do we need to announce that deprecation in the upgrade information?

Comment (mstegmeyer) [reply UPGRADE-6.8.md]: According to our internal confluence (why is this not external?):

### UPGRADE-6.8.md

- Upgrade instructions for breaking changes.
- Every break as defined by our [Backwards Compatibility Promise](https://developer.shopware.com/docs/resources/guidelines/code/backward-compatibility.html#backward-compatibility).
- Must include:
  - What changed
  - Why it changed / benefit
  - When developers need to care
  - How to adjust (code snippet or exact steps)

Comment (mitelg) [reply UPGRADE-6.8.md]: yes, right. :heavy_check_mark:
