### PR TITLE
fix: Customer group decline sets now correct group

### LINKED ISSUE #12117: Mailtemplate "Customer Group Registration Declined" does not work correctly
### Shopware Version

6.7.1.2

### Affected area / extension

Platform(Default)

### Actual behaviour

The Customer Group Registration Declined mail template sends the name of the default customer group and not the customer group for which the original request was made or, in this case, rejected.

### Expected behaviour

The mail template also displays the correct customer group for which the request was made and thus rejected, rather than the standard customer group.

### How to reproduce

- Creates a customer group that must be requested using a registration form
- Submits a request for the customer group and rejects it in the admin
- Now looks at the rejection email that was sent, and the “default customer group” is displayed there instead of the customer group for which the request was made

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by DennisGarding**
Close: #12117 

The Customer Group Registration Declined mail template sends the name of the default customer group and not the customer group for which the original request was made.

### CODE REVIEW

File: tests/integration/Core/Checkout/Customer/Api/CustomerGroupRegistrationActionControllerTest.php [hunk 1]
```diff
@@ -0,0 +1,125 @@
...
+        // Make sure requested group id is set to null
+        $criteria = new Criteria([$customerId]);
+        $customerResult = $this->getContainer()->get('customer.repository')
+            ->search($criteria, Context::createDefaultContext())->getEntities()->first();
+
+        static::assertInstanceOf(CustomerEntity::class, $customerResult);
+        static::assertNull($customerResult->getRequestedGroupId());
+    }
+
+    private function createCustomer(string $requestedCustomerGroupId): string
```
Comment (mitelg) [inline tests/integration/Core/Checkout/Customer/Api/CustomerGroupRegistrationActionControllerTest.php]: don't we have helper for creating customer data?

**Review by ennasus4sun — APPROVED** [review]

**Review by mitelg — APPROVED** [review]

**Comment by mitelg** [comment]
question, why is that not in the checkout area? maybe @shopware/product-cc-checkout should have a look?

**Review by En0Ma1259 — APPROVED** [review]

**Review by cyl3x — APPROVED** [review]
