### PR TITLE
fix: List/price percentage ratio dynamic product groups not working

### LINKED ISSUE #12996: List/price percentage ratio dynamic product groups not working
### Shopware Version

6.7.1.2

### Affected Area / Extension

We have created a dynamic product group with a "Price/Percentage Strike" rule of 0.

*_Expected Behavior:_*

The dynamic product group rule "Price/Percentage Strike" should display the same product list in both the storefront and the admin

*_Actual Behavior:_*

The dynamic product group rule "Price/Percentage Strike" is not working correctly in both admin and storefront (the issue only occurs when the value is 0)

*_How to reproduce:_*

1. Create a dynamic product group and apply a "Price/Percentage Strike" rule of 0
2. Assign the created dynamic product group to a category
3. Check the list displayed in the storefront

### PR DESCRIPTION
**Pull request by nguyenytran**
### Shopware Version

6.7.1.2

### Affected Area / Extension

We have created a dynamic product group with a "Price/Percentage Strike" rule of 0.

*_Expected Behavior:_*

The dynamic product group rule "Price/Percentage Strike" should display the same product list in both the storefront and the admin

*_Actual Behavior:_*

The dynamic product group rule "Price/Percentage Strike" is not working correctly in both admin and storefront (the issue only occurs when the value is 0)

*_How to reproduce:_*

1. Create a dynamic product group and apply a "Price/Percentage Strike" rule of 0
2. Assign the created dynamic product group to a category
3. Check the list displayed in the storefront

### CODE REVIEW

File: src/Core/Content/Product/DataAbstractionLayer/CheapestPrice/CheapestPriceAccessorBuilder.php [hunk 1]
```diff
@@ -58,9 +58,11 @@ public function buildAccessor(string $root, Field $field, Context $context, stri
             array_pop($parts);
         }
 
+        $isPercentageAccessor = false;
```
Comment (vienthuong) [inline src/Core/Content/Product/DataAbstractionLayer/CheapestPrice/CheapestPriceAccessorBuilder.php]:
```suggestion
        $isPercentageAccessor = end($parts) === 'percentage';
        if ($isPercentageAccessor)
```

**Review by tamvt — APPROVED** [review]

File: src/Core/Content/Product/DataAbstractionLayer/CheapestPrice/CheapestPriceAccessorBuilder.php [hunk 2]
```diff
@@ -58,7 +58,8 @@ public function buildAccessor(string $root, Field $field, Context $context, stri
             array_pop($parts);
         }
 
-        if (end($parts) === 'percentage') {
+        $isPercentageAccessor = end($parts) === 'percentage';
```
Comment (mitelg) [inline src/Core/Content/Product/DataAbstractionLayer/CheapestPrice/CheapestPriceAccessorBuilder.php]: we should introduce the symfony PHP8.5 polyfill and use `array_last` instead

**Review by mitelg — CHANGES_REQUESTED** [review]
please fill out the PR description correctly. the linked issue also has no information about what is going on

**Review by vienthuong — APPROVED** [review]

File: src/Core/Content/Product/DataAbstractionLayer/CheapestPrice/CheapestPriceAccessorBuilder.php [hunk 3]
```diff
@@ -45,20 +45,24 @@ public function buildAccessor(string $root, Field $field, Context $context, stri
...
 
         $parts = explode('.', $accessor);
+        $lastAccessorPart = array_last($parts);
 
         // is tax state explicitly requested? => overwrite selector
-        if (\in_array(end($parts), ['net', 'gross'], true)) {
-            $jsonAccessor = end($parts);
+        if (\in_array($lastAccessorPart, ['net', 'gross'], true)) {
+            $jsonAccessor = $lastAccessorPart;
             array_pop($parts);
```
Comment (mitelg) [inline src/Core/Content/Product/DataAbstractionLayer/CheapestPrice/CheapestPriceAccessorBuilder.php:53]: here you can then use `array_first` :wink:

File: src/Core/Content/Product/DataAbstractionLayer/CheapestPrice/CheapestPriceAccessorBuilder.php [hunk 4]
```diff
@@ -94,12 +98,14 @@ public function buildAccessor(string $root, Field $field, Context $context, stri
                 '#multiplier#' => (string) $multiplier,
             ];
 
-            $select[] = str_replace(
+            $expression = str_replace(
```
Comment (mitelg) [inline src/Core/Content/Product/DataAbstractionLayer/CheapestPrice/CheapestPriceAccessorBuilder.php]: why does it need to be set to a variable?

File: composer.json [hunk 5]
```diff
@@ -152,6 +152,7 @@
         "symfony/options-resolver": "~7.3.0",
         "symfony/polyfill-php83": ">=1.31.0",
         "symfony/polyfill-php84": ">=1.31.0",
+        "symfony/polyfill-php85": ">=1.33.0",
```
Comment (mitelg) [inline composer.json:155]: must also be added to the Core composer.json  file

Comment (vienthuong) [reply composer.json:155]: can you also add it in the changelog as well as the Upgrade information so plugins developer can also benefit from it

File: src/Core/Content/Product/DataAbstractionLayer/CheapestPrice/CheapestPriceAccessorBuilder.php (hunk 4 above)
Comment (nguyenytran) [reply src/Core/Content/Product/DataAbstractionLayer/CheapestPrice/CheapestPriceAccessorBuilder.php]: Hi @mitelg I forgot to update the code after the last change, I will revert this code

File: changelog/_unreleased/2025-10-14-fix-dynamic-product-group-percentage-accessor.md [hunk 6]
```diff
@@ -0,0 +1,11 @@
+---
+title: Fix percentage ratio dynamic product groups
+issue: 12996
+---
+# Core
+* Changed `Shopware\Core\Content\Product\DataAbstractionLayer\CheapestPrice\CheapestPriceAccessorBuilder::buildAccessor` to ignore zero-valued entries so dynamic product group conditions based on percentage ratios evaluate correctly again.
+* Added the `symfony/polyfill-php85` dependency and moved affected internals to `array_last()` so pointer handling stays consistent across supported PHP versions.
```
Comment (mitelg) [inline changelog/_unreleased/2025-10-14-fix-dynamic-product-group-percentage-accessor.md]:
```suggestion
* Added the `symfony/polyfill-php85` dependency to make it possible to use PHP 8.5 features
```

File: changelog/_unreleased/2025-10-14-fix-dynamic-product-group-percentage-accessor.md [hunk 7]
```diff
@@ -0,0 +1,11 @@
...
+___
+# Upgrade Information
+## array_last helper availability
```
Comment (mitelg) [inline changelog/_unreleased/2025-10-14-fix-dynamic-product-group-percentage-accessor.md]:
```suggestion
## Added PHP 8.5 polyfill
```

File: changelog/_unreleased/2025-10-14-fix-dynamic-product-group-percentage-accessor.md [hunk 8]
```diff
@@ -0,0 +1,11 @@
...
+All installations now ship with `symfony/polyfill-php85`, which exposes the native `array_last()` helper on PHP 8.2 and 8.3. Plugin developers can drop custom implementations and rely on the global `array_last()` function for consistent pointer handling across Shopware and their extensions.
```
Comment (mitelg) [inline changelog/_unreleased/2025-10-14-fix-dynamic-product-group-percentage-accessor.md]:
```suggestion
The new dependency `symfony/polyfill-php85` was added, to make it possible to already use PHP 8.5 features, like `array_first` and `array_last`.
```

I would not necessarily mention your refactors.

**Review by mitelg — CHANGES_REQUESTED** [review]

File: src/Core/Content/Product/DataAbstractionLayer/CheapestPrice/CheapestPriceAccessorBuilder.php (hunk 3 above)
Comment (nguyenytran) [reply src/Core/Content/Product/DataAbstractionLayer/CheapestPrice/CheapestPriceAccessorBuilder.php:53]: Hi @mitelg I'm not sure, but here we need to get the last parts of the access paths that's why we don't use array_first, or do you have any idea that can suggest me more clearly?

File: changelog/_unreleased/2025-10-14-fix-dynamic-product-group-percentage-accessor.md [hunk 9]
```diff
@@ -0,0 +1,11 @@
...
+title: Fix percentage ratio dynamic product groups
+issue: 12996
+---
+# Core
+* Changed `Shopware\Core\Content\Product\DataAbstractionLayer\CheapestPrice\CheapestPriceAccessorBuilder::buildAccessor` to ignore zero-valued entries so dynamic product group conditions based on percentage ratios evaluate correctly again.
+* Added the `symfony/polyfill-php85` dependency to make it possible to use PHP 8.5 features.
+___
+# Upgrade Information
+## Added PHP 8.5 polyfill
+The new dependency `symfony/polyfill-php85` was added, to make it possible to already use PHP 8.5 features, like `array_first` and `array_last
```
Comment (mitelg) [inline changelog/_unreleased/2025-10-14-fix-dynamic-product-group-percentage-accessor.md]:
```suggestion
The new dependency `symfony/polyfill-php85` was added, to make it possible to already use PHP 8.5 features, like `array_first` and `array_last`
```

File: src/Core/Content/Product/DataAbstractionLayer/CheapestPrice/CheapestPriceAccessorBuilder.php (hunk 3 above)
Comment (mitelg) [reply src/Core/Content/Product/DataAbstractionLayer/CheapestPrice/CheapestPriceAccessorBuilder.php:53]: ah sorry, I had the wrong thing in mind what `array_pop` is doing :see_no_evil: 

all good! as we do not use the returned last part of the array, `array_pop` should be the right thing to do here :+1:

**Review by mitelg — APPROVED** [review]
