### PR TITLE
fix: hot reload accept header

### LINKED ISSUE #9408: Error inside the start-hot-reload.js
### Shopware Version

6.6.10.4

### Affected area / extension

Platform(Default)

### Actual behaviour

When im running the storefront watcher (bin/watch-storefront.sh) and using the Chrome Devtools, the watcher crashes as soon as the devtools are opened with the following error message:

TypeError: Cannot read properties of undefined (reading 'indexOf')
in vendor/shopware/storefront/Resources/app/storefront/build/start-hot-reload.js:86

Image

Im using dockware/dev:latest with shopware version 6.6.10.4 and Chrome Version 136.0.7103.93

### Expected behaviour

The watcher should work as expected and not crash while using chrome dev tools.
A quick workaround would be to edit the start-hot-reload.js and edit the line 86 
from:
if (req.headers['sec-fetch-dest'] === 'document' || req.headers.accept.indexOf('text/html') !== -1) {
to:
if (req.headers['sec-fetch-dest'] === 'document' || req.headers.accept?.indexOf('text/html') !== -1) {

### How to reproduce

- Shopware Version 6.6.10.4
- Chrome Version 136.0.7103.93
- Running the storefront watcher (bin/watch-storefront.sh)
- Open Chrome and go to localhost:9998
- Everything should work until now
- Open the Devtools (F12) -> the watcher should break with the given error message

Image

### PR DESCRIPTION
**Pull request by BrocksiNet**
### 1. Why is this change necessary?
closes: [#9408](https://github.com/shopware/shopware/issues/9408)

### 2. What does this change do, exactly?
Make the Accept header optional because not every environment returns that.
Improve the theme selection in the theme dump command.

image

### 3. Describe each step to reproduce the issue or behaviour.
See Issue.

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfill them.

### CODE REVIEW

File: src/Storefront/Resources/app/storefront/build/start-hot-reload.js [hunk 1]
```diff
@@ -83,10 +83,10 @@ const proxyOptions = {
                     return;
                 }
                 // we only replace things when the request is a document
-                const isDocumentRequest = req.headers['sec-fetch-dest'] === 'document' || req.headers.accept.indexOf('text/html') !== -1;
-                const isHtmlRequests = req.url.indexOf('widgets/menu/offcanvas') !== -1 || req.url.indexOf('checkout/offcanvas') !== -1;
+                const isDocumentRequest = req.headers['sec-fetch-dest'] === 'document' || req.headers.accept?.indexOf('text/html') !== -1;
+                const isOffcanvasRequest = ['/widgets/menu/offcanvas', '/checkout/offcanvas'].some(path => req.url.includes(path));
```
Comment (OliverSkroblin) [inline src/Storefront/Resources/app/storefront/build/start-hot-reload.js:86]: what about ajax modals? Would they be also affected? "we only replace things when the request is a document" @tobiasberge @shyim

Comment (shyim) [reply src/Storefront/Resources/app/storefront/build/start-hot-reload.js:86]: they return also just html, so should be fine

Comment (shyim) [reply src/Storefront/Resources/app/storefront/build/start-hot-reload.js:86]: i would not check for a `sec-fetch-dest` header, it's chromium specific I guess

Comment (BrocksiNet) [reply src/Storefront/Resources/app/storefront/build/start-hot-reload.js:86]: Moved it to a function ... what do you think?

File: src/Storefront/Theme/Command/ThemeDumpCommand.php [hunk 2]
```diff
@@ -156,6 +158,37 @@ protected function getThemeChoices(): array
         return $choices;
     }
 
+    protected function getThemeAssignmentInfos(): string
```
Comment (mitelg) [inline src/Storefront/Theme/Command/ThemeDumpCommand.php]:
```suggestion
    private function getThemeAssignmentInfos(): string
```

File: src/Storefront/Theme/Command/ThemeDumpCommand.php [hunk 3]
```diff
@@ -156,6 +158,37 @@ protected function getThemeChoices(): array
...
+    {
+        $choices = 'Theme assignment:' . \PHP_EOL;
+
+        $criteria = new Criteria();
+        $criteria->addAssociation('salesChannels');
+        $themes = $this->themeRepository->search($criteria, Context::createCLIContext())->getEntities();
```
Comment (mitelg) [inline src/Storefront/Theme/Command/ThemeDumpCommand.php]:
```suggestion
        $themes = $this->themeRepository->search($criteria, $this->context)->getEntities();
```

**Review by mitelg — CHANGES_REQUESTED** [review]

File: src/Storefront/Theme/Command/ThemeDumpCommand.php (hunk 3 above)
Comment (BrocksiNet) [reply src/Storefront/Theme/Command/ThemeDumpCommand.php]: Upsi. Thx.

**Review by mitelg — APPROVED** [review]

**Review by tobiasberge — APPROVED** [review]
