### PR TITLE
fix: inconsistent seoUrls for cross-selling products

### LINKED ISSUE #11445: Inconsistent seoUrl for Cross-Selling Products in Store API Response
### Shopware Version

6.6.10.5 and above

### Affected area / extension

Platform(Default)

### Actual behaviour

**Summary**

When retrieving the Product Detail using the Shopware Store API, we observed inconsistent seoUrl values for a product that appears in multiple cross-selling groups under the same main product.

The same cross-selling product returns:

1.     seoUrl = null in one cross-selling group
2.     Valid seoUrl in another group

Image
Image

This inconsistency leads to unpredictable frontend behavior and broken links depending on which cross-sell group is rendered.

### Expected behaviour

A product included in multiple cross-selling groups for the same parent product should return consistent seoUrl values across all instances in the API response.

### How to reproduce

1.     Create a product (e.g., Product A) with two different cross-selling groups.
2.     Add the same product (e.g., Product B) to both cross-selling groups.
3.     Fetch the Product Detail via the /store-api/product/{productId} endpoint.
4.     Inspect the cross-sellings:
         - [ ]  first instance shows seoUrl: null
         - [ ]  second instance of Product B shows a valid seoUrl

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [x] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [x] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [x] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [x] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by vienthuong**
Fixes #11445 

On many occasions, the same entity but in a different objects are added to SeoResolverData so only one of them is enriched with seoUrls.

With this change, I refer the entity not only by the identifier but also by the object hash so every object is correctly referenced and their seoUrls will be added correspondingly

### CODE REVIEW

File: src/Core/Content/Seo/SalesChannel/SeoResolverData.php [hunk 1]
```diff
@@ -38,7 +49,23 @@ public function getIds(string $entityName): array
         return array_keys($this->entityMap[$entityName]);
     }
 
+    /**
+     * @deprecated tag:v6.8.0 - use getAll instead
+     */
     public function get(string $entityName, string $id): Entity
```
Comment (keulinho) [inline src/Core/Content/Seo/SalesChannel/SeoResolverData.php:59]: please add a changelog describing the deprecation and add a `# next major version` entry describing the break and what to do instead

File: src/Core/Content/Seo/SalesChannel/SeoResolverData.php [hunk 2]
```diff
@@ -19,7 +20,17 @@ public function add(string $entityName, Entity $entity): void
             $this->entityMap[$entityName] = [];
         }
 
-        $this->entityMap[$entityName][$entity->getUniqueIdentifier()] = $entity;
+        if (!isset($this->entityMap[$entityName][$entity->getUniqueIdentifier()])) {
+            $this->entityMap[$entityName][$entity->getUniqueIdentifier()] = [];
+        }
+
+        $hash = spl_object_hash($entity);
```
Comment (keulinho) [inline src/Core/Content/Seo/SalesChannel/SeoResolverData.php:31]: lets add a comment indicating why we need to use the object hash as well here e.g. if the same entity is loaded twice over different associations 
product 1 -> cross selling 1 -> product 2
product 1 -> cross selling 2 -> product 2

in that case product 2 would be there two times right?

Comment (vienthuong) [reply src/Core/Content/Seo/SalesChannel/SeoResolverData.php:31]: yup that's correct

**Review by nguyenytran — APPROVED** [review]

File: src/Core/Content/Seo/SalesChannel/SeoResolverData.php (hunk 2 above)
Comment (vienthuong) [reply src/Core/Content/Seo/SalesChannel/SeoResolverData.php:31]: I added a explaination in the code

**Review by keulinho — APPROVED** [review]

File: changelog/_unreleased/2025-07-29-fix-inconsistent-seourls-for-cross-selling-products.md [hunk 3]
```diff
@@ -0,0 +1,39 @@
+---
+title: Fix inconsistent seoUrls for cross-selling products
+issue: 11550
+---
+# Core
+* Added new method `Shopware\Core\Content\Seo\SalesChannel\SeoResolverData::getAll` to returns all items with the given entity and identifier
+* Deprecated method `Shopware\Core\Content\Seo\SalesChannel\SeoResolverData::get`, please use `getAll` instead because `get` returns only the first item with could lead to other items with the same entity and identifier are ignored
+___
+# Upgrade Information
```
Comment (mitelg) [inline changelog/_unreleased/2025-07-29-fix-inconsistent-seourls-for-cross-selling-products.md:9]: this won't work

you need to separate those two headlines. 
`# Upgrade Information` should state, that a deprecation is introduced and what the alternatives are. 
`# Next Major Version Changes` then needs to tell, what was removed and what should be used instead

File: changelog/_unreleased/2025-07-29-fix-inconsistent-seourls-for-cross-selling-products.md [hunk 4]
```diff
@@ -0,0 +1,39 @@
...
+# Next Major Version Changes
+## Deprecate method Shopware\Core\Content\Seo\SalesChannel\SeoResolverData::get:
+
+In some occasions, the method `Shopware\Core\Content\Seo\SalesChannel\SeoResolverData::get` was used to retrieve a single item based on its entity and identifier. However, this method only returns the first item found, which can lead to inconsistencies when multiple items share the same entity and identifier.
+So we will introduce a new method `Shopware\Core\Content\Seo\SalesChannel\SeoResolverData::getAll` that returns all items with the given entity and identifier. This change ensures that all relevant items are considered, preventing potential seoUrls loss or misrepresentation.
+
+This will lead to, if you use the method `get` in your code, you have to adapt the `getAll` method
```
Comment (mitelg) [inline changelog/_unreleased/2025-07-29-fix-inconsistent-seourls-for-cross-selling-products.md]:
```suggestion
This will lead to issues, if you use the method `get` in your code, you have to use the `getAll` method.
```

there is a word missing :grin:

File: changelog/_unreleased/2025-07-29-fix-inconsistent-seourls-for-cross-selling-products.md [hunk 5]
```diff
@@ -0,0 +1,39 @@
+---
+title: Fix inconsistent seoUrls for cross-selling products
+issue: 11550
+---
+# Core
+* Added new method `Shopware\Core\Content\Seo\SalesChannel\SeoResolverData::getAll` to returns all items with the given entity and identifier
```
Comment (mitelg) [inline changelog/_unreleased/2025-07-29-fix-inconsistent-seourls-for-cross-selling-products.md]:
```suggestion
* Added new method `Shopware\Core\Content\Seo\SalesChannel\SeoResolverData::getAll` to return all items with the given entity and identifier
```

File: changelog/_unreleased/2025-07-29-fix-inconsistent-seourls-for-cross-selling-products.md [hunk 6]
```diff
@@ -0,0 +1,39 @@
...
+* Deprecated method `Shopware\Core\Content\Seo\SalesChannel\SeoResolverData::get`, please use `getAll` instead because `get` returns only the first item with could lead to other items with the same entity and identifier are ignored
```
Comment (mitelg) [inline changelog/_unreleased/2025-07-29-fix-inconsistent-seourls-for-cross-selling-products.md]:
```suggestion
* Deprecated method `Shopware\Core\Content\Seo\SalesChannel\SeoResolverData::get`, use `getAll` instead, as `get` returns only the first item which could lead to other items with the same entity and identifier being ignored
```

File: src/Core/Content/Seo/SalesChannel/SeoResolverData.php [hunk 7]
```diff
@@ -19,7 +20,21 @@ public function add(string $entityName, Entity $entity): void
             $this->entityMap[$entityName] = [];
         }
 
-        $this->entityMap[$entityName][$entity->getUniqueIdentifier()] = $entity;
+        if (!isset($this->entityMap[$entityName][$entity->getUniqueIdentifier()])) {
+            $this->entityMap[$entityName][$entity->getUniqueIdentifier()] = [];
+        }
+
+        /**
+         * a same entity can be added multiple times, e.g. if a same product is assigned in multiple cross-selling groups
```
Comment (mitelg) [inline src/Core/Content/Seo/SalesChannel/SeoResolverData.php]:
```suggestion
         * The same entity can be added multiple times, e.g. if the same product is assigned in multiple cross-selling groups
```

File: src/Core/Content/Seo/SalesChannel/SeoResolverData.php [hunk 8]
```diff
@@ -19,7 +20,21 @@ public function add(string $entityName, Entity $entity): void
...
+         * we use the spl_object_hash to ensure that every entity can be added multiple times and hence we can enrich seoUrls for all these duplicated entities even they're in different extensions
```
Comment (mitelg) [inline src/Core/Content/Seo/SalesChannel/SeoResolverData.php]:
```suggestion
         * Using `spl_object_hash` to ensure that every entity can be added multiple times and hence allowing to enrich seoUrls for all these duplicated entities even if they're in different extensions
```

File: src/Core/Content/Seo/SalesChannel/StoreApiSeoResolver.php [hunk 9]
```diff
@@ -155,16 +156,18 @@ private function enrich(SeoResolverData $data, SalesChannelContext $context): vo
...
-                }
+                foreach ($entities as $entity) {
+                    if ($entity->getSeoUrls() === null) {
+                        $entity->setSeoUrls(new SeoUrlCollection());
+                    }
 
-                /** @var SeoUrlCollection $seoUrlCollection */
-                $seoUrlCollection = $entity->getSeoUrls();
-                $seoUrlCollection->add($url);
+                    /** @var SeoUrlCollection $seoUrlCollection */
```
Comment (mitelg) [inline src/Core/Content/Seo/SalesChannel/StoreApiSeoResolver.php]: would be nice, if we could remove the `@var` annotations in this file :grin:

**Review by mitelg — CHANGES_REQUESTED** [review]

File: src/Core/Content/Seo/SalesChannel/StoreApiSeoResolver.php [hunk 10]
```diff
@@ -153,18 +153,25 @@ private function enrich(SeoResolverData $data, SalesChannelContext $context): vo
...
-                /** @var SalesChannelProductEntity|CategoryEntity $entity */
-                $entity = $data->get($definition, $url->getForeignKey());
+                $entities = $data->getAll($definition, $url->getForeignKey());
 
-                if ($entity->getSeoUrls() === null) {
-                    $entity->setSeoUrls(new SeoUrlCollection());
-                }
+                foreach ($entities as $entity) {
+                    if (!\method_exists($entity, 'getSeoUrls') || !\method_exists($entity, 'setSeoUrls')) {
+                        break;
```
Comment (mitelg) [inline src/Core/Content/Seo/SalesChannel/StoreApiSeoResolver.php:161]: do we really want to break here, or is continue enough?

File: src/Core/Content/Seo/SalesChannel/StoreApiSeoResolver.php [hunk 11]
```diff
@@ -153,18 +153,25 @@ private function enrich(SeoResolverData $data, SalesChannelContext $context): vo
...
+                    }
+
+                    if ($entity->getSeoUrls() === null) {
+                        $entity->setSeoUrls(new SeoUrlCollection());
+                    }
+
+                    if (!$entity->getSeoUrls() instanceof SeoUrlCollection) {
+                        break;
```
Comment (mitelg) [inline src/Core/Content/Seo/SalesChannel/StoreApiSeoResolver.php:169]: same here

File: src/Core/Content/Seo/SalesChannel/SeoResolverData.php [hunk 12]
```diff
@@ -19,7 +20,21 @@ public function add(string $entityName, Entity $entity): void
             $this->entityMap[$entityName] = [];
         }
 
-        $this->entityMap[$entityName][$entity->getUniqueIdentifier()] = $entity;
+        if (!isset($this->entityMap[$entityName][$entity->getUniqueIdentifier()])) {
+            $this->entityMap[$entityName][$entity->getUniqueIdentifier()] = [];
+        }
+
+        /**
+         * The same entity can be added multiple times, e.g. if a same product is assigned in multiple cross-selling groups
```
Comment (mitelg) [inline src/Core/Content/Seo/SalesChannel/SeoResolverData.php]:
```suggestion
         * The same entity can be added multiple times, e.g. if the same product is assigned in multiple cross-selling groups
```

File: changelog/_unreleased/2025-07-29-fix-inconsistent-seourls-for-cross-selling-products.md [hunk 13]
```diff
@@ -0,0 +1,43 @@
...
+title: Fix inconsistent seoUrls for cross-selling products
+issue: 11550
+---
+# Core
+* Added new method `Shopware\Core\Content\Seo\SalesChannel\SeoResolverData::getAll` to return all items with the given entity and identifier
+* Deprecated method `Shopware\Core\Content\Seo\SalesChannel\SeoResolverData::get`, please use `getAll` instead, as `get` returns only the first item which could lead to other items with the same entity and identifier being ignored
+___
+# Upgrade Information
+
+## Deprecate method Shopware\Core\Content\Seo\SalesChannel\SeoResolverData::get
```
Comment (mitelg) [inline changelog/_unreleased/2025-07-29-fix-inconsistent-seourls-for-cross-selling-products.md:11]: this should already mention the new method. so basically saying the `get` method is deprecated and will be removed with the next major and then this is the new alternative which should be used now. 

you can already add the before/after examples here. 

the `# Next Major Version Changes` then just states that the `get` method was removed and that they should use the `getAll` method instead. before/after could also be added here. 

be aware, that those sections will be extracted from this changelog file and go into two different upgrade guide files, first in the 6.7 file and second into the 6.8 file. 

so we kinda need to duplicate the content a bit. but it is still slightly different, as we introduce the deprecation first and then second remove it

**Review by mitelg — CHANGES_REQUESTED** [review]

File: src/Core/Content/Seo/SalesChannel/StoreApiSeoResolver.php (hunk 10 above)
Comment (vienthuong) [reply src/Core/Content/Seo/SalesChannel/StoreApiSeoResolver.php:161]: normally it should be continue but in this case, all $entity are from the same entity definition (see the previous lines) so I think we can safely break the loop

File: src/Core/Content/Seo/SalesChannel/StoreApiSeoResolver.php (hunk 11 above)
Comment (vienthuong) [reply src/Core/Content/Seo/SalesChannel/StoreApiSeoResolver.php:169]: same as above

File: changelog/_unreleased/2025-07-29-fix-inconsistent-seourls-for-cross-selling-products.md (hunk 13 above)
Comment (vienthuong) [reply changelog/_unreleased/2025-07-29-fix-inconsistent-seourls-for-cross-selling-products.md:11]: that's make sense 👍🏽 I updated it again

File: changelog/_unreleased/2025-07-29-fix-inconsistent-seourls-for-cross-selling-products.md [hunk 14]
```diff
@@ -0,0 +1,69 @@
...
+foreach ($entities as $entity) {
+    $seoUrls = $entity->getSeoUrls();
+    $seoUrls->add($url);
+}
+```
+
+___
+# Next Major Version Changes
+
+## Introduce new method Shopware\Core\Content\Seo\SalesChannel\SeoResolverData::getAll
```
Comment (mitelg) [inline changelog/_unreleased/2025-07-29-fix-inconsistent-seourls-for-cross-selling-products.md]:
```suggestion
## Remove method Shopware\Core\Content\Seo\SalesChannel\SeoResolverData::get
```

File: changelog/_unreleased/2025-07-29-fix-inconsistent-seourls-for-cross-selling-products.md [hunk 15]
```diff
@@ -0,0 +1,69 @@
...
+
+The method `Shopware\Core\Content\Seo\SalesChannel\SeoResolverData::get` will be removed as it's no longer used because it only returns the first entity found, which can lead to inconsistencies when multiple items share the same entity and identifier.
```
Comment (mitelg) [inline changelog/_unreleased/2025-07-29-fix-inconsistent-seourls-for-cross-selling-products.md]:
```suggestion
The method `Shopware\Core\Content\Seo\SalesChannel\SeoResolverData::get` was removed as it's no longer used because it only returns the first entity found, which can lead to inconsistencies when multiple items share the same entity and identifier.
```

File: changelog/_unreleased/2025-07-29-fix-inconsistent-seourls-for-cross-selling-products.md [hunk 16]
```diff
@@ -0,0 +1,69 @@
...
+We will introduce a new method `Shopware\Core\Content\Seo\SalesChannel\SeoResolverData::getAll` that returns all items with the given entity and identifier. This change ensures that all relevant items are considered, preventing potential seoUrls loss or misrepresentation.
```
Comment (mitelg) [inline changelog/_unreleased/2025-07-29-fix-inconsistent-seourls-for-cross-selling-products.md]:
```suggestion
A new method `Shopware\Core\Content\Seo\SalesChannel\SeoResolverData::getAll` was introduced which returns all items with the given entity and identifier. This change ensures that all relevant items are considered, preventing potential seoUrls loss or misrepresentation.
```

File: changelog/_unreleased/2025-07-29-fix-inconsistent-seourls-for-cross-selling-products.md [hunk 17]
```diff
@@ -0,0 +1,69 @@
...
+This will lead to the this change, if you use the method `get` in your code, you have to use the `getAll` method instead.
```
Comment (mitelg) [inline changelog/_unreleased/2025-07-29-fix-inconsistent-seourls-for-cross-selling-products.md]:
```suggestion
If you use the method `get` in your code, you have to use the `getAll` method instead.
```

File: changelog/_unreleased/2025-07-29-fix-inconsistent-seourls-for-cross-selling-products.md (hunk 15 above)
Comment (mitelg) [reply changelog/_unreleased/2025-07-29-fix-inconsistent-seourls-for-cross-selling-products.md]: at this point, the method will already be removed :wink:

**Review by mitelg — APPROVED** [review]
