### PR TITLE
fix: Change tc parameter order

### LINKED ISSUE #7722: Info banners in sale channels are missing data
*Steps:*

- Login to admin
- Go to Sales Channels → Headless or Storefront
- Observe Info banner under General Settings and Payment & shipping

Actual info:

* The language is not assigned to a domain. In order to use this language in your Sales Channel, create a respective domain first.
* Some of the payment methods assigned to this Sales Channel are currently not available. Please check your [+settings+|http://localhost:8167/admin] for these payment methods:

Expected info:

* The language *Deutsch* is not assigned to a domain. In order to use this language in your Sales Channel, create a respective domain first.
* Some of the payment methods assigned to this Sales Channel are currently not available. Please check your [+settings+|http://localhost:8100/admin#/sw/settings/payment/overview] for these payment methods:
*Direct Debit*

6.6 vs 6.7

!image-20250303-103948.png|width=2286,height=1075,alt="image-20250303-103948.png"!

### PR DESCRIPTION
**Pull request by alexdumea**
### 1. Why is this change necessary?
Variable from snippet is not replaced correctly because the parameter order of $tc was wrong.
In our setup, $tc uses vue-i18n's t function, where the second parameter should be the variables for replacement, and the third is for pluralization
image

### 2. What does this change do, exactly?
This change corrects the parameter order when calling $tc to match the expected signature
image

### 4. Please link to the relevant issues (if any).
closes #7722 

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfill them.

### CODE REVIEW

**Comment by mitelg** [comment]
hey @alexdumea 

the PR template is there for a reason :slightly_smiling_face: would be nice if you could provide some context. at least a link to the issue would be nice. also because it will be auto-closed, once it is referenced with a PR

**Review by dgrothaus-sw — APPROVED** [review]

**Review by bschulzebaek — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-sales-channel/view/sw-sales-channel-detail-base/index.js [hunk 1]
```diff
@@ -744,7 +744,7 @@ export default {
                 paymentSettingsLink: routeData.href,
             };
 
-            return this.$tc(snippet, collection.length, data);
+            return this.$tc(snippet, data, collection.length);
```
Comment (marcelbrode) [inline src/Administration/Resources/app/administration/src/module/sw-sales-channel/view/sw-sales-channel-detail-base/index.js]: You can (and should) use $t instead. $tc is deprecated in the original vue dependency. Currently, $tc is only reference to $t anyway.

**Review by marcelbrode — CHANGES_REQUESTED** [review]

**Review by marcelbrode — APPROVED** [review]

**Review by marcelbrode — APPROVED** [review]
