### PR TITLE
fix: validate custom field name

### LINKED ISSUE #12570: Editing custom fields is no longer possible
### Shopware Version

6.7.2.2

### Affected area / extension

Platform(Default)

### Actual behaviour

Before 6.7, you could use a hyphen/minus sign in the technical name for custom fields (set-Informationen).

f.e.

Image

Updating to 6.7, it seems this character is no longer allowed in the technical name, and you can no longer edit the custom fields and you cant change it.

Image

This can be a very big problem for customers with many custom fields.

### Expected behaviour

.

### How to reproduce

.

### PR DESCRIPTION
**Pull request by larskemper**
fixes #12570

Screenshot 2025-09-25 at 08 57 03

### CODE REVIEW

File: src/Core/System/CustomField/CustomFieldException.php [hunk 1]
```diff
@@ -19,7 +19,7 @@ public static function customFieldNameInvalid(string $name): self
         return new self(
             Response::HTTP_BAD_REQUEST,
             self::CUSTOM_FIELD_NAME_INVALID,
-            'Invalid custom field name: It must begin with a letter or underscore, followed by letters, numbers, or underscores.',
+            'Invalid field name: Only letters, numbers, or underscores are allowed, and it must start with a letter or underscore.',
```
Comment (larskemper) [inline src/Core/System/CustomField/CustomFieldException.php:22]: @GitEvil ok with that?

File: src/Administration/Resources/app/administration/src/module/sw-settings-custom-field/component/sw-custom-field-detail/index.js [hunk 2]
```diff
@@ -55,8 +65,24 @@ export default {
             return [this.$root.$i18n.fallbackLocale.value];
         },
 
+        customFieldNameError() {
+            if (!this.currentCustomField.name) {
+                return null;
+            }
+
+            const isValid = CUSTOM_FIELD_NAME_PATTERN.test(this.currentCustomField.name);
```
Comment (mitelg) [inline src/Administration/Resources/app/administration/src/module/sw-settings-custom-field/component/sw-custom-field-detail/index.js]: isn't that checked in the backend? why is it then necessary to do it here again?

Comment (larskemper) [reply src/Administration/Resources/app/administration/src/module/sw-settings-custom-field/component/sw-custom-field-detail/index.js]: cause "live validation" makes the error easier to resolve and gives you instant feedback without submitting everytime (I added a screenshot)

**Review by DennisGarding — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-settings-custom-field/component/sw-custom-field-detail/index.js (hunk 2 above)
Comment (mitelg) [reply src/Administration/Resources/app/administration/src/module/sw-settings-custom-field/component/sw-custom-field-detail/index.js]: yes, but we do not do that anywhere else. we always show the errors given back by the API. with this it could happen, that the validations diverge

Comment (mitelg) [reply src/Administration/Resources/app/administration/src/module/sw-settings-custom-field/component/sw-custom-field-detail/index.js]: @jleifeld what do you think about that?

Comment (larskemper) [reply src/Administration/Resources/app/administration/src/module/sw-settings-custom-field/component/sw-custom-field-detail/index.js]: changed implementation, to use api errors

**Review by mitelg — APPROVED** [review]
