### PR TITLE
fix: sanitize mail template type data

### LINKED ISSUE #11531: Password hash via /api/search/mail-template
### Shopware Version

6.6.10.3

### Affected area / extension

Platform(Default)

### Actual behaviour

When the POST call to /api/search/mail-template is made from the Shopware 6.6 backend to edit an email form containing user data (and probably also in similar calls such as the preview for emails, etc., if requested), the backend's response contains the serialized user object in JSON format. Part of this user data is the “password” field, which contains the customer's password hash.

- The hash is sensitive and potentially vulnerable to attack
- Even administrators have no objective reason to view this hash, especially not in an email template preview
- OWASP / GDPR: “Expose only what is necessary.”

The admin should ideally never have the need of seeing the user's password hash, but specifically not in calls like these which might be available to lower-level admin users. Instead, the field should either contain obfuscated information or be removed. 

### Expected behaviour

Instead, the field should either contain obfuscated information or be removed. 

### How to reproduce

To reproduce: 
* Open Backend
* Settings > E-Mails
* Edit an e-mail like "Registration confirmation"
* Check response for POST /api/search/mail-template call for irrelevant data. 

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by larskemper**
fixes #11531

### CODE REVIEW

File: tests/integration/Core/Content/Flow/SendMailActionTest.php [hunk 1]
```diff
@@ -564,20 +573,34 @@ public function testUpdateTemplateData(bool $shouldUpdate): void
 
         $flowFactory = static::getContainer()->get(FlowFactory::class);
         $flow = $flowFactory->create($event);
-        $flow->setConfig($config);
+        $flow->setConfig([
+            'mailTemplateId' => $mailTemplate->getId(),
+            'recipient' => [
+                'type' => 'admin',
+                'data' => [
+                    'phuoc.cao@shopware.com' => 'shopware',
```
Comment (mitelg) [inline tests/integration/Core/Content/Flow/SendMailActionTest.php]: please do not use real mail addresses

Comment (larskemper) [reply tests/integration/Core/Content/Flow/SendMailActionTest.php]: I don't added this and also found it odd😅, but I will change it then

**Review by mitelg — APPROVED** [review]

**Review by CR0YD — APPROVED** [review]

**Review by ennasus4sun — APPROVED** [review]
