### PR TITLE
test: fix flaky dst unit test 

### LINKED ISSUE #15843: TimeRangeRuleTest flaky on DST transition days
### Shopware Version

6.7.8.2 and before

### Affected area / extension

Platform(Default)

### Actual behaviour

`TimeRangeRuleTest::testIfOnSameDayInTimeRangeWithDifferentTimezonesAndCurrentOffsetMatches`fails when the CI runs between 00:00 and 01:00 UTC on a spring DST transition day (e.g. March 29, 2026 for Europe/Berlin). The test calculates the timezone offset using `new \DateTimeImmutable('now')` (line 81) but mocks the scope time as a fixed 12:00 UTC (line 87). When the real time is pre-transition (offset +1) but 12:00 UTC falls post-transition (offset +2), the computed toTime is off by one hour, causing the match to return false instead of true.

### Expected behaviour

The test should pass regardless of when it runs, including during DST transition windows.

### How to reproduce

Run the test on March 29, 2026 (Europe/Berlin DST switch day) between 00:00 and 01:00 UTC:

```bash
vendor/bin/phpunit tests/unit/Core/Framework/Rule/TimeRangeRuleTest.php --filter testIfOnSameDayInTimeRangeWithDifferentTimezonesAndCurrentOffsetMatches
```

The offset calculation at line 81 uses now (pre-transition, offset +1), producing toTime = '13:00'. But the mock time at line 87 (12:00 UTC = 14:00 CEST) is post-transition (offset +2). The rule converts 13:00 CEST to 11:00 UTC, which is before 12:00 UTC, so the match returns false instead of true.

### PR DESCRIPTION
**Pull request by nfortier-shopware**
### 1. Why is this change necessary?
See the issue attached, in pipeline CI during DST change this test can break

### 2. What does this change do, exactly?

Use DatetimeImmutable without `now` notion, and the tooling of Datetime classes for format

### 3. Describe each step to reproduce the issue or behaviour.

Run this during DST change on the pipeline
Run this locally with modified clock in docker to mimic the behaviour

### 4. Please link to the relevant issues (if any).
- closes https://github.com/shopware/shopware/issues/15843

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have updated developer-facing release notes if this change is **relevant** for external developers:
  - Add a short entry to `RELEASE_INFO-6.<major>.md` under “Upcoming” for informational changes, including the consequences of the change and how it affects external developers.
  - Add an `UPGRADE` section in `UPGRADE-6.<next-major>.md` for breaking changes (what/why/impact/how to adapt).
  - See the [Documenting a Release Process](https://github.com/shopware/shopware/blob/trunk/delivery-process/documenting-a-release.md) for details.
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: tests/unit/Core/Framework/Rule/TimeRangeRuleTest.php [hunk 1]
```diff
@@ -78,8 +78,9 @@ public function testIfOnSameDayInTimeRangeWithDifferentTimezonesAndCurrentOffset
         $timezoneEuropeBerlin = new \DateTimeZone('Europe/Berlin');
         $timezoneUTC = new \DateTimeZone('UTC');
 
-        $offset = $timezoneEuropeBerlin->getOffset(new \DateTimeImmutable('now', $timezoneUTC)) / 3600;
-        $toTime = (12 + $offset) . ':00';
+        $reference = new \DateTimeImmutable('12:00', $timezoneUTC);
```
Comment (SpiGAndromeda) [inline tests/unit/Core/Framework/Rule/TimeRangeRuleTest.php]:
```suggestion
        $reference = new \DateTimeImmutable('2025-05-25 04:20:42', $timezoneUTC);
```

A fixed data would be even better. Towel Day btw.

File: tests/unit/Core/Framework/Rule/TimeRangeRuleTest.php [hunk 2]
```diff
@@ -98,8 +99,9 @@ public function testIfOnSameDayOutOfTimeRangeWithDifferentTimezonesAndCurrentOff
         $timezoneEuropeBerlin = new \DateTimeZone('Europe/Berlin');
         $timezoneUTC = new \DateTimeZone('UTC');
 
-        $offset = $timezoneEuropeBerlin->getOffset(new \DateTimeImmutable('now', $timezoneUTC)) / 3600;
-        $toTime = (11 + $offset) . ':00';
+        $reference = new \DateTimeImmutable('12:00', $timezoneUTC);
```
Comment (SpiGAndromeda) [inline tests/unit/Core/Framework/Rule/TimeRangeRuleTest.php]:
```suggestion
        $reference = new \DateTimeImmutable('2025-05-25 04:20:42', $timezoneUTC);
```

A fixed data would be even better. Towel Day btw.

**Review by SpiGAndromeda — CHANGES_REQUESTED** [review]

**Review by umutdogan4291 — APPROVED** [review]

File: tests/unit/Core/Framework/Rule/TimeRangeRuleTest.php [hunk 3]
```diff
@@ -75,40 +75,35 @@ public function testIfOnSameDayInTimeRangeWithDifferentTimezonesAndCurrentOffset
...
-        $timezoneEuropeBerlin = new \DateTimeZone('Europe/Berlin');
-        $timezoneUTC = new \DateTimeZone('UTC');
-
-        $offset = $timezoneEuropeBerlin->getOffset(new \DateTimeImmutable('now', $timezoneUTC)) / 3600;
-        $toTime = (12 + $offset) . ':00';
+        // Convert the exact instant returned by getCurrentTime() into Berlin to derive toTime.
+        // This guarantees the mocked UTC time falls inside [00:00, toTime] in Europe/Berlin,
+        // regardless of DST (UTC+1 winter / UTC+2 summer).
+        $now = new \DateTimeImmutable('12:00', new \DateTimeZone('UTC'));
+        $toTime = $now->setTimezone(new \DateTimeZone('Europe/Berlin'))->modify('+1 hour')->format('H:i');
```
Comment (nfortier-shopware) [inline tests/unit/Core/Framework/Rule/TimeRangeRuleTest.php:82]: @SpiGAndromeda I've reverted your suggestion since $reference used to derive $toTime is 04:20:42 UTC, which in Berlin is 06:20 CEST. The mocked getCurrentTime() returned 12:00 UTC = 14:00 CEST. 

So the rule evaluated 14:00 against [00:00, 06:20] and failed

**Review by mitelg — APPROVED** [review]

File: tests/unit/Core/Framework/Rule/TimeRangeRuleTest.php (hunk 3 above)
Comment (nfortier-shopware) [reply tests/unit/Core/Framework/Rule/TimeRangeRuleTest.php:82]: Also after rechecking this test and other tests in the file, it's not about plain datetime with full day and time, but more about gap between time only with timezone differences

**Review by SpiGAndromeda — APPROVED** [review]
