### PR TITLE
fix: NEXT-40000 - add order transaction transition action pay

### LINKED ISSUE #5795: Missing state_machine_transition "paid" for some order_transaction transitions
*PHP Version:* 8.3   | *Shopware Version:* latest  | *Affected area / extension:* Platform(Default) 

 ----

*_Actual behaviour:_*

Hi,

There is a problem with transitions for `order_transaction`.
Either there is a missing constant `Shopware\Core\System\StateMachine\Aggregation\StateMachineTransition\StateMachineTransitionActions::ACTION_PAY`  and/or there are some entries missing in the `state_machine_transition` database table for the **order_transaction** state machine.

**Explanation**:

For **order_transaction** there are some transitions that are performed with the action `pay`. 
These transitions are (`technical name from_state` => `technical name to_state`):

- `failed` => `paid`
- `open` => `paid`
- **`paid_partially` => `paid`**
- **`reminded` => `paid`**

Problematic are the **bold** marked transitions.
Why? Because in the database these transitions can only be performend with the action `pay` - the other ones can also be performed with the action `paid`.

On the other hand the class `Shopware\Core\System\StateMachine\Aggregation\StateMachineTransition\StateMachineTransitionActions` only has a constant for `ACTION_PAID` but not for `ACTION_PAY`.

If you are relying on the constants and not checking the database, you would assume that `ACTION_PAID` can also be used for changing the order transaction state for example from `paid_partially` to `paid` - but this is not the case. 
You can only perform this transition with the action `pay` which - as explained above - has no own constant.

*_Expected behaviour:_*

1. Shopware should add the constant `Shopware\Core\System\StateMachine\Aggregation\StateMachineTransition\StateMachineTransitionActions::ACTION_PAY` with value `pay`
2. Shopware should add the entries for the transitions mentioned above with action `paid` and/or clarify why some of the order_transaction state transitions can only be performed with an action that has no constant in the core

*_How to reproduce:_*

Just check the code and database as mentioned above.

You can use the following SQL statement to fetch all **order_transaction** state transitions for actions `pay` and `paid`:

```
SELECT
	smt.id,
	#smt.from_state_id,
	sms_from.technical_name,
	#smst_from.`name`,
	#smt.to_state_id,
	sms_to.technical_name,
	#smst_to.`name`,
	smt.action_name
FROM
	state_machine sm
JOIN
	state_machine_transition smt
	ON (sm.id = smt.state_machine_id)
JOIN
	state_machine_state sms_from
	ON (smt.from_state_id = sms_from.id)
LEFT JOIN
	state_machine_state_translation smst_from
	ON (sms_from.id = smst_from.state_machine_state_id)
JOIN
	state_machine_state sms_to
	ON (smt.to_state_id = sms_to.id)
LEFT JOIN
	state_machine_state_translation smst_to
	ON (sms_to.id = smst_to.state_machine_state_id)
WHERE
	1=1
	AND action_name IN ('paid', 'pay')
	AND smst_from.language_id = 0x2fbb5fe2e29a4d70aa5854ce7ce3e20b
	AND smst_to.language_id = 0x2fbb5fe2e29a4d70aa5854ce7ce3e20b
	AND sm.technical_name = 'order_transaction.state'
order BY
	sms_from.technical_name,
	sms_to.technical_name
	
```

### PR DESCRIPTION
**Pull request by lernhart**
Original PR: https://github.com/shopware/shopware/pull/5803

### 1. Why is this change necessary?

Our transition names can be irritating at times. This PR aims to clean that up.

### 2. What does this change do, exactly?

The underlying migration first aims to create following duplicate order transaction transitions actions, if not existing:
| Old action | new action |
|--------|--------|
| do_pay | process |
| pay | paid |
| pay_partially | paid_partially | 

If run destructively, the migration will remove the old action names alltogether.

### 3. Describe each step to reproduce the issue or behaviour.

Just have a look at state_machine_transition.

### 4. Please link to the relevant issues (if any).

[https://shopware.atlassian.net/browse/NEXT-40000](https://shopware.atlassian.net/browse/NEXT-40000)
[https://github.com/shopware/shopware/issues/5795](https://github.com/shopware/shopware/issues/5795)

### 5. Checklist

- [x] I have rebased my changes to remove merge conflicts
- [x] I have written tests and verified that they fail without my change
- [x] I have created a [changelog file](https://github.com/shopware/platform/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfill them.

### CODE REVIEW

**Comment by mitelg** [comment]
the PR description contains stuff, that was not done here (or not anymore) would be cool, if you could update that

File: src/Core/Checkout/Order/Aggregate/OrderTransaction/OrderTransactionStateHandler.php [hunk 1]
```diff
@@ -112,11 +113,28 @@ public function paid(string $transactionId, Context $context): void
...
+     *
      * @throws InconsistentCriteriaIdsException
      * @throws StateMachineException
      * @throws IllegalTransitionException
      */
     public function payPartially(string $transactionId, Context $context): void
+    {
+        Feature::triggerDeprecationOrThrow(
+            'v6.8.0.0',
+            Feature::deprecatedMethodMessage(__CLASS__, __METHOD__, 'v6.8.0.0', 'OrderTransactionStateHandler::payPartially')
```
Comment (cyl3x) [inline src/Core/Checkout/Order/Aggregate/OrderTransaction/OrderTransactionStateHandler.php]: Correct replacement:
```suggestion
            Feature::deprecatedMethodMessage(__CLASS__, __METHOD__, 'v6.8.0.0', __CLASS__ . '::paidPartially')
```

File: changelog/_unreleased/2024-12-19-rename-transaction-transition-action-pay-and-pay-partially.md [hunk 2]
```diff
@@ -0,0 +1,10 @@
+---
+title: Rename `order_transaction` transition action `pay` and `pay_partially`
+issue: NEXT-40000
+---
+
+# Core
+
```
Comment (cyl3x) [inline changelog/_unreleased/2024-12-19-rename-transaction-transition-action-pay-and-pay-partially.md]:
```suggestion
# Core
```

**Review by mstegmeyer — APPROVED** [review]

**Review by Bird87ZA — APPROVED** [review]

**Review by cyl3x — APPROVED** [review]

**Review by mitelg — APPROVED** [review]

**Comment by hanneswernery** [comment]
👋 https://github.com/shopware/shopware/pull/7652/files#diff-13c2750602d9a206bc042471baf1deaa152dec53b449defd533e21bb0cb1f1dd
Seems like there is no filter that ensures that actual _order transaction_ state transitions are migrated. This migration broke our custom state machine which happen to use "pay" and "pay_partially" state transitions as well when updating to Shopware 6.7.x
