### PR TITLE
fix: manufacturer replace media sidebar to media modal

### LINKED ISSUE #10394: Manufacturer administration should use media modal
### Shopware Version

6.7

### Affected area / extension

Platform(Default)

### Actual behaviour

Creating a new manufacturer or editing a manufacturer uses the media side-panel to manage media.

### Expected behaviour

To provide a consistent experience in the administration, media selection should be done with the media modal.

### How to reproduce

1. Login to administration
2. Catalogues → Manufacturers
3. <kbd>Add manufacturer</kbd>

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by nguyenquocdaile**
### Solution 

https://github.com/user-attachments/assets/1277b14f-6e0f-4326-b28d-39f3bf4cf32f

### CODE REVIEW

**Review by vienthuong — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-manufacturer/page/sw-manufacturer-detail/index.js [hunk 1]
```diff
@@ -201,6 +213,19 @@ export default {
...
         },
 
+        /**
+         * Handles media selection from sw-media-modal-v2
+         */
+        onMediaSelectionChange([mediaEntity]) {
+            this.manufacturer.mediaId = mediaEntity.id;
+        },
+
+        getMediaDefaultFolderId() {
```
Comment (vienthuong) [inline src/Administration/Resources/app/administration/src/module/sw-manufacturer/page/sw-manufacturer-detail/index.js:219]: please move this method into loadEntityData Promise.allSettled to make sure the mediaDefaultFolderId is loaded before the meida-folder is rendered

**Review by sydinh — APPROVED** [review]
