### PR TITLE
fix: use minimal search term length in config tables

### LINKED ISSUE #8018: Set Minimal search term length <> 3
### PHP Version

8.3

### Shopware Version

6.6.10.2

### Affected area / extension

Platform(Default)

### Actual behaviour

The setting `Minimal search term length` appears to take a value of "3" into account regardless of the specified value.

Currently, as a workaround, you need to set `SHOPWARE_DBAL_TOKEN_MINIMUM_LENGTH` in the `.env.local` to "2" for example. 

--> `SHOPWARE_DBAL_TOKEN_MINIMUM_LENGTH=2`

### Expected behaviour

Whatever value is defined gets considered. 

### How to reproduce

Set `Minimal search term length` to 2 (in settings > search). In that case terms with two characters are being ignored, such as "Test ab". Here the "ab" is not being considered and it is only being searched for "Test". Even if split search terms and "AND"-search is active.

### PR DESCRIPTION
**Pull request by tamvt**
This pull request introduces changes to implement a minimal search term length configuration across various components in the system. The changes ensure that the search term length is dynamically loaded from the configuration table and passed to relevant classes, enhancing flexibility and consistency in search functionality.

### Core functionality updates:

* Updated `Tokenizer` to accept an optional `tokenMinimumLength` parameter, replacing the hardcoded minimum token length with a configurable value. [[1]](diffhunk://#diff-a3cdab2d5909472e49840bf324a75c079a72901809eb63c1d94ff1063a353283R16-R32) [[2]](diffhunk://#diff-2764f48916286034215d7f2f9896e9171d98a91e374df2be90d9df75b3b333d3L13-R13)
* Modified `TokenFilter` to load filter configuration dynamically using the new `SearchConfigLoader`, removing the previous static configuration logic. [[1]](diffhunk://#diff-46d9d39f1edbca0c6be98afcd787d838f16e0668fcb1dff1a1649b8bc42dde79L43-R52) [[2]](diffhunk://#diff-46d9d39f1edbca0c6be98afcd787d838f16e0668fcb1dff1a1649b8bc42dde79L100-L129)ff-9854b9bdce67aeecbbc86c20d848186142bf30968df539bf8885adf044b13a95R82)

### Search term handling improvements:

* Updated `ProductSearchKeywordAnalyzer` and `ProductSearchTermInterpreter` to utilize the dynamically loaded `minSearchLength` from the configuration during tokenization and filtering. [[1]](diffhunk://#diff-81c75768c86f37e5ef2de55abcedc57c3376732655029f6bd1eb7a3ce877372bR78-R82) [[2]](diffhunk://#diff-93cfe04f788b8260c084ae323f16917f27a5a24b63422e1b3ffc614b9eb621f0L31-R42)
* Enhanced scoring logic in `ProductSearchTermInterpreter` to factor in the configurable `minSearchLength`.

### Search configuration loader:

* Introduced `loadFilterConfig` method in `SearchConfigLoader` to fetch and cache search-related configurations, including excluded terms and minimum search length.

### CODE REVIEW

File: src/Core/Framework/DataAbstractionLayer/Search/Term/Tokenizer.php [hunk 1]
```diff
@@ -11,15 +13,23 @@ class Tokenizer implements TokenizerInterface
      * @param string[] $preservedChars
      *
      * @internal
+     *
+     *  Property `$tokenMinimumLength` will be removed
```
Comment (mitelg) [inline src/Core/Framework/DataAbstractionLayer/Search/Term/Tokenizer.php]: is there a deprecation tag missing? or when should that be removed?

File: src/Core/Framework/DataAbstractionLayer/Search/Term/TokenizerInterface.php [hunk 2]
```diff
@@ -10,5 +10,5 @@ interface TokenizerInterface
     /**
      * @return list<string>
      */
-    public function tokenize(string $string): array;
+    public function tokenize(string $string, ?int $tokenMinimumLength = null): array;
```
Comment (mitelg) [inline src/Core/Framework/DataAbstractionLayer/Search/Term/TokenizerInterface.php]: that should be a break 🙈 as classes that implement this interface need to update their method as well

File: src/Elasticsearch/Product/SearchConfigLoader.php [hunk 3]
```diff
@@ -61,4 +86,34 @@ public function load(Context $context): array
 
         throw ElasticsearchProductException::configNotFound();
     }
+
+    /**
+     * @return FilterConfig|null
```
Comment (mitelg) [inline src/Elasticsearch/Product/SearchConfigLoader.php]: instead of using an array in object shape, we could directly introduce a small DTO for that

**Review by mitelg — CHANGES_REQUESTED** [review]

File: src/Core/Framework/DataAbstractionLayer/Search/Term/TokenizerInterface.php [hunk 4]
```diff
@@ -11,4 +11,9 @@ interface TokenizerInterface
      * @return list<string>
      */
     public function tokenize(string $string): array;
+
+    /**
+     * @return list<string>
+     */
+    public function tokenizeWithMinLength(string $string, ?int $tokenMinimumLength = null): array;
```
Comment (mitelg) [inline src/Core/Framework/DataAbstractionLayer/Search/Term/TokenizerInterface.php]: this is a break :see_no_evil: every class that implements this interface will not work anymore, once this is released, as an implementation of this method is missing

File: src/Core/Content/Product/SearchKeyword/ProductSearchKeywordAnalyzer.php [hunk 5]
```diff
@@ -73,8 +75,12 @@ public function analyze(ProductEntity $product, Context $context, array $configF
      */
     private function tokenize(array $values, Context $context): array
     {
+        $config = $this->configLoader->load($context);
+
+        /** @phpstan-ignore-next-line This ignore should be removed when the deprecated method signature is updated */
```
Comment (mitelg) [inline src/Core/Content/Product/SearchKeyword/ProductSearchKeywordAnalyzer.php]: would you mind changing it to this? 
```suggestion
        /** @phpstan-ignore specific.identifier.change.me! (This ignore should be removed when the deprecated method signature is updated) */
```
also see https://phpstan.org/user-guide/ignoring-errors
ignore-next-line will ignore every PHPStan issue and not just the specific one.

File: src/Core/Content/Product/SearchKeyword/ProductSearchTermInterpreter.php [hunk 6]
```diff
@@ -28,13 +29,18 @@ public function __construct(
...
     ) {
     }
 
     public function interpret(string $word, Context $context): SearchPattern
     {
-        $tokens = $this->tokenizer->tokenize($word);
+        $config = $this->configLoader->load($context);
+        $minSearchLength = $config[0]['min_search_length'] ?? null;
+
+        /** @phpstan-ignore-next-line This ignore should be removed when the deprecated method signature is updated */
```
Comment (mitelg) [inline src/Core/Content/Product/SearchKeyword/ProductSearchTermInterpreter.php]: see above

File: src/Core/Content/Product/SearchKeyword/ProductSearchTermInterpreter.php [hunk 7]
```diff
@@ -177,12 +183,13 @@ private function groupTokenKeywords(array $matches, array $keywordRows): array
...
      * @return array<string, float>
      */
-    private function score(array $tokens, array $originalTokens, array $matches): array
+    private function score(array $tokens, array $originalTokens, array $matches, ?int $minSearchLength = null): array
     {
         $scoring = [];
 
         foreach ($matches as $match) {
-            $matchSegments = $this->tokenizer->tokenize($match);
+            /** @phpstan-ignore-next-line This ignore should be removed when the deprecated method signature is updated */
```
Comment (mitelg) [inline src/Core/Content/Product/SearchKeyword/ProductSearchTermInterpreter.php]: see above

File: src/Core/Framework/DataAbstractionLayer/Search/Term/Filter/TokenFilter.php [hunk 8]
```diff
@@ -6,24 +6,21 @@
...
-
     /**
      * @internal
+     *
+     * @deprecated tag:v6.8.0 - Property `Connection` will be removed
      */
-    public function __construct(private readonly Connection $connection)
-    {
+    public function __construct(
+        /** @phpstan-ignore-next-line deprecated property, will be removed in v6.8.0 */
```
Comment (mitelg) [inline src/Core/Framework/DataAbstractionLayer/Search/Term/Filter/TokenFilter.php]: the constructor method is internal. so you can directly remove dependencies

File: src/Core/Framework/DataAbstractionLayer/Search/Term/SearchTermInterpreter.php [hunk 9]
```diff
@@ -2,21 +2,35 @@
...
+    public function interpret(string $term/* , Context $context */): SearchPattern
     {
-        $terms = $this->tokenizer->tokenize($term);
+        $config = null;
+        if (\func_num_args() === 2) {
+            $context = func_get_arg(1);
+            $config = $this->configLoader->load($context);
+        }
+
+        /** @phpstan-ignore-next-line This ignore should be removed when the deprecated method signature is updated */
```
Comment (mitelg) [inline src/Core/Framework/DataAbstractionLayer/Search/Term/SearchTermInterpreter.php]: see above

File: src/Core/Framework/DataAbstractionLayer/Search/Term/Tokenizer.php (hunk 1 above)
Comment (mitelg) [reply src/Core/Framework/DataAbstractionLayer/Search/Term/Tokenizer.php]: still not solved :thinking:

File: src/Elasticsearch/Product/ProductSearchQueryBuilder.php [hunk 10]
```diff
@@ -42,15 +42,16 @@ public function build(Criteria $criteria, Context $context): BuilderInterface
     {
         $originalTerm = mb_strtolower((string) $criteria->getTerm());
 
-        $tokens = $this->tokenizer->tokenize($originalTerm);
+        $searchConfig = $this->configLoader->load($context);
+
+        /** @phpstan-ignore-next-line This ignore should be removed when the deprecated method signature is updated */
```
Comment (mitelg) [inline src/Elasticsearch/Product/ProductSearchQueryBuilder.php]: see above

File: src/Elasticsearch/Product/SearchConfigLoader.php [hunk 11]
```diff
@@ -9,9 +9,9 @@
 use Shopware\Core\Framework\Uuid\Uuid;
 
 /**
- * @internal
+ * @final
  *
- * @phpstan-type SearchConfig array{and_logic: string, field: string, tokenize: int, ranking: float}
+ * @phpstan-type SearchConfig array{and_logic: string, excluded_terms: array<string>, min_search_length: int, field: string, tokenize: int, ranking: float}
```
Comment (mitelg) [inline src/Elasticsearch/Product/SearchConfigLoader.php:12]: you do not have to do it now, but on such array shapes, we should definitely think about a DTO :grin:

**Review by mitelg — CHANGES_REQUESTED** [review]

**Review by mitelg — APPROVED** [review]

File: src/Core/Framework/DataAbstractionLayer/Search/Term/Filter/TokenFilter.php [hunk 12]
```diff
@@ -40,19 +32,21 @@ public function filter(array $tokens, Context $context): array
...
+        return $this->excludedTermsFilter(
+            $tokens,
+            array_flip($config[0]['excluded_terms'] ?? [])
+        );
     }
 
     public function reset(): void
     {
-        $this->config = [];
+        // do nothing
```
Comment (nguyenytran) [inline src/Core/Framework/DataAbstractionLayer/Search/Term/Filter/TokenFilter.php:49]: i'm not sure 😃

**Review by nguyenytran — APPROVED** [review]

File: changelog/_unreleased/2025-07-07-use-minimal-search-term-length-in-config-tables.md [hunk 13]
```diff
@@ -0,0 +1,12 @@
+---
+title: Use minimal search term length in config tables
+issue: 8018
+---
+# Core
```
Comment (vienthuong) [inline changelog/_unreleased/2025-07-07-use-minimal-search-term-length-in-config-tables.md:5]: please add t he upgrade information that what this change affect the configuration

File: changelog/_unreleased/2025-07-07-use-minimal-search-term-length-in-config-tables.md [hunk 14]
```diff
@@ -0,0 +1,12 @@
...
+* Changed these classes to load the minimal search term length from the config table and pass it to the Tokenizer.
+   * `Shopware\Core\Content\Product\SearchKeyword\ProductSearchKeywordAnalyzer`
+   * `Shopware\Core\Content\Product\SearchKeyword\ProductSearchTermInterpreter`
+   * `Shopware\Core\Framework\DataAbstractionLayer\Search\Term\SearchTermInterpreter`
+   * `Shopware\Elasticsearch\Product\ProductSearchQueryBuilder`
+* Changed `Shopware\Core\Framework\DataAbstractionLayer\Search\Term\Filter\TokenFilter` to use `SearchConfigLoader` to load filter config.
+* Changed `load` method in `Shopware\Elasticsearch\Product\SearchConfigLoader` to load min search length and excluded terms.
```
Comment (vienthuong) [inline changelog/_unreleased/2025-07-07-use-minimal-search-term-length-in-config-tables.md:12]: Where is the deprecation notice of the env variable?

File: src/Elasticsearch/Product/SearchConfigLoader.php [hunk 15]
```diff
@@ -34,10 +34,11 @@ public function __construct(private readonly Connection $connection)
     public function load(Context $context): array
```
Comment (vienthuong) [inline src/Elasticsearch/Product/SearchConfigLoader.php:32]: can youb added a CachedSearchConfigLoader that decorates this loader?

File: changelog/_unreleased/2025-07-07-use-minimal-search-term-length-in-config-tables.md [hunk 16]
```diff
@@ -0,0 +1,12 @@
+---
+title: Use minimal search term length in config tables
+issue: 8018
+---
```
Comment (vienthuong) [inline changelog/_unreleased/2025-07-07-use-minimal-search-term-length-in-config-tables.md:4]: also maybe deprecate the parameter and env variable in src/Core/Framework/DependencyInjection/data-abstraction-layer.xml:11

File: src/Core/Content/Product/SearchKeyword/ProductSearchTermInterpreter.php [hunk 17]
```diff
@@ -28,13 +29,18 @@ public function __construct(
...
     ) {
     }
 
     public function interpret(string $word, Context $context): SearchPattern
     {
-        $tokens = $this->tokenizer->tokenize($word);
+        $config = $this->configLoader->load($context);
+        $minSearchLength = $config[0]['min_search_length'] ?? null;
+
+        /** @phpstan-ignore arguments.count (This ignore should be removed when the deprecated method signature is updated) */
```
Comment (vienthuong) [inline src/Core/Content/Product/SearchKeyword/ProductSearchTermInterpreter.php:42]: maybe add @deprecated tag v6.8.0 so we can remember it when remove 6.8.0 feature flag, same for other places

**Review by vienthuong — APPROVED** [review]

**Comment by shyim** [comment]
Heyy 👋 

This PR broke several pipelines:

```
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException {#23476
  #message: "The service "Shopware\Core\Framework\DataAbstractionLayer\Search\Term\SearchTermInterpreter" has a dependency on a non-existent service "Shopware\Elasticsearch\Product\SearchConfigLoader"."
  #code: 0
  #file: "./vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php"
  #line: 116
  -id: "Shopware\Elasticsearch\Product\SearchConfigLoader"
  -sourceId: "Shopware\Core\Framework\DataAbstractionLayer\Search\Term\SearchTermInterpreter"
  -alternatives: []
  trace: {
    ./vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:116 { …}
    ./vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:123 { …}
    ./vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:83 { …}
    ./vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:84 { …}
    ./vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:48 { …}
    ./vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:93 { …}
    ./vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:48 { …}
    ./vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:84 { …}
    ./vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:48 { …}
    ./vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:45 { …}
    ./vendor/symfony/dependency-injection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:39 { …}
    ./vendor/symfony/dependency-injection/Compiler/Compiler.php:73 { …}
    ./vendor/symfony/dependency-injection/ContainerBuilder.php:814 { …}
    ./vendor/symfony/http-kernel/Kernel.php:499 { …}
    ./vendor/symfony/http-kernel/Kernel.php:744 { …}
    ./vendor/symfony/http-kernel/Kernel.php:120 { …}
    ./vendor/shopware/core/Kernel.php:161 { …}
    ./bin/console:54 {
      {closure}
      › $application = new Application($kernel);
      › $kernel->boot();
      › 
    }
    ./vendor/symfony/runtime/Resolver/DebugClosureResolver.php:25 { …}
    ./vendor/autoload_runtime.php:24 { …}
    ./bin/console:17 { …}
  }
2025-07-28T01:32:38+00:00 [critical] Uncaught Exception: The service "Shopware\Core\Framework\DataAbstractionLayer\Search\Term\SearchTermInterpreter" has a dependency on a non-existent service "Shopware\Elasticsearch\Product\SearchConfigLoader".
}
```


The SearchConfigLoader should be in Core bundle, I think if it's needed also in Core namespace
