### PR TITLE
fix: Missing undefined array key checks in HookableBusinessEvent

### LINKED ISSUE #15395: Order state change throws error if you have installed app that activates webhooks for order status change
### Shopware Version

6.7.8

### Affected area / extension

Platform(Default)

### Actual behaviour

When order status change happens this error shows. 

Image

You need to have webhooks active on order status change. In this Shopware instance we use our app that has installed webhooks during installation in its manifest. 
It works fine with other previous versions. 

Error details: 
```
{
    "errors": [
        {
            "code": "0",
            "status": "500",
            "title": "Internal Server Error",
            "detail": "Warning: Undefined array key \u0022data\u0022",
            "meta": {
                "trace": [
                    {
                        "file": "\/usr\/www\/users\/tscon\/shopware6-automation\/vendor\/shopware\/core\/Framework\/Webhook\/Hookable\/HookableBusinessEvent.php",
                        "line": 50,
                        "function": "checkPermissionsForDataType",
                        "class": "Shopware\\Core\\Framework\\Webhook\\Hookable\\HookableBusinessEvent",
                        "type": "-\u003E"
                    },
                    {
                        "file": "\/usr\/www\/users\/tscon\/shopware6-automation\/vendor\/shopware\/core\/Framework\/Webhook\/Service\/WebhookManager.php",
                        "line": 321,
                        "function": "isAllowed",
                        "class": "Shopware\\Core\\Framework\\Webhook\\Hookable\\HookableBusinessEvent",
                        "type": "-\u003E"
                    },
                    {
                        "file": "\/usr\/www\/users\/tscon\/shopware6-automation\/vendor\/shopware\/core\/Framework\/Webhook\/Service\/WebhookManager.php",
                        "line": 203,
                        "function": "isEventDispatchingAllowed",
                        "class": "Shopware\\Core\\Framework\\Webhook\\Service\\WebhookManager",
                        "type": "-\u003E"
                    },
                    {
                        "file": "\/usr\/www\/users\/tscon\/shopware6-automation\/vendor\/shopware\/core\/Framework\/Webhook\/Service\/WebhookManager.php",
                        "line": 117,
                        "function": "callWebhooksSynchronous",
                        "class": "Shopware\\Core\\Framework\\Webhook\\Service\\WebhookManager",
                        "type": "-\u003E"
                    },
                    {
                        "file": "\/usr\/www\/users\/tscon\/shopware6-automation\/vendor\/shopware\/core\/Profiling\/Profiler.php",
                        "line": 67,
                        "function": "{closure:Shopware\\Core\\Framework\\Webhook\\Service\\WebhookManager::callWebhooks():117}",
                        "class": "Shopware\\Core\\Framework\\Webhook\\Service\\WebhookManager",
                        "type": "-\u003E"
                    },
                    {
                        "file": "\/usr\/www\/users\/tscon\/shopware6-automation\/vendor\/shopware\/core\/Framework\/Webhook\/Service\/WebhookManager.php",
                        "line": 115,
                        "function": "trace",
                        "class": "Shopware\\Core\\Profiling\\Profiler",
                        "type": "::"
                    },
                    {
                        "file": "\/usr\/www\/users\/tscon\/shopware6-automation\/vendor\/shopware\/core\/Framework\/Webhook\/Service\/WebhookManager.php",
                        "line": 75,
                        "function": "callWebhooks",
                        "class": "Shopware\\Core\\Framework\\Webhook\\Service\\WebhookManager",
                        "type": "-\u003E"
                    },
                    {
                        "file": "\/usr\/www\/users\/tscon\/shopware6-automation\/vendor\/shopware\/core\/Framework\/Webhook\/WebhookDispatcher.php",
                        "line": 34,
                        "function": "dispatch",
                        "class": "Shopware\\Core\\Framework\\Webhook\\Service\\WebhookManager",
                        "type": "-\u003E"
                    },
                    {
                        "file": "\/usr\/www\/users\/tscon\/shopware6-automation\/vendor\/shopware\/core\/Framework\/Event\/NestedEventDispatcher.php",
                        "line": 31,
                        "function": "dispatch",
                        "class": "Shopware\\Core\\Framework\\Webhook\\WebhookDispatcher",
                        "type": "-\u003E"
                    },
                    {
                        "file": "\/usr\/www\/users\/tscon\/shopware6-automation\/vendor\/symfony\/event-dispatcher\/Debug\/TraceableEventDispatcher.php",
                        "line": 126,
                        "function": "dispatch",
                        "class": "Shopware\\Core\\Framework\\Event\\NestedEventDispatcher",
                        "type": "-\u003E"
                    },
                    {
                        "file": "\/usr\/www\/users\/tscon\/shopware6-automation\/vendor\/shopware\/core\/Checkout\/Order\/Listener\/OrderStateChangeEventListener.php",
                        "line": 159,
                        "function": "dispatch",
                        "class": "Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher",
                        "type": "-\u003E"
                    },
                    {
                        "file": "\/usr\/www\/users\/tscon\/shopware6-automation\/vendor\/shopware\/core\/Checkout\/Order\/Listener\/OrderStateChangeEventListener.php",
                        "line": 111,
                        "function": "dispatchEvent",
                        "class": "Shopware\\Core\\Checkout\\Order\\Listener\\OrderStateChangeEventListener",
                        "type": "-\u003E"
                    },
                    {
                        "file": "\/usr\/www\/users\/tscon\/shopware6-automation\/vendor\/symfony\/event-dispatcher\/Debug\/WrappedListener.php",
                        "line": 115,
                        "function": "onOrderStateChange",
                        "class": "Shopware\\Core\\Checkout\\Order\\Listener\\OrderStateChangeEventListener",
                        "type": "-\u003E"
                    },
                    {
                        "file": "\/usr\/www\/users\/tscon\/shopware6-automation\/vendor\/symfony\/event-dispatcher\/EventDispatcher.php",
                        "line": 206,
                        "function": "__invoke",
                        "class": "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener",
                        "type": "-\u003E"
                    },
                    {
                        "file": "\/usr\/www\/users\/tscon\/shopware6-automation\/vendor\/symfony\/event-dispatcher\/EventDispatcher.php",
                        "line": 56,
                        "function": "callListeners",
                        "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
                        "type": "-\u003E"
                    },
                    {
                        "file": "\/usr\/www\/users\/tscon\/shopware6-automation\/vendor\/shopware\/core\/Content\/Flow\/Dispatching\/FlowDispatcher.php",
                        "line": 43,
                        "function": "dispatch",
                        "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
                        "type": "-\u003E"
                    },
                    {
                        "file": "\/usr\/www\/users\/tscon\/shopware6-automation\/vendor\/shopware\/core\/Framework\/Webhook\/WebhookDispatcher.php",
                        "line": 28,
                        "function": "dispatch",
                        "class": "Shopware\\Core\\Content\\Flow\\Dispatching\\FlowDispatcher",
                        "type": "-\u003E"
                    },
                    {
                        "file": "\/usr\/www\/users\/tscon\/shopware6-automation\/vendor\/shopware\/core\/Framework\/Event\/NestedEventDispatcher.php",
                        "line": 31,
                        "function": "dispatch",
                        "class": "Shopware\\Core\\Framework\\Webhook\\WebhookDispatcher",
                        "type": "-\u003E"
                    },
                    {
                        "file": "\/usr\/www\/users\/tscon\/shopware6-automation\/vendor\/symfony\/event-dispatcher\/Debug\/TraceableEventDispatcher.php",
                        "line": 126,
                        "function": "dispatch",
                        "class": "Shopware\\Core\\Framework\\Event\\NestedEventDispatcher",
                        "type": "-\u003E"
                    },
                    {
                        "file": "\/usr\/www\/users\/tscon\/shopware6-automation\/vendor\/shopware\/core\/System\/StateMachine\/StateMachineRegistry.php",
                        "line": 206,
                        "function": "dispatch",
                        "class": "Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher",
                        "type": "-\u003E"
                    },
                    {
                        "file": "\/usr\/www\/users\/tscon\/shopware6-automation\/vendor\/shopware\/core\/Framework\/Context.php",
                        "line": 201,
                        "function": "{closure:Shopware\\Core\\System\\StateMachine\\StateMachineRegistry::transition():115}",
                        "class": "Shopware\\Core\\System\\StateMachine\\StateMachineRegistry",
                        "type": "-\u003E"
                    },
                    {
                        "file": "\/usr\/www\/users\/tscon\/shopware6-automation\/vendor\/shopware\/core\/System\/StateMachine\/StateMachineRegistry.php",
                        "line": 115,
                        "function": "scope",
                        "class": "Shopware\\Core\\Framework\\Context",
                        "type": "-\u003E"
                    },
                    {
                        "file": "\/usr\/www\/users\/tscon\/shopware6-automation\/vendor\/shopware\/core\/Checkout\/Order\/SalesChannel\/OrderService.php",
                        "line": 100,
                        "function": "transition",
                        "class": "Shopware\\Core\\System\\StateMachine\\StateMachineRegistry",
                        "type": "-\u003E"
                    },
                    {
                        "file": "\/usr\/www\/users\/tscon\/shopware6-automation\/vendor\/shopware\/core\/Checkout\/Order\/Api\/OrderActionController.php",
                        "line": 70,
                        "function": "orderStateTransition",
                        "class": "Shopware\\Core\\Checkout\\Order\\SalesChannel\\OrderService",
                        "type": "-\u003E"
                    },
                    {
                        "file": "\/usr\/www\/users\/tscon\/shopware6-automation\/vendor\/symfony\/http-kernel\/HttpKernel.php",
                        "line": 183,
                        "function": "orderStateTransition",
                        "class": "Shopware\\Core\\Checkout\\Order\\Api\\OrderActionController",
                        "type": "-\u003E"
                    },
                    {
                        "file": "\/usr\/www\/users\/tscon\/shopware6-automation\/vendor\/symfony\/http-kernel\/HttpKernel.php",
                        "line": 76,
                        "function": "handleRaw",
                        "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
                        "type": "-\u003E"
                    },
                    {
                        "file": "\/usr\/www\/users\/tscon\/shopware6-automation\/vendor\/shopware\/core\/Framework\/Adapter\/Kernel\/HttpKernel.php",
                        "line": 72,
                        "function": "handle",
                        "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
                        "type": "-\u003E"
                    },
                    {
                        "file": "\/usr\/www\/users\/tscon\/shopware6-automation\/vendor\/symfony\/http-kernel\/HttpCache\/SubRequestHandler.php",
                        "line": 86,
                        "function": "handle",
                        "class": "Shopware\\Core\\Framework\\Adapter\\Kernel\\HttpKernel",
                        "type": "-\u003E"
                    },
                    {
                        "file": "\/usr\/www\/users\/tscon\/shopware6-automation\/vendor\/symfony\/http-kernel\/HttpCache\/HttpCache.php",
                        "line": 466,
                        "function": "handle",
                        "class": "Symfony\\Component\\HttpKernel\\HttpCache\\SubRequestHandler",
                        "type": "::"
                    },
                    {
                        "file": "\/usr\/www\/users\/tscon\/shopware6-automation\/vendor\/symfony\/http-kernel\/HttpCache\/HttpCache.php",
                        "line": 268,
                        "function": "forward",
                        "class": "Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache",
                        "type": "-\u003E"
                    },
                    {
                        "file": "\/usr\/www\/users\/tscon\/shopware6-automation\/vendor\/symfony\/http-kernel\/HttpCache\/HttpCache.php",
                        "line": 282,
                        "function": "pass",
                        "class": "Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache",
                        "type": "-\u003E"
                    },
                    {
                        "file": "\/usr\/www\/users\/tscon\/shopware6-automation\/vendor\/symfony\/http-kernel\/HttpCache\/HttpCache.php",
                        "line": 202,
                        "function": "invalidate",
                        "class": "Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache",
                        "type": "-\u003E"
                    },
                    {
                        "file": "\/usr\/www\/users\/tscon\/shopware6-automation\/vendor\/shopware\/core\/Framework\/Adapter\/Kernel\/HttpCacheKernel.php",
                        "line": 61,
                        "function": "handle",
                        "class": "Symfony\\Component\\HttpKernel\\HttpCache\\HttpCache",
                        "type": "-\u003E"
                    },
                    {
                        "file": "\/usr\/www\/users\/tscon\/shopware6-automation\/vendor\/shopware\/core\/Kernel.php",
                        "line": 129,
                        "function": "handle",
                        "class": "Shopware\\Core\\Framework\\Adapter\\Kernel\\HttpCacheKernel",
                        "type": "-\u003E"
                    },
                    {
                        "file": "\/usr\/www\/users\/tscon\/shopware6-automation\/vendor\/symfony\/runtime\/Runner\/Symfony\/HttpKernelRunner.php",
                        "line": 35,
                        "function": "handle",
                        "class": "Shopware\\Core\\Kernel",
                        "type": "-\u003E"
                    },
                    {
                        "file": "\/usr\/www\/users\/tscon\/shopware6-automation\/vendor\/autoload_runtime.php",
                        "line": 32,
                        "function": "run",
                        "class": "Symfony\\Component\\Runtime\\Runner\\Symfony\\HttpKernelRunner",
                        "type": "-\u003E"
                    },
                    {
                        "file": "\/usr\/www\/users\/tscon\/shopware6-automation\/public\/index.php",
                        "line": 10,
                        "args": [
                            "\/usr\/www\/users\/tscon\/shopware6-automation\/vendor\/autoload_runtime.php"
                        ],
                        "function": "require_once"
                    }
                ],
                "file": "\/usr\/www\/users\/tscon\/shopware6-automation\/vendor\/shopware\/core\/Framework\/Webhook\/Hookable\/HookableBusinessEvent.php",
                "line": 64
            }
        }
    ]
}
 
```

### Expected behaviour

Webhook for order status change to be sent and no error to show to the customer in frontend.

### How to reproduce

Install an app with webhooks for order status change. 
You can install our app if you want to test: 
https://store.shopware.com/de/trus502933614734/trusted-shops-easy-integration-fuer-shopware-6.html

### PR DESCRIPTION
**Pull request by mitelg**
### 1. Why is this change necessary?

Due to the refactoring of removing the usage of `empty` it can now happen, that an undefined array key access is happening in the `HookableBusinessEvent`. (see PR https://github.com/shopware/shopware/pull/15042/changes#diff-805d7e1aa3994187a04e7a6b72cc75ab40ef9f46e90d344909a5e961f269728dR64-R65 )

### 2. What does this change do, exactly?

Use `??` operator to initialise the variables correctly.

### 3. Describe each step to reproduce the issue or behaviour.

Execute the `HookableBusinessEventTest` with the `restrictWarnings` setting in the `phpunit.xml.dist` set to `false`. Warnings about undefined array key will appear, like described in the linked issue. 

### 4. Please link to the relevant issues (if any).

- closes https://github.com/shopware/shopware/issues/15395

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have updated developer-facing release notes if this change is **relevant** for external developers:
  - Add a short entry to `RELEASE_INFO-6.<major>.md` under “Upcoming” for informational changes, including the consequences of the change and how it affects external developers.
  - Add an `UPGRADE` section in `UPGRADE-6.<next-major>.md` for breaking changes (what/why/impact/how to adapt).
  - See the [Documenting a Release Process](https://github.com/shopware/shopware/blob/trunk/delivery-process/documenting-a-release.md) for details.
- [ ] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfilled them

### CODE REVIEW

**Review by larskemper — APPROVED** [review]

File: src/Core/Framework/Event/EventData/EntityCollectionType.php [hunk 1]
```diff
@@ -2,17 +2,24 @@
 
 namespace Shopware\Core\Framework\Event\EventData;
 
+use Shopware\Core\Framework\DataAbstractionLayer\EntityDefinition;
 use Shopware\Core\Framework\Log\Package;
 
 #[Package('fundamentals@after-sales')]
```
Comment (MalteJanz) [inline src/Core/Framework/Event/EventData/EntityCollectionType.php]: While you are at it: this package annotation looks wrong. I guess it should be `framework`? I don't think we ever worked on this code and can't imagine how this fits our domain.

File: src/Core/Framework/Event/EventData/EntityType.php
Comment (MalteJanz) [inline src/Core/Framework/Event/EventData/EntityType.php]: see above

File: src/Core/Framework/Event/EventData/ScalarValueType.php [hunk 2]
```diff
@@ -2,6 +2,8 @@
 
 namespace Shopware\Core\Framework\Event\EventData;
 
+use Shopware\Core\Framework\Feature;
+use Shopware\Core\Framework\FrameworkException;
 use Shopware\Core\Framework\Log\Package;
 
 #[Package('fundamentals@after-sales')]
```
Comment (MalteJanz) [inline src/Core/Framework/Event/EventData/ScalarValueType.php]: see above

File: src/Core/Framework/Webhook/Hookable/HookableBusinessEvent.php [hunk 3]
```diff
@@ -70,15 +70,18 @@ private function checkPermissionsForDataType(array $dataType, AclPrivilegeCollec
...
             return false;
         }
 
         if ($type === EntityType::TYPE || $type === EntityCollectionType::TYPE) {
-            /** @var EntityDefinition $definition */
-            $definition = new $dataType['entityClass']();
-            if (!$permissions->isAllowed($definition->getEntityName(), AclRoleDefinition::PRIVILEGE_READ)) {
-                return false;
+            $entityDefinitionClass = $dataType['entityClass'] ?? null;
+            if (\is_string($entityDefinitionClass) && is_a($entityDefinitionClass, EntityDefinition::class, true)) {
```
Comment (MalteJanz) [inline src/Core/Framework/Webhook/Hookable/HookableBusinessEvent.php]: Should there be some kind of exception or warning log if this `if` isn't true? Or is it fine to silently ignoring it here? I guess before it would have raised an error if the class didn't exist?

**Review by MalteJanz — APPROVED** [review]

**Review by arens-myz — APPROVED** [review]

File: src/Core/Framework/Webhook/Hookable/HookableBusinessEvent.php (hunk 3 above)
Comment (mitelg) [reply src/Core/Framework/Webhook/Hookable/HookableBusinessEvent.php]: added an exception

File: src/Core/Framework/Event/EventData/EntityCollectionType.php (hunk 1 above)
Comment (mitelg) [reply src/Core/Framework/Event/EventData/EntityCollectionType.php]: changed all I could find
