### PR TITLE
fix: Fix snippet validate command

### LINKED ISSUE #12609: Fix translation:validate command
### Shopware Version

6.7.2.3

### Affected area / extension

Platform(Default)

### Actual behaviour

`translation:validate` (formerly known as `snippet:validate`) fails, with a huge lists of all snippets, even if they're fine

### Expected behaviour

`translation:validate` (formerly known as `snippet:validate`) should work and run in the pipeline

### How to reproduce

Run `translation:validate`, get errors.

### PR DESCRIPTION
**Pull request by lukasrump**
### 1. Why is this change necessary?
Closes #12609

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Core/System/Snippet/SnippetValidator.php [hunk 1]
```diff
@@ -29,7 +30,7 @@
      * @internal
      */
     public function __construct(
-        private SnippetFileCollection $deprecatedSnippetFiles,
+        private SnippetFileCollection $loadedSnippetFiles,
```
Comment (marcelbrode) [inline src/Core/System/Snippet/SnippetValidator.php:33]: "loaded" sounds ambiguous. It's only about our file snippets, provided by shopware, right? Maybe "bundledSnippetFiles" or so?

See this as optional. Dunno a perfect name, but maybe worth a thought 🤔

**Review by marcelbrode — APPROVED** [review]

File: src/Core/System/Snippet/SnippetValidator.php (hunk 1 above)
Comment (lukasrump) [reply src/Core/System/Snippet/SnippetValidator.php:33]: I named it that way because these are the snippets that come from the SnippetFileLoader e.g for Plugins

Comment (marcelbrode) [reply src/Core/System/Snippet/SnippetValidator.php:33]: Ah, okay

**Review by MartinKrzykawski — APPROVED** [review]
