### PR TITLE
fix: load cms page association data with category has no cms page

### LINKED ISSUE #15214: Retrieving the cmsPage field in the SEO URL template of a category page fails.
### Shopware Version

6.7.x

### Affected area / extension

Platform(Default)

### Actual behaviour

We've noticed that the issue occurs with the newly created category or when the layout of that category is deleted.  The behavior is that the default category layout is set to that category during processing, not in the database. That leads to the inconsistent loading `cmsPage` association.

### Expected behaviour

With the newly created category and layout that have no cms_page_id, the default cms page should be loaded correctly (including both cmsPageId and cmsPage in the category entity).

### How to reproduce

- Create a new category, or delete the layout of the existing category
- Check if with Shopware\Core\Content\Seo\SeoUrlGenerator::generate(), categories is loaded with `cmsPage` association data.

Image

Image

### PR DESCRIPTION
**Pull request by rittou**
Currently, the category's cmsPageId is null when it's newly created, or the layout is deleted in the administration.
And via `CategorySubscriber`, it's assigned to the default layout for runtime use. But the `cmsPage` association is missing there, despite the association's criteria that include it.

That's why we raised this PR to solve it:
- No longer listen to the category loaded and assign the default layout. Instead, we use `EntityWriteEvent` to check if the category's cmsPageId in the payload is valid. If not, we will add the default one to the payload for the following operation for persistence. 
- Add a migration that sets the default layout to all categories that are of the `page` type and have no cmsPageId.
- Deprecate the runtime field `cmsPageIdSwitched` which is no longer used
- Refactor a bit to the `SeoUrlGenerator` without cloning the seoUrl

### CODE REVIEW

File: src/Core/Content/Seo/SeoUrlGenerator.php
Comment (mitelg) [inline src/Core/Content/Seo/SeoUrlGenerator.php:63]: couldn't we just add the association here to the criteria? I am not sure, what happens if the entity has no such association. hopefully it will just be ignored. but with that we do not need to fetch them in another call 🤔

Comment (rittou) [reply src/Core/Content/Seo/SeoUrlGenerator.php:63]: The association has already been added to the criteria below:
```php
if ($this->loadTwigTemplate($config, $template)) {
            $associations = $this->getAssociations($template, $repository->getDefinition());
            $criteria->addAssociations($associations);

            $criteria->setLimit(50);
            ... 
```

The thing is:
- If the category has been assigned to a cms page -> everything works properly with cmsPage association data
- Otherwise, the default cms page ID will be assigned via `CategorySubscriber`, but it is after the loaded categories. That's why we miss them.



> About what happens if the entity has no such association

Maybe the external wants to use it for some customization, or whatever. But in the end, if the category has cmsPageId there, but no association data (with association in criteria), it would confuse them.
So, IMHO, we need to take care of it.

Comment (vienthuong) [reply src/Core/Content/Seo/SeoUrlGenerator.php:63]: I guess this solution is just a hacky way to load the default cms page for the category when its CMSPageId is null. The question is why we need this special treatment in \Shopware\Core\Content\Category\Subscriber\CategorySubscriber? can we just set the default cmsPageId on write if the user didn't provide it instead? cc @shopware/product-cc-discovery, do you know if it's an intended behavior?

File: src/Core/Content/Seo/SeoUrlGenerator.php [hunk 1]
```diff
@@ -91,41 +93,55 @@ private function generateUrls(
...
+
+        foreach ($entities as $entity) {
             $seoUrl = new SeoUrlEntity();
             $seoUrl->setForeignKey($entity->getUniqueIdentifier());
 
             $seoUrl->setIsCanonical(true);
             $seoUrl->setIsModified(false);
             $seoUrl->setIsDeleted(false);
 
-            $copy = clone $seoUrl;
```
Comment (vienthuong) [inline src/Core/Content/Seo/SeoUrlGenerator.php:108]: why we need clone it in the first place? it's probably intended to clone it ?

File: src/Core/Content/Seo/SeoUrlGenerator.php [hunk 2]
```diff
@@ -91,41 +93,55 @@ private function generateUrls(
...
+
+            if (
+                $cmsPageId !== null
+                && !$entity->get('cmsPage') instanceof CmsPageEntity
+                && $cmsPages->has($cmsPageId)
+            ) {
+                $entity->assign(['cmsPage' => $cmsPages->get($cmsPageId)]);
+            }
 
             $mapping = $seoUrlRoute->getMapping($entity, $salesChannel);
```
Comment (vienthuong) [inline src/Core/Content/Seo/SeoUrlGenerator.php:110]: I'd pass the criteria to getMapping and handle it specifically in \Shopware\Storefront\Framework\Seo\SeoUrlRoute\NavigationPageSeoUrlRoute::getMapping 

I am aware of N+1 problem with doing so but you can provide a DefaultCmsPageLoader and have some memoize cache there, it feels less hacky that way, this class should know nothing about CmsPage

File: src/Core/Content/Seo/SeoUrlGenerator.php [hunk 3]
```diff
@@ -220,4 +236,29 @@ private function getAssociations(string $template, EntityDefinition $definition)
 
         return array_filter(array_unique($associations));
     }
+
+    /**
+     * @param EntityCollection<covariant Entity> $entities
+     *
+     * @return EntityCollection<covariant Entity>
+     */
+    private function getMissingCmsPageData(EntityCollection $entities, Context $context): EntityCollection
```
Comment (vienthuong) [inline src/Core/Content/Seo/SeoUrlGenerator.php]: This is a bit complex, if tthe criteria has 'cmsPage' but the entity doesn't have it, we can just load the default cms page for it anyway

File: src/Core/Content/Seo/SeoUrlGenerator.php (hunk 1 above)
Comment (rittou) [reply src/Core/Content/Seo/SeoUrlGenerator.php:108]: I did check possible relatives to see if it was used from somewhere for further action, such as updating.

The only place is `SeoUrlUpdater` -> `SeoUrlPersister::updateSeoUrls()`. However, there's a read-only purpose.

So, I think it's illegal to remove it. Could you verify it?

Comment (rittou) [reply src/Core/Content/Seo/SeoUrlGenerator.php:108]: Or we have to consider that for the external as well.  If so, that could make more sense to clone it.

Comment (vienthuong) [reply src/Core/Content/Seo/SeoUrlGenerator.php:108]: I double check it and this clone is not necessary, it only make sense if you put this part outside of the loop 

```
            $seoUrl = new SeoUrlEntity();
            $seoUrl->setForeignKey($entity->getUniqueIdentifier());

            $seoUrl->setIsCanonical(true);
            $seoUrl->setIsModified(false);
            $seoUrl->setIsDeleted(false);

foreach ($searchResult->getEntities() as $entity) {
    $copy = clone $seoUrl;
    $copy->setForeignKey($entity->getUniqueIdentifier());
    ...
}
```

but even in that case, the difference is not noticeable IMO, so we can just remove the clone part here (it made sense before in the original commit but it doesnt make much different now)

File: src/Core/Content/Seo/SeoUrlGenerator.php
Comment (dgrothaus-sw) [reply src/Core/Content/Seo/SeoUrlGenerator.php:63]: I agree with @vienthuong here. This looks like an oversight from `CategorySubscriber` which should not only set the Id but ideally the page too. Although this would add an implicit association without knowing if it was asked for or not.

Comment (rittou) [reply src/Core/Content/Seo/SeoUrlGenerator.php]: If so, I prefer to save the default cms page ID to the database instead of the current approach.

File: src/Core/Content/Category/CategoryDefinition.php [hunk 4]
```diff
@@ -137,6 +137,7 @@ protected function defineFields(): FieldCollection
             (new BoolField('visible', 'visible'))->addFlags(new ApiAware())->setDescription('Displays categories on category page when true.'),
             (new BoolField('active', 'active'))->addFlags(new ApiAware())->setDescription('When boolean value is `true`, the category is listed for selection.'),
 
+            /** @deprecated tag:v6.8.0 - Will be removed without replacement */
             (new BoolField('cms_page_id_switched', 'cmsPageIdSwitched'))->addFlags(new Runtime(), new ApiAware()),
```
Comment (mitelg) [inline src/Core/Content/Category/CategoryDefinition.php]: please also add the deprecated flag

File: RELEASE_INFO-6.7.md [hunk 5]
```diff
@@ -2,6 +2,16 @@
...
 
+### Default CMS page ID now persisted for categories
+
+Previously, when a category had no CMS page assigned, the default CMS page ID was only set at runtime during entity loading. This caused missing `cmsPage` association data when loading categories with criteria that included the `cmsPage` association.
+
+Now the default CMS page ID is automatically written to the database when a category is saved without a `cmsPageId`. A migration also backfills all existing categories that have no CMS page assigned.
+
+The `categoryLoaded` event listener has been removed from `CategorySubscriber` since the default CMS page ID is now always present in the database. Sales channel-specific CMS page defaults continue to be applied at runtime during `salesChannelCategoryLoaded`.
+
+The runtime-only field `cmsPageIdSwitched` on `CategoryDefinition` and `CategoryEntity` has been deprecated and will be removed in v6.8.0. It is no longer used internally.
```
Comment (mitelg) [inline RELEASE_INFO-6.7.md:13]: please also add this already to the 6.8 upgrade guide.

**Review by mitelg — CHANGES_REQUESTED** [review]

File: src/Core/Content/Category/CategoryDefinition.php [hunk 6]
```diff
@@ -137,7 +138,8 @@ protected function defineFields(): FieldCollection
             (new BoolField('visible', 'visible'))->addFlags(new ApiAware())->setDescription('Displays categories on category page when true.'),
             (new BoolField('active', 'active'))->addFlags(new ApiAware())->setDescription('When boolean value is `true`, the category is listed for selection.'),
 
-            (new BoolField('cms_page_id_switched', 'cmsPageIdSwitched'))->addFlags(new Runtime(), new ApiAware()),
+            /** @deprecated tag:v6.8.0 - Will be removed without replacement */
+            (new BoolField('cms_page_id_switched', 'cmsPageIdSwitched'))->addFlags(new Runtime(), new ApiAware(), new Deprecated('v6.7.9.0', 'v6.8.0.0')),
```
Comment (mitelg) [inline src/Core/Content/Category/CategoryDefinition.php]: sorry me again 🙈 

can you also add a feature flag around this, so it is only added if the 6.8 feature flag is not available?

File: tests/integration/Storefront/Framework/HealthCheck/ProductListingReadinessCheckTest.php [hunk 7]
```diff
@@ -77,7 +77,7 @@ public function testCheckProductListingWithoutProducts(): void
         $result = $check->run();
 
         static::assertTrue($result->healthy);
-        static::assertSame(Status::SKIPPED, $result->status);
+        static::assertSame(Status::OK, $result->status);
```
Comment (mitelg) [inline tests/integration/Storefront/Framework/HealthCheck/ProductListingReadinessCheckTest.php:80]: why are you changing this?

File: UPGRADE-6.8.md [hunk 8]
```diff
@@ -4,6 +4,12 @@
 
 <details>
 
+## Default CMS page ID now persisted for categories
+
+Now the default CMS page ID is automatically written to the database when a category is saved without a `cmsPageId`. A migration also backfills all existing categories that have no CMS page assigned.
+
+The runtime-only field `cmsPageIdSwitched` on `CategoryDefinition` will be removed without replacement.
+
```
Comment (mitelg) [inline UPGRADE-6.8.md:12]:
```suggestion
## Default CMS page ID now persisted for categories

The default CMS page ID is now automatically written to the database when a category is saved without a `cmsPageId`.

The runtime-only field `cmsPageIdSwitched` on `CategoryDefinition` was removed without replacement.

```

in this file you need to write like the change already happend. this is what people read after 6.8 was released

File: tests/integration/Storefront/Framework/HealthCheck/ProductListingReadinessCheckTest.php (hunk 7 above)
Comment (rittou) [reply tests/integration/Storefront/Framework/HealthCheck/ProductListingReadinessCheckTest.php:80]: Back then, it was SKIPPED here because of the missing category layout.
Now, the default layout will be saved anytime categories without cmsPageId are written. So, it's OK now.

File: src/Core/Content/Category/CategoryDefinition.php (hunk 6 above)
Comment (rittou) [reply src/Core/Content/Category/CategoryDefinition.php]: Still feeling new with deprecations 🫨 . Thank you.

File: UPGRADE-6.8.md [hunk 9]
```diff
@@ -4,6 +4,12 @@
 
 <details>
 
+## Default CMS page ID now persisted for categories
+
+The default CMS page ID is now automatically written to the database when a category is saved without a `cmsPageId`.
+
+The runtime-only field `cmsPageIdSwitched` on `CategoryDefinition` will be removed without replacement.
```
Comment (mitelg) [inline UPGRADE-6.8.md]:
```suggestion
The runtime-only field `cmsPageIdSwitched` on `CategoryDefinition` was removed without replacement.
```

**Review by mitelg — APPROVED** [review]

File: src/Core/Content/Category/Subscriber/CategorySubscriber.php [hunk 10]
```diff
@@ -74,13 +59,56 @@ public function salesChannelCategoryLoaded(SalesChannelEntityLoadedEvent $event)
...
+        foreach ($event->getWriteResults() as $result) {
+            $payload = $result->getPayload();
+
+            if (!empty($payload['cmsPageId'])) {
+                continue;
+            }
+
+            $needsDefault = match ($result->getOperation()) {
+                EntityWriteResult::OPERATION_INSERT => true,
+                EntityWriteResult::OPERATION_UPDATE => \array_key_exists('cmsPageId', $payload),
```
Comment (vienthuong) [inline src/Core/Content/Category/Subscriber/CategorySubscriber.php]: Is this correct? When they set a new cmsPageId for the category, then the default cms page id will be overridden instead

File: src/Core/Content/Category/Subscriber/CategorySubscriber.php [hunk 11]
```diff
@@ -74,13 +59,56 @@ public function salesChannelCategoryLoaded(SalesChannelEntityLoadedEvent $event)
...
+        $defaultCmsPageId = $this->systemConfigService->getString(CategoryDefinition::CONFIG_KEY_DEFAULT_CMS_PAGE_CATEGORY);
+        if ($defaultCmsPageId === '') {
+            return;
+        }
+
+        $ids = [];
+        foreach ($event->getWriteResults() as $result) {
+            $payload = $result->getPayload();
+
+            if (!empty($payload['cmsPageId'])) {
```
Comment (vienthuong) [inline src/Core/Content/Category/Subscriber/CategorySubscriber.php]:
```suggestion
            if (isset($payload['cmsPageId'])) {
```

File: src/Core/Content/Category/Subscriber/CategorySubscriber.php (hunk 10 above)
Comment (vienthuong) [reply src/Core/Content/Category/Subscriber/CategorySubscriber.php]: but it will be early returned earlier anyway right? then this always be false

File: src/Core/Content/Category/Subscriber/CategorySubscriber.php [hunk 12]
```diff
@@ -74,13 +59,56 @@ public function salesChannelCategoryLoaded(SalesChannelEntityLoadedEvent $event)
                 continue;
             }
 
-            // continue if layout is given and was not set in the `category.loaded` event and has not been modified in between
-            if ($category->getCmsPageId() !== null && (!$category->getCmsPageIdSwitched() || $category->getCmsPageId() !== $systemDefaultLayout)) {
+            if ($category->getCmsPageId() !== null && $category->getCmsPageId() !== $systemDefaultLayout) {
```
Comment (vienthuong) [inline src/Core/Content/Category/Subscriber/CategorySubscriber.php]:
```suggestion
            if ($category->getCmsPageId() !== null) {
```

File: src/Core/Migration/V6_7/Migration1773112488SetDefaultCmsPageIdForCategories.php [hunk 13]
```diff
@@ -0,0 +1,44 @@
...
+
+        $decoded = json_decode((string) $result, true);
+        $cmsPageId = $decoded['_value'] ?? null;
+
+        if (!\is_string($cmsPageId) || $cmsPageId === '') {
+            return;
+        }
+
+        $connection->executeStatement(
+            'UPDATE `category` SET `cms_page_id` = :cmsPageId WHERE `cms_page_id` IS NULL',
```
Comment (vienthuong) [inline src/Core/Migration/V6_7/Migration1773112488SetDefaultCmsPageIdForCategories.php]: only page with type 'page' needs a cms_page_id IMO

File: src/Core/Content/Category/Subscriber/CategorySubscriber.php [hunk 14]
```diff
@@ -74,13 +59,56 @@ public function salesChannelCategoryLoaded(SalesChannelEntityLoadedEvent $event)
...
                 continue;
             }
 
             $category->setCmsPageId($salesChannelDefaultLayout);
-            $category->setCmsPageIdSwitched(true);
         }
     }
+
+    public function onCategoryWritten(EntityWrittenEvent $event): void
```
Comment (vienthuong) [inline src/Core/Content/Category/Subscriber/CategorySubscriber.php]: probably better to use EntityWriteEvent instead (mean you can check it before the write, and use WriteCommand.addPayload to add the cmsPageId into the payload instead of another plain sql update

File: src/Core/Content/Category/Subscriber/CategorySubscriber.php [hunk 15]
```diff
@@ -74,13 +59,56 @@ public function salesChannelCategoryLoaded(SalesChannelEntityLoadedEvent $event)
...
+            $primaryKey = $result->getPrimaryKey();
+            $ids[] = \is_array($primaryKey) ? $primaryKey['id'] : $primaryKey;
+        }
+
+        if ($ids === []) {
+            return;
+        }
+
+        $this->connection->executeStatement(
+            'UPDATE `category` SET `cms_page_id` = :cmsPageId WHERE `id` IN (:ids) AND `cms_page_id` IS NULL',
```
Comment (vienthuong) [inline src/Core/Content/Category/Subscriber/CategorySubscriber.php]: always good to use versionId so we have a PKs pair

File: src/Core/Content/Category/Subscriber/CategorySubscriber.php [hunk 16]
```diff
@@ -74,13 +59,56 @@ public function salesChannelCategoryLoaded(SalesChannelEntityLoadedEvent $event)
...
+    {
+        $defaultCmsPageId = $this->systemConfigService->getString(CategoryDefinition::CONFIG_KEY_DEFAULT_CMS_PAGE_CATEGORY);
+        if ($defaultCmsPageId === '') {
+            return;
+        }
+
+        $ids = [];
+        foreach ($event->getWriteResults() as $result) {
+            $payload = $result->getPayload();
+
```
Comment (vienthuong) [inline src/Core/Content/Category/Subscriber/CategorySubscriber.php:68]: also we can early return if the write category.type is not "page"

File: src/Core/Migration/V6_7/Migration1773112488SetDefaultCmsPageIdForCategories.php (hunk 13 above)
Comment (vienthuong) [inline src/Core/Migration/V6_7/Migration1773112488SetDefaultCmsPageIdForCategories.php]: probably safer to update them in batch

```
        $batchSize = 5000;

        do {
			$affected = ....
        } while ($affected > 0);
```

File: src/Core/Content/Category/Subscriber/CategorySubscriber.php (hunk 14 above)
Comment (rittou) [reply src/Core/Content/Category/Subscriber/CategorySubscriber.php]: The `EntityWriteEvent` seems to be a better solution overall. 
I will go with that approach.

File: src/Core/Content/Category/Subscriber/CategorySubscriber.php (hunk 12 above)
Comment (vienthuong) [reply src/Core/Content/Category/Subscriber/CategorySubscriber.php]: is this even necessary to setCmsPageId when we already have the migration?

Comment (rittou) [reply src/Core/Content/Category/Subscriber/CategorySubscriber.php]: Coincidentally, I'm thinking about that.
IMO, we still need to do it to prioritize the default category set to the sales channel.

File: src/Core/Content/Category/Subscriber/CategorySubscriber.php [hunk 17]
```diff
@@ -74,13 +58,41 @@ public function salesChannelCategoryLoaded(SalesChannelEntityLoadedEvent $event)
...
+        }
+
+        $defaultCmsPageIdBytes = Uuid::fromHexToBytes($defaultCmsPageId);
+
+        foreach ($event->getCommandsForEntity(CategoryDefinition::ENTITY_NAME) as $command) {
+            if ($command instanceof DeleteCommand) {
+                continue;
+            }
+
+            if ($command instanceof InsertCommand) {
```
Comment (mitelg) [inline src/Core/Content/Category/Subscriber/CategorySubscriber.php:74]: why making a difference between insert and update command? they are doing exactly the same 😁

File: src/Core/Content/Category/Subscriber/CategorySubscriber.php (hunk 12 above)
Comment (vienthuong) [reply src/Core/Content/Category/Subscriber/CategorySubscriber.php]: I don't get it, the category.cmsPageId shouldn't be null at this point though

File: src/Core/Content/Category/Subscriber/CategorySubscriber.php (hunk 17 above)
Comment (rittou) [reply src/Core/Content/Category/Subscriber/CategorySubscriber.php:74]: a bit diff of condition check 😆

File: src/Core/Content/Category/Subscriber/CategorySubscriber.php (hunk 12 above)
Comment (rittou) [reply src/Core/Content/Category/Subscriber/CategorySubscriber.php]: Yup, of course, the category.cmsPageId will not be null anymore. 

``` php 
$systemDefaultLayout = $this->systemConfigService->getString(CategoryDefinition::CONFIG_KEY_DEFAULT_CMS_PAGE_CATEGORY);

$salesChannelDefaultLayout = $this->systemConfigService->getString(CategoryDefinition::CONFIG_KEY_DEFAULT_CMS_PAGE_CATEGORY, $salesChannelId);
```
Just an additional case: What the category SHOULD be if those defaults are different !!? Should we use the default layout, which is set **SPECIALLY** for that loading sales channel, instead of the global one?
And if we use the specific one, is the `cmsPage` association data stale again? And, we need to re-fetch it to `setCmsPage`.

Comment (vienthuong) [reply src/Core/Content/Category/Subscriber/CategorySubscriber.php]: I don't think it's possible on the UI to set a salesChannelDefaultLayout for a specific salesChannel though

File: src/Core/Content/Category/Subscriber/CategorySubscriber.php [hunk 18]
```diff
@@ -74,13 +57,41 @@ public function salesChannelCategoryLoaded(SalesChannelEntityLoadedEvent $event)
                 continue;
             }
 
-            // continue if layout is given and was not set in the `category.loaded` event and has not been modified in between
-            if ($category->getCmsPageId() !== null && (!$category->getCmsPageIdSwitched() || $category->getCmsPageId() !== $systemDefaultLayout)) {
+            if ($category->getCmsPageId() !== null) {
```
Comment (vienthuong) [inline src/Core/Content/Category/Subscriber/CategorySubscriber.php]: This is no longer necessary, no?

**Review by tamvt — APPROVED** [review]

File: tests/unit/Core/Content/Seo/SeoUrlGeneratorTest.php [hunk 19]
```diff
@@ -0,0 +1,370 @@
...
+
+    /**
+     * @param list<mixed> $arguments
+     */
+    private function invokePrivate(object $instance, string $methodName, array $arguments = []): mixed
+    {
+        $method = new \ReflectionMethod($instance, $methodName);
+        $method->setAccessible(true);
+
+        return $method->invokeArgs($instance, $arguments);
```
Comment (nfortier-shopware) [inline tests/unit/Core/Content/Seo/SeoUrlGeneratorTest.php]: Is this really necessary? We should not test the private methods directly (use only public accessor)

In general, using reflection is done for other objects consumed by the main one we test, to indeed change some behaviours impossible to set.

Comment (rittou) [reply tests/unit/Core/Content/Seo/SeoUrlGeneratorTest.php]: I've removed them and added more test suites to cover them instead.

File: src/Core/Migration/V6_7/Migration1773112488SetDefaultCmsPageIdForCategories.php [hunk 20]
```diff
@@ -0,0 +1,59 @@
...
+
+        if ($result === false) {
+            return;
+        }
+
+        $decoded = json_decode((string) $result, true);
+        $cmsPageId = $decoded['_value'] ?? null;
+
+        if (!\is_string($cmsPageId) || $cmsPageId === '') {
+            return;
```
Comment (nfortier-shopware) [inline src/Core/Migration/V6_7/Migration1773112488SetDefaultCmsPageIdForCategories.php:38]: Can we cover this return in a migration test?

Comment (rittou) [reply src/Core/Migration/V6_7/Migration1773112488SetDefaultCmsPageIdForCategories.php:38]: More test suites come 😄

**Review by MartinKrzykawski — APPROVED** [review]

File: src/Core/Migration/V6_7/Migration1773112488SetDefaultCmsPageIdForCategories.php (hunk 20 above)
Comment (nfortier-shopware) [reply src/Core/Migration/V6_7/Migration1773112488SetDefaultCmsPageIdForCategories.php:38]: thank you!
