### PR TITLE
fix: consider all vendor folders for composer and app loader

### LINKED ISSUE #11893: Unable to installed the plugin due to  composer failing to parse your composer.json
### Shopware Version

6.6.9.0 & 6.6.10.4

### Affected area / extension

Platform(Default)

### Actual behaviour

When trying to install the plugin via the Shopware admin or CLI. Composer throws the following error:

In Factory.php line 317:
[Composer\Json\JsonValidationException] "./composer.json" does not match the expected JSON schema:
- require.composer/composer: NULL value found, but a string is required.

The plugin installation fails and cannot proceed.

Detailed error:-

Shopware Plugin Lifecycle Service
=================================

 Install 1 plugin(s):
 * AgiqonConnector (v1.3.0)

1^ Symfony\Component\Console\Input\ArrayInput^ {#2348
  #definition: Symfony\Component\Console\Input\InputDefinition^ {#2389
    -arguments: []
    -requiredCount: 0
    -lastArrayArgument: null
    -lastOptionalArgument: null
    -options: []
    -negations: []
    -shortcuts: []
  }
  #stream: null
  #options: []
  #arguments: []
  #interactive: true
  -parameters: array:6 [
    "command" => "require"
    "packages" => array:1 [
      0 => "agiqon/connector:1.3.0"
    ]
    "--working-dir" => "/xxxx/xxxxx/xxxx"
    "--no-interaction" => null
    "--update-with-dependencies" => null
    "--no-scripts" => null
  ]
}
2^ "/xxxx/xxxx/xxxxx/vendor/shopware/core/Framework/Plugin/Composer"

### Expected behaviour

Expected behaviour:

The plugin should be installed successfully without Composer JSON validation errors.
composer.json should be correctly validated according to the Composer schema.

### How to reproduce

When I try to install this plugin, an error occurs. I checked this existing issue: https://github.com/shopware/shopware/issues/6437.

However, I want to use this plugin on Shopware versions 6.6.9.0 and 6.6.10.2. Please let me know if there is any solution for installing the plugin.

I also tested the same Shopware versions on Docker, and there the plugin was installed successfully.

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by shyim**
### 1. Why is this change necessary?

```
InstalledVersions::getInstalledPackagesByType(x)
```

considers only only one vendor folder.  That's why there is deprecation:

> getRawData only returns the first dataset loaded, which may not be what you expect. Use getAllRawData() instead which returns all datasets for all autoloaders present in the process.

This is mostly fine, but when a plugin brings his own vendor folder, it confuses the system and when we call InstalledVersions, we get zero packages back as the plugin didn't required any plugin or app.

### 2. What does this change do, exactly?

Add a helper and use `getAllRawData` to retrieve the composer packages from ALL autoloaders currently active not only the first one

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

**Review by nfortier-shopware — APPROVED** [review]

File: src/Core/Framework/Adapter/Composer/ComposerInfoProvider.php [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+
+namespace Shopware\Core\Framework\Adapter\Composer;
+
+use Composer\InstalledVersions;
+use Shopware\Core\Framework\Log\Package;
+
+/**
+ * @internal
+ *
+ * @phpstan-type ComposerPackage = array{name: string, version: string, path: string, pretty_version: string}
```
Comment (mitelg) [inline src/Core/Framework/Adapter/Composer/ComposerInfoProvider.php]: can we introduce a real object instead of an array?

**Review by mitelg — CHANGES_REQUESTED** [review]

**Review by keulinho — APPROVED** [review]

File: src/Core/Framework/Adapter/Composer/ComposerInfoProvider.php [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+#[Package('framework')]
+class ComposerInfoProvider
+{
+    /**
+     * @var ComposerPackage[]|null
+     */
+    private static ?array $fakedPackages = null;
+
+    /**
+     * @return ComposerPackage[]
```
Comment (mitelg) [inline src/Core/Framework/Adapter/Composer/ComposerInfoProvider.php]:
```suggestion
     * @return list<ComposerPackage>
```

File: src/Core/Framework/Adapter/Composer/ComposerInfoProvider.php [hunk 3]
```diff
@@ -0,0 +1,71 @@
...
+use Shopware\Core\Framework\Log\Package;
+
+/**
+ * @internal
+ */
+#[Package('framework')]
+class ComposerInfoProvider
+{
+    /**
+     * @var ComposerPackage[]|null
```
Comment (mitelg) [inline src/Core/Framework/Adapter/Composer/ComposerInfoProvider.php]:
```suggestion
     * @var list<ComposerPackage>|null
```

File: src/Core/Framework/Adapter/Composer/ComposerInfoProvider.php [hunk 4]
```diff
@@ -0,0 +1,71 @@
...
+                    path: $packageData['install_path'] ?? '',
+                );
+            }
+        }
+
+        return $packages;
+    }
+
+    /**
+     * @param ComposerPackage[] $packages
```
Comment (mitelg) [inline src/Core/Framework/Adapter/Composer/ComposerInfoProvider.php]:
```suggestion
     * @param list<ComposerPackage> $packages
```

**Review by mitelg — APPROVED** [review]

File: src/Core/Framework/Adapter/Composer/ComposerInfoProvider.php [hunk 5]
```diff
@@ -0,0 +1,71 @@
...
+                $packages[$packageName] = new ComposerPackage(
+                    name: $packageName,
+                    version: $packageData['version'] ?? '1.0.0',
+                    prettyVersion: $packageData['pretty_version'] ?? $packageData['version'] ?? '1.0.0.0',
+                    path: $packageData['install_path'] ?? '',
+                );
+            }
+        }
+
+        return $packages;
```
Comment (mitelg) [inline src/Core/Framework/Adapter/Composer/ComposerInfoProvider.php]:
```suggestion
        return array_values($packages);
```
