### PR TITLE
fix: encode logo urls from document config

### LINKED ISSUE #16165: Missing logo on documents
### Shopware Version

Cloud

### Affected area / extension

Platform(Default)

### Actual behaviour

Within the cloud, not all logos are reliably displayed on documents anymore.

A client and I are using a transparent logo that is only displayed as a placeholder. However, this doesn't seem to affect all transparent images.

If I download the affected image and then re-upload it, the re-uploaded image (webp) works.

A different transparent image (jpg / already present in the media library) works without any problems.

---

It seems to be related to the image file name. If I use the same image with spaces and underscores in the name, the image is no longer displayed. If I rename the image to "test," the image is displayed in the document again.

### Expected behaviour

.

### How to reproduce

.

### PR DESCRIPTION
**Pull request by larskemper**
resolves https://github.com/shopware/shopware/issues/16165

Logo urls in the document config where not encoded, causing broken images in generated documents.

### Changes

- General encoding of media urls is implemented with `6.8.0.0` (`MediaUrlGenerator`), till then the `DocumentConfigLoader` does that on its own.
- Fixed `UrlEncoder` to not encode already encoded urls.
- Refactored `MediaUrlGenerator` to use `UrlEncoder`

### CODE REVIEW

**Review by ennasus4sun — APPROVED** [review]

File: src/Core/Framework/Util/UrlEncoder.php [hunk 1]
```diff
@@ -47,4 +41,17 @@ public static function encodeUrl(?string $mediaUrl): ?string
...
         return $encodedPath . $path;
     }
+
+    public static function encodePathSegments(string $path): string
+    {
+        $segments = explode('/', $path);
+
+        foreach ($segments as $index => $segment) {
+            $segments[$index] = rawurlencode(
+                rawurldecode($segment)
```
Comment (MalteJanz) [inline src/Core/Framework/Util/UrlEncoder.php]: This `rawurldecode` wasn't part of any previous implementations. At first glance it looks smart and prevents double encoding an already encoded segment. But on closer inspection its also a source of bugs:
- What if the source `$path` looks like this? `my%sign`? It will likely try to decode `%si` into invalid UTF-8
- We should add test cases for that, a % sign is allowed in most file systems and can be in the (non-encoded) path, which should be encoded to `%25` (or the example `my%25sign`)

I suggest sticking to the old implementation where the caller needs to ensure no double encoding happens and not doing this `rawurldecode` here, otherwise it could be a breaking change

**Review by MalteJanz — CHANGES_REQUESTED** [review]

File: src/Core/Framework/Util/UrlEncoder.php (hunk 1 above)
Comment (larskemper) [reply src/Core/Framework/Util/UrlEncoder.php]: On the `my%sign` case: `rawurldecode` only decodes sequences where `%` is followed by exactly two hex digits. `%si` s is not hex, so its left untouched. Then `rawurlencode` correctly encodes the bare `%` to `%25`

I have added these test cases:
- `my%sign.jpg` -> `my%25sign.jpg`
- `my%.jpg` -> `my%25.jpg`
- `my%25sign.jpg` -> `my%25sign.jpg`

The limitation to that is a filename literally containing `%a0` (valid hex), so the encoder cant distinguish it from an already encoded byte. Pretty much unavoidable and the old implementation (or a caller) has the same issue with an already encoded path.

Comment (MalteJanz) [reply src/Core/Framework/Util/UrlEncoder.php]: You're right, I picked a bad example, so here is a better one. My original file / path contains `contracts%aborted` (`ab` are both valid hex chars) and I guess you can come up with others on your own.

The difference is that the old implementation treated this correctly. It always expected that the caller passes unencoded input to the function and gets encoded output back. So even that `contracts%aborted` would become `contracts%25aborted` instead of something else - likely even invalid UTF-8). Here is the example in a [PHP playground](
https://php-play.dev/?c=DwfgDgFmBQ0CQGcD2BXATgYwKYAIC8OA5BkgHYAuaAhhuQgKRUBGSa5WAJoQNzwdYl%2BHfDmoB3dABt%2BgrAApEqTFgCUvOFlKyOAZRHipm2QuTpsa%2BEaRCAIvqoS0kq-wUzrnC9AEQkRF5w4psoAXEQ4AHQ4GloeupFEwExoAHyECTgACgASmQD6AKIA8gAyvD5%2BhAHC7kJh6VEx2nZRhEmpDThZuYWl3EA&v=8.4&f=html)

This new "smart" implementation would break and return something different for that case. And because this URL encoding is so widely used across shopware and with likely millions of different files across all installations, I would rather not break the behaviour on this in a minor version 😅

Comment (larskemper) [reply src/Core/Framework/Util/UrlEncoder.php]: get it now 😄 I reverted the decode

**Review by MalteJanz — APPROVED** [review]
