### PR TITLE
fix: Required fields can not be saved with empty value

### LINKED ISSUE #12675: For the field "Default search result sorting" the value can be removed even though it is a required field
### Shopware Version

6.7.2.2.

### Affected area / extension

Platform(Default)

### Actual behaviour

The value for the "Default search result sorting" field can be removed, even though it is a required field.

Image

This may result in neither the standard search nor the advanced search working.

Instead, a 404 error occurs when searching and the following error message:

"Shopware\Core\Content\Product\ProductException: Thrown Shopware\Core\Content\Product\ProductException: Could not find sorting with key "" in /var/www/html/vendor/shopware/platform/src/Core/Content/Product/ProductException.php:43"

### Expected behaviour

A value must be set for the field.

### How to reproduce

.

### PR DESCRIPTION
**Pull request by rittou**
### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have updated developer-facing release notes if this change is **relevant** for external developers:
  - Add a short entry to `RELEASE_INFO-6.<major>.md` under “Upcoming” for informational changes, including the consequences of the change and how it affects external developers.
  - Add an `UPGRADE` section in `UPGRADE-6.<next-major>.md` for breaking changes (what/why/impact/how to adapt).
  - See the [Documenting a Release Process](https://github.com/shopware/shopware/blob/trunk/delivery-process/documenting-a-release.md) for details.
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Administration/Resources/app/administration/src/module/sw-settings-listing/page/sw-settings-listing/index.js [hunk 1]
```diff
@@ -118,7 +119,7 @@ export default {
             return Shopware.Filter.getByName('asset');
         },
 
-        salesChannelDefaultSortingError() {
```
Comment (sydinh) [inline src/Administration/Resources/app/administration/src/module/sw-settings-listing/page/sw-settings-listing/index.js:121]: This is a breaking change?

**Review by sydinh — CHANGES_REQUESTED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-settings-listing/page/sw-settings-listing/index.js (hunk 1 above)
Comment (rittou) [reply src/Administration/Resources/app/administration/src/module/sw-settings-listing/page/sw-settings-listing/index.js:121]: Yes, it is, and I did add the deprecation thing there. 
Please help me review it.

File: src/Administration/Resources/app/administration/src/module/sw-settings-listing/page/sw-settings-listing/index.js [hunk 2]
```diff
@@ -174,16 +188,29 @@ export default {
...
+                if (!this.$refs.systemConfig.actualConfigData.null['core.listing.defaultSearchResultSorting']) {
+                    this.hasDefaultSearchResultSortingError = true;
+                }
+
+                if (this.hasDefaultSortingError || this.hasDefaultSearchResultSortingError) {
+                    /**
+                     * display both errors in the UI
+                     * instead of just one using reject() right after the first error
+                     */
+                    reject(new Error(this.$tc('sw-settings-listing.general.messageSaveDefaultValuesEmpty')));
```
Comment (sydinh) [inline src/Administration/Resources/app/administration/src/module/sw-settings-listing/page/sw-settings-listing/index.js]: A very tiny point, but people are transitioning to use $t instead of $tc these days.

File: src/Administration/Resources/app/administration/src/module/sw-settings-listing/page/sw-settings-listing/index.js [hunk 3]
```diff
@@ -212,7 +226,7 @@ export default {
                 })
                 .catch((e) => {
                     const options = {
-                        message: e?.response.data?.errors[0]?.detail || 'Unknown error',
+                        message: e?.message || 'Unknown error',
                     };
```
[the remark this answers is not in the document]
Comment (sydinh) [reply src/Administration/Resources/app/administration/src/module/sw-settings-listing/page/sw-settings-listing/index.js:230]: the bot was correct 😄

File: RELEASE_INFO-6.7.md [hunk 4]
```diff
@@ -159,6 +159,11 @@ Changing a property group or option will no longer automatically invalidate prod
 
 ## Administration
 
+### The default search result sorting can be empty despite of required
```
Comment (sydinh) [inline RELEASE_INFO-6.7.md]: Did you mean a changelog instead?

**Review by sydinh — CHANGES_REQUESTED** [review]

**Review by sydinh — APPROVED** [review]
LGTM overall 👍🏻

File: RELEASE_INFO-6.7.md (hunk 4 above)
Comment (rittou) [reply RELEASE_INFO-6.7.md]: Hmm, sry I don't get it yet. 
All the changelog is in this file, right? 

Anyway, I have changed the title a bit to make it easier for people to understand.

**Review by vienthuong — APPROVED** [review]

**Review by nguyenquocdaile — APPROVED** [review]
