### PR TITLE
fix: incorrect country sorting

### LINKED ISSUE #5413: CountryList is not sorting umlauts properly (Z, Ä, Ö)
*PHP Version:* 8.3   | *Shopware Version:* latest  | *Affected area / extension:* Platform(Default) 

 ----

*_Expected behaviour:_*

Country lists, for example in the registration should sort umlauts next to the non-umlaut vovel.

Currently Österreich is at the end of the list.

*_Actual behaviour:_*

Image

*_How to reproduce:_*

* Activate all countries
* try to register

# More info

I am pretty sure this boils down the the not [multibyte save strnatcasecmp here](https://github.com/shopware/shopware/blob/45ac2a37c9dcc0b801114a5398240fa13f830afb/src/Core/System/Country/CountryCollection.php#L38).

Here is the proof that this does not lead to proper results: https://3v4l.org/J4LBM

On this occasion we should also check other appearances of strnatcasecmp in the code.

We could probably work on a pull request with a fix.

Shall we or do you want to tackle this internally?
And is there also a multibyte aware version of this function anywhere in the Shopware code?

### PR DESCRIPTION
**Pull request by mstegmeyer**
### 1. Why is this change necessary?
Countries with a name like `Österreich` were sorted at the bottom instead of at `O`.

### 2. What does this change do, exactly?
Use SQL instead of non-multibyte-supporting PHP or complicated `intl` extensions.

### 3. Describe each step to reproduce the issue or behaviour.
- Set Storefront language to German.
- See where Österreich is sorted to, should be at `O` instead of at the bottom.

### 4. Please link to the relevant issues (if any).
fixes #5413 

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfill them.

### CODE REVIEW

**Review by cyl3x — APPROVED** [review]

**Review by FlorianKe — COMMENTED** [review]
Should we include a short note in the upgrade file, or is the change too small?

**Comment by mitelg** [comment]
> Should we include a short note in the upgrade file, or is the change too small?

at least the deprecations need to be documented

File: src/Storefront/Page/Account/Login/AccountLoginPageLoader.php [hunk 1]
```diff
@@ -88,13 +88,13 @@ private function getSalutations(SalesChannelContext $salesChannelContext): Salut
     private function getCountries(SalesChannelContext $salesChannelContext): CountryCollection
     {
         $criteria = (new Criteria())
-            ->addFilter(new EqualsFilter('active', true))
```
Comment (mitelg) [inline src/Storefront/Page/Account/Login/AccountLoginPageLoader.php:91]: was intended to drop the active filter?

File: src/Storefront/Page/Address/Detail/AddressDetailPageLoader.php [hunk 2]
```diff
@@ -104,14 +106,14 @@ private function getSalutations(SalesChannelContext $salesChannelContext): Salut
     private function getCountries(SalesChannelContext $salesChannelContext): CountryCollection
     {
         $criteria = (new Criteria())
-            ->addFilter(new EqualsFilter('country.active', true))
```
Comment (mitelg) [inline src/Storefront/Page/Address/Detail/AddressDetailPageLoader.php:107]: same here

File: src/Storefront/Page/Address/Listing/AddressListingPageLoader.php [hunk 3]
```diff
@@ -101,15 +100,15 @@ private function getSalutations(SalesChannelContext $context): SalutationCollect
     private function getCountries(SalesChannelContext $salesChannelContext): CountryCollection
     {
         $criteria = (new Criteria())
-            ->addFilter(new EqualsFilter('country.active', true))
```
Comment (mitelg) [inline src/Storefront/Page/Address/Listing/AddressListingPageLoader.php:104]: same

**Review by mitelg — CHANGES_REQUESTED** [review]
I remembered something and digging in the past, I found this commit: https://github.com/shopware/shopware/commit/5ecb0a4e44410f10a2bc0bfcb855227d6aa783ec

Interesting, that we did the exact opposite back then under the title "optimization" :grimacing: So I would assume, that handling sorting in the DB is more performance intense?

File: src/Storefront/Page/Account/Login/AccountLoginPageLoader.php (hunk 1 above)
Comment (mstegmeyer) [reply src/Storefront/Page/Account/Login/AccountLoginPageLoader.php:91]: Yes, that's already default of the `CountryRoute`

File: src/Storefront/Page/Address/Detail/AddressDetailPageLoader.php (hunk 2 above)
Comment (mstegmeyer) [reply src/Storefront/Page/Address/Detail/AddressDetailPageLoader.php:107]: Yes, that's already default of the `CountryRoute`

File: src/Storefront/Page/Address/Listing/AddressListingPageLoader.php (hunk 3 above)
Comment (mstegmeyer) [reply src/Storefront/Page/Address/Listing/AddressListingPageLoader.php:104]: Yes, that's already default of the `CountryRoute`

**Review by En0Ma1259 — APPROVED** [review]

**Comment by mstegmeyer** [comment]
@mitelg Yes, the sorting via DB adds about 1ms of query time on my system, because during the search-ids phase, it needs to join in the translated field, which it didn't need to do before. (CountryRoute takes roughly 20ms otherwise, roughly 21ms with SQL sorting)

The alternative to correct the sorting is to sort via a Collator from the `php-intl` extension. This basically no performance toll, but it adds a lot of complexity, since we then need to pass a `locale` to it, which means I have to modify the Collection methods to either take a complete `Collator` object or a `string $localeCode` from a SalesChannelContext (or I just inject the SalesChannelContext).

What would you do?

**Comment by mitelg** [comment]
I would give you an approve, once you documented the deprecations :sweat_smile: :+1: 

thanks for giving some numbers, let's see how they work out :+1:

File: changelog/_unreleased/2025-05-27-fix-sorting-of-countries.md [hunk 4]
```diff
@@ -0,0 +1,11 @@
+---
+title: Fix sorting of countries in Storefront
+issue: 5413
+author: Max Stegmeyer
+author_email: m.stegmeyer@shopware.com
+author_github: @mstegmeyer
+---
+# Core
+* Deprecated `Shopware\Core\System\Country\CountryCollection::sortByPositionAndName()`, use SQL field sorting instead.
```
Comment (mitelg) [inline changelog/_unreleased/2025-05-27-fix-sorting-of-countries.md]: do people know that they should add a DAL sorting field to the criteria if you write it like this? :thinking:

Comment (mstegmeyer) [reply changelog/_unreleased/2025-05-27-fix-sorting-of-countries.md]: Better? `use a FieldSorting via the DAL or direct SQL instead`

**Review by mitelg — APPROVED** [review]
