### PR TITLE
fix: loading hookable entities dynamically

### LINKED ISSUE #11742: Make `warehouse` and `warehouse_group` entities hookable
### Technical TODO

Currently there is a hard coded list of entities that are "Hookable" for webhooks in the app system, we should add warehouse and warehouse group entities to them 

The current list is in `\Shopware\Core\Framework\Webhook\Hookable\HookableEventCollector::HOOKABLE_ENTITIES`, we need to make that more dynamic so that plugins (like commercial) can add their entities to the list

### PR DESCRIPTION
**Pull request by leduc92**
fixes: shopware/shopware#11742

### CODE REVIEW

File: src/Core/Framework/Webhook/Hookable/HookableEntityInterface.php [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+    public function isHookable(): bool;
+
+    /**
+     * Returns additional privileges required for webhook events on this entity.
+     * By default, entities get read privileges automatically, but this method
+     * allows specifying additional required privileges.
+     *
+     * @return array<string> List of additional privilege strings (e.g., ['custom:read', 'order:write'])
+     */
+    public function getHookableEventPrivileges(): array;
```
Comment (vienthuong) [inline src/Core/Framework/Webhook/Hookable/HookableEntityInterface.php]: This method is not used anywhere

File: src/Core/Framework/Webhook/Hookable/HookableEntityInterface.php [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+ * @internal only for use by the app-system
+ */
+#[Package('framework')]
+interface HookableEntityInterface
+{
+    /**
+     * Returns whether this entity should be hookable for webhook events.
+     * This method allows entities to conditionally enable/disable their hookable status.
+     */
+    public function isHookable(): bool;
```
Comment (vienthuong) [inline src/Core/Framework/Webhook/Hookable/HookableEntityInterface.php]: This method is unnecessary if the Definition already implements the interface tbh, or the interface won't be needed if the isHookable method is defined (default as false) in EntityDefinition parent class

Comment (vienthuong) [reply src/Core/Framework/Webhook/Hookable/HookableEntityInterface.php]: Another approach could be to create a new tag `shopware.entity.hookable` for hookable entities definitions, so you don't need to touch existing Definition classes. The downside is you can't have additional method like `getHookableEventPrivileges`

File: src/Core/Framework/Webhook/Hookable/HookableEventCollector.php [hunk 3]
```diff
@@ -99,6 +91,31 @@ public function getEntityWrittenEventNamesWithPrivileges(): array
...
+     */
+    public function getHookableEntities(): array
+    {
+        if ($this->discoveredHookableEntities !== null) {
+            return $this->discoveredHookableEntities;
+        }
+
+        $hookableEntities = [];
+
+        foreach ($this->definitionRegistry->getDefinitions() as $definition) {
```
Comment (vienthuong) [inline src/Core/Framework/Webhook/Hookable/HookableEventCollector.php]: this won't work for Attribute Entity probably

File: src/Core/Framework/Webhook/Hookable/HookableEntityInterface.php (hunk 2 above)
Comment (silverDuy) [inline src/Core/Framework/Webhook/Hookable/HookableEntityInterface.php]: Do we have any chance to set the hookable of specific entities to false by plugins

File: src/Core/Checkout/Order/OrderDefinition.php [hunk 4]
```diff
@@ -75,6 +76,16 @@ public function since(): ?string
         return '6.0.0.0';
     }
 
+    public function isHookable(): bool
+    {
+        return true;
+    }
+
+    public function getHookableEventPrivileges(): array
```
Comment (silverDuy) [inline src/Core/Checkout/Order/OrderDefinition.php]: What is the purpose of this method? 🤔 I did not see it used anywhere.

File: src/Core/Framework/Webhook/Hookable/HookableEventCollector.php [hunk 5]
```diff
@@ -99,6 +84,30 @@ public function getEntityWrittenEventNamesWithPrivileges(): array
...
+        }
+
+        $hookableEntities = [];
+
+        foreach ($this->hookableEntityDefinitions as $definition) {
+            if ($definition instanceof EntityDefinition) {
+                $hookableEntities[] = $definition->getEntityName();
+            }
+        }
+
```
Comment (silverDuy) [inline src/Core/Framework/Webhook/Hookable/HookableEventCollector.php:122]: I have not tested it yet, but you might want to consider giving it a try. The idea is to tag the Entity that has an Entity Attribute.

```suggestion
...
use Shopware\Core\Framework\DataAbstractionLayer\Entity;
use Shopware\Core\Framework\DataAbstractionLayer\Attribute\Entity as EntityAttribute;
...


if ($definition instanceof Entity) {

	    $reflection = new \ReflectionClass(get_class($definition));
	
	    $collection = $reflection->getAttributes(EntityAttribute::class);
	
	    if (empty($collection)) {
	        return [];
	    }
	
	    /** @var EntityAttribute $instance */
	    $instance = $collection[0]->newInstance();
	    $hookableEntities[] = $instance->name;
	}
```

**Review by keulinho — APPROVED** [review]
Nice good job, i like the approach, also that you directly thought about attribute entities 

only phpstan is still failing, but once that is fixed it looks really good to me 👍

**Review by silverDuy — APPROVED** [review]

File: src/Core/Framework/Webhook/Hookable/HookableEntityInterface.php [hunk 6]
```diff
@@ -0,0 +1,15 @@
+<?php declare(strict_types=1);
+
+namespace Shopware\Core\Framework\Webhook\Hookable;
+
+use Shopware\Core\Framework\Log\Package;
+
+/**
+ * Marker interface that EntityDefinitions can implement to automatically be tagged as hookable.
+ *
+ * @internal only for use by the app-system
```
Comment (mitelg) [inline src/Core/Framework/Webhook/Hookable/HookableEntityInterface.php:10]: should we really mark that as internal? isn't that something externals should use?

File: src/Core/Framework/Webhook/Hookable/HookableEventCollector.php [hunk 7]
```diff
@@ -99,6 +89,44 @@ public function getEntityWrittenEventNamesWithPrivileges(): array
...
     }
 
+    /**
+     * Dynamically discovers all hookable entities by checking for services tagged with 'shopware.entity.hookable'.
+     *
+     * @return array<string>
+     */
+    public function getHookableEntities(): array
+    {
+        if ($this->hookableEntities !== null) {
```
Comment (mitelg) [inline src/Core/Framework/Webhook/Hookable/HookableEventCollector.php:100]: should we implement the ResetInterface, if we introduce such cache?

**Review by mitelg — CHANGES_REQUESTED** [review]

File: src/Core/Framework/Webhook/Hookable/HookableEntityInterface.php (hunk 6 above)
Comment (keulinho) [reply src/Core/Framework/Webhook/Hookable/HookableEntityInterface.php:10]: Not sure if there is a case where an app should rely on the data of a external plugin to be installed 🤔  Anyway i would first start with internal, in theory externals could already use and when we get requests we can remove internal

@leduc92 one think that came to mind when reading telgis comment: we should make sure that apps can register a webhook from e.g. b2b in commercial, but that app should be still able to be installed when commercial plugin is not there

I had a quick look and at least on manifest schema level there is no validation for which webhook you register, can you double check that you can install an app that listens on b2b events without commercial being active?

**Review by mitelg — APPROVED** [review]

File: src/Core/Framework/Webhook/Hookable/HookableEntityInterface.php (hunk 6 above)
Comment (leduc92) [reply src/Core/Framework/Webhook/Hookable/HookableEntityInterface.php:10]: Hi @keulinho, I have made a simple app to test it. The app listens to b2b events, and we can use it, uninstall it, and install it normally without the commercial being activated. 

Here is the setup of the app:

Webhook registration:
image

Adding hookable to b2b entities:
image

Here is the log and the steps that I tested:
image
