### PR TITLE
fix: display return address

### LINKED ISSUE #11534: Invoice document header missing (sender info) in Shopware 6.7.1
### Shopware Version

6.7.1

### Affected area / extension

Platform(Default)

### Actual behaviour

After updating to Shopware 6.7.1, the generated invoice documents no longer include the sender's address block (company name, address, etc.) above the recipient address — even though no configuration changes were made.

This issue occurs consistently, and the header area that typically shows the merchant's details is entirely missing from the generated PDF invoice. This issue was not present before the update and appeared without any manual changes.

### Expected behaviour

The sender's company information should appear above the customer address on the invoice document

### How to reproduce

Go to Settings > Shop > Documents > Invoice.

1. Ensure that company name and address are correctly filled in under the Header section.
2. Generate a new invoice (e.g. via order > documents).
3. Open the PDF → the sender block (merchant address) is missing above the recipient address.

Image

Image

### Definition of Done

- [x] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by CR0YD**
### 1. Why is this change necessary?
Some companies need their address displayed above the customer address so that when they send a letter, their address is visible without opening the letter.

### 2. What does this change do, exactly?
This change adds a toggle in the admin to controll the rendering of the company address above the customer address in documents. This is sepereated from the 'normal' company address which is displayed on the top right.

[document_without_return_address.pdf](https://github.com/user-attachments/files/21654427/document_without_return_address.pdf)
[document_with_return_address.pdf](https://github.com/user-attachments/files/21654428/document_with_return_address.pdf)

### 4. Please link to the relevant issues (if any).

- closes #11534 

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Core/Migration/V6_7/Migration1754295570DocumentActivateReturnAddress.php [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+    public function getCreationTimestamp(): int
+    {
+        return 1754295570;
+    }
+
+    public function update(Connection $connection): void
+    {
+        $documentConfig = array_map(function ($arr): array {
+            $arr['config'] = json_decode($arr['config'], true, 512, \JSON_THROW_ON_ERROR);
+            $arr['config']['displayReturnAddress'] = true;
```
Comment (ennasus4sun) [inline src/Core/Migration/V6_7/Migration1754295570DocumentActivateReturnAddress.php:24]: Iam not sure ... maybe setting it to `false` by default is the better option?

**Review by ennasus4sun — COMMENTED** [review]
I think this could be more a feature than a fix... This would probably also make it into [this documentation](https://developer.shopware.com/release-notes/6.7/6.7.1.2.html), which is written more for merchants than for developers to let them know what was changed/added. What do you think?

(Also a test should be written for the migration.)

File: src/Core/Migration/V6_7/Migration1754295570DocumentActivateReturnAddress.php (hunk 1 above)
Comment (CR0YD) [reply src/Core/Migration/V6_7/Migration1754295570DocumentActivateReturnAddress.php:24]: I've already had a talk with Daniel about that and we came to the conclusion, that we want to have it set to true by default, as the return address was still always displayed in `Delivery notes`, `quotes` and `partial cancellations`. And to not break with this behavior we decided to set it to true.

**Comment by CR0YD** [comment]
> I think this could be more a feature than a fix... This would probably also make it into [this documentation](https://developer.shopware.com/release-notes/6.7/6.7.1.2.html), which is written more for merchants than for developers to let them know what was changed/added. What do you think?
> 
> (Also a test should be written for the migration.)

I think it is a combination of both, as I add the return address back (fix) combined with the toggle option (improvment).
But I wanted to look more into how we could notify merchants about that so you gave me a good starting point :+1: 

(I'm actually currently working on that. One of the reasons I marked this as a draft :sweat_smile:. But thanks for the hint. )

File: src/Administration/Resources/app/administration/src/module/sw-settings-document/snippet/de-DE.json [hunk 2]
```diff
@@ -36,6 +36,7 @@
       "labelPageSize": "Seitenformat",
       "labelItemsPerPage": "Positionen pro Seite",
       "labelDisplayCompanyAddress": "Geschäftsadresse anzeigen",
+      "labelDisplayReturnAddress": "Absenderadresse anzeigen",
```
Comment (MalteJanz) [inline src/Administration/Resources/app/administration/src/module/sw-settings-document/snippet/de-DE.json]: Maybe make it even more descriptive by adding a tooltip like `Absenderaddresse im Anschriftfeld anzeigen` (I guess that is the correct term for "Brieffenster"? 🙈 )

**Review by MalteJanz — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-settings-document/snippet/de-DE.json (hunk 2 above)
Comment (CR0YD) [reply src/Administration/Resources/app/administration/src/module/sw-settings-document/snippet/de-DE.json]: Good hint :+1: 
I will have a talk with @GitEvil about that.

**Review by larskemper — APPROVED** [review]

**Review by ennasus4sun — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-settings-document/snippet/de-DE.json (hunk 2 above)
Comment (CR0YD) [reply src/Administration/Resources/app/administration/src/module/sw-settings-document/snippet/de-DE.json]: We decided that we change `Absenderadresse` to `Rücksendeangabe` and include `im Anschriftfeld` part in a help text displayed next to the option.

**Review by MalteJanz — APPROVED** [review]

File: changelog/_unreleased/2025-08-12-added-return-address-display-option.md [hunk 3]
```diff
@@ -0,0 +1,15 @@
+---
```
Comment (larskemper) [inline changelog/_unreleased/2025-08-12-added-return-address-display-option.md:1]: Does this change not apply to the DeliveryNote? The snapshot file hasn’t changed 😅

Comment (CR0YD) [reply changelog/_unreleased/2025-08-12-added-return-address-display-option.md:1]: It applies to it, as you can see in the [changed fille](https://github.com/shopware/shopware/pull/11795/files#diff-852ffda42188c5225b10942d8cf00a08b6558900b8eff35e087779f6d37ec60c), but the template for delivery notes still contained the return address above the customer's one (it overwrote the block, in which the return address was deleted), so the snapshot didn't need to b changed.

**Comment by CR0YD** [comment]
Release note information:
https://github.com/shopware/release-notes/pull/93

File: changelog/_unreleased/2025-08-12-added-return-address-display-option.md [hunk 4]
```diff
@@ -0,0 +1,15 @@
...
+author: Simon Fiebranz
+author_email: s.fiebranz@shopware.com
+author_github: @CR0YD
+---
+# Administration
+* Added option `displayReturnAddress` in `sw-settings-document-detail/index.js` to toggle the display of the return address above the customer address in documents.
+___
+# Upgrade Information
+## Return address in documents
+The option `Display company` address in the `Company settings` section of the document configuration is now split into `Diplay return address` and `Display company address`.
```
Comment (ennasus4sun) [inline changelog/_unreleased/2025-08-12-added-return-address-display-option.md]:
```suggestion
The option `Display company` address in the `Company settings` section of the document configuration is now split into `Display return address` and `Display company address`.  
```

Comment (CR0YD) [reply changelog/_unreleased/2025-08-12-added-return-address-display-option.md]: Changed it.
