### PR TITLE
fix: correct promotion rule evaluation

### LINKED ISSUE #14555: "Promotion -> All -> Are None of" fails to match
### Shopware Version

6.7.6.2

### Affected area / extension

Platform(Default)

### Actual behaviour

A Rule "Promotion -> All -> Are None of -> (select any promotion)" should match if the selected promotion is not in the cart, and should not match if it is.
Create such a rule and make it the requirement for e.g. a shipping method.

Without the selected promotion in the cart, the rule will not match, therefore the shipping method will not be offered.
The same can be applied to cart rules for other promotions etc.

### Expected behaviour

If A is not in the cart, the rule should match, so the shipping method should be offered.

### How to reproduce

Also reproducable in 6.6.10.10.

### PR DESCRIPTION
**Pull request by Aliaaaam**
### 1. Why is this change necessary?
Promotion rules are evaluated incorrectly when checking whether a specific promotion is present in the cart. As a result, conditions that depend on the absence of a promotion do not behave as expected.

### 2. What does this change do, exactly?
It fixes the cart rule evaluation so that promotion-based conditions correctly match when the promotion is not in the cart and do not match when it is present.
Screenshot 2026-02-13 at 13 59 02
Screenshot 2026-02-13 at 13 55 58

### 3. Describe each step to reproduce the issue or behaviour.
1. Create a rule with condition: Promotion -> select a specific promotion.
2. Assign this rule to a shipping method (or another cart-dependent feature).
3. Add products to the cart without adding the selected promotion.
4. Observe that the rule does not match and the shipping method is not available.
5. Add the selected promotion and observe inconsistent matching behavior.

### 4. Please link to the relevant issues
- Fixes https://github.com/shopware/shopware/issues/14555

### 5. Checklist
- [x] I have written tests and verified that they fail without my change
- [ ] I have updated developer-facing release notes if this change is **relevant** for external developers:
  - Add a short entry to `RELEASE_INFO-6.<major>.md` under “Upcoming” for informational changes, including the consequences of the change and how it affects external developers.
  - Add an `UPGRADE` section in `UPGRADE-6.<next-major>.md` for breaking changes (what/why/impact/how to adapt).
  - See the [Documenting a Release Process](https://github.com/shopware/shopware/blob/trunk/delivery-process/documenting-a-release.md) for details.
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Core/Framework/Rule/Container/MatchAllLineItemsRule.php [hunk 1]
```diff
@@ -51,8 +51,9 @@ public function match(RuleScope $scope): bool
 
         $flatItems = $this->filterAndFlatten($lineItems);
 
+        // When there are no line items of this type, the rule still passes (e.g. "none of promotion" with an empty cart).
         if (\count($flatItems) === 0) {
-            return false;
+            return !empty($this->types);
```
Comment (mitelg) [inline src/Core/Framework/Rule/Container/MatchAllLineItemsRule.php]: please avoid the usage of `empty` and use explicit checks instead.

Comment (Aliaaaam) [reply src/Core/Framework/Rule/Container/MatchAllLineItemsRule.php]: Sure, fixed

**Review by mitelg — APPROVED** [review]

**Review by En0Ma1259 — APPROVED** [review]

**Review by cyl3x — APPROVED** [review]

**Comment by janobi** [comment]
Also needs to be backported to 6.6.x
