### PR TITLE
fix: improve RedisInvalidatorStorage

### LINKED ISSUE #13647: Delayed invalidation gets stuck on redis OOM
### Shopware Version

6.6.10.6

### Affected area / extension

Platform(Default)

### Actual behaviour

When the redis instance handling delayed invalidation gets into an OOM state, delayed invalidation no longer works and cannot get itself into a working state. This has devastating consequences, because basic shopware functionality (e.g. orders) fails to function. This is because redis developers decided on redis 5 to no longer execute `MULTI` transactions in OOM states.

https://github.com/redis/redis/pull/5454

### Expected behaviour

Delayed invalidation must be implemented in a way that doesn't deadlock the shop in case of delayed invalidation set overflow. As the amount of invalidations is not capped on shopwares side, and is not really predictable from the API side, shopware must handle the case where not enough resources are available to store new xkeys. In my opinion, this can be done by either
1. clearing the cache sooner in those circumstances
2. switching into a mode where delayed invalidation is disabled as long as necessary
3. dropping new xkey invalidation requests
4. failing but changing the code so that delayed invalidation can restore itself with the next clear cycle by executing the code inside loadAndDelete() without the `MULTI` transaction

### How to reproduce

Configure delayed invalidation, set a low maxmemory limit, invalidate xkeys so that they are inserted into the redis instance's `invalidations` set, and observe that orders no longer work when maxmemory OOM is reached and that shopware cannot itself resolve that issue on next cache clear, necessitating admin intervention.

### PR DESCRIPTION
**Pull request by BrocksiNet**
### 1. Why is this change necessary?
It adds some Fallback (`loadAndDeleteSequentialFallback`) when MULTI is OOM.

### 2. What does this change do, exactly?
Modified RedisInvalidatorStorage to handle Redis transaction failures (such as those caused by OOM conditions) by falling back to sequential sMembers and del commands. This ensures that cache invalidation tags can still be processed even if the atomic transaction is rejected.

### 3. Describe each step to reproduce the issue or behaviour.
See issue.

### 4. Please link to the relevant issues (if any).
- closes #13647

### 5. Checklist

- [X] I have written tests and verified that they fail without my change
- [ ] I have updated developer-facing release notes if this change is **relevant** for external developers:
  - Add a short entry to `RELEASE_INFO-6.<major>.md` under “Upcoming” for informational changes, including the consequences of the change and how it affects external developers.
  - Add an `UPGRADE` section in `UPGRADE-6.<next-major>.md` for breaking changes (what/why/impact/how to adapt).
  - See the [Release Notes & Changelog Process](https://github.com/shopware/shopware/blob/trunk/adr/2025-10-28-changelog-release-info-process.md) for details.
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Core/Framework/Adapter/Cache/InvalidatorStorage/RedisInvalidatorStorage.php [hunk 1]
```diff
@@ -27,14 +27,27 @@ public function store(array $tags): void
...
+            if ($values !== false) {
+                return $values[0];
+            }
+        } catch (\Throwable) {
+            // If the transaction fails (e.g. OOM), we fall back to sequential execution
+        }
+
+        // This breaks atomicity but ensures the queue is drained
+        /** @var list<string> $tags */
+        $tags = $this->redis->sMembers(self::KEY);
```
Comment (mitelg) [inline src/Core/Framework/Adapter/Cache/InvalidatorStorage/RedisInvalidatorStorage.php]: should we batch the keys here?

Comment (shyim) [inline src/Core/Framework/Adapter/Cache/InvalidatorStorage/RedisInvalidatorStorage.php]: we should maybe inject Logger and log a warning

File: src/Core/Framework/Adapter/Cache/InvalidatorStorage/RedisInvalidatorStorage.php
Comment (shyim) [inline src/Core/Framework/Adapter/Cache/InvalidatorStorage/RedisInvalidatorStorage.php:9]: what about wrapping the calls to this invalidators in a try catch, and directly invalidate if storing fails + log?

Comment (BrocksiNet) [reply src/Core/Framework/Adapter/Cache/InvalidatorStorage/RedisInvalidatorStorage.php:9]: you mean inside `src/Core/Framework/Adapter/Cache/CacheInvalidator.php` ?

File: src/Core/Framework/Adapter/Cache/InvalidatorStorage/RedisInvalidatorStorage.php (hunk 1 above)
Comment (BrocksiNet) [reply src/Core/Framework/Adapter/Cache/InvalidatorStorage/RedisInvalidatorStorage.php]: That would increase complexity, and basically, we are in a fallback scenario. 
So, I would say no, but yes, we should add a logger.

File: src/Core/Framework/Adapter/Cache/InvalidatorStorage/RedisInvalidatorStorage.php
Comment (shyim) [reply src/Core/Framework/Adapter/Cache/InvalidatorStorage/RedisInvalidatorStorage.php:9]: yes

File: src/Core/Framework/Adapter/Cache/InvalidatorStorage/RedisInvalidatorStorage.php (hunk 1 above)
Comment (mitelg) [reply src/Core/Framework/Adapter/Cache/InvalidatorStorage/RedisInvalidatorStorage.php]: I just wondered, if that could also cause OOM (again), if we send many many keys :man_shrugging:

File: src/Core/Framework/Adapter/Cache/InvalidatorStorage/RedisInvalidatorStorage.php [hunk 2]
```diff
@@ -27,14 +29,59 @@ public function store(array $tags): void
...
+     */
+    private function loadAndDeleteSequentialFallback(): array
+    {
+        // This breaks atomicity but ensures the queue is drained
+        try {
+            /** @var list<string> $tags */
+            $tags = $this->redis->sMembers(self::KEY);
+            $this->redis->del(self::KEY);
+        } catch (\Throwable $e) {
+            $this->logger->error('Could not load and delete tags from Redis. Error: ' . $e->getMessage());
```
Comment (mitelg) [inline src/Core/Framework/Adapter/Cache/InvalidatorStorage/RedisInvalidatorStorage.php]: we should add to the message, that this is already the fallback

File: src/Core/Framework/Adapter/Cache/InvalidatorStorage/RedisInvalidatorStorage.php [hunk 3]
```diff
@@ -27,14 +29,65 @@ public function store(array $tags): void
...
+     * @return list<string>
+     */
+    private function loadAndDeleteSequentialFallback(): array
+    {
+        // This breaks atomicity but ensures the queue is drained
+        try {
+            $tags = [];
+
+            $chunk = $this->redis->sPop(self::KEY, 10000);
+            while (\is_array($chunk) && !empty($chunk)) {
```
Comment (mitelg) [inline src/Core/Framework/Adapter/Cache/InvalidatorStorage/RedisInvalidatorStorage.php:79]: where do you delete the tags now? :thinking:

Comment (BrocksiNet) [reply src/Core/Framework/Adapter/Cache/InvalidatorStorage/RedisInvalidatorStorage.php:79]: https://redis.io/docs/latest/commands/spop/

File: src/Core/Framework/Adapter/Cache/InvalidatorStorage/RedisInvalidatorStorage.php
Comment (BrocksiNet) [reply src/Core/Framework/Adapter/Cache/InvalidatorStorage/RedisInvalidatorStorage.php:9]: did that now here:
https://github.com/shopware/shopware/pull/13669/files#diff-ae481c26f2431679c742b89d5c458b8ba8762f864508c65fa13f5e5f3c30ad38R53

File: src/Core/Framework/Adapter/Cache/InvalidatorStorage/RedisInvalidatorStorage.php [hunk 4]
```diff
@@ -27,14 +29,65 @@ public function store(array $tags): void
...
+                }
+                $chunk = $this->redis->sPop(self::KEY, 10000);
+            }
+        } catch (\Throwable $e) {
+            $this->logger->error('Sequential fallback: Could not load and delete tags from Redis. Error: ' . $e->getMessage());
+
+            throw $e;
+        }
+
+        return $tags;
```
Comment (mitelg) [inline src/Core/Framework/Adapter/Cache/InvalidatorStorage/RedisInvalidatorStorage.php:91]:
```suggestion
                $tags[] = $chunk;
                $chunk = $this->redis->sPop(self::KEY, 10000);
            }
        } catch (\Throwable $e) {
            $this->logger->error('Sequential fallback: Could not load and delete tags from Redis. Error: ' . $e->getMessage());

            throw $e;
        }

        return array_values(array_merge([], ...$tags));
```

this is probably a bit faster, than iterating in every loop 10k pieces

Comment (mitelg) [reply src/Core/Framework/Adapter/Cache/InvalidatorStorage/RedisInvalidatorStorage.php:91]: not tested! pseudo code! but you get the idea :wink:

File: src/Core/Framework/Adapter/Cache/InvalidatorStorage/RedisInvalidatorStorage.php [hunk 5]
```diff
@@ -27,14 +29,63 @@ public function store(array $tags): void
...
+            /** @var array{0: list<string>, 1: mixed}|false $values */
+            $values = $this
+                ->redis
+                ->multi()
+                ->sMembers(self::KEY)
+                ->del(self::KEY)
+                ->exec();
+
+            if ($values !== false) {
+                return $values[0];
```
Comment (keulinho) [inline src/Core/Framework/Adapter/Cache/InvalidatorStorage/RedisInvalidatorStorage.php]: what if it is empty? Will this return an empty array here?

I would prefer to put the edge case that values is false (foer whatever reason) up in here in the if, and default case (we got a result) in the main execution branch

File: src/Core/Framework/Adapter/Cache/InvalidatorStorage/RedisInvalidatorStorage.php [hunk 6]
```diff
@@ -27,14 +29,63 @@ public function store(array $tags): void
...
+                $tags[] = $chunk;
+                $chunk = $this->redis->sPop(self::KEY, 10000);
+            }
+        } catch (\Throwable $e) {
+            $this->logger->error('Sequential fallback: Could not load and delete tags from Redis. Error: ' . $e->getMessage());
+
+            throw $e;
+        }
+
+        return array_values(array_merge([], ...$tags));
```
Comment (keulinho) [inline src/Core/Framework/Adapter/Cache/InvalidatorStorage/RedisInvalidatorStorage.php]: Whats the reason for the array merge? Can't we already merge above when we iterate through the chuncks?

Comment (BrocksiNet) [reply src/Core/Framework/Adapter/Cache/InvalidatorStorage/RedisInvalidatorStorage.php]: Was a suggestion from Telgi, but when I think about it, the solution with the "dump" foreach loop looks like the most effective (in the while loop):

```
foreach ($chunk as $tag) {
    $tags[] = (string) $tag;
}
```

File: src/Core/Framework/Adapter/Cache/InvalidatorStorage/RedisInvalidatorStorage.php (hunk 5 above)
Comment (BrocksiNet) [reply src/Core/Framework/Adapter/Cache/InvalidatorStorage/RedisInvalidatorStorage.php]: Yes, if the set is empty, sMembers returns an empty array [], so $values[0] would be [], which is correct.

You mean like this about the edge case?

```php
/**
     * @return list<string>|null
     */
    private function loadAndDeleteMultiTransaction(): ?array
    {
        try {
            /** @var array{0: list<string>, 1: mixed}|false $values */
            $values = $this
                ->redis
                ->multi()
                ->sMembers(self::KEY)
                ->del(self::KEY)
                ->exec();

            if ($values === false) {
                $this->logger->warning('Redis transaction failed (exec returned false), falling back to sequential execution.');

                return null;
            }

            return $values[0];
        } catch (\Throwable $e) {
            $this->logger->warning('Redis transaction failed, falling back to sequential execution. Error: ' . $e->getMessage());

            return null;
        }
    }
```

File: src/Core/Framework/Adapter/Cache/InvalidatorStorage/RedisInvalidatorStorage.php (hunk 6 above)
Comment (mitelg) [reply src/Core/Framework/Adapter/Cache/InvalidatorStorage/RedisInvalidatorStorage.php]: array_merge should not be used in loops due to performance reasons :grin:

File: src/Core/Framework/Adapter/Cache/InvalidatorStorage/RedisInvalidatorStorage.php (hunk 5 above)
Comment (mitelg) [reply src/Core/Framework/Adapter/Cache/InvalidatorStorage/RedisInvalidatorStorage.php]: behold! `$values[0]` is `null` if `$values` is an empty array (`[]`)!

**Comment by BrocksiNet** [comment]
Some local test results, FYI:

image

_Tested with the foreach implementation instead of array_merge._

**Review by mitelg — APPROVED** [review]

**Review by keulinho — APPROVED** [review]
