### PR TITLE
fix: sales channel specific static system config

### LINKED ISSUE #13792: system_config.yaml configuration for different sales channels not working
### Shopware Version

6.6.10.8

### Affected area / extension

Platform(Default)

### Actual behaviour

We are using system_config.yaml for changing config values on our staging environments. Today, we noticed that changing is working only for the default option. In the [documentation](https://developer.shopware.com/docs/guides/hosting/configurations/shopware/static-system-config.html#usage), there is info that we can change values by salesChannelId, but it is not working. We found the [PR](https://github.com/shopware/shopware/commit/c2858c770b05c72f0894969e59a8f12968408a6c), but even when we roll back this change, it is still not working.

### Expected behaviour

Like it is described in the official [documentation](https://developer.shopware.com/docs/guides/hosting/configurations/shopware/static-system-config.html#usage). We are able to override system_config values per sales channel.

### How to reproduce

Create the system_config.yaml file and try to override system_config values differently per sales channel.

### PR DESCRIPTION
**Pull request by dneustadt**
### 1. Why is this change necessary?
https://developer.shopware.com/docs/guides/hosting/configurations/shopware/static-system-config.html#usage states that for the static system config using *.yaml files, the sales channel ID can be used to set system config specifically for the given sales channel. In fact only the `default` key can be used.

### 2. What does this change do, exactly?
Allows either the use of `default` or a valid UUID as key for the collection of system config values.

### 3. Describe each step to reproduce the issue or behaviour.
* Create a `*.yaml` file at `config/packages` with the content
```yaml
shopware:
    system_config:
        default:
            core.listing.allowBuyInListing: true
        # Disable it for the specific sales channel
        {{salesChannelId}}:
            core.listing.allowBuyInListing: false
```
* Replace {{salesChannelId}} with an actual id of a sales channel

### 4. Please link to the relevant issues (if any).
https://github.com/shopware/shopware/issues/13792

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [ ] I have updated developer-facing release notes if this change is **relevant** for external developers:
  - Add a short entry to `RELEASE_INFO-6.<major>.md` under “Upcoming” for informational changes, including the consequences of the change and how it affects external developers.
  - Add an `UPGRADE` section in `UPGRADE-6.<next-major>.md` for breaking changes (what/why/impact/how to adapt).
  - See the [Documenting a Release Process](https://github.com/shopware/shopware/blob/trunk/delivery-process/documenting-a-release.md) for details.
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfilled them

### CODE REVIEW

**Review by mitelg — APPROVED** [review]

**Review by MartinKrzykawski — APPROVED** [review]

File: src/Core/Framework/DependencyInjection/Configuration.php [hunk 1]
```diff
@@ -948,8 +949,18 @@ private function createSystemConfigNode(): ArrayNodeDefinition
 
         $rootNode = $treeBuilder->getRootNode();
         $rootNode
-            ->children()
-                ->arrayNode('default')->scalarPrototype()->end()
+            ->arrayPrototype()->scalarPrototype()->end()
```
Comment (mitelg) [inline src/Core/Framework/DependencyInjection/Configuration.php:971]: does it make sense to keep `default` as default value? 🤔

Comment (dneustadt) [reply src/Core/Framework/DependencyInjection/Configuration.php:971]: You mean from a naming or definition point of view?
AFAIK mixing fixed children and prototypes from the point of definition doesn't work technically. The structure would have to be changed and that would be a breaking change in both regards to the existing docs and current behavior. Same would go for a pure naming change.

Comment (mitelg) [reply src/Core/Framework/DependencyInjection/Configuration.php:971]: before we had an arrayNode with the name `default`, now it is just an array missing the name. not sure, what impact that has or if it doesn't matter. 

I guess that is also the reason you need to adjust the one test case

Comment (dneustadt) [reply src/Core/Framework/DependencyInjection/Configuration.php:971]: Yes, exactly, had to change `static::assertInstanceOf(ArrayNodeDefinition::class, $nodes['default'])` to `static::assertInstanceOf(ArrayNodeDefinition::class, $nodes[''])` because empty string in that context essentially mean every possible key.

But as mentioned you can't have both, some fixed keys and then in addition any number of keys. It has to be either all fixed keys or all dynamic.

The alternative would be to keep the one static key and then add an array of dynamic sales channel ids:
```yaml
shopware:
  system_config:
    default:
      core.listing.allowBuyInListing: true
    sales_channels:
      0188da12724970b9b4a708298259b171:
        core.listing.allowBuyInListing: false
```

However that would be different from how the docs describe it, which was the whole point of the PR to make it work like that 🙈 Also would probably a bit more work to then properly override the configs. For now this was enough to make it work as expected.

Comment (dneustadt) [reply src/Core/Framework/DependencyInjection/Configuration.php:971]: @shyim @mitelg how to proceed here?

Comment (mitelg) [reply src/Core/Framework/DependencyInjection/Configuration.php:971]: for me it is all good, just wanted to be that noted down :slightly_smiling_face:
