### PR TITLE
fix: deserialization of MediaThumbnailEntity

### LINKED ISSUE #10040: Unable to Log In After Migration When Cart Contains Products with Images
### Shopware Version

Cloud

### Affected area / extension

Platform(Default)

### Actual behaviour

After the migration from [20250506-1136-brattain](https://jarvis.swstage.store/version/20250506-1136-brattain) to [20250528-1113-benz](https://jarvis.swstage.store/version/20250528-1113-benz), I am unable to log in using my credentials as a business partner / customer. This was working prior to the migration, so I suspect there may be an issue related to the user authentication process. 
Env: https://yt-66-67.swstage.store/

Image

### Expected behaviour

Successful login with correct credentials or continue to use your already logged-in session without any issue.

### How to reproduce

1. Refresh the storefront after migration
2. Enter valid credentials (previously working before migration).
3. Click "Login".

Or if you already have a session, just refresh the page.

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by mstegmeyer**
### 1. Why is this change necessary?
Carts that have been serialized in 6.6 may not be able to be deserialized, because this field had `null` set as its value, but the new strong type does not support that.

### 2. What does this change do, exactly?
Change the property type to nullable.

### 3. Describe each step to reproduce the issue or behaviour.
- Login as a customer with a cart with thumbnails
- Upgrade to 6.7
- Login again.

### 4. Please link to the relevant issues (if any).
fixes #10040 

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfill them.

### CODE REVIEW

File: src/Core/Content/Media/Aggregate/MediaThumbnail/MediaThumbnailEntity.php [hunk 1]
```diff
@@ -48,7 +48,7 @@ public function setHeight(int $height): void
 
     public function getUrl(): string
```
Comment (mitelg) [inline src/Core/Content/Media/Aggregate/MediaThumbnail/MediaThumbnailEntity.php:52]: recently we did it like this: https://github.com/shopware/shopware/blob/trunk/src/Core/System/SalesChannel/Aggregate/SalesChannelType/SalesChannelTypeEntity.php#L79-L89

Comment (mstegmeyer) [reply src/Core/Content/Media/Aggregate/MediaThumbnail/MediaThumbnailEntity.php:52]: @mitelg I can do it this way, but in the example, you just broke the setter to take a nullable parameter. Should we also do that or deprecate the setter as well?

Comment (mitelg) [reply src/Core/Content/Media/Aggregate/MediaThumbnail/MediaThumbnailEntity.php:52]: that is debatable :see_no_evil: :grin: 

one could argue, that a setter should always set a valid value and not `null` if used, on the other hand, it might be necessary to exactly do that, to reset the property :man_shrugging:

**Review by mitelg — APPROVED** [review]

**Review by Bird87ZA — APPROVED** [review]

**Review by MartinKrzykawski — APPROVED** [review]

**Review by cyl3x — APPROVED** [review]

**Review by lernhart — APPROVED** [review]
