### PR TITLE
fix: unable to fall back to parent language on product entity

### LINKED ISSUE #9909: Unable to fall back to parent language on product entity
### Shopware Version

6.6.10.4 | 6.7.0.0-rc4

### Affected area / extension

Platform(Default)

### Actual behaviour

In a default Shopware 6 installation with English as the system language and any additional language that inherits from it, removing a translation of a product name and saving the product results in an error. Specifically, when the translated name field is cleared and saved, the system displays a validation error stating that the "name" field cannot be empty.

This happens because the EntityValidationService (used in the onSave() function of sw-product-detail/index.js) only checks whether the field is marked as required and does not take language inheritance or fallback values into account.

### Expected behaviour

Expected Behaviour
If a translated field (such as the product name in a language that inherits from the system language) is empty and a fallback value exists in the system language (e.g., English), saving should succeed. The product should use the system language value as the fallback without triggering a validation error.
It works this way for any other entity, but because the EntityValidationService is only implemented for products it fails there.

### How to reproduce

How to Reproduce

1. Start with a default Shopware 6 installation.
2. Set the system language to English.
3. Add a new language that inherits from English.
4. Create a new product and set the name in English.
5. Switch to the inherited language and add a translated name. Save the product.
6. Switch to the inherited language again, clear the translated name field (leave it empty), and attempt to save.

Result: A validation error appears stating that the name field cannot be empty.
Expected: The product should save successfully, using the system language name as the fallback.

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by nguyenytran**
This pull request introduces a fix for the issue where product entities were unable to fall back to the parent language, along with enhancements to the entity validation process. The most significant changes include adding support for ignoring certain fields during validation, implementing language inheritance handling for product entities, and updating the relevant tests to ensure correctness.

### Enhancements to Entity Validation:

* Modified the `validate` method in `EntityValidationService` to accept an `ignoreFields` parameter, allowing specific fields to be excluded from validation. Updated the logic to filter out ignored fields when checking for required fields. (`src/Administration/Resources/app/administration/src/app/service/entity-validation.service.ts`, [[1]](diffhunk://#diff-4f9b310423bdcfaa4e3e82e968697dfd80abacbcb0fcfc0175363965753a96f7L71-R75) [[2]](diffhunk://#diff-4f9b310423bdcfaa4e3e82e968697dfd80abacbcb0fcfc0175363965753a96f7L81-R96)

### Language Inheritance Handling for Product Entities:

* Added a new method `ignoreFieldsValidate` in the `sw-product-detail` component to dynamically determine which fields to ignore during validation based on language inheritance. (`src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-detail/index.js`, [src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-detail/index.jsR1244-R1265](diffhunk://#diff-e2d623f2b3caa0af769855ca06293d72a1822a8fbdff1fac4dd5ff32adb65877R1244-R1265))
* Updated the `onSave` method to use the `ignoreFieldsValidate` method when calling the `validate` method of `EntityValidationService`. (`src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-detail/index.js`, [src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-detail/index.jsL891-R901](diffhunk://#diff-e2d623f2b3caa0af769855ca06293d72a1822a8fbdff1fac4dd5ff32adb65877L891-R901))
* Introduced a `loadLanguage` method to handle language inheritance and ensure proper context when switching languages. (`src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-detail/index.js`, [src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-detail/index.jsR1244-R1265](diffhunk://#diff-e2d623f2b3caa0af769855ca06293d72a1822a8fbdff1fac4dd5ff32adb65877R1244-R1265))

### Test Coverage:

* Added unit tests to verify the behavior of `ignoreFieldsValidate` for both inherited and non-inherited languages. (`src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-detail/sw-product-detail.spec.js`, [src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-detail/sw-product-detail.spec.jsR548-R603](diffhunk://#diff-6e74a5057b0cc8999f5567e415d1a83a79135cc6f740bdcad83563825f127997R548-R603))
* Added a test case to ensure validation succeeds when ignored fields are excluded. (`src/Administration/Resources/app/administration/src/app/service/entity-validation.service.spec.js`, [src/Administration/Resources/app/administration/src/app/service/entity-validation.service.spec.jsR181-R204](diffhunk://#diff-10f27c35135bf6cbf921c7a8f47fa52f021961654e45a5c4612d35cf758ce232R181-R204))

### CODE REVIEW

File: src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-detail/index.js [hunk 1]
```diff
@@ -7,8 +7,9 @@ import template from './sw-product-detail.html.twig';
 import errorConfiguration from './error.cfg.json';
 import './sw-product-detail.scss';
 import '../../page/sw-product-detail/store';
+import { required } from '../../../../core/service/validation.service';
```
Comment (sydinh) [inline src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-detail/index.js]: Where does this function get used?

File: src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-detail/index.js [hunk 2]
```diff
@@ -1231,5 +1234,33 @@ export default {
...
+                return;
+            }
+
+            if (!this.parentProduct || !this.parentProduct.id) {
+                return;
+            }
+
+            const ignoreFields = ['createAt'];
+
+            // Get required fields from entity validation service
```
Comment (sydinh) [inline src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-detail/index.js]: I would remove this code comment, it's already clear.

File: src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-detail/index.js [hunk 3]
```diff
@@ -1231,5 +1234,33 @@ export default {
...
+            const requiredFields = Object.keys(EntityDefinition.getRequiredFields(this.product.getEntityName()));
+
+            // Fallback to parent product values for empty required fields
```
Comment (sydinh) [inline src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-detail/index.js]: This too.

File: src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-detail/index.js [hunk 4]
```diff
@@ -1231,5 +1234,33 @@ export default {
...
+            requiredFields.forEach((field) => {
+                if (ignoreFields.indexOf(field) !== -1) {
```
Comment (sydinh) [inline src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-detail/index.js]:
```ts
ignoreFields.includes(field)
```

**Review by sydinh — CHANGES_REQUESTED** [review]

**Review by sydinh — APPROVED** [review]
LGTM overall 👍🏻

**Review by nguyenquocdaile — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-detail/index.js [hunk 5]
```diff
@@ -1231,5 +1233,29 @@ export default {
...
+        fallbackToParentProduct() {
+            if (!this.product.parentId) {
+                return;
+            }
+
+            if (!this.parentProduct || !this.parentProduct.id) {
+                return;
+            }
+
+            const ignoreFields = ['createAt'];
```
Comment (vienthuong) [inline src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-detail/index.js]:
```suggestion
            const ignoreFields = ['createdAt'];
```

**Comment by matthias-nijland** [comment]
Wouldn't this change also overwrite non-inherited, required fields such as stock?
Seems to me the main issue isn't with the onSave of the product detail page but with the validationService.

File:
src/Administration/Resources/app/administration/src/app/service/entity-validation.service.ts

        // check for required fields
        const requiredFields = definition.getRequiredFields() as Record<string, never>;
        errors.push(...this.getRequiredErrors(entity, requiredFields));

        // run custom validator
        if (customValidator !== undefined) {
            errors = customValidator(errors, entity, definition);
        }

        // report errors
        // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
        this.errorResolver.handleWriteErrors([{ entity, changes }], { errors });
        return errors.length < 1;

If you add an inhertance field check and add a parent value to an inherited field BEFORE checking the required fields, this validation service can be re-used for more entities.

**Comment by nguyenytran** [comment]
> Wouldn't this change also overwrite non-inherited, required fields such as stock? Seems to me the main issue isn't with the onSave of the product detail page but with the validationService.
> 
> File: src/Administration/Resources/app/administration/src/app/service/entity-validation.service.ts
> 
> ```
>     // check for required fields
>     const requiredFields = definition.getRequiredFields() as Record<string, never>;
>     errors.push(...this.getRequiredErrors(entity, requiredFields));
> 
>     // run custom validator
>     if (customValidator !== undefined) {
>         errors = customValidator(errors, entity, definition);
>     }
> 
>     // report errors
>     // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
>     this.errorResolver.handleWriteErrors([{ entity, changes }], { errors });
>     return errors.length < 1;
> ```
> 
> If you add an inhertance field check and add a parent value to an inherited field BEFORE checking the required fields, this validation service can be re-used for more entities.

Hi @matthias-nijland Thanks for suggestions, I just updated the code can you take a look

**Comment by matthias-nijland** [comment]
:+1:  Looks good

File: src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-detail/index.js [hunk 6]
```diff
@@ -1231,5 +1241,27 @@ export default {
                 });
             });
         },
+
+        ignoreFieldsValidate() {
```
Comment (vienthuong) [inline src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-detail/index.js]:
```suggestion
        ignoreFieldsValidation() {
```

Comment (vienthuong) [reply src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-detail/index.js]: computed please

File: src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-detail/index.js [hunk 7]
```diff
@@ -1231,5 +1241,27 @@ export default {
...
+            if (!this.language?.parentId) {
+                return [];
+            }
+
+            const ignoreFields = ['createdAt'];
```
Comment (vienthuong) [inline src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-detail/index.js]: EntityDefinition.getTranslatedFields(this.product.getEntityName());

**Review by vienthuong — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-detail/index.js [hunk 8]
```diff
@@ -385,6 +385,36 @@ export default {
...
+
+        translateFields() {
+            if (!this.product) {
+                return null;
+            }
+
+            return Object.keys(EntityDefinition.getTranslatedFields(this.product.getEntityName()));
+        },
+
+        ignoreFieldsValidation() {
```
Comment (vienthuong) [inline src/Administration/Resources/app/administration/src/module/sw-product/page/sw-product-detail/index.js:405]: could be helpful to put a comment that translated fields of children language could inherited values from parent language

**Review by jleifeld — APPROVED** [review]
