### PR TITLE
fix: mediaThumbnailSizeId not null in MediaThumbnailEntity

### LINKED ISSUE #11632: Thumbnails not generated
### Shopware Version

trunk

### Affected area / extension

Platform(Default)

### Actual behaviour

no thumbnails generated.

just trunk fails:
https://github.com/FriendsOfShopware/FroshPlatformThumbnailProcessor/actions/runs/16626823401/job/47045458713

see test: https://github.com/FriendsOfShopware/FroshPlatformThumbnailProcessor/blob/e8e97a3897ca0ea101e40ae96239a05627781ad2/tests/integration/MediaUrlTest.php#L98

How should we create the thumbnails [after this change](https://github.com/shopware/shopware/commit/de8605468da3edb574d9b2e2129ae2920865f79b)?

### Expected behaviour

should have thumbnails generated

### How to reproduce

(see test)
 
- use NamedMimePngEtxPngWithFolder of mediaFixtures
- set folder
- generate thumbnails
- runWorker
- have no thumbnails

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by gecolay**
### 1. Why is this change necessary?
- See https://github.com/shopware/shopware/commit/de8605468da3edb574d9b2e2129ae2920865f79b#r163148399
- See https://github.com/shopware/shopware/pull/11417
- https://github.com/shopware/shopware/issues/11632

### 2. What does this change do, exactly?
* Changed `Shopware\Core\Content\Media\Aggregate\MediaThumbnail\MediaThumbnailDefinition` to allow a null value for `mediaThumbnailSizeId`
* Changed `Shopware\Core\Content\Media\Aggregate\MediaThumbnail\MediaThumbnailEntity` to allow a null value for `mediaThumbnailSizeId`

### 3. Describe each step to reproduce the issue or behaviour.
- https://github.com/shopware/shopware/commit/de8605468da3edb574d9b2e2129ae2920865f79b#r163148399

### 4. Please link to the relevant issues (if any).
- https://github.com/shopware/shopware/commit/de8605468da3edb574d9b2e2129ae2920865f79b#r163148399
- https://github.com/shopware/shopware/pull/11417
- Fixes #11632

### 5. Checklist

- [X] I have written tests and verified that they fail without my change
- [X] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [X] I have written or adjusted the documentation according to my changes
- [X] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I have read the contribution requirements and fulfilled them

### CODE REVIEW

**Comment by gecolay** [comment]
@shyim @mitelg @tinect This should fix the issues

File: src/Core/Migration/V6_8/Migration1753945220ModifyMediaThumbnailSizeIdInMediaThumbnail.php [hunk 1]
```diff
@@ -0,0 +1,104 @@
...
+        $this->migrateMediaThumbnailRows($connection);
+
+        if ($this->indexExists($connection, 'media_thumbnail', 'fk.media_thumbnail.media_thumbnail_size_id')) {
+            $connection->executeStatement('
+                ALTER TABLE `media_thumbnail`
+                DROP FOREIGN KEY `fk.media_thumbnail.media_thumbnail_size_id`
+            ');
+        }
+
+        $connection->executeStatement('
```
Comment (mitelg) [inline src/Core/Migration/V6_8/Migration1753945220ModifyMediaThumbnailSizeIdInMediaThumbnail.php]: you can do that in the original migration, but the whole point is, that we cannot set the column to `NOT NULL` in the `update` method. it needs to be done in the destructive method. that is what is it for. adding it to 6.8 is also not correct, as this will lead to other problems

File: src/Core/Content/Media/Aggregate/MediaThumbnail/MediaThumbnailEntity.php [hunk 2]
```diff
@@ -114,6 +121,12 @@ public function setMedia(MediaEntity $media): void
 
     public function getMediaThumbnailSizeId(): string
     {
+        if (!isset($this->mediaThumbnailSizeId)) {
```
Comment (mitelg) [inline src/Core/Content/Media/Aggregate/MediaThumbnail/MediaThumbnailEntity.php:127]: we should not return an empty string. 

add `null` to the return type and add a deprecation, that is will not return null anymore with 6.8. 

as you introduced this method just yesterday we do need to care about the "break"

File: src/Core/Content/Media/Thumbnail/ThumbnailService.php [hunk 3]
```diff
@@ -157,8 +158,14 @@ public function updateThumbnails(MediaEntity $media, Context $context, bool $str
...
         foreach ($toBeCreatedSizes as $thumbnailSize) {
             foreach ($toBeDeletedThumbnails as $thumbnail) {
-                if ($thumbnailSize->getId() !== $thumbnail->getMediaThumbnailSizeId()) {
-                    continue;
+                if (Feature::isActive('v6.8.0.0')) {
+                    if ($thumbnailSize->getId() !== $thumbnail->getMediaThumbnailSizeId()) {
+                        continue;
+                    }
+                } else {
+                    if ($thumbnail->getMediaThumbnailSizeId() && $thumbnailSize->getId() !== $thumbnail->getMediaThumbnailSizeId()) {
```
Comment (mitelg) [inline src/Core/Content/Media/Thumbnail/ThumbnailService.php:166]: shouldn't we do the old check in that case, to make sure it is working correctly? :thinking:

Comment (gecolay) [reply src/Core/Content/Media/Thumbnail/ThumbnailService.php:166]: The old check will not work, as the thumbnails will now have their correct width & height saved to the database. This is explained in the original PR

File: src/Core/Content/Media/Aggregate/MediaThumbnail/MediaThumbnailEntity.php (hunk 2 above)
Comment (gecolay) [reply src/Core/Content/Media/Aggregate/MediaThumbnail/MediaThumbnailEntity.php:127]: Changed.

File: src/Core/Migration/V6_8/Migration1753945220ModifyMediaThumbnailSizeIdInMediaThumbnail.php (hunk 1 above)
Comment (gecolay) [reply src/Core/Migration/V6_8/Migration1753945220ModifyMediaThumbnailSizeIdInMediaThumbnail.php]: Moved the code to the updateDestructive method

File: src/Core/Content/Media/Thumbnail/ThumbnailService.php (hunk 3 above)
Comment (mitelg) [reply src/Core/Content/Media/Thumbnail/ThumbnailService.php:166]: do we then even need a feature flag condition here? `$thumbnail->getMediaThumbnailSizeId()` returns an empty string if not set (or `null` if you consider my other comments` and then it will also never be the same than `$thumbnailSize->getId()`

**Review by mitelg — CHANGES_REQUESTED** [review]

File: src/Core/Content/Media/Thumbnail/ThumbnailService.php (hunk 3 above)
Comment (gecolay) [reply src/Core/Content/Media/Thumbnail/ThumbnailService.php:166]: Not necessarily. After the 6.8 update, it would just be an unnecessary check.

Comment (gecolay) [reply src/Core/Content/Media/Thumbnail/ThumbnailService.php:166]: After the 6.8 update we no longer need the check.
Before the update we need to skip the check and always re-generate the thumbnail if the size id is missing

Comment (mitelg) [reply src/Core/Content/Media/Thumbnail/ThumbnailService.php:166]: ah yes, I see :+1:

**Review by mitelg — APPROVED** [review]

**Review by marcelbrode — APPROVED** [review]

File: src/Core/Content/Media/Aggregate/MediaThumbnail/MediaThumbnailDefinition.php [hunk 4]
```diff
@@ -55,8 +55,10 @@ protected function defineFields(): FieldCollection
         return new FieldCollection([
             (new IdField('id', 'id'))->addFlags(new ApiAware(), new PrimaryKey(), new Required()),
 
-            (new FkField('media_id', 'mediaId', MediaDefinition::class))->addFlags(new ApiAware(), new Required()),
-            (new FkField('media_thumbnail_size_id', 'mediaThumbnailSizeId', MediaThumbnailSizeDefinition::class))->addFlags(new Required()),
+            /** @deprecated tag:v6.8.0 - Will be required */
+            (new FkField('media_id', 'mediaId', MediaDefinition::class))->addFlags(new ApiAware()),
```
Comment (dgrothaus-sw) [inline src/Core/Content/Media/Aggregate/MediaThumbnail/MediaThumbnailDefinition.php]: Why remove the requirement of the foreign key? How to match the thumbnail to a media file without FK?

File: src/Core/Content/Media/Aggregate/MediaThumbnail/MediaThumbnailEntity.php [hunk 5]
```diff
@@ -27,11 +27,14 @@ class MediaThumbnailEntity extends Entity
     /**
      * @deprecated tag:v6.8.0 - Will be non-nullable
      */
-    protected ?string $mediaId;
+    protected ?string $mediaId = null;
```
Comment (dgrothaus-sw) [inline src/Core/Content/Media/Aggregate/MediaThumbnail/MediaThumbnailEntity.php]: Please don't assign a default value here. The field is not intended to ever be null. There was a bug in 6.6 where this could be `null` in a very specific combination, but in general the class should always require the ID to be set and to throw Exceptions when not.

**Review by dgrothaus-sw — CHANGES_REQUESTED** [review]

**Comment by gecolay** [comment]
@dgrothaus-sw I reverted the changes of the media_id.

**Review by dgrothaus-sw — APPROVED** [review]

**Comment by mitelg** [comment]
thanks for your contribution @gecolay 👍🎉💙

**Comment by shyim** [comment]
image

```
11:24:18 INFO      [php] User Deprecated: Since shopware/core : $mediaThumbnailSizeId must not be null
[
  "exception" => ErrorException {
    #message: "User Deprecated: Since shopware/core : $mediaThumbnailSizeId must not be null"
    #code: 0
    #file: "./src/Core/Framework/Feature.php"
    #line: 255
    #severity: E_USER_DEPRECATED
    trace: {
      ./src/Core/Framework/Feature.php:255 {
        Shopware\Core\Framework\Feature::triggerDeprecationOrThrow(string $majorFlag, string $message): void^
        › 
        ›     trigger_deprecation('shopware/core', '', $message);
        › }
      }
      ./src/Core/Content/Media/Aggregate/MediaThumbnail/MediaThumbnailEntity.php:50 { …}
      ./src/Core/Framework/DataAbstractionLayer/Dbal/EntityHydrator.php:276 { …}
      ./src/Core/Framework/DataAbstractionLayer/Dbal/EntityHydrator.php:176 { …}
      ./src/Core/Framework/DataAbstractionLayer/Dbal/EntityHydrator.php:589 { …}
      ./src/Core/Framework/DataAbstractionLayer/Dbal/EntityHydrator.php:95 { …}
      ./src/Core/Framework/DataAbstractionLayer/Dbal/EntityReader.php:135 { …}
      ./src/Core/Framework/DataAbstractionLayer/Dbal/EntityReader.php:76 { …}
      ./src/Core/Framework/DataAbstractionLayer/EntityRepository.php:207 { …}
      ./src/Core/Framework/DataAbstractionLayer/EntityRepository.php:235 { …}
      ./src/Core/Framework/DataAbstractionLayer/EntityRepository.php:65 { …}
      ./src/Core/Content/Media/DataAbstractionLayer/MediaIndexer.php:101 { …}
      ./src/Core/Content/Media/Thumbnail/ThumbnailService.php:119 { …}
      ./src/Core/Content/Media/Message/GenerateThumbnailsHandler.php:50 { …}
      ./vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:152 { …}
      ./vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php:91 { …}
      ./vendor/symfony/messenger/Middleware/SendMessageMiddleware.php:71 { …}
      ./src/Core/Framework/Adapter/Messenger/Middleware/QueuedTimeMiddleware.php:23 { …}
      ./vendor/symfony/messenger/Middleware/DeduplicateMiddleware.php:28 { …}
      ./vendor/symfony/messenger/Middleware/FailedMessageProcessingMiddleware.php:34 { …}
      ./vendor/symfony/messenger/Middleware/DispatchAfterCurrentBusMiddleware.php:68 { …}
      ./vendor/symfony/messenger/Middleware/RejectRedeliveredMessageMiddleware.php:41 { …}
      ./vendor/symfony/messenger/Middleware/AddBusNameStampMiddleware.php:35 { …}
      ./vendor/symfony/messenger/Middleware/TraceableMiddleware.php:36 { …}
      ./src/Core/Framework/MessageQueue/Middleware/RoutingOverwriteMiddleware.php:28 { …}
      ./vendor/symfony/messenger/MessageBus.php:69 { …}
      ./vendor/symfony/messenger/TraceableMessageBus.php:42 { …}
      ./vendor/symfony/messenger/RoutableMessageBus.php:51 { …}
      ./vendor/symfony/messenger/Worker.php:170 { …}
      ./vendor/symfony/messenger/Worker.php:119 { …}
      ./vendor/symfony/messenger/Command/ConsumeMessagesCommand.php:260 { …}
      ./vendor/symfony/console/Command/Command.php:318 { …}
      ./vendor/symfony/console/Application.php:1092 { …}
      ./vendor/symfony/framework-bundle/Console/Application.php:123 { …}
      ./vendor/symfony/console/Application.php:341 { …}
      ./vendor/symfony/framework-bundle/Console/Application.php:77 { …}
      ./vendor/symfony/console/Application.php:192 { …}
      ./vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:49 { …}
      ./vendor/autoload_runtime.php:29 { …}
      ./bin/shopware:17 { …}

```


my terminal is full of deprecations I cannot read anything

**Comment by mitelg** [comment]
@shyim did you execute all migrations? :thinking:

**Comment by shyim** [comment]
```
./bin/console system:install --basic-setup --drop-database --create-database
./bin/console framework:demodata -eprod
./bin/console dal:refresh:index --use-queue
```

```
./bin/console messenger:consume async -vvv
```

log spam of doom

**Comment by gecolay** [comment]
@shyim I fixed the issue with the deprecated message in #11785
