### PR TITLE
fix: Optimize CleanupCorruptedMediaHandler

### LINKED ISSUE #14634: CleanupCorruptedMediaHandler deleting media referenced by path
### Shopware Version

6.7.5.0

### Affected area / extension

Platform(Default)

### Actual behaviour

The corresponding ScheduledTask is called once a day: https://github.com/shopware/shopware/blob/trunk/src/Core/Content/Media/ScheduledTask/CleanupCorruptedMediaHandler.php

This task deletes supposedly corrupt media entries (e.g., in case of failed upload).

For media that is created via the API endpoint POST /api/media (https://shopware.stoplight.io/docs/admin-api/c5267f85b987c-create-a-new-media-resources) no file size is added, cannot be provided or changed afterwards - neither via this endpoint, nor in the admin.

That way, valid media gets deleted which is not desired

### Expected behaviour

Media files that are not corrupt should not be deleted.
Media without filesize (filesize=null) but including a path should persist.

### How to reproduce

Add media with a path via API POST call including a path.

### LINKED ISSUE #14655: Batch CleanupCorruptedMediaTask to avoid OOM on large media tables
### Technical TODO

CleanupCorruptedMediaHandler currently calls searchIds() with no limit for fileSize = NULL . On shops with big corrupted media rows can lead to Out of memory

Possible solution:
Process media in batches of 500-1000

### PR DESCRIPTION
**Pull request by MartinKrzykawski**
fixes https://github.com/shopware/shopware/issues/14634
fixes https://github.com/shopware/shopware/issues/14655

### 1. Why is this change necessary?

  The current corrupted-media cleanup can delete valid media entries in real merchant setups, especially when media is registered from external/CDN sources via Admin API (no Shopware upload step, fileSize may stay
  NULL by design).
  At the same time, the cleanup must still remove genuinely broken placeholders from interrupted two-step uploads.
  This PR fixes that safety gap and improves cleanup scalability for large media tables.

  ### 2. What does this change do, exactly?

  - Refines corrupted-media detection so only stale, unfinished placeholders are targeted.
  - Uses safer conditions centered on upload state and storage path presence, plus a grace period:
      - uploadedAt IS NULL
      - path IS NULL
      - createdAt < now - gracePeriod
  - Keeps cleanup processing in batches with cursor-based iteration to avoid large memory usage and long-running full-table operations.
  - Uses correct ID cursor handling for binary UUID comparison in DAL range filtering.
  - Adds dedicated database indices for the queried fields used by cleanup to improve lookup and batching performance on large media datasets.
  - Adds/validates migration coverage and tests for the cleanup-related DB/index behavior and handler behavior.

  ### 3. Describe each step to reproduce the issue or behaviour.

  1. Create media entries via Admin API for externally hosted assets (CDN), set path, do not call Shopware upload endpoints, and leave upload-derived fields like fileSize unset.
  2. Let the scheduled corrupted-media cleanup run.
  3. Observe that with old logic, valid CDN media can be removed because it looked “incomplete” by fileSize-based heuristics.
  4. With this PR, those CDN entries are preserved (because path is set), while old unfinished two-step upload placeholders (uploadedAt/path missing and beyond grace period) are cleaned up efficiently using
     indexed, batched processing.

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have updated developer-facing release notes if this change is **relevant** for external developers:
  - Add a short entry to `RELEASE_INFO-6.<major>.md` under “Upcoming” for informational changes, including the consequences of the change and how it affects external developers.
  - Add an `UPGRADE` section in `UPGRADE-6.<next-major>.md` for breaking changes (what/why/impact/how to adapt).
  - See the [Documenting a Release Process](https://github.com/shopware/shopware/blob/trunk/delivery-process/documenting-a-release.md) for details.
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Core/Content/Media/ScheduledTask/CleanupCorruptedMediaHandler.php [hunk 1]
```diff
@@ -35,18 +43,41 @@ public function __construct(
...
+            $criteria->setLimit(self::CORRUPTED_MEDIA_BATCH_SIZE);
+
+            $ids = $this->mediaRepository->searchIds($criteria, $context)->getIds();
+
+            if ($ids === []) {
+                return;
+            }
 
-        $ids = $this->mediaRepository->searchIds($criteria, $context)->getIds();
+            $lastId = $ids[array_key_last($ids)];
```
Comment (mitelg) [inline src/Core/Content/Media/ScheduledTask/CleanupCorruptedMediaHandler.php]:
```suggestion
            $lastId = array_last($ids);
```

**Review by mitelg — APPROVED** [review]

**Review by dgrothaus-sw — APPROVED** [review]
