### PR TITLE
fix: Add default language to ui

### LINKED ISSUE #10149: Sales Channel – Missing Validation for Required Language
### Shopware Version

6.7

### Affected area / extension

Platform(Default)

### Actual behaviour

“Default language” field is marked as required, but no validation error appears if left empty

Image

### Expected behaviour

Show validation error message when left blank

### How to reproduce

Create sales channel -> leave Default language empty -> save

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by alexdumea**
### 1. Why is this change necessary?
Default language field when creating sales channels is empty in UI even if as default we use the system language

### 2. What does this change do, exactly?
Pre-fills `languageId` with system default language
Ensure the field shows a value in UI instead of being blank

### 3. Describe each step to reproduce the issue or behaviour.
Try to create a new storefront sales channel
Check default language field that is required but empty
Save

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have updated developer-facing release notes if this change is **relevant** for external developers:
  - Add a short entry to `RELEASE_INFO-6.<major>.md` under “Upcoming” for informational changes, including the consequences of the change and how it affects external developers.
  - Add an `UPGRADE` section in `UPGRADE-6.<next-major>.md` for breaking changes (what/why/impact/how to adapt).
  - See the [Documenting a Release Process](https://github.com/shopware/shopware/blob/trunk/delivery-process/documenting-a-release.md) for details.
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Administration/Resources/app/administration/src/module/sw-sales-channel/page/sw-sales-channel-create/index.js [hunk 1]
```diff
@@ -44,6 +44,9 @@ export default {
             this.salesChannel.typeId = this.$route.params.typeId;
             this.salesChannel.active = false;
 
+            // Set default language from admin context
+            this.salesChannel.languageId = Shopware.Store.get('context').api.languageId;
```
Comment (MartinKrzykawski) [inline src/Administration/Resources/app/administration/src/module/sw-sales-channel/page/sw-sales-channel-create/index.js]: Can you cover this with an unit test please?

**Review by MartinKrzykawski — APPROVED** [review]

**Review by dgrothaus-sw — CHANGES_REQUESTED** [review]
This change does not fulfil the requirements for the reported issue.

The input for the language is still marked as required but not checked for requirement. It is now pre-filled with the default language, but the input can be deleted and it won't be marked as a missing input when submitting the form.

Same for the **Storefront** input, when creating a product comparison sales channel. It's tagged with an asterisk, but there's no error message or highlighting when the input is missing.

**Comment by alexdumea** [comment]
@dgrothaus-sw , you're correct , the field can be cleared and no validation error because the backend auto-fills 'languageId' no matter what (so it's never actually null -> see `WriteContext::createFromContext()` even `WriteContext::resetPaths()` that ensures the language id is always available). That's the whole difference from the other fields . I think this auto-fill is intentional for entities like order where we get the language from context and not specifically set it. Maybe it makes more sense to remove to option to clear field for this languageId selection if it's visually better

**Comment by dgrothaus-sw** [comment]
Additional comment from @MalteJanz .

There's an issue with saving the sales channel when no domain has been configured and the error message does not show always.

**Review by dgrothaus-sw — APPROVED** [review]

**Review by ravenokko — APPROVED** [review]
