### PR TITLE
fix: Partial entity loading with nested association

### LINKED ISSUE #5114: Expected collection element of type MediaEntity got PartialEntity
*PHP Version:* 8.3   | *Shopware Version:* 6.6.7.0  | *Affected area / extension:* Platform(Default) 

----

*_Expected behaviour:_*

Should return result as before 6.6.7.0

*_Actual behaviour:_*

Throws exception: `Expected collection element of type Shopware\Core\Content\Media\MediaEntity got Shopware\Core\Framework\DataAbstractionLayer\PartialEntity`

Image

*_How to reproduce:_*

```php
$criteria = new Criteria();

$criteria->addFields(['cover.media']);
$criteria->addFilter(new EqualsFilter('productNumber', $productNo));
$criteria->addAssociation('cover.media.thumbnails');

$cover = $this->productRepository->search($criteria, $context);
```

### PR DESCRIPTION
**Pull request by mitelg**
### 1. Why is this change necessary?

Loading partial entities with nested associations fails. See linked issue

### 2. What does this change do, exactly?

Change the detection of partial entity loading in the `EntityReader`, so it is determined at the beginning of the read and is passed down.
Inspired by a PR of @OliverSkroblin https://github.com/shopware/shopware/pull/5169

### 4. Please link to the relevant issues (if any).
- closes https://github.com/shopware/shopware/issues/5114

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [ ] I have updated developer-facing release notes if this change is **relevant** for external developers:
  - Add a short entry to `RELEASE_INFO-6.<major>.md` under “Upcoming” for informational changes, including the consequences of the change and how it affects external developers.
  - Add an `UPGRADE` section in `UPGRADE-6.<next-major>.md` for breaking changes (what/why/impact/how to adapt).
  - See the [Documenting a Release Process](https://github.com/shopware/shopware/blob/trunk/delivery-process/documenting-a-release.md) for details.
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Core/Framework/DataAbstractionLayer/Dbal/EntityReader.php [hunk 1]
```diff
@@ -111,15 +115,15 @@ private function _read(
             return $collection;
         }
 
-        if ($partial !== []) {
-            $fields = $definition->getFields()->filter(function (Field $field) use (&$partial) {
+        if ($fieldsForPartialLoading !== []) {
```
Comment (umutdogan4291) [inline src/Core/Framework/DataAbstractionLayer/Dbal/EntityReader.php:120]: Can we use $isPartialLoading here?

Comment (mitelg) [reply src/Core/Framework/DataAbstractionLayer/Dbal/EntityReader.php:120]: no, this would change the logic for calls of the `_read` in other places here :see_no_evil: 

tried that in first draft, didn't work :sweat_smile:

**Review by shyim — APPROVED** [review]

**Review by umutdogan4291 — APPROVED** [review]

File: tests/integration/Core/Framework/DataAbstractionLayer/Reader/EntityReaderTest.php [hunk 2]
```diff
@@ -346,6 +342,36 @@ public function testPartialLoadingManyToMany(): void
...
+                ->cover('cover1')
+                ->build(),
+        ];
+        $context = Context::createDefaultContext();
+        $this->productRepository->create($products, $context);
+
+        $criteria = new Criteria();
+        $criteria->addFields(['cover.media']);
+        $criteria->addFilter(new EqualsFilter('productNumber', $productNumber));
+        $criteria->addAssociation('cover.media.thumbnails');
```
Comment (keulinho) [inline tests/integration/Core/Framework/DataAbstractionLayer/Reader/EntityReaderTest.php:366]: what about the thumbnails association? how is it supposed to work in combination with the partial field loading? 🤔 

so will $media->get('thumbnails') return something or not?

Comment (mitelg) [reply tests/integration/Core/Framework/DataAbstractionLayer/Reader/EntityReaderTest.php:366]: yes, it will return an empty EntityCollection (probably, because thumbnails are not generated during the test :thinking: )

should we assert that, too?

Comment (keulinho) [reply tests/integration/Core/Framework/DataAbstractionLayer/Reader/EntityReaderTest.php:366]: why do we add the association then here? 🤔 

and yes i would be interested what happens when you add an association to an partial entity, that could be a second testcase

Comment (keulinho) [reply tests/integration/Core/Framework/DataAbstractionLayer/Reader/EntityReaderTest.php:366]: i mean what happens when the association really exists

Comment (mitelg) [reply tests/integration/Core/Framework/DataAbstractionLayer/Reader/EntityReaderTest.php:366]: if we would not add the `thumbnails` association here, the test case from the issue would not fail. 

the use case from the issue is, that you want all the information about a media from the cover of a specific product, incl. the thumbnails. 

but now I see, that this would not work like this. once the criteria is defined with fields, partial loading is and must be applied to all associations. Before this change, this was not the case. 
First issue was the usage of `MediaCollection`for the `media` association. 
Second issue was the usage of `MediaThumbnailCollection` for the thumbnails. 
Those were the two if conditions I changed.

Comment (mitelg) [reply tests/integration/Core/Framework/DataAbstractionLayer/Reader/EntityReaderTest.php:366]: so normally you would need to define the `thumbnails` as field as well to get them loaded, but this also seems to work :man_shrugging:

Comment (mitelg) [reply tests/integration/Core/Framework/DataAbstractionLayer/Reader/EntityReaderTest.php:366]: added two more assertions. should be okay now

File: src/Core/Framework/DataAbstractionLayer/Dbal/EntityReader.php (hunk 1 above)
Comment (mitelg) [reply src/Core/Framework/DataAbstractionLayer/Dbal/EntityReader.php:120]: added a comment, to make that clear :wink:

**Review by keulinho — APPROVED** [review]
