### PR TITLE
fix: web installer db autofill from env

### LINKED ISSUE #7835: Installer does not use DATABASE_URL
### PHP Version

*

### Shopware Version

* 6.6 / 6.7

### Affected area / extension

Platform(Default)

### Actual behaviour

The web installer ignores `DATABASE_URL`. This leads to issues after the install if the config different. 

### Expected behaviour

The installer should use the connection config from `DATABASE_URL` when it's set

### How to reproduce

- `composer create-project shopware/production`
  - add docker recipe
- `compose up`
- `symfony server:start -d` 
- install via web installer

### PR DESCRIPTION
**Pull request by umutdogan4291**
### 1. Why is this change necessary?
To avoid mistakes when entering database credentials and speed up installation.

### 2. What does this change do, exactly?
It autofills the database fields in the installer with default values.

### 3. Describe each step to reproduce the issue or behaviour.
Start the installer
Go to the database setup form
Database fields are automatically filled with default values from environment variables

### 4. Please link to the relevant issues (if any).
https://github.com/shopware/shopware/issues/7835

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have updated developer-facing release notes if this change is **relevant** for external developers:
  - Add a short entry to `RELEASE_INFO-6.<major>.md` under “Upcoming” for informational changes, including the consequences of the change and how it affects external developers.
  - Add an `UPGRADE` section in `UPGRADE-6.<next-major>.md` for breaking changes (what/why/impact/how to adapt).
  - See the [Documenting a Release Process](https://github.com/shopware/shopware/blob/trunk/delivery-process/documenting-a-release.md) for details.
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: tests/unit/Core/Installer/Controller/DatabaseConfigurationControllerTest.php [hunk 1]
```diff
@@ -64,8 +65,46 @@ protected function setUp(): void
         $this->controller->setContainer($this->getInstallerContainer($this->twig, ['router' => $this->router]));
     }
 
+    #[BackupGlobals(true)]
```
Comment (mitelg) [inline tests/unit/Core/Installer/Controller/DatabaseConfigurationControllerTest.php]: instead of this attribute and setting something to the global variable directly, you should use `\Shopware\Core\Framework\Test\TestCaseBase\EnvTestBehaviour`

**Review by mitelg — CHANGES_REQUESTED** [review]

File: tests/unit/Core/Installer/Controller/DatabaseConfigurationControllerTest.php (hunk 1 above)
Comment (umutdogan4291) [reply tests/unit/Core/Installer/Controller/DatabaseConfigurationControllerTest.php]: Thank you

**Review by mitelg — APPROVED** [review]

**Review by nfortier-shopware — APPROVED** [review]
