### PR TITLE
fix: increase criteria limit for property groups

### LINKED ISSUE #6807: Criteria Limit of 500 items blocks loading administration modules like the "Storefront presentation"-Modal
*PHP Version:* 8.3.9   | *Shopware Version:* 6.6.9.0  | *Affected area / extension:* Platform(Default) 

 ----

*_Actual behaviour:_*

We noticed an error, when we want open the "Storefront presentation"-Modal on a variant-product: 
the modal opens with continious loading-icon, but never gets a content. 

After some checks, we noticed, that the method wich loads the property-groups, loads only the first 500 property-group-items, because of the configured limit of 500 items per request. We already have more than 1.900 property-groups and so the opening of the Storefront presentation for many variant-products is not possible anymore.

*_Expected behaviour:_*

The administration-modal should open correctly and all groups schould be loaded with their property-options.

*_How to reproduce:_*

 - Create more than 500 property-groups with related options
 - Create a variant-product with a configurator-option whose property group is not included into the first 500 property-groups loaded via the api-call
 - when you now try to open the "Storefront presentation"-Modal over the administration, the modal will be shown, but content ist not loaded and loading-icon will not disappear.

Code-Line where the groups are loaded without a configured limit, but getting only the first 500 results caused of pre-configured MAX_LIMIT of 500 items:
https://github.com/shopware/shopware/blob/v6.6.9.0/src/Administration/Resources/app/administration/src/module/sw-product/view/sw-product-detail-variants/index.js#L184

### PR DESCRIPTION
**Pull request by nguyenytran**
### Actual behaviour:

We noticed an error, when we want open the "Storefront presentation"-Modal on a variant-product: 
the modal opens with continious loading-icon, but never gets a content. 

After some checks, we noticed that the method that loads the property groups loads only the first 500 property group items because of the configured limit of 500 items per request. We already have more than 1,900 property groups, and so opening the Storefront presentation for many variant products is not possible anymore.

### Expected behaviour:

The administration-modal should open correctly and all groups schould be loaded with their property-options.

### How to reproduce:

Create more than 500 property-groups with related options

Create a variant-product with a configurator-option whose property group is not included into the first 500 property-groups loaded via the api-call

when you now try to open the "Storefront presentation"-Modal over the administration, the modal will be shown, but content ist not loaded and loading-icon will not disappear.

### CODE REVIEW

File: src/Administration/Resources/app/administration/src/module/sw-product/view/sw-product-detail-variants/index.js [hunk 1]
```diff
@@ -248,5 +249,26 @@ export default {
...
+            const initialResult = await this.groupRepository.search(criteria);
+            const totalGroups = initialResult.total;
+            const limit = initialResult.length;
+
+            const totalPages = Math.ceil(totalGroups / limit);
+
+            const promises = [];
+            // eslint-disable-next-line no-plusplus
+            for (let page = 2; page <= totalPages; page++) {
+                const pageCriteria = new Criteria();
```
Comment (sydinh) [inline src/Administration/Resources/app/administration/src/module/sw-product/view/sw-product-detail-variants/index.js]: nextCriteria

**Review by sydinh — APPROVED** [review]

**Comment by sydinh** [comment]
LGTM ✅

**Comment by nguyenquocdaile** [comment]
Please backport to `6.6.x` and `6.7.0`

**Review by nguyenquocdaile — APPROVED** [review]

**Comment by vienthuong** [comment]
Please check the comment in this PR https://github.com/shopware/shopware/pull/8143

**Review by vienthuong — APPROVED** [review]
