### PR TITLE
fix: rollback plugin installation on failure

### LINKED ISSUE #11331: Install tool reports plugin install success, even on uncaught sql errors
### Shopware Version

6.6.10.5

### Affected area / extension

Platform(Default)

### Actual behaviour

As found out in #11042 having a SQL_SAFE_UPDATES = 1 in a plugin migration and leave it active after all migrations are applied, leads to errors in the shopware plugin install process afterwards. This Error is reported on the console, but ignored by the install command. 
Resulting in an installed “yes” marker in the plugin:list overview.
But the actual installation is incomplete (composer dependencies are not installed, maybe more) and the plugin not useable.

    08:09:57 CRITICAL [console] Error thrown while running command "plugin:install MYPLUGIN". Message: "An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1175 You are using safe update mode and you tried to update a table without a WHERE that uses a KEY column. " ["exception" => Doctrine\DBAL\Exception\DriverException^ { …},"command" => "plugin:install MYPLUGIN","message" => "An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1175 You are using safe update mode and you tried to update a table without a WHERE that uses a KEY column. "]

    In ExceptionConverter.php line 118:

    An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1175 You are using safe update mode and you tried to update a table without a WHERE that uses a KEY column.

    In Exception.php line 24:

    SQLSTATE[HY000]: General error: 1175 You are using safe update mode and you tried to update a table without a WHERE that uses a KEY column.

    In Statement.php line 131:

    SQLSTATE[HY000]: General error: 1175 You are using safe update mode and you tried to update a table without a WHERE that uses a KEY column.

### Expected behaviour

Any error on install should be handled.

### How to reproduce

Add `$connection->executeStatement('SET SQL_SAFE_UPDATES = 1;');` to any migration.

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by umutdogan4291**
### 1. Why is this change necessary?
A plugin can fail during installation but still be marked as installed, which leaves it broken.

### 2. What does this change do, exactly?
It uninstalls the plugin when an error happens during installation.

### 3. Describe each step to reproduce the issue or behaviour.

1. Add a migration that enables SQL_SAFE_UPDATES.
2. Install the plugin via the CLI.
3. An error occurs during installation.
4. The plugin is still shown as installed.

### 4. Please link to the relevant issues (if any).
https://github.com/shopware/shopware/issues/11331

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have updated developer-facing release notes if this change is **relevant** for external developers:
  - Add a short entry to `RELEASE_INFO-6.<major>.md` under “Upcoming” for informational changes, including the consequences of the change and how it affects external developers.
  - Add an `UPGRADE` section in `UPGRADE-6.<next-major>.md` for breaking changes (what/why/impact/how to adapt).
  - See the [Documenting a Release Process](https://github.com/shopware/shopware/blob/trunk/delivery-process/documenting-a-release.md) for details.
- [x] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Core/Framework/Plugin/PluginLifecycleService.php [hunk 1]
```diff
@@ -167,6 +167,10 @@ public function installPlugin(PluginEntity $plugin, Context $shopwareContext): I
                 $this->executor->remove($plugin->getComposerName(), $plugin->getName());
             }
 
+            if ($plugin->getInstalledAt()) {
+                $this->uninstallPlugin($plugin, $shopwareContext);
```
[the remark this answers is not in the document]
Comment (mitelg) [reply src/Core/Framework/Plugin/PluginLifecycleService.php]: that thing has a point here

File: src/Core/Framework/Plugin/PluginLifecycleService.php [hunk 2]
```diff
@@ -167,6 +167,10 @@ public function installPlugin(PluginEntity $plugin, Context $shopwareContext): I
                 $this->executor->remove($plugin->getComposerName(), $plugin->getName());
             }
 
+            if ($plugin->getInstalledAt()) {
```
Comment (mitelg) [inline src/Core/Framework/Plugin/PluginLifecycleService.php]: could probably also be put into a "finally" branch? :thinking:

File: tests/integration/Core/Framework/Plugin/PluginLifecycleServiceTest.php [hunk 3]
```diff
@@ -514,6 +515,29 @@ public function testInstallationOfPluginWhichExecutesComposerCommandsWithPreviou
...
+        $dispatcher = $this->container->get('event_dispatcher');
+
+        $listener = static function (): void {
+            throw new \RuntimeException('Fail from post-install event');
+        };
+
+        try {
+            $dispatcher->addListener(PluginPostInstallEvent::class, $listener);
+
+            $this->expectException(\RuntimeException::class);
```
Comment (mitelg) [inline tests/integration/Core/Framework/Plugin/PluginLifecycleServiceTest.php]: you should use `expectExceptionObject` instead. which checks the instance, message and so on

**Review by mitelg — CHANGES_REQUESTED** [review]

File: src/Core/Framework/Plugin/PluginLifecycleService.php (hunk 2 above)
Comment (umutdogan4291) [reply src/Core/Framework/Plugin/PluginLifecycleService.php]: True. That makes it safer.

File: tests/integration/Core/Framework/Plugin/PluginLifecycleServiceTest.php (hunk 3 above)
Comment (umutdogan4291) [reply tests/integration/Core/Framework/Plugin/PluginLifecycleServiceTest.php]: Thanks :)

File: src/Core/Framework/Plugin/PluginLifecycleService.php [hunk 4]
```diff
@@ -168,6 +168,10 @@ public function installPlugin(PluginEntity $plugin, Context $shopwareContext): I
             }
 
             throw $e;
+        } finally {
+            if (isset($e) && $plugin->getInstalledAt()) {
```
Comment (shyim) [inline src/Core/Framework/Plugin/PluginLifecycleService.php]: why can't we do it in catch above? it feels weird to have an finally 🤔 without multiple catches

Comment (umutdogan4291) [reply src/Core/Framework/Plugin/PluginLifecycleService.php]: :thinking: In that case if there is another exception thrown in the catch block before this code, it will not uninstall the plugin.

Comment (mitelg) [reply src/Core/Framework/Plugin/PluginLifecycleService.php]: we would need another try catch around the if with the `$this->executor->remove` call :thinking: 
is finally even called if in the above mentioned call an exception would be thrown? :thinking: 

with that isset check if looks a bit ugly :sweat_smile:

File: tests/integration/Core/Framework/Plugin/PluginLifecycleServiceTest.php [hunk 5]
```diff
@@ -514,6 +515,28 @@ public function testInstallationOfPluginWhichExecutesComposerCommandsWithPreviou
...
 
+    public function testPluginInstallFailureTriggersUninstall(): void
+    {
+        $dispatcher = $this->container->get('event_dispatcher');
+
+        $listener = static function (): void {
+            throw new \RuntimeException('Fail from post-install event');
+        };
+
+        try {
```
Comment (mitelg) [inline tests/integration/Core/Framework/Plugin/PluginLifecycleServiceTest.php:542]: why the try catch around all that?

File: tests/integration/Core/Framework/Plugin/PluginLifecycleServiceTest.php [hunk 6]
```diff
@@ -514,6 +515,28 @@ public function testInstallationOfPluginWhichExecutesComposerCommandsWithPreviou
...
+            $dispatcher->addListener(PluginPostInstallEvent::class, $listener);
+
+            $this->expectExceptionObject(new \RuntimeException('Fail from post-install event'));
+
+            $plugin = $this->getPlugin($this->context);
+            $this->pluginLifecycleService->installPlugin($plugin, $this->context);
+
+            static::assertNull($plugin->getInstalledAt());
```
Comment (mitelg) [inline tests/integration/Core/Framework/Plugin/PluginLifecycleServiceTest.php:547]: this check will not be executed. the expected exception is thrown in the `installPlugin`. every code after that, will not be executed anymore.

Comment (umutdogan4291) [reply tests/integration/Core/Framework/Plugin/PluginLifecycleServiceTest.php:547]: True. I can move it into finally maybe :thinking: it will be executed there.

File: tests/integration/Core/Framework/Plugin/PluginLifecycleServiceTest.php (hunk 5 above)
Comment (umutdogan4291) [reply tests/integration/Core/Framework/Plugin/PluginLifecycleServiceTest.php:542]: I wanted to remove the listener even if this test fails to prevent any flaky behavior in other scenarios.

File: src/Core/Framework/Plugin/PluginLifecycleService.php (hunk 4 above)
Comment (umutdogan4291) [reply src/Core/Framework/Plugin/PluginLifecycleService.php]: Yes, I have tested that if an exception is thrown in `$this->executor->remove`, finally is called and the plugin is uninstalled.

I agree that isset($e) is not precise enough :thinking: 

Edit: I added another try block for the composer cleanup in catch. Again used finally because I don't know what to do with the exception from `$this->executor->remove`. :thinking:

File: tests/integration/Core/Framework/Plugin/PluginLifecycleServiceTest.php (hunk 6 above)
Comment (umutdogan4291) [reply tests/integration/Core/Framework/Plugin/PluginLifecycleServiceTest.php:547]: I changed the structure a bit to use `static::assertNull($plugin->getInstalledAt());`

File: tests/integration/Core/Framework/Plugin/PluginLifecycleServiceTest.php (hunk 5 above)
Comment (mitelg) [reply tests/integration/Core/Framework/Plugin/PluginLifecycleServiceTest.php:542]: @nfortier-shopware maybe you know some trick, or is this fine?

File: tests/integration/Core/Framework/Plugin/PluginLifecycleServiceTest.php [hunk 7]
```diff
@@ -514,6 +515,30 @@ public function testInstallationOfPluginWhichExecutesComposerCommandsWithPreviou
...
+
+        $listener = static function () use ($expectedException): void {
+            throw $expectedException;
+        };
+        $dispatcher->addListener(PluginPostInstallEvent::class, $listener);
+
+        try {
+            $this->pluginLifecycleService->installPlugin($plugin, $this->context);
+        } catch (\Throwable $actualException) {
+            static::assertEquals($expectedException, $actualException);
```
Comment (mitelg) [inline tests/integration/Core/Framework/Plugin/PluginLifecycleServiceTest.php]: isn't it even the same? :grin:

**Review by mitelg — APPROVED** [review]

File: tests/integration/Core/Framework/Plugin/PluginLifecycleServiceTest.php (hunk 7 above)
Comment (umutdogan4291) [reply tests/integration/Core/Framework/Plugin/PluginLifecycleServiceTest.php]: true :D lately I used the same object but didn't update here

File: tests/integration/Core/Framework/Plugin/PluginLifecycleServiceTest.php (hunk 5 above)
Comment (BrocksiNet) [reply tests/integration/Core/Framework/Plugin/PluginLifecycleServiceTest.php:542]: Why not move the `removeListener()` call into the `tearDown()` function?

**New Property**
```php
/**
 * @var array<array{string, callable}>
 */
private array $registeredListeners = [];
```

**New Helper Method**
```php
private function addTestListener(string $eventName, callable $listener): void
{
    $dispatcher = $this->container->get('event_dispatcher');

    $dispatcher->addListener($eventName, $listener);

    $this->registeredListeners[] = [$eventName, $listener];
}
```

**Updated trearDown**
```php
protected function tearDown(): void
{
    if (isset($this->container)) {
        $dispatcher = $this->container->get('event_dispatcher');

        foreach ($this->registeredListeners as [$eventName, $listener]) {
            $dispatcher->removeListener($eventName, $listener);
        }
    }

    $this->registeredListeners = [];

    static::getContainer()
        ->get(Connection::class)
        ->rollBack();

    if (isset($_SERVER['FAKE_MIGRATION_NAMESPACE'])) {
        unset($_SERVER['FAKE_MIGRATION_NAMESPACE']);
    }

    if (isset($_SERVER['TEST_KEEP_MIGRATIONS'])) {
        unset($_SERVER['TEST_KEEP_MIGRATIONS']);
    }

    parent::tearDown();
}
```

**Refactored Test**
```php
public function testPluginInstallFailureTriggersUninstall(): void
{
    $plugin = $this->getPlugin($this->context);
    $expectedException = new \RuntimeException('Fail from post-install event');

    $listener = static function () use ($expectedException): void {
        throw $expectedException;
    };

    $this->addTestListener(PluginPostInstallEvent::class, $listener);

    try {
        $this->pluginLifecycleService->installPlugin($plugin, $this->context);
        static::fail('Expected exception was not thrown.');
    } catch (\Throwable $actualException) {
        static::assertSame($expectedException, $actualException);
    }

    static::assertNull($plugin->getInstalledAt());
}
```

**Review by shyim — APPROVED** [review]

File: tests/integration/Core/Framework/Plugin/PluginLifecycleServiceTest.php (hunk 5 above)
Comment (umutdogan4291) [reply tests/integration/Core/Framework/Plugin/PluginLifecycleServiceTest.php:542]: thanks. that looks better now :)

File: tests/integration/Core/Framework/Plugin/PluginLifecycleServiceTest.php [hunk 8]
```diff
@@ -126,6 +132,16 @@ protected function setUp(): void
 
     protected function tearDown(): void
     {
+        if (isset($this->container)) {
```
Comment (mitelg) [inline tests/integration/Core/Framework/Plugin/PluginLifecycleServiceTest.php]: this check is not necessary

Comment (umutdogan4291) [reply tests/integration/Core/Framework/Plugin/PluginLifecycleServiceTest.php]: If we get an exception before the container parameter is set 🤔 then we would see an error like "must not be accessed before $container is initialized" 
Please correct me if I am thinking wrong 🤔

Comment (mitelg) [reply tests/integration/Core/Framework/Plugin/PluginLifecycleServiceTest.php]: `$this->container = static::getContainer();` is set in the `setup` method of the test. 
if the property is not set in the `teardown` we have other problems :sweat_smile:

Comment (umutdogan4291) [reply tests/integration/Core/Framework/Plugin/PluginLifecycleServiceTest.php]: I thought when we have "other problems :D" at least tearDown shouldn't be interrupted by this. But I can at least move it to end of the tearDown

**Review by mitelg — APPROVED** [review]
