### PR TITLE
fix(customer): prevent failure when customer language is missing from sales channel

### LINKED ISSUE #7960: Delete customer - Saleschannel language removed
If the language a customer has, is deleted from “his/her” sales channel, then this customer can not be deleted. The {{salesChannelContext}} can not be created

{{Shopware\Core\Checkout\Customer\Subscriber\CustomerBeforeDeleteSubscriber::beforeDelete}}

{noformat}In SalesChannelException.php line 121:
                                                                                                                                
  [Shopware\Core\System\SalesChannel\SalesChannelException]                                                                     
  Provided language "2fbb5fe2e29a4d70aa5854ce7ce3e20b" is not in list of available languages: 0191e5eedb0f7307bdf4a372d2c46116 {noformat}

Customer language English (Default Language)

!image-20250205-102523.png|width=458,height=233,alt="image-20250205-102523.png"!

### PR DESCRIPTION
**Pull request by Aliaaaam**
### 1. Why is this change necessary?
Deleting a customer fails if the language assigned to the customer is no longer available in customer's sales channel.

### 2. What does this change do, exactly?
This fix handles the case where a customer’s language has been removed from the sales channel.
Instead of failing while creating the `SalesChannelContext`, the deletion process proceeds safely allowing the customer to be deleted without throwing a `SalesChannelException`.

### 3. Describe each step to reproduce the issue or behaviour:
1. Add multiple langauges to the sales channel (Storefront for instance).
2. Create a customer and assign them a language.
3. Remove that language from the sales channel configuration.
4. Attempt to delete the customer from the Administration.
5. An exception is thrown (_Provided language is not in list of available languages_) and the customer cannot be deleted.

### 4. Please link to the relevant issues.
- Fixes #7960 
- Fixed deletion part of #5767

### 5. Checklist
- [x] I have written tests and verified that they fail without my change
- [ ] I have updated developer-facing release notes if this change is **relevant** for external developers:
  - Add a short entry to `RELEASE_INFO-6.<major>.md` under “Upcoming” for informational changes, including the consequences of the change and how it affects external developers.
  - Add an `UPGRADE` section in `UPGRADE-6.<next-major>.md` for breaking changes (what/why/impact/how to adapt).
  - See the [Documenting a Release Process](https://github.com/shopware/shopware/blob/trunk/delivery-process/documenting-a-release.md) for details.
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Core/Checkout/Customer/Subscriber/CustomerBeforeDeleteSubscriber.php [hunk 1]
```diff
@@ -78,16 +79,33 @@ public function beforeDelete(EntityDeleteEvent $event): void
...
+                        new SalesChannelContextServiceParameters(
+                            $salesChannelId ?? $customer->getSalesChannelId(),
+                            Random::getAlphanumericString(32),
+                            $customer->getLanguageId(),
+                            null,
+                            null,
+                            $context,
+                        )
+                    );
+                } catch (SalesChannelException $e) {
```
Comment (cyl3x) [inline src/Core/Checkout/Customer/Subscriber/CustomerBeforeDeleteSubscriber.php]: While possible, until we reach the exception a lot of loading has happened, slowing down the deletion. How about using the language / sales channel repository to do a small lookup if the language ID is available for the sales channel? you can use the `Criteria::addFields` method to reduce the amount of data you're loading, which should result in a even faster lookup

File: src/Core/Checkout/Customer/Subscriber/CustomerBeforeDeleteSubscriber.php [hunk 2]
```diff
@@ -78,16 +79,33 @@ public function beforeDelete(EntityDeleteEvent $event): void
...
+                    if ($e->getErrorCode() === SalesChannelException::SALES_CHANNEL_LANGUAGE_NOT_AVAILABLE_EXCEPTION) {
```
Comment (mitelg) [inline src/Core/Checkout/Customer/Subscriber/CustomerBeforeDeleteSubscriber.php]: if we need to check the error code, we should introduce a specific child class of the `SalesChannelException` for that case

File: src/Core/Checkout/Customer/Subscriber/CustomerBeforeDeleteSubscriber.php (hunk 1 above)
Comment (Aliaaaam) [reply src/Core/Checkout/Customer/Subscriber/CustomerBeforeDeleteSubscriber.php]: I’ve added the sales channel lookup as you proposed.

File: src/Core/Checkout/Customer/Subscriber/CustomerBeforeDeleteSubscriber.php (hunk 2 above)
Comment (Aliaaaam) [reply src/Core/Checkout/Customer/Subscriber/CustomerBeforeDeleteSubscriber.php]: I’ve changed the implementation entirely to use a sales channel lookup, as proposed by @cyl3x

File: src/Core/Checkout/Customer/Subscriber/CustomerBeforeDeleteSubscriber.php [hunk 3]
```diff
@@ -102,4 +110,63 @@ public function beforeDelete(EntityDeleteEvent $event): void
             }
         });
     }
+
+    /**
+     * @return array<string, string|null>
+     */
+    private function resolveEffectiveLanguageIds(CustomerCollection $customers, ?string $salesChannelIdFromSource, Context $context): array
```
Comment (cyl3x) [inline src/Core/Checkout/Customer/Subscriber/CustomerBeforeDeleteSubscriber.php]: This looks a bit complex, how about reducing it a bit?

```php
        $criteria = (new Criteria($salesChannelIds))
            ->addFields(['languages'])
            ->getAssociation('languages')
                ->addFields(['id']);

        $salesChannels = $this->salesChannelRepository->search($salesChannelCriteria, $context)->getEntities();
       
        // ...

       $languageId = $salesChannels->get($salesChannelId ?? $customer->getSalesChannelId())?->get('languages')?->get($customer->getLanguageId())?->getId();
      // build context
```
Because matching the pairs by customer doesn't really matter 🤔

Comment (cyl3x) [reply src/Core/Checkout/Customer/Subscriber/CustomerBeforeDeleteSubscriber.php]: Maybe add a language Id filter too, `new EqualsAny('id', $customers->map(fn ($c) => $c->getLanguageId())))` :thinking:

Comment (Aliaaaam) [reply src/Core/Checkout/Customer/Subscriber/CustomerBeforeDeleteSubscriber.php]: @cyl3x I simplified the logic and also added a filter to load only the given language IDs.

**Review by cyl3x — APPROVED** [review]

**Review by mitelg — APPROVED** [review]

File: src/Core/Checkout/Customer/Subscriber/CustomerBeforeDeleteSubscriber.php [hunk 4]
```diff
@@ -102,4 +120,17 @@ public function beforeDelete(EntityDeleteEvent $event): void
             }
         });
     }
+
+    private function loadSalesChannelLanguages(CustomerCollection $customers, ?string $salesChannelIdFromSource, Context $context): SalesChannelCollection
+    {
+        $salesChannelIds = $customers->map(fn ($c) => $salesChannelIdFromSource ?? $c->getSalesChannelId());
```
Comment (En0Ma1259) [inline src/Core/Checkout/Customer/Subscriber/CustomerBeforeDeleteSubscriber.php]: Isn't this the same?
```suggestion
        $salesChannelIds = $salesChannelIdFromSource ?? [$salesChannelIdFromSource] : $customers->getSalesChannelIds();
```

File: src/Core/Checkout/Customer/Subscriber/CustomerBeforeDeleteSubscriber.php [hunk 5]
```diff
@@ -102,4 +120,17 @@ public function beforeDelete(EntityDeleteEvent $event): void
...
+        $languageIds = $customers->map(fn ($c) => $c->getLanguageId());
```
Comment (En0Ma1259) [inline src/Core/Checkout/Customer/Subscriber/CustomerBeforeDeleteSubscriber.php]: Since `CustomerCollection` has many `get...Ids()` methods, one could consider implementing a new method.

File: src/Core/Checkout/Customer/Subscriber/CustomerBeforeDeleteSubscriber.php [hunk 6]
```diff
@@ -102,4 +120,17 @@ public function beforeDelete(EntityDeleteEvent $event): void
...
+
+        $criteria = (new Criteria($salesChannelIds))->addAssociation('languages');
```
Comment (En0Ma1259) [inline src/Core/Checkout/Customer/Subscriber/CustomerBeforeDeleteSubscriber.php]: `addAssociation` is not needed, if you also use `getAssociation`

Comment (Aliaaaam) [reply src/Core/Checkout/Customer/Subscriber/CustomerBeforeDeleteSubscriber.php]: Resolved.

File: src/Core/Checkout/Customer/Subscriber/CustomerBeforeDeleteSubscriber.php (hunk 5 above)
Comment (Aliaaaam) [reply src/Core/Checkout/Customer/Subscriber/CustomerBeforeDeleteSubscriber.php]: a new `getLanguageIds()` introduced in `CustomerCollection`.

File: src/Core/Checkout/Customer/Subscriber/CustomerBeforeDeleteSubscriber.php (hunk 4 above)
Comment (Aliaaaam) [reply src/Core/Checkout/Customer/Subscriber/CustomerBeforeDeleteSubscriber.php]: Yes make sense, I used yours.

**Review by En0Ma1259 — APPROVED** [review]
