### PR TITLE
fix: adds CMS data mapping source for media custom fields #14648

### LINKED ISSUE #14648: Custom Field Data Mapping: Media custom field treated as text
### Shopware Version

6.7.6.2

### Affected area / extension

Platform(Default)

### Actual behaviour

A media custom field for e.g. a category cannot be selected via data mapping for an image element in that category's layout.
It can however be selected for a text element in the same layout.

### Expected behaviour

While this is what should and does happen with text custom fields, media custom fields should be selectable as a data source in image elements, not in text elements.

### How to reproduce

Create a media custom field for categories.
Then navigate to a category with an editable layout containing an image and a text element.
Observe the options for data mapping in both elements.

### PR DESCRIPTION
**Pull request by zFl4wless**
### 1. Why is this change necessary?

Media custom fields on entities like products and categories cannot be used as data sources for CMS image elements, even though they are configured as media types.
This prevents shop administrators from binding media custom fields to images in layouts and leads to confusing behaviour, because the same fields can incorrectly be selected in text elements instead.

### 2. What does this change do, exactly?

This change adjusts the CMS data mapping so that media-type custom fields are exposed as valid data sources for image elements (e.g. on product and category pages).
At the same time, media custom fields are no longer offered as mappings for text elements, aligning the UI and data mapping behaviour with the actual field type.

### 3. Describe each step to reproduce the issue or behaviour.

1. Create a custom field set with a custom field of type “media” for categories (and/or products).
2. Assign the custom field set to the corresponding entity so the field is available in the administration.
3. Open a category (or product) that uses a layout containing both an image element and a text element.
4. Edit the layout, select the image element, and open the data mapping dropdown: the media custom field is not available as a selectable source.
5. Select the text element in the same layout and open the data mapping dropdown: the same media custom field is incorrectly available as a selectable source.

### 4. Please link to the relevant issues (if any).

closes #14648

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [x] I have updated developer-facing release notes if this change is **relevant** for external developers:
  - Add a short entry to `RELEASE_INFO-6.<major>.md` under “Upcoming” for informational changes, including the consequences of the change and how it affects external developers.
  - Add an `UPGRADE` section in `UPGRADE-6.<next-major>.md` for breaking changes (what/why/impact/how to adapt).
  - See the [Documenting a Release Process](https://github.com/shopware/shopware/blob/trunk/delivery-process/documenting-a-release.md) for details.
- [x] I have written or adjusted the documentation according to my changes
- [x] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfilled them

### CODE REVIEW

**Comment by zFl4wless** [comment]
I would also love to have this issue fixed in the 6.6 Version. What do i have to do for this to happen?

**Comment by marcelbrode** [comment]
> I would also love to have this issue fixed in the 6.6 Version. What do i have to do for this to happen?

Added the backport label. When this gets merged, it will auto create a second PR

**Comment by zFl4wless** [comment]
@marcelbrode I resolved the lint issue. Is there anything else I need to do now?

**Comment by marcelbrode** [comment]
> Marcel Brode (@marcelbrode) I resolved the lint issue. Is there anything else I need to do now?

Allowed the pipeline to run again. Seems like a lint error is still there and some more. I guess you can see it now

**Comment by zFl4wless** [comment]
> > Marcel Brode (Marcel Brode (@marcelbrode)) I resolved the lint issue. Is there anything else I need to do now?
> 
> Allowed the pipeline to run again. Seems like a lint error is still there and some more. I guess you can see it now

Thanks! I just saw the feedback comments in the changed files and resolved these. I now also hopefully resolved the other checks that failed 😁

**Comment by marcelbrode** [comment]
> > > Marcel Brode (Marcel Brode (Marcel Brode (@marcelbrode))) I resolved the lint issue. Is there anything else I need to do now?
> > 
> > 
> > Allowed the pipeline to run again. Seems like a lint error is still there and some more. I guess you can see it now
> 
> Thanks! I just saw the feedback comments in the changed files and resolved these. I now also hopefully resolved the other checks that failed 😁

Fingers crossed 🤞

**Comment by zFl4wless** [comment]
Alright... I fixed the formatting. Then there is also the BC Check failing. But i don't know what to do there. I believe this isn't even cause by my changes, or?

It is saying something like `Shopware\Core\Framework\Api\Controller\UserController#logout() was removed` but I just worked on CMS/Admin/Media files and had nothing to do with the UserController.

**Comment by zFl4wless** [comment]
To improve patch coverage for the resolver changes, I now also added/extended unit tests for:
- `ImageCmsElementResolver`
- `VideoCmsElementResolver`
- `YoutubeVideoCmsElementResolver`

The tests now cover the new mapped-media paths in both `collect()` and `enrich()` (mapped `MediaEntity`, mapped string id, missing search result, non-entity resolver context).

**Comment by marcelbrode** [comment]
> Alright... I fixed the formatting. Then there is also the BC Check failing. But i don't know what to do there. I believe this isn't even cause by my changes, or?
> 
> It is saying something like `Shopware\Core\Framework\Api\Controller\UserController#logout() was removed` but I just worked on CMS/Admin/Media files and had nothing to do with the UserController.

Will check this tomorrow 👍

**Comment by zFl4wless** [comment]
All checks have passed 🤩

**Comment by marcelbrode** [comment]
Fantastic! 👍 Now my team can properly review it.

**Review by marcelbrode — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-cms/component/sw-cms-mapping-field/index.ts [hunk 1]
```diff
@@ -121,12 +125,37 @@ export default Shopware.Component.wrapComponentConfig({
...
+
+                this.demoValue = entity;
+            } catch {
+                if (fetchId === this.demoValueFetchId) {
+                    this.demoValue = demoValue;
+                }
+            }
         },
 
         onMappingSelect(property: string) {
```
Comment (MartinKrzykawski) [inline src/Administration/Resources/app/administration/src/module/sw-cms/component/sw-cms-mapping-field/index.ts:161]: Did you also consider the preview path in `onMappingSelect()` here? It still only assigns `getDemoValue(property)`, which for mapped media custom fields seems to be just the raw media ID until `updateDemoValue()` resolves the entity. That could leave the CMS preview empty or incorrect immediately after selecting the mapping, until another reactive update happens.

Comment (zFl4wless) [reply src/Administration/Resources/app/administration/src/module/sw-cms/component/sw-cms-mapping-field/index.ts:161]: Good catch, thanks.

`onMappingSelect()` was only assigning `getDemoValue(property)`, which can be the raw media id for mapped custom fields. That bypassed the entity-resolution path in `updateDemoValue()`, so the preview could be incomplete right after selecting a mapping.

I changed `onMappingSelect()` to trigger `updateDemoValue()` so mapped entity previews are resolved consistently immediately.

**Review by MartinKrzykawski — APPROVED** [review]

**Comment by MartinKrzykawski** [comment]
Hey @zFl4wless, thanks for your contribution! Your changes are merged 🚀 🙌

**Comment by zFl4wless** [comment]
> Hey @zFl4wless, thanks for your contribution! Your changes are merged 🚀 🙌 

No problem my friend! How does it now work with the backport?

**Comment by marcelbrode** [comment]
Well, normally it would take your commit and put it onto the 6.6.x branch and create a new pull request. In this case this doesnt work, since you touched files only available in trunk and it therefore got conflicts. So unfortunately, you have to create a new PR yourself.

Maybe check out 6.6.x and try to apply your changes yourself rn :/

**Comment by zFl4wless** [comment]
I now opened the PR for the 6.6.x backport.
