### PR TITLE
fix: search term custom find weird icons

### LINKED ISSUE #9486: Search term “custom” finds weird icons
### Shopware Version

6.7

### Affected area / extension

Platform(Default)

### Actual behaviour

Search term “custom” finds two entries that have a strange new symbol and cannot be clicked.

Image

### Expected behaviour

Is it maybe looking for "custom fields"? Touch base with the UX team.

### How to reproduce

Type 'custom' into the admin search

### PR DESCRIPTION
**Pull request by nguyenquocdaile**
### Description 

1. If a module doesn't define an entity, it will lead to a bug if we search for the name of this module.
ex: custom-entity module [here](https://github.com/shopware/shopware/blob/trunk/src/Administration/Resources/app/administration/src/module/sw-custom-entity/index.ts#L39)

2. Filter frequently used modules when they have an entity.

### Solution

| Before   | After |
|---------------------------|-------------------------|
| Screenshot 2025-05-22 at 15 47 51  | Screenshot 2025-05-22 at 15 53 57 |
| Screenshot 2025-05-22 at 14 34 37 | Screenshot 2025-05-22 at 15 54 12 |

### CODE REVIEW

File: src/Administration/Resources/app/administration/src/app/component/structure/sw-search-bar/index.js [hunk 1]
```diff
@@ -895,6 +895,8 @@ export default {
 
             moduleEntities.push(...this.getSalesChannelTypesBySearchTerm(regex));
 
+            moduleEntities = moduleEntities.filter((item) => item.entity);
```
Comment (nguyenytran) [inline src/Administration/Resources/app/administration/src/app/component/structure/sw-search-bar/index.js]: please add a test case

File: src/Administration/Resources/app/administration/src/app/component/structure/sw-search-bar/index.js [hunk 2]
```diff
@@ -987,7 +989,9 @@ export default {
                     return {
                         entity: 'frequently_used',
                         total: entities.length,
-                        entities: entities?.map((item) => this.getInfoModuleFrequentlyUsed(item)),
+                        entities: entities
+                            ?.map((item) => this.getInfoModuleFrequentlyUsed(item))
+                            .filter((item) => item),
```
Comment (nguyenytran) [inline src/Administration/Resources/app/administration/src/app/component/structure/sw-search-bar/index.js:994]: please add a test case

**Review by nguyenytran — APPROVED** [review]

**Review by vienthuong — APPROVED** [review]
