### PR TITLE
fix: add caching to lower amount of calls to update extensions

### LINKED ISSUE #8333: Reduce number of extension update checks to SBP
Everytime someone logs into the Shopware 6 admin a request is made to the SBP ([api.shopware.com/swplatform/pluginupdates|http://api.shopware.com/swplatform/pluginupdates]) to check if there are any new available extension updates.

These scenarios are currently known:

* The call is done for every single admin user. So if a 5 employees of a company logging in in the morning we get 5 requests.
* When someone reloads the page via CTRL+R or reopens it.

So please reduce the number of API requests. I cannot give a direct suggestion but here are some first ideas:

* Only 1 request in a specific interval (1 day, 4 hours)
* Only 1 request per shop and not 1 per admin user

If needed, I’m happy to discuss ideas and help from the SBP point of view.

----

In this small excerpt you can see what’s happening on SBP side.

[example.txt](https://github.com/user-attachments/files/19681486/example.txt)

### PR DESCRIPTION
**Pull request by Bird87ZA**
### 1. Why is this change necessary?
Calls were made to the update server every time a page was loaded

### 2. What does this change do, exactly?
reduces the number of calls to the update server

### 4. Please link to the relevant issues (if any).
fixes: #8333 

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfill them.

### CODE REVIEW

**Comment by cyl3x** [comment]
looks good but missing a changelog

File: src/Core/Framework/Store/Api/ExtensionStoreActionsController.php
Comment (cyl3x) [inline src/Core/Framework/Store/Api/ExtensionStoreActionsController.php:1]: I think it's best to also delete the cache on a refresh

Comment (Bird87ZA) [reply src/Core/Framework/Store/Api/ExtensionStoreActionsController.php:1]: When does a refresh happen?

File: src/Core/Framework/Store/Services/StoreClient.php [hunk 1]
```diff
@@ -34,6 +36,8 @@
 class StoreClient
 {
     public const EXTENSION_LICENSE_IS_ALREADY_CANCELLED = 'ShopwarePlatformException-61';
+    public const EXTENSION_LIST_CACHE = 'extensionListStatus';
+    public const EXTENSION_LIST_TTL = 3600; // 1 hour
```
Comment (mstegmeyer) [inline src/Core/Framework/Store/Services/StoreClient.php]: I think, one hour doesn't really help the SBP, right? They were complaining about "several times a day", right?

File: src/Core/Framework/Store/Api/ExtensionStoreActionsController.php
Comment (cyl3x) [reply src/Core/Framework/Store/Api/ExtensionStoreActionsController.php:1]: Wait stop, when is the `refreshExtensions` function called? Is it on purpose that the cache isn't deleted?

File: src/Core/Framework/Store/Services/StoreClient.php [hunk 2]
```diff
@@ -119,7 +124,11 @@ public function getExtensionUpdateList(ExtensionCollection $extensionCollection,
             ];
         }
 
-        return $this->getUpdateListFromStore($extensionList, $context);
+        return $this->cache->get(self::EXTENSION_LIST_CACHE, function (ItemInterface $item) use ($extensionList, $context) {
```
Comment (mstegmeyer) [inline src/Core/Framework/Store/Services/StoreClient.php:127]: Just curious, couldn't different users get different lists? Just in theory, do we block that different users are connected to different companies in the SBP?

**Review by mstegmeyer — CHANGES_REQUESTED** [review]

File: src/Core/Framework/Store/Services/StoreClient.php (hunk 1 above)
Comment (Bird87ZA) [reply src/Core/Framework/Store/Services/StoreClient.php]: This is what they say:

```
These scenarios are currently known:

The call is done for every single admin user. So if a 5 employees of a company logging in in the morning we get 5 requests.

When someone reloads the page via CTRL+R or reopens it.
```

So we could make it once a day, but this already solves the Ctr + R and 5 logins at once issue

File: src/Core/Framework/Store/Api/ExtensionStoreActionsController.php
Comment (Bird87ZA) [reply src/Core/Framework/Store/Api/ExtensionStoreActionsController.php:1]: I think it would be better to call it in refreshExtensions actually, since it gets called post install, update, remove and uninstall.

**Review by cyl3x — APPROVED** [review]

File: tests/unit/Core/Framework/Store/Api/ExtensionStoreActionsControllerTest.php [hunk 3]
```diff
@@ -59,7 +63,11 @@ public function testUploadExtensionsWithInvalidFile(): void
         $file->method('getPathname')->willReturn(tempnam(sys_get_temp_dir(), __METHOD__));
         $request->files->set('file', $file);
 
-        static::expectException(PluginNotAZipFileException::class);
+        if (!Feature::isActive('v6.8.0.0')) {
```
Comment (mitelg) [inline tests/unit/Core/Framework/Store/Api/ExtensionStoreActionsControllerTest.php]: you can use the following instead

```
$this->expectExceptionObject(StoreException::pluginNotAZipFile());
```

**Review by mstegmeyer — APPROVED** [review]

**Comment by shyim** [comment]
See https://github.com/shopware/shopware/issues/8333#issuecomment-2934821453 i would suggest reverting it or proper fixing it.
