### PR TITLE
fix: downloaded pdf has broken file extension

### LINKED ISSUE #9573: Spaces in document/number range prefix makes PDF file unusable
### Shopware Version

6.6.10.4

### Affected area / extension

Platform(Default)

### Actual behaviour

If a prefix such as “Invoice no.” (with a space at the end) is added in the number range and in the invoice document, the PDF file is no longer readable afterwards, as an underscore is added to the file extension.

For example, the file looks like this afterwards: `_Invoice No. Invoice No. 1009.pdf_`

Image
Image

### Expected behaviour

The file extension is not destroyed

### How to reproduce

If a prefix such as “Invoice no.” (with a space at the end) is added in the number range and in the invoice document, the PDF file is no longer readable afterwards, as an underscore is added to the file extension.

For example, the file looks like this afterwards: `_Invoice No. Invoice No. 1009.pdf_`

Image
Image

### PR DESCRIPTION
**Pull request by philippdinkhoff**
### 1. Why is this change necessary?
When using document prefixes. The filename can recieve underscores at the beginning and the end, which can lead to unusable file extensions: `_Invoice No. Invoice No. 1009.pdf_`

### 2. What does this change do, exactly?
Filters out the Double and single quotes

### 3. Describe each step to reproduce the issue or behaviour.
Use prefixes in the document and number range settings.
Download a document 
File has underscores at beginning and end.

### 4. Please link to the relevant issues (if any).

- closes #9573 

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

**Review by ennasus4sun — APPROVED** [review]
is it possible to write a test for that case?

**Review by jozsefdamokos — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-document-card/index.js [hunk 1]
```diff
@@ -341,7 +341,7 @@ export default {
                 .getDocument(documentId, documentDeepLink, Shopware.Context.api, true, fileType)
                 .then((response) => {
                     if (response.data) {
-                        const filename = response.headers['content-disposition'].split('filename=')[1];
+                        const filename = response.headers['content-disposition'].match(/filename="?(.*?)"?$/)[1];
```
Comment (MalteJanz) [inline src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-document-card/index.js]: Is the `$` at the end needed, because it shouldn't matter if something else comes after it right?
Also we should do it properly this time and support all possible cases according to spec, e.g. also
```
Content-Disposition: attachment; filename*=UTF-8''file%20name.jpg
```

https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Content-Disposition#syntax

Comment (MalteJanz) [reply src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-document-card/index.js]: Also as @ennasus4sun already mentioned, please write tests for this. You could for example extract this line into it's own method, e.g. `getFilenameFromResponse` and at least test that specific method with multiple different headers in `sw-order-document-card.spec.js`

**Review by MalteJanz — DISMISSED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-document-card/index.js
Comment (MalteJanz) [inline src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-document-card/index.js:1]: Btw, we have another place in our codebase that reads from the `content-disposition` header:

https://github.com/shopware/shopware/blob/e451da58e31bbd615294b1323e666b0a9ac514e4/src/Administration/Resources/app/administration/src/module/sw-bulk-edit/component/sw-bulk-edit-save-modal-success/index.js#L181

So we should fix it there too. Maybe extract a utility method to a service where it makes sense. I'm also wondering how media items are handled and why they don't use this technique 🤔

Comment (philippdinkhoff) [reply src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-document-card/index.js:1]: Just tested this one. Not sure if it's necessary. The filename of the bulk edit is just a UUID (`vrsbgsYhoCQFCzxm0GSdfK40q8RslYyw.pdf`), it seems not needed there, at least that's what I would have thought.

Comment (MalteJanz) [reply src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-document-card/index.js:1]: Doesn't matter if the filename currently is always a UUID. I would still call the same service / function to extract it from the same header (you don't want two slightly different implementations), otherwise we might have bugs again in the future if the filename somehow changes and includes for example spaces

File: src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-document-card/index.js [hunk 2]
```diff
@@ -351,6 +351,21 @@ export default {
...
 
+        getFilenameFromResponse(response) {
+            const header = response.headers['content-disposition'];
+            if (!header) {
+                return null;
+            }
+
+            const filenameStarMatch = header.match(/filename\*=UTF-8''([^;]+)/);
+            if (filenameStarMatch) {
+                return decodeURIComponent(filenameStarMatch[1]);
```
Comment (MalteJanz) [inline src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-document-card/index.js]: Not sure if the extra decode is needed here 🤔 
https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/a#download
As far as I understand that it uses it as the real filesystem filename, but it also mentions that it would use the value of the `content-dispotition` if that is available 😕 .

Maybe test with a filename that contains an emoji or something 🤷‍♂️

File: src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-document-card/sw-order-document-card.spec.js [hunk 3]
```diff
@@ -248,6 +248,34 @@ describe('src/module/sw-order/component/sw-order-document-card', () => {
         setActivePinia(createPinia());
     });
 
+    it('Should test filename extraction from content-disposition header', async () => {
+        wrapper = await createWrapper();
+
+        let response = {
+            headers: {
+                'content-disposition': 'attachment; filename="normal-filename.pdf"',
```
Comment (MalteJanz) [inline src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-document-card/sw-order-document-card.spec.js]: this case would have a space in the real world right? otherwise the quotes are not needed / added
```suggestion
                'content-disposition': 'attachment; filename="normal filename.pdf"',
```

File: src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-document-card/index.js (hunk 2 above)
Comment (philippdinkhoff) [reply src/Administration/Resources/app/administration/src/module/sw-order/component/sw-order-document-card/index.js]: Yeah, also works without the decode

File: src/Administration/Resources/app/administration/src/module/sw-bulk-edit/component/sw-bulk-edit-save-modal-success/index.js [hunk 4]
```diff
@@ -178,7 +179,8 @@ export default {
                         return;
                     }
 
-                    const filename = response.headers['content-disposition'].split('filename=')[1];
+                    const contentDisposition = response.headers['content-disposition'];
+                    const filename = fileReaderUtils.getFilenameFromResponse(contentDisposition);
```
Comment (MalteJanz) [inline src/Administration/Resources/app/administration/src/module/sw-bulk-edit/component/sw-bulk-edit-save-modal-success/index.js]: Small nitpick: the function name is `getFilenameFromResponse` but it takes in just a string of a header. I would suggest changing the signature to take in the full response, then you don't have to look up which header to pass into this function and it's much easier to use

**Review by DennisGarding — APPROVED** [review]
