### PR TITLE
fix: overwrite of deepLinkCode on order recalculation

### LINKED ISSUE #9571: Changing an order via the admin overwrites its deep link code
### Shopware Version

6.4.18.1 - 6.7.0.0

### Affected area / extension

Platform(Default)

### Actual behaviour

When editing an order via the admin and a recalculation is performed, the deep link code gets replaced by the `CartTransformer`

### Expected behaviour

The deep link code is not overwritten by the `CartTransformer` during a recalculation.

### How to reproduce

- Place an order
- Confirm that the deep link is working
- Add a product to an existing order
- Confirm that the deep link is no longer working

### PR DESCRIPTION
**Pull request by mstegmeyer**
### 1. Why is this change necessary?
When recalculating an order, the deepLinkCode, with which a customer can access his order should stay the same.

### 2. What does this change do, exactly?
Not overwrite the deepLinkCode.

### 3. Describe each step to reproduce the issue or behaviour.
- Place an order
- Confirm that the deep link is working
- Add a product to an existing order
- Confirm that the deep link is still working

### 4. Please link to the relevant issues (if any).
fixes #9571 

### 5. Checklist

- [X] I have written tests and verified that they fail without my change
- [X] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [X] This change has comments for package types, values, functions, and non-obvious lines of code
- [X] I have read the contribution requirements and fulfill them.

### CODE REVIEW

File: src/Core/Checkout/Cart/Order/OrderConversionContext.php [hunk 1]
```diff
@@ -16,8 +17,13 @@ class OrderConversionContext extends Struct
 
     protected bool $includeTransactions = true;
 
+    /**
+     * @deprecated tag:v6.8.0 - will be removed, use `includePersistentData` instead
+     */
     protected bool $includeOrderDate = true;
 
+    protected bool $includePersistentData = true;
```
Comment (cyl3x) [inline src/Core/Checkout/Cart/Order/OrderConversionContext.php:28]: Not sure if that name is a good description. If we cannot find a better name, I propose adding a comment

File: src/Core/Checkout/Cart/Order/OrderConversionContext.php [hunk 2]
```diff
@@ -66,14 +72,44 @@ public function setIncludeTransactions(bool $includeTransactions): OrderConversi
...
+     */
     public function setIncludeOrderDate(bool $includeOrderDate): OrderConversionContext
     {
+        Feature::triggerDeprecationOrThrow(
+            'v6.8.0',
+            'The method "OrderConversionContext::setIncludeOrderDate" is deprecated and will be removed in v6.8.0. Use "setIncludePersistentData" instead.'
+        );
+
         $this->includeOrderDate = $includeOrderDate;
+        $this->includePersistentData = $includeOrderDate;
```
Comment (En0Ma1259) [inline src/Core/Checkout/Cart/Order/OrderConversionContext.php:102]: Is this working with
`$object->set('includeOrderDate', $data);`
`$object->assign(['includeOrderDate' => $data]);`

File: src/Core/Checkout/Cart/Order/OrderConversionContext.php (hunk 1 above)
Comment (mstegmeyer) [reply src/Core/Checkout/Cart/Order/OrderConversionContext.php:28]: any opinions, @Bird87ZA @lernhart ?

File: src/Core/Checkout/Cart/Order/OrderConversionContext.php (hunk 2 above)
Comment (mstegmeyer) [reply src/Core/Checkout/Cart/Order/OrderConversionContext.php:102]: fixed it for assign, we don't implement the magic `__set` function.

File: src/Core/Checkout/Cart/Order/OrderConversionContext.php (hunk 1 above)
Comment (Bird87ZA) [reply src/Core/Checkout/Cart/Order/OrderConversionContext.php:28]: I also can't come up with a less confusing name. I would have gone for `includeDataThatShouldNotBeChangedAfterTheFirstWriteButForSomeReasonNowHasToBe`, but that would have given @cyl3x a stroke.

**Review by Bird87ZA — APPROVED** [review]

File: src/Core/Checkout/Cart/Order/OrderConversionContext.php (hunk 1 above)
Comment (Bird87ZA) [reply src/Core/Checkout/Cart/Order/OrderConversionContext.php:28]: How about `ImmutableData` ?

I'm taking the credit for that, Max

File: src/Core/Checkout/Cart/Order/OrderConversionContext.php [hunk 3]
```diff
@@ -2,9 +2,13 @@
 
 namespace Shopware\Core\Checkout\Cart\Order;
 
+use Shopware\Core\Framework\Feature;
 use Shopware\Core\Framework\Log\Package;
 use Shopware\Core\Framework\Struct\Struct;
 
+/**
+ * @codeCoverageIgnore
+ */
```
Comment (lernhart) [inline src/Core/Checkout/Cart/Order/OrderConversionContext.php:11]: Is this necessary? Structs are ignored globally

File: src/Core/Checkout/Cart/Order/OrderConversionContext.php (hunk 1 above)
Comment (lernhart) [reply src/Core/Checkout/Cart/Order/OrderConversionContext.php:28]: I hate the `shouldInclude` naming scheme

Maybe sth. like `preserveMetadata`?

**Review by lernhart — CHANGES_REQUESTED** [review]

File: src/Core/Checkout/Cart/Order/OrderConversionContext.php (hunk 3 above)
Comment (mstegmeyer) [reply src/Core/Checkout/Cart/Order/OrderConversionContext.php:11]: Files ending in `Struct.php` are ignored, but therefore not a `OrderConversionContext`.

File: src/Core/Checkout/Cart/Order/OrderConversionContext.php (hunk 1 above)
Comment (mstegmeyer) [reply src/Core/Checkout/Cart/Order/OrderConversionContext.php:28]: Metadata is also a good option, yes. Is your issue with the `should` or the `include`? Because I think, include is more fitting than preserve. Preserve would imply for me that stuff is being protected, but it's simply not included in the array in the `CartTransformer`.

Comment (mstegmeyer) [reply src/Core/Checkout/Cart/Order/OrderConversionContext.php:28]: internal poll in our team channel says `includePersistentData`. So no change.

**Review by lernhart — APPROVED** [review]

**Review by cyl3x — APPROVED** [review]
