### PR TITLE
fix: sales channel name translations in mail templates

### LINKED ISSUE #1715: Default mail templates: Nearly all do not use fallback chain for sales channel name in subjects and for sender and maybe content
**Description**  
Nearly all mail templates currently use `salesChannel.name` in subjects and for senders. However, it should be `salesChannel.translated.name` to correctly use the fallback chain. 
Maybe also an issue in the content of the templates but I did not check. Might also be the case for payment method / shipping method names.

**Possible Solution**  
Adjust default mail templates to use language fallback chain for sales channel name.

Not sure, what to do about existing mail templates. Maybe replace salesChannel.name with salesChannel.translated.name or just ignore it.

### PR DESCRIPTION
**Pull request by DennisGarding**
closes: #1715 

Replaces all `{{ salesChannel.name }}` with `{{ salesChannel.translated.name }}` in mail templates

`salesChannel.name` contains the value set directly in the current language.

`salesChannel.translated.name` contains the inherited (fallback) value if no specific value exists for the current language.

If a value is null, the system searches for an existing value along the language hierarchy (e.g. AT → DE → EN).

Therefore, `salesChannel.name`  and `salesChannel.translated.name`  may differ.

In the storefront/sales channel context, `salesChannel.translated.name`  should always be used, as fallbacks are expected there.

### CODE REVIEW

File: tests/migration/SalesChannelTranslatedNameTest.php [hunk 1]
```diff
@@ -0,0 +1,111 @@
...
+
+        $message = 'Do not use the twig tag "{{ salesChannel.name }}" for mail templates and it translations. Use "{{ salesChannel.translated.name }}" instead.';
+        foreach ($result as $file) {
+            $message .= \PHP_EOL . $file;
+        }
+
+        static::assertCount(0, $result, $message);
+    }
+
+    private function findFiles(string $baseDirectory): \Iterator
```
Comment (jozsefdamokos) [inline tests/migration/SalesChannelTranslatedNameTest.php]: maybe a better name would be `findFilesWithIncorrectTwigTag` or something similar, more descriptive

File: tests/migration/SalesChannelTranslatedNameTest.php [hunk 2]
```diff
@@ -0,0 +1,111 @@
...
+    public function testMigrationFiles(): void
+    {
+        $fileSystem = new Filesystem();
+
+        $baseDirectory = realpath(__DIR__ . '/../../src/Core/Migration');
+        static::assertIsString($baseDirectory);
+        static::assertDirectoryExists($baseDirectory);
+
+        $result = \json_decode(
+            $fileSystem->readFile(__DIR__ . '/SalesChannelTranslatedNameResult.json'),
```
Comment (jozsefdamokos) [inline tests/migration/SalesChannelTranslatedNameTest.php:65]: A constant wouldn't be enough? Maybe instead of `$result` call it `$allowedFiles`

File: tests/migration/SalesChannelTranslatedNameTest.php [hunk 3]
```diff
@@ -0,0 +1,111 @@
...
+        $files = $this->findFiles($baseDirectory);
+
+        foreach ($files as $file) {
+            static::assertInstanceOf(SplFileInfo::class, $file);
+            $fileList[] = $file->getFilename();
+        }
+
+        $fileList = \array_values(array_unique($fileList));
+        // to ensure find the allowed 22 files. (Old migrations)
+        static::assertGreaterThanOrEqual(22, \count($fileList));
```
Comment (jozsefdamokos) [inline tests/migration/SalesChannelTranslatedNameTest.php:81]: If it's only the 22 old migrations should be allowed to contain it then the assertion should be `assertSame`

**Review by jozsefdamokos — APPROVED** [review]

File: tests/migration/SalesChannelTranslatedNameTest.php (hunk 3 above)
Comment (DennisGarding) [reply tests/migration/SalesChannelTranslatedNameTest.php:81]: It can be greater, because this test is for preventing other people from introducing new false salesChannel.name translations

File: tests/migration/SalesChannelTranslatedNameTest.php (hunk 2 above)
Comment (DennisGarding) [reply tests/migration/SalesChannelTranslatedNameTest.php:65]: In the end it is the result because I removed files that were contained here and add files that are new. 

This "result" i analyze.

File: src/Core/Migration/V6_7/Migration1773815272SalesChannelNameTranslation.php [hunk 4]
```diff
@@ -0,0 +1,94 @@
...
+SQL;
+        $mailTemplateIds = $connection->fetchFirstColumn($sql);
+
+        $sql = <<<SQL
+SELECT mail_template_id, language_id, sender_name, subject, content_html, content_plain
+FROM mail_template_translation
+WHERE mail_template_id IN (:mailTemplateIds)
+SQL;
+
+        return $connection->fetchAllAssociative($sql, ['mailTemplateIds' => $mailTemplateIds], ['mailTemplateIds' => ArrayParameterType::BINARY]);
```
Comment (larskemper) [inline src/Core/Migration/V6_7/Migration1773815272SalesChannelNameTranslation.php]: we cloud also do that in one query `SELECT ... FROM mail_template_translation INNER JOIN mail_template ...`

**Review by larskemper — APPROVED** [review]

File: tests/migration/SalesChannelTranslatedNameTest.php (hunk 3 above)
Comment (jozsefdamokos) [reply tests/migration/SalesChannelTranslatedNameTest.php:81]: These 22 files can have `salesChannel.name` inside them and no further files should have it, right? Then I dont get why we would allow greater than 22 here 🤔

Comment (DennisGarding) [reply tests/migration/SalesChannelTranslatedNameTest.php:81]: Yes, these 22 files can have it, but the test is not at the end here. Also, this is not the main test case. This is just a counter test to ensure the 22 files are found. After that comes the code that is important for this test. And if i test here for equals, the test will fail at this point and the user will not know which file caught the error

**Review by jozsefdamokos — APPROVED** [review]
