### PR TITLE
fix: restore muted tests for NotificationController

### LINKED ISSUE #12950: Fix test cases in NotificationControllerTest
### Technical TODO

See https://github.com/shopware/shopware/pull/12940

### PR DESCRIPTION
**Pull request by nfortier-shopware**
### 1. Why is this change necessary?
During the restoration of some tests in integration, https://github.com/shopware/shopware/pull/12940 2 cases were constantly failing and muted. We should not let this indefinitely.

Those tests were failing from the start, but initially not run in the pipeline (the PR was created before the check about missing integration folder was in place), except in the nightly after merge.

The proposed fix relies on the expectation that these 2 tests cases are described correctly.

### 2. What does this change do, exactly?
- (first commit) Restores the 2 cases of integration initially written

It fails https://github.com/shopware/shopware/actions/runs/20968616813/job/60265744627 showing we need to adjust how we are dealing with the request

- (second commit) Enforces json_decode through getPayload() from Request, since the tests are sending a json encoded string

https://github.com/shopware/shopware/blob/de33b0b2d89c6cfb6d1259ac42abbd2216779658/tests/integration/Core/Framework/Notification/Api/NotificationControllerTest.php#L69-L72

while
https://github.com/shopware/shopware/blob/de33b0b2d89c6cfb6d1259ac42abbd2216779658/src/Core/Framework/Notification/Api/NotificationController.php#L50-L52

It was not decoded, then always null, and converted to empty string which would make those tests fail (like in the first commit).

### 3. Describe each step to reproduce the issue or behaviour.
Run the integration & unit tests related to NotificationController

### 4. Please link to the relevant issues (if any).
- closes https://github.com/shopware/shopware/issues/12950

### 5. Checklist

- [X] I have written tests and verified that they fail without my change
- [ ] I have updated developer-facing release notes if this change is **relevant** for external developers:
  - Add a short entry to `RELEASE_INFO-6.<major>.md` under “Upcoming” for informational changes, including the consequences of the change and how it affects external developers.
  - Add an `UPGRADE` section in `UPGRADE-6.<next-major>.md` for breaking changes (what/why/impact/how to adapt).
  - See the [Documenting a Release Process](https://github.com/shopware/shopware/blob/trunk/delivery-process/documenting-a-release.md) for details.
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

**Review by AydinHassan — APPROVED** [review]

File: src/Core/Framework/Notification/Api/NotificationController.php [hunk 1]
```diff
@@ -47,12 +47,14 @@ public function __construct(
     )]
     public function saveNotification(Request $request, Context $context): Response
     {
-        $status = (string) $request->request->get('status');
```
Comment (mitelg) [inline src/Core/Framework/Notification/Api/NotificationController.php:50]: I could not find usage of this route, but is that a break, if we now only consider the JSON payload instead of request body? :thinking:

Comment (nfortier-shopware) [reply src/Core/Framework/Notification/Api/NotificationController.php:50]: It is the request content, json encoded => see https://github.com/symfony/symfony/blob/7.4/src/Symfony/Component/HttpFoundation/Request.php#L1584-L1595

```
    public function getPayload(): InputBag
    {
        if ($this->request->count()) {
            return clone $this->request;
        }

        if ('' === $content = $this->getContent()) {
            return new InputBag([]);
        }

        try {
            $content = json_decode($content, true, 512, \JSON_BIGINT_AS_STRING | \JSON_THROW_ON_ERROR);
```

Comment (nfortier-shopware) [reply src/Core/Framework/Notification/Api/NotificationController.php:50]: also it's even stated 

> Request body parameters ($_POST).
See also:
getPayload() for portability between content types

https://github.com/symfony/symfony/blob/7.4/src/Symfony/Component/HttpFoundation/Request.php#L96-L101

So I guess this is not really breaking change

Comment (mitelg) [reply src/Core/Framework/Notification/Api/NotificationController.php:50]: I see, didn't check that on my own. sorry!

File: src/Core/Framework/Notification/Api/NotificationController.php [hunk 2]
```diff
@@ -47,12 +47,14 @@ public function __construct(
...
-        $message = (string) $request->request->get('message');
-        $adminOnly = (bool) $request->request->get('adminOnly', false);
+        $payload = $request->getPayload();
+
+        $status = (string) $payload->get('status');
+        $message = (string) $payload->get('message');
+        $adminOnly = (bool) $payload->get('adminOnly', false);
```
Comment (mitelg) [inline src/Core/Framework/Notification/Api/NotificationController.php]:
```suggestion
        $status = $payload->getString('status');
        $message = $payload->getString('message');
        $adminOnly = $payload->getBoolean('adminOnly');
```

**Review by mitelg — APPROVED** [review]

**Review by mitelg — APPROVED** [review]
