### PR TITLE
fix: prevent float steps for integer custom fields

### LINKED ISSUE #14690: CustomField of numberType int can have a float step value assigned
### Shopware Version

6.7.7.0

### Affected area / extension

Platform(Default)

### Actual behaviour

{"id":"019c23f4411877cf91e696ecdea221ed","config":{"componentName":"sw-field","type":"number","numberType":"int","max":20,"min":0,"step":0.13,"label":{"en-GB":"number"},"helpText":{"en-GB":null},"placeholder":{"en-GB":null},"customFieldType":"number","customFieldPosition":1}}

This breaks the function of the arrows up and down in the input field, e.g. in the rule builder.

Image

Image

### Expected behaviour

Only int values for step if numberType is int.

### How to reproduce

In the Administration, create a custom field with the type number and set the numberType to int and step to e.g. 0.1.

### PR DESCRIPTION
**Pull request by davidtraum**
### 1. Why is this change necessary?

As reported in https://github.com/shopware/shopware/issues/14690, it is possible to set a float number as the step width for integer custom fields.

### 2. What does this change do, exactly?

- The values for max, min, and step are rounded when the field type is changed from float to int  
- The prop `numberType` for the step-width input field is set

### 3. Describe each step to reproduce the issue or behaviour.

1. Create a number custom field of type integer and set the step width to 0.1  
2. The step arrow buttons won’t work when using the custom field

### 4. Please link to the relevant issues (if any).

Closes https://github.com/shopware/shopware/issues/14690

### CODE REVIEW

File: src/Administration/Resources/app/administration/src/module/sw-settings-custom-field/component/sw-custom-field-type-number/index.js [hunk 1]
```diff
@@ -27,9 +27,27 @@ export default {
...
+        },
+    },
+
     watch: {
         'currentCustomField.config.numberType'(value) {
             this.currentCustomField.type = value;
+
+            if (value === 'int') {
+                if (this.currentCustomField.config.step != null) {
+                    this.currentCustomField.config.step = Math.round(this.currentCustomField.config.step);
```
[the remark this answers is not in the document]
Comment (davidtraum) [reply src/Administration/Resources/app/administration/src/module/sw-settings-custom-field/component/sw-custom-field-type-number/index.js]: Added clamping for the rounded value.

File: src/Administration/Resources/app/administration/src/module/sw-settings-custom-field/component/sw-custom-field-type-number/sw-custom-field-type-number.html.twig [hunk 2]
```diff
@@ -18,20 +18,29 @@
     <mt-number-field
         v-model="currentCustomField.config.step"
         :label="$tc('sw-settings-custom-field.customField.detail.labelStep')"
+        :number-type="isIntField ? 'int' : 'float'"
```
Comment (mitelg) [inline src/Administration/Resources/app/administration/src/module/sw-settings-custom-field/component/sw-custom-field-type-number/sw-custom-field-type-number.html.twig]: instead of repeating the "calculation" three times, couldn't we introduce computed properties also for these?

Comment (davidtraum) [reply src/Administration/Resources/app/administration/src/module/sw-settings-custom-field/component/sw-custom-field-type-number/sw-custom-field-type-number.html.twig]: Thanks, thats indeed an duplicate expression. The numberType value is now used directly from currentCustomField.config.

File: src/Administration/Resources/app/administration/src/module/sw-settings-custom-field/component/sw-custom-field-type-number/index.js [hunk 3]
```diff
@@ -27,9 +27,28 @@ export default {
...
+            return this.currentCustomField.config.numberType === 'int';
+        },
+    },
+
     watch: {
         'currentCustomField.config.numberType'(value) {
             this.currentCustomField.type = value;
+
+            if (value === 'int') {
+                if (this.currentCustomField.config.step != null) {
```
Comment (gweiermann) [inline src/Administration/Resources/app/administration/src/module/sw-settings-custom-field/component/sw-custom-field-type-number/index.js]: I don't feel comfortable with a loose equality check. If you explicitly want to use `!=` instead of `!==` to also implicitly check for `undefined`, I would like to have an explanatory comment, a more verbose check or just `!==`.

**Review by gweiermann — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-settings-custom-field/component/sw-custom-field-type-number/index.js (hunk 3 above)
Comment (davidtraum) [reply src/Administration/Resources/app/administration/src/module/sw-settings-custom-field/component/sw-custom-field-type-number/index.js]: Thanks, I have added two explicit checks instead of using !=.

**Review by jleifeld — APPROVED** [review]
