### PR TITLE
fix: Handle duplicate custom field set names

### LINKED ISSUE #10738: App update custom field: Integrity constraint violation
### Shopware Version

6.7.0.0

### Affected area / extension

Platform(Default)

### Actual behaviour

```
Exception trace:
  at /var/www/html/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:24
 Doctrine\DBAL\Driver\PDO\Exception::new() at /var/www/html/vendor/doctrine/dbal/src/Driver/PDO/Statement.php:57
 Doctrine\DBAL\Driver\PDO\Statement->execute() at /var/www/html/vendor/doctrine/dbal/src/Connection.php:882
 Doctrine\DBAL\Connection->executeStatement() at /var/www/html/vendor/shopware/platform/src/Core/Framework/DataAbstractionLayer/Doctrine/MultiInsertQueryQueue.php:76
 Shopware\Core\Framework\DataAbstractionLayer\Doctrine\MultiInsertQueryQueue->Shopware\Core\Framework\DataAbstractionLayer\Doctrine\{closure}() at /var/www/html/vendor/doctrine/dbal/src/Connection.php:941
 Doctrine\DBAL\Connection->transactional() at /var/www/html/vendor/shopware/platform/src/Core/Framework/DataAbstractionLayer/Doctrine/RetryableTransaction.php:45
 Shopware\Core\Framework\DataAbstractionLayer\Doctrine\RetryableTransaction::retry() at /var/www/html/vendor/shopware/platform/src/Core/Framework/DataAbstractionLayer/Doctrine/RetryableTransaction.php:31
 Shopware\Core\Framework\DataAbstractionLayer\Doctrine\RetryableTransaction::retryable() at /var/www/html/vendor/shopware/platform/src/Core/Framework/DataAbstractionLayer/Doctrine/MultiInsertQueryQueue.php:74
 Shopware\Core\Framework\DataAbstractionLayer\Doctrine\MultiInsertQueryQueue->execute() at /var/www/html/vendor/shopware/platform/src/Core/Framework/DataAbstractionLayer/Dbal/EntityWriteGateway.php:149
 Shopware\Core\Framework\DataAbstractionLayer\Dbal\EntityWriteGateway->Shopware\Core\Framework\DataAbstractionLayer\Dbal\{closure}() at /var/www/html/vendor/shopware/platform/src/Core/Framework/DataAbstractionLayer/Dbal/EntityWriteGateway.php:161
 Shopware\Core\Framework\DataAbstractionLayer\Dbal\EntityWriteGateway->executeCommands() at /var/www/html/vendor/shopware/platform/src/Core/Framework/DataAbstractionLayer/Dbal/EntityWriteGateway.php:110
 Shopware\Core\Framework\DataAbstractionLayer\Dbal\EntityWriteGateway->Shopware\Core\Framework\DataAbstractionLayer\Dbal\{closure}() at /var/www/html/vendor/doctrine/dbal/src/Connection.php:941
 Doctrine\DBAL\Connection->transactional() at /var/www/html/vendor/shopware/platform/src/Core/Framework/DataAbstractionLayer/Doctrine/RetryableTransaction.php:45
 Shopware\Core\Framework\DataAbstractionLayer\Doctrine\RetryableTransaction::retry() at /var/www/html/vendor/shopware/platform/src/Core/Framework/DataAbstractionLayer/Doctrine/RetryableTransaction.php:31
 Shopware\Core\Framework\DataAbstractionLayer\Doctrine\RetryableTransaction::retryable() at /var/www/html/vendor/shopware/platform/src/Core/Framework/DataAbstractionLayer/Dbal/EntityWriteGateway.php:109
 Shopware\Core\Framework\DataAbstractionLayer\Dbal\EntityWriteGateway->execute() at /var/www/html/vendor/shopware/platform/src/Core/Framework/DataAbstractionLayer/Write/EntityWriter.php:204
 Shopware\Core\Framework\DataAbstractionLayer\Write\EntityWriter->write() at /var/www/html/vendor/shopware/platform/src/Core/Framework/DataAbstractionLayer/Write/EntityWriter.php:129
 Shopware\Core\Framework\DataAbstractionLayer\Write\EntityWriter->upsert() at /var/www/html/vendor/shopware/platform/src/Core/Framework/DataAbstractionLayer/VersionManager.php:86
 Shopware\Core\Framework\DataAbstractionLayer\VersionManager->upsert() at /var/www/html/vendor/shopware/platform/src/Core/Framework/DataAbstractionLayer/EntityRepository.php:110
 Shopware\Core\Framework\DataAbstractionLayer\EntityRepository->upsert() at /var/www/html/vendor/shopware/platform/src/Core/Framework/App/Lifecycle/Persister/CustomFieldPersister.php:111
 Shopware\Core\Framework\App\Lifecycle\Persister\CustomFieldPersister->upsertCustomFieldSets() at /var/www/html/vendor/shopware/platform/src/Core/Framework/App/Lifecycle/Persister/CustomFieldPersister.php:44
 Shopware\Core\Framework\App\Lifecycle\Persister\CustomFieldPersister->Shopware\Core\Framework\App\Lifecycle\Persister\{closure}() at /var/www/html/vendor/shopware/platform/src/Core/Framework/Context.php:199
 Shopware\Core\Framework\Context->scope() at /var/www/html/vendor/shopware/platform/src/Core/Framework/App/Lifecycle/Persister/CustomFieldPersister.php:43
 Shopware\Core\Framework\App\Lifecycle\Persister\CustomFieldPersister->updateCustomFields() at /var/www/html/vendor/shopware/platform/src/Core/Framework/App/Lifecycle/AppLifecycle.php:298
 Shopware\Core\Framework\App\Lifecycle\AppLifecycle->updateApp() at /var/www/html/vendor/shopware/platform/src/Core/Framework/App/Lifecycle/AppLifecycle.php:167
 Shopware\Core\Framework\App\Lifecycle\AppLifecycle->update() at /var/www/html/vendor/swag/saas-rufus/src/Core/Framework/App/Lifecycle/Update/AppUpdater.php:131
 Swag\SaasRufus\Core\Framework\App\Lifecycle\Update\AppUpdater->doUpdateApp() at /var/www/html/vendor/swag/saas-rufus/src/Core/Framework/App/Lifecycle/Update/AppUpdater.php:68
 Swag\SaasRufus\Core\Framework\App\Lifecycle\Update\AppUpdater->updateApps() at /var/www/html/src/Command/AppUpdateCommand.php:33
 Shopware\Production\Command\AppUpdateCommand->execute() at /var/www/html/vendor/symfony/console/Command/Command.php:279
 Symfony\Component\Console\Command\Command->run() at /var/www/html/vendor/symfony/console/Application.php:1094
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/vendor/symfony/framework-bundle/Console/Application.php:123
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/html/vendor/symfony/console/Application.php:342
 Symfony\Component\Console\Application->doRun() at /var/www/html/vendor/symfony/framework-bundle/Console/Application.php:77
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/html/vendor/symfony/console/Application.php:193
 Symfony\Component\Console\Application->run() at /var/www/html/bin/console:84

In Statement.php line 55:
                                                                               
  [PDOException (23000)]                                                       
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'twt_  
  clean_cloud_custom_field__category__hero_section' for key 'custom_field.uni  
  q.custom_field.name'                                                                                                  
                                 
```

The issue only occurs during app update, the initial install works since there the custom_field is not present.

@keulinho did an initial investigation: The app had mistakenly created 2 custom field sets with the same names in the manifest, installing the app works, but the app can no longer be updated once the broken version was installed.

### Expected behaviour

App update works as expected, duplicated custom field sets are prevented in the first place.

### How to reproduce

Issue was discovered on Shopware SaaS during 6.6->6.7 migration

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by keulinho**
When custom field set names are duplicated the initial install works, but the later update fails

with https://github.com/shopware/shopware/pull/10772 that is not possible anymore, however we need to offer a way forward when a broken app was already installed

### CODE REVIEW

File: src/Core/Framework/App/Lifecycle/Persister/CustomFieldPersister.php [hunk 1]
```diff
@@ -47,13 +47,27 @@ public function updateCustomFields(Manifest $manifest, string $appId, Context $c
...
+            ['appId' => Uuid::fromHexToBytes($appId)]
         );
 
+        $groupedByName = [];
+        foreach ($allCustomFields as $id => $name) {
+            $groupedByName[$name][] = Uuid::fromBytesToHex($id);
+        }
+
+        $existingCustomFieldSets = [];
+        foreach ($groupedByName as $name => $ids) {
```
Comment (keulinho) [inline src/Core/Framework/App/Lifecycle/Persister/CustomFieldPersister.php:61]: i didn't find a more elegant solution without the double loop, if you have any ideas how to improve please let me know

**Review by shyim — APPROVED** [review]

File: src/Core/Framework/App/Lifecycle/Persister/CustomFieldPersister.php (hunk 1 above)
Comment (mitelg) [reply src/Core/Framework/App/Lifecycle/Persister/CustomFieldPersister.php:61]: instead of `fetchAllKeyValue` just `fetchAllAssociative` and iterate over that list?

**Review by mitelg — APPROVED** [review]

File: src/Core/Framework/App/Lifecycle/Persister/CustomFieldPersister.php (hunk 1 above)
Comment (keulinho) [reply src/Core/Framework/App/Lifecycle/Persister/CustomFieldPersister.php:61]: i still would need a double loop right?
