### PR TITLE
fix: align flow names with event names

### LINKED ISSUE #13150: Wrong name for Transaction Flows
### Shopware Version

6.4.*

### Affected area / extension

Platform(Default)

### Actual behaviour

public const AUTHORIZED_FLOW = 'Order enters status authorized';
public const CHARGEBACK_FLOW = 'Order enters status chargeback';
public const UNCONFIRMED_FLOW = 'Order enters status unconfirmed';

are used for state_enter.order_transaction.state.xxx

Since this is a transaction, naming must be "Payment enters ...".

This wrong naming might occur in other translations as well. 

/Core/Migration/V6_5/Migration1689257577AddMissingTransactionMailFlow.php

### Expected behaviour

Payment enters ...

### How to reproduce

Image

### PR DESCRIPTION
**Pull request by larskemper**
resolves https://github.com/shopware/shopware/issues/13150

### Changes

- "Order enters status authorized" => "Payment enters status authorized"
- "Order enters status chargeback" => "Payment enters status chargeback"
- "Order enters status unconfirmed" => "Payment enters status unconfirmed"

### CODE REVIEW

**Review by jozsefdamokos — APPROVED** [review]

File: src/Core/Migration/V6_7/Migration1773647849AlignFlowNameWithEventName.php [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+    {
+        foreach (self::FLOW_TRANSLATION_MAPPING as $eventName => $data) {
+            $this->updateFlowName($connection, $eventName, $data);
+        }
+
+        $this->registerIndexer($connection, 'flow.indexer');
+    }
+
+    /**
+     * @param array<string, mixed> $data
```
Comment (MalteJanz) [inline src/Core/Migration/V6_7/Migration1773647849AlignFlowNameWithEventName.php]: You can be more specific here and define the actual array shape

```suggestion
     * @param array{old: string, new: string} $data
```

File: src/Core/Migration/V6_7/Migration1773647849AlignFlowNameWithEventName.php [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+            ->fetchOne();
+
+        if (!$flowId) {
+            return;
+        }
+
+        $connection->update(
+            'flow',
+            ['name' => $data['new']],
+            ['id' => $flowId]
```
Comment (MalteJanz) [inline src/Core/Migration/V6_7/Migration1773647849AlignFlowNameWithEventName.php]: There is no need to fetch the flow first. You can just do an update with the given criteria of `name` + `eventName`

**Review by MalteJanz — CHANGES_REQUESTED** [review]

File: src/Core/Migration/V6_7/Migration1773647849AlignFlowNameWithEventName.php (hunk 2 above)
Comment (larskemper) [reply src/Core/Migration/V6_7/Migration1773647849AlignFlowNameWithEventName.php]: true 🏃

**Review by MalteJanz — APPROVED** [review]
