### PR TITLE
fix: preserve customer context on order creation in the Administration area

### LINKED ISSUE #14213: Creating an order via Admin loses context upon repeated attempts
### Shopware Version

6.7.5.1

### Affected area / extension

Platform(Default)

### Actual behaviour

When creating an order from a specific customer account, under specific circumstances Shopware does not get that customer as a context for the order.

### Expected behaviour

When creating an order with a customer account selected, the order should always be for that customer. If we wanted to create an order for another customer, we'd either do it via their account OR in the Order overview of Shopware 6.

### How to reproduce

- Have environment with multiple customers and orders spread across them
- Go to Customer overview -> Pick a customer
- Go to Orders tab -> Create new order
- Abort back to Dashboard
- Go to Customer overview -> Pick a DIFFERENT customer
- Orders tab -> Create new order

At this point, Shopware lost the context of the newly selected customer. We get a list of ALL customers and often the one we wanted to create the order for is the only one missing.

### PR DESCRIPTION
**Pull request by Aliaaaam**
### 1. Why is this change necessary?
Because the Administration loses the selected customer context after aborting order creation or refreshing the customer page, which can lead to creating orders for the wrong customer.

### 2. What does this change do, exactly?
It ensures the currently selected customer is always preserved when starting a new order from the customer’s orders tab or after refreshing the customer page.

### 3. Describe each step to reproduce the issue or behaviour
Scenario 1:
1. Open Customer A → Orders -> Add order
2. Abort and return to Dashboard
3. Open Customer B -> Orders -> Add order
4. The customer context is lost instead of preselecting Customer B

Scenario 2:
1. Open Customer A -> Orders -> Add order
2. Refresh the page multiple times
3. After several attempts, the customer context is lost

### 4. Please link to the relevant issues
- Fixes https://github.com/shopware/shopware/issues/14213

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [ ] I have updated developer-facing release notes if this change is **relevant** for external developers:
  - Add a short entry to `RELEASE_INFO-6.<major>.md` under “Upcoming” for informational changes, including the consequences of the change and how it affects external developers.
  - Add an `UPGRADE` section in `UPGRADE-6.<next-major>.md` for breaking changes (what/why/impact/how to adapt).
  - See the [Documenting a Release Process](https://github.com/shopware/shopware/blob/trunk/delivery-process/documenting-a-release.md) for details.
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [x] I have read the contribution requirements and fulfilled them

### CODE REVIEW

**Review by En0Ma1259 — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-order/view/sw-order-create-initial/index.js [hunk 1]
```diff
@@ -43,14 +49,21 @@ export default {
...
             }
 
-            const customer = await this.customerRepository.get(customerId, Shopware.Context.api, this.customerCriteria);
-            if (customer) {
-                Store.get('swOrder').setCustomer(customer);
+            try {
+                const customer = await this.customerRepository.get(customerId, Shopware.Context.api, this.customerCriteria);
+                if (customer) orderStore.setCustomer(customer);
+            } finally {
+                this.routeCustomerReady = true;
```
Comment (cyl3x) [inline src/Administration/Resources/app/administration/src/module/sw-order/view/sw-order-create-initial/index.js:66]: if the customer does not exist (so the get fails) should the modal really be opened?

Comment (Aliaaaam) [reply src/Administration/Resources/app/administration/src/module/sw-order/view/sw-order-create-initial/index.js:66]: The modal remains open anyway, but you have the option to select the customer.
It behaves like the initial version, I just introduced this flag to control the `sw-loader` inside the modal.

**Review by cyl3x — APPROVED** [review]
