### PR TITLE
fix: RetryableTransaction is not retrying on deadlocks

### LINKED ISSUE #9024: RetryableTransaction does not retry when Deadlock occurs in transaction because the error is hidden by a Savepoint error
### Shopware Version

6.7.0.0-rc3

### Affected area / extension

Platform(Default)

### Actual behaviour

Currently in DBAL a DeadlockException is lost when happening in a transaction with savepoints and covert by a DriverException with the Message `SAVEPOINT DOCTRINE_X does not exist` (see [here](https://github.com/doctrine/dbal/issues/6651) and [here](https://github.com/doctrine/dbal/issues/4279)).

A deadlock could also be the reason for the error in https://github.com/shopware/shopware/issues/7892.

Because a DriverException is not retryable this error is not handled in RetryableTransaction and no retry is tried.

### Expected behaviour

Closure gets retried up to 10 times when a deadlock occurs even when the deadlock is covered up.

### How to reproduce

Force a deadlock in any code that uses the `RetryableTransaction` like the `EntityWriteGateway`.

Maybe this helps in reproducing https://github.com/shopware/shopware/issues/7892 too.

### PR DESCRIPTION
**Pull request by h1k3r**
### 1. Why is this change necessary?

See https://github.com/shopware/shopware/issues/9024

### 2. What does this change do, exactly?

Added processing of additional exceptions to `RetryableTransaction::retryable`. Added code uses reflection to reset `\Doctrine\DBAL\Connection::$transactionNestingLevel` on transactions rolled back by MySQL.

**The change must be rolled back after fix in Doctrine.**

### 3. Describe each step to reproduce the issue or behaviour.

See referenced issue.

Also you can use this reproducer https://github.com/h1k3r/dbal-deadlock-repro.

### 4. Please link to the relevant issues (if any).
- closes https://github.com/shopware/shopware/issues/9024
- relates https://github.com/doctrine/dbal/issues/6651, https://github.com/doctrine/dbal/issues/4279

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfill them.

### 6. Sequence diagram
One of isolated scenarios looks like this:

```mermaid
sequenceDiagram
    participant uc as User code
    participant rt as RetryableTransaction
    participant c as Closure
    participant dbal as DBAL
    participant db as MySQL

    uc-)rt: retry(Closure)
    loop 10 times
        rt-)dbal: beginTransaction()
        activate dbal
        dbal--)dbal: transactionNestingLevel++
        dbal-)db: beginTransaction
        db-)dbal: 
        dbal-)rt: 
        deactivate dbal 
        rt-)c: run
        

        # nested transaction is started in closure
        c-)dbal: beginTransaction()
        activate dbal
        dbal--)dbal: transactionNestingLevel++
        dbal-)db: createSavePoint
        db-)dbal: 
        dbal-)c: 
        deactivate dbal 

        # closure executes query leading to deadlock
        c-)dbal: executeQuery
        activate dbal 
        dbal-)db: executeQuery()
        db--)db: deadlock detected & rollback
        Note right of dbal: whole transaction was rolled back, system <br> should call send rollBack command to db once
        db-)dbal: deadlock error
        dbal-)rt: Deadlock exception 
        deactivate dbal 


        rt-)dbal: rollBack()
        activate dbal
        dbal--)dbal: transactionNestingLevel--
        Note right of dbal: wrong counter leads to savepoint rollbak
        dbal-)db: rollbackToSavepoint
        db-)dbal: savepoint does not exist error
        dbal-)rt: Doctrine\DBAL\Exception\DriverException (savepoint)
        deactivate dbal 
    end
```

### CODE REVIEW

**Review by keulinho — APPROVED** [review]

File: tests/unit/Core/Framework/DataAbstractionLayer/Doctrine/RetryableTransactionTest.php [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+
+        $e = null;
+        try {
+            RetryableTransaction::retryable($connection, $f);
+            /** @phpstan-ignore catch.neverThrown (exceptions are thrown in passed closure) */
+        } catch (\Throwable $e) {
+        }
+
+        static::assertInstanceOf(RetryableException::class, $e);
+        static::assertEquals(11, $counter);
```
Comment (mitelg) [inline tests/unit/Core/Framework/DataAbstractionLayer/Doctrine/RetryableTransactionTest.php]:
```suggestion
        static::assertSame(11, $counter);
```

**Review by mitelg — APPROVED** [review]
looks good so far, but just one question: what would happen, if the issue is fixed on DBAL side? would your code still work, or is it broken again?

**Comment by h1k3r** [comment]
> looks good so far, but just one question: what would happen, if the issue is fixed on DBAL side? would your code still work, or is it broken again?

@mitelg the fix in doctrine should do less or more similar thing. If I did not miss anything - code should work, if I did - it can break.

In the best case it should be covered by proper integration test, so we would detect failure early. I was not able to create stable enough test that will work using pcntl_fork. [The test I wrote](https://gist.github.com/h1k3r/d74a56413b218c0e81abf2c37ad3b3d4) is creating deadlock, but loses connection afterwards. Unfortunately I was not able to fix this problem in the reasonable time. Any help appreciated :)
