### PR TITLE
fix: load the env var for admin path redirect

### LINKED ISSUE #14604: Shopware Installer ignores changed administration path
### Shopware Version

6.7.6.2

### Affected area / extension

Platform(Default)

### Actual behaviour

When a shop has changed the path of the administration via the env variable `SHOPWARE_ADMINISTRATION_PATH_NAME`, clicking on the “Open Administration” button at the end of the updater will redirect the user to /admin anyway, returning a 404 error.

### Expected behaviour

Clicking on the button would open the administration at the correct URL

### How to reproduce

- Set up shop on 6.7.6.1
- Add `SHOPWARE_ADMINISTRATION_PATH_NAME=backend` to the .env.local and clear the cache
- Log in to the new /backend path
- Start the updater in the settings to upgrade to 6.7.6.2
- When finished, click on “Open Administration”, observe the wrong redirect

### PR DESCRIPTION
**Pull request by zukucker**
### 1. Why is this change necessary?
The updater redirect a user to a 404 if they have set an ADMINISTRATION_PATH via the .env.local file

### 2. What does this change do, exactly?
The finish controller now keeps track of the env variable if it is set. Or uses the fallback to 'admin'

### 3. Describe each step to reproduce the issue or behaviour.
Set up shop on 6.7.6.1
Add SHOPWARE_ADMINISTRATION_PATH_NAME=backend to the .env.local and clear the cache
Log in to the new /backend path
Start the updater in the settings to upgrade to 6.7.6.2
When finished, click on “Open Administration”, observe the wrong redirect

### 4. Please link to the relevant issues (if any).
- closes #14604 

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have updated developer-facing release notes if this change is **relevant** for external developers:
  - Add a short entry to `RELEASE_INFO-6.<major>.md` under “Upcoming” for informational changes, including the consequences of the change and how it affects external developers.
  - Add an `UPGRADE` section in `UPGRADE-6.<next-major>.md` for breaking changes (what/why/impact/how to adapt).
  - See the [Documenting a Release Process](https://github.com/shopware/shopware/blob/trunk/delivery-process/documenting-a-release.md) for details.
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

**Review by mitelg — APPROVED** [review]

**Review by mitelg — CHANGES_REQUESTED** [review]
I know there is none for this class by now, but would be cool, if you could add a unit test for your changes.

**Comment by zukucker** [comment]
Hey @mitelg , thank you. Will do that asap

**Comment by zukucker** [comment]
Hey  @mitelg , I tried my best. It's my first unit test from scratch. Please let me know what I can do better

**Review by mitelg — APPROVED** [review]
looks good so far :+1: 

I will let the pipeline run and see what pops up, that might need a fix

**Comment by shyim** [comment]
Can we rather deprecate this env? It's fake security it does not help at all, as the api is still accessible at same endpoint.

**Comment by mitelg** [comment]
@shyim I am not sure, if this is about "improving" security :thinking: it is just about having it under another URL available :man_shrugging:

**Comment by mitelg** [comment]
@zukucker please fix the code style and PHPStan issues

**Comment by mitelg** [comment]
@zukucker do you still want to work on this?

File: tests/unit/Core/Installer/Controller/FinishControllerTest.php [hunk 1]
```diff
@@ -0,0 +1,162 @@
...
+        $this->systemLocker = $this->createMock(SystemLocker::class);
+    }
+
+    public function testFinishWithCompletedParameterRendersTemplate(): void
+    {
+        $controller = $this->getMockBuilder(FinishController::class)
+            ->setConstructorArgs([
+                $this->systemLocker,
+                new Client(),
+                'https://example.com',
```
Comment (nfortier-shopware) [inline tests/unit/Core/Installer/Controller/FinishControllerTest.php]: Though we won't reach the url, it is safer to use 'https://www.shopware.com', as we have had some surprises in the past (mainly with integration tests 🙈)

And so on for every usages of this url in the suite

**Review by nfortier-shopware — APPROVED** [review]

**Review by nfortier-shopware — APPROVED** [review]

**Comment by mitelg** [comment]
thanks for your contribution @zukucker 👍🎉💙
