### PR TITLE
fix: refresh cms sidebar navigation after resize

### LINKED ISSUE #15304: ProductListLayout visual test is flaky with viewport resizing
### Shopware Version

trunk

### Affected area / extension

Platform(Default)

### Actual behaviour

Tab indicator does not appear (unless page is refreshed) if the original viewport is scaled up

https://github.com/user-attachments/assets/a8e790d8-1b31-4ea3-8c69-bed38e16c725

### Expected behaviour

Tab indicator is always visible when the side tabs become visible, without the need to refresh the browser.

### How to reproduce

The problem is that Playwright uses a [smaller viewport](https://playwright.dev/docs/api/class-testoptions#test-options-viewport) by default, which is then scaled up to our needs.

Open the admin
Set viewport to 1400px width
Refresh browser
Go to the Shopping Experiences main page
Set viewport to 1440px width

### PR DESCRIPTION
**Pull request by MartinKrzykawski**
fixes https://github.com/shopware/shopware/issues/15304

## 1. Why is this change necessary?

  The CMS detail sidebar can lose its active navigation state after the viewport changes from a width where the sidebar is hidden to one where it becomes visible again.

  This made the original issue reproducible in production and also affected the previous visual test, which relied on a broader and less deterministic flow through the listing and creation pages. That test mixed
  multiple UI states and picked up unrelated instability.

  ## 2. What does this change do, exactly?

  This change updates the administration sidebar handling so the CMS sidebar navigation is recalculated on resize and keeps the active state visible after the sidebar becomes visible again.

  It also adds a focused sidebar unit test for the resize behavior.

  On the acceptance side, the visual test was rewritten to cover the actual resize scenario directly on the CMS detail page. Instead of going through the listing and creation flow, it now creates a deterministic
  `product_list` layout through the API, opens the detail page directly in the smaller viewport, resizes to the desktop width, and captures the relevant sidebar states there.

  As part of that rewrite, the obsolete listing and creation screenshots were removed from the visual coverage because they were not part of the production bug and introduced unnecessary instability.

  ## 3. Describe each change in more detail

  - `sw-sidebar` now listens to resize events and refreshes its navigation rendering when the viewport changes.
  - Sidebar offset propagation is recalculated through a dedicated helper instead of only during the initial mount.
  - A unit test was added to verify that an active sidebar navigation item stays active after a resize.
  - The acceptance visual test now uses API-created data and direct navigation to the CMS detail page.
  - The acceptance flow was reduced to the stable detail-page screenshots that actually represent the reported issue.

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have updated developer-facing release notes if this change is **relevant** for external developers:
  - Add a short entry to `RELEASE_INFO-6.<major>.md` under “Upcoming” for informational changes, including the consequences of the change and how it affects external developers.
  - Add an `UPGRADE` section in `UPGRADE-6.<next-major>.md` for breaking changes (what/why/impact/how to adapt).
  - See the [Documenting a Release Process](https://github.com/shopware/shopware/blob/trunk/delivery-process/documenting-a-release.md) for details.
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Administration/Resources/app/administration/src/app/component/sidebar/sw-sidebar/index.js [hunk 1]
```diff
@@ -125,6 +131,24 @@ export default {
...
+        onResize() {
+            this.resizeNavigationKey += 1;
+
+            if (this.propagateWidth) {
+                this.updateSidebarOffset();
+            }
+        },
+
+        updateSidebarOffset() {
+            const sidebarWidth = this.$el.querySelector('.sw-sidebar__navigation')?.offsetWidth;
```
Comment (marcelbrode) [inline src/Administration/Resources/app/administration/src/app/component/sidebar/sw-sidebar/index.js:143]: Tinkering with the DOM, here using querySelector, is always something which should let your bytie-sense tingling.

Since Vue uses a ShadowDOM, interacting with the real DOM can lead to unwanted side effects. Since you only read, not write, it's okay I guess. But if you have means to get these infos by otherwise, that would always be better.

You'll get my approve anyway, but I'd appreciate another look 🙂

**Review by marcelbrode — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/app/component/sidebar/sw-sidebar/index.js (hunk 1 above)
Comment (MartinKrzykawski) [reply src/Administration/Resources/app/administration/src/app/component/sidebar/sw-sidebar/index.js:143]: The general concern is fair, but Vue does not use Shadow DOM here. Since we only read layout, this is safe :)

**Review by ravenokko — APPROVED** [review]

File: tests/acceptance/tests/Visual/Administration/Themes.spec.ts-snapshots/Themes-Detail-Visual-linux.png
Comment (ravenokko) [inline tests/acceptance/tests/Visual/Administration/Themes.spec.ts-snapshots/Themes-Detail-Visual-linux.png:1]: The updated snapshot is missing the thumbnails in the sidebar, remove it.

**Review by ravenokko — CHANGES_REQUESTED** [review]

**Review by ravenokko — APPROVED** [review]
