### PR TITLE
fix: Special Characters "/" in Search Not Working Even When Added as …

### LINKED ISSUE #13179: Special Characters "/" in Search Not Working Even When Added as Preserved Characters in Config File
### Shopware Version

6.7.3.0

### Affected area / extension

Platform(Default)

### Actual behaviour

The search results do not include expected matches that contain the "/" character, indicating that it is not being preserved or processed correctly.

### Expected behaviour

The search should correctly interpret and return results that include the "/" character as specified in the query.

### How to reproduce

1. Navigate to the search bar on our Shopware storefront.
2. Enter a search query that includes the "/" character (e.g., "product/123").
3. Observe that the search results do not include expected items that should match the query.

### PR DESCRIPTION
**Pull request by tamvt**
This pull request addresses an issue where special characters such as `/` and ` were not correctly handled in search tokenization, even when specified as preserved characters in the configuration file. The main change is an update to the `tokenize` method to ensure these characters are properly preserved, along with new unit tests to verify the fix.

Core functionality improvements:

* Updated the `tokenize` method in `Shopware\Core\Framework\DataAbstractionLayer\Search\Term\Tokenizer` to correctly handle special characters like `/` and `This pull request addresses an issue where special characters such as `/` and ` were not correctly handled in search tokenization, even when specified as preserved characters in the configuration file. The main change is an update to the `tokenize` method to ensure these characters are properly preserved, along with new unit tests to verify the fix.

Core functionality improvements:

 when they are listed as preserved characters in the config file. [[1]](diffhunk://#diff-3c170598ae59507e4cb67513522eee26a2f1d5671b2ecd473b4aa1f24a9191b0R1-R6) [[2]](diffhunk://#diff-a3cdab2d5909472e49840bf324a75c079a72901809eb63c1d94ff1063a353283L36)

### CODE REVIEW

**Review by nguyenytran — APPROVED** [review]

File: tests/unit/Core/Framework/DataAbstractionLayer/Search/Term/TokenizerTest.php [hunk 1]
```diff
@@ -69,6 +69,11 @@ public static function cases(): array
                 ['synergistic', 'copper', 'dm.10000', 'face@master'],
                 ['.', '@'],
             ],
+            'text with allowed chars "/"' => [
```
Comment (mitelg) [inline tests/unit/Core/Framework/DataAbstractionLayer/Search/Term/TokenizerTest.php:72]: will `/` still be removed if not explicitly configured? can you add a test for this case, too?

to ensure, the default behaviour stays the same.

ah should be covered by `text with special chars` test case. maybe you can add the backslash additionally.

File: changelog/_unreleased/2025-10-26-special-characters-in-search-not-working-even-when-added-as-preserved-characters-in-config-file.md [hunk 2]
```diff
@@ -0,0 +1,6 @@
+---
+title: Special Characters / in Search Not Working Even When Added as Preserved Characters in Config File
+issue: 13179
+---
+# Core
+* Changed `tokenize` method in `Shopware\Core\Framework\DataAbstractionLayer\Search\Term\Tokenizer` to properly handle special characters such as `/`, `\`, etc., when they are specified as preserved characters in the configuration file.
```
Comment (mitelg) [inline changelog/_unreleased/2025-10-26-special-characters-in-search-not-working-even-when-added-as-preserved-characters-in-config-file.md]:
```suggestion
* Changed `tokenize` method in `Shopware\Core\Framework\DataAbstractionLayer\Search\Term\Tokenizer` to properly handle special characters `/` and `\`, when they are specified as preserved characters in the configuration file.
```

why "etc"? :sweat_smile: no other chars are allowed now, right?

File: changelog/_unreleased/2025-10-26-special-characters-in-search-not-working-even-when-added-as-preserved-characters-in-config-file.md [hunk 3]
```diff
@@ -0,0 +1,6 @@
+---
+title: Special Characters / in Search Not Working Even When Added as Preserved Characters in Config File
```
Comment (mitelg) [inline changelog/_unreleased/2025-10-26-special-characters-in-search-not-working-even-when-added-as-preserved-characters-in-config-file.md]:
```suggestion
title: Slash and backslash are now working correctly in search if configured as preserved characters
```

**Review by mitelg — COMMENTED** [review]
would you mind signing the CLA? :grin: 

and also the PR title should be adjusted, as it would be the commit message

**Review by vienthuong — APPROVED** [review]
