### PR TITLE
fix: Elasticsearch Admin search does not find search terms with more than 5 characters

### LINKED ISSUE #12274: Elasticsearch Admin search does not find search terms with more than 5 characters
### Shopware Version

6.7.2.0

### Affected area / extension

Platform(Default)

### Actual behaviour

Since 6.7.2.0 the administration cannot find search terms with more than 5 characters anymore:

Image

Image

The storefront search does not seem to be impacted

### Expected behaviour

The search would work as in previous releases

### How to reproduce

- Set up a new shop on 6.7.2.0 or upgrade an existing one with Demodata 
- Make sure the .env contains a valid opensearch configuration like:

```
OPENSEARCH_URL=http://localhost:10003
SHOPWARE_ES_ENABLED="1"
SHOPWARE_ES_INDEXING_ENABLED="1"
SHOPWARE_ES_INDEX_PREFIX="estest"
SHOPWARE_ES_THROW_EXCEPTION=1

ADMIN_OPENSEARCH_URL=http://localhost:10003
SHOPWARE_ADMIN_ES_ENABLED=1
SHOPWARE_ADMIN_ES_REFRESH_INDICES=1
SHOPWARE_ADMIN_ES_INDEX_PREFIX=estest-admin
```

- Reset the index and start indexing:

```
bin/console es:admin:reset
bin/console es:admin:index --no-queue
```

- Search in the administration, once your search term reaches more than 5 characters, there will be no results.

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by tamvt**
This pull request enhances the admin Elasticsearch search functionality by introducing n-gram subfields for improved partial and numeric matching, and updates the search logic and tests accordingly. The main improvements include adding n-gram subfields to the index mappings, updating search queries to leverage these subfields, and providing robust detection and handling of n-gram capabilities in both code and tests.

**Index mapping and search improvements:**

* Added `ngram` subfields to both `text` and `textBoosted` properties in the Elasticsearch index mappings, enabling more effective partial and fuzzy matching. [[1]](diffhunk://#diff-a064faf259b0d781b728139a3821770d7db9196b4e3a718c4133a9e98c284f80L452-L454) [[2]](diffhunk://#diff-a6f8d4708e758d14a67b54185f70ac6e4112350b735cc26392b9d8da5ea49c67L112-R124) [[3]](diffhunk://#diff-a6f8d4708e758d14a67b54185f70ac6e4112350b735cc26392b9d8da5ea49c67L153-R193) [[4]](diffhunk://#diff-2f2df9f48bd41efbc4bd6540432bedf42bfb2afd5691c6f1101474fbeb646ee2L107-R200)
* Introduced the `hasNgramSubfields` method in `AdminSearchRegistry` to detect if an index mapping includes `ngram` subfields, allowing the search logic to dynamically adapt based on index capabilities.

**Search logic enhancements:**

* Updated the search construction in `AdminSearcher` and `ProductAdminSearchIndexer` to use `ngram` subfields when available, improving search results for partial and numeric queries. This includes special handling for numeric search terms to use exact and wildcard matching without fuzziness. [[1]](diffhunk://#diff-0fe294a7d08df3e27d0baa510709df3be76d75e2491b52debb6fce75d745dd17L60-R63) [[2]](diffhunk://#diff-0fe294a7d08df3e27d0baa510709df3be76d75e2491b52debb6fce75d745dd17L110-R172) [[3]](diffhunk://#diff-07029d5963c28b7be1ebef29dad17628f32c746896c8dc42c8e09c89ee73695aL101-R138)
* Modified the `globalCriteria` method signatures to accept a `hasNgramSubfields` parameter, propagating n-gram awareness through the search pipeline. [[1]](diffhunk://#diff-2b9c91d8842c81b0fbd3e415a309ccae0bb240f78105c15627f7723d4fd527ebL58-R58) [[2]](diffhunk://#diff-07029d5963c28b7be1ebef29dad17628f32c746896c8dc42c8e09c89ee73695aL101-R138)

https://github.com/user-attachments/assets/5818ebce-ad63-498b-b109-56285dd74cf5

### CODE REVIEW

File: src/Elasticsearch/Admin/AdminSearcher.php [hunk 1]
```diff
@@ -107,24 +109,64 @@ public function search(string $term, array $entities, Context $context, int $lim
...
+        if ($indexName !== null) {
+            $hasNgramSubfields = $this->registry->hasNgramSubfields($indexName);
         }
 
-        $query = new SimpleQueryStringQuery($term, [
-            'fields' => ['text'],
-        ]);
+        $isNumericSearch = $this->isNumericSearch($term);
+
+        if ($hasNgramSubfields) {
```
Comment (nguyenytran) [inline src/Elasticsearch/Admin/AdminSearcher.php]:
```suggestion
        $search->setSize($limit);
        
        $fields = ['text'];
        if ($hasNgramSubfields) {
           $fields[] = 'text.ngram'
        }
        
        if (!isNumericSearch) {
             if (preg_match('/^[\p{L}0-9]+$/u', $lastPart)) {
                $term .= '*';
            }
            
            $query = new SimpleQueryStringQuery($term, [
                'fields' => $fields,
            ]);

            $search->addQuery($query, BoolQuery::SHOULD);
                       
            return $search;
        }
        
        foreach ($fields as $field) {
                $matchQuery = new MatchQuery($field, $term, [
                    'fuzziness' => 0,
                    'operator' => 'or', // Use 'or' to match any token containing the numeric value
                ]);
                $search->addQuery($matchQuery, BoolQuery::SHOULD);

                // Wildcard query to match numeric substrings (e.g., "*3800*" matches "X3800")
                $wildcardQuery = new WildcardQuery($field, '*' . $term . '*', [
                    'boost' => 0.8,
                ]);
                $search->addQuery($wildcardQuery, BoolQuery::SHOULD);
            }
            
        return $search;
```

**Review by nguyenytran — APPROVED** [review]

**Review by vienthuong — APPROVED** [review]
