### PR TITLE
fix(customerGroup): listing of seo urls mapped to a customer group form

### LINKED ISSUE #10192: The custom sign-up form URL input only has a path. It does not have a completed URL
### Shopware Version

6.7

### Affected area / extension

Platform(Default)

### Actual behaviour

The input only includes the path, for example, '/Test-title'.

### Expected behaviour

Full url for example: `https://sguder-explo-66-reference.swstage.store/test` like in 6.6 and not only `/Test-title`

### How to reproduce

1. Go to Settings > Customer Groups.
2. Add a new customer group with a custom signup from.
3. Scroll down to the URL card.
4. Select an available storefront.
5. Check the URL in the input field.

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by bschulzebaek**
### 4. Please link to the relevant issues (if any).
- closes #10192 

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfill them.

### CODE REVIEW

**Review by MartinKrzykawski — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-settings-customer-group/page/sw-settings-customer-group-detail/index.js [hunk 1]
```diff
@@ -142,7 +180,7 @@ export default {
         },
 
         technicalUrl() {
-            return `${domainPlaceholderId}/customer-group-registration/${this.customerGroupId}#`;
+            return `<domain-url>/customer-group-registration/${this.customerGroupId}#`;
```
Comment (marcelbrode) [inline src/Administration/Resources/app/administration/src/module/sw-settings-customer-group/page/sw-settings-customer-group-detail/index.js:183]: Being curious: Will this be replaced somewhere else now?

File: src/Administration/Resources/app/administration/src/module/sw-settings-customer-group/snippet/de-DE.json [hunk 2]
```diff
@@ -37,7 +37,8 @@
       "technicalUrlHelpText": "Technische URLs können als \"benutzerdefinierte Links\" im Kategorienmodul verwendet werden. Die Sprachauswahl erfolgt dabei automatisch.",
       "availabilitySalesChannel": "Verfügbare Verkaufskanäle",
       "infoText": "Shop-Benutzer können sich über dieses Formular registrieren. Die Benutzer werden der Kundengruppe erst zugewiesen, wenn Du die Anfrage im Kundenmodul angenommen hast. Das Formular kann mit den untenstehenden Feldern angepasst werden.",
-      "seoUrlLabel": "{salesChannelName} - URL"
+      "seoUrlLabel": "{salesChannelName} URL ({languageName})",
+      "domainBanner": "SEO URLs werden für jede Domain aufgelistet, die pro Verkaufskanal konfiguriert ist."
```
Comment (marcelbrode) [inline src/Administration/Resources/app/administration/src/module/sw-settings-customer-group/snippet/de-DE.json]:
```suggestion
      "domainBanner": "SEO-URLs werden für jede Domain aufgelistet, die pro Verkaufskanal konfiguriert ist."
```

**Review by marcelbrode — CHANGES_REQUESTED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-settings-customer-group/page/sw-settings-customer-group-detail/index.js (hunk 1 above)
Comment (bschulzebaek) [reply src/Administration/Resources/app/administration/src/module/sw-settings-customer-group/page/sw-settings-customer-group-detail/index.js:183]: image

Nope, it's just a visual placeholder, the previous ID didn't make any sense since you'd copy it with the rest ond wouldn't understand why the URL as a whole doesn't point anywhere.

Comment (marcelbrode) [reply src/Administration/Resources/app/administration/src/module/sw-settings-customer-group/page/sw-settings-customer-group-detail/index.js:183]: Lol, weird decision. Nice to know, thanks 👍

**Review by marcelbrode — APPROVED** [review]
