### PR TITLE
fix: promotion discount advanced prices responsitivity

### LINKED ISSUE #10987: 6.7.0.1: Discount value can no longer be adjusted correctly
### Shopware Version

6.7.0.1

### Affected area / extension

Platform(Default)

### Actual behaviour

If you create a new discount promotion and want to change the value, it always jumps back to the previous value after saving.

F.e:
0.01 to 10 = back to 0.01
0.01 to 15 = 15
15 to 10 = back to 15
15 to 10 = 10

### Expected behaviour

.

### How to reproduce

Create a discount and try to change the discount value

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by mstegmeyer**
### 1. Why is this change necessary?
The recent introduction of a debounce function made saving values impossible, when the field was still in focus when hitting save.

### 2. What does this change do, exactly?
Remove debounce function (not important, as there are no big calculations or irritating behavior).
Also cleaned up the duplicate calculation code.

### 3. Describe each step to reproduce the issue or behaviour.
- Create a promotion with a discount and a value.
- Save it.
- Edit the value and then hit save without previously defocusing the value field.

### 4. Please link to the relevant issues (if any).
closes #10987 

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Administration/Resources/app/administration/src/module/sw-promotion-v2/component/sw-promotion-discount-component/index.js [hunk 1]
```diff
@@ -468,63 +468,48 @@ export default {
...
-                .filter((price) => currencyMapping[price.currencyId] !== undefined)
-                .map((price) => {
-                    const setPrice = (basePrice ?? discountHandler.getMinValue()) * currencyMapping[price.currencyId];
-                    price.price = Math.min(setPrice, discountHandler.getMinValue());
-
-                    return price;
-                });
         },
 
-        prepareAdvancedPrices(currency, basePrice) {
```
Comment (En0Ma1259) [inline src/Administration/Resources/app/administration/src/module/sw-promotion-v2/component/sw-promotion-discount-component/index.js:507]: You can't remove this without deprecation? Or does the `@private` allow us to?

Comment (mstegmeyer) [reply src/Administration/Resources/app/administration/src/module/sw-promotion-v2/component/sw-promotion-discount-component/index.js:507]: `@private` should allow this, right, @shopware/product-ct-admin ?

**Review by cyl3x — APPROVED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-promotion-v2/component/sw-promotion-discount-component/index.js (hunk 1 above)
Comment (mstegmeyer) [reply src/Administration/Resources/app/administration/src/module/sw-promotion-v2/component/sw-promotion-discount-component/index.js:507]: I resolve this, as AFAIK `@private` on admin is the same as `@internal` on PHP.

**Review by En0Ma1259 — APPROVED** [review]
