### PR TITLE
fix: include transaction on recalculation

### LINKED ISSUE #13625: Incorrect display when changing payment method and simultaneously adjusting prices
### Shopware Version

6.7.4.2

### Affected area / extension

Shopware(default)

### Actual behaviour

If, during a completed order (prepayment method), the price of an item is changed via the administrator account, and the customer then changes the payment method to PayPal via their account, the correct order value is not displayed in the PayPal window.

In my test, I first ordered three items at €2 each (total €6). Then, the price of one of the items was changed to €1.97 (in the administrator account).

The correct new price (€5.97) was then displayed in the customer's account. However, if the customer then changes the payment method to PayPal via their account, the old price is still displayed in the PayPal window.

Image

Image

### Expected behaviour

.

### How to reproduce

1. Order 3 items at €2 each via prepayment
2. Change the price of one item to €1.97 via admin
3. Change the payment method for this order to PayPal via the customer account
-> Display of the wrong shopping cart total

### PR DESCRIPTION
**Pull request by En0Ma1259**
### 1. Why is this change necessary?
While changing a line item price, the order amount will change, but not the transaction amount

### 2. What does this change do, exactly?
The transaction amount is compared with the order amount when `setPayment` is called. If the amounts differ, a new transaction is created.

### 3. Describe each step to reproduce the issue or behaviour.
Change an order line item price and save the order. No new transaction will be created and the old one will not be updated

### 4. Please link to the relevant issues (if any).
- fixes https://github.com/shopware/shopware/issues/13625

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [ ] I have updated developer-facing release notes if this change is **relevant** for external developers:
  - Add a short entry to `RELEASE_INFO-6.<major>.md` under “Upcoming” for informational changes, including the consequences of the change and how it affects external developers.
  - Add an `UPGRADE` section in `UPGRADE-6.<next-major>.md` for breaking changes (what/why/impact/how to adapt).
  - See the [Documenting a Release Process](https://github.com/shopware/shopware/blob/trunk/delivery-process/documenting-a-release.md) for details.
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

**Review by cyl3x — APPROVED** [review]

File: src/Core/Checkout/Order/SalesChannel/SetPaymentOrderRoute.php [hunk 1]
```diff
@@ -181,6 +182,10 @@ private function tryTransition(OrderEntity $order, string $paymentMethodId, Cont
 
         foreach ($transactions as $transaction) {
             if ($transaction->getPaymentMethodId() === $paymentMethodId && $lastTransaction->getId() === $transaction->getId()) {
+                if ($this->hasChangedAmount($order->getPrice(), $transaction->getAmount())) {
+                    return false;
```
Comment (mstegmeyer) [inline src/Core/Checkout/Order/SalesChannel/SetPaymentOrderRoute.php:186]: There could be an argument, that we try to set the existing migration to `cancelled` and not leave it in whatever state it currently is. WDYT?

At least maybe from some states like `open` or `reminded` 🤔

Comment (cyl3x) [reply src/Core/Checkout/Order/SalesChannel/SetPaymentOrderRoute.php:186]: I think this is better left to the payment handlers :thinking:

**Review by mstegmeyer — APPROVED** [review]

**Review by FlorianKe — APPROVED** [review]
