### PR TITLE
fix: ManyToMany association of inherited associations

### LINKED ISSUE #11878: ManyToMany association fetch too many records
### Shopware Version

6.7

### Affected area / extension

Platform(Default)

### Actual behaviour

Please see the original issue here:

https://github.com/shopware/shopware/issues/11823

We need to address the issue in the DAL and optimize it

### Expected behaviour

Only relevant mapping records are fetched

### How to reproduce

Call an admin api against the product with `properties` association and checking the query from the profiler

### Definition of Done

- [ ] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [ ] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [ ] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by keulinho**
fixes https://github.com/shopware/shopware/issues/11878

I fixed the original issue here https://github.com/shopware/shopware/issues/5328 in a way that loads way too many mapping entries which could have negative performance impacts

in short how it worked before:

for inherited associations we join the many to many to resolve the matching ids
when the association is filtered we do another query on the mapping table to apply filter, sorting etc with a filter on the ids we found in query one, however that let to the following issue:
Take for example the product category association:
We load the product with the category ids in query 1,
the category association is limited, therefore we do another query on the mapping to apply the limit with `WHERE category.id IN (...)` -> 💣  because now we also load stuff for all the products that are associated with that category

the new approach solves it in a way that we don't join the to many on the inital query if it is filtered
and then in query two we join back to the base table and use the `join` column there to resolve the inheritance

### CODE REVIEW

**Review by shyim — APPROVED** [review]

**Review by mitelg — APPROVED** [review]

File: src/Core/Framework/DataAbstractionLayer/Dbal/EntityReader.php [hunk 1]
```diff
@@ -810,8 +819,22 @@ private function loadManyToManyWithCriteria(
...
+                $joinCondition .= ' AND ' . $root . '.' . EntityDefinitionQueryHelper::escape($definition->getEntityName() . '_version_id') . ' = ' . EntityDefinitionQueryHelper::escape($definition->getEntityName()) . '.version_id';
+            }
+            $query->innerJoin(
+                $root,
+                EntityDefinitionQueryHelper::escape($definition->getEntityName()),
+                EntityDefinitionQueryHelper::escape($definition->getEntityName()),
+                $joinCondition
+            );
+
+            $query->andWhere(EntityDefinitionQueryHelper::escape($definition->getEntityName()) . '.id IN (:localIds)');
```
Comment (vienthuong) [inline src/Core/Framework/DataAbstractionLayer/Dbal/EntityReader.php:838]: just trying to understand the logic here, so here the `EntityDefinitionQueryHelper::escape($definition->getEntityName()) . '.id` could be interchangable with `$root . '.' . $localColumn` right?

**Review by vienthuong — APPROVED** [review]

File: src/Core/Framework/DataAbstractionLayer/Dbal/EntityReader.php (hunk 1 above)
Comment (keulinho) [reply src/Core/Framework/DataAbstractionLayer/Dbal/EntityReader.php:838]: no not really, as we also don't join over the id of the product 

`$root` in this case is the mapping table, say `Product_category`, `$localColumn` would be `product_id`. but we don't want to filter by that in the case of inherited associations, because in the case the product has that association inherited only the parent id shows up in the mapping table

therefore we have the `association join columns` in the product that are named like the association itself (and not like the storage name), e.g `categories` column on the `product` table, that column contains the id by which we need to join the association, e.g. parent id in case it is inherited, child id in case it is not

So what we do here is instead (only for inherited associations) of filtering on the local column in the mapping table directly we join the product table of that association join column and filter there for the product id
