### PR TITLE
fix: extension update caching issue

### LINKED ISSUE #8333: Reduce number of extension update checks to SBP
Everytime someone logs into the Shopware 6 admin a request is made to the SBP ([api.shopware.com/swplatform/pluginupdates|http://api.shopware.com/swplatform/pluginupdates]) to check if there are any new available extension updates.

These scenarios are currently known:

* The call is done for every single admin user. So if a 5 employees of a company logging in in the morning we get 5 requests.
* When someone reloads the page via CTRL+R or reopens it.

So please reduce the number of API requests. I cannot give a direct suggestion but here are some first ideas:

* Only 1 request in a specific interval (1 day, 4 hours)
* Only 1 request per shop and not 1 per admin user

If needed, I’m happy to discuss ideas and help from the SBP point of view.

----

In this small excerpt you can see what’s happening on SBP side.

[example.txt](https://github.com/user-attachments/files/19681486/example.txt)

### PR DESCRIPTION
**Pull request by Bird87ZA**
### 1. Why is this change necessary?
Currently the extension refresh is clearing the cache.

### 2. What does this change do, exactly?
It removes the cache clear on the refresh extensions route

### 4. Please link to the relevant issues (if any).

fixes: https://github.com/shopware/shopware/issues/8333

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfill them.

### CODE REVIEW

File: src/Core/Framework/Store/Api/ExtensionStoreActionsController.php [hunk 1]
```diff
@@ -130,6 +130,8 @@ public function uninstallExtension(string $type, string $technicalName, Request
             $context
         );
 
+        $this->cache->delete(StoreClient::EXTENSION_LIST_CACHE);
```
Comment (shyim) [inline src/Core/Framework/Store/Api/ExtensionStoreActionsController.php]: I would subscribe to DAL written event to plugin/app entity and then clear the cache there. it's pretty uggly here and cli commands are not considered

Comment (Bird87ZA) [reply src/Core/Framework/Store/Api/ExtensionStoreActionsController.php]: ok let me have a look at that approach.

**Review by cyl3x — APPROVED** [review]

File: src/Core/Framework/Store/Subscriber/ExtensionChangedSubscriber.php [hunk 2]
```diff
@@ -0,0 +1,33 @@
...
+{
+    public function __construct(
+        private CacheInterface $cache
+    ) {
+    }
+
+    public static function getSubscribedEvents(): array
+    {
+        return [
+            'plugin.written' => 'onExtensionChanged',
```
Comment (mitelg) [inline src/Core/Framework/Store/Subscriber/ExtensionChangedSubscriber.php]: we have this `\Shopware\Core\Framework\Plugin\PluginEvents::PLUGIN_WRITTEN_EVENT` but no equivalent for apps :see_no_evil:

Comment (cyl3x) [reply src/Core/Framework/Store/Subscriber/ExtensionChangedSubscriber.php]: ~~Shouldn't it be a DAL event, always triggering on table updates?~~

Sorry, I misunderstood, I thought you're saying the `app.written` does not exist

Comment (Bird87ZA) [reply src/Core/Framework/Store/Subscriber/ExtensionChangedSubscriber.php]: I will create one. better to have it uniform I think.

Comment (mitelg) [reply src/Core/Framework/Store/Subscriber/ExtensionChangedSubscriber.php]: those are generated events by the DAL in the format `<entity_name>.written`. we introduced those constants in an event class for each entity very early. but didn't forced this with new entities :see_no_evil:

**Review by mitelg — APPROVED** [review]

**Review by shyim — APPROVED** [review]
