### PR TITLE
fix: redis services configuration

### LINKED ISSUE #8152: Redis configuration for number_range causes exception
### PHP Version

8.2.27

### Shopware Version

6.7

### Affected area / extension

Platform(Default)

### Actual behaviour

Configuring number_range redis storage causes 500 error:
```yaml
shopware:
    redis:
        connections:
            ephemeral:
                dsn: 'redis://localhost:6379/1'
            persistent:
                dsn: 'redis://localhost:6379/2'
    number_range:
        increment_storage: "redis"
        config:
            connection: 'persistent'
```

Exception message:
`Redis::__construct(): Argument #1 ($options) must be of type ?array, string given`

### Expected behaviour

To work as documented: https://developer.shopware.com/docs/guides/hosting/performance/number-ranges.html

### How to reproduce

Add configuration above to the config/packages/shopware.yaml, reload the page.

### PR DESCRIPTION
**Pull request by h1k3r**
### 1. Why is this change necessary?

In current version few of Redis-dependent services in service container are misconfigured, which will cause exception when they are accessed.

### 2. What does this change do, exactly?

- Fixes configuration (using factory in container configuration)
- Fixed deprecated configuration parameter in the test.
- Added compiler pass to remove unused redis services for cache invalidation (similar to other redis usages)

### 3. Describe each step to reproduce the issue or behaviour.

See linked issue.

### 4. Please link to the relevant issues (if any).
- closes [8152](https://github.com/shopware/shopware/issues/8152)

### 5. Checklist

- [x] I have written tests and verified that they fail without my change
- [ ] I have created a [changelog file](https://github.com/shopware/shopware/blob/trunk/adr/2020-08-03-implement-new-changelog.md) with all necessary information about my changes
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfill them.

### CODE REVIEW

**Review by keulinho — APPROVED** [review]

**Review by mitelg — APPROVED** [review]

File: src/Core/Framework/DependencyInjection/Configuration.php [hunk 1]
```diff
@@ -404,7 +404,7 @@ private function createCacheSection(): ArrayNodeDefinition
                                     ->defaultValue('mysql')
                                 ->end()
                                 ->scalarNode('connection')
-                                    ->defaultValue(null)
+                                    ->defaultValue('')
```
Comment (h1k3r) [inline src/Core/Framework/DependencyInjection/Configuration.php]: Currently delayed invalidation logic uses mysql by default, related redis services are available in the container, but not initialized. So not specifying connection would work (unless those services are accessed), but cause
container lint problem (as `Shopware\Core\Framework\Adapter\Redis\RedisConnectionProvider` does not support nulls).

In other places we use compiler passes to remove unneeded Redis services. 

**reviewers**, wdyt?

Comment (mitelg) [reply src/Core/Framework/DependencyInjection/Configuration.php]: aren't unused services automatically be removed from the container? :thinking:

Comment (h1k3r) [reply src/Core/Framework/DependencyInjection/Configuration.php]: Not those that marked as public :) I will implement compiler pass

File: tests/integration/Core/Framework/_snapshots/redis_test.yaml [hunk 2]
```diff
@@ -9,7 +9,6 @@ shopware:
     # delayed cache invalidation
     cache:
         invalidation:
-            delay: 1
```
Comment (BrocksiNet) [inline tests/integration/Core/Framework/_snapshots/redis_test.yaml:12]: Why was the delay removed?

File: src/Core/Framework/Adapter/AdapterException.php [hunk 3]
```diff
@@ -278,4 +279,13 @@ public static function duplicateFilesystemFactory(string $type): DuplicateFilesy
             ['type' => $type]
         );
     }
+
+    public static function missingRequiredParameter(string $parameter): self
+    {
+        return new self(
+            Response::HTTP_INTERNAL_SERVER_ERROR,
+            self::MISSING_REQUIRED_PARAMETER,
+            \sprintf('Parameter "%s" is required but not found in the container.', $parameter)
```
Comment (mitelg) [inline src/Core/Framework/Adapter/AdapterException.php]: please use the string replace functionality, we built in. see examples above. this will automatically make the parameter available

File: src/Core/Framework/Adapter/Cache/CacheCompilerPass.php [hunk 4]
```diff
@@ -0,0 +1,31 @@
...
+
+#[Package('framework')]
+class CacheCompilerPass implements CompilerPassInterface
+{
+    public function process(ContainerBuilder $container): void
+    {
+        $storage = $container->getParameter('shopware.cache.invalidation.delay_options.storage');
+
+        switch ($storage) {
+            case 'mysql':
```
Comment (mitelg) [inline src/Core/Framework/Adapter/Cache/CacheCompilerPass.php:18]: do we need constants or an enum for the storage type? or is this the only place? and no other endpoints will be added most likely?

File: src/Core/Framework/Adapter/Command/CacheWatchDelayedCommand.php [hunk 5]
```diff
@@ -45,8 +51,11 @@ protected function execute(InputInterface $input, OutputInterface $output): int
             }
         });
 
-        $before = $this->container
-            ->get('shopware.cache.invalidator.storage.redis_adapter')
+        /** @var \Redis $adapter */
```
Comment (mitelg) [inline src/Core/Framework/Adapter/Command/CacheWatchDelayedCommand.php]: is this var annotation needed? you know, I am allergic to them :sweat_smile:

File: tests/unit/Core/Framework/Adapter/AdapterExceptionTest.php [hunk 6]
```diff
@@ -102,4 +102,12 @@ public function testInvalidArgument(): void
         static::assertSame('test', $exception->getMessage());
         static::assertEmpty($exception->getParameters());
     }
+
+    public function testMissingRequiredParameter(): void
+    {
+        static::expectException(AdapterException::class);
+        static::expectExceptionMessage('Parameter "shopware.cache.invalidation.delay_options.connection" is required but not found in the container.');
+
+        throw AdapterException::missingRequiredParameter('shopware.cache.invalidation.delay_options.connection');
```
Comment (mitelg) [inline tests/unit/Core/Framework/Adapter/AdapterExceptionTest.php]: we should not test the exception by throwing it. see the other tests. but I also already forgot again, what @nfortier-shopware prefers in such cases :see_no_evil:

File: tests/unit/Core/Framework/Adapter/Cache/CacheCompilerPassTest.php [hunk 7]
```diff
@@ -0,0 +1,70 @@
...
+        static::assertFalse($container->hasDefinition('shopware.cache.invalidator.storage.mysql'));
+    }
+
+    public function testProcessRedisNoConnectionConfigured(): void
+    {
+        $container = $this->container;
+        $container->setParameter('shopware.cache.invalidation.delay_options.storage', 'redis');
+        $container->setParameter('shopware.cache.invalidation.delay_options.connection', null); // default value
+
+        self::expectException(AdapterException::class);
```
Comment (mitelg) [inline tests/unit/Core/Framework/Adapter/Cache/CacheCompilerPassTest.php]: we should use `expectExceptionObject`

**Review by mitelg — CHANGES_REQUESTED** [review]

File: tests/unit/Core/Framework/Adapter/Cache/CacheCompilerPassTest.php (hunk 7 above)
Comment (nfortier-shopware) [reply tests/unit/Core/Framework/Adapter/Cache/CacheCompilerPassTest.php]: yes it's way more accurate

File: tests/integration/Core/Framework/_snapshots/redis_test.yaml (hunk 2 above)
Comment (h1k3r) [reply tests/integration/Core/Framework/_snapshots/redis_test.yaml:12]: "As this feature is now active by default the previous shopware.cache.invalidation.delay configuration is [removed](https://github.com/shopware/shopware/blob/trunk/changelog/_unreleased/2025-01-08-add-force-cache-invalidate-header.md)."

File: tests/unit/Core/Framework/Adapter/AdapterExceptionTest.php (hunk 6 above)
Comment (nfortier-shopware) [reply tests/unit/Core/Framework/Adapter/AdapterExceptionTest.php]: We can stick with what was done previously in that file, see testInvalidArgument, testInvalidTemplateSyntax etc.
So we don't throw the exception, we invoke the method and then do assertions on getMessage and all the classic methods of this exception.

This is typically the place to do it, as this test file is really dedicated to the exception itself

File: src/Core/Framework/Adapter/AdapterException.php (hunk 3 above)
Comment (h1k3r) [reply src/Core/Framework/Adapter/AdapterException.php]: Updated, thanks

File: tests/unit/Core/Framework/Adapter/AdapterExceptionTest.php (hunk 6 above)
Comment (h1k3r) [reply tests/unit/Core/Framework/Adapter/AdapterExceptionTest.php]: Fixed, thanks guys. I moved this method from other file the last minute and missed to adjust it to the new location's style 🙈

File: src/Core/Framework/Adapter/Command/CacheWatchDelayedCommand.php (hunk 5 above)
Comment (h1k3r) [reply src/Core/Framework/Adapter/Command/CacheWatchDelayedCommand.php]: In other case phpstan can't detect the class of the service in the container (it's not present in testing container because of newly added compiler pass).

File: src/Core/Framework/Adapter/Cache/CacheCompilerPass.php (hunk 4 above)
Comment (h1k3r) [reply src/Core/Framework/Adapter/Cache/CacheCompilerPass.php:18]: The usages are happening mainly in the container configurations https://github.com/shopware/shopware/blob/trunk/src/Core/Framework/DependencyInjection/cache.xml#L27

We have few [similar cases](https://github.com/search?q=repo%3Ashopware%2Fshopware%20%27redis%27&type=code) in the system though. Not sure that adding something like a class with constants with storage types in the Core namespace makes sense 🤔

**Review by nfortier-shopware — APPROVED** [review]

File: src/Core/Framework/Adapter/Cache/CacheCompilerPass.php (hunk 4 above)
Comment (mitelg) [reply src/Core/Framework/Adapter/Cache/CacheCompilerPass.php:18]: no need probably, all good :+1:

File: src/Core/Framework/Adapter/Command/CacheWatchDelayedCommand.php (hunk 5 above)
Comment (mitelg) [reply src/Core/Framework/Adapter/Command/CacheWatchDelayedCommand.php]: damn PHPStan :grin: 

should we then use the `RedisTypeHint` from the `\Shopware\Core\Framework\Adapter\Cache\RedisConnectionFactory`

**Review by mitelg — APPROVED** [review]

File: src/Core/Framework/Adapter/Command/CacheWatchDelayedCommand.php (hunk 5 above)
Comment (h1k3r) [reply src/Core/Framework/Adapter/Command/CacheWatchDelayedCommand.php]: @mitelg done, looks a bit like overkill, but will show proper error message in case someone configures redis factory to use RedisArray
