### PR TITLE
fix: Fix issue that incorrect navigation to product detail when variant names are similar

### LINKED ISSUE #13974: Incorrect navigation to product detail when variant names are similar
### Shopware Version

6.7.5.0

### Affected area / extension

Platform(Default)

### Actual behaviour

Suppose that a product has several variant names , the variant names are similar. For example:
- Product name: Sport Bottle 
- Variant names: Sport Bottle Green, Sport Bottle Blue, Sport Bottle Red, Sport Bottle Black

From Storefront, when searching with each variant name, the result list cannot return each one of them. As in the attached video, it can only return 2/5 variant names

https://github.com/user-attachments/assets/82ad5f9e-cd88-43c5-85f8-f1af57116f23

**Note**: when variant name is completely different (e.g: red, blue, white) then the search result is correct
Note2: When enable settings "Load product previews on search page" at Settings > Product, then Product name displays instead. However, when click to the product name, it also navigates to incorrect variant (e.g: search Variant3 but display Variant1)

### Expected behaviour

Result list returns correct data if the the variant name matches 100% 

### How to reproduce

1. Create a product then add several variant to this product (- Product name: Sport Bottle _
2. Make sure that each variant has it's own name not link to parent name( - Variant names: Sport Bottle Green, Sport Bottle Blue, Sport Bottle Red, Sport Bottle Black)
3. From Storefront , search for each of variant name as defined in step 2

Result:
Can only return result for Sport Bottle Black and Sport Bottle Blue --> cannot return correct variant for the rest

### PR DESCRIPTION
**Pull request by tamvt**
This pull request introduces a new mechanism to improve product variant selection in listings, specifically ensuring that the best-scored variant from each family is shown when searching via the MySQL route. It also adds comprehensive unit tests to verify this behavior. The most important changes are grouped below:

### Product Listing Logic Enhancements

* Added logic in `ProductListingLoader.php` to swap in the highest-scored variant for each product family when the `core.listing.findBestVariant` system config is enabled and the search is not handled by Elasticsearch. This ensures that the most relevant variant is displayed in search results, rather than an arbitrary one chosen by MySQL's `GROUP BY`.
* Introduced the private methods `swapBestVariants` and `findSiblingFamilies` to handle the selection and scoring of sibling variants, grouping them by their parent product and choosing the best-scored variant per group.

### CODE REVIEW

**Review by ngocblue — APPROVED** [review]
Test Date: 12 Mar 2026
Test Status: **PASSED**
Browser: Chrome, Safari, Firefox

- Can search variant products with exact name when:
+ Disable Elastic Search 
`SHOPWARE_ES_ENABLED=0
SHOPWARE_ES_INDEXING_ENABLED=0`
+ Enable settings "Preview best matching variant for search results" at Settings > Products

https://github.com/user-attachments/assets/9e1b40b4-a2a7-409c-8418-f0f49e646fb4

**Review by rittou — APPROVED** [review]

File: src/Core/Content/Product/SalesChannel/Listing/ProductListingLoader.php [hunk 1]
```diff
@@ -273,7 +273,110 @@ private function resolveIds(Criteria $criteria, SalesChannelContext $context): I
...
+        }
+
+        return $this->swapBestVariants($result, $criteria, $context);
+    }
+
+    /**
+     * MySQL GROUP BY picks an arbitrary variant per displayGroup.
+     * Re-score all sibling variants of the returned families and swap in the best match.
+     */
+    private function swapBestVariants(IdSearchResult $result, Criteria $criteria, SalesChannelContext $context): IdSearchResult
```
Comment (mitelg) [inline src/Core/Content/Product/SalesChannel/Listing/ProductListingLoader.php]: how is the performance if this needs to be called? would be good, if we can see, if the additional queries have some impact of the loading of a listing. 

I also wonder, if we can't handle this while fetching the products directly 🤔

Comment (vienthuong) [reply src/Core/Content/Product/SalesChannel/Listing/ProductListingLoader.php]: It would be hard because we use group by display_group then mysql picks arbitrary row from each group

File: src/Core/Content/Product/SalesChannel/Listing/ProductListingLoader.php [hunk 2]
```diff
@@ -273,7 +273,110 @@ private function resolveIds(Criteria $criteria, SalesChannelContext $context): I
...
 
-        return $this->productRepository->searchIds($criteria, $context);
+        $isSearchRoute = $criteria->hasState(ResolvedCriteriaProductSearchRoute::STATE, ProductSuggestRoute::STATE);
+        $findBestVariant = $isSearchRoute
+            && ($criteria->getQueries() !== [] || $criteria->getTerm() !== null)
+            && $this->systemConfigService->getBool('core.listing.findBestVariant', $context->getSalesChannelId());
+
+        $result = $this->productRepository->searchIds($criteria, $context);
+
+        if (!$findBestVariant || $result->hasState('loaded-by-elastic')) {
```
Comment (vienthuong) [inline src/Core/Content/Product/SalesChannel/Listing/ProductListingLoader.php]: please put a comment here why when `loaded-by-elastic` we don't need to do an extra finding

File: src/Core/Content/Product/SalesChannel/Listing/ProductListingLoader.php [hunk 3]
```diff
@@ -273,7 +273,110 @@ private function resolveIds(Criteria $criteria, SalesChannelContext $context): I
...
+
+        $idToParent = $this->findSiblingFamilies($ids, $context);
+
+        if ($idToParent === []) {
+            return $result;
+        }
+
+        $siblingIds = array_keys($idToParent);
+
+        $scoreCriteria = clone $criteria;
```
Comment (vienthuong) [inline src/Core/Content/Product/SalesChannel/Listing/ProductListingLoader.php]:
```suggestion
        $scoreCriteria = $criteria->cloneForRead($idToParent);
```

File: src/Core/Content/Product/SalesChannel/Listing/ProductListingLoader.php [hunk 4]
```diff
@@ -273,7 +273,110 @@ private function resolveIds(Criteria $criteria, SalesChannelContext $context): I
...
+        $scoreCriteria->resetGroupFields();
+        $scoreCriteria->setIds($siblingIds);
+        $scoreCriteria->setLimit(\count($siblingIds));
```
Comment (vienthuong) [inline src/Core/Content/Product/SalesChannel/Listing/ProductListingLoader.php]:
```suggestion
        $scoreCriteria->setLimit(null);
```

File: src/Core/Content/Product/SalesChannel/Listing/ProductListingLoader.php [hunk 5]
```diff
@@ -273,7 +273,110 @@ private function resolveIds(Criteria $criteria, SalesChannelContext $context): I
...
+
+        if ($idToParent === []) {
+            return $result;
+        }
+
+        $siblingIds = array_keys($idToParent);
+
+        $scoreCriteria = clone $criteria;
+        $scoreCriteria->resetGroupFields();
+        $scoreCriteria->setIds($siblingIds);
```
Comment (vienthuong) [inline src/Core/Content/Product/SalesChannel/Listing/ProductListingLoader.php]:
```suggestion
```

File: src/Core/Content/Product/SalesChannel/Listing/ProductListingLoader.php [hunk 6]
```diff
@@ -273,7 +273,110 @@ private function resolveIds(Criteria $criteria, SalesChannelContext $context): I
...
+        $scoreCriteria->setLimit(\count($siblingIds));
+        $scoreCriteria->setOffset(0);
```
Comment (vienthuong) [inline src/Core/Content/Product/SalesChannel/Listing/ProductListingLoader.php]:
```suggestion
        $scoreCriteria->setOffset(null);
```

File: src/Core/Content/Product/SalesChannel/Listing/ProductListingLoader.php [hunk 7]
```diff
@@ -273,7 +273,110 @@ private function resolveIds(Criteria $criteria, SalesChannelContext $context): I
...
+            return [];
+        }
+
+        $siblings = $this->connection->fetchAllAssociative(
+            '# product-listing-loader::find-sibling-variants
+            SELECT LOWER(HEX(id)) as id,
+                   LOWER(HEX(parent_id)) as parentId
+            FROM product
+            WHERE version_id = :version
+              AND parent_id IN (:parentIds)',
```
Comment (vienthuong) [inline src/Core/Content/Product/SalesChannel/Listing/ProductListingLoader.php]: please combine these two queries into one (using sub query), you fetchAllKeyValue to have a mapping

File: src/Core/Content/Product/SalesChannel/Listing/ProductListingLoader.php [hunk 8]
```diff
@@ -273,7 +273,110 @@ private function resolveIds(Criteria $criteria, SalesChannelContext $context): I
...
+        $scoreCriteria->setIds($siblingIds);
+        $scoreCriteria->setLimit(\count($siblingIds));
+        $scoreCriteria->setOffset(0);
+
+        $scoredResult = $this->productRepository->searchIds($scoreCriteria, $context);
+        $scoredResultIds = $scoredResult->getIds();
+
+        $bestPerParent = [];
+        foreach ($scoredResultIds as $id) {
+            $bestPerParent[$idToParent[$id]] ??= $id;
```
Comment (vienthuong) [inline src/Core/Content/Product/SalesChannel/Listing/ProductListingLoader.php]:
```suggestion
            isset($bestPerParent[$idToParent[$id]]) continue;
            $bestPerParent[$idToParent[$id]] = $id;
```

File: src/Core/Content/Product/SalesChannel/Listing/ProductListingLoader.php [hunk 9]
```diff
@@ -273,7 +273,110 @@ private function resolveIds(Criteria $criteria, SalesChannelContext $context): I
...
+        }
+
+        $newData = [];
+        foreach ($ids as $originalId) {
+            $parentId = $idToParent[$originalId] ?? $originalId;
+            $bestId = $bestPerParent[$parentId] ?? $originalId;
```
Comment (vienthuong) [inline src/Core/Content/Product/SalesChannel/Listing/ProductListingLoader.php]: Since $parentId = $originalId doesn't make sense, I'd rather:

```suggestion
            $bestId = isset($bestPerParent[$idToParent[$originalId]]) ? $bestPerParent[$idToParent[$originalId]] : $originalId;
```

File: src/Core/Content/Product/SalesChannel/Listing/ProductListingLoader.php (hunk 5 above)
Comment (vienthuong) [inline src/Core/Content/Product/SalesChannel/Listing/ProductListingLoader.php]: $criteria->setTotalCountMode(Criteria::TOTAL_COUNT_MODE_NONE)

File: src/Core/Content/Product/SalesChannel/Listing/ProductListingLoader.php (hunk 3 above)
Comment (tamvt) [reply src/Core/Content/Product/SalesChannel/Listing/ProductListingLoader.php]: This does not work because:
  cloneForRead creates a brand new Criteria and only copies over: IDs, Title, Associations, Fields.

  It does not copy: $term, $queries, $sorting, $filters, $postFilters, $groupFields, $states.

  Without the term and queries, the DAL has no scoring information. The search returns results in an arbitrary/default order

Comment (vienthuong) [reply src/Core/Content/Product/SalesChannel/Listing/ProductListingLoader.php]: then I'd go with create a brand new criteria and set it a new title than clone the old one, you don't need other properties but only criteria.term and that's it

**Review by ngocblue — APPROVED** [review]
Test Passed

- Can search with variant name successfully with normal search

https://github.com/user-attachments/assets/b40aa79f-4a89-424c-9c00-d039f9361dd9

File: src/Core/Content/Product/SalesChannel/Listing/ProductListingLoader.php (hunk 1 above)
Comment (tamvt) [reply src/Core/Content/Product/SalesChannel/Listing/ProductListingLoader.php]: Hi @mitelg,
I have updated the PR. Can you please take a look?

File: src/Core/Content/Product/SalesChannel/Listing/ProductListingLoader.php [hunk 10]
```diff
@@ -264,6 +264,15 @@ private function resolveIds(Criteria $criteria, SalesChannelContext $context): I
     {
         $this->addGrouping($criteria);
 
+        $isSearchRoute = $criteria->hasState(ResolvedCriteriaProductSearchRoute::STATE, ProductSuggestRoute::STATE);
```
Comment (mitelg) [inline src/Core/Content/Product/SalesChannel/Listing/ProductListingLoader.php:267]: this checks whether one of the given states is applied, not both. is that intended? or do we need both?

File: src/Core/Framework/DataAbstractionLayer/Dbal/EntitySearcher.php [hunk 11]
```diff
@@ -75,7 +75,11 @@ public function search(EntityDefinition $definition, Criteria $criteria, Context
             $this->queryHelper->addIdCondition($criteria, $definition, $query);
         }
 
-        $this->queryHelper->addGroupBy($definition, $criteria, $context, $query, $table);
+        if ($query->hasState('_score') && $criteria->hasState(Criteria::STATE_FIND_BEST_VARIANT) && $criteria->getGroupFields() !== []) {
```
Comment (mitelg) [inline src/Core/Framework/DataAbstractionLayer/Dbal/EntitySearcher.php]: maybe it is time to introduce a constant for `'_score'` 😁

File: src/Core/Framework/DataAbstractionLayer/Search/Criteria.php [hunk 12]
```diff
@@ -30,6 +30,8 @@ class Criteria extends Struct implements \Stringable
 
     final public const STATE_DISABLE_SEARCH_INFO = 'disableSearchInfo';
 
+    final public const STATE_FIND_BEST_VARIANT = 'findBestVariant';
```
Comment (mitelg) [inline src/Core/Framework/DataAbstractionLayer/Search/Criteria.php]: I would rename the constant, as this is not only about products anymore, right?

File: tests/integration/Core/Framework/DataAbstractionLayer/Dbal/EntitySearcherTest.php [hunk 13]
```diff
@@ -331,6 +332,45 @@ public function testSearchFiltersByAndAppliesQueryToTranslatedFields(): void
         static::assertSame([$productId1], $productIds->getIds());
     }
 
+    public function testScoreRankingPicksHighestScoredRowPerGroup(): void
+    {
+        $ids = new IdsCollection();
+        $productBuilder1 = $this->buildProduct(
```
Comment (mitelg) [inline tests/integration/Core/Framework/DataAbstractionLayer/Dbal/EntitySearcherTest.php]: can we add one or two more products and then set the highest score an the second or third product? I am always a bit sceptical, if we assert the first created thing to be correct 😁

File: tests/integration/Core/Framework/DataAbstractionLayer/Dbal/EntitySearcherTest.php [hunk 14]
```diff
@@ -331,6 +332,45 @@ public function testSearchFiltersByAndAppliesQueryToTranslatedFields(): void
...
+                $productBuilder2->build(),
+            ],
+            Context::createDefaultContext(),
+        );
+
+        $criteria = new Criteria();
+        $criteria->addState(Criteria::STATE_FIND_BEST_VARIANT);
+        $criteria->addQuery(new ScoreQuery(new ContainsFilter('name', 'Sport Bottle Green'), score: 500));
+        $criteria->addQuery(new ScoreQuery(new ContainsFilter('name', 'Sport Bottle'), score: 100));
+        $criteria->addGroupField(new FieldGrouping('displayGroup'));
```
Comment (mitelg) [inline tests/integration/Core/Framework/DataAbstractionLayer/Dbal/EntitySearcherTest.php:367]: should the created products also have two different displayGroups? 🤔 so asserting the highest scored of each group?

File: tests/integration/Core/Framework/DataAbstractionLayer/Dbal/EntitySearcherTest.php [hunk 15]
```diff
@@ -331,6 +332,45 @@ public function testSearchFiltersByAndAppliesQueryToTranslatedFields(): void
...
+
+        $result = $this->entitySearcher->search(
+            static::getContainer()->get(ProductDefinition::class),
+            $criteria,
+            Context::createDefaultContext(),
+        );
+
+        $resultIds = $result->getIds();
+
+        static::assertContains($ids->get('score-group-1'), $resultIds, 'Higher-scored "Sport Bottle Green" should be selected for its group');
```
Comment (mitelg) [inline tests/integration/Core/Framework/DataAbstractionLayer/Dbal/EntitySearcherTest.php]: shouldn't we assert, that it is the first ID? 🤔 

the other ID is also part of the result, or isn't it?

**Review by mitelg — CHANGES_REQUESTED** [review]

File: src/Core/Content/Product/SalesChannel/Listing/ProductListingLoader.php (hunk 10 above)
Comment (tamvt) [reply src/Core/Content/Product/SalesChannel/Listing/ProductListingLoader.php:267]: That is intended because we want to check if it is a suggestion search or a search request

**Review by vienthuong — APPROVED** [review]

**Review by mitelg — APPROVED** [review]

**Comment by ngocblue** [comment]
Re-test PASSED

- Can search with variant name successfully with normal search
