### PR TITLE
fix: generate variants with empty restrictions

### LINKED ISSUE #12985: Can not generate Product variant within empty variant value exclution (reopen #3231)
### Shopware Version

6.7.3.0

### Affected area / extension

Platform(Default)

### Actual behaviour

If the attribute exclusion is opened during variant generation and “Continue” is clicked without further action, the field `product.variant_restrictions` is filled with an empty array. This leads to the following error when attempting to generate further variants for the same item:

```
71d55d8b106d10cfecd7.js:1 Uncaught (in promise) TypeError: (this.product.variantRestrictions || []).map is not a function

    at Proxy.filterRestrictions (71d55d8b106d10cfecd7.js:1:9147)

    at 71d55d8b106d10cfecd7.js:1:8909

    at new Promise (<anonymous>)

    at Proxy.filterVariations (71d55d8b106d10cfecd7.js:1:7687)

    at 71d55d8b106d10cfecd7.js:1:7549
```

### Expected behaviour

clicking "continue" in the variant restriction section should not write an empty array if there are no exclusions at all. In this case `product.variant_restrictions` must remain "NULL"

### How to reproduce

- open variant generation overlay
- open variant restriction section and click "continue" without further action
- open db table `product` --> column `variant_restrictions`

Result: There should be an entry now where product.variant_restrictions is set to `[]`. At this point, no further variants can be added since the error mentioned above will be thrown.

### PR DESCRIPTION
**Pull request by rittou**
### 1. Why is this change necessary?
This PR introduces several improvements and bug fixes to the product variants module, focusing on variant generation, restriction management, and error handling. The most significant changes include refactoring how configurator settings are saved during variant generation, enhancing the user experience with error notifications, and updating the logic for saving variant restrictions to prevent saving empty or invalid data.

#### Variant Generation and Error Handling
* Refactored the variant generation process to use `variantsGenerator.saveConfiguratorSettings` instead of directly saving the product via `productRepository.save`, improving data consistency and fixing the error when trying to delete existing variants. 
   Specifically, when saveVariants() cascades to delete `configuratorSettings` on the server, the local origin becomes stale, causing DELETE requests for items that have already been deleted.
* Added error handling and user notifications to the variant generation flow, displaying an error message if generation fails.

#### Variant Restriction Management
* Modified the restriction saving logic to filter out values with no selected options, preventing empty restrictions from being saved.
* Enhanced and expanded tests to verify that restrictions with empty options are not saved, and that only valid restriction values are persisted. [[1]](diffhunk://#diff-f2aefaedbeb6d51690a64a7e7cbb5320affdcdef73b4d2be40b36889894d8f05L316-R316) [[2]](diffhunk://#diff-f2aefaedbeb6d51690a64a7e7cbb5320affdcdef73b4d2be40b36889894d8f05R326-R453)

### Miscellaneous Improvements
* Updated logic in the variant overview to prevent errors when the product ID is missing or the product is not loaded yet.

#### Scenario 1
* Open PDP of a product that has variants
* Open tab Variants -> Generate variants -> Open tab Value exclusion 
* Click the button `Exclude values` -> Do nothing -> Save -> Next -> Save variants 
* Open modal generate variants ->  Open tab Value exclusion -> Do nothing -> Next -> Save variants. Do this step one more time. Nothing happens when you click Next button -> Open Inspect -> Tab Console -> You will see an error `Uncaught (in promise) TypeError: (this.product.variantRestrictions || []).map is not a function`

#### Scenario 2
* Open PDP of a product that has variants
* Open tab Variants -> Generate variants 
* In Value selection -> Deselect a value to delete the variants with that value -> Click Next -> Save variants -> The button Save variants loads infinitely.

### 4. Please link to the relevant issues (if any).
- relates #12985

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have updated developer-facing release notes if this change is **relevant** for external developers:
  - Add a short entry to `RELEASE_INFO-6.<major>.md` under “Upcoming” for informational changes, including the consequences of the change and how it affects external developers.
  - Add an `UPGRADE` section in `UPGRADE-6.<next-major>.md` for breaking changes (what/why/impact/how to adapt).
  - See the [Documenting a Release Process](https://github.com/shopware/shopware/blob/trunk/delivery-process/documenting-a-release.md) for details.
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

File: src/Administration/Resources/app/administration/src/module/sw-product/helper/sw-products-variants-generator.js [hunk 1]
```diff
@@ -25,7 +25,67 @@ export default class VariantsGenerator extends EventEmitter {
...
+                    return true;
+                }
+
+                // If marked as new, only include if the option is truly new (in createQueue)
+                return newOptionIds.has(setting.optionId);
+            })
+            .map((setting) => {
+                const settingData = deepCopyObject(setting);
+                settingData.productId = this.product.id;
+                return settingData;
```
[the remark this answers is not in the document]
Comment (rittou) [reply src/Administration/Resources/app/administration/src/module/sw-product/helper/sw-products-variants-generator.js:63]: Does the Shopware DAL handle field filtering?

File: src/Administration/Resources/app/administration/src/module/sw-product/component/sw-product-variants/sw-product-variants-configurator/sw-product-variants-configurator-restrictions/index.js [hunk 2]
```diff
@@ -200,6 +200,20 @@ export default {
         },
 
         saveAddRestriction() {
+            // Filter out values with no options selected
```
Comment (sydinh) [inline src/Administration/Resources/app/administration/src/module/sw-product/component/sw-product-variants/sw-product-variants-configurator/sw-product-variants-configurator-restrictions/index.js]: The filter prototype itself describes well what it does, so for this code comment, i don't think it's really needed.

File: src/Administration/Resources/app/administration/src/module/sw-product/component/sw-product-variants/sw-product-variants-configurator/sw-product-variants-configurator-restrictions/index.js [hunk 3]
```diff
@@ -200,6 +200,20 @@ export default {
...
+            const validValues = this.actualRestriction.values.filter((value) => {
+                return Array.isArray(value.options) && value.options.length > 0;
+            });
+
+            // Don't save if no valid values exist
```
Comment (sydinh) [inline src/Administration/Resources/app/administration/src/module/sw-product/component/sw-product-variants/sw-product-variants-configurator/sw-product-variants-configurator-restrictions/index.js]: Same as https://github.com/shopware/shopware/pull/14660/changes#r2762090134

File: src/Administration/Resources/app/administration/src/module/sw-product/component/sw-product-variants/sw-product-variants-configurator/sw-product-variants-configurator-restrictions/index.js [hunk 4]
```diff
@@ -200,6 +200,20 @@ export default {
...
+            if (validValues.length === 0) {
```
Comment (sydinh) [inline src/Administration/Resources/app/administration/src/module/sw-product/component/sw-product-variants/sw-product-variants-configurator/sw-product-variants-configurator-restrictions/index.js]:
```suggestion
            if (this.actualRestriction.values.length === 0) {
```

File: src/Administration/Resources/app/administration/src/module/sw-product/component/sw-product-variants/sw-product-variants-configurator/sw-product-variants-configurator-restrictions/index.js [hunk 5]
```diff
@@ -200,6 +200,20 @@ export default {
         },
 
         saveAddRestriction() {
+            // Filter out values with no options selected
+            const validValues = this.actualRestriction.values.filter((value) => {
```
Comment (sydinh) [inline src/Administration/Resources/app/administration/src/module/sw-product/component/sw-product-variants/sw-product-variants-configurator/sw-product-variants-configurator-restrictions/index.js]:
```suggestion
            const this.actualRestriction.values = this.actualRestriction.values.filter((value) => {
```

File: src/Administration/Resources/app/administration/src/module/sw-product/component/sw-product-variants/sw-product-variants-configurator/sw-product-variants-configurator-restrictions/index.js [hunk 6]
```diff
@@ -200,6 +200,20 @@ export default {
...
+            });
+
+            // Don't save if no valid values exist
+            if (validValues.length === 0) {
+                this.actualRestriction = {};
+                this.restrictionModalIsOpen = false;
+                return;
+            }
+
+            this.actualRestriction.values = validValues;
```
Comment (sydinh) [inline src/Administration/Resources/app/administration/src/module/sw-product/component/sw-product-variants/sw-product-variants-configurator/sw-product-variants-configurator-restrictions/index.js]:
```suggestion
```

File: src/Administration/Resources/app/administration/src/module/sw-product/helper/sw-products-variants-generator.js [hunk 7]
```diff
@@ -25,7 +25,67 @@ export default class VariantsGenerator extends EventEmitter {
...
+     * This approach avoids issues with stale entity origin state that could cause
+     * DELETE requests for settings already cascade-deleted on the server.
+     * Only upserts are performed, no deletions.
+     *
+     * @param {EntityCollection} configuratorSettings - The configurator settings to save
+     * @param {Array} createQueue - Queue of new variants to be created (used to determine truly new options)
+     * @returns {Promise}
+     */
+    saveConfiguratorSettings(configuratorSettings, createQueue = []) {
+        // If no settings to save, resolve immediately
```
Comment (sydinh) [inline src/Administration/Resources/app/administration/src/module/sw-product/helper/sw-products-variants-generator.js]: I see lots of unnecessary code comments 😄

File: src/Administration/Resources/app/administration/src/module/sw-product/helper/sw-products-variants-generator.js [hunk 8]
```diff
@@ -25,7 +25,67 @@ export default class VariantsGenerator extends EventEmitter {
...
+                variant.options.forEach((option) => {
+                    newOptionIds.add(option.id);
+                });
+            }
+        });
+
+        const payload = configuratorSettings
+            .filter((setting) => {
+                // If not marked as new, always include
+                if (!setting._isNew) {
```
Comment (sydinh) [inline src/Administration/Resources/app/administration/src/module/sw-product/helper/sw-products-variants-generator.js]: isNew()

**Review by sydinh — CHANGES_REQUESTED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-product/component/sw-product-variants/sw-product-variants-overview/index.js [hunk 9]
```diff
@@ -305,7 +305,11 @@ export default {
         getList() {
             // Promise needed for inline edit error handling
             return new Promise((resolve) => {
-                if (this.product.parentId) {
+                /**
+                 * if no product id or parent id, return early
+                 * prevents errors when the product is not loaded yet
+                 */
```
Comment (sydinh) [inline src/Administration/Resources/app/administration/src/module/sw-product/component/sw-product-variants/sw-product-variants-overview/index.js]: I would remove these code comments, since the handling is already clear.

File: src/Administration/Resources/app/administration/src/module/sw-product/helper/sw-products-variants-generator.js [hunk 10]
```diff
@@ -25,7 +25,63 @@ export default class VariantsGenerator extends EventEmitter {
...
+
+                return newOptionIds.has(setting.optionId);
+            })
+            .map((setting) => {
+                const settingData = deepCopyObject(setting);
+                settingData.productId = this.product.id;
+                return settingData;
+            });
+
+        // If no valid settings to save after filtering, resolve immediately
```
Comment (sydinh) [inline src/Administration/Resources/app/administration/src/module/sw-product/helper/sw-products-variants-generator.js]: Same as https://github.com/shopware/shopware/pull/14660/changes#r2791353607

File: src/Administration/Resources/app/administration/src/module/sw-product/helper/sw-products-variants-generator.js [hunk 11]
```diff
@@ -313,20 +369,33 @@ export default class VariantsGenerator extends EventEmitter {
     }
 
     filterRestrictions(createQueue) {
-        const variantRestriction = this.product.variantRestrictions || [];
+        // Ensure variantRestrictions is an array
```
Comment (sydinh) [inline src/Administration/Resources/app/administration/src/module/sw-product/helper/sw-products-variants-generator.js]: Same as https://github.com/shopware/shopware/pull/14660/changes#r2791353607

File: src/Administration/Resources/app/administration/src/module/sw-product/helper/sw-products-variants-generator.js [hunk 12]
```diff
@@ -313,20 +369,33 @@ export default class VariantsGenerator extends EventEmitter {
...
+        if (!Array.isArray(this.product.variantRestrictions)) {
+            return createQueue;
+        }
+
+        // Filter out invalid/empty restrictions before processing
```
Comment (sydinh) [inline src/Administration/Resources/app/administration/src/module/sw-product/helper/sw-products-variants-generator.js]: Same as https://github.com/shopware/shopware/pull/14660/changes#r2791353607

File: src/Administration/Resources/app/administration/src/module/sw-product/helper/sw-products-variants-generator.js [hunk 13]
```diff
@@ -313,20 +369,33 @@ export default class VariantsGenerator extends EventEmitter {
...
+        const validRestrictions = this.product.variantRestrictions.filter((restriction) => {
+            return (
+                restriction &&
+                Array.isArray(restriction.values) &&
+                restriction.values.length > 0 &&
+                restriction.values.every((value) => Array.isArray(value.options) && value.options.length > 0)
+            );
+        });
+
+        // Return the normal create queue when no valid restrictions exist
```
Comment (sydinh) [inline src/Administration/Resources/app/administration/src/module/sw-product/helper/sw-products-variants-generator.js]: Same as https://github.com/shopware/shopware/pull/14660/changes#r2791353607

**Review by sydinh — CHANGES_REQUESTED** [review]

**Review by vienthuong — APPROVED** [review]

**Review by sydinh — APPROVED** [review]
LGTM, thanks 👍🏻
