### PR TITLE
fix: handle merge documents errors

### LINKED ISSUE #8194: Downloading migrated invoice documents for multiple orders using the bulk edit fails
### Shopware Version

6.6.10.2

### Affected area / extension

Extension:Migration-Tool

### Actual behaviour

When trying to download migrated order documents (testes specifically with invoice documents) for multiple orders at once through the bulk edit function, you get an internal server error:

{
    "errors": [
        {
            "code": "257",
            "status": "500",
            "title": "Internal Server Error",
            "detail": "The xref position points to an incorrect object type."
        }
    ]
}

### Expected behaviour

Invoice documents can be downloaded for multiple orders at once using the bulk edit. 

### How to reproduce

- Set up at least two orders in Shopware 5 shop
- Generate invoice documents for both orders
- Migrate orders to Shopware 6 shop
- Open bulk edit through order overview after selecting these two orders
- Select option `Download: Documents: Invoice`
- Click "Apply changes" and then "Download" once the overlay becomes visible

Result: `Error - Request failed with status code 500`

### PR DESCRIPTION
**Pull request by ennasus4sun**
### 1. Why is this change necessary?

1. bulk edit for download documents fails for Shopware 6 generated documents that have a logo with this error: `Cannot assign array to property Shopware\\Core\\Checkout\\Document\\DocumentConfiguration::$logo of type ?`Shopware\\Core\\Content\\Media\\MediaEntity",
2. Shopware 5 migrated documents fails with this error for invoices:` Object (id:23) not found at location (857).`

### 2. What does this change do, exactly?

1. Since 6.7 the `\Shopware\Core\Checkout\Document\DocumentConfiguration::$logo` property is typed nativly to `MediaEntity`. Before, it expected an array. 2 methods were added and used to set the value: `getLogo` and `setLogo`.
2. The Fdpi library is throwing errors for Shopware 5 generated and migrated documents. When an error is thrown, we create a zip file for all documents.

### 3. Describe each step to reproduce the issue or behaviour.

1. Shopware 5 migrated documents

- create at least 2 orders and generate documents (for example: invoice) for them
- migrate them with the SwagMigrationAssistent

3. Shopware 6 generated documents

- set a logo for the document (for example: invoice) -> Settings > Documents
- create at least 2 orders and generate documents (for example: invoice) for them

4. bulk edit first the Shopware 5 migrated documents - in a separate run the Shopware 6 generated documents

- select the Shopware 5/ Shopware 6 documents
- run "Bulk edit"
- Download: Documents > check the document type you created previously (for example: invoice)

### 4. Please link to the relevant issues (if any).
- closes #8194

### CODE REVIEW

File: src/Core/Checkout/Document/DocumentConfigurationFactory.php [hunk 1]
```diff
@@ -51,6 +52,8 @@ public static function mergeConfiguration(DocumentConfiguration $baseConfig, Doc
                     $baseConfig->__set('custom', array_merge((array) $baseConfig->__get('custom'), [$customKey => $value]));
                 } elseif ($key === 'companyCountry' && \is_array($value)) {
                     $baseConfig->setCompanyCountry((new CountryEntity())->assign($value));
+                } elseif ($key === 'logo' && \is_array($value)) {
```
Comment (mitelg) [inline src/Core/Checkout/Document/DocumentConfigurationFactory.php]: I already commented this on the PR, were the companyCountry was fixed. I wonder, if we need a general solution, or if now all properties work correctly :grin:

File: src/Core/Checkout/Document/Service/DocumentMerger.php [hunk 2]
```diff
@@ -103,49 +153,68 @@ public function merge(array $documentIds, Context $context): ?RenderedDocument
...
 
-        $renderedDocument->setContent($this->fpdi->Output($fileName, 'S'));
+        $renderedDocument->setContent($this->fpdi->Output($renderedDocument->getName(), 'S'));
         $renderedDocument->setContentType(PdfRenderer::FILE_CONTENT_TYPE);
 
         return $renderedDocument;
     }
 
-    private function ensureDocumentMediaFileGenerated(DocumentEntity $document, Context $context): ?string
+    private function createDocumentsZip(DocumentCollection $documents, Context $context): ?RenderedDocument
```
Comment (mitelg) [inline src/Core/Checkout/Document/Service/DocumentMerger.php:197]: would you mind moving the `ensureDocumentMediaFileGenerated` back to this position? that would make the code review easier

File: tests/unit/Core/Checkout/Document/Service/DocumentMergerTest.php [hunk 3]
```diff
@@ -30,23 +31,110 @@
...
+            $this->createMock(Fpdi::class),
+        );
+
+        $result = $documentMerger->merge(
+            [$document->getId()],
+            Context::createDefaultContext()
+        );
+
+        static::assertNotNull($result);
+        static::assertEquals('pdf', $result->getFileExtension());
```
Comment (mitelg) [inline tests/unit/Core/Checkout/Document/Service/DocumentMergerTest.php]:
```suggestion
        static::assertSame('pdf', $result->getFileExtension());
```

please use `assertSame` where possible instead, as it is type safe. please also fix all other occurrences

**Review by mitelg — CHANGES_REQUESTED** [review]

File: src/Core/Checkout/Document/Service/DocumentMerger.php (hunk 2 above)
Comment (ennasus4sun) [reply src/Core/Checkout/Document/Service/DocumentMerger.php:197]: It's on the same position ... I dont understand why that looks so weird 🙈 
I add the new methods below `ensureDocumentMediaFileGenerated`.

**Comment by ennasus4sun** [comment]
Note:
we need to backport that to 6.6.x but remove the solution for the MediaEntity-error as `$logo` is not typed as `MediaEntity`

File: src/Core/Checkout/Document/DocumentConfigurationFactory.php (hunk 1 above)
Comment (ennasus4sun) [reply src/Core/Checkout/Document/DocumentConfigurationFactory.php]: https://github.com/shopware/shopware/pull/7019#discussion_r1967712953

Comment (ennasus4sun) [reply src/Core/Checkout/Document/DocumentConfigurationFactory.php]: Now all properties should work correctly, I think, as these 2 properties are at the moment (...) the only object properties in https://github.com/shopware/shopware/blob/3c0e82fa56a8e1ff25a31b786de1d9ba42d58e85/src/Core/Checkout/Document/DocumentConfiguration.php#L15. 
It's "just" not "scalable" when more are added....
I will talk with my team about that.

File: src/Core/Checkout/Document/DocumentConfigurationFactory.php [hunk 4]
```diff
@@ -46,14 +46,37 @@ public static function mergeConfiguration(DocumentConfiguration $baseConfig, Doc
...
+
+                if (!property_exists($baseConfig, $key)) {
                     $baseConfig->__set($key, $value);
+                    continue;
                 }
+
+                $property = new \ReflectionProperty($baseConfig, $key);
+                $propertyType = $property->getType();
+
+                if ($propertyType instanceof \ReflectionNamedType) {
```
Comment (ennasus4sun) [inline src/Core/Checkout/Document/DocumentConfigurationFactory.php]: @mitelg (and FYI @jozsefdamokos ) this is how our solution would look like. Manual adjustments wouldn't be needed.
What do you think about that?
I also run now into phpstan error thrown from this rule: https://github.com/symplify/phpstan-rules?tab=readme-ov-file#nodynamicnamerule
if we want to use the rule, the code would look similar like before 😅 
or we ignore that line

Comment (mitelg) [reply src/Core/Checkout/Document/DocumentConfigurationFactory.php]: you can set an annotation to ignore this. but please with a comment, why this is necessary. 

have you checked if this has a performance impact? I am not sure, where we use this factory. 
I mean, just to be future proof implementing something with reflections, we should check, if this is worth it :wink:

File: src/Core/Checkout/Document/DocumentConfigurationFactory.php [hunk 5]
```diff
@@ -29,7 +29,7 @@ public static function createConfiguration(array $specificConfig, ?DocumentBaseC
     }
 
     /**
-     * @param DocumentBaseConfigEntity|DocumentConfiguration|array<string, bool|int|string|array<array-key, mixed>|null> $additionalConfig
+     * @param DocumentBaseConfigEntity|DocumentConfiguration|array<string, mixed> $additionalConfig
```
Comment (ennasus4sun) [inline src/Core/Checkout/Document/DocumentConfigurationFactory.php:33]: Iam not sure if that is the best approach but also objects are passed as params. Any other ideas are welcome.

File: src/Core/Checkout/Document/DocumentConfigurationFactory.php (hunk 4 above)
Comment (ennasus4sun) [reply src/Core/Checkout/Document/DocumentConfigurationFactory.php]: for completeness:
the time of the creation of 10 invoices (bulk edit; average value from 8 runs based on the demodata) takes 0.031 seconds longer with the new approach.
The time for 10.000 documents is increased by 31 seconds.

Comment (mitelg) [reply src/Core/Checkout/Document/DocumentConfigurationFactory.php]: okay, that sounds okay to me

File: src/Core/Checkout/Document/DocumentConfigurationFactory.php (hunk 5 above)
Comment (mitelg) [reply src/Core/Checkout/Document/DocumentConfigurationFactory.php:33]: if everything could be in that array, mixed it totally fine

File: src/Core/Checkout/Document/DocumentConfigurationFactory.php [hunk 6]
```diff
@@ -46,14 +46,44 @@ public static function mergeConfiguration(DocumentConfiguration $baseConfig, Doc
...
+
+                if (!property_exists($baseConfig, $key)) {
                     $baseConfig->__set($key, $value);
+                    continue;
                 }
+
+                $property = new \ReflectionProperty($baseConfig, $key);
+                $propertyType = $property->getType();
+
+                if ($propertyType instanceof \ReflectionNamedType) {
```
Comment (mitelg) [inline src/Core/Checkout/Document/DocumentConfigurationFactory.php]: should we do an early continue here instead?

File: src/Core/Checkout/Document/DocumentConfigurationFactory.php [hunk 7]
```diff
@@ -46,14 +46,44 @@ public static function mergeConfiguration(DocumentConfiguration $baseConfig, Doc
...
+                    $typeName = $propertyType->getName();
+                    if (is_subclass_of($typeName, Entity::class) && \is_array($value)) {
```
Comment (mitelg) [inline src/Core/Checkout/Document/DocumentConfigurationFactory.php]: also here: for better readability we can invert the ifs and do early continues

File: src/Core/Checkout/Document/Service/DocumentMerger.php (hunk 2 above)
Comment (mitelg) [reply src/Core/Checkout/Document/Service/DocumentMerger.php:197]: maybe it gets better if you move `mergeWithFpdi` above `ensureDocumentMediaFileGenerated` ?

File: src/Core/Checkout/Document/DocumentConfigurationFactory.php (hunk 6 above)
Comment (ennasus4sun) [reply src/Core/Checkout/Document/DocumentConfigurationFactory.php]: yes, sounds good 👍🏻

File: src/Core/Checkout/Document/Service/DocumentMerger.php (hunk 2 above)
Comment (ennasus4sun) [reply src/Core/Checkout/Document/Service/DocumentMerger.php:197]: yes, looks better now 👍🏻

File: src/Core/Checkout/Document/Service/DocumentMerger.php [hunk 8]
```diff
@@ -151,4 +164,88 @@ private function ensureDocumentMediaFileGenerated(DocumentEntity $document, Cont
...
+
+        $fileName = Random::getAlphanumericString(32) . '.zip';
+
+        $renderedDocument = new RenderedDocument(
+            name: $fileName,
+            fileExtension: 'zip',
+            contentType: 'application/zip'
+        );
+
+        $fileContent = file_get_contents($tempFile);
```
Comment (mitelg) [inline src/Core/Checkout/Document/Service/DocumentMerger.php]: would be nice, if you could use the Symfony FileSystem component instead of the native PHP functions. this helps for example with testing the class

**Review by mitelg — APPROVED** [review]

File: src/Core/Checkout/Document/DocumentConfigurationFactory.php [hunk 9]
```diff
@@ -46,13 +46,47 @@ public static function mergeConfiguration(DocumentConfiguration $baseConfig, Doc
...
+                automatically supporting new entity properties without code changes with a static
+                switch/if-else approach.
+                */
+                if (method_exists($baseConfig, $setterMethod)) {
+                    // @phpstan-ignore symplify.noDynamicName
+                    $baseConfig->$setterMethod((new $typeName())->assign($value));
+                } else {
+                    // @phpstan-ignore symplify.noDynamicName
+                    $baseConfig->{$key} = (new $typeName())->assign($value);
                 }
```
Comment (MalteJanz) [inline src/Core/Checkout/Document/DocumentConfigurationFactory.php:91]: Very interesting solution, I like that it automatically constructs the correct type and assigns values based on the input array. Well done 👍 

What I don't like is that we are going from array to object and back with this `DocumentConfiguration` struct, instead of sticking with the object. But that's another topic we might tackle with a bigger "document generation refactor" 😂

File: src/Core/Checkout/Document/DocumentConfigurationFactory.php [hunk 10]
```diff
@@ -46,13 +46,47 @@ public static function mergeConfiguration(DocumentConfiguration $baseConfig, Doc
...
+                $propertyType = $property->getType();
+
+                if (!($propertyType instanceof \ReflectionNamedType)) {
+                    $baseConfig->__set($key, $value);
+                    continue;
+                }
+
+                $typeName = $propertyType->getName();
+
+                if (!is_subclass_of($typeName, Entity::class) || !\is_array($value)) {
```
Comment (MalteJanz) [inline src/Core/Checkout/Document/DocumentConfigurationFactory.php]: You could make it even more generic and allow any type that is a subclass of `Struct`, as that class brings the `assign` method with it.

File: src/Core/Checkout/Document/Service/DocumentMerger.php [hunk 11]
```diff
@@ -151,4 +164,88 @@ private function ensureDocumentMediaFileGenerated(DocumentEntity $document, Cont
...
+            $documentMediaId = $this->documentMediaCache[$document->getId()] ?? null;
+            if ($documentMediaId === null) {
+                continue;
+            }
+
+            $fileContent = $context->scope(Context::SYSTEM_SCOPE, function (Context $context) use ($documentMediaId) {
+                return $this->mediaService->loadFile($documentMediaId, $context);
+            });
+
+            $name = $document->getDocumentType()?->getTechnicalName() ?? 'unknown'
```
Comment (MalteJanz) [inline src/Core/Checkout/Document/Service/DocumentMerger.php]: Is the `$document->getDocumentType()?->getTechnicalName()` really unique enough here? E.g. Imagine there are two invoice documents, wouldn't this lead to two identical filenames in the zip? 🤔

File: tests/unit/Core/Checkout/Document/Service/DocumentMergerTest.php [hunk 12]
```diff
@@ -144,10 +217,203 @@ public function testMergeWithFpdiConfig(): void
...
+
+        $result = $documentMerger->merge(
+            [$firstDocument->getId(), $secondDocument->getId()],
+            Context::createDefaultContext()
+        );
+
+        static::assertNotNull($result);
+        static::assertSame('zip', $result->getFileExtension());
+        static::assertSame('application/zip', $result->getContentType());
+        static::assertNotEmpty($result->getContent());
```
Comment (MalteJanz) [inline tests/unit/Core/Checkout/Document/Service/DocumentMergerTest.php:286]: I would be curious on what the zip actually contains, e.g. are there really two files in there? what names do they have?

it's related to my comment above, they might have the same name 🤔 . Anyways actually asserting that the zip contains the correct content would be nice 🙂

File: src/Core/Checkout/Document/Service/DocumentMerger.php (hunk 11 above)
Comment (ennasus4sun) [reply src/Core/Checkout/Document/Service/DocumentMerger.php]: the document name contains also the order-id.
Only the last/newest document of a type in an order is downloaded. So, when an order has 2 invoices only the newest will be used: https://github.com/shopware/shopware/blob/ef6f152acbc23e84426de225c1350f193a3d6ce1/src/Administration/Resources/app/administration/src/module/sw-bulk-edit/component/sw-bulk-edit-save-modal-success/index.js#L127-L160

File: src/Core/Checkout/Document/Service/DocumentMerger.php (hunk 8 above)
Comment (ennasus4sun) [reply src/Core/Checkout/Document/Service/DocumentMerger.php]: I had already forgotten this way again... 🙈

File: tests/unit/Core/Checkout/Document/Service/DocumentMergerTest.php (hunk 12 above)
Comment (ennasus4sun) [reply tests/unit/Core/Checkout/Document/Service/DocumentMergerTest.php:286]: yes... this is a bit difficult because I need to open the zip-Archive which is deleted before the return. 
I can try to do this in an integration test.

Comment (ennasus4sun) [reply tests/unit/Core/Checkout/Document/Service/DocumentMergerTest.php:286]: was a good idea ✅

File: src/Core/Checkout/Document/Service/DocumentMerger.php (hunk 11 above)
Comment (ennasus4sun) [reply src/Core/Checkout/Document/Service/DocumentMerger.php]: yes, it seems there was a problem. I adjusted this part.

Comment (MalteJanz) [reply src/Core/Checkout/Document/Service/DocumentMerger.php]: Thanks for clarifying. Just to double check, as I'm not familiar with this bulk edit of documents. Does it generate the zip for only one single order? Can I call this `DocumentMerger` service or it's HTTP API with documents of multiple orders or all (e.g. two invoices) of a single order?

Just want to make sure we properly handle these cases to prevent wrong use of that service which sounds to me that it can merge any documents without any documented limitations / preconditions. 

My reasoning behind is that we should try to make our API misuse resistant and it should do what one would expect without any surprises, e.g. throwing random zip exceptions when giving it two documents of the same type.

File: tests/unit/Core/Checkout/Document/Service/DocumentMergerTest.php (hunk 12 above)
Comment (MalteJanz) [reply tests/unit/Core/Checkout/Document/Service/DocumentMergerTest.php:286]: What speaks against writing that content to another temp file and opening that as a zip in the test? The function under test already writes to disk or not? So why not continue doing so in the test? 🤔 

Unfortunately it doesn't seem easily possible to read a zip from a string / byte buffer in PHP

**Review by MalteJanz — APPROVED** [review]

File: src/Core/Checkout/Document/Service/DocumentMerger.php (hunk 11 above)
Comment (ennasus4sun) [reply src/Core/Checkout/Document/Service/DocumentMerger.php]: I can confirm this: downloading 3 inoices via API from one order will return just one.
I will adjust the name and add maybe also the document-number...

Comment (ennasus4sun) [reply src/Core/Checkout/Document/Service/DocumentMerger.php]: done ✅

File: src/Core/Checkout/Document/Service/DocumentMerger.php [hunk 13]
```diff
@@ -215,7 +215,8 @@ private function createDocumentsZip(DocumentCollection $documents, Context $cont
             });
 
             $technicalName = $document->getDocumentType()?->getTechnicalName() ?? 'unknown';
-            $name = $technicalName . '_' . $document->getOrderId() . '.' . PdfRenderer::FILE_EXTENSION;
+            $documentNumber = $document->getDocumentNumber() ?? $document->getId();
+            $name = $technicalName . '_' . $document->getOrderId() . '_' . $documentNumber . '.' . PdfRenderer::FILE_EXTENSION;
```
Comment (MalteJanz) [inline src/Core/Checkout/Document/Service/DocumentMerger.php]: Small optional nitpick (the current solution already works fine like this): Isn't the `$documentNumber` already unique? I'm not sure what benefit the `$document->getOrderId()` then provides other than making the file name harder to read. There is also the "order number" which might be better suited to show to the user as a filename which order it is about 🤔

**Review by MalteJanz — APPROVED** [review]

File: src/Core/Checkout/Document/Service/DocumentMerger.php (hunk 13 above)
Comment (ennasus4sun) [reply src/Core/Checkout/Document/Service/DocumentMerger.php]: I like that way 👍🏻 but I have to include the order association. See the adjustments: https://github.com/shopware/shopware/pull/9294/commits/48ba740643f0cf32c8760508330117a1211d17a7

**Review by jozsefdamokos — APPROVED** [review]

**Review by MalteJanz — APPROVED** [review]
