### PR TITLE
fix: bulk edit list price or cheapest price not possible without also checking base price checkbox

### LINKED ISSUE #14157: Bulk editing list price or cheapest price not possible without also checking base price checkbox
### Shopware Version

6.6.10.10 & 6.7.5.1

### Affected area / extension

Platform(Default)

### Actual behaviour

When you try to bulk edit list prices or cheapest prices, the field will be greyed out unless you also check the box to edit the base price.

Image

Image

If you check the price checkbox, the price does not seem to be changed by itself as long as no value is inserted (6.6) or the existing value is not changed (6.7). Though that may not be intuitive to users.

### Expected behaviour

List and cheapest prices can be modified independently without checking the price check box

### How to reproduce

Bulk edit products, observe the issue

### PR DESCRIPTION
**Pull request by nguyenquocdaile**
This pull request refactors the handling of `listPrice` and `regulationPrice` fields in the bulk edit product page, ensuring that changes to these fields are properly sent in the API request even when the main price field is not changed. It also removes legacy logic for disabling these fields and adds tests to verify the new behavior.

Bulk edit price field logic improvements:

* Removed legacy disabling logic for `listPrice` and `regulationPrice` fields, allowing them to be edited independently of the main price field. (`sw-bulk-edit-product/index.js`) [[1]](diffhunk://#diff-6f5d780ac16aff8423ac70fc38f2be2bb6a8c8f8da155948ca78a2c2e77cb783L285-R291) [[2]](diffhunk://#diff-6f5d780ac16aff8423ac70fc38f2be2bb6a8c8f8da155948ca78a2c2e77cb783L301-R307) [[3]](diffhunk://#diff-6f5d780ac16aff8423ac70fc38f2be2bb6a8c8f8da155948ca78a2c2e77cb783L1113-L1117)
* Updated the data processing logic so that when only `listPrice` or `regulationPrice` is changed, a price payload is constructed and included in the API request, ensuring proper backend handling. (`sw-bulk-edit-product/index.js`) [[1]](diffhunk://#diff-6f5d780ac16aff8423ac70fc38f2be2bb6a8c8f8da155948ca78a2c2e77cb783R1221-R1236) [[2]](diffhunk://#diff-6f5d780ac16aff8423ac70fc38f2be2bb6a8c8f8da155948ca78a2c2e77cb783R1247-R1262)

Deprecation and cleanup:

* Marked `isDisabledListPrice` and `isDisabledRegulationPrice` as deprecated and scheduled for removal in v6.8.0, reflecting their obsolescence in the new logic. (`sw-bulk-edit-product/index.js`)

Testing enhancements:

* Added new unit tests to verify that requests include `listPrice` or `regulationPrice` when only those fields are changed, improving coverage and reliability. (`sw-bulk-edit-product.spec.js`)

### CODE REVIEW

File: src/Administration/Resources/app/administration/src/module/sw-bulk-edit/page/sw-bulk-edit-product/index.js [hunk 1]
```diff
@@ -29,7 +29,13 @@ export default {
...
             isSaveSuccessful: false,
             displayAdvancePricesModal: false,
+            /**
+             * @deprecated tag:v6.8.0 - will be removed without replacement
+             */
             isDisabledListPrice: true,
+            /**
+             * @deprecated tag:v6.8.0 - will be removed without replacement
+             */
             isDisabledRegulationPrice: true,
```
Comment (sydinh) [inline src/Administration/Resources/app/administration/src/module/sw-bulk-edit/page/sw-bulk-edit-product/index.js:39]: Likely, people did it on purpose. May I know why you confidently removed it 🤔

**Review by sydinh — CHANGES_REQUESTED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-bulk-edit/page/sw-bulk-edit-product/index.js (hunk 1 above)
Comment (nguyenquocdaile) [reply src/Administration/Resources/app/administration/src/module/sw-bulk-edit/page/sw-bulk-edit-product/index.js:39]: Maybe at that time they implemented it,  API doesn't support changing separate price and listPrice ( regulationPrice ). 
We also discussed in daily that we can support it.
cc @vienthuong @tamvt, maybe the BE guys have some options, or have you implemented the same feature before?

File: src/Administration/Resources/app/administration/src/module/sw-bulk-edit/page/sw-bulk-edit-product/index.js [hunk 2]
```diff
@@ -29,7 +29,13 @@ export default {
             isLoadedData: false,
             isSaveSuccessful: false,
             displayAdvancePricesModal: false,
+            /**
+             * @deprecated tag:v6.8.0 - will be removed without replacement
+             */
             isDisabledListPrice: true,
```
Comment (sydinh) [inline src/Administration/Resources/app/administration/src/module/sw-bulk-edit/page/sw-bulk-edit-product/index.js:35]: Please ensure you update all dependencies with this `deprecated` state, including the one below.

Comment (sydinh) [reply src/Administration/Resources/app/administration/src/module/sw-bulk-edit/page/sw-bulk-edit-product/index.js:35]: isDisabledRegulationPrice

File: src/Administration/Resources/app/administration/src/module/sw-bulk-edit/service/handler/bulk-edit-product.handler.js [hunk 3]
```diff
@@ -317,6 +317,8 @@ class BulkEditProductHandler extends BulkEditBaseHandler {
     }
 
     formatPrice(price, dbPrice) {
+        const preserveFromDb = price.gross === null && price.net === null;
```
Comment (sydinh) [inline src/Administration/Resources/app/administration/src/module/sw-bulk-edit/service/handler/bulk-edit-product.handler.js:320]: I have no clue about this, kindly take a look @vienthuong

**Review by sydinh — CHANGES_REQUESTED** [review]

File: src/Administration/Resources/app/administration/src/module/sw-bulk-edit/page/sw-bulk-edit-product/index.js (hunk 2 above)
Comment (nguyenquocdaile) [reply src/Administration/Resources/app/administration/src/module/sw-bulk-edit/page/sw-bulk-edit-product/index.js:35]: Yes, I checked and removed the unused items.

File: src/Administration/Resources/app/administration/src/module/sw-bulk-edit/service/handler/bulk-edit-product.handler.js (hunk 3 above)
Comment (vienthuong) [reply src/Administration/Resources/app/administration/src/module/sw-bulk-edit/service/handler/bulk-edit-product.handler.js:320]: LGTM

**Review by vienthuong — APPROVED** [review]

**Review by sydinh — APPROVED** [review]
