### PR TITLE
fix: error during offline theme compilation

### LINKED ISSUE #11422: Compiling the storefront without a database
### Shopware Version

6.7.0.1

### Affected area / extension

Platform(Default)

### Actual behaviour

```
Warning: Failed to load apps. Loading apps from local. Message: An exception occurred in the driver: SQLSTATE[HY000] [2002] Connection refused
Start theme compilation

 Compiling theme for sales channel for : 01982ce6298979d7b863861ba74011f4                                               

Warning: Failed to load plugin css configuration. Ignoring plugin css customizations. Message: An exception occurred in the driver: SQLSTATE[HY000] [2002] Connection refused

In ExceptionConverter.php line 80:
                                                                                  
  [Doctrine\DBAL\Exception\ConnectionException (2002)]                            
  An exception occurred in the driver: SQLSTATE[HY000] [2002] Connection refused  
                                                                                  

Exception trace:
  at /var/www/html/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:80
 Doctrine\DBAL\Driver\API\MySQL\ExceptionConverter->convert() at /var/www/html/vendor/doctrine/dbal/src/Connection.php:1418
 Doctrine\DBAL\Connection->handleDriverException() at /var/www/html/vendor/doctrine/dbal/src/Connection.php:1366
 Doctrine\DBAL\Connection->convertException() at /var/www/html/vendor/doctrine/dbal/src/Connection.php:227
 Doctrine\DBAL\Connection->connect() at /var/www/html/vendor/doctrine/dbal/src/Connection.php:244
 Doctrine\DBAL\Connection->getServerVersion() at /var/www/html/vendor/doctrine/dbal/src/Driver/AbstractMySQLDriver.php:38
 Doctrine\DBAL\Driver\AbstractMySQLDriver->getDatabasePlatform() at /var/www/html/vendor/doctrine/dbal/src/Connection.php:199
 Doctrine\DBAL\Connection->getDatabasePlatform() at /var/www/html/vendor/doctrine/dbal/src/Connection.php:445
 Doctrine\DBAL\Connection->getTransactionIsolation() at /var/www/html/vendor/shopware/core/Framework/Adapter/Cache/InvalidatorStorage/MySQLInvalidatorStorage.php:108
 Shopware\Core\Framework\Adapter\Cache\InvalidatorStorage\MySQLInvalidatorStorage->readCommittedIsolation() at /var/www/html/vendor/shopware/core/Framework/Adapter/Cache/InvalidatorStorage/MySQLInvalidatorStorage.php:47
 Shopware\Core\Framework\Adapter\Cache\InvalidatorStorage\MySQLInvalidatorStorage->store() at /var/www/html/var/cache/dev_hc6d1cb0d0e024032df64e6f9d6587bd6/ContainerG0YwYeQ/proxy-classes.php:266
 ContainerG0YwYeQ\AbstractInvalidatorStorageProxyD6f1bbb->store() at /var/www/html/vendor/shopware/core/Framework/Adapter/Cache/CacheInvalidator.php:52
 Shopware\Core\Framework\Adapter\Cache\CacheInvalidator->invalidate() at /var/www/html/vendor/shopware/storefront/Theme/ThemeCompiler.php:128
 Shopware\Storefront\Theme\ThemeCompiler->compileTheme() at /var/www/html/vendor/shopware/storefront/Theme/ThemeService.php:73
 Shopware\Storefront\Theme\ThemeService->compileTheme() at /var/www/html/vendor/shopware/storefront/Theme/Command/ThemeCompileCommand.php:93
 Shopware\Storefront\Theme\Command\ThemeCompileCommand->execute() at /var/www/html/vendor/symfony/console/Command/Command.php:279
 Symfony\Component\Console\Command\Command->run() at /var/www/html/vendor/symfony/console/Application.php:1094
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/vendor/symfony/framework-bundle/Console/Application.php:123
  Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/html/vendor/symfony/console/Application.php:342
 Symfony\Component\Console\Application->doRun() at /var/www/html/vendor/symfony/framework-bundle/Console/Application.php:77
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/html/vendor/symfony/console/Application.php:193
 Symfony\Component\Console\Application->run() at /var/www/html/vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php:49
 require_once() at /var/www/html/bin/ci:13
```

### Expected behaviour

As per the documentation it should be possible to compile the styles without a database. e.g. using a build pipeline.,
See; https://developer.shopware.com/docs/guides/hosting/installation-updates/deployments/build-w-o-db.html#compiling-the-storefront-without-database

However the in the theme compile command it is now required to have a mysql or redis connection.
Since the cache rework the class `vendor/shopware/core/Framework/Adapter/Cache/CacheInvalidator.php`  now calls  `$this->cache->store($tags);` whenever the environment is not `test` or the request contains the `sw-force-cache-invalidate` header.

I suggest adding a flag or some kind of other logic so the `shouldForceInvalidate` returns true when compiling the theme. Or catch the exception and continue.

### How to reproduce

1. Setup project for compiling without a database, follow the guide https://developer.shopware.com/docs/guides/hosting/installation-updates/deployments/build-w-o-db.html#compiling-the-storefront-without-database
2. Execute the `theme:compile command without a database`.
3. See that the exception occurs.

### Definition of Done

- [x] An automated test covers the fix.
- [ ] Integration/E2E testing in staging is done.
- [ ] Changelog markdown file created or updated in /changelog/_unreleased directory.
- [x] Developer documentation written/updated.
- [ ] End user and/or developer documentation written or updated with clarification.
- [ ] Regression test created to ensure bug does not reappear, and automated regression tests pass.
- [x] Code changes resolve the reported bug without introducing new issues.

### PR DESCRIPTION
**Pull request by h1k3r**
### 1. Why is this change necessary?

When theme is compiled without database, and delayed invalidation is enabled, theme compiles, but user sees error message that may be confusing.

### 2. What does this change do, exactly?

Reduces severity of logged message to the warning mode.

### 3. Describe each step to reproduce the issue or behaviour.

- enable delayed cache invalidation
- configure theme compilation without db https://developer.shopware.com/docs/guides/hosting/installation-updates/deployments/build-w-o-db.html#compiling-the-storefront-without-database
- run `bin/console theme:dump`
- run `CI=1 bin/ci theme:compile`

### 4. Please link to the relevant issues (if any).
- closes https://github.com/shopware/shopware/issues/11422

### 5. Checklist

- [ ] I have written tests and verified that they fail without my change
- [ ] I have updated developer-facing release notes if this change is **relevant** for external developers:
  - Add a short entry to `RELEASE_INFO-6.<major>.md` under “Upcoming” for informational changes, including the consequences of the change and how it affects external developers.
  - Add an `UPGRADE` section in `UPGRADE-6.<next-major>.md` for breaking changes (what/why/impact/how to adapt).
  - See the [Documenting a Release Process](https://github.com/shopware/shopware/blob/trunk/delivery-process/documenting-a-release.md) for details.
- [ ] I have written or adjusted the documentation according to my changes
- [ ] This change has comments for package types, values, functions, and non-obvious lines of code
- [ ] I have read the contribution requirements and fulfilled them

### CODE REVIEW

**Review by mitelg — APPROVED** [review]

File: src/Core/DevOps/Environment/EnvironmentHelper.php [hunk 1]
```diff
@@ -40,6 +40,11 @@ public static function hasVariable(string $key): bool
         return \array_key_exists($key, $_SERVER) || \array_key_exists($key, $_ENV);
     }
 
+    public static function isCiMode(): bool
```
Comment (h1k3r) [inline src/Core/DevOps/Environment/EnvironmentHelper.php:46]: **Note:** this becomes a part of public api

File: src/Core/DevOps/Environment/EnvironmentHelper.php [hunk 2]
```diff
@@ -40,6 +40,11 @@ public static function hasVariable(string $key): bool
         return \array_key_exists($key, $_SERVER) || \array_key_exists($key, $_ENV);
```
Comment (shyim) [inline src/Core/DevOps/Environment/EnvironmentHelper.php:40]: I would merge so kinda fix this. BUT directly deprecate the functionality for the next major version.

We were forced to implement this for Platform.SH but, last year we moved away because of soo much trouble of extensions complexity in customer setups because they have to copy files down and so on. Therefore to make our life easier, I would kill this feature.

The Application is in a such weird way when there is no database connection, but having then plugins also interacting there makes it much more hard. It's not worth the effort. We should rather focus more on making theme compile faster

File: src/Core/DevOps/Environment/EnvironmentHelper.php (hunk 1 above)
Comment (shyim) [reply src/Core/DevOps/Environment/EnvironmentHelper.php:46]: I would make it internal 🙈

File: src/Core/DevOps/Environment/EnvironmentHelper.php (hunk 2 above)
Comment (h1k3r) [reply src/Core/DevOps/Environment/EnvironmentHelper.php:40]: You mean deprecate offline theme compilation? I see the point, I had some fun debugging edge cases during some work on themes. But also I get the point of people wanting reproducible builds. Not sure what is planned for further themes subsystem evolution, but I have a feeling that best practice for themes should be using some type of composition approach. Theme compilation should happen in the pipeline, while changing of theme configuration should lead to regenerating of one theme_variables.css and theme_config.js files at most.

Maybe we should create an issue for that? I think this will spike some discussion, which should stay in one place.

**Review by umutdogan4291 — APPROVED** [review]

File: src/Core/DevOps/Environment/EnvironmentHelper.php (hunk 2 above)
Comment (h1k3r) [reply src/Core/DevOps/Environment/EnvironmentHelper.php:40]: for reference https://github.com/shopware/shopware/issues/14553

**Review by nfortier-shopware — APPROVED** [review]
